### ISSUE TITLE
ng build --prod --aot error "Property 'quickMenu' does not exist on type 'DashboardV1Component'"

### ISSUE THREAD

**Issue by iedwin** [ng-alain/ng-alain#1]
ng build --prod --aot failed because of lack of property "quickMenu" in DashboardV1Component.

<img width="1680" alt="screen shot 2017-08-27 at 9 47 43 pm" src="https://user-images.githubusercontent.com/17739715/29750494-10da3844-8b06-11e7-8cb9-201c6a4c1700.png">

**Comment by cipchk** [comment]
bug confirmed, tomorrow fix this. thanks.
