### ISSUE TITLE
fullscreen bug

### ISSUE THREAD

**Issue by dangzhenghui1985** [ng-alain/ng-alain#1002]
- ng-alain version: X.Y.Z
- Angular version: X.Y.Z

## 【必填项】重现链接，Reproduction link

全屏代码升级版本以后用不了了 最新版本4.20
![image](https://user-images.githubusercontent.com/16914422/55296880-15204a80-5452-11e9-9d45-e1407ffaf69a.png)
api应该是变了

**Comment by cipchk** [comment]
暂时使用，可解决。

```
"screenfull": "~4.0.0",
```

> 相关 ISSUES：https://github.com/sindresorhus/screenfull.js/issues/130

**Comment by dangzhenghui1985** [comment]
这个问题最新版本已经解决了我看 应该可以关闭了

**Comment by cipchk** [comment]
解决方案见：https://github.com/ng-alain/ng-alain/pull/1031
