### ISSUE TITLE
st组件增强过滤、搜索功能

### ISSUE THREAD

**Issue by bingyun123** [ng-alain/ng-alain#1004]
st组件能否实现通过简单配置，自动达到下图中的过滤和搜索效果？这个是DevExtreme中的功能，很简单实用。请考虑下，谢谢！
![image](https://user-images.githubusercontent.com/30248969/55380388-9c54e780-5552-11e9-96f5-d0fc9e90433b.png)
 
网址：
https://js.devexpress.com/Demos/WidgetsGallery/Demo/DataGrid/Filtering/Vue/Light/
在线示例：
https://codepen.io/anon/pen/ZZGEbV?&editable=true

**Comment by cipchk** [comment]
暂时不会考虑 `nz-table` 无法实现的功能。
