### ISSUE TITLE
ng g ng-alain:module ConstructionManagement  生成命令 import { SharedModule } from '@shared'; 自动生成的这段代码出错 应该是import { SharedModule } from '@shared/shared.module';

### ISSUE THREAD

**Issue by hennychen** [ng-alain/ng-alain#1005]
- ng-alain version: ^7.0.3
- Angular version: ^7.0.3

## 【必填项】重现链接，Reproduction link
```bash
ng g ng-alain:module ConstructionManagement
```
生成命令 

```ts
import { SharedModule } from '@shared'; 
```

自动生成的这段代码出错,应该是
```ts
import { SharedModule } from '@shared/shared.module';
```

## 重现步骤，Steps to reproduce

https://ng-alain.com/cli/generate/zh

Module 模块#
生成一个 trade 模块：

```bash
ng g ng-alain:module trade
```

会在 routes/trade 生成两个文件 trade.module.ts、trade-routing.module.ts，你无法指定不生成 *-routing.module.ts 因为这是 ng-alain 的任性。

模块内容包括了导入 SharedModule 以及一些统一性导入与导出的方式，并且你不可能破坏这些变量名（例如：COMPONENTS、COMPONENTS_NOROUNT、routes）。

**Comment by cipchk** [comment]
在 `shared/index.ts` 中已经导入 `SharedModule` [Code](https://github.com/ng-alain/ng-alain/blob/master/src/app/shared/index.ts#L7)，因此以下代码可用：

```ts
import { SharedModule } from '@shared';
```
