### ISSUE TITLE
头像展示栏这里名字不能是中文？谢谢回答！

### ISSUE THREAD

**Issue by lfzx** [ng-alain/ng-alain#1007]
当我传的名字是中文时：
![image](https://user-images.githubusercontent.com/34572392/55457136-9119be80-561b-11e9-826a-fa683f07d815.png)
当我传名字为英文时：
![image](https://user-images.githubusercontent.com/34572392/55457029-413af780-561b-11e9-87f2-e01c0d1f63c4.png)

**Comment by cipchk** [comment]
请提供重现链接

**Comment by lfzx** [comment]
用官网的例子测试了，可以显示，我的可能哪里出错了，我再看看~
不好意思~~
