### ISSUE TITLE
主题付款问题

### ISSUE THREAD

**Issue by ZenithalTechnical** [ng-alain/ng-alain#1008]
很抱歉在这里反馈问题
我通过扫码已经支付了
![image](https://user-images.githubusercontent.com/44557323/55529654-03020e80-56d5-11e9-8557-6d6eda25a426.png)
但是在支付的过程中忘记添加备注信息，订单是2019-04-04 04:08 am支付的，支付宝我有尝试通过支付宝联系收款方，暂时没有回复，请问有什么其他办法不

**Comment by cipchk** [comment]
已处理

**Comment by ZenithalTechnical** [comment]
thanks
