### ISSUE TITLE
st表格如何更新一行数据

### ISSUE THREAD

**Issue by s641135196** [ng-alain/ng-alain#1009]
st有没有方法不刷新整个表格，只更一行数据。 st表格只有删除的方法，没有更新一行的方法。

**Comment by cipchk** [comment]
`st` 的数据会经过一系列的计算，若你真的需要更新数据，我建议你直接访问 `st._data`，并调用 `st.cd()`。

注意你可能还会遇到 [数据修改后页面为什么没有更新](https://ng-alain.com/docs/faq/en#%E6%95%B0%E6%8D%AE%E4%BF%AE%E6%94%B9%E5%90%8E%E9%A1%B5%E9%9D%A2%E4%B8%BA%E4%BB%80%E4%B9%88%E6%B2%A1%E6%9C%89%E6%9B%B4%E6%96%B0)。

**Comment by s641135196** [comment]
@cipchk 经过测试，还是有问题
例如我更新第一行的数据。 
```javascript
      this.st._data[0].email = 'hello';
      this.st.cd();
```
设置的值并未更新到界面上。
后来发现是this.st.data[0]._values 参数的值未自动更新导致的。
后来我将代码更改如下，值就会更新到界面上
```javascript
      this.st._data[0].email = 'hello';
      this.st._data[0]._values[5] = {text:'hello',org: 'hello'};
      this.st.cd();
```

`console.log(this.st.data[0])的值`

![image](https://user-images.githubusercontent.com/8079013/57970894-98bdd880-79b9-11e9-8433-f5ebff1b6e21.png)


上面这样做只是测试出问题， 有什么办法解决没。
