### ISSUE TITLE
feat(abc: reuse-tab): new reuse-tab component plans!

### ISSUE THREAD

**Issue by cipchk** [ng-alain/ng-alain#101]
复用标签在中台系统非常常见，本质是不同路由页可切换且这一过程中数据不会丢失。（例如：#97 也是这个想法）

基于此理论，可能涉及以下若干方面的变更：

**Menu**

- 增加 `reuse: true` 属性表示该菜单可被复用

**LayoutComponent**

- 增加 `<reuse-tab></reuse-tab>` 组件

## 功能

- [x] 复用策略
- [x] 菜单复用策略
- [x] URL复用策略
- [x] 复用组件
    - [x] 当前页
    - [x] 历史页
    - [x] 操作区
    - ~支持右键操作~

## API

**reuse-tab**

参数 | 说明 | 类型 | 默认值
----|------|-----|------
max | 允许最多复用多少个页面，限 `2-100` | `number` | 10
excludes | 排除规则，限 `mode=URL` | `RegExp[]` | -
change | 切换时回调 | `EventEmitter` | -
close | 关闭回调 | `EventEmitter` | -

欢迎大家提供更友好的想法 :smile:。

**Comment by dusdong** [comment]
楼主的意思是一个tab对应一个路由页面吗？类似于 ext.js 或者 easyui 吗？这个强悍！目前还没见过 angular 实现的案例

**Comment by dusdong** [comment]
这个基于ext.js的前端体验很不错：
[http://core.fineui.com/#/Button/ButtonIconFont](http://core.fineui.com/#/Button/ButtonIconFont)

1、tab页右键菜单
2、右侧有最大化按钮
![tim 20171213202242](https://user-images.githubusercontent.com/3461709/33938694-651fb978-e043-11e7-8cde-db4a20165650.png)

**Comment by cipchk** [comment]
不会有花销的功能，其实我也只是一个想法，目前还没想好如何制作一个 `<reuse-tab></reuse-tab>` 符合 ANT DESIGN 理念的组件。

**Comment by blueisboy** [comment]
Content组件选项卡化呗，RouteReuseStrategy 在复用路由时，有个问题就是会冲突，两个路由体系完全不相干的页面被复用时，很难互相跳转。所以我在RouteReuseStrategy的做法是……只保持 Content组件里的路由的复用。是否复用 =route && route.parent && route.parent.component && route.parent.component instanceof LayoutComponent;

**Comment by cipchk** [comment]
@blueisboy 在路由复用这一策略上，针对不同路由路径会产生难于复用的这个问题我倒没想过。
但对于 `RouteReuseStrategy` 而言的判断标准其实是可以利用路由地址，本质上应该很容易区分。

若是 `content` 选项卡化，这有点回到 `iframe` 的世界了。
