### ISSUE TITLE
ST行事件的record对象由原来的传引用变成了传值

### ISSUE THREAD

**Issue by devsharper** [ng-alain/ng-alain#1011]
ng-alain: 7.1.0

https://github.com/ng-alain/delon/blob/ab34a44a106d9f1d69cd36d30413dc4308f27031/packages/abc/table/table.component.ts#L577

https://github.com/ng-alain/delon/blob/ab34a44a106d9f1d69cd36d30413dc4308f27031/packages/abc/table/table.component.ts#L590

可能是这两行代码的问题，上一个版本修改全局modalOptions和drawerOptions配置被覆盖的问题，deepMergeKey 复制了 modal.params.record 和 drawer.params.record 对象？

导致传进Modal或Drawer内部的record不是原始的record，而是复制出来的一个新对象，这样有很多问题，比如在Modal中修改了record，原始record没有变化，建议这里把 params 改回直接传递引用。

配置信息可以复制传值，而数据还是建议传递引用比较合理

**Comment by devsharper** [comment]
@cipchk 
https://stackblitz.com/edit/ng-alain-setup-qwrfcp

**Comment by devsharper** [comment]
很欣赏ng-alain框架，做的非常棒！但类似这种修改以后建议还是要慎重一点，升级一个小版本，改了这么重要的逻辑，影响太大了，差点被客户喷死……

**Comment by cipchk** [comment]
麻烦提供一个可重现的有效的示例。

**Comment by devsharper** [comment]
又测试了一下，我之前的理解有点偏差。

实际问题是ST的数据源data和行数据record不是同一个对象，在初始化表格时有深拷贝？

也就是说，之前旧版本中如果在子页面Modal中修改了record.x，那么父页面中的ST数据源 data: STData[] 也会变。从7.0.3开始，只有行数据 click: record => { ... } 这里的record.x变了，而原始数据源data: STData[] 不变，仍然是原始数据。可以再看一下上面的示例。

不明白为什么改成这样了，有时间我再研究一下源代码吧

**Comment by cipchk** [comment]
你提供的重现示例并没有重现出你所说的问题，老实说至今为至我完全不明白你在讲什么。

**Comment by devsharper** [comment]
@cipchk 
= =!!   我再解释几句……

假设有一个ST数据源，只有一条数据：

data: STData[] = [ { id: 1, name: '1111' } ];

绑定到ST，只有一行，在这一行的“编辑”按钮中，把record传入Modal内，旧版本中，这个record就是 data[0]，如果在Modal内修改了 record.name，关掉Modal以后会发现 data[0].name 也变了，因为record和data[0]实际上就是同一个对象

但7.0.3以后，传入Modal的record（ 即params: record =>({ .... }) 这里的record参数），不是 data[0] 了，而是根据 data[0] 的值复制出来的另一个对象，在Modal内修改 record.name，data[0].name 不会变。

这样说清楚了没？

这倒也不算什么bug，只是说这个逻辑变化比较大，在Modal中不能直接修改ST的源数据了。

比如有这样的场景，有一个订单Order，包含多个子订单项 OrderItem[]，子订单项绑定到ST，以前我会通过ST每一行的“编辑”，打开Modal编辑一个OrderItem，编辑之后关闭，不用再做任何处理，对应的OrderItem已经改好了。现在新版中，只能在Modal关闭之后的click: record => {....}中手写代码，用record的值向原始的OrderItem回写赋值

不知道有没有说明白？

算了，这个无所谓了，你如果觉得不用改就关了吧

**Comment by devsharper** [comment]
现在ST每一行的record并不是原始的data[x]，而是复制了一个，并且添加了其他一些辅助字段？

我是建议这里不要深拷贝复制STData，而是直接引用原始的STData对象。原因有两点，一是上边说的这个问题，二是有时复杂表格的数据源  STData[] 可能很大，尤其是表格显示行数很多时，复制一份完全没必要，影响性能，占内存

**Comment by cipchk** [comment]
我建议你好好按 issues 的格式来，我真的无法理解，也许你的说法太过于理论，感觉太复杂了，能否提供一个重现问题的所在，以及你期望的结果应该是什么的示例。

**Comment by devsharper** [comment]
无语 = =!!  

我上边写了那么多，兄弟你是不是根本没仔细看啊？

上边最长的那个回复，说的还不够清楚？？如果你连这个都看不明白，我不相信你能写出这个框架。

非让我重现，我的重现代码里边其实也写了，你仔细看看那几个message.info(...)，这个问题只能用语言描述，我即使写200行代码给你重现，最后也还是要用语言描述，否则根本说不清楚。

说实话项目做得不错，确实能提高效率、节省时间。即使我根本不用Pro还是特意买了一个支持你。但你能不能认真讨论问题，仔细看看别人的观点？别总是一种命令的语气告诉别人按照你的规矩来？

无所谓了，改不改是你的权利，你决定

**Comment by cipchk** [comment]
放个DEMO点进点弹出一个 edit 点确定什么都没有，鬼知道你在鬼扯干什么 。

干，你爱用不用，PRO 我光明正大的放上去的，你爱支持不支持，凭什么我需要浪费时间，我很忙好吗？别TM这么无聊，把问题扯那么远。

**Comment by devsharper** [comment]
github用了这么多年，看了无数项目，牛逼成你这样的作者我还真是第一次见……

跟你讨论问题，连看都不看的，只会教训人骂街啊……牛逼！

你忙吧，祝你的项目越做越好^_^  继续老铁，你可以的

**Comment by cipchk** [comment]
你有种说出2天前我看到 https://stackblitz.com/edit/ng-alain-setup-qwrfcp 那时的版本是怎么样的吗？

你这种人就该骂，什么叫【即使我根本不用Pro还是特意买了一个支持你】，讨论归讨论何必扯到金钱上，你不觉得你非常无聊吗？

**Comment by devsharper** [comment]
这个问题我一开始就认为用代码不好表达，说不清，最初那个版本的重现代码，我给你写了大段的注释，主要就是为了让你看注释的，注释里边解释的很清楚了，你非说看不懂，你认真看了吗？？

还有上边最长的那段回复，也是你说了好几次看不懂，我又耐心给你写的，你仔细看了吗？那都已经不是技术语言了！我是用给非技术人员讲课的方式说的，连不懂技术的产品经理都能看懂吧？？你如果真的认真看了，还看不懂，我把键盘吃了！这样沟通有什么意思呢？

后来我也说了，这不算一个bug，只是一个比较大的代码逻辑改变，对于旧代码可能会有比较大的影响，这是探讨问题，你连这点耐心都没有，只会教训别人按你的规矩来写issue，什么毛病？？

你的时间是时间，我的时间就不是？你知道写这些issue、准备重现代码，花了我多少时间？如果我自私一点，我大可以发现问题以后不吭声，自己改一下自己项目的代码就完事了，因为这个问题我已经找到解决方案了，并不需要你提供什么帮助！之所以花时间发到这里，更多的原因是希望其他人遇到类似问题时能找到，有个参考。

开源共享的意义是什么？我愿意花时间写，愿意帮你完善项目，你却不愿意花时间看？那你做个屁开源！

**Comment by cipchk** [comment]
滚

**Comment by devsharper** [comment]
哈哈哈   好好，我滚

扯到钱无聊？你敢卖Pro，有问题不认真听客户反馈，还不让说，哈哈哈。

当婊子还要立牌坊，说的就是你这样的了

你要是个爷们就别删，放着吧，让大家看看
