### ISSUE TITLE
SF date widget指定format包含time时表单验证不能识别初始值

### ISSUE THREAD

**Issue by devsharper** [ng-alain/ng-alain#1013]
- ng-alain version: 7.1.0

当date widget指定 format: 'date-time' 时，SF表单验证不能识别初始值/默认值，必须再点击一次，选择一个日期/时间，表单验证才能通过

重现链接：
https://stackblitz.com/edit/ng-alain-setup-chr5tj

**Comment by cipchk** [comment]
![image](https://user-images.githubusercontent.com/2987467/55693742-e28aca80-59da-11e9-998e-25800e04449f.png)

我打开以后直接这样子显示，我不清楚什么是【不能识别初始值/默认值】，请告知具体的重现步骤。

**Comment by devsharper** [comment]
@cipchk 
如果这个dateTime类型的字段是必填，页面初始化时已经给表单赋值了（比如编辑修改的场景），或者没有赋值但给它定义了default值，这个字段是有值的，它的值也能正常显示出来，但是表单状态仍然是无效，提交按钮不可用。必须手动点开日历框，再重新选择一下日期时间，重新给它赋值，表单状态才能变成有效。  只有日期没有时间的date则不存在此问题

**Comment by cipchk** [comment]
@devsharper 能否提供可重现示例和步骤，我真的无法理解你的问题所在。

**Comment by devsharper** [comment]
@cipchk 

重现代码已经改了，再看一下。

两个表单的字段都有值，为什么第一个提交可用，第二个提交不可用？
把第二个点开，重新选一下日期时间，提交就可用了。

第一个应该是合理的，第二个未识别初始值

**Comment by cipchk** [comment]
请认真阅读 [注意事项](https://ng-alain.com/form/date/zh#%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9)，日期务必遵守  RFC3339 格式。
