### ISSUE TITLE
st组件支持对Expand列的自定义

### ISSUE THREAD

**Issue by tky753** [ng-alain/ng-alain#1014]
![](https://s2.ax1x.com/2019/04/08/A42jJS.png)
或者提供开关，能够不显示默认的expand关联列。

**Comment by cipchk** [comment]
目前没有办法，`expand` 是 `nz-table` 的固定写法。

**Comment by tky753** [comment]
能否加个开关不显示，然后让使用者自定义一列，通过 [**render**] 和 [**renderTitle**] 来自己画?

**Comment by cipchk** [comment]
我建议你使用 `nz-table` 来实现你的需求，是可以实现的。
