### ISSUE TITLE
page-header的autoTitle属性不起作用

### ISSUE THREAD

**Issue by tangjwtj** [ng-alain/ng-alain#1016]
- ng-alain version: 7.0.2
- Angular version: 7.3.6

## 【必填项】重现链接，Reproduction link
代码片断：
<page-header [autoTitle]="false"  ></page-header>

预期只显示导航条，不单独显示标题，实际结果如下图：

![image](https://user-images.githubusercontent.com/12179772/55781497-d9822200-5adc-11e9-9767-67ccf5b29c2b.png)

通过查看page-header组件的源码， 在设置标题的时候， 有以下判断：
   private setTitle() {
    if (
      typeof this._title === 'undefined' &&
      typeof this._titleTpl === 'undefined' &&
      this.autoTitle &&
      this.menus.length > 0
    ) {
      const item = this.menus[this.menus.length - 1];
      let title = item.text;
      if (item.i18n && this.i18nSrv) title = this.i18nSrv.fanyi(item.i18n);
      this._titleVal = title;
    }

在autoTitle为false的情况下，应当是不会设置_titleVal的值， 但不知道为何，没有生效。

**Comment by Gotham-Joker** [comment]
说实话这个title确实很多余，你应该先找到src/app/delon.module.ts文件，然后找到这个以下函数：

export function fnPageHeaderConfig(): PageHeaderConfig {
  return {
    ...new PageHeaderConfig(),
    ...{ homeI18n: 'home' } as PageHeaderConfig
  };
}

做以下改动 ...{ homeI18n: 'home' }  => ...{homeI18n: 'home', autoTitle: false}

**Comment by tangjwtj** [comment]
> 说实话这个title确实很多余，你应该先找到src/app/delon.module.ts文件，然后找到这个以下函数：
> 
> export function fnPageHeaderConfig(): PageHeaderConfig {
> return {
> ...new PageHeaderConfig(),
> ...{ homeI18n: 'home' } as PageHeaderConfig
> };
> }
> 
> 做以下改动 ...{ homeI18n: 'home' } => ...{homeI18n: 'home', autoTitle: false}

有效，非常感谢，完全不知道，在这还藏着个需要设定的。
