### ISSUE TITLE
st 表格中STColumn的width不起作用

### ISSUE THREAD

**Issue by tangjwtj** [ng-alain/ng-alain#1018]
- ng-alain version: 7.1.0
- Angular version: 7.2.11

## 【必填项】重现链接，Reproduction link

https://stackblitz.com/edit/ng-alain-setup-qoxwad

## 重现步骤，Steps to reproduce
设置email字段宽度为20，文本超出截取并加 ... 
实际显示了全部的email信息

**Comment by cipchk** [comment]
这是一个老问题，但由于 `st` 使用量比较大，为了保持兼容性，新增 `widthMode` 配置性（可全局性配置），来决定列描述 `width` 的渲染方式。

例如：

```ts
columns: STColumn[] = [
    { title: '编号', index: 'id', width: 80 },
    { title: '头像', type: 'img', width: 60, index: 'picture.thumbnail' },
    { title: '邮箱', index: 'email', width: 80 },
    { title: '电话', index: 'phone' },
    { title: '注册时间', type: 'date', index: 'registered' },
  ];
```

其中，若设置 `[widthMode]="{type: 'strict'}"`，则上述的前三列会认为是严格模式，若 email 超过 `80` 则强制设置为截短。

**Comment by allenlongbaobao** [comment]
@cipchk  请问 `widthMode` 如何进行全局配置？在 [官网全局参数](https://ng-alain.com/theme/global/zh#%E8%A1%A8%E6%A0%BC) 中没有找到对应的配置项。

**Comment by cipchk** [comment]
@allenlongbaobao https://github.com/ng-alain/delon/blob/master/packages/abc/table/table.config.ts#L143

**Comment by allenlongbaobao** [comment]
@cipchk  thank you

**Comment by allenlongbaobao** [comment]
@cipchk 升级为 `7.7.1` 之后， `widthMode` 声明为 ： 

```
/* 表格宽度模式 */
  widthMode: STWidthMode = {
    type: 'strict',
    strictBehavior: 'truncate',
  }
```

表格并不会截断超出宽度的字符，之前是 `7.3.0` 版本是可以的。可以帮忙看一下吗

**Comment by allenlongbaobao** [comment]
@cipchk 因为我对 st 做了自定义样式覆盖，其中有一个类名 在更新后不存在后，因此影响到了。打扰了。
