### ISSUE TITLE
sf在search模式下若enum初始为空，则formSubmit不触发。

### ISSUE THREAD

**Issue by KellenHe** [ng-alain/ng-alain#1019]
- ng-alain version: 7.0.1
- Angular version: 7.2.0

## 【必填项】重现链接，Reproduction link
https://stackblitz.com/edit/ng-alain-setup-7paqxe?file=src/app/app.component.ts

## 重现步骤，Steps to reproduce
      portfolio: {
        type: 'string',
        title: '预警范围',
        enum: [],
        ui: {
          widget: 'select',
          mode: 'multiple',
          allowClear: true
        }
      }

sf中使用select，enum数据从后台获取，发现后台若返回空，则enum=[]的情况下，formSubmit事件不会触发。

**Comment by cipchk** [comment]
抱歉，没明白你的意思，能否提供一下更详细的重现示例和步骤。

**Comment by KellenHe** [comment]
schema: SFSchema = {
    properties: {
      portfolio: {
        type: 'string',
        title: '预警范围',
        enum: [],
        ui: {
          widget: 'select',
          mode: 'multiple',
          allowClear: true
        }
      },
      name: {
        type: 'string',
        title: 'Name',
        ui: {
          addOnAfter: 'RMB',
          placeholder: 'RMB结算'
        }
      }
    },
    ui: {
      spanLabelFixed: 75,
      grid: {
        span: 6
      }
    }
  };
sf使用上面的schema，点击提交按钮事件没有触发。
测试发现主要是enum没有初始值导致的。
![image](https://user-images.githubusercontent.com/9713892/56103883-99e98900-5f67-11e9-8ed9-e98df1fb62a4.png)

**Comment by cipchk** [comment]
@KellenHe 抱歉，我依然无法理解，麻烦提供一个具体的重现步骤（例如：第一步做什么，第二步做什么），结果应该怎么样，但实际又是怎么样？

**Comment by KellenHe** [comment]
好的
1. 设置sf [schema]="schema", 使用上面的schema代码。
2. 点击搜索按钮

期望结果：点击搜索按钮，触发绑定的submit事件。
实际结果：点击搜索按钮无效，submit事件没有触发。

HTML：
`  <sf #sf [mode]="'search'" [schema]="searchSchema" [button]="searchButton" (formSubmit)="submit($event)">
  </sf>`
ts:
`  searchSchema: SFSchema = {
    properties: {
      portfolio: {
        type: 'string',
        title: '预警范围',
        enum: [],
        ui: {
          widget: 'select',
          mode: 'multiple',
          allowClear: true
        }
      },
      date: {
        type: 'string',
        title: '预警时间',
        ui: {
          widget: 'date',
          mode: 'range'
        },
        format: 'date',
        default: [format(new Date(new Date().getTime() - 7 * 24 * 3600 * 1000), 'YYYY-MM-DD'), format(new Date(), 'YYYY-MM-DD')]
      },
      keyword: {
        type: 'string',
        title: '搜索'
      },
      important: {
        type: 'string',
        title: '严重程度',
        enum: [
          { label: '高', value: 3 },
          { label: '中', value: 2 },
          { label: '低', value: 1 },
          { label: '无', value: 0 }
        ],
        ui: {
          widget: 'checkbox'
        }
      }
    },
    ui: {
      spanLabelFixed: 75,
      grid: {
        span: 6
      }
    }
  };
  searchButton: SFButton = {
    render: {
      class: 'searchButton'
    }
  };`

**Comment by KellenHe** [comment]
测试发现是使用了select组件，但是select的enum设置为空导致点击搜索按钮无效。

**Comment by cipchk** [comment]
JSON Schema 对 `enum` 规定必须至少包含一项，否则会产生 `minItems` 异常，这一点你可以打开 `debug` 可以了解得到。

有两个解决办法：

一、把 `minItems` 加入 `ingoreKeywords` 列队中，忽略这种错误。
二、待 `enum` 数据加载后再初始化，或者使用 `asyncData` 来加载异步数据。

**Comment by KellenHe** [comment]
使用的方法
一、把 minItems 加入 ingoreKeywords 列队中，忽略这种错误。
完美解决，谢谢
