### ISSUE TITLE
sf的format使用time类型，validation失败

### ISSUE THREAD

**Issue by ayaka209** [ng-alain/ng-alain#1022]
- ng-alain version: 最新
- Angular version: 7.1.4

## 【必填项】重现链接，Reproduction link
https://ng-alain-setup-nbkka3.stackblitz.io

## 重现步骤，Steps to reproduce
在两个不同框选择时间，一个提示格式问题，一个没问题

（虽然可能文档上加一笔也就行了？）

**Comment by cipchk** [comment]
一个已经的问题，`sf` 目前 JSON Schema 采用的是 draft 7 版本，对于这个版本的 `format: 'time'` 必须包含时区，即 `08:08:08+00:00` 的格式，因此要解决格式问题，目前只能在此基础格式化的基础上加上时区，例如：

```ts
time1: {
  type: 'string',
  title: '有问题的，选择时间后验证不对',
  format: 'time',
  ui: {
    format: `HH:mm:ss+00:00`,
  },
},
```

而对于后者，因为无指定 `format`，所以当作普通字符串处理，因此无格式问题。
