### ISSUE TITLE
sf在一些情况下更改了一个属性的值，会把某些属性给清空

### ISSUE THREAD

**Issue by zmzimpl** [ng-alain/ng-alain#1026]
- ng-alain version: 7.2.0
- Angular version: 7

## 【必填项】重现链接，Reproduction link
https://stackblitz.com/edit/angular-rxpwjm

## 重现步骤，Steps to reproduce
在重现链接中先选择发布日期，再输入任务名称，会把publishMonth和publishDay两个属性的值清空

**Comment by cipchk** [comment]
直接使用 `sf.value.xxx` 作为绑定对象，会被清除，是因为 `sf` 在校验过程中会实时重置 `value` 值。

将自定义部件的绑定独立另一个变量，并根据 `ngModelChange` 重新刷新某个部件的值。

一个示例：https://stackblitz.com/edit/angular-rxpwjm-dkyw8b?file=src/app/app.component.ts

> 建议将发布日期重新定制为小部件，这样可以进行复用。

**Comment by zmzimpl** [comment]
> 直接使用 `sf.value.xxx` 作为绑定对象，会被清除，是因为 `sf` 在校验过程中会实时重置 `value` 值。
> 
> 将自定义部件的绑定独立另一个变量，并根据 `ngModelChange` 重新刷新某个部件的值。
> 
> 一个示例：https://stackblitz.com/edit/angular-rxpwjm-dkyw8b?file=src/app/app.component.ts
> 
> > 建议将发布日期重新定制为小部件，这样可以进行复用。

完美解决，非常感谢~
