### ISSUE TITLE
sf select 未显示选中项

### ISSUE THREAD

**Issue by seightday** [ng-alain/ng-alain#1027]
- ng-alain version: 7.2.0
- Angular version: 7.2.13

## 【必填项】重现链接，Reproduction link
https://stackblitz.com/edit/angular-rxpwjm-nnpwnr

## 重现步骤，Steps to reproduce
在重现链接中下拉选择任务，任务不会显示出来，点击提交弹出信息显示已选中任务信息

**Comment by cipchk** [comment]
`interval` 是一个时间操作符，你试着把 `50` 换成 `5000` 你就明白了。
