### ISSUE TITLE
@delon/form upload加入默认ui.remove方法移除该上传文件,如果自己有写就覆盖掉

### ISSUE THREAD

**Issue by jerrytang67** [ng-alain/ng-alain#1028]
@delon/form upload加入默认ui.remove方法移除该上传文件,如果自己有写就覆盖掉

**Comment by cipchk** [comment]
@jerrytang67 抱歉，不明白你的意思。

**Comment by jerrytang67** [comment]
就比如现在的官方实例
https://ng-alain.com/form/upload/zh
不是有个xxx.png的文件么.点删除把他删除了提交,结果里还是有,
就是默认做个移除的,不用自己再去做

**Comment by jerrytang67** [comment]
我现在的的项目中在修改了delon的form上传组件,当没有指定ui.remove时,加了默认的ui.remove方法 .不知道别人需不需要
