### ISSUE TITLE
ng-alain样式与bootstrap有冲突

### ISSUE THREAD

**Issue by tangjwtj** [ng-alain/ng-alain#1030]
- ng-alain version: 7.2.0
- Angular version: 7.2.13

## 【必填项】重现链接，Reproduction link
https://stackblitz.com/edit/ng-alain-setup-l6z1jr
加载bootstrap前
![image](https://user-images.githubusercontent.com/12179772/56334556-5d1dcc00-61cb-11e9-8045-229a4561b513.png)
加载bootstrap后
![image](https://user-images.githubusercontent.com/12179772/56334572-6c047e80-61cb-11e9-842a-5ac814401e2f.png)

**Comment by cipchk** [comment]
肯定的，ng-zorro 有自己的一套 UI 样式风格，这与 bootstrap 会有一些冲突。主要还是一些全局的样式，你只能自己修正。

事实上，有 ng-alain 也包含一套类似 bootstrap 的工具类样式，我想可以满足大部分的需求，当然如果你在 ng-zorro 里包含引用一些 bootstrap 组件，而导致必须引用 bootstrap 那我就没办法，你只能自己修正这种小细节。
