### ISSUE TITLE
screenfull.isFullscreen 属性找不到

### ISSUE THREAD

**Issue by lizhen** [ng-alain/ng-alain#1035]
- ng-alain version: 7.2.0
- Angular version: 7.3.8

## 【必填项】重现链接，Reproduction link
![snipaste_20190422_111029](https://user-images.githubusercontent.com/248860/56481002-45a65200-64ef-11e9-8110-52b5c1c3a243.png)

## 新创建的项目，启动时报screenfull下的isFullscreen、enabled、toggle()属性不存在：
ERROR in src/app/layout/default/header/components/fullscreen.component.ts(20,30): error TS2339: Property 'isFullscreen' does not exist on type 'false | (Screenfull & { default: false | (Screenfull & ...); })'.
  Property 'isFullscreen' does not exist on type 'false'.
src/app/layout/default/header/components/fullscreen.component.ts(25,20): error TS2339: Property 'enabled' does not exist on type 'false | (Screenfull & { default: false | (Screenfull & ...); })'.
  Property 'enabled' does not exist on type 'false'.
src/app/layout/default/header/components/fullscreen.component.ts(26,18): error TS2339: Property 'toggle' does not exist on type 'false | (Screenfull & { default: false | (Screenfull & ...); })'.
  Property 'toggle' does not exist on type 'false'.

**Comment by cipchk** [comment]
duplcated of https://github.com/ng-alain/ng-alain/pull/1031
