### ISSUE TITLE
st表格，内容行隐藏了标题

### ISSUE THREAD

**Issue by zhhhc** [ng-alain/ng-alain#1038]
- ng-alain version: 7.2.0
- Angular version: 7.213

## 重现步骤，Steps to reproduce
![image](https://user-images.githubusercontent.com/20251916/56556072-85416c80-65c9-11e9-9253-aa4c8386f679.png)

如上图，表格body的td里都隐藏了标题的内容。

**Comment by cipchk** [comment]
这是响应时的标题，在小屏幕下才会启用。
