### ISSUE TITLE
nz-table无法触发nzDataChange

### ISSUE THREAD

**Issue by xbu** [ng-alain/ng-alain#104]
nz-table选择nzAjaxData分页加载数据，无法触发nzDataChange方法，我拿table页面的ajax例子试了下也无法触发。

但是在nzDataSource加载时候可以

不知道这算不算issue，还是nzDataChange只能和nzDataSource配合使用

**Comment by cipchk** [comment]
`nz-*` 开头的组件，都属于 https://github.com/NG-ZORRO/ng-zorro-antd，请至那边提交相应 issue。
