### ISSUE TITLE
ST表格，paging问题

### ISSUE THREAD

**Issue by zhhhc** [ng-alain/ng-alain#1041]
- ng-alain version: 7.2.0
- Angular version: 7.2.13

## 【必填项】重现链接，Reproduction link

https://stackblitz.com/edit/ng-alain-setup-kuajv8

## 重现步骤，Steps to reproduce
前提：table采用后端分页，数据量为3页
1. 每页10条数据，选择第三页。
2. 改变每页条数为20条。
此时本应该触发一次table的change事件（到后台请求一次数据），结果触发了两次。
第一次：type=ps, pi=3, ps=20
第二次：type=pi, pi=2, ps=20  
试了一下, 总页数为4页时也发生同样的问题，页数多时好像没有这个问题。

**table代码**  后端分页
<st #st [columns]="columns" [data]="data" [total]="total" [loading]="loading" (change)="stChange($event)"
    [page]="{front:false,showSize:true}">
</st>

stChange(e: STChange) {
    switch (e.type) {
      case 'pi':
        this.getData();
        break;
      case 'ps':
        this.getData();
        break;
    }
  }

**Comment by zhhhc** [comment]
**重现链接**
https://stackblitz.com/edit/ng-alain-setup-kuajv8

操作步骤：
1. 选择第三页
2. 将每页显示条数，由10条/页 改为 20条/页

现象：
1. 最终页码停留在第二页
2. 控制台会打印两条日志，触发了ps 和 pi 两个事件。

**Comment by cipchk** [comment]
根据上述步骤，我只看到两条：
- 触发 `pi` 切换至第2页
- 触发 `ps` 调整页数为 20

![image](https://user-images.githubusercontent.com/2987467/56723782-34be4080-677c-11e9-9d74-e85fb2170866.png)

这是正常现象的呀。

**Comment by zhhhc** [comment]
看你的log，你应该是执行下面的操作
1. 选择**第二页**
2. 调整条数为20
这个步骤是没问题的。

有问题的步骤是
1. 选择**第三页**
2. 调整条数为20

**Comment by cipchk** [comment]
忽略 `ps` 的数据加载，目前 `nz-table` 的确在切换页数时会发生 `nzPageSizeChange` 和 `nzPageIndexChange` 事件（相关讨论：[#601](https://github.com/NG-ZORRO/ng-zorro-antd/issues/601), [#3279](https://github.com/NG-ZORRO/ng-zorro-antd/issues/3279)），内置的 `url` 也将忽略 `ps` 切换时数据的重新加载，以保持一致性。

**Comment by ayaka209** [comment]
ps修改后，不重新reload之后就变得比较奇怪了
见https://stackblitz.com/edit/ng-alain-setup-xzagtq
下面的这个自己做的select（不是st内置的分页器）
可以见到：
ps修改之后，页数选项变了，但因为没有reload所以数据还是那些条
