### ISSUE TITLE
ST表格，reload后的滚动条

### ISSUE THREAD

**Issue by zhhhc** [ng-alain/ng-alain#1042]
- ng-alain version: 7.2.0
- Angular version: 7.2.13

## 重现步骤，Steps to reproduce
ST表格中有编辑按钮，打开modal，点击保存按钮后。执行reload。
页面刷新正常，滚动条位置不正常。
本应该改变table本身的滚动条，却改变了table外部的div滚动条。
滚动条滚动后，table在div的最顶端。（top=0）

代码如下
![image](https://user-images.githubusercontent.com/20251916/56672383-f166c200-66e8-11e9-9cac-4bd9d331922d.png)

**Comment by cipchk** [comment]
长时间无提供重现链接，暂时关闭，若有进一步信息再次打开。
