### ISSUE TITLE
ScrollService.scrollToElement方法在nz-drawer中失效

### ISSUE THREAD

**Issue by ZeyZhang** [ng-alain/ng-alain#1043]
🚨 Issues 是用于BUG、Feature、进度追踪 🚨
🚨 The issue tracker is not for questions 🚨

如果有任何问题，可在以下方式获得答案：

- https://ng-alain.com/
- QQ Group：316911865
- https://segmentfault.com/t/ng-alain

在nz-drawer中使用scrollToElement方法控制body的滚动条，没有任何反应。
在body内使用scrollToElement时有效

**Comment by cipchk** [comment]
长时间无提供重现链接，暂时关闭，若有进一步信息再次打开。
