### ISSUE TITLE
ST表格指定scroll.y后列头和内容不对齐

### ISSUE THREAD

**Issue by erupts** [ng-alain/ng-alain#1044]
![image](https://user-images.githubusercontent.com/20358088/56710403-910f6900-6758-11e9-87eb-ff6415e4cea1.png)

**Comment by nita22** [comment]
同发现有这个问题，请问您解决了吗

**Comment by screamsyk** [comment]
how did you fix this?

**Comment by alicksnake22** [comment]
how did you fix this?
