### ISSUE TITLE
STColumn中button打开对话框，使用modalOptions属性后，size属性不生效

### ISSUE THREAD

**Issue by zhhhc** [ng-alain/ng-alain#1045]
- ng-alain version: 7.2.0
- Angular version: 7.2.0

## 【必填项】重现链接，Reproduction link

https://stackblitz.com/edit/ng-alain-setup-xkucbq

## 重现步骤，Steps to reproduce
同时制定size和modalOptions属性， size属性不生效
modal: {
    component: ProBasicListEditComponent,
    size: 'sm',
    modalOptions: { nzWrapClassName: 'modal__center' }
},

**Comment by cipchk** [comment]
临时解决办法，取消 `size` 并使用 `model-sm` 来代替：

```
modalOptions: { nzWrapClassName: 'modal-sm modal__center' }
```

**Comment by zhhhc** [comment]
好的，谢谢。
