### ISSUE TITLE
DrawerHelper 抽屉辅助类创建的标题不会固定在顶部

### ISSUE THREAD

**Issue by C-racker** [ng-alain/ng-alain#1046]
- ng-alain version: 7.2.0
- Angular version: 7.2.0

## 【必填项】重现链接，Reproduction link
https://stackblitz.com/edit/ng-alain-setup-euh8nx?file=src%2Fapp%2Fopen.component.html
![截图](https://user-images.githubusercontent.com/20217449/56716861-eb66f480-676d-11e9-92ea-9b2438ceb18e.png)

## 重现步骤，Steps to reproduce
还有，能否添加nzOnClose事件？目前是创建的抽屉，无法获取点击右上角关闭和抽屉以外的事件。

**Comment by cipchk** [comment]
1、试着增加 `nzPlacement: 'right'`，可能是缺少默认值，当 `drawerOptions` 存在时。
2、暂时不支持。

**Comment by C-racker** [comment]
> 1、试着增加 `nzPlacement: 'right'`，可能是缺少默认值，当 `drawerOptions` 存在时。
> 2、暂时不支持。

那我右上角的关闭按钮通过什么方法监听呢？

**Comment by cipchk** [comment]
@C-racker 下一版本会新增 `extra` 属性，用于表示不管哪种关闭都可以接收到回调

**Comment by C-racker** [comment]
> @C-racker 下一版本会新增 `extra` 属性，用于表示不管哪种关闭都可以接收到回调

太给力了，感谢~！！
