### ISSUE TITLE
G2数据动态刷新

### ISSUE THREAD

**Issue by SoraYY** [ng-alain/ng-alain#1047]
🚨 Issues 是用于BUG、Feature、进度追踪 🚨
🚨 The issue tracker is not for questions 🚨

g2-能够跟随后端数据动态重绘？

- https://ng-alain.com/
- QQ Group：316911865
- https://segmentfault.com/t/ng-alain

**Comment by cipchk** [comment]
是的，有问题请提供一个可重现示例。

**Comment by SoraYY** [comment]
就是用了G2插件，然后初始化的时候画了一个图表，然后通过http请求了新的后台数据，然后想要重新根据新数据去重绘这个图表，没找到对应的API

**Comment by cipchk** [comment]
@SoraYY 当前可以，但我不知道你具体在指哪个G2组件，这个过程到底出了什么错误而无法达到期望；无法达到期望的，需要重现链接与步骤。

> 或者加群：316911865

**Comment by SoraYY** [comment]
`<g2-timeline #g2  title="收入曲线增长图" position="bottom" [data]="chartData" [titleMap]="detailSchema" [height]="400" [delay]="500" ></g2-timeline>`
就是折线组件，在http请求完成后就重新改变了charData数据，然而不知道要怎么重绘当前折线图

**Comment by cipchk** [comment]
@SoraYY 一个可用的示例：https://stackblitz.com/edit/angular-ecu3t6?file=src/app/app.component.ts

**Comment by SoraYY** [comment]
给的示例无法运行起来..

**Comment by cipchk** [comment]
@SoraYY 
![a](https://user-images.githubusercontent.com/2987467/56898988-efc04400-6ac4-11e9-9ce7-9509f4e66afc.gif)

**Comment by Ryuchen** [comment]
请问一下，g2-bar 这个内置图表，是否也支持同样的操作？
目前我更新了数据，但是图表没有进行刷新动作

**Comment by Ryuchen** [comment]
已经按照如下尝试了，g2-bar的图表不能刷新，希望能够加入更新的动作

```
@Component({
  selector: 'app-piechart',
  template: `
    <nz-card [nzTitle]="enrollTitle" [nzBordered]="false" class="mb-lg project-list">
      <g2-bar height="200" [data]="salesData"></g2-bar>
    </nz-card>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class BarchartComponent implements OnInit {
  salesData: any[] = [];

  genData(): void {
    const res = new Array(12).fill({}).map((_i, idx) => ({
      x: `${idx + 1}月`,
      y: Math.floor(Math.random() * 1000) + 200,
    }));

    this.salesData = res;

    setTimeout(() => this.genData(), 1000 * 3);
  }

  ngOnInit(): void {
    this.genData();
  }

  constructor(private http: _HttpClient, private cdr: ChangeDetectorRef, public college: CollegeService) {}

  get enrollTitle() {
    return `${this.college.academy}历年招生`;
  }
}
```
