### ISSUE TITLE
ViewDestroyedError: Attempt to use a destroyed view: detectChanges

### ISSUE THREAD

**Issue by zdxxxxxx** [ng-alain/ng-alain#1048]
- ng-alain version: 7.0.2
- Angular version: 7.1.0

## 【必填项】重现链接，https://stackblitz.com/edit/ng-alain-setup-w49okh1-z93t3w?file=src/app/app.component.ts

![image](https://user-images.githubusercontent.com/16288673/56724389-7b606a80-677d-11e9-9576-e155ba5b241e.png)

## 重现步骤，Steps to reproduce
select切换选项，会看到报错信息

**Comment by cipchk** [comment]
@zdxxxxxx 重现链接无法打开了。

**Comment by zdxxxxxx** [comment]
@cipchk 重现链接更新了
