### ISSUE TITLE
SFSchema条件类， 组件有默认值时，会触发校验

### ISSUE THREAD

**Issue by zdxxxxxx** [ng-alain/ng-alain#1050]
- ng-alain version: 7.0.2
- Angular version: 7.1.0

## 【必填项】重现链接，Reproduction link
https://stackblitz.com/edit/ng-alain-setup-w49okh1?file=src%2Fapp%2Fapp.component.ts

![image](https://user-images.githubusercontent.com/16288673/56730759-49560500-678b-11e9-9600-f674309db4b2.png)

## 重现步骤，Steps to reproduce
当有default值时，就会触发校验
这样组件第一次渲染就显示error了

**Comment by cipchk** [comment]
的确会有这种情况，原因是 `sf` 的机制导致的，`sf` 会先渲染整个（不管是否符合条件）表单一遍，最后才做一次条件判断并重新渲染这一部分相关的表单元素，从而导致第二次发生渲染时显示错误信息。

出于目前版本机制的因素，我无法去改变它。
