### ISSUE TITLE
<st> column render  ng-template,  let-column retrun object just like let-item

### ISSUE THREAD

**Issue by qy8502** [ng-alain/ng-alain#1053]
- ng-alain version: 7.3.0
- Angular version: 7.2.12

## 重现链接，Reproduction link :
[https://ng-alain-setup-9fa19p.stackblitz.io]( https://ng-alain-setup-9fa19p.stackblitz.io)

## 重现步骤，Steps to reproduce
```
 columns: STColumn[] = [
    { title: '编号', index: 'id' },
    { title: '头像', type: 'img', width: 50, index: 'picture.thumbnail' },
    { title: '邮箱', index: 'email' },
    { title: '电话', index: 'phone', render: 'phoneTpl'},
    { title: '注册时间', type: 'date', index: 'registered' },
  ];
```
```

<st [data]="url" ps="2" [req]="{params: params}" [columns]="columns">
 <ng-template st-row="phoneTpl" let-column let-item >
      {{column| json}} 
</ng-template>
</st>

```
![QQ截图20190428095326](https://user-images.githubusercontent.com/2696897/56857097-cf489a80-699b-11e9-9df4-3688dc77e3fb.jpg)

**Comment by cipchk** [comment]
You must use `let-column="column"` to get the value, pls refer to angular.io.

**Comment by qy8502** [comment]
![image](https://user-images.githubusercontent.com/2696897/56857287-35ceb800-699e-11e9-8c85-ce719d58032c.png)
 Thanks lot.
