### ISSUE TITLE
请问一下ng-alain加载层的属性是那个？

### ISSUE THREAD

**Issue by smileTaylor** [ng-alain/ng-alain#1056]

**Comment by cipchk** [comment]
@smileTaylor 什么是加载层？

**Comment by smileTaylor** [comment]
------------------ 原始邮件 ------------------
发件人: "卡色"<notifications@github.com>; 
发送时间: 2019年4月29日(星期一) 晚上6:18
收件人: "ng-alain/ng-alain"<ng-alain@noreply.github.com>; 
抄送: "微笑面对生活"<1920515792@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [ng-alain/ng-alain] 请问一下ng-alain加载层的属性是那个？ (#1056)



@smileTaylor 什么是加载层？

**Comment by smileTaylor** [comment]
@cipchk 
![image](https://user-images.githubusercontent.com/40836686/56948492-de2d7980-6b62-11e9-94a6-3312ef9751ae.png)
就是这个样子，跟后端交互之后发现这个加载层没有了

**Comment by smileTaylor** [comment]
我想要的就是数据还没加载出来的时候，显示这个加载层

**Comment by cipchk** [comment]
@smileTaylor 完全 不懂你的意思，有问题请提供一个完整的可重现示例。

**Comment by hennychen** [comment]
@smileTaylor
题主要的是这个吧：Spin加载中
用于页面和区块的加载中状态。
https://ng.ant.design/components/spin/zh
[https://stackblitz.com/run](url)
