### ISSUE TITLE
双y轴 

### ISSUE THREAD

**Issue by charlee2025** [ng-alain/ng-alain#1058]
想咨询下g2怎么实现双y轴
![微信图片_20190429215803](https://user-images.githubusercontent.com/8101989/56901119-fa310c80-6ac9-11e9-91fa-c3301679a20d.png)

**Comment by cipchk** [comment]
使用自定义 `g2` 组件，并结合 https://antv.alipay.com/zh-cn/g2/3.x/demo/index.html 的示例，就可以了。
