### ISSUE TITLE
feat(demo): need more page templates

### ISSUE THREAD

**Issue by cipchk** [ng-alain/ng-alain#106]
We need more page templates to help your business develop.

- [x] Editor
    - [x] Ueditor
    - [x] Tinymce
    - ~Markdown~ (0.5.0)
    - ~CodeMirrorr~ (0.5.0)
- [x] Split
- [x] Clipboard
- ~Export~ (0.5.0)
    - Excel (xlsx)
    - Zip (jszip)

**Comment by dusdong** [comment]
可以增加页面打印的模板吗？如文本页、自定义表格（报名表/审批表等）的打印

**Comment by cipchk** [comment]
欢迎你来PR

**Comment by bokire** [comment]
增加动态页面的例子
