### ISSUE TITLE
st组件 column中的下拉项点击后不会自动关闭dropdown

### ISSUE THREAD

**Issue by tky753** [ng-alain/ng-alain#1064]
- ng-alain version: 7.2.0
- Angular version: 7.2.9

## 【必填项】重现链接，Reproduction link
https://stackblitz.com/edit/ng-alain-st-btn-click-close?file=package.json
![EUZoD0.png](https://s2.ax1x.com/2019/05/03/EUZoD0.png)
## 重现步骤，Steps to reproduce
1. 鼠标 移到Action列的More
2. 点击 弹出的dropdonw中的btn1，dropdown不会关闭

## 备注
如果STColumnButton的type为**link**，点击button后鼠标不要移开，这时候跳到其他页后，这个dropdwon就会一直存在，无法关闭。

**Comment by cipchk** [comment]
@tky753 尝试升级至最新版本，或者提供一个可用的重现链接。

**Comment by tky753** [comment]
@cipchk 

- @delon version: 7.2.0
- ng-alain version: -
- 浏览器：Chrome 版本 72.0.3626.121（正式版本） （64 位）

## 重现链接
https://stackblitz.com/edit/ng-alain-st-btn-click-close?file=src%2Fapp%2Fapp.component.ts

![EaFx9s.png](https://s2.ax1x.com/2019/05/04/EaFx9s.png)

## 备注
在 [文档](https://ng-alain.com/components/table/zh#components-table-buttons) 也能看出来，
点击 操作区>更多>过期后，下拉不会关闭
![EakQHO.png](https://s2.ax1x.com/2019/05/04/EakQHO.png)
