### ISSUE TITLE
ng g ng-alain:list list -m=xxx  tips: error Could not find any [COMPONENTS] variable.

### ISSUE THREAD

**Issue by hennychen** [ng-alain/ng-alain#1068]
- ng-alain version: 7.3.2
- Angular version: ^7.2.14

## 【必填项】重现链接，Reproduction link
![OR$ G UJO TU{R5D8{SD)T](https://user-images.githubusercontent.com/2526830/57187829-88245180-6f27-11e9-95a3-49defa92c0f0.png)

## 重现步骤，Steps to reproduce

C:\Users\Administrator\HTAdminProject>ng g ng-alain:list DesignRequirement -m=design
? Specifies relative path(could be set like `bus/list`):
Could not find any [COMPONENTS] variable.

**Comment by cipchk** [comment]
`design` 模块未找到 `COMPONENTS`，类似：https://github.com/ng-alain/ng-alain/blob/master/src/app/routes/pro/pro.module.ts#L34
