### ISSUE TITLE
setting-drawer.component.ts  中 loadStyle ./assets/alain-default.less后 头部的 header-notify 等失效

### ISSUE THREAD

**Issue by GITxiangzhang** [ng-alain/ng-alain#1069]
- ng-alain version: master
- Angular version: master

## 重现步骤，Steps to reproduce
setting-drawer.component.ts  中 loadStyle ./assets/alain-default.less后 头部的 header-notify 等失效

**Comment by cipchk** [comment]
目前生成的 `alain-default.less` 的确会有开发环境下发生这种情况，主要还是 `antd-theme-generator` 无法工作，所以采用一种极端的办法，倒置生成的样式会有重复。

我会持续跟进这一问题，目前没有什么好的办法，但若不把 `setting-drawer` 应用至生产环境中，就不存在这一问题。

**Comment by GITxiangzhang** [comment]
> 目前生成的 `alain-default.less` 的确会有开发环境下发生这种情况，主要还是 `antd-theme-generator` 无法工作，所以采用一种极端的办法，倒置生成的样式会有重复。
> 
> 我会持续跟进这一问题，目前没有什么好的办法，但若不把 `setting-drawer` 应用至生产环境中，就不存在这一问题。
目前因我需要把setting-drawer应用到生产环境做换肤了，故生成 alain-default.less后不再通过color-less.js 再去生成，主动去维护alain-default.less 文件将有问题的样式剔除去解决。
