### ISSUE TITLE
sf表达自定义小部件，label显示，属性错误

### ISSUE THREAD

**Issue by a952454** [ng-alain/ng-alain#1070]
- ng-alain version: 7.3.2
- Angular version: 7.2.12

## 【必填项】重现链接，Reproduction link
https://stackblitz.com/edit/ng-alain-setup-nynmqn

## 重现步骤，Steps to reproduce
showTitle和schema.title类型不匹配。

**Comment by cipchk** [comment]
不管如何都必须指定 `[showTitle]="true"` 才会显示标题，`title` 可以视为一种标题文件。

**Comment by a952454** [comment]
那我觉得应该修改一下，官网文档的实例。

**Comment by cipchk** [comment]
@a952454 ?
