### ISSUE TITLE
st （表格） 样式能否自定义

### ISSUE THREAD

**Issue by allenlongbaobao** [ng-alain/ng-alain#1071]
如题，在业务开发中，ui 给出的表格样式很大概率和 ng-alain 的风格不同，请问如何进行表格样式的自定义呢？

**Comment by cipchk** [comment]
`st` 其实就是 `nz-table` 你完全可以定制你需要的样式，有许多办法，利用重置[表格样式变量](https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/components/table/style/index.less#L5)，当然无变量部分，可以利用覆盖CSS样式的方式。

**Comment by allenlongbaobao** [comment]
@cipchk 嗯，已经找到样式侵入的方法了，感谢🙏
