### ISSUE TITLE
build --prod 之后文件体积能不能更小点？

### ISSUE THREAD

**Issue by Dyinfalse** [ng-alain/ng-alain#1072]
给出的例子页面打开首次加载大概1.3M的资源，感觉还是有点大，最好能到1M以内。
原本build之后30M+， 使用 build --prod 减少到10M左右，在nginx配置gzip，也只能到1.5M，没办法到1M以内么？

**Comment by cipchk** [comment]
文件大小取决于绝大部分是第三方类库的运用，有关一些小细节请参考：

- https://ng-alain.com/docs/performance/en
- https://ng-alain.com/docs/deploy/en#Analyze-the-build-file-volume
