### ISSUE TITLE
CLI安装发现bug

### ISSUE THREAD

**Issue by dahuahe** [ng-alain/ng-alain#1073]
- ng-alain version: X.Y.Z
- Angular version: X.Y.Z
![image](https://user-images.githubusercontent.com/16739083/57205982-ea975380-6ff4-11e9-8480-f3160682d5b3.png)

## 重现步骤，Steps to reproduce
ng new my-project --style less
cd my-project
ng add ng-alain
一直回车
npm start

**Comment by dayhi** [comment]
同样碰到这个bug
