### ISSUE TITLE
ng g ng-alain:list xxx -m=xxx  genrate http module private  error 

### ISSUE THREAD

**Issue by hennychen** [ng-alain/ng-alain#1074]
- ng-alain version: 7.3.2
- Angular version: 7.2.14

## 【必填项】重现链接，Reproduction link
 constructor(private http: _HttpClient, private modal: ModalHelper,
    private ss: SessionStorageService,
    private msgSrv: NzMessageService,
  ) { }

## 重现步骤，Steps to reproduce
ng g ng-alain:list xxx -m=xxx 
constructor(public http: _HttpClient, private modal: ModalHelper,
    private ss: SessionStorageService,
    private msgSrv: NzMessageService,
  ) { }

**请生成命令 默认改为public http ，谢谢**

**Comment by cipchk** [comment]
`list` 默认行为中，并不需要 `http` 在模板中运用，因此若这样处理反而会有误导。
