### ISSUE TITLE
@delon/auth canDeactivate

### ISSUE THREAD

**Issue by meherett** [ng-alain/ng-alain#1077]
- [ ] There is no `canDeactivate` on simple.guard

**Comment by cipchk** [comment]
@meherett `CanDeactivate` trigger when a route can be deactivated, I think it's already on the authorized page, why do I still need authorization verification?

**Comment by huafengThunder** [comment]
离开守卫会触发2次

**Comment by huafengThunder** [comment]
离开守卫会触发2次

**Comment by cipchk** [comment]
@huafengThunder 会不会是因为你的守卫多次使用了呢？比如里外层都引用了一个相同的守卫。

**Comment by huafengThunder** [comment]
> @huafengThunder 会不会是因为你的守卫多次使用了呢？比如里外层都引用了一个相同的守卫。

是的，放在父级上去了。理解错了。谢谢
