### ISSUE TITLE
@delon/form Is there any way to add Card/Collapse to contain multiple fields?

### ISSUE THREAD

**Issue by NanFengCheong** [ng-alain/ng-alain#1079]
Example:
Card
![image](https://user-images.githubusercontent.com/7321833/57351882-0f76fc80-7196-11e9-9d30-772bbd4c34c2.png)

Collapse
![image](https://user-images.githubusercontent.com/7321833/57351924-3af9e700-7196-11e9-8138-b124b072c4f4.png)

**Comment by cipchk** [comment]
Maybe dupcated of #953, I think you can create an object widget.

**Comment by NanFengCheong** [comment]
Ya. I created a custom object widget wrapped with the card/collapse component. Thanks.

**Comment by 13776668267** [comment]
> Ya. I created a custom object widget wrapped with the card/collapse component. Thanks.

May you share your realization？thanks
