### ISSUE TITLE
HELP!? about token

### ISSUE THREAD

**Issue by flyingbeecd** [ng-alain/ng-alain#108]
## Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] help question
```

i don't understand how to use the token, could you give a detail example?
i can't found the token message add into the header  when use the SimpleInterceptor, i should deal it by myself？

**Comment by cipchk** [comment]
[Document](http://ng-alain.com/docs/auth).

If still unclear, please provider more information to be discussed.

**Comment by cipchk** [comment]
长时间未处理；有任何问题重新提交issues。
