### ISSUE TITLE
g2-timeline 左右拖动会影响y坐标的显示效果

### ISSUE THREAD

**Issue by zhaopeiym** [ng-alain/ng-alain#1083]
-  "@antv/g2": "^3.2.7",
    "@antv/g2-plugin-slider": "^2.0.4",
-  "@angular/cli": "^6.1.3",

## 重现效果截图
![QQ截图20190509113953](https://user-images.githubusercontent.com/5820324/57425773-304f5880-724f-11e9-8987-a08514340c1e.png)

## 重现效果GIF录屏
![GIF](https://user-images.githubusercontent.com/5820324/57425686-c8007700-724e-11e9-98ad-76bbd3e7e98f.gif)

**Comment by cipchk** [comment]
@zhaopeiym 请告知 @delon 版本号，若非 7.x，请更改自定义G2组件来编写。

**Comment by zhaopeiym** [comment]
"@delon/abc": "^1.4.1",
    "@delon/acl": "^1.4.0",
    "@delon/theme": "^1.4.0",
    "@delon/util": "^1.4.1",

好的，那我升级试试。
