### ISSUE TITLE
如何封装 ng-alain 中的组件

### ISSUE THREAD

**Issue by allenlongbaobao** [ng-alain/ng-alain#1085]
您好，我在业务开发中，需要在 `st` 组件底部增加一组 button，因为 st 没有现成的插槽，我的思路是想封装一下 st 组件:

```
@Component({
  selector: 'app-cst',
  template:
  `
    <st></st>
  `,
  providers: []
})
export class CstComponent extends STComponent { }
```

然后在其他组件使用这个 `app-cst` 组件，但是浏览器报错

```
ERROR Error: StaticInjectorError(AppModule)[CstComponent -> STExport]: 
  StaticInjectorError(Platform: core)[CstComponent -> STExport]: 
    NullInjectorError: No provider for STExport!
```

看提示是因为没有 provider ，但我不知道该给它加哪些provider，不知我的思路对不对，如果对的话，接下去该怎么进行？不如不对的话，该怎么解决这个需求呢？

**Comment by cipchk** [comment]
使用 `extends` 只能针对类，对于 [@Component](https://github.com/ng-alain/delon/blob/master/packages/abc/table/table.component.ts#L66) 部分，你依然需要重新定义。

**Comment by allenlongbaobao** [comment]
您说的重新定义指的是 implments 吗？
