### ISSUE TITLE
ng serve --baseHref=/back/后，:4200/assets/tmp/i18n/zh-CN.json 找不到的问题

### ISSUE THREAD

**Issue by charlee2025** [ng-alain/ng-alain#1086]
- ng-alain version: 7.0.1
- Angular version: 7.2.0

## 重现步骤，Steps to reproduce

ng serve --baseHref=/back/后，zh-CN.json 报404，路径为:4200/assets/tmp/i18n/zh-CN.json，没有加上/back/，然后项目无法启动

**Comment by cipchk** [comment]
HTTP 请求若你不以 `/` 开头会遵守 `base-href` 的规则。有关其他相关细节，可以自行 Google，另：https://angular.io/cli/build#options，也可以了解一下。

**Comment by charlee2025** [comment]
感谢
