### ISSUE TITLE
st组件 能否提供禁止前端排序的选项

### ISSUE THREAD

**Issue by tky753** [ng-alain/ng-alain#1088]
当st组件的data不是字符串时，点击列排序时会强制从排序列去获取`sorterFn`(排序方法)进行前端排序，
如果找不到就会警告 `[st] Muse provide the compare function in sort`
如果提前排好序后再赋值data的话，前端排序就用不到了。

能否提供选项 禁止前端排序

**Comment by xingkoo** [comment]
难道列配置中不设置排序的情况下也可以产生排序操作？先提供个演示再说吧。

**Comment by tky753** [comment]
@xingkoo 
我现在的场景是，在sort事件触发时获取排序的参数，然后传递给后端在后端加载数据时顺便排好序，再传回数据赋值给data。
因此我会这样定义column：`{ title: 'F1', index: 'F1', sort: true }`
![E4Yurt.png](https://s2.ax1x.com/2019/05/13/E4Yurt.png)

[https://stackblitz.com/edit/ng-alain-st-auto-front-sort?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/edit/ng-alain-st-auto-front-sort?file=src%2Fapp%2Fapp.component.ts)

**Comment by tang-butian** [comment]
![image](https://user-images.githubusercontent.com/27254047/66725816-c5dabe00-ee67-11e9-9c9a-33341d16e39b.png)
升级到8.5.0 问题依然存在
