### ISSUE TITLE
sf组件中，select 多选模式，选项不能正常显示

### ISSUE THREAD

**Issue by zdxxxxxx** [ng-alain/ng-alain#1089]
- ng-alain version: 7.3.2
- Angular version: 7.3.2

## 【必填项】重现链接，Reproduction link
https://stackblitz.com/edit/ng-alain-setup-a8ekns?file=src/app/app.component.ts

![image](https://user-images.githubusercontent.com/16288673/57599148-598e2280-7588-11e9-9062-17adba8f9b8f.png)

## 重现步骤，Steps to reproduce
选择下拉选项时，直接收起为+1...

**Comment by cipchk** [comment]
- `maxMultipleCount` 最多选中多少个标签
- `maxTagCount` 最多显示多少个 tag

**Comment by zdxxxxxx** [comment]
@cipchk 
问题是多选模式，选择一项直接就会展示成+1....这样的省略标签，没有做任何配置，默认应该是全部展示呢
