### ISSUE TITLE
关于自定义指令问题

### ISSUE THREAD

**Issue by guccihuiyuan** [ng-alain/ng-alain#109]
我自定义了一个指令，然后声明在AppModule中的declarations里面，在模板中使用就报错，但是我新建一个angular工程的时候，一起的处理，是正常的，不知道什么原因

**Comment by cipchk** [comment]
建议在 `SharedModule` 中注册。

**Comment by hellheaven** [comment]
@cipchk 在sharedModule中注册也无法使用。

`declarations: [
        HighlightDirective,
    ],`

**Comment by cipchk** [comment]
需要导出 `exports: [ HighlightDirective ]`
