### ISSUE TITLE
st -- How decide search button? -- Schematics curd

### ISSUE THREAD

**Issue by alelorenzoitop** [ng-alain/ng-alain#1090]
Hello, I have tryed to use Schematics curd generation (ng g ng-alain:curd curd -m=trade), however I cannot use the Search button when I change the source data and the columns:

![Captura de pantalla (104)](https://user-images.githubusercontent.com/50572875/57605919-b0333680-755f-11e9-8c50-364436c460eb.png)

```html
<nz-card>
  <sf mode="search" [schema]="searchSchema"  (formSubmit)="st.reset($event)" (formReset)="st.reset($event)"></sf>
  <st #st [data]="data" [columns]="columns"></st>
</nz-card>
```

```ts
searchSchema: SFSchema = {
    properties: {
      pregunta: {
        type: 'string',
        title: 'Filtrar'
      }
    }
  };
  @ViewChild('st') st: STComponent;
  columns: STColumn[] = [
    { title: 'Pregunta',  index: 'pregunta' },
    { title: 'Respuesta', index: 'respuesta', type: 'number' },
    { title: '',
      buttons: [
        { text: 'Ver', click: (item: any) => `/form/${item.id}` },
        { text: 'Editar', type: 'static', component: InteligenciaCurdviewEditComponent, click: 'reload' },
      ]
    }
  ];
```

(I cannot use qq on English)

**Comment by cipchk** [comment]
Sorry, I can't understand what you mean, pls provide a reproducible steps & stackblitz.

**Comment by alelorenzoitop** [comment]
**https://stackblitz.com/edit/angular-upkyjq**

I only changed the data source.
(Origin: https://stackblitz.com/run?file=src/app/app.component.ts)
(https://ng-alain.com/components/table/en#components-table-export)

I want to use "Alfa" column for search. When I click 搜索, search into "Alfa" column.

**Comment by cipchk** [comment]
For local data sources, `st` has no built-in search function; You can implement it yourself: 

```html
<button nz-button (click)="search()" [nzType]="'primary'">搜索</button>
```

```ts
search(): void {
	this.data = deepCopy(this.data).filter(w => ~w.a.indexOf(this.params.name));
}
```

**Comment by alelorenzoitop** [comment]
Ok, thanks
