### ISSUE TITLE
ng-alain里面的列表不能通过拖拽行进行排序吗，angular里面是支持的

### ISSUE THREAD

**Issue by linhuchong521** [ng-alain/ng-alain#1091]
🚨 Issues 是用于BUG、Feature、进度追踪 🚨
🚨 The issue tracker is not for questions 🚨

如果有任何问题，可在以下方式获得答案：

- https://ng-alain.com/
- QQ Group：316911865
- https://segmentfault.com/t/ng-alain

**Comment by cipchk** [comment]
ng-alain 依赖 angular/cdk，你可以参考自己实现：https://material.angular.io/cdk/drag-drop/overview
