### ISSUE TITLE
不添加 i18N 的话，页面无法正常使用。

### ISSUE THREAD

**Issue by dvorakchen** [ng-alain/ng-alain#1092]
- ng-alain version: 7.3.2
- Angular version: 7.3.9

使用 ng add ng-alain
会提示：Would you like to add i18n plugin? <default: N> (y/N)
选择 N 的话，npm start 的页面会一直停留在加载页，不会跳转到登陆页。
在console 中会提示缺少 translate 

![image](https://user-images.githubusercontent.com/50647468/57751165-6ee58700-7717-11e9-9fda-f22adfde8249.png)

**Comment by cipchk** [comment]
fixed #561

**Comment by dvorakchen** [comment]
并不知道你想表达什么，若你认为这个issue没有意义那就closed它吧。抱歉打扰了。


________________________________
发件人: 卡色 <notifications@github.com>
发送时间: Wednesday, May 15, 2019 3:07:09 PM
收件人: ng-alain/ng-alain
抄送: mrunowen; Author
主题: Re: [ng-alain/ng-alain] 不添加 i18N 的话，页面无法正常使用。 (#1092)


fixed #561<https://github.com/ng-alain/ng-alain/issues/561>

―

**Comment by cipchk** [comment]
@mrunowen 抱歉，发错链接了，已修复该问题：https://github.com/ng-alain/delon/pull/561
