### ISSUE TITLE
st表格分页器中每页显示条目数下拉框点选后无反应

### ISSUE THREAD

**Issue by erupts** [ng-alain/ng-alain#1093]
- ng-alain version: 7.3.2
- Angular version: 7.2.0

## 【必填项】重现链接，Reproduction link
![image](https://user-images.githubusercontent.com/20358088/57754831-f46e3480-7721-11e9-809e-8a0d9870fbaa.png)

## 重现步骤，Steps to reproduce
st表格分页器中每页显示条目数下拉框点选后无反应（后台分页），也不做任何网络请求

**Comment by cipchk** [comment]
fixed https://github.com/ng-alain/delon/pull/564

**Comment by cipchk** [comment]
fixed by 7.4.0

**Comment by erupts** [comment]
已经更新并得到解决👌
