### ISSUE TITLE
menu服务，一旦路由路径携带了queryParams，菜单无法匹配展开

### ISSUE THREAD

**Issue by ZeyZhang** [ng-alain/ng-alain#1096]
- ng-alain version: X.Y.Z
- Angular version: X.Y.Z

**Comment by cipchk** [comment]
是的，目前不支持 QueryString 参数。

**Comment by ZeyZhang** [comment]
目前解决方法是在ngAfterViewInit的时候调用MenuService.openedByUrl，但是页面刷新时，依然存在这个问题，请问是否menu.add是异步执行的方法

**Comment by cipchk** [comment]
@ZeyZhang  一般确保 `menu.add` 早于 `ngAfterViewInit` 就不会有这种问题，所以我个人比较推荐在 StartupService 中使用 `menu.add`。

**Comment by ZeyZhang** [comment]
@cipchk 问题依然存在，希望后续版本可以考虑匹配带queryParams的路由，感谢提供ng-alain.

**Comment by cipchk** [comment]
@ZeyZhang 你只要确保你的菜单数据有包括相应的带参数的数据即可；但对于动态，你只能利用 `add` 来更新菜单数据。

**Comment by allenlongbaobao** [comment]
@cipchk 同遇到这个问题，因为一个页面 init 的时候会设置默认请求参数，导致菜单栏无法匹配，请问有推荐的解决方案吗？

**Comment by Carpon39038** [comment]
我们老项目用的1.x版本就可以在路由里携带queryParams，新项目使用新版本8.x后携带queryParams菜单就无法匹配了 不是很理解

**Comment by allenlongbaobao** [comment]
@CaBeta 我用的是 7.x，最后用一种比较hack 的方式来解决：路由重定向一下
before:

```
const routes  = [
  {
    path: '',
    component: AcquirerListComponent,
    pathMatch: 'full',
  },
]
```
after: 

```
const routes  = [
  { path: '', redirectTo: 'list', pathMatch: 'full' },
  {
    path: 'list',
    component: AcquirerListComponent,
    pathMatch: 'full',
  },
]
```
希望对你有帮助～
