### ISSUE TITLE
st表格直接访问st._data更新一行数据问题

### ISSUE THREAD

**Issue by s641135196** [ng-alain/ng-alain#1097]
直接访问 st._data，并调用 st.cd()更新单选有问题

例如我更新第一行的数据。 
```javascript
      this.st._data[0].email = 'hello';
      this.st.cd();
```
设置的值并未更新到界面上。
后来发现是this.st.data[0]._values 参数的值未自动更新导致的。
后来我将代码更改如下，值就会更新到界面上
```javascript
      this.st._data[0].email = 'hello';
      this.st._data[0]._values[5] = {text:'hello',org: 'hello'};
      this.st.cd();
```

`console.log(this.st.data[0])的值`

![image](https://user-images.githubusercontent.com/8079013/57970894-98bdd880-79b9-11e9-8433-f5ebff1b6e21.png)

上面这样做只是测试出问题， 有什么办法解决没。

**Comment by cipchk** [comment]
没有，`_values` 会根据原生数据与`STColumn`计算后产生的可被渲染的数据，例如上面的下标 `8` 的数据 `text` 渲染属性与 `org` 原生数据是完全不一样的，目前你的方式与理解是对的。

是否需要增加例如 `setValue` 方法来变更数据，细节我觉得可以讨论一下，到底如何提供一个有效的 `setValue` 方法更合理。

**Comment by s641135196** [comment]
不会就我遇到这问题吧， 希望后期能解决。
现在用是刷新整个表格的解决方案，  虽然可行但有时候却没那么友好。
