### ISSUE TITLE
搭建了基础的ng-alian脚手架启动后菜单不全,而且已有的菜单也看不到子菜单

### ISSUE THREAD

**Issue by wangchao16213** [ng-alain/ng-alain#1099]
搭建了基础的ng-alian脚手架启动后菜单不全,而且已有的菜单也看不到子菜单
![image](https://user-images.githubusercontent.com/16793182/58043261-4de5c180-7b6f-11e9-801d-9fa268d38e62.png)

**Comment by cipchk** [comment]
利用 `ng add ng-alain` 命令只会生成一个仪表盘页。
