### ISSUE TITLE
IE无法进入主页，一直停留再loading

### ISSUE THREAD

**Issue by david1025** [ng-alain/ng-alain#11]
IE无法进入主页，一直停留再loading

**Comment by cipchk** [comment]
现代浏览器和 IE9 以上（需要 [polyfills](https://angular.cn/guide/browser-support)）。

**Comment by david1025** [comment]
polyfills 需要我自行引用么？

**Comment by cipchk** [comment]
是，开启 `polyfills.ts` 文件里面的配置。

**Comment by chenjia123** [comment]
我也遇到这个问题了，如何开启 Polyfills 里面的配置啊，Alain里面的Polyfills配置我是没有修改的，但是IE还是不能打开，只能不断的 loading
