### ISSUE TITLE
st表格如何获得经过columnfilter 过滤之后的数据

### ISSUE THREAD

**Issue by jiangbw112** [ng-alain/ng-alain#1102]
想把经过列筛选过后，也就是当前显示表格内容，导出excel，怎么样获得filtered data?

**Comment by cipchk** [comment]
`st._data`

**Comment by jiangbw112** [comment]
st._data只能显示第一页的值，但是我需要所有的页里的数据

**Comment by cipchk** [comment]
@jiangbw112 `st` 支持本地数据与远程数据，能否提供更进一步的描述及场景的说明。

**Comment by jiangbw112** [comment]
比如st 一共有100个数据，每页显示10个， 然后我通过STColumn的filter筛选出50个，并且想把这筛选后的数据导出到excel，但是_data只有第一页的10个， data是全部的100个，没有找到表示筛选后的数据的属性，所以我自己加了一个，这个属性在google 的material table里面已经有了，名字是datasource.filtereddata.

**Comment by cipchk** [comment]
@jiangbw112 我看到了，但是只是实现的本地数据，`st` 支持远程数据，能否进一步实现呢？以及我个人认为名称不应该按驼峰来命名。

**Comment by jiangbw112** [comment]
好的，这几天在培训，有空了我研究下，谢谢反馈
