### ISSUE TITLE
page refresh is very slow，Mainly vendor. JS files, sometimes loaded for 27 seconds or longer

### ISSUE THREAD

**Issue by wushuxuan** [ng-alain/ng-alain#1103]
page refresh is very slow，Mainly vendor. JS files, sometimes loaded for 27 seconds or longer，

Is there a good solution to this problem?

**Comment by cipchk** [comment]
Can you provider a network pannel in chrome?

**Comment by wushuxuan** [comment]
![image](https://user-images.githubusercontent.com/30644407/58220460-8b01ad80-7d41-11e9-9349-8e5e94b0b284.png)

**Comment by wushuxuan** [comment]
@cipchk

**Comment by wushuxuan** [comment]
maybe it's because of the network problem, but it shouldn't be so slow....

**Comment by cipchk** [comment]
@wushuxuan I think you can try another computer, maybe it's an env problem.

**Comment by wushuxuan** [comment]
well, I wonder if there are any other solutions? For example, reduce something

**Comment by cipchk** [comment]
This question is complicated!

It’s hard to optimize it without knowing the details of the project, Maybe the following two links to be helpful:

- https://ng-alain.com/docs/performance/en
- https://ng-alain.com/docs/deploy/en#Analyze-the-build-file-volume
