### ISSUE TITLE
Is there a way to dynamically change required without refreshSchema

### ISSUE THREAD

**Issue by NanFengCheong** [ng-alain/ng-alain#1106]
I want to preserve formData after change.

**Comment by cipchk** [comment]
Not, but you can using `deepCopy` origin schema and call `refreshSchema` method, like this:

```ts
const copy: SFSchema = deepCopy(this.schema);
copy.required = ['mobile'];
this.sf.refreshSchema(copy);
```

**Comment by shiqkuangsan** [comment]
> Not, but you can using `deepCopy` origin schema and call `refreshSchema` method, like this:
> 
> ```ts
> const copy: SFSchema = deepCopy(this.schema);
> copy.required = ['mobile'];
> this.sf.refreshSchema(copy);
> ```
刷新 schema 会刷新掉 SF 当前已操作的值、请问如何避免？

**Comment by cipchk** [comment]
@shiqkuangsan 参考 `refreshSchema` 的第二个参数 。
