### ISSUE TITLE
在使用 sf upload中，有发现很多问题

### ISSUE THREAD

**Issue by wushuxuan** [ng-alain/ng-alain#1109]
- ng-alain version: X.Y.Z
- Angular version: X.Y.Z

## 【必填项】重现链接，Reproduction link

**1、官网的例子，如果加上required，那么有 enum属性的 组件的下方就不会显示 “必填项”，但是没有enum属性的组件下方就会显示 “必填项”;**

import { Component } from '@angular/core';
import { SFSchema } from '@delon/form';
import { NzMessageService } from 'ng-zorro-antd';

@Component({
  selector: 'form-upload-simple',
  template: `
    <sf [schema]="schema" (formSubmit)="submit($event)"></sf>
  `,
})
export class FormUploadSimpleComponent {
  schema: SFSchema = {
    properties: {
      file: {
        type: 'string',
        title: '单个文件',
        enum: [
          {
            uid: -1,
            name: 'xxx.png',
            status: 'done',
            url: 'https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png',
            response: {
              resource_id: 1,
            },
          },
        ],
        ui: {
          widget: 'upload',
          action: '/upload',
          resReName: 'resource_id',
          urlReName: 'url',
        },
      },
      mulit: {
        type: 'string',
        title: '多个文件',
        ui: {
          widget: 'upload',
          action: '/upload',
          resReName: 'resource_id',
          urlReName: 'url',
          multiple: true,
        },
      },
      // 拖动模式
      drag: {
        type: 'string',
        title: 'Drag',
        enum: [],
        ui: {
          widget: 'upload',
          action: '/upload',
          resReName: 'resource_id',
          urlReName: 'url',
          type: 'drag',
        },
      },
    },
    required: ['file','mulit', 'drag',],
  };
  constructor(public msg: NzMessageService) {}
  submit(value: any) {
    this.msg.success(JSON.stringify(value));
  }
}

**2、在sf中使用upload组件，他并不能像其他组件一样返回组件所绑定的值，这一块是否有优化方案呢？**

![image](https://user-images.githubusercontent.com/30644407/58318890-43ffdf00-7e4b-11e9-8b70-13af6b384479.png)

**Comment by wushuxuan** [comment]
@cipchk    并且sf 里的upload组件 的 [nzShowButton] 属性 貌似是不支持这个功能么？

还有在sf里是不支持upload的手动上传功能么？在大多的项目中，手动上传还是应用的比较多的了。。。

**Comment by cipchk** [comment]
@wushuxuan 抱歉，不明白你的意思， `file: 1` 这是结果，但是你认为结果不对，正确应该是什么，我应该如何重现这种错误 ？

**Comment by wushuxuan** [comment]
@cipchk   准确来说不是结果不对，就是这个设计有点不太懂，在sf里upload是不支持手动上传么？比如支持，那绑定的数据具体怎么使用呢？因为官网上没有举出手动上传的例子，而且我这边使用的手动上传，貌似是没有用的，并且sf 里的upload组件 的 [nzShowButton] 属性 貌似是不支持这个功能么？

**Comment by wushuxuan** [comment]
@cipchk   如果是手动上传，获取到的就是文件本身，而不是自动上传获取返回数据的某一字段值

**Comment by cipchk** [comment]
@wushuxuan 其实我比较建议自己写一个属于你们业务的上传小部件，特别很多时候内部都会有自己的图片空间之类的。

**Comment by wushuxuan** [comment]
@cipchk  请问如果要给sf中的upload组件赋值具体怎么赋呢？


this.sf.setValue('/title', '12233');   这样就可以给input组件赋值，但是同样的方法，upload却不能赋值。。。


代码示例：

`
import { Component, OnInit, ViewChild, SimpleChanges } from '@angular/core';
import { SFSchema, SFComponent } from '@delon/form';

@Component({
  selector: 'app-school-info',
  template: `
  <nz-card nzTitle="学校信息">
  <sf #sf [mode]="edit" [schema]="schema" [button]=null (formSubmit)="submit($event)">
    <button type="submit" nzType="primary" [nzLoading]="loading" nz-button [disabled]="!sf.valid">保存</button>
  </sf>

</nz-card>

  `,
  styles: []
})
export class SchoolInfoComponent implements OnInit {

  @ViewChild('sf') sf: SFComponent;

  loading = false;
  schema: SFSchema = {
    properties: {
      title: {
        type: 'string', title: '文字', maxLength: 5,
        ui: {
          placeholder: '请输入文字',
          errors: {
            'required': '请输入文字'
          },
        }
      },
      headerImg: {
        type: 'string', title: '图片',
        ui: {
          widget: 'uploads',
          type: 'select',
          text: '选择文件',
          //限制图片的数量
          limitLength: 1,
          errors: {
            'required': '请选择图片'
          },
        }
      },
    },
    required: ['title', 'headerImg'],
    ui: {
      // spanLabelFixed: 150,
      spanControl: 5,
      grid: { span: 24, },
    },
  };
  constructor() { }

  ngOnInit() {

  }

  ngAfterViewInit(): void {
    this.sf.setValue('/title', '12233');
    this.sf.setValue('/headerImg', [{
      uid: -1,
      name: 'xxx.png',
      status: 'done',
      url: 'https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png',
    }]);

  }

  submit(value: any) {
    console.log(value)
  }


}


`

**Comment by cipchk** [comment]
`sf.value` 值对于 Upload 小部件而言可能是一个 `id` 或 `url` 字符串，而不是 `fileList` 值。
