### ISSUE TITLE
I want to ask the author a question（想请教一个问题）

### ISSUE THREAD

**Issue by ohmygodoh** [ng-alain/ng-alain#111]
How does ng-alain start with a blue screen and a bunch of white dots? How do you get rid of this interface or shorten the time of this interface to the main interface（ng-alain开始的时候有一个蓝屏加上一堆白点是有什么作用，怎么样去除这个界面或者缩短这个界面到弹出主界面的时间）

**Comment by cipchk** [comment]
从网页打开至 Angular 组件开始渲染这一过程包含了：下载JS、CSS、加载远程配置信息(例如：菜单数据、用户数据等），这期间的整个过程会有一定的时间（特别是首次加载 ）；因此，利用一个动画让等待不会那么单一，仅此而已。

若你需要删除，只需要在 `index.html` 中将相应的 css & html 删除即可。

**Comment by ohmygodoh** [comment]
thanks for your replying.
