### ISSUE TITLE
tab标签页无法刷新当前界面

### ISSUE THREAD

**Issue by icodeing** [ng-alain/ng-alain#1112]
![image](https://user-images.githubusercontent.com/11436630/58363898-1fa11280-7ede-11e9-90e4-bc7d678411b7.png)

如果要刷新当前界面查看最新数据的话，需要刷新整个网站，刷新后只保留了当前打开的tab标签，其他的会自动关闭掉，希望能够在标签右键菜单功能中加入刷新按钮，实现刷新当前子界面。

**Comment by cipchk** [comment]
路由复用会缓存路由的组件状态，且缓存只会在缓存离开时发生；基于这一点所谓”刷新“只能是一种变性的形式，虽然技术上的确可以做到切换时重新构建一遍组件当放弃当前的缓存，但这太成本太高；

因此，才会有内置了两个事件 `_onReuseInit`、`_onReuseDestroy` 来满足切换的刷新，当然也支持自定义右键菜单，你也可以实现右键增加刷新功能，并调用该上述事件。
