### ISSUE TITLE
构建失败

### ISSUE THREAD

**Issue by olivewind** [ng-alain/ng-alain#1114]
- ng-alain version: 7.5.0
- Angular version: 7.3.1

## 【必填项】重现链接，Reproduction link

![image](https://user-images.githubusercontent.com/17901361/58394555-70e40a00-8076-11e9-9f9f-c8fa595a47e3.png)

https://github.com/ng-alain/delon/issues/582

## 重现步骤，Steps to reproduce

```
npm run build
```

**Comment by cipchk** [comment]
尝试升级至最新版本
