### ISSUE TITLE
优化 @delon 的依赖关系

### ISSUE THREAD

**Issue by zjxcv7** [ng-alain/ng-alain#1115]
目前只是用了 @delon/theme,没有使用@delon/abc或者@delon/chart模块。希望能将样式独立为一个模块，感谢开发者🙏🙏🙏。

**Comment by cipchk** [comment]
目前的确存在 `@delon/*` 的相互依赖，但它会尽可能的少，事实上并没有太多影响；ng-alain 从 `7.x` 以后我们也抛弃了非 ng-alain 对 `@delon/*` 的使用，不过对于 ng-alain 项目而言对部分 `@delon/*` 的**不使用**会有一些依赖，我会在 Angular8 对这一部分的重构。
