### ISSUE TITLE
how to add own svg icon to sider bar  in app-data.json 

### ISSUE THREAD

**Issue by allenlongbaobao** [ng-alain/ng-alain#1116]
as title, i want to use own svg icon in siderbar, how to use it in app-data.json? thank you!

**Comment by cipchk** [comment]
Supported, just only `type: 'iconfont'`, and load iconfont data via `iconService.fetchFromIconfont`, pls refer to ng-zorro [demo](https://ng.ant.design/components/icon/en#components-icon-demo-iconfont)

**Comment by allenlongbaobao** [comment]
@cipchk thanks for your help. as you suggested, i upload my custom svg icon to iconfont.cn and get the scriptUrl, the last step, i am confused by app-data.json code style:
```
        {
          "text": "待办事项",
          "i18n": "MENU.WORK_BENCH.TODO_LIST",
          "link": "/dashboard/todo",
          "icon": "icon-icon-test19",
          "type": "iconfont"
        },
```
how to add custom font in this json? is still `icon` key?

**Comment by cipchk** [comment]
@allenlongbaobao https://ng-alain.com/theme/menu/en#MenuIcon

**Comment by kang0310** [comment]
Got example?
