### ISSUE TITLE
SimpleInterceptor能支持Http头认证Authorization : Bearer ${token}吗

### ISSUE THREAD

**Issue by downlder** [ng-alain/ng-alain#112]
## Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x ] feature request
```

### Desired functionality.

只看到JWTInterceptor支持Http头认证Authorization : Bearer ${token}，需要让SimpleInterceptor也支持谢谢

**Comment by cipchk** [comment]
`SimpleInterceptor` 可以通过 `AuthOptions` 指定 `token_send_key`、`token_send_place` 参数调整发送方式；

**Comment by downlder** [comment]
@cipchk，AuthOptions指定了，但是AuthOptions不支持前缀，token_send_key为Authorization，token_send_place为header, 只能做到 Authorization:${token}，做不到Authorization : **Bearer** ${token}，谢谢

**Comment by cipchk** [comment]
JWT 请使用 JWT 拦截器。

**Comment by downlder** [comment]
您好，Bearer的不是JWT的规范，是Oauth2的规范，access_token虽然可以放在url里，但是我更喜欢放到header的Authorization里，您可以查看一下RFC规范 http://www.rfcreader.com/#rfc6750，谢谢

**Comment by cipchk** [comment]
看样子需要增加一个 `token_send_tpl` 参数：

```
{
    token_send_key: `Authorization`,
    token_send_template: `Bearer {token}`
}
```
