### ISSUE TITLE
sf的自定义widget可以实现多值绑定么

### ISSUE THREAD

**Issue by syxxjgh** [ng-alain/ng-alain#1122]
![image](https://user-images.githubusercontent.com/18287573/58771451-d4c28180-85e6-11e9-8445-79d75b68475a.png)
类似于这样的起始值结束值在一个widget中的

**Comment by cipchk** [comment]
可以。

参考 [date widget](https://github.com/ng-alain/delon/blob/master/packages/form/src/widgets/date/date.widget.ts#L98)，其中对 `end` 参数的处理。
