### ISSUE TITLE
如何在一个Modal中设计一个比较复杂的界面，并在Modal中导航？

### ISSUE THREAD

**Issue by fantasizer** [ng-alain/ng-alain#1123]
因为一些场景，需要打开一个Modal，Modal中会有比较复杂的界面，比如左边是菜单栏，进行导航；上边是tab栏，进行某一个具体页面的不同切换。

我想请教下，ng-alain是否可以做到？比较困惑的是如何在Modal打开的页面中进行路由，如果按照目前其他页面的路由方式，会导致modal被关闭，或者路由找不到的情况。

谢谢！

**Comment by cipchk** [comment]
路由切换会倒置关闭应该是[这里](https://github.com/ng-alain/ng-alain/blob/master/src/app/app.component.ts#L28)引起的。
