### ISSUE TITLE
调试阶段如何暂时关闭载入动画？不然每次修改后都要等好久才能看到反应

### ISSUE THREAD

**Issue by shikihane** [ng-alain/ng-alain#1124]
🚨 Issues 是用于BUG、Feature、进度追踪 🚨
🚨 The issue tracker is not for questions 🚨

如果有任何问题，可在以下方式获得答案：

- https://ng-alain.com/
- QQ Group：316911865
- https://segmentfault.com/t/ng-alain

**Comment by cipchk** [comment]
npm run hmr
