### ISSUE TITLE
st: add 'rowspan' config for STColumn

### ISSUE THREAD

**Issue by liveangela** [ng-alain/ng-alain#1126]
卡神，是否有空为st添加[attr.rowspan]配置？
应该和colspan的配置方式大致相同。
涉及代码位置:
- 定义: [table.interfaces.ts](https://github.com/ng-alain/delon/blob/437152140218fa31acd285b5893844c245dabd19/packages/abc/table/table.interfaces.ts#L270)
- html: [table.component.html](https://github.com/ng-alain/delon/blob/437152140218fa31acd285b5893844c245dabd19/packages/abc/table/table.component.html#L34)

**Comment by cipchk** [comment]
统一跟踪 #1576
