### ISSUE TITLE
侧边栏及其它组件样式无法改变, 只能更改主题色

### ISSUE THREAD

**Issue by wangziqiang131** [ng-alain/ng-alain#1127]
https://ng-alain.github.io/ng-alain/#/dashboard/v1

![TIM图片20190603163514](https://user-images.githubusercontent.com/46188227/58788843-56360600-861f-11e9-983e-f347312dbd58.png)

**Comment by cipchk** [comment]
暂时是的，这里只对颜色有效，但是不表示这些选项无法使用，将生成的主题应用至 `src/styles/theme.less` 中会生效。
