### ISSUE TITLE
关于@delon/acl 的建议，peerDependencies

### ISSUE THREAD

**Issue by CK110** [ng-alain/ng-alain#1128]
单独使用@delon/acl ，还需要自己安装@delon/util，可以直接设置成依赖，或者去除依赖相关代码

**Comment by cipchk** [comment]
不行，`@delon/util` 的依赖是正常的，打包时只会加入使用的部分，并不会影响包体大小 。

**Comment by CK110** [comment]
但是peerDependencies默认不会下载，为什么不改为dependencies
