### ISSUE TITLE
AdSimpleTableModule 导入报错

### ISSUE THREAD

**Issue by dangzhenghui1985** [ng-alain/ng-alain#113]
![image](https://user-images.githubusercontent.com/16914422/34088056-f8ee0668-e3e1-11e7-9462-2ec7100bb02f.png)
![image](https://user-images.githubusercontent.com/16914422/34088110-3aa39802-e3e2-11e7-862e-0a389441facf.png)
![image](https://user-images.githubusercontent.com/16914422/34088147-672d6812-e3e2-11e7-8510-d97f7277d5ca.png)

项目启动的时候就报这个错误了。
## Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
```

**Comment by cipchk** [comment]
应该是缺少 `providers`  注册 `SimpleTableConfig`。

```ts

export class SharedModule {
    static forRoot(): ModuleWithProviders {
        return {
            ngModule: SharedModule,
            providers: [
                // ng-zorro-antd Services
                NzNotificationService,
                NzMessageService,
                // @delon/abc
                SimpleTableConfig,
                // reuse-tab
                // ReuseTabService,
                // { provide: RouteReuseStrategy, useClass: ReuseTabStrategy, deps: [ ReuseTabService ] }
            ]
        };
    }
}
````

**Comment by dangzhenghui1985** [comment]
![image](https://user-images.githubusercontent.com/16914422/34092016-1adda278-e3fc-11e7-9211-143ddf9bab79.png)
    @cipchk 添加了依然报错

**Comment by cipchk** [comment]
这是一个完整在线示例，我不确定还缺少什么，你自行对比一下。
https://stackblitz.com/edit/ng-alain-setup?file=app%2Fapp.component.ts
