### ISSUE TITLE
最新版ng-alain 编辑form表单存在问题

### ISSUE THREAD

**Issue by ydostyle** [ng-alain/ng-alain#1132]
## 如图，在编辑表单的时候，第一次，不做任何修改，直接提交，返回的数据是undefined
![image](https://user-images.githubusercontent.com/22721444/58935260-96bc8d80-879f-11e9-9147-c37cc6cffffc.png)
## 进行编辑某个字段之后再提交，则返回正常
![image](https://user-images.githubusercontent.com/22721444/58935288-a936c700-879f-11e9-9148-59136dc406bb.png)
## 期望：
在第一次提交时，就返回正常的formdata数据，而不是undefined，经过测试这个问题在7.3.2版本不会出现，升级后才出现的

**Comment by liveangela** [comment]
- 7.5.0版本之前，默认会触发一次sf.reset()，[4f4c4f9](https://github.com/ng-alain/delon/commit/4f4c4f9)中去掉了该功能
- 我的做法是在ngAfterViewInit时机下手动调用一次

**Comment by ydostyle** [comment]
@liveangela  谢谢解答!但是影响到现有逻辑了，这个算bug吗 还是接下来的版本都是如此

**Comment by liveangela** [comment]
不算bug，只是使用方式变了，你可以通过sf的[formData]将默认值给出即可，具体看一下[文档](https://ng-alain.com/form/getting-started/zh#sf)

**Comment by ydostyle** [comment]
@liveangela 我formData一直有设置默认值，而且渲染在页面上了默认值，但是提交表单在新版本是undefined

**Comment by ydostyle** [comment]
![image](https://user-images.githubusercontent.com/22721444/58938011-91167600-87a6-11e9-8e82-df69b9dd33b2.png)
呈现在页面上了默认值，而提交表单的value却是undefined，我感觉不合理

**Comment by liveangela** [comment]
$event和sf.value拿到的都是undefined吗？

**Comment by ydostyle** [comment]
@liveangela 是的

**Comment by ydostyle** [comment]
只有7.5以上有这个问题，之前的版本没这个问题

**Comment by liveangela** [comment]
在第一次提交前，如果稍微改动几个数据呢？

**Comment by ydostyle** [comment]
@liveangela 我描述了的。。只要一个字段稍微改一个字，提交就正常了

**Comment by liveangela** [comment]
我本地测试看到的表现是，如果在第一次提交前没有做任何修改，提交按钮是disabled，个人认为这是合理的

**Comment by ydostyle** [comment]
disabled是根据sf.vaid判断的，如果你的表单没有必填项，这个vaid就是true，不会出现disabled,除非你再加个判断!sf.value,但是我感觉这个在内部处理好了就好了，没必要还依赖这个disabled属性规避这个问题
