### ISSUE TITLE
STColumn 设置 default 无效

### ISSUE THREAD

**Issue by iloveyins** [ng-alain/ng-alain#1134]
- ng-alain version: X.Y.Z

https://ng-alain.com/components/table/zh#components-table-statistical

**Comment by iloveyins** [comment]
[https://ng-alain.com/components/table/zh#components-table-statistical](url)

**Comment by cipchk** [comment]
@iloveyins 麻烦提供一个重现示例

**Comment by cipchk** [comment]
@iloveyins https://stackblitz.com/edit/angular-4hfhbd?file=src/app/app.component.ts

这个示例并没有问题。

**Comment by iloveyins** [comment]
https://stackblitz.com/run?file=src/app/app.component.ts
![image](https://user-images.githubusercontent.com/18527569/58954705-85d64100-87cc-11e9-96e0-c909e5888f88.png)

**Comment by iloveyins** [comment]
![image](https://user-images.githubusercontent.com/18527569/58954799-ba49fd00-87cc-11e9-89b1-12b590dc2a04.png)

**Comment by cipchk** [comment]
@iloveyins  这里的 `default` 只针对 `undefined`、`null`。

**Comment by iloveyins** [comment]
![image](https://user-images.githubusercontent.com/18527569/59000844-f3bb5080-883e-11e9-8c95-d1462f6b4a0d.png)
好像只支持undefined
