### ISSUE TITLE
在@delon/form的schema中设置visibleIf多个属性的问题

### ISSUE THREAD

**Issue by tumblingG** [ng-alain/ng-alain#1137]
我有一个需求，需用通过需要通过组件1和组件2的值来决定是否显示显示组件3，于是我在组件3的visibleIf里面设置监视组件1和组件2，代码如下
```
visibleIf: {
      attendanceType: (value: any) => value !== 0,
      needPatrolPoint: (value: any) => value !== false,
},
```
但是我发现这是一个或的关系，只要有一个为真就就显示，另外当例如needPatrolPoint的值改变的时候，只会执行needPatrolPoint对应的函数，但是attendanceType对应的函数没有执行，这样就导致了当attendanceType为真值的时候，无论我如何改变needPatrolPoint都是没用的。

原本我希望通过共同调用一个函数来执行解决这个问题，但是由于只执行改变了值的函数，这也失败了：
```
visibleIf: {
       attendanceType: (value: any) => this.showCondition(value, 0),
       needPatrolPoint: (value: any) => this.showCondition(value, 1),
},
```
请问我应该如何解决用多个组件的值来决定显示另一个组件呢？

**Comment by liveangela** [comment]
- 源码[注释](https://github.com/ng-alain/delon/blob/25f26172a6c84ea4b757896db9973577ab9f63c5/packages/form/src/model/form.property.ts#L295)中确实注明了是“或”的关系
- 用这样一种思路不知可否？
```js
visibleIf: {
  attendanceType: (value: any) => value !== 0 && this.sf.value.needPatrolPoint !== false,
},
```
- 未来或许能够支持让用户指定“或”还是“且”的关系？

**Comment by tumblingG** [comment]
非常感谢您的回复，这样做attendanceType的值改变的时候是正确的，但是needPatrolPoint值改变的时候却不会使目标组件隐藏或恢复，如上例所示。

如果能够在visibleIf里面任一属性改变的时候使visibleIf里面的函数全部执行一次，那么就可以实现这种特殊的需求，很遗憾现在只执行了改变值对应的函数。

**Comment by xingkoo** [comment]
```
visibleIf: {
  attendanceType: (value: any) => value !== 0 && this.sf.value.needPatrolPoint !== false,
  needPatrolPoint: (value: any) => value !== 0 && this.sf.value.attendanceType !== false,
},
```
这样呢？

**Comment by cipchk** [comment]
其实 `visibleIf` 支持的方法中有第二个参数 `property`，可以通过  `property.parent` 来获取其他信息或当前值；当然使用 `this.sf.value` 也是一种办法。
