### ISSUE TITLE
Property 'menus' is private and only accessible within class 'MenuService'.

### ISSUE THREAD

**Issue by changxinjie** [ng-alain/ng-alain#114]
打包发布时报错: 
ERROR in node_modules\@delon\abc\components\sidebar-nav\sidebar-nav.component.html(2,19): : Property 'menus' is private and only accessible within class 'MenuService'.

建议去掉private修饰符 line: 49
menus: Menu[];
@delon/theme/services/menu/menu.service.ts.

**Comment by cipchk** [comment]
并无 `private` [code](https://github.com/cipchk/delon/blob/master/src/core/theme/services/menu/menu.service.ts#L159)

**Comment by changxinjie** [comment]
![image](https://user-images.githubusercontent.com/9565184/34098146-6a00802c-e416-11e7-8aa3-fa958014f964.png)

 "@delon/theme": "^0.3.0-rc.2",
是这个文件, 原来有private, 删了就好了

**Comment by cipchk** [comment]
建议使用  `^0.3.0`
