### ISSUE TITLE
当启用serverSearch时Select组件的选择操作会触发onSearch

### ISSUE THREAD

**Issue by zd5043039119** [ng-alain/ng-alain#1144]
- ng-alain version: latest
- Angular version: 7.2.0

## 【必填项】重现链接，Reproduction link

https://stackblitz.com/edit/angular-j4mtpj?file=src/app/app.component.ts

## 重现步骤，Steps to reproduce
1.点击下拉框,此时无选项
2.输入查询字符串如1
3.此时console显示look1
4.点击选择任意option,此时console显示look
所以在选择option时会触发onSearch,如果不加判断会导致向服务端发起无参请求,可能导致报错

**Comment by cipchk** [comment]
tracking https://github.com/NG-ZORRO/ng-zorro-antd/issues/3554

**Comment by cipchk** [comment]
点击之后会清除当前搜索内容，所以会触发一次 `nzOnSearch`，原则上来说这也算是合理的行为，可以自行过滤掉；虽然会产生另一个现象，即若首次需要默认值时也会一并过滤，这一点可能需要额外第三个变量来支持，`sf` 依然保持这种行为。
