### ISSUE TITLE
ng update 之后编译失败

### ISSUE THREAD

**Issue by ZeyZhang** [ng-alain/ng-alain#1147]
- ng-alain version: X.Y.Z
- Angular version: X.Y.Z

## 【必填项】重现链接，Reproduction link

![image](https://user-images.githubusercontent.com/20785848/59241075-cbfe2b00-8c38-11e9-9071-f5a84270f37e.png)

## 重现步骤，Steps to reproduce
ng update ng-alain成功后，npm start出现如图所示报错

**Comment by cipchk** [comment]
尝试移除 `node_moduels`、`yarn.lock` 重新 `yarn`
