### ISSUE TITLE
无法加载自定义PIPE

### ISSUE THREAD

**Issue by wjlee3465** [ng-alain/ng-alain#1148]
ERROR Error: Uncaught (in promise): Error: Template parse errors:
The pipe 'dicts' could not be found ("<page-header [title]="merbase.merName" [tab]="tab">
  <div sv-container>
    <sv label="商户号">{{ [ERROR ->]merbase.merNo | dicts}}</sv>
    <sv label="商户名称">{{ merbase.merName }}</sv>
    <sv label="商户类别">{"): ng:///CpayModule/CpayCpayMerchantMerbaseMerchanneldtlComponent.html@2:23
Error: Template parse errors:
The pipe 'dicts' could not be found ("<page-header [title]="merbase.merName" [tab]="tab">
  <div sv-container>
    <sv label="商户号">{{ [ERROR ->]merbase.merNo | dicts}}</sv>
    <sv label="商户名称">{{ merbase.merName }}</sv>
    <sv label="商户类别">{"): ng:///CpayModule/CpayCpayMerchantMerbaseMerchanneldtlComponent.html@2:23
    at syntaxError (compiler.js:2430)
    at TemplateParser.push../node_modules/@angular/compiler/fesm5/compiler.js.TemplateParser.parse (compiler.js:20605)
    at JitCompiler.push../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._parseTemplate (compiler.js:26171)
    at JitCompiler.push../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._compileTemplate (compiler.js:26158)

SharedModule :
`const PIPES = [DictsPipe];
// #endregion

@NgModule({
  imports: [...],
  declarations: [
    ...PIPES,
  ],
  exports: [
    ...PIPES,
  ]
})
export class SharedModule { }`

PIPE:
`import { Pipe, PipeTransform } from '@angular/core';

@Pipe({
  name: 'dicts'
})
export class DictsPipe implements PipeTransform {

  transform(value: any, args?: any): any {
    return 'test';
  }

}`

**Comment by cipchk** [comment]
可能你需要需要的模块未导入 `SharedModule`，亦或重新 `ng s`
