### ISSUE TITLE
multiSort 排序问题

### ISSUE THREAD

**Issue by iloveyins** [ng-alain/ng-alain#1149]
https://stackblitz.com/run?file=src/app/app.component.ts

如果是这种，不能进行服务端排序？
 
datas = [{a:1,b:2,c:3}];

  columns: STColumn[] = [
    { title: '行号', type: 'no', fixed: 'left', width: '100px' },
    { title: '店铺编号', index: 'a', fixed: 'left', width: '150px' },
    { title: '实收金额', index: 'b',    sort: true},
  ];

 <st [data]="datas" [columns]="columns"></st>

一定要改成  这种形式？
url='/post/list?pi=1';

<st [data]="url" [columns]="columns"></st>

**Comment by yihango** [comment]
这个问题是怎么解决的？
