### ISSUE TITLE
Select的Tag模式下,每增加一个tag,下拉框中选项重复增加

### ISSUE THREAD

**Issue by zd5043039119** [ng-alain/ng-alain#1152]
- ng-alain version: latest
- Angular version: 7.2.0

## 【必填项】重现链接，Reproduction link

https://stackblitz.com/edit/angular-dmyidt?file=src/app/app.component.ts

## 重现步骤，Steps to reproduce
1.触发select,输入1,然后回车,此时下拉中显示1
2.继续输入2,然后回车,此时下拉中显示1,1,2
3.继续输入3,然后回车,此时下拉中显示1,2,1,2,3

**Comment by cipchk** [comment]
https://github.com/NG-ZORRO/ng-zorro-antd/issues/3559
