### ISSUE TITLE
ng g ng-alain:list xxx  -m=xxx  Invalid 无效

### ISSUE THREAD

**Issue by hennychen** [ng-alain/ng-alain#1155]
-   "ng-alain": "^7.6.1",
 "@angular/cli": "^7.3.8",
   "@angular/compiler-cli": "^7.2.15",

"ng-zorro-antd": "^7.5.0",

## 【必填项】重现链接，Reproduction link
 ng g ng-alain:list  xxx -m=mmm
没有反应 ，没有生成任何文件
之前一直这么用没有问题
升级版本出现的

**Comment by cipchk** [comment]
![image](https://user-images.githubusercontent.com/2987467/59549490-f3cef500-8f90-11e9-8b3e-b1c51fbea796.png)
