### ISSUE TITLE
关于default-interceptor，实际错误处理走向不是预期的

### ISSUE THREAD

**Issue by CK110** [ng-alain/ng-alain#1161]
```
    return next.handle(newReq).pipe(
      mergeMap((event: any) => {
        // 允许统一对请求错误处理
        if (event instanceof HttpResponseBase) return this.handleData(event);
        // 若一切都正常，则后续操作
        return of(event);
      }),
      catchError((err: HttpErrorResponse) => this.handleData(err)),
    );
```

在实际使用的过程中，我这边的情况是，只有event.status是200，才会走`mergeMap`操作，其他状态码都走的是`catchError`，如下图的500错误。

![image](https://user-images.githubusercontent.com/9956098/59586965-ba27f680-9116-11e9-96a8-7a3f1816b5e5.png)

**Comment by cipchk** [comment]
对的呀，任何HTTP状态码返回的是非 `2xx` 都会被认为是错误，最终都会被 `observer.error`，因此这里使用 `catchError` 来获取这种错误，并加于处理。
