### ISSUE TITLE
文档: SF的date的showTime属性支持TimePickerOptions类型的object

### ISSUE THREAD

**Issue by ayaka209** [ng-alain/ng-alain#1162]
- ng-alain version: 7.7.0

## 【必填项】重现链接，Reproduction link
如https://ng.ant.design/components/date-picker/zh所言
```
nzShowTime 中当前支持的 nz-time-picker 参数有：nzFormat, nzHourStep, nzMinuteStep, nzSecondStep, nzDisabledHours, nzDisabledMinutes, nzDisabledSeconds, nzHideDisabledOptions, nzDefaultOpenValue, nzAddOn
```

而当前ng-alain文档描述为仅支持boolean
https://ng-alain.com/form/date/zh

**Comment by cipchk** [comment]
@ayaka209  文档会跟进，但本质上是支持 Object 类型。
