### ISSUE TITLE
ng g ng-alain:list 报错

### ISSUE THREAD

**Issue by wlsun** [ng-alain/ng-alain#1164]
ng-alain升级到7.3.2后运行ng g ng-alain 报错
ng g ng-alain:list account -m=sysmanage
? Specifies relative path(could be set like `bus/list`): 
Unexpected token ] in JSON at position 1213
![image](https://user-images.githubusercontent.com/6070949/59643109-16802a00-919a-11e9-9d64-794a920fc6fe.png)

**Comment by cipchk** [comment]
检查一下 `angular.json` 或 `packgae.json` 是否包注释代码，这会引起 `JSON` 无法解析从而失败。
