### ISSUE TITLE
官网英文title

### ISSUE THREAD

**Issue by its404** [ng-alain/ng-alain#1166]
官网英文的title翻译貌似有点问题，`based on`前边需要一个主语，建议：
A `front-end solution` based on Antd for web applications 或者 A `scaffold` based on Antd for web applications

![Screen Shot 2019-06-19 at 9 12 04 AM](https://user-images.githubusercontent.com/35132886/59720407-de004f00-9272-11e9-8834-b13c39bbdbb8.png)

**Comment by its404** [comment]
@cipchk ，官网的源码在哪呢？我没找到哈，我可以改这个，后边也可以帮忙刷新官网英文部分。

**Comment by cipchk** [comment]
@its404 https://github.com/ng-alain/delon/blob/master/src/app/core/i18n/en-US.ts

**Comment by its404** [comment]
[PR 617](https://github.com/ng-alain/delon/pull/617) merged
