### ISSUE TITLE
不同模块页面切换会报错

### ISSUE THREAD

**Issue by s641135196** [ng-alain/ng-alain#1168]
- ng-alain version: 7.6.1
- Angular version: 7.5.0

## 【必填项】重现链接，Reproduction link
![test](https://user-images.githubusercontent.com/8079013/59748573-f9d51680-92ad-11e9-8e70-0df57239943f.gif)

## 重现步骤，Steps to reproduce

单击 切换‘用户信息‘和'用户信息管理' （‘用户信息‘和'用户信息管理' 所属不同module. 如果是处于同一module的页面切换不报错）
![image](https://user-images.githubusercontent.com/8079013/59748654-21c47a00-92ae-11e9-8302-797f1ea3b451.png)
会报如下错误（不影响使用，但这会让人感觉有错误发生了）
![image](https://user-images.githubusercontent.com/8079013/59748731-4c163780-92ae-11e9-83e4-1f9914cfb0bf.png)

如果通过单击左边的菜单则是正常
![image](https://user-images.githubusercontent.com/8079013/59748848-841d7a80-92ae-11e9-8a20-28ff5a71ce20.png)

**Comment by s641135196** [comment]
不知道为啥在stackblitz.com运行不起来。 麻烦在github下载在本地运行。  
github地址： [https://github.com/s641135196/angular-g9kekk](https://github.com/s641135196/angular-g9kekk)

**Comment by cipchk** [comment]
长时间未提供重现链接，关闭该问题。
