### ISSUE TITLE
Have a question about ng-alain

### ISSUE THREAD

**Issue by ohmygodoh** [ng-alain/ng-alain#117]
First, the framework is very good.
Second I have a question that Development documentation on running this command ng g module trade -- the routing that automatically help us create trade.module.ts and trade-routing.module.ts two ts files, and in terms of the forms folder below the routes, why, found that only forms.module.ts file and without forms-routing.module.ts file.  because the two files together? I am not very clear about that,thank you.

(文档写运行ng g module trade --routing会有两个文件，在demo里，发现只有xxxmodule.ts没有xxx-routing.module.ts文件)

**Comment by cipchk** [comment]
thx.

just historical, i will base on the angular cli standars.
