### ISSUE TITLE
使用 setValue 给checkbox赋值问题

### ISSUE THREAD

**Issue by ZZChaser** [ng-alain/ng-alain#1171]
不管是使用根据路径赋值还是还是rootProperty下的setValue都有问题，打印出来组件下的value已经改变了，但是界面没有改变

**Comment by ZZChaser** [comment]
重现的demo
![html](https://user-images.githubusercontent.com/35095052/59836518-3d975100-937e-11e9-8572-557cac159ef0.png)
![ts](https://user-images.githubusercontent.com/35095052/59836531-412ad800-937e-11e9-920e-1ad413e04bea.png)
![result](https://user-images.githubusercontent.com/35095052/59836540-44be5f00-937e-11e9-81be-b15032e32416.png)

点击test按钮中使用setValue更新值，log中的sf.value已经更改，但是界面还是没有更改

**Comment by ZZChaser** [comment]
再问一问，我给formData重新赋值后，整个form的节点都重新渲染了

**Comment by cipchk** [comment]
> 再问一问，我给formData重新赋值后，整个form的节点都重新渲染了

是的。

另，请提供 stackblitz 重现链接。
