### ISSUE TITLE
@delon升级后， SFSchema中的number类型报错，无法正常渲染页面

### ISSUE THREAD

**Issue by wlsun** [ng-alain/ng-alain#1174]
* 升级后需要去掉@ViewChild中的 ` { static: true }`；
![image](https://user-images.githubusercontent.com/6070949/59841225-7cc9a000-9386-11e9-90f2-c23fc775b06c.png)

* SFSchema 中 number类型页面无法显示
![image](https://user-images.githubusercontent.com/6070949/59841329-aedb0200-9386-11e9-89dd-9725b22e3f81.png)

3. 一直报如下的错误：
![image](https://user-images.githubusercontent.com/6070949/59841537-15602000-9387-11e9-82a2-38093f0a53cb.png)

4. 请问如何解决？感谢!

**Comment by cipchk** [comment]
@wlsun 请务必提供重现示例，脱离环境我无法判断哪里的问题。

> 另，NG-ALAIN 目前还不支持 NG8

**Comment by cipchk** [comment]
长时间未提供重现链接，关闭该问题。
