### ISSUE TITLE
reusetab在浏览器刷新时tab丢失

### ISSUE THREAD

**Issue by 13775072234** [ng-alain/ng-alain#1175]
🚨 Issues 是用于BUG、Feature、进度追踪 🚨
🚨 The issue tracker is not for questions 🚨

如果有任何问题，可在以下方式获得答案：

- https://ng-alain.com/
- QQ Group：316911865
- https://segmentfault.com/t/ng-alain

**Comment by cipchk** [comment]
组件数据非常复杂并非只是单纯的基本类型数据，所以无法持久化。
