### ISSUE TITLE
切换用户时，左侧导航菜单没有根据权限正确显示

### ISSUE THREAD

**Issue by dusdong** [ng-alain/ng-alain#1177]
- ng-alain version: 7.7.1
- Angular version: 7.2.0

## 重现步骤，Steps to reproduce

切换用户时，如果新用户的权限更少，导航菜单可以正确隐藏；如果新用户的权限更多，新增的菜单却没有显示出来。F5刷新后，菜单正常显示。

貌似这个问题在老版本的下没有问题，不知道从今年的版本几开始有问题了。

PS：用户登陆后，设置权限及菜单的语句为：
```
this.aclService.setFull(false);
this.aclService.setRole(result.permissions);
this.menuService.resume((item) => {
    item.hide = item.acl && !this.aclService.can(item.acl);
});
```

我对上述语句进行跟踪调试，menu 的 hide 已经正确赋值了。

**Comment by dusdong** [comment]
重新修改了下代码，问题消失了。谢谢~

**Comment by Lancerxxzz** [comment]
> 重新修改了下代码，问题消失了。谢谢~

最后是怎么处理的 能告诉一下嘛 谢谢！
