### ISSUE TITLE
SF 日期控件默认格式问题

### ISSUE THREAD

**Issue by insov** [ng-alain/ng-alain#1181]
- ng-alain version: 7.7.1
- Angular version: 8.0.2

## 【必填项】重现链接，Reproduction link

https://stackblitz.com/edit/angular-prjsvk

![TIM截图20190624174910](https://user-images.githubusercontent.com/3804453/60009410-65e9bd00-96a8-11e9-8113-4719e009b0a0.png)

## 重现步骤，Steps to reproduce
点击界面中的 重置按钮

> 不指定 schema.format 根据 schema.type 值按以下规则处理（允许通过 DelonFormConfig 替换）数据格式化： string 默认 YYYY-MM-DD HH:mm:ss

首次加载的时候，date控件不会报错，重置之后会提示格式错误。

**Comment by insov** [comment]
#690   同样的错误

**Comment by cipchk** [comment]
@insov `formatDate` 数据并不是标准的 RFC3339 格式。你所引用与重现示例不一致，应该是

> date, full-date default is YYYY-MM-DD

**Comment by insov** [comment]
@cipchk  明白了 
配置改成
` properties: {
      date: {
        type: 'string',
        ui: { widget: 'date' }
      },
    },`

解决问题。
