### ISSUE TITLE
项目npm install后无法启动

### ISSUE THREAD

**Issue by jsdjiazhiheng** [ng-alain/ng-alain#1182]
- ng-alain version: 8.0.0-rc.0
- Angular version: 8.0.1

## 项目启动
下载完项目，运行yarn install 后运行 yarn start就出现以下错误
ERROR in ./src/app/layout/default/header/components/user.component.ts 20:12-25
"export 'ITokenService' was not found in '@delon/auth'
ERROR in ./src/app/routes/passport/login/login.component.ts 167:12-25
"export 'ITokenService' was not found in '@delon/auth'
ERROR in ./src/app/routes/passport/lock/lock.component.ts 35:12-25
"export 'ITokenService' was not found in '@delon/auth'

在手动安装过@delon/auth库后出现以下提示
ERROR in src/app/delon.module.ts(78,56): error TS2339: Property 'forRoot' does not exist on type 'typeof DelonACLModule'.

**Comment by jsdjiazhiheng** [comment]
升级过angluar cli后，上面的错误没有了，提示错误
ERROR in src/app/delon.module.ts(78,56): error TS2339: Property 'forRoot' does not exist on type 'typeof DelonACLModule'.

**Comment by cipchk** [comment]
参考 #1183 解决。
