### ISSUE TITLE
export 'ITokenService' was not found in '@delon/auth' 

### ISSUE THREAD

**Issue by cipchk** [ng-alain/ng-alain#1183]
`8.0.0-rc.0` 版本在开发环境下会收到：

```
export 'ITokenService' was not found in '@delon/auth' 
```

是因为 `@angular-devkit/build-angular` 新版本可能有一处依赖错误引起的 https://github.com/angular/angular-cli/issues/14888 。暂时可以固定为 `0.800.3` 版本来解决：

```
# package.json
"@angular-devkit/build-angular": "0.800.3"
```

**Comment by Alucardxy** [comment]
我把 "@angular-devkit/build-angular": "0.800.3"改成0.800.4也试过了，问题依旧，能不能先不升级到8.0？

**Comment by cipchk** [comment]
@Alucardxy 尝试移除 node_modules & yarn.lock 再安装。

**Comment by Jornve** [comment]
I have the same issue. Tried to remove node_modules and yarn.lock but the problem remains...

Full error: 

```
ERROR in ./src/app/layout/default/header/components/user.component.ts 20:12-25
"export 'ITokenService' was not found in '@delon/auth'
ERROR in ./src/app/routes/passport/login/login.component.ts 167:12-25
"export 'ITokenService' was not found in '@delon/auth'
ERROR in ./src/app/routes/passport/lock/lock.component.ts 35:12-25
"export 'ITokenService' was not found in '@delon/auth'
** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
ℹ ｢wdm｣: Failed to compile.
```

**Comment by cipchk** [comment]
@Jornve Limited to https://github.com/angular/angular-cli/issues/14888 must be fixed 
 `@angular-devkit/build-angular` version number of `0.800.3`

**Comment by 751811032** [comment]
修改angular-devkit/build-angular的版本依旧会报错。有解决方案吗

**Comment by Alucardxy** [comment]
I have tried to remove node_modules and yarn.lock ,and check the @angualr-devkit/build-angular version is 0.800.3,but the problem remains
`ERROR in ./src/app/core/startup/startup.service.ts 132:12-25
"export 'ITokenService' was not found in '@delon/auth'
ERROR in ./src/app/layout/default/header/components/user.component.ts 20:12-25
"export 'ITokenService' was not found in '@delon/auth'
ERROR in ./src/app/routes/passport/login/login.component.ts 167:12-25
"export 'ITokenService' was not found in '@delon/auth'
ERROR in ./src/app/routes/passport/lock/lock.component.ts 35:12-25
"export 'ITokenService' was not found in '@delon/auth'
`
could I create a project of angular 7 and keep ng-alain in version 7?

**Comment by cipchk** [comment]
@Alucardxy Yes,

But, You can trying using `ng s --aot` in developer env in 8.0.0-rc.0

**Comment by Alucardxy** [comment]
ok！--aot is worked

**Comment by 751811032** [comment]
尝试重新解压项目再安装也一样会出现该问题，删掉ITokenService的引用，就可以了，还好调用ITokenService的地方不多

**Comment by Jornve** [comment]
> @Jornve Limited to [angular/angular-cli#14888](https://github.com/angular/angular-cli/issues/14888) must be fixed
> `@angular-devkit/build-angular` version number of `0.800.3`

Thanks @cipchk , after changing the version it works.

**Comment by ant-robert** [comment]
请问 8.0正式发布是什么时候

**Comment by cipchk** [comment]
@ant-robert 估计至 `rc.2`

**Comment by Alucardxy** [comment]
use @angular-devkit/build-angular version number of 0.800.6 had fixed this problem
