### ISSUE TITLE
部署到nginx，登录验证报错405

### ISSUE THREAD

**Issue by codingzhou** [ng-alain/ng-alain#1184]
本地跑没问题，放到nginx上之后，登录验证报错405
![image](https://user-images.githubusercontent.com/14120629/60076934-668f5b80-975b-11e9-8149-cc57d1fd6b9d.png)

**Comment by cipchk** [comment]
`405` 应该是API请求方法（`GET` `POST` 等）不允许，这是 nginx 配置的问题或其他后端方面的问题引起的。

**Comment by codingzhou** [comment]
@cipchk 卡色大佬，图上调用的/login/account地址，项目中应该是调用_mock下的api地址，但是线上调用了http请求，没有调用mock请求，可以看到从线上/本地服务器分别针对/login/account的调用是http和mock，前者报错
![image](https://user-images.githubusercontent.com/14120629/60077665-0f8a8600-975d-11e9-808c-6273249e48c0.png)
![image](https://user-images.githubusercontent.com/14120629/60077677-174a2a80-975d-11e9-846a-7831b4601ea2.png)

**Comment by cipchk** [comment]
@codingzhou 无疑就是后端的问题，自行配合后端人员一起核实。

**Comment by codingzhou** [comment]
@cipchk 这个demo并没有后端，是干净的ng alain脚手架初始化出来的项目，直接放到nginx上跑的，没有做其他更改。。

**Comment by cipchk** [comment]
@codingzhou 默认 build 时不会打 mock 打包进来，若需要生产环境使用 Mock，请至delon.module.ts，细节请自行查阅 ng-alain.com 文档 中心。

**Comment by codingzhou** [comment]
@cipchk 明白了，就是生产环境没有把mock包加进来的原因，找不到mock serve，所以去请求真实的http，因此报错了，已经解决，谢谢大佬
