### ISSUE TITLE
构建失败，报错 Cannot find name 'module'.Do you need to install type definitions for node?

### ISSUE THREAD

**Issue by zpaul** [ng-alain/ng-alain#1185]
- ng-alain version: ^7.7.1
- Angular version: ~8.0.1

## 重现步骤，Steps to reproduce
按照 https://ng-alain.com/docs/getting-started/en
的说明，
执行
ng new my-project --style less
cd my-project
ng add ng-alain
npm start
后，
报以下错误：
src/main.ts(28,7): error TS2591: Cannot find name 'module'. Do you need to install type definitions for node? Try `npm i @types/node` and then add `node` to the types field in your tsconfig.
src/main.ts(29,18): error TS2591: Cannot find name 'module'. Do you need to install type definitions for node? Try `npm i @types/node` and then add `node` to the types field in your tsconfig.

**Comment by cipchk** [comment]
可能在两个相关 #1186  #1183

**Comment by zpaul** [comment]
已解决，十分感谢
