### ISSUE TITLE
npm start 构建失败

### ISSUE THREAD

**Issue by dvorakchen** [ng-alain/ng-alain#1186]
- ng-alain version: stable
- Angular version: 8.0.4

## 【必填项】重现链接，Reproduction link

npm start 构建失败
在wondows 7 下和windows 10 下都是一样。
npm 版本 6.9.0
使用ng new admin --style less
使用 ng add ng-alain
接下来的选项全部选 y
然后 npm start，出现：
![屏幕截图(2)](https://user-images.githubusercontent.com/50647468/60100234-dfa6a700-978b-11e9-834a-007f1ebeba36.png)

## 重现步骤，Steps to reproduce
使用ng new admin --style less
使用 ng add ng-alain
接下来的选项全部选 y
然后 npm start
构建失败
没有其他的任何操作

**Comment by cipchk** [comment]
目前 Angular8 是在 `next` 版本上，文档的错误，正确应该是：

```bash
ng add ng-alain@next
```
