### ISSUE TITLE
加载了JWT实现后没起到作用，也看了你写的文档，求指点，版本就是当前时间

### ISSUE THREAD

**Issue by laosandegudai** [ng-alain/ng-alain#119]
## Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
```

**Comment by cipchk** [comment]
请认真核查模块导入等问题。

若问题依旧烦请提供所有当前的细节以便讨论。

**Comment by ziben** [comment]
@laosandegudai 
我之前也是这样，在app.module里声明拦截器，但是拦截器没有被调用。
后来把HttpClientModule的导入从SharedModule移到了AppModule里就可以了。

但是，当前的jwt拦截器还有一个bug，还不能正常使用。

**Comment by ulo-huangsz** [comment]
人GV地方v

**Comment by cipchk** [comment]
长时间未处理；有任何问题重新提交issues。
