### ISSUE TITLE
动态表单 移动端布局

### ISSUE THREAD

**Issue by charlee2025** [ng-alain/ng-alain#1191]
希望能提供这样的特性：动态表单在移动端展示的时候，可以是标签和输入框纵向排列的，因为有时候label会比较长，不太好处理。就像这样：
![image](https://user-images.githubusercontent.com/8101989/60266547-ced86b80-991a-11e9-8c3d-06ce8d000ad4.png)

**Comment by cipchk** [comment]
麻烦提供重现示例，若不是很麻烦的情况可以我会修复，但是 zorro 目前不考虑移动端。

**Comment by charlee2025** [comment]
@cipchk 非常抱歉，之前写的描述没有提交成功，才看到。

**Comment by cipchk** [comment]
关于这一点本身已经就是适配的：

[png]
![image](https://user-images.githubusercontent.com/2987467/60270905-ee27c680-9923-11e9-9938-65b70d3f5451.png)

**Comment by charlee2025** [comment]
@cipchk 请问有示例代码吗？我这效果不是这样。我想着是PC上label和input在同一行，在移动端是占两行这样响应式的。

**Comment by charlee2025** [comment]
@cipchk 或者是需要升级版本吗？我看文档里面的示例是可以的，我的不行。我的是7.2版本的

**Comment by NanFengCheong** [comment]
@lichangfeng  Need to change sf layout to 'vertical'.
`<sf [layout]="'vertical'" [schema]="schema">`
