### ISSUE TITLE
sf render speed

### ISSUE THREAD

**Issue by NanFengCheong** [ng-alain/ng-alain#1199]
Currently I have a huge schema, refreshSchema may take more 2-3 seconds to complete.
This is just a suggestion, it is possible to refresh only the changed property by comparing new schema and existing schema to improve the render speed?

**Comment by NanFengCheong** [comment]
Speed improved after production build.

**Comment by NanFengCheong** [comment]
![image](https://user-images.githubusercontent.com/7321833/60513012-af6d8400-9d08-11e9-8e63-86656fa92fd8.png)

@cipchk 是否可以帮忙看下。

[Profile-20190702T203047.zip](https://github.com/ng-alain/ng-alain/files/3350027/Profile-20190702T203047.zip)

**Comment by cipchk** [comment]
长时间未提供重现链接，关闭该问题。
