### ISSUE TITLE
feat(editor): new @delon/editor component plans!

### ISSUE THREAD

**Issue by cipchk** [ng-alain/ng-alain#120]
Based on the Ant-Design editor.

- [ ] Support WYSIWYG
    - [ ] Support Bold, Italic, Underline, H1, H2, H3, Blockquote, Code, Inline code, Ul, Ol, Link, Image
- [ ] Support Markdown
    - [ ] Editor
    - [ ] Word count
    - [ ] Sync preview
- [ ] Auto save (draft)
- [ ] Switch WYSIWYG & Markdown, but not content conversion
- [ ] I18n
- [ ] Custom button

if you have better suggestions!! :smile:

**Comment by DreamPWJ** [comment]
1. Hope to support more chart components or add custom attribute 2. User permission management system.

**Comment by winpzs** [comment]
感觉好多东西不完善，还不如先完善再做。
