### ISSUE TITLE
st  STColumnButton type 是否可以支持 input输入

### ISSUE THREAD

**Issue by ant-robert** [ng-alain/ng-alain#1201]
![image](https://user-images.githubusercontent.com/52145938/60378955-3e567400-9a5d-11e9-91a2-049fcf2ffc67.png)

**Comment by cipchk** [comment]
`st` 不会考虑增加表单功能。

**Comment by ant-robert** [comment]
那这种需求 只能用ngzorro 解决?

**Comment by cipchk** [comment]
是的，建议使用原生的写法。

**Comment by ant-robert** [comment]
OK 谢谢
