### ISSUE TITLE
降低耦合度，如果只是用acl包，还需要theme包

### ISSUE THREAD

**Issue by CK110** [ng-alain/ng-alain#1204]
![image](https://user-images.githubusercontent.com/9956098/60408021-b81e6700-9bef-11e9-928c-0fcce622b122.png)

在不引入theme包的情况下，自定义这个样式类也可以，不过还是直接在ACL包里面处理比较好

**Comment by cipchk** [comment]
是的，参考：https://github.com/ng-alain/delon/blob/master/packages/theme/styles/app/delon/_acl.less

> 主要还是指令不支持 `styles`，不然就无须这样子。
