### ISSUE TITLE
reuse-tab 不能复用，点击多个只会在tab显示一个选项卡

### ISSUE THREAD

**Issue by ant-robert** [ng-alain/ng-alain#1206]
🚨 Issues 是用于BUG、Feature、进度追踪 🚨
🚨 The issue tracker is not for questions 🚨

![image](https://user-images.githubusercontent.com/52145938/60415925-29214700-9c0f-11e9-834d-bbf9dde806d4.png)

**Comment by cipchk** [comment]
@ant-robert  请提供重现示例。

> 另，请自行根据 https://github.com/ng-alain/ng-alain/blob/master/src/app/delon.module.ts#L20 步骤核实是否遗漏。
