### ISSUE TITLE
Multiple projects are defined; please specify a project name

### ISSUE THREAD

**Issue by TheAifam5** [ng-alain/ng-alain#1208]
- ng-alain version: all
- Angular version: 7.0.0 ... 8.0.0

## Steps to reproduce
1. Create multiple projects
2. Install `ng-alain` using `ng add ng-alain`.
3. Throws an error `Multiple projects are defined; please specify a project name`

## Full log
```
? Which default language would you like to use? English
? Would you like to add hmr plugin? (default: Y) Yes
? Would you like to add code style plugin? (default: Y) Yes
? Would you like to add dynamic form (sf component) plugin? (default: Y) Yes
? Would you like to add mock plugin? (default: Y) Yes
? Would you like to add i18n plugin? (default: N) Yes
? Would you like to add g2 chart plugin? (default: N) Yes
Multiple projects are defined; please specify a project name
```

I know that the library is added, but the generator/migrator thing does not work. I need do that by hand right now and I don't see a documentation how can I do everything manually.

## Similar issues
https://github.com/ng-alain/ng-alain/issues/535

**Comment by cipchk** [comment]
@TheAifam5 `ng-add` can only be built on a clean Angular8 (via `ng new`). If you want to create multiple applications in an Angular project, Recommend simply modifying `angular.json` to implement multiple application. like this:

```json
{
	"projects": {
		"app1": {},
		"app2": {}
	}
}
```

**Comment by cipchk** [comment]
Closing as per above answer.
