### ISSUE TITLE
sidebar折叠菜单栏时样式问题

### ISSUE THREAD

**Issue by expcat** [ng-alain/ng-alain#1209]
- ng-alain version: 8.0.0-rc.1
- Angular version: 8.0.6

## 【必填项】重现链接，Reproduction link

https://ng-alain.github.io/ng-alain/#/dashboard/v1

![image](https://user-images.githubusercontent.com/4289694/60474106-ab0e8000-9ca2-11e9-8fdc-b5f54917d85c.png)

## 重现步骤，Steps to reproduce

点击折叠左侧菜单栏

**Comment by cipchk** [comment]
duplicated of #1203
