### ISSUE TITLE
The theme color custom modification doesn't work

### ISSUE THREAD

**Issue by DreamPWJ** [ng-alain/ng-alain#121]
themes: { l: ThemeType, bg: string, nav: string, con: string }[] = [
        { l: 'A', bg: '#108ee9', nav: '#108ee9', con: '#f5f7fa' },
        { l: 'B', bg: '#00a2ae', nav: '#fff', con: '#f5f7fa' },
        { l: 'C', bg: '#00a854', nav: '#fff', con: '#f5f7fa' },
        { l: 'D', bg: '#f04134', nav: '#fff', con: '#f5f7fa' },
        { l: 'E', bg: '#373d41', nav: '#fff', con: '#f5f7fa' },
        { l: 'F', bg: '#108ee9', nav: '#404040', con: '#f5f7fa' },
        { l: 'G', bg: '#00a2ae', nav: '#404040', con: '#f5f7fa' },
        { l: 'H', bg: '#00a854', nav: '#404040', con: '#f5f7fa' },
        { l: 'I', bg: '#f04134', nav: '#404040', con: '#f5f7fa' },
        { l: 'J', bg: '#373d41', nav: '#404040', con: '#f5f7fa' }
    ];

**Comment by DreamPWJ** [comment]
The main head and side bars are blue

**Comment by cipchk** [comment]
About [customize theme](http://ng-alain.com/docs/theme)

**Comment by DreamPWJ** [comment]
Thank you for knowing that it is more common to recommend adding a whole blue theme

**Comment by cipchk** [comment]
ng-alain allows you to customize some basic theme to meet the needs of diversity.

**Comment by DreamPWJ** [comment]
Thank you very much for providing such a scaffold
