### ISSUE TITLE
g2-single-bar 渲染异常问题

### ISSUE THREAD

**Issue by FE-Master** [ng-alain/ng-alain#1211]
- 我放了个g2-single-bar在table 中，但是初始化的时候前面几个的长度是不准的。
  
![issues](https://user-images.githubusercontent.com/52437182/60480893-e10d2d80-9cbd-11e9-82dc-ed97f80f0a6a.png)

 需要缩放一下窗口才可以准确显示出来。
![issues1](https://user-images.githubusercontent.com/52437182/60480970-23cf0580-9cbe-11e9-9ab5-6f721c35a299.png)

附上代码 html
![code](https://user-images.githubusercontent.com/52437182/60481082-81fbe880-9cbe-11e9-900a-c0d7a3e8451a.png)

.ts
![code2](https://user-images.githubusercontent.com/52437182/60481090-8d4f1400-9cbe-11e9-8aa2-c8e4bdfb1e57.png)

**Comment by cipchk** [comment]
尝试使用 `delay` 来延迟渲染。

> 长时间未提供重现链接，关闭该问题。
