### ISSUE TITLE
更新到最新版本，路由中带参数的页面报错

### ISSUE THREAD

**Issue by wushuxuan** [ng-alain/ng-alain#1213]
![image](https://user-images.githubusercontent.com/30644407/60580364-8e17a100-9db7-11e9-92a3-970447bdc191.png)

路由配置：
![image](https://user-images.githubusercontent.com/30644407/60580426-adaec980-9db7-11e9-99b4-db3d38759cd2.png)

各版本信息
![image](https://user-images.githubusercontent.com/30644407/60580458-bacbb880-9db7-11e9-8b7f-246632acf37d.png)

**Comment by hennychen** [comment]
看样子说的是NzModalService  没有在app.module引入吧

**Comment by wushuxuan** [comment]
@hennychen   但是我引入了还是报错
![image](https://user-images.githubusercontent.com/30644407/60635508-a7ffc500-9e45-11e9-88dc-5618e66d50fe.png)


![image](https://user-images.githubusercontent.com/30644407/60635516-ab934c00-9e45-11e9-878f-013983263110.png)

**Comment by hennychen** [comment]
建议你检查一下 对应的哪个文件报错，去查一下

**Comment by wushuxuan** [comment]
@hennychen   只要是路由带参的页面都会抱这个错，很奇怪，不带参数的就不报

**Comment by cipchk** [comment]
@wushuxuan 麻烦提供一下复现示例

**Comment by weirui** [comment]
你的问题解决了？，我好像遇到类似问题了

**Comment by xiaohei189** [comment]
你的问题解决了？，我好像遇到类似问题了 @wushuxuan

**Comment by wushuxuan** [comment]
@weirui    angular版本的问题，更新 @angular/*  到8.0.1版本

**Comment by xiaohei189** [comment]
谢谢，忘记恢复了，锁定一个版本就好了
