### ISSUE TITLE
移动端下footer-toolbar遮挡表单

### ISSUE THREAD

**Issue by charlee2025** [ng-alain/ng-alain#1215]
- ng-alain version: X.Y.Z
- Angular version: X.Y.Z

## 【必填项】重现链接，Reproduction link

这会儿上不了Stackblitz，稍后补充上

## 重现步骤，Steps to reproduce
使用sf表单和footer-toolbar，footer-toolbar遮挡表单项
![image](https://user-images.githubusercontent.com/8101989/60640505-1058a180-9e5a-11e9-9afa-870bf8f82c94.png)

**Comment by cipchk** [comment]
长时间未提供重现链接，关闭该问题。
