### ISSUE TITLE
按照文档操作, 默认首页要登陆而不是主页

### ISSUE THREAD

**Issue by ToMakeSense** [ng-alain/ng-alain#1216]
按照文档https://netlify.ng-alain.com/docs/getting-started/ 操作, 默认首页要登陆而不是主页，如何解决？
![image](https://user-images.githubusercontent.com/6244148/60642665-4d756180-9e63-11e9-94cd-a489fc931719.png)

**Comment by cipchk** [comment]
By default enabled authentication in ng-alain preview site, pls refer [@delon/auth](https://ng-alain.com/auth/getting-started/en).

**Comment by ToMakeSense** [comment]
解决了，原来是我的其他Demo记住了用户名密码，用的也是Admin/XXXX系列，chrome记住了用户名密码。加载ng-alain Demo的时候，把默认的登录信息覆盖了。删除记住的密码，刷新，ng-alain Demo默认的用户名密码就填充上了，点登陆就进去了。脑子秀逗了。。。

**Comment by ToMakeSense** [comment]
删除记住的密码，刷新，ng-alain Demo默认的用户名密码就填充上了，点登陆就进去了。脑子秀逗了。。。
