### ISSUE TITLE
在app.module里设置了STConfig的全局变量：page：{front：false}，但是在页面的st里再设置front:true后不起作用。

### ISSUE THREAD

**Issue by link1206** [ng-alain/ng-alain#1218]
- ng-alain version: ^8.0.0-rc.1
- Angular version:8.0.3

## 【必填项】重现链接，https://stackblitz.com/edit/ng-alain-setup-wjxksg
![image](https://user-images.githubusercontent.com/22811949/60660691-e10e5880-9e8a-11e9-8e30-6b821bf6f469.png)
![image](https://user-images.githubusercontent.com/22811949/60660730-f08da180-9e8a-11e9-84e3-32d6628688ea.png)

## 重现步骤，Steps to reproduce
在app.module.ts里定义了STConfig全局属性 page：{front:fasle} 也及时默认分页使用服务端的
需求是某个页面想使用前端进行分页 在st里设置<st [data]="data"   [columns]="columns"  [page]="{front:true}"></st>  还是走的服务端分页 也就是说这样设置没有效果

**Comment by cipchk** [comment]
@link1206 请提供一个复现地址，你提供的地址有并没有复现该问题。

**Comment by link1206** [comment]
> @link1206 请提供一个复现地址，你提供的地址有并没有复现该问题。
sorry,正确的地址已修改。
