### ISSUE TITLE
sf组件需要一个可以同时设置多个form表单值的setValue方法

### ISSUE THREAD

**Issue by xiaotupansy** [ng-alain/ng-alain#1221]
如题。

现有的setValue方法，只能一次性设置一个值。
假定有个字段a，当修改它的值的时候我希望同时修改字段b的值，那么我需要调用2次setValue方法。
这个时候会产生一个问题，就是它会调用两次formChange事件，这会导致一些不可控的行为。

**Comment by cipchk** [comment]
`sf` 的校验与数据更新都是异步行为，我们很难做到哪一次更新不想事件触 发，若需要多次则使用 `refreshSchema` 来重置。

**Comment by xiaotupansy** [comment]
我需要解决的不是更新不想触发事件。
我是说
SFComponent.setValue这个方法，能不能有个扩展。
以前setValue改变的是form里面单个元素的值
现在我想对其中的某些元素做些定制，改变它的值的时候，同时触发更改其它form元素的值

假设有两个输入框a和b，假设b=2*a
我想做到的是，当a里面输入1的时候，b的值可以自动变成2，
那么在sf组件中，就需要一个a的setValue方法，这个setValue可以一次性的写入两个值

以下代码是在用的代码，继承自ControlWidget：

            this.setValue(this.obj['Id']);
            const item = this.sfComp.getProperty('/' + this.ui['name']);
            item.setValue(this.obj, false);

这段代码的问题在于调用了两次setValue，我希望只用调用一次setValue就可以赋值了
