### ISSUE TITLE
ACLService cannot get singleton instance

### ISSUE THREAD

**Issue by zd5043039119** [ng-alain/ng-alain#1223]
- ng-alain version: 8.0.0
- Angular version: 8.1.0

1.在login.component.ts中登录后用ACLService的setRole,并console可见aclService.data.role有数据
2.刷新页面后在app.component.ts中注入的aclService的console结果中aclService.data.role无数据
3.不刷新页面,通过route进入懒加载模块,aclService一样没有role数据

由于涉及代码太多不太好提供链接,但是官方Demo只是一个简单场景,不包含懒加载或router.navigate情况,能否在ng-alain中进行测试

**Comment by cipchk** [comment]
@zd5043039119 文档站有一个示例是关于 ACL https://ng-alain.com/form/acl/en  并且属于懒模块范围；若有其他问题请提供重现示例。

**Comment by NanFengCheong** [comment]
我也是遇到一样的问题。
需要在两个module import DelonACLModule
delon.module.ts 
```
@NgModule({
  imports: [AlainThemeModule.forRoot(), DelonACLModule.forRoot()],
})
```
shared.module.ts
```
@NgModule({
  imports: [DelonACLModule],
})
```

**Comment by zd5043039119** [comment]
@NanFengCheong 感谢,按照你的方法确实可以了,之前升级完后尝试过一种是只在shared.module.ts里面更改了 DelonACLModule.forRoot(),另一种是在app.module.ts中添加了DelonACLModule.forRoot(),而把shared.module.ts中的移除,能请教是什么原因么
@cipchk 我尝试模拟个重现示例出来

**Comment by zd5043039119** [comment]
@cipchk 重现链接
https://stackblitz.com/edit/angular-pmdp4s-sioudn?file=src%2Fapp%2Fapp.component.ts

操作步骤,在route1,看console日志
```
app.component.ts:19 app component init {full: false, roles: Array(0), abilities: Array(0)}
app.component.ts:20 app component mock add role
app.component.ts:22 app component mock add role - done {full: false, roles: Array(2), abilities: Array(0)}
route1.component.ts:19 route1 {full: false, roles: Array(2), abilities: Array(0)}
```
然后点击route2,看日志
```
route2.component.ts:19 route2 {full: false, roles: Array(0), abilities: Array(0)}
```
route2为懒加载的路由,可见没有了roles,

然后换一下,先访问
https://angular-pmdp4s-sioudn.stackblitz.io/lazy/route2
输出为
```
app component init {full: false, roles: Array(0), abilities: Array(0)}
app.component.ts:20 app component mock add role
app.component.ts:22 app component mock add role - done {full: false, roles: Array(2), abilities: Array(0)}
console.ts:15 Angular is running in the development mode. Call enableProdMode() to enable the production mode.
route2.component.ts:19 route2 {full: false, roles: Array(0), abilities: Array(0)}
```
点击route1
```
route1.component.ts:19 route1 {full: false, roles: Array(2), abilities: Array(0)}
```
懒加载的route2还是没有roles

**Comment by zd5043039119** [comment]
看了一下
https://medium.com/slackernoon/when-to-use-angulars-forroot-method-400094a0ebb7
大致理解了,
但我在另一个项目中确实是将DelonACLModule.forRoot()写到了app.module.ts,过两天确认下,现在没有问题了
