### ISSUE TITLE
 error TS1323: Dynamic import is only supported when '--module' flag is 'commonjs' or 'esNext'.

### ISSUE THREAD

**Issue by hennychen** [ng-alain/ng-alain#1224]
- ng-alain version: 8.0.0
- Angular version: 8.0.3

## 【必填项】重现链接，Reproduction link
 ERROR in src/app/routes/routes-routing.module.ts(38,29): error TS1323: Dynamic import is only supported when '--module' flag is 'commonjs' or 'esNext'.
    src/app/routes/routes-routing.module.ts(45,29): error TS1323: Dynamic import is only supported when '--module' flag is 'commonjs' or 'esNext'.
    src/app/routes/routes-routing.module.ts(52,29): error TS1323: Dynamic import is only supported when '--module' flag is 'commonjs' or 'esNext'.
    src/app/routes/routes-routing.module.ts(56,43): error TS1323: Dynamic import is only supported when '--module' flag is 'commonjs' or 'esNext'.
    src/app/routes/routes-routing.module.ts(59,42): error TS1323: Dynamic import is only supported when '--module' flag is 'commonjs' or 'esNext'.
    src/app/routes/routes-routing.module.ts(62,42): error TS1323: Dynamic import is only supported when '--module' flag is 'commonjs' or 'esNext'.
    src/app/routes/routes-routing.module.ts(67,29): error TS1323: Dynamic import is only supported when '--module' flag is 'commonjs' or 'esNext'.
    src/app/routes/routes-routing.module.ts(70,43): error TS1323: Dynamic import is only supported when '--module' flag is 'commonjs' or 'esNext'.
    src/app/routes/routes-routing.module.ts(74,29): error TS1323: Dynamic import is only supported when '--module' flag is 'commonjs' or 'esNext'.
    src/app/routes/routes-routing.module.ts(77,44): error TS1323: Dynamic import is only supported when '--module' flag is 'commonjs' or 'esNext'.
    src/app/routes/routes-routing.module.ts(82,29): error TS1323: Dynamic import is only supported when '--module' flag is 'commonjs' or 'esNext'.
    src/app/routes/routes-routing.module.ts(88,29): error TS1323: Dynamic import is only supported when '--module' flag is 'commonjs' or 'esNext'.

![image](https://user-images.githubusercontent.com/2526830/60754871-3af15880-a01a-11e9-9f19-6fe1b5bc0ba0.png)

tsconfig.json
![image](https://user-images.githubusercontent.com/2526830/60754876-4cd2fb80-a01a-11e9-878f-4c085ad4bbce.png)

**Comment by cipchk** [comment]
应该是缺少设置 `tsconfig.json` 里的 `"module": "esnext"`，因为 `loadChildren: () => import('./style/style.module')` 写法只允许 `esnext` 时有效。

**Comment by hennychen** [comment]
我上面截图就是tsconfig.json 里面也设置了。很奇怪 ，我想知道如果不按照 angular 8 的写法 有什么影响吗

**Comment by cipchk** [comment]
没有影响，只是无法使用差异加载。
