### ISSUE TITLE
ng build --prod error

### ISSUE THREAD

**Issue by hennychen** [ng-alain/ng-alain#1225]
- ng-alain version:8.0.0
- Angular version: 8.0.3

## 【必填项】重现链接，Reproduction link

![image](https://user-images.githubusercontent.com/2526830/60768206-e4a51800-a0f4-11e9-8255-588990306b58.png)

**Comment by hennychen** [comment]
npm run color-less && node --max_old_space_size=8192 ./node_modules/@angular/cli/bin/ng build --prod

**Comment by everfire130** [comment]
@hennychen 我也遇到这样的问题，如何解决呢？
