### ISSUE TITLE
版本升级8.0.0 ng  serve 报错

### ISSUE THREAD

**Issue by iloveyins** [ng-alain/ng-alain#1226]
![image](https://user-images.githubusercontent.com/18527569/60779672-2e7e1480-a16e-11e9-8988-3381d91984df.png)

**Comment by cipchk** [comment]
从两个层面试着解决：

1. 自行检查 `tsconfig.json` （包含 `tsconfig.app.json`、`tsconfig.spec.json`）是否缺少什么参数
2. 移除 `node_modules`、`yarn.lock` 并重新安装依赖包

除此之外我也没有别的有效建议。

**Comment by iloveyins** [comment]
好的  谢谢
