### ISSUE TITLE
sf动态表单报错

### ISSUE THREAD

**Issue by liuyun521** [ng-alain/ng-alain#1229]
- ng-alain version: 7.5.0
- Angular version: 7.2.15

ts如下
![image](https://user-images.githubusercontent.com/9554224/60854388-ac0b5880-a232-11e9-9bba-237f508084d9.png)

html
![image](https://user-images.githubusercontent.com/9554224/60854401-bcbbce80-a232-11e9-9195-9f1d72526a8e.png)

但在页面运行时，出现如下错误

![image](https://user-images.githubusercontent.com/9554224/60854422-cf360800-a232-11e9-8f43-53c77aea99d2.png)

**Comment by leeuoo11** [comment]
[https://github.com/ng-alain/ng-alain/issues/836](url)

**Comment by leeuoo11** [comment]
#836
