### ISSUE TITLE
0.4.0  rc3不正常

### ISSUE THREAD

**Issue by jiankian** [ng-alain/ng-alain#123]
报错信息：
<img width="941" alt="qq20171220-025534 2x" src="https://user-images.githubusercontent.com/9036838/34173730-6a79deec-e531-11e7-9cf0-fff767339a76.png">
我的环境：
<img width="626" alt="qq20171220-025718 2x" src="https://user-images.githubusercontent.com/9036838/34173765-86b047f4-e531-11e7-901d-f1d0a7b0f588.png">

**Comment by cipchk** [comment]
[full.component](https://github.com/cipchk/ng-alain/blob/master/src/app/routes/tables/full/full.component.ts#L37) 请重新对比一下。
