### ISSUE TITLE
异步设置reuseTabService.title时切换tab导致title错乱

### ISSUE THREAD

**Issue by KellenHe** [ng-alain/ng-alain#1230]
1.异步回调中设置reuseTabService.title，比如http回调。
2.在回调还未完成时切换reuseTab到别的界面
3.回调完成后会改变当前激活的reuseTab界面，而不是代码所在的界面。

请问这种有什么好的办法避免吗？

**Comment by cipchk** [comment]
未执行完的 `Observable` 最好在 `ngOnDestroy` 取消结束这些订阅。

**Comment by KellenHe** [comment]
如果在ngOnDestroy 中结束订阅，再次切换回该tab页的话，还需要再次请求，体验不是很好。

**Comment by houkongquan12138** [comment]
> 如果在ngOnDestroy 中结束订阅，再次切换回该tab页的话，还需要再次请求，体验不是很好。

有解决方法么

**Comment by cipchk** [comment]
可以将异步 title 放入 Signal 就很好的简单这类问题。
