### ISSUE TITLE
打包后运行出现 VERSION_ALAIN is not defined

### ISSUE THREAD

**Issue by SuperRichZhao** [ng-alain/ng-alain#1235]
🚨 Issues 是用于BUG、Feature、进度追踪 🚨
🚨 The issue tracker is not for questions 🚨

如果有任何问题，可在以下方式获得答案：

- https://ng-alain.com/
- QQ Group：316911865
- https://segmentfault.com/t/ng-alain

**Comment by cipchk** [comment]
可以明确是存在的，尝试重新安装依赖包看看。
