### ISSUE TITLE
[STColumn] Index couldn't support string[]

### ISSUE THREAD

**Issue by FE-Master** [ng-alain/ng-alain#1238]
I found that I could't use  string array for Index in STColumn. 

![image](https://user-images.githubusercontent.com/52437182/61130407-3250c480-a4e9-11e9-8e58-3d0e6a61cc2d.png)

**Comment by cipchk** [comment]
https://github.com/ng-alain/delon/blob/master/packages/abc/table/test/table-column-source.spec.ts#L55
