### ISSUE TITLE
直接本地运行ng-align，会出现按钮之间的空格丢失的问题

### ISSUE THREAD

**Issue by ziben** [ng-alain/ng-alain#124]
## Bug Report or Feature Request (mark with an `x`)
<pre><code>
[x] Bug report -> please search issues before submitting
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

When I run "npm start", the whitespace between buttons disappear.
![image](https://user-images.githubusercontent.com/614036/34188509-c119c3d0-e571-11e7-8aeb-b351e91119c8.png)

## Expected behavior

When I run "npm run build", then visit the dist, the display is normal.
![image](https://user-images.githubusercontent.com/614036/34188525-ced49d56-e571-11e7-8257-43c92006361d.png)

## Environment

<pre><code>
Angular version: X.Y.Z

delon version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX

For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

I think the problem is the "preserveWhitespaces: false" when bootstrapModule.

**Comment by cipchk** [comment]
Yes, but it can improve the generated code size and speed components creation.

Also, you can using `pl-sm` `pr-sm` etc to change padding, about more class rule going to [ng-alain.com](http://ng-alain.com/docs/style) website.
