### ISSUE TITLE
ST 可选列显示+Tag标签 会出现渲染Tag报错

### ISSUE THREAD

**Issue by jol5** [ng-alain/ng-alain#1240]
- ng-alain version: 8.1.0
- Angular version: 8.1.1

## 【必填项】重现链接，Reproduction link

- 重现链接：https://stackblitz.com/run?file=src/app/app.component.ts
- 截图：
![image](https://user-images.githubusercontent.com/28615922/61168153-37ab1f00-a57c-11e9-89ee-b2483a9dcc29.png)

**Comment by cipchk** [comment]
@jol5 麻烦提供一个有效的重现链接。

**Comment by jol5** [comment]
> @jol5 麻烦提供一个有效的重现链接。

https://stackblitz.com/run?file=src/app/app.component.ts 已提供

**Comment by cipchk** [comment]
长时间未提供重现链接，关闭该问题。
