### ISSUE TITLE
st tooltip 不消失

### ISSUE THREAD

**Issue by hennychen** [ng-alain/ng-alain#1242]
- ng-alain version: 8.0.0
- Angular version: 8.0.3

## 【必填项】重现链接，Reproduction link
 鼠标hover 会出现tooltip 提示，点击 用 router.navigate 跳转到新标签，tooltip 不消失，
可否增加tooltip 的 属性，用户来设置是否显示或隐藏

**Comment by cipchk** [comment]
duplcated of https://github.com/NG-ZORRO/ng-zorro-antd/issues/1530
