### ISSUE TITLE
g2-bar在nz-tab组件中渲染异常

### ISSUE THREAD

**Issue by Duaneding** [ng-alain/ng-alain#1244]
- ng-alain version: 7.6.0
- Angular version: 7.2.0

如下图所示，
1.使用nz-tabset组件，包含3个页签；
2.使g2-bar组件作为页签内容填充；
3.切换页签，发现只有只有第一个页签的g2-bar正常渲染，其他第二、第三个页签g2-bar都渲染异常，包括饼状图也会出现同样问题。
![question](https://user-images.githubusercontent.com/37576723/61206928-5d742780-a726-11e9-9e77-2cc9fa736a67.jpeg)

**Comment by cipchk** [comment]
`nz-tabset` 的实现会导致在渲染 G2 时无法获取容器的高度，可以参考分析页的实现 https://github.com/ng-alain/ng-alain/blob/master/src/app/routes/dashboard/analysis/analysis.component.html#L108

**Comment by Duaneding** [comment]
ok,解决了，是个渲染顺序的问题

**Comment by Kacoo** [comment]
@Duaneding 请问后面怎么解决的？没看出渲染顺序的区别orz
