### ISSUE TITLE
st.reset()或st.load()方法使用后异常

### ISSUE THREAD

**Issue by listennatural** [ng-alain/ng-alain#1246]
- ng-alain version: 8.0.3
- Angular version: 

## 【必填项】重现链接，Reproduction link

![深度截图_选择区域_20190719111126](https://user-images.githubusercontent.com/38430895/61506888-3499ae00-aa16-11e9-8975-c6885fbeddeb.png)
![深度截图_选择区域_20190719111147](https://user-images.githubusercontent.com/38430895/61506892-36637180-aa16-11e9-8cc8-8c222f17481d.png)
![深度截图_选择区域_20190719111303](https://user-images.githubusercontent.com/38430895/61506893-37949e80-aa16-11e9-810d-f5bb4fc74ec9.png)

## 重现步骤，Steps to reproduce
指定 st表格 data 为 url ,设置表格重置方法
![深度截图_选择区域_20190719111401](https://user-images.githubusercontent.com/38430895/61506928-52ffa980-aa16-11e9-85d5-d12ff545737d.png)
请求参数处理以及返回参数处理方法设置
![深度截图_选择区域_20190719111517](https://user-images.githubusercontent.com/38430895/61506974-7f1b2a80-aa16-11e9-86fa-735807356a2e.png)

加载页面, 加载完成后,可以正常切换页码,展示不同页面数据
<第一次请求api>

1: 点击重置按钮,使表格重置
<第二次请求API>
2: 重置后的表格数据正常
3: 再次切换页码,表格一直显示加载中,没有发送第三次请求

**Comment by cipchk** [comment]
长时间未提供重现链接，关闭该问题，如果有其他问题请重新提交。
