### ISSUE TITLE
自定义变量主题

### ISSUE THREAD

**Issue by flxy1028** [ng-alain/ng-alain#1249]
自定义组件中自己写的ess样式使用了主题变量，当改变主题时，怎么让我自定义组件中的使用了主题变量的样式也一起更新

**Comment by cipchk** [comment]
引入 [@import '~@delon/theme/styles/default';](https://github.com/ng-alain/ng-alain/blob/master/src/app/routes/dashboard/analysis/analysis.component.less#L1) 所有主题变量定义包，这样就可以使用像主色系 `color: @primary-color;` 参数。
