### ISSUE TITLE
menu.service问题

### ISSUE THREAD

**Issue by zdxxxxxx** [ng-alain/ng-alain#125]
item.link.includes(url)

如果url中带参数

如 /a/b/c?d=e
则不会选中 link = /a/b/c 的导航
是不是改成
url.includes(item.link)就好了

**Comment by cipchk** [comment]
这里所指的不会选中是在什么情况下呢？因为侧边栏的状态是由路由来管理的，当你指定的路由存在自然会高亮。是否你所指的还有其他地方?

**Comment by zdxxxxxx** [comment]
菜单_open属性
