### ISSUE TITLE
自定义主题

### ISSUE THREAD

**Issue by flxy1028** [ng-alain/ng-alain#1251]
自己定一套主题色如：@color-1: #111;@color-2: #222;@color-3: #333;,
全局定义了几个class:  .fl-xy-1: {color: @color-1}
 .fl-xy-2: {color: @color-2}
 .fl-xy-3: {color: @color-3}

怎样换主题时动态改动变量 @color-1，;@color-2，;@color-3的值，并使我全局定义的class: .fl-xy-1,
.fl-xy-2,.fl-xy-3的值也一起改变

**Comment by cipchk** [comment]
增加需要动态的参数，目前 antd-theme-generate 有一些BUG，无法100%的提取，细节可能要自己斟酌：

https://github.com/ng-alain/ng-alain/blob/master/scripts/color-less.js#L15
