### ISSUE TITLE
ST 表格 tag 列类型如何支持多个 tag 

### ISSUE THREAD

**Issue by zooyoo** [ng-alain/ng-alain#1252]
目前支持单个 tag 的数据源定义如下：
![image](https://user-images.githubusercontent.com/12769712/61602747-72dcda80-ac6d-11e9-94e1-82c017402c08.png)

那如果要显示多个 tag ，要如何定义数据源？

**Comment by cipchk** [comment]
不支持，可以使用自定义列来实现。
