### ISSUE TITLE
生成的alain-default.less里的样式中class都是最少多写了一次

### ISSUE THREAD

**Issue by flxy1028** [ng-alain/ng-alain#1254]
- ng-alain version: 8.1.0
- Angular version: 8.1.2

![image](https://user-images.githubusercontent.com/20421386/61614673-ed6e2000-ac96-11e9-8f4f-8a649da1a11d.png)
![image](https://user-images.githubusercontent.com/20421386/61614691-f7901e80-ac96-11e9-91d7-a29820e9a68b.png)
![image](https://user-images.githubusercontent.com/20421386/61614734-0d9ddf00-ac97-11e9-8a40-d0b6e76a077d.png)

还有我在theme.less文件里面定义的 内容 ：
@flxy-red: red;
.flxy {
    background-color: @flxy-red;
}
编译后在alain-default.less文件里面如下：
![image](https://user-images.githubusercontent.com/20421386/61615139-dbd94800-ac97-11e9-94a1-592b936998e9.png)
![image](https://user-images.githubusercontent.com/20421386/61615154-e3005600-ac97-11e9-857a-7c2fa93aa2de.png)
![image](https://user-images.githubusercontent.com/20421386/61615169-eabffa80-ac97-11e9-961e-8b3af1a23205.png)

**Comment by cipchk** [comment]
duplicted of #1247
