### ISSUE TITLE
使用路由复用的时候如何带参复用

### ISSUE THREAD

**Issue by SuperRichZhao** [ng-alain/ng-alain#1255]
使用路由复用，当进入复用路由的时候，之前离开路由后的参数消失了，例如url地址为：/home/child?test=1&value=2，当再次使用tab页进入的时候url地址确为：/home/child

**Comment by cipchk** [comment]
路由复用不支持 `queryParam` 查询参数，只支持 `param` 参数。

**Comment by SuperRichZhao** [comment]
谢谢
