### ISSUE TITLE
升级到 8.2.0 后，ReuseTab打开带参数的url时，参数会丢失

### ISSUE THREAD

**Issue by dusdong** [ng-alain/ng-alain#1257]
- ng-alain version: 8.2.0
- Angular version: 8.1.2

## 重现步骤，Steps to reproduce

1、打开页面Helper对象：
```
@Injectable()
export class ReuseTabHelper {
    constructor(private reuseTab: ReuseTabService, private router: Router, private route: ActivatedRoute) {
    }

    openTab(url: string, params?: any) {
        // this.reuseTab['removeUrlBuffer'] = url;

        // 关闭已缓存的页面
        if (this.reuseTab.curUrl !== url) this.reuseTab.close(url);

        // 打开新页面
        this.router.navigate([url], { relativeTo: this.route, queryParams: params }).then();
    }
}
```

2、打开页面：
```
this.reuseTabHelper.openTab('/business/bill-of-lading/view', { id: id });
```

3、执行后：
浏览器的地址栏会首先显示争取的地址【http://localhost:4206/#/business/sales-contract/view?id=4f1b6f7f-eea5-4196-929a-2ef4d4262150】，然后一闪而过显示为【http://localhost:4206/#/business/sales-contract/view】，url参数丢失，该页面Component也无法获取参数信息。

此时，点击浏览器【后退】按钮，浏览器可跳转到 【http://localhost:4206/#/business/sales-contract/view?id=4f1b6f7f-eea5-4196-929a-2ef4d4262150】页面。

注：将ng-alain回滚到 8.1.0 ，则无此问题。

**Comment by cipchk** [comment]
dupclated of #1255
