### ISSUE TITLE
使用 ReuseTab 打开带param的标签页后，再点击其他tab会被自动关闭（已重现）

### ISSUE THREAD

**Issue by dusdong** [ng-alain/ng-alain#1259]
效果如下：
![reused](https://user-images.githubusercontent.com/3461709/61765593-4ad9ac80-ae10-11e9-9595-46b981171334.gif)

1、route 声明：
```
const routes: Routes = [
    { path: 'sales-contract', component: SalesContractComponent, canActivate: [CanAuthProvide] },
    { path: 'sales-contract/view/:id', component: SalesContractViewComponent, canActivate: [CanAuthProvide], data: { title: '销售合同浏览', reuse: 'true' } }
];
```

2、app-data.json 配置：
```
{
      "text": "销售合同浏览",
      "translate": "销售合同浏览",
      "link": "/business/sales-contract/view/:id",
      "reuse": true
}
```

3、打开url代码：
```
    openTab(url: string) {
        // 关闭已缓存的页面
        if (this.reuseTab.curUrl !== url) this.reuseTab.close(url);

        // 打开新页面
        this.router.navigateByUrl(url).then();
    }
```

请问下，问题出在哪里呢？

**Comment by coolyujiyu** [comment]
我知道是啥问题了，默认的复用路由MODE设置的是0，也就是菜单复用，非Menu打开的页面，是保持不了的，你想要保持的话，可以设置MODE为3，就所有URL都复用了

**Comment by dusdong** [comment]
@coolyujiyu 谢谢提醒，使用了 ReuseTabMatchMode.URL 果然好使了。

但还有个问题，在 ReuseTabMatchMode.URL 的模式下，ReuseTab 的 Title 就不从 Menu 中自动获取了，必须要 data:{title:'我是标题'} 中指定。

@cipchk 能否提供一个menu通配符匹配模式（比如 ? * 之类的），自动匹配id呢？

```
{
      "text": "销售合同浏览",
      "translate": "销售合同浏览",
      "link": "/business/sales-contract/view/?",
      "reuse": true
}
```
谢谢~

**Comment by dusdong** [comment]
终于在 stackblitz.io 上重现出来了~ ^_^  链接：[stackblitz.io](https://stackblitz.com/edit/ng-alain-setup-kam1km?file=src%2Fapp%2Fapp-routing.module.ts)

![reused](https://user-images.githubusercontent.com/3461709/61835520-a78ba480-aeae-11e9-92b8-68f20603cd5e.gif)


1、路由定义
```
const routes: Routes = [
  {path: 'list', component: ListComponent},
  {path: 'item/:id', component: ItemComponent},
  {path: 'item-fixed/:id', component: ItemComponent},
];
```

2、menu定义
```
menuService.add([{
      text: '列表',
      link: '/list',
      reuse: true
    }, {
      text: '浏览',
      link: '/item',
      reuse: true
    }, {
      text: '浏览-指定url',
      link: '/item-fixed/2',
      reuse: true
    }]);
```
a) 第一种方案，在使用 [mode]="0" 的情况下：
如果 menu 中指定id，即 link: '/item-fixed/2' ，这种方式是没问题的。但实际使用得时候，id是无法提前指定好的。
因此，能否可以提供一个 类似 link: '/item/?'  通配符的方式来兼容 'item-fixed/:id' 路由呢？

b) 另一种方案，就是使用 [mode]="2" 的方式：
但在这种方式下，ReusedTab 将不从 menuService 中读取title，所有的title都必须在路由中指定，增加了好多工作量。
因此，能否当  [mode]="2" 时，先从路由中读取title，如果读不到，就从menu中读取呢？

@cipchk 谢谢~
