### ISSUE TITLE
nz-cascader组件无法进行异步双向绑定

### ISSUE THREAD

**Issue by xbu** [ng-alain/ng-alain#126]
1. 在空白表单里使用nz-cascader，可以把model绑定到controller里的标量
2. 表单里编辑某对象，在controller里面调用http方法，将model和options绑定到页面的变量，options成功绑定，可以选择级联参数，但model始终无法显示。 参数格式没问题，我如果在http请求方法外写死参数，并绑定到model就显示正常
3.使用细节如下
<nz-cascader
[nzPlaceHolder]="''"
formControlName="org_id"
[(ngModel)]="org"
[nzExpandTrigger]="'hover'"
(ngModelChange)="changeOrg($event)"
[nzOptions]="orgTree"></nz-cascader>

4.我在changeOrg打印了变量，日志显示changeOrg触发了3此，分别打印null，null ，[]。 

搞了一下午，看了源代码也百思不得其解，求解惑

**Comment by cipchk** [comment]
抱歉，关于 ng-zorro-antd 组件的问题，请至少提供一个在线演示（模板：https://stackblitz.com/edit/ng-zorro-antd-setup?file=app%2Fapp.component.ts）说明你当前的状态。

**Comment by xbu** [comment]
你好，演示版见链接，options可以异步加载，但是model不行
https://stackblitz.com/edit/ng-zorro-antd-setup-44qmr3

**Comment by cipchk** [comment]
这应该是一个 ng-zorro-antd 的bug，你可以至官网提一个  issue。但是可以有一种临时的解决办法：
https://stackblitz.com/edit/ng-zorro-antd-setup-gjwofw?file=app/app.component.ts

**Comment by xbu** [comment]
已经提交issue到ng-zorro-antd，最后用另外一个hack处理了，利用nz-cascader的ngModelChange方法判断如果数组为空那么重新赋值解决。
