### ISSUE TITLE
通过npm搭建工程，启动访问前台报Unexpected token u in JSON at position 0，无法进入首页

### ISSUE THREAD

**Issue by tifazxy** [ng-alain/ng-alain#1260]
@angular version:7.2.0
@delon version:7.6.1
操作系统windows7

创建操作步骤：
1 ng new demo --style less
2 cd demo ng add ng-alain
3 ng serve -o

编译正常
![image](https://user-images.githubusercontent.com/18232986/61782956-8e94dc00-ae39-11e9-9648-925cac9ebf32.png)

浏览器访问不能进入登录页：
![image](https://user-images.githubusercontent.com/18232986/61782993-9f455200-ae39-11e9-8ebb-5f35ca091a88.png)
控制台输出如下错误：
![image](https://user-images.githubusercontent.com/18232986/61783056-b8e69980-ae39-11e9-8342-98fbdf267ed9.png)

调试过程中发现可能是token为undefined，尝试去掉route中的canActivate: [SimpleGuard]之后可以直接进入主页面，但是st不能绑定请求到的数据。

**Comment by cipchk** [comment]
尝试清除 localhost:4200 站点的所有存储数据（包含：cookie, LocalStorge）；另外建议使用 `8.x` 版本。

**Comment by tifazxy** [comment]
重新搭建了工程，并清除浏览器缓存，问题已解决，谢谢！
