### ISSUE TITLE
titleservice无法再配合page-header使用

### ISSUE THREAD

**Issue by kyumoka** [ng-alain/ng-alain#1261]
1在titlesevice按照getByElement()取标题时，直接获取'.alain-default__content-title h1的firstChild一般是类似的注释
2. setTitle在NavigationEnd运行时新的组建正在载入，老的组建并未清除，所有这时候会取到老组件的page-header中的信息

**Comment by cipchk** [comment]
这是一个已知问题，的确 `NavigationEnd` 的触发是在新路由组件树渲染前，会导致 [app.component.ts](https://github.com/ng-alain/ng-alain/blob/master/src/app/app.component.ts#L27) 的自动标题设置无法正确的获取，大部分人可能会遇到 `{ "binding:" }` 之类的标题，就是如此产生的。

解决这一问题，只能是使 `app.component.ts` 利用 `setTimeout` 来延迟一下使 Angular 组件树渲染完成后再设置，但这会引起另一个问题，我们无法保证新路由组件的执行会晚于 `app.component.ts` 的处理。

我想只能针对 `TitleService.setTitle` 增加一个比 `app.component.ts` 来得更晚的延迟，虽然这样子做很蠢，但可能唯一简单、有效的办法了。

**Comment by kyumoka** [comment]
最开始尝试的方法就是在app.component.ts增加延时，就是无法解决一致性问题和问题1
现在解决方法是直接在每个路由的data数据中增加title
thx
