### ISSUE TITLE
g2 图表封装建议加xyz三维数据

### ISSUE THREAD

**Issue by dangzhenghui1985** [ng-alain/ng-alain#1262]
目前看到的都是xy
![image](https://user-images.githubusercontent.com/16914422/61842162-c6e3fb00-aec9-11e9-8af0-f629eb569d41.png)
是否可以封装xyz这种的让图表更加丰富
![image](https://user-images.githubusercontent.com/16914422/61842188-dd8a5200-aec9-11e9-8c87-1cd567dcd45a.png)
![image](https://user-images.githubusercontent.com/16914422/61842209-ee3ac800-aec9-11e9-9197-a968a2f66c93.png)

**Comment by cipchk** [comment]
建议使用自定义 g2 来定制自己的需求。
