### ISSUE TITLE
st 表格搜索问题

### ISSUE THREAD

**Issue by wanjianbo** [ng-alain/ng-alain#1263]
[req]="{params: params}"
通过这个params上传多个数据后，
![image](https://user-images.githubusercontent.com/37653362/61868474-07fcff00-af0c-11e9-95be-8081cf237aa4.png)通过这个图可以看到我选择了多个数据和上传的数据，然后我取消了其中的会员等级
![image](https://user-images.githubusercontent.com/37653362/61868564-37137080-af0c-11e9-90d1-d66739c7eab3.png)但是，上传的levels依旧存在，搜索结果没有改变

**Comment by cipchk** [comment]
并不清楚你是采用什么方式来重置 `st` 数据加载，分为：`load`，`reload` 等等，这类方法的第二个参数可以来调整这些数据有合并方式。

为什么参数需要指定合并方式，主要是当我们请求可能是固定值（例如：必须状态为打开时）与动态值（例如表单产生）二者的合并是不相同的。
