### ISSUE TITLE
g2-timeline 不显示坐标轴 

### ISSUE THREAD

**Issue by RainyBow** [ng-alain/ng-alain#1264]
- ng-alain version: 8.2.0
- Angular version: 8.1.2
Angular CLI: 8.1.2
Node: 10.16.0
OS: linux x64
Angular: 8.1.2
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.801.2
@angular-devkit/build-angular     0.801.2
@angular-devkit/build-optimizer   0.801.2
@angular-devkit/build-webpack     0.801.2
@angular-devkit/core              8.1.2
@angular-devkit/schematics        8.1.2
@angular/cdk                      8.1.1
@ngtools/webpack                  8.1.2
@schematics/angular               8.1.2
@schematics/update                0.801.2
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.35.2

## 【必填项】重现链接，Reproduction link

![image](https://user-images.githubusercontent.com/20679042/61945147-d5b5d500-afd1-11e9-9371-31a789c9f541.png)

html代码：
<g2-timeline [delay]="500" [data]="tab.data" [height]="239" [padding]="[2, 2, 2, 2]" [mask]="'YYYY-MM-DD HH:mm:ss'" [titleMap]="tab.titlemap"></g2-timeline>
ts:
tab={
                key:"cpu利用率",
                display:false,
                data:[],
                id:0,
                titlemap:{
                    "y1":"cpu usage",
                },
         }
然后tab.push({x:1564109826000,y1:10})
tab.push({x:1564109831000,y1:10})
这种输入数据，

## 重现步骤，Steps to reproduce
一直没有显示坐标轴，之前使用7.x的版本也没有显示，看起来跟给的例子没什么区别啊，
应该是什么地方的问题？

**Comment by cipchk** [comment]
https://ng.ant.design/components/table/en#note

**Comment by RainyBow** [comment]
不是表格显示问题 ，是折线图没有横，纵坐标显示,如示例中红框部分
![image](https://user-images.githubusercontent.com/20679042/61991359-72837b80-b081-11e9-9e3d-886e9cb46800.png)

**Comment by RainyBow** [comment]
而且在给出的例子中，是使用push 来添加数据的
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'chart-timeline-basic',
  template: `
    <g2-timeline
        [data]="chartData"
        [titleMap]="{y1: '客流量', y2: '支付笔数'}"
        [height]="200"></g2-timeline>`,
})
export class ChartTimelineBasicComponent implements OnInit {
  chartData: any[] = [];
  ngOnInit(): void {
    for (let i = 0; i < 20; i += 1) {
      this.chartData.push({
        x: (new Date().getTime()) + (1000 * 60 * 30 * i),
        y1: Math.floor(Math.random() * 100) + 1000,
        y2: Math.floor(Math.random() * 100) + 10,
      });
    }
  }
}

**Comment by RainyBow** [comment]
找到原因了，[padding]="[2, 2, 2, 2]" 设置padding 太小把坐标轴弄掉了。
