### ISSUE TITLE
<reuse-tab>标签是否只能用一次，如果有多个路由出口<router-outlet>，在子路由出口无法实现复用

### ISSUE THREAD

**Issue by SuperRichZhao** [ng-alain/ng-alain#1265]
目前我有两个路由出口，父路由出口是使用&lt;router-outlet&gt;&lt;/router-outlet&gt;，子路由出口是放在一个父组件里的也是使用&lt;router-outlet&gt;&lt;/router-outlet&gt;

&lt;reuse-tab&gt;加在了父路由出口上，复用功能正常，但在子路由出口下的所有路由无法实现复用，必须在所有子路由出口下的所有子路由添加属性reuse：true才可实现复用

**Comment by cipchk** [comment]
reuse-tab 不支持嵌套 `router-outlet`
