### ISSUE TITLE
sf upload拖拽模式下，手动上传时文件列表不显示

### ISSUE THREAD

**Issue by chf007** [ng-alain/ng-alain#1266]
- ng-alain version: ^8.2.0
- ng-zorro-antd version: ^8.1.0
- Angular version: ^8.1.0

## 说明
upload拖拽模式下，想要自已手动上传文件时（beforeUpload => false），下方的文件列表不显示，ng-zorro-antd的[upload拖拽模式](https://ng.ant.design/components/upload/zh#components-upload-demo-drag)下是可以显示的

**Comment by cipchk** [comment]
是的，按照 [Angular 的设计](https://angular.io/guide/lifecycle-hooks#onchanges)，外部对某个对象属性变更是不会引发变更检测的。
