### ISSUE TITLE
I think that STReq missing the propertype for Lazyload

### ISSUE THREAD

**Issue by kasimLZ** [ng-alain/ng-alain#1267]
I use the ng-alain later than 8.0.0，
I don't want the ST to actively load data from server when the page finishes rendering.
Then I found the porpertype for lazyload on STReq in document.
But in my code,  I found that lazyload for STReq was removed .
Is it wrong in my code，or there is some new API instead the lazyload but the document has not been updated  yet？

**Comment by cipchk** [comment]
the `lazyLoad` will release in `·`8.3.0`

**Comment by kasimLZ** [comment]
Is there any alternative solution now?

**Comment by cipchk** [comment]
`8.3.0` has been release.
