### ISSUE TITLE
IE11下Input样式问题

### ISSUE THREAD

**Issue by xLong1029** [ng-alain/ng-alain#1268]
- ng-alain version: 8.1.0
- Angular version: 8.1.2
在以上版本，IE11下Input样式问题：占位符位置没与图标对称，偏下，影响外观
![TIM截图20190729144500](https://user-images.githubusercontent.com/18066675/62027199-a9879780-b20f-11e9-826c-d9a0fd0256c2.jpg)

**Comment by xLong1029** [comment]
经测试，ng-alain version:7.3.0 下无此问题，由于使用原因无法回退版本，希望能尽快解决，谢谢

**Comment by cipchk** [comment]
请至 https://github.com/NG-ZORRO/ng-zorro-antd/ 提交相应 issues
