### ISSUE TITLE
reuse-tab超过最大复用数时没有清除之前的复用，再次点击未清除的复用时导致无限循环(详情见GIF)

### ISSUE THREAD

**Issue by zjxcv7** [ng-alain/ng-alain#1270]
- ng-alain version: 8.2.0
- Angular version: 8.1.0

## 【必填项】重现链接，Reproduction link

![bug](https://user-images.githubusercontent.com/24834874/62272214-28c5d700-b46d-11e9-9657-4a090f609a15.gif)

**Comment by obamin** [comment]
这个我也发现了,  然后浏览器地址栏中的地址一直在变化

**Comment by zjxcv7** [comment]
1、正常启用路由复用；
2、设置最大路由复用数为2；
3、点击菜单加载路由；
4、当路由复用数量操作最大路由复用数时第一个并没有销毁，点击第一个时出现无限循环。

**Comment by cipchk** [comment]
@zjxcv7 抱歉，根据上述步骤我无法重现，以下是我的 gif 动画：

![demo](https://user-images.githubusercontent.com/2987467/63993045-5318bc00-cb21-11e9-8aef-6859ec222539.gif)

**Comment by zjxcv7** [comment]
@cipchk  你点击路由复用标签上的第一个页签就会出现bug，我的gif动画里面点击的是路由复用上的第一个页签。我有时间的时候做一个重现的项目。然后再反馈给你。

**Comment by rzjen** [comment]
为什么卡总无法重现这个BUG,我们都重现了

**Comment by cipchk** [comment]
统一跟踪 #1379
