### ISSUE TITLE
tree-select 关闭时会自动展开后才关闭

### ISSUE THREAD

**Issue by HePeng11** [ng-alain/ng-alain#1273]
![addmenugif3](https://user-images.githubusercontent.com/23466980/62347487-73f2ef00-b52c-11e9-83eb-28cf3e728ac5.gif)

**Comment by HePeng11** [comment]
刚更新版本为8.2.0过后出现的

**Comment by HePeng11** [comment]
![Capture](https://user-images.githubusercontent.com/23466980/62348657-ed401100-b52f-11e9-88f9-52503edb6e50.PNG)

**Comment by cipchk** [comment]
有关 `ng-zorro-antd` 组件，请至 https://github.com/NG-ZORRO/ng-zorro-antd/
