### ISSUE TITLE
reuse-tab 如何添加当前路由到reuse标签的队列中，目前只有移除方法move()

### ISSUE THREAD

**Issue by SuperRichZhao** [ng-alain/ng-alain#1274]
不使用reuse：true的方式来复用路由，我需要任何时候指定当前路由是否复用，或者使用添加方法将当前的路由添加到reuse队列中。

**Comment by cipchk** [comment]
路由复用只在路由离开后才能存储，当进入路由时将存储的状态进行还原；若需要进行额外处理，可以调用 `ReuseTabService.store` 写入缓存列表中。
