### ISSUE TITLE
动态修改sidebar-nav的背景色

### ISSUE THREAD

**Issue by wzlhappy** [ng-alain/ng-alain#1278]
如何动态修改左侧边栏的背景色，就像动态修改导航的数据一样

**Comment by cipchk** [comment]
请参考 https://github.com/ng-alain/ng-alain/blob/master/src/app/layout/default/setting-drawer/setting-drawer.component.ts 的做法；有关主题的LESS变量描述，请阅读文档：https://ng-alain.com/theme/default/zh
