### ISSUE TITLE
8.3.0版本 npm run build 打包部署后样式有问题

### ISSUE THREAD

**Issue by danxiaogui** [ng-alain/ng-alain#1280]
- ng-alain version: 8.3.0
- Angular version: 8.2.0

## 重现步骤2，配置nginx转发，浏览器访问打包后的 /dist 文件夹路径，发现样式有问题，登陆按钮、菜单栏按钮、甚至Tree组件的显示都有问题
![image](https://user-images.githubusercontent.com/22045563/62506922-0cdb8000-b835-11e9-9045-6111285fd327.png)

**Comment by danxiaogui** [comment]
菜单栏和Tree组件在我的实际工程上表现为，菜单栏的badgeDot=true设置无效，ng-zorro的Tree组件的Checkbox复选框显示不出来

**Comment by cipchk** [comment]
示例DEMO页并无这种现象 ：https://ng-alain.github.io/ng-alain/#/passport/login

建议是否 nginx 配置问题导致无法加载样式文件，或者构建后在使用 http-serve 来验证一下是否有问题。

**Comment by danxiaogui** [comment]
刚刚使用  http-serve 来启动 ng-alain 8.3.0，浏览器访问后样式还是不对@cipchk

![image](https://user-images.githubusercontent.com/22045563/62509879-7b254000-b83f-11e9-9ed2-d76888ef3b01.png)
![image](https://user-images.githubusercontent.com/22045563/62509890-942df100-b83f-11e9-9cfb-8c24f7047fa5.png)

**Comment by chpxl2** [comment]
楼主你最后解决了吗，我现在也出现一模一样的问题

**Comment by danxiaogui** [comment]
不知道是什么原因导致的，我后面的项目跳过这个版本，现在用的是8.5.1，这个没有问题

**Comment by chpxl2** [comment]
本地运行样式都是OK的，build发布之后就不行了，看了下的登陆页面的button,build之后的class少一个“ant-btn-block”

**Comment by chpxl2** [comment]
> 不知道是什么原因导致的，我后面的项目跳过这个版本，现在用的是8.5.1，这个没有问题
那我也只能跳过这个版本了,用8.5.0试试看
