### ISSUE TITLE
sf  动态控制表单的 readOnly 

### ISSUE THREAD

**Issue by sdandroid** [ng-alain/ng-alain#1281]
使用 asyncData   作为数据源， BehaviorSubject更新数据，动态修改 select  readOnly 属性，
由 true改成 false 后，select 框可以下拉，选项被禁用，调试 schema.readOnly 为true。

> export function getData(schema: SFSchema, ui: SFUISchemaItem, formData: any, asyncArgs?: any): Observable<SFSchemaEnum[]> {
  if (typeof ui.asyncData === 'function') {
    return ui.asyncData(asyncArgs).pipe(map((list: SFSchemaEnum[]) => getEnum(list, formData, schema.readOnly!)));
  }
  return of(getCopyEnum(schema.enum!, formData, schema.readOnly!));
}

**Comment by sdandroid** [comment]
@cipchk   [https://github.com/sdandroid/my-test](url) 例子

**Comment by cipchk** [comment]
@sdandroid 所有 `asyncData` 处理的是冷Observable，换句话说它只会在初始化过程中调用一次，如果希望下拉框需要依赖外部的情况下，可以在外部数据加载完成后再渲染 `sf`。

**Comment by sdandroid** [comment]
@cipchk  更新了代码，麻烦看下这样写不对？
