### ISSUE TITLE
请问less换肤有没有持久化方案

### ISSUE THREAD

**Issue by KellenHe** [ng-alain/ng-alain#1284]
现在是参照的setting-drawer.component.ts中的换肤方法。但是刷新浏览器后会还原。请问有持久化的方案吗？

**Comment by cipchk** [comment]
事实上可以实现，但是会**严重影响用户体验**；

你可以根据 [setting-drawer.component.ts](https://github.com/ng-alain/ng-alain/blob/master/src/app/layout/default/setting-drawer/setting-drawer.component.ts#L241) 动态加载换肤代码转移至 [startup.service.ts](https://github.com/ng-alain/ng-alain/blob/master/src/app/core/startup/startup.service.ts#L33)，意味者每一次 Angular 启动前会先先进行换肤再才会开始渲染。

**Comment by KellenHe** [comment]
> 事实上可以实现，但是会严重影响用户体验；
> 你可以根据 setting-drawer.component.ts 动态加载换肤代码转移至 startup.service.ts，意味者每一次 Angular 启动前会先先进行换肤再才会开始渲染。

是的，这样会很慢。

**Comment by KellenHe** [comment]
为什么使用antd-theme-generator 生成的less里。相同的样式生成了7份。

**Comment by cipchk** [comment]
应该是你使用旧的版本：https://github.com/ng-alain/ng-alain/blob/master/scripts/color-less.js
