### ISSUE TITLE
購買版型問題

### ISSUE THREAD

**Issue by ChangYinShung** [ng-alain/ng-alain#1285]
@cipchk 
能否為這些版型 寫一下 USD售價
https://e.ng-alain.com/theme/ms
我們這邊只能用Paypal，但Paypal 沒有 CNY/RMB ，
能否為主題 MicroSerives 標註 USD 售價

抱歉，這問題似乎不該發送到這裡，但 我們的IP(台灣)似乎無法用 聯絡到 cipchk@qq.com 
收到了退信通知 ，請問有其他聯絡方式嗎?

**Comment by cipchk** [comment]
@ChangYinShung 你可以使用的当前的[汇率](https://www.google.com/search?q=rmb+to+usd&oq=rmb+to+&aqs=chrome.0.0l2j69i57j0l3.1724j0j7&sourceid=chrome&ie=UTF-8) 按 人民币等额换算支付即可。

感谢对 ng-alain 的支持。
