### ISSUE TITLE
sidebar-nav  组件 [openStrictly] = true 点击子菜单无效 会自动折叠

### ISSUE THREAD

**Issue by hennychen** [ng-alain/ng-alain#1287]
- ng-alain version: 8.x
- Angular version: 8.x
## 【必填项】重现链接，Reproduction link
sidebar-nav  组件 [openStrictly] = true 点击子菜单无效 会自动折叠
menservice open=true  也一样效果

**Comment by cipchk** [comment]
长时间未提供重现，因此关掉此 issues.
