### ISSUE TITLE
建议st增加名称属性,  嵌套子st的时候,  可以方便查找数据行下具体哪个子st

### ISSUE THREAD

**Issue by obamin** [ng-alain/ng-alain#1289]
![反馈1](https://user-images.githubusercontent.com/36915753/62989227-c52ea700-be79-11e9-9951-df0c150cfe77.png)
![反馈2](https://user-images.githubusercontent.com/36915753/62989382-46863980-be7a-11e9-9930-7506a967259d.png)
希望能改进,  希望系统越来约好

**Comment by obamin** [comment]
还有一个
st表格变化时回调change 事件中能否加上 checked 的当前行信息(目前勾选和取消不知道是哪一行操作的)

**Comment by cipchk** [comment]
`STColumn` 支持 `{ [key: string]: any }` 类型，并且在所有事件中返回 `STColumn` 都原样返回。
