### ISSUE TITLE
how to lazy load ng-zorro?

### ISSUE THREAD

**Issue by xingkoo** [ng-alain/ng-alain#129]
打包发布版本中的vendor文件就差不多4m了。
里面包括了完整的ng-zorro组件。但是实际中，用户进入时，并不会使用全部的组件。
这样导致新开页面需要的时间会非常多，影响用户体验。
如何能够让ng-zorro包按需加载？

**Comment by cipchk** [comment]
[shared.module.ts](https://github.com/cipchk/ng-alain/blob/master/src/app/shared/shared.module.ts#L19)

**Comment by xingkoo** [comment]
这些引用的文件都是会被打包到vendor.js里面的吧？build后，该文件近4m的。我想要实现的是让打包的时候，这些组件可以分开，然后在使用的时候，才会懒加载到文件。
现在是直接一次性打包并在初始的时候直接加载给用户了

**Comment by cipchk** [comment]
是的 vendor.js 相当于主模块打包，4m如果是通过 `ng build --prod --build-optimizer` 也如此大，说明你引用 的第三方类库实在太多了，如果说这些第三方类库是其中某个子模块才需要的，则你可以将这些类库在子模块中引用就行，无须在 `shared.module` 中引用 。

至于 ng-zorro 本身其实并不大。

另外关于包体大小问题，这不是一言两语说得清楚的，可以参考http://ng-alain.com/docs/deploy中【分析构建文件体积】的方法去寻找问题的根源。

**Comment by xingkoo** [comment]
我是直接git下来的项目，然后使用上述命令打包的。访问时通过chrome查看到对应的文件有这么大。然后检查了代码后发现在shared.module里面导入的组件是最多的。

**Comment by cipchk** [comment]
https://github.com/cipchk/ng-alain/blob/gh-pages/main.bcbb801c1ca8523aecc4.bundle.js

这是当前的大小 `2.6m` 配合 gzip 实际前端接收的大概在 555kb 左右:

![tim 20171220191712](https://user-images.githubusercontent.com/2987467/34204661-81f918a6-e5ba-11e7-9623-efcc3af26987.png)

**Comment by xingkoo** [comment]
是的，2.8M，本地没有开gzip，忘记这个因素了。
几百k的话是完全可以接受的。
