### ISSUE TITLE
st可否添加拖拽改变列宽的功能

### ISSUE THREAD

**Issue by visionding** [ng-alain/ng-alain#1290]
NG-ZORRO最新版本添加了Resizable组件，但是看[table的demo](https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/components/resizable/demo/table.ts)使用很麻烦，不知道在st中可否有简化的实现，现在项目中有大量的表格，大部分都需要拖拽改变列宽

**Comment by cipchk** [comment]
tracking https://github.com/NG-ZORRO/ng-zorro-antd/pull/5475

**Comment by gaomengyong** [comment]
@cipchk 请问什么时候添加这个功能，这边急需这个功能

**Comment by ttnkh21** [comment]
@cipchk 同求 期待增加
