### ISSUE TITLE
alain-default.less文件生成内容问题

### ISSUE THREAD

**Issue by KellenHe** [ng-alain/ng-alain#1292]
目前生成的样式都是这种，直接带样式的
.ant-layout-sider {
background: #3a3d4d;
}
而不是这种带变量的。
.ant-layout-sider {
background:  @layout-sider-background;
}

导致less.modifyVars无效。不知道是什么原因导致的。

**Comment by cipchk** [comment]
目前 `alain-default.less` 是依赖于 [antd-theme-generator](https://github.com/mzohaibqc/antd-theme-generator) 来产生的，是否是少部分几个，还是所有 antd 变量都无法生成呢？另是否确认 `scripts/color-less.js` 是否采用最新版本的。

**Comment by KellenHe** [comment]
scripts/color-less.js是最新版本。大部分的antd变量无法生成，只有@primary-color是可以的。

**Comment by cipchk** [comment]
给需要生成变量写入至 [color-less.js](https://github.com/ng-alain/ng-alain/blob/master/scripts/color-less.js#L15) 中。
