### ISSUE TITLE
st 的数据源支持 Graphql 接口调用

### ISSUE THREAD

**Issue by chf007** [ng-alain/ng-alain#1294]
目前 st 的数据源只有url和本地2种，现在有些接口是 Graphql 方式提供的，在未来是否可以考虑支持一下。我们现在使用的 Graphql Client 库是 Apollo。

或者  st  数据源可以支持从 service 取数据，这样就可以在 service 层做 graphql 的请求。

**Comment by zealotwjr** [comment]
I've found a solution that works  fine with GraphQL 

Here is my code :

template 

<st #st [data]="data" [columns]="columns" [page]="pager" (change)="change($event)">
...

#########################
ngOnInit(){
....

this.queryRef = this.apollo.watchQuery({
      query: brandListQuery,
      variables: { 'page': 1, 'size': this.st ? this.st.ps : 10 },
    });
    this.querySubscription = this.queryRef.valueChanges.subscribe(({ data, loading }) => {
      this.loading = loading;
      // @ts-ignore
      const brandList = data.brandList;
      this.data = brandList.records;
      // @ts-ignore
      this.st.total = brandList.totalRecord;
    });
}
####################

change(e: STChange) {
    if (e.type == 'pi') {
      this.queryRef.refetch({
        'page': e.pi, 'size': e.ps,
      });
    }
 }

**Comment by Diluka** [comment]
再比如接口是这个生成的那种 https://github.com/doug-martin/nestjs-query

**Comment by Diluka** [comment]
再比如客户端使用这个生成的 https://www.npmjs.com/package/apollo-angular https://graphql-cli.com/ 那么注入的XXXGQL就是service了

**Comment by Diluka** [comment]
@cipchk 能不能在st配置属性上开放相关的适配器接口，比如如何读取远程数据并返回st需要的格式，比如如何将查询表单组装成查询参数等，这样我们可以根据自己的需要开发适配自己服务端接口的适配器，让graphql不再使用离线表格
