### ISSUE TITLE
刚下载下来，编译不通过，ng cli是最新版本，clone git下来的版本没问题

### ISSUE THREAD

**Issue by checkmateTowindn** [ng-alain/ng-alain#1295]
![image](https://user-images.githubusercontent.com/26129032/63142749-9d784400-c01d-11e9-8749-617b088a7f01.png)

**Comment by checkmateTowindn** [comment]
貌似是ng cli版本太低得原因

**Comment by cipchk** [comment]
`static` 属于 angular 8 范畴，请先升级 Angular cli 至最新版本。
