### ISSUE TITLE
侧边栏 Menu 路由匹配 在 url 中有 queryparams 时失效

### ISSUE THREAD

**Issue by allenlongbaobao** [ng-alain/ng-alain#1298]
如题，在 `app-data.json` 中配置了各个菜单的 link，当某个页面的 url 中带有 params 时，菜单的路由匹配失效，菜单项无法高亮。

**Comment by cipchk** [comment]
设定参数 `recursivePath` 为 `true`，例如： `/ware/2` 其中 `2` 表示 params 参数，而 `/ware` 是一个真实存在的路由且在菜单数据中能找得到的路径。

**Comment by allenlongbaobao** [comment]
@cipchk 感谢建议，但是有个疑问：如果 params 是 queryParams 以 `/ware?name=test&age=2` 的形式呢？

**Comment by cipchk** [comment]
包含，但必须保证其完整路径在菜单数据中存在。

**Comment by allenlongbaobao** [comment]
@cipchk 我试了一下，如果是完整路径的话，的确能匹配出来，但是 queryparams 一般都是条件搜索，它的值该如何替换？
