### ISSUE TITLE
hmr error

### ISSUE THREAD

**Issue by xingkoo** [ng-alain/ng-alain#130]
`ng serve --hmr`
error info: Cannot enable prod mode after platform setup
so,modify **environment.hmr.ts**, production value is false.
`
zone.js:690 Unhandled Promise rejection: AlainThemeModule.forRoot() called twice. Lazy loaded modules should use AlainThemeModule.forChild() instead. ; Zone: <root> ; Task: Promise.then ; Value: Error: AlainThemeModule.forRoot() called twice. Lazy loaded modules should use AlainThemeModule.forChild() instead.
`
try moidy core.module.ts line 9 **AlainThemeModule.forRoot()** to **AlainThemeModule.forChild()**
error too.
pls help me fix it.

**Comment by cipchk** [comment]
confirmed, i will next version fix.

**Comment by xingkoo** [comment]
Is there a temporary solution?

**Comment by cipchk** [comment]
using `ng serve`

**Comment by xingkoo** [comment]
all right.
i'm try find solution.

**Comment by cipchk** [comment]
if was change `production: true` to `production: false` in `environment.hmr.ts`.

you can trying `npm run serve:hmr` command.

**Comment by xingkoo** [comment]
yes,after execute `npm run serve:hmr`,then modify user.component.html.
show error!

**Comment by ziben** [comment]
I can run the 'ng serve --hmr' without error.

**Comment by xingkoo** [comment]
run command without error.
but modify files,hot replacement is error!
