### ISSUE TITLE
路由变化，导致tinymce富文本编辑器失效

### ISSUE THREAD

**Issue by ChaoQunPeng** [ng-alain/ng-alain#1300]
- ng-alain version: ^8.2.0
- Angular version:  8.0.6
- ngx-tinymce: ^7.0.0

## 【必填项】重现链接，Reproduction link
因为stackblitz不好重现ng-alain，就在git page里弄了...

源码：https://github.com/ChaoQunPeng/tinymce-rich
git page：https://chaoqunpeng.github.io/tinymce-rich-ys/#/dashboard

## 重现步骤，Steps to reproduce
第一次进入tinymce，编辑器正常使用，此时切换路由至dashboard，然后又切回到tinymce，编辑器失效，数据丢失且编辑器无法点击

**Comment by cipchk** [comment]
主要原因是路由复用引起的，因为复用是无法触发 `ngOnInit`，目前针对复用提供两个额外的事件接口，可以在 [_onReuseInit](https://ng-alain.com/components/reuse-tab/en#Reuse-Events)  重新初始化。

**Comment by betgo** [comment]
我也遇到这个问题
解决办法是延迟加载
`<tinymce [delay]=100`
