### ISSUE TITLE
类型为del后点击没反应

### ISSUE THREAD

**Issue by myprogo** [ng-alain/ng-alain#1301]
- ng-alain version: 8.3.0
- Angular version: 8.1.3

st组件里面按钮组，类型为del后点击没有任何反应。没升级到8.0之前是正常的。升级到8.0后就出现这问题了

**Comment by cipchk** [comment]
@myprogo Can u provider a reproduce link?

**Comment by myprogo** [comment]
已经解决了。是delon.module里增加了STConfig配置的问题。
在8.0升级后改成
export function fnSTConfig(): STConfig {
  return {
    ...new STConfig(),
    modal: { size: 'lg' },
  };
}
