### ISSUE TITLE
新版本，如何在启动时动态设置自定义主题和颜色 ?

### ISSUE THREAD

**Issue by 1166544** [ng-alain/ng-alain#1302]
- ng-alain version: latest
- Angular version: latest

## 重现步骤，Steps to reproduce
![image](https://user-images.githubusercontent.com/2033010/63668206-096e5f80-c809-11e9-9bf9-aac837916b2f.png)

新版移除了ThemeService,请问如何通过类似的方法：
比如如 this.themeServ.setTheme(theme); this.settings.setLayout('theme', theme);

来在启动时动态设置自定义主题？

**Comment by cipchk** [comment]
这是 `0.x` 的做法，从 `1.x` 开始将不再使用这种方式，而是使用 less 参数来订制主题，有关更多细节见：https://ng-alain.com/theme/getting-started/zh#%E5%A6%82%E4%BD%95%E8%A6%86%E7%9B%96%E5%8F%82%E6%95%B0
