### ISSUE TITLE
page-header内tab属性的nztable 的nzScroll无效

### ISSUE THREAD

**Issue by angelxg** [ng-alain/ng-alain#1306]
- ng-alain version: 8.30
- Angular version: 8.20

因为st 没找到可编辑表格的例子
用的 nz-table

【现象】
整个table th的总长是1700px
如果 nzScroll x设置为 比如 2000px  ，整个页面的宽度和 nzScroll x 宽度一致了 
页面跑到浏览器可视范围外面了（page-header包裹的所有内容）

如果nzScroll x小于 1700px 则td全挤在一起显示 没有出现滚动条

放在page-header内tab 里的tab 就出现问题

现在只能通过 将 tab  拿出到 page header外面（下面） 解决的
[tab]属性没用上

**Comment by cipchk** [comment]
我无法重现该问题，请提供重现链接。

另 tab 的实现是基于 `nz-tabset`，由于它的实现方式，有可能是渲染顺序问题，试着延迟 `nz-table` 的显示。

**Comment by angelxg** [comment]
请问如何延时加载
我用 ngIf  和setTimeout  延迟5秒后显示  table
还是没有好用
吧其他没用的元素去掉了页不行

尝试 Stackblitz 画个 page-header  但没有显示 不知道为什么
谢谢

**Comment by cipchk** [comment]
长时间未提供重现，因此关掉此 issues.
