### ISSUE TITLE
reuse-tab切换标签时 nz-tabs-ink-bar 丢失

### ISSUE THREAD

**Issue by liang0213** [ng-alain/ng-alain#1311]
- ng-alain version: 8.3.0
- Angular version: 8.2.4

![image](https://user-images.githubusercontent.com/13412697/64077641-e100cc80-cd04-11e9-97bc-4cc8cfdcc77f.png)
如图点开两个标签后,再切换到菜单管理时,蓝色线条丢失,打开f12又出现线条,再切换至用户管理时,线条再次丢失
![image](https://user-images.githubusercontent.com/13412697/64077671-20c7b400-cd05-11e9-87b0-9115a80ab187.png)

**Comment by cipchk** [comment]
抱歉，这看起来并不是 `reuse-tab`，恐怕我无法提供解决方案，目前我在 ng-alain 上并没有这类问题。

**Comment by liang0213** [comment]
![image](https://user-images.githubusercontent.com/13412697/64411324-80381200-d0bf-11e9-9798-31d1baaa0792.png)
![image](https://user-images.githubusercontent.com/13412697/64411343-875f2000-d0bf-11e9-8581-63fb58d2a951.png)

**Comment by liang0213** [comment]
这个问题还有大概多久可以修复

**Comment by CodingYiyi** [comment]
> 抱歉，这看起来并不是 `reuse-tab`，恐怕我无法提供解决方案，目前我在 ng-alain 上并没有这类问题。

看了下组件源码，ChangeDetectorRef的问题，reuse-tab.component.ts中的 genList函数修改下即可。
![20191127095749](https://user-images.githubusercontent.com/13033654/69687091-a7214580-10fc-11ea-90b0-9be219abbd3b.jpg)

**Comment by liang0213** [comment]
好的,谢谢

**Comment by liang0213** [comment]
detectChanges 改为 markForCheck后,左侧导航切换可以显示,但切换标签还是不能显示

**Comment by CodingYiyi** [comment]
> detectChanges 改为 markForCheck后,左侧导航切换可以显示,但切换标签还是不能显示

诶，我的可以呀。你说的切换标签不能显示指的是？已经打开的tab页，切换的时候 active 的 tab 下面的蓝线丢失？

**Comment by liang0213** [comment]
对对对,就是多打开几个,然后点击切换标签的时候就丢了,你版本升到最新了么

**Comment by CodingYiyi** [comment]
> 对对对,就是多打开几个,然后点击切换标签的时候就丢了,你版本升到最新了么

我是好久之前，大概半年吧，拉个一个分支出来，就自己维护了，没再合并delon这个库了

**Comment by liang0213** [comment]
头疼…




| |
葛亮
|
|
邮箱：gl_0213@163.com
|

签名由 网易邮箱大师 定制

在2019年12月03日 20:42，CodingYiyi 写道：

对对对,就是多打开几个,然后点击切换标签的时候就丢了,你版本升到最新了么

我是好久之前，大概半年吧，拉个一个分支出来，就自己维护了，没再合并delon这个库了

**Comment by CodingYiyi** [comment]
建议你把源码（nz-tabs-ink-bar 和 delon）拉下来调试下，问题就在这个cdr和阿里那个nz-tabs-ink-bar指令的
![20191203210106](https://user-images.githubusercontent.com/13033654/70053302-17a1f800-1610-11ea-92a7-9b61f27e4dea.jpg)
这个地方

**Comment by liang0213** [comment]
感谢  我看是因为跳转后丢失的  




| |
葛亮
|
|
邮箱：gl_0213@163.com
|

签名由 网易邮箱大师 定制

在2019年12月03日 21:01，CodingYiyi 写道：

建议你把源码（nz-tabs-ink-bar 和 delon）拉下来调试下，问题就在这个cdr和阿里那个nz-tabs-ink-bar指令的

这个地方
