### ISSUE TITLE
sf cascader 在8.2.1版本下错误

### ISSUE THREAD

**Issue by JustForYouKing** [ng-alain/ng-alain#1312]
- ng-alain version: 8.4.0
- Angular version: 8.1.3
-ant version ：8.2.1
sf cascader 
![QQ图片20190903084501](https://user-images.githubusercontent.com/54824126/64136887-5bc20880-ce27-11e9-8b02-02b016d4ed4c.png)
![QQ图片20190903084505](https://user-images.githubusercontent.com/54824126/64136888-5bc20880-ce27-11e9-8731-31bb36921633.png)

**Comment by cipchk** [comment]
暂时并不会影响使用。
