### ISSUE TITLE
功能建议：为动态表单中的upload引入“nzShowButton”配置项

### ISSUE THREAD

**Issue by ococl** [ng-alain/ng-alain#1315]
**场景**

针对头像、logo等单个图像上传场景，我希望未上传时显示+号或默认图，上传后显示已上传的图，整个过程无需额外按钮参与。

其他情况，例如我希望选定了3个文件之后+号按钮隐藏。

**问题**
通过现有的配置项无法做到这一点。

**参考效果**

见：[https://uplrs1.run.stackblitz.io](https://uplrs1.run.stackblitz.io)

该代码来自[https://ng.ant.design/components/upload/zh](https://ng.ant.design/components/upload/zh)，做了细微更改。

**Comment by cipchk** [comment]
针对不同的业务，我建议自己实现相应的 upload 小部件；你很容易可以实现：https://ng-alain.com/form/customize/zh#%E5%88%B6%E4%BD%9C%E5%B0%8F%E9%83%A8%E4%BB%B6

**Comment by ococl** [comment]
明白，实际上我在项目当中也是自定义小部件来实现的，相比delon来讲，只是增加了一个`nzShowButton`的配置项。
个人感觉这个功能点会有很多人也能用到，所以才提交此建议，期望大家都能受益。
