### ISSUE TITLE
功能建议：为BaseApi添加拼接“~/api/[controller]/[action]:batchDisable”风格路径的支持

### ISSUE THREAD

**Issue by ococl** [ng-alain/ng-alain#1317]
**问题**

我采用了[google api](https://cloud.google.com/apis/design/custom_methods)的rest风格规范，其中包含了这样的url样式，它常用于针对资源的自定义方法：
```
# 这种风格在目前的BaseApi及相关注解中无法直接实现，因为delon在拼接url的时候总是会加上一个斜杠“/”
# 见：https://github.com/ng-alain/delon/blob/master/packages/theme/src/services/http/http.decorator.ts#L128
/api/xxx/files:undelete

# 这种情况可以实现，虽然有些小不适
/api/xxx/files/{fileId}:undelete
```

**目前采用的解决方案**

```ts
// 这里的:disable作为自定义方法名称，但其实为了安全起见我期望写为`:id::disable`，也就是对冒号进行显性转义声明，但目前的delon貌似不支持，但按照这种写法也没什么问题，可以正常运行
@POST(`:id:disable`)
enable(@Path('id') id: string): Observable<any> ...

// 由于无法通过注解或其他的配置方法去除多余的“/”，这里我定义了一个占位符，然后在net拦截器中将其替换掉，目前也可以正常工作
@POST(`{FULL_API_URL}:batchEnable`)
batchEnable(@Body data: any): Observable<any> ...
```

我还曾经试过将以http/https开头的全路径写入@POST注解，但最终拼出了两个重复的http路径。

**Comment by cipchk** [comment]
@ymind 抱歉，我对 google api 首次了解；恐怕不能深刻，你能否进一步描述几种不同的 URL 的现状态，期望状态；以便我更好的处理这类问题。期望表格：

现状态 | google api 状态 | 描述 
------ | -------------- | ----
`url/:a` | - | -

**Comment by ococl** [comment]
## 回复

google api的这套针对RESTful的定制规范，可以很好的解决一些特定问题。例如针对资源或资源集合的某些操作，在RESTful之下无法找到与之匹配的资源描述格式，这些操作在OOP建模的时候通常会被定义为对象的方法。

关于RESTful相关的许多疑问，我都在google的这套机制之下找到了一个良好的解答，也很好用，甚至它还细化到了如何为资源和操作进行命名。

针对咱们的话题，在我以往的实践中，只遇到了以下两种情况（格式）：

| 现状态                                      | google api 状态                             | 描述                     |
| ------------------------------------------- | ------------------------------------------- | ------------------------ |
| `/api/ucenter/users/:importUsers?a=1&b=2`   | `/api/ucenter/users:importUsers?a=1&b=2`    | 针对资源集合的自定义操作 |
| `/api/ucenter/users/{userId}/:lock?a=1&b=2` | `/api/ucenter/users/{userId}:lock?a=1&b=2`  | 针对单个资源的自定义操作 |

实际上我只是希望剔除其中多余的`/`。

在这套规范之下，自定义操作的HTTP方法只有两个即`GET`和`POST`，如果自定义方法是用来获取（读）特定资源的，使用`GET`。除此之外，其他带有更改资源的自定义操作一律使用`POST`。这也与RESTful对未知操作应使用`POST`的规则一致。

## 其他

结合`ng-alain`框架，我的使用痛点还有几条，只是怕一次提太多需求不太好，但都列出来或许能够帮助大家理解这个问题，例如：

### 冒号转义问题
上文提到过，我们期望在需要对`:`转义的时候，应当强制性写为`::`更加合适，除了它更加符合使用习惯之外，还有个原因：
我猜测`_HttpClient`的`@GET`、`@POST`以及`@QUERY`、`@BODY`等这一系列装饰器可能由于时间问题实现的比较仓促，功能并不完整。导致如下代码并不能如愿工作：
```ts
delete(@Path() id: string): Observable<any> { return; }

// 将会发出下述请求：
// .../users/:id
// 它并不会替换掉其中的“:id”。
```
因为它必须这样写：
```ts
delete(@Path('id') id: string): Observable<any> { return; }

// 将发出正常请求：
// ../users/123456
```
也就是说，装饰器参数如果不填，它并不会自动获取这里的参数`id`作为其默认值。这其实也导致了下面这个问题：
```ts
// 这里最终会变成：.../xxx:disable
// 也就是我只要不定义`disable`这个参数它也就不会替换，目前我也就是利用这个特点来变通实现我的api client的。只是有时候看起来有点怪异。
@POST(`:id:disable`)
disable(@Path('id') id: string): Observable<any> { return; }
```

添加了双冒号转义或其他方式的转义约定，此处也就可以做出更多花样来了！

### 复杂对象传参序列化问题

见 #1325

**Comment by cipchk** [comment]
@ymind 其中有一点关于 `Path('id')`，它也只能这么做，因为 ES 没有反编译的说法，因为要想知道 这个名称，就只能以一个字符串来表述。

另外关于转义，我会提供一个接口，用于自定义转义需求；

关于 #1325 我建议合并至这里，我在此一并回答：当初没有设计支持对象，主要因素是目前参数对象（即 `searchArgs` 值必须是 `publice` 类型，对于 `private` 是不安全的，这很大会引起误编写，所以一开始没有这么做，不过的确可以增加 `Object` 对象的支持。
