### ISSUE TITLE
siderbar-nav最大支持几级菜单栏

### ISSUE THREAD

**Issue by HuangFuQuang** [ng-alain/ng-alain#1318]
🚨 Issues 是用于BUG、Feature、进度追踪 🚨
🚨 The issue tracker is not for questions 🚨

我们业务场景里面有7级的子菜单，请问作者，siderbar-nav是不是对级别做了限制，因为我看了貌似被隐藏了不显示

**Comment by cipchk** [comment]
是的，目前只支持 3 级（包含组名算 4 级），我们认为超过 4 级（或 5 级）的菜单用户在使用上会很难过。
