### ISSUE TITLE
Could not find any [COMPONENTS_NOROUNT] variable in path 'xx/xx/xx'

### ISSUE THREAD

**Issue by hennychen** [ng-alain/ng-alain#1319]
- ng-alain version: "ng-alain": "^8.4.0",
- Angular version:"@angular/cli": "~8.3.1",
- "ng-zorro-antd": "^8.2.1",
## 【必填项】重现链接，Reproduction link

执行 ：ng g ng-alain:view view -m=sys -t=project-manage
错误：
Could not find any [COMPONENTS_NOROUNT] variable in path '/src/app/routes/sys/sys.module.ts'.

之前一直都没问题，升级之后产生

**Comment by hennychen** [comment]
如果执行 ng g ng-alain:list xxx -m=sys  
会出现错误 Could not find any [COMPONENTS] variable in path

**Comment by cipchk** [comment]
duplcated of #1314

**Comment by devsharper** [comment]
ng-alain@8.4.0 & @angular/core@8.1.2 存在这个问题，升级@angular/core到 8.2.5 恢复正常
