### ISSUE TITLE
关于_HttpClient

### ISSUE THREAD

**Issue by downlder** [ng-alain/ng-alain#132]
@cipchk 你好
1.发现只有delon_scheme中_HttpClient会被拦截，而原生的HttpClient不会被拦截，请问在哪里配置使原生的HttpClient也可以被拦截呢？
2.delon_scheme中_HttpClient有一个诡异的问题，比如下面forkJoin怎么都不返回，而替换成原生的HttpClient可以正常返回。
        const reqs = [];
        for (var i = 0; i < 10; i++) {
            reqs.push(this.http.get('./assets/pois.json'));
        }
        console.log('start');
        Observable.forkJoin(reqs).subscribe(
            () => { console.log('next') },
            () => { console.log('error') },
            () => { console.log('complete') });

**Comment by cipchk** [comment]
1、关于这问题可能是子模块中拦截器被覆盖的原因（见 [#18894](https://github.com/angular/angular/issues/18894)），而 `_HttpClient` 和拦截器默认都是在根模块中注入，因此当使用 `_HttpClient` 调用时会无形中在同一个层级中调用到拦截器。

2、`forkJoin` 有一个前提是必须所有 Observable 都结束才会触发订阅方法，当然如果这个前提成立的话那的确很诡异。

**Comment by downlder** [comment]
首先，谢谢您的回复
第一个问题看不太明白，如果想使用原生的HttpClient,并且让SimpleIntercetor和DefaultInteceptor拦截之，如何做到？
第二个确实有这个问题， 单次调用this.http.get('./assets/pois.json')可以返回，但是在任何位置forkJoin多次这个接口this.http.get('./assets/pois.json')不返回，而改成原生HttpClient是可以返回的。

测试代码如下，当前版本，仅仅修改poi.components.ts
`
    import { Observable } from 'rxjs/Rx;

    load(reload: boolean = false) {
        if (reload) {
            this.s.pi = 1;
        }
        this.http.get('./assets/pois.json', this.s).subscribe((res: any) => {
            this.list = res.data;
            this.total = res.total;
        });

        //以下为增加代码，Rx forkJoin测试
        const reqs = [];
        for (var i = 0; i < 10; i++) {
            reqs.push(this.http.get('./assets/pois.json'));
        }
        console.log('start');
        //next, error, complete都没有返回
        Observable.forkJoin(reqs).subscribe(
            () => { console.log('next') },
            () => { console.log('error') },
            () => { console.log('complete') });
    }
`

**Comment by cipchk** [comment]
1、你可以相应的子模块中重新注册拦截器。

2、这是我的代码，我运行是正常：

```ts
import { forkJoin } from 'rxjs/observable/forkJoin';

        // 以下为增加代码，Rx forkJoin测试
        const reqs = [];
        for (let i = 0; i < 10; i++) {
            reqs.push(this.httpOrg.get('./assets/pois.json'));
        }
        console.log('start');
        // next, error, complete都没有返回
        forkJoin(reqs).subscribe(
            () => { console.log('next'); },
            () => { console.log('error'); },
            () => { console.log('complete'); }
        );
```

**Comment by cipchk** [comment]
1、你可以相应的子模块中重新注册拦截器。

2、好像的确无法运行，我目前也不清楚问题在哪，像是 Observable 无法真正完成一样，但实际已经发送请求，我尝试加上  `.pipe(take(1))` 的确成功了：

```ts
import { forkJoin } from 'rxjs/observable/forkJoin';

        // 以下为增加代码，Rx forkJoin测试
        const reqs = [];
        for (let i = 0; i < 10; i++) {
            reqs.push(this.http.get('./assets/pois.json').pipe(take(1)));
        }
        console.log('start');
        // next, error, complete都没有返回
        forkJoin(reqs).subscribe(
            () => { console.log('next'); },
            () => { console.log('error'); },
            () => { console.log('complete'); }
        );
```

更多细节恐怕我没办法告知你实际的原因。

**Comment by downlder** [comment]
谢谢
