### ISSUE TITLE
sf 可否加上 校验属性    updateOn?: 'change' | 'blur' | 'submit';

### ISSUE THREAD

**Issue by hennychen** [ng-alain/ng-alain#1320]
参考 
https://www.angular.cn/guide/form-validation#note-on-performance
/**
     * @description
     * The event name for control to update upon.
     */
    updateOn?: 'change' | 'blur' | 'submit';

目前看来 sf 是blur 来校验 ，用户输入完之后 失去焦点才会触发校验

**Comment by tangdou369098655** [comment]
这个功能是实现了吗？

**Comment by crazywen** [comment]
或者SF是否有接口暴露出来绑定相关事件的方法以及及时调用validate的方法，以自由组合事件调用校验。

**Comment by cipchk** [comment]
重构部分 `sf` [#969](https://github.com/ng-alain/delon/pull/969)，可以利用 `formValueChange` (将在 `9.5` 发布) 事件来监听当前哪个路径引起的数据变更，这是一种对任意小部件的做法。

同时，对于像 `string` 小部件内部也有 `change`、`blur` 等事件可以处理。

**Comment by cipchk** [comment]
fixed by `9.5.1`.
