### ISSUE TITLE
reuse-tab 匹配 :id/index 路由，路由无法切换了

### ISSUE THREAD

**Issue by Tinet-zhangmd** [ng-alain/ng-alain#1322]
路由如下
const routes: Routes = [
    {
    path: '', redirectTo: '/index/home', pathMatch: 'full'
  },
  {
    path: ':id', redirectTo: ':id/index/home', pathMatch: 'full'
  },
  {
    path: ':id/index', loadChildren: 'src/app/index/index.module#IndexModule'
  }
]；
如果我的路由是 http://www.baidu.com/aliyun，我首先会跳转到 http://www.baidu.com/aliyun/index/home,但是再跳转其它路由比如（http://www.baidu.com/aliyun/index/call）不能再跳转，也不会报错

**Comment by cipchk** [comment]
我无法重现，麻烦提供完整的重现示例，我的示例相关代码：

```ts
# Route config

{ path: ':id', redirectTo: ':id/index/home', pathMatch: 'full' },
{ path: ':id/index', component: DevPageComponent },
{ path: ':id/index/home', component: DevPageComponent },
{ path: ':id/index/call', component: DevPageComponent },

# Menu Config

{ text: 'aliyun', link: '/dev/aliyun' },
{ text: 'aliyun/index/home', link: '/dev/aliyun/index/home' },
{ text: 'aliyun/index/call', link: '/dev/aliyun/index/call' },
```

一个GIF动画：

![demo](https://user-images.githubusercontent.com/2987467/64432655-8940d780-d0ef-11e9-9d61-bec8ec38009d.gif)

**Comment by cipchk** [comment]
长时间未提供重现，因此关掉此 issues.
