### ISSUE TITLE
开启ivy构建报错

### ISSUE THREAD

**Issue by schuman66** [ng-alain/ng-alain#1323]
开启ivy后，ng build报错
错误信息：ERROR in There is no appropriate source code format in 'C:/Users/Administrator/Desktop/my-project/node_modules/date-fns/distance_in_words_to_now' entry-point.
这个需要怎么解决呢？

**Comment by cipchk** [comment]
目前还不支持 ivy

**Comment by schuman66** [comment]
> 目前还不支持 ivy

请问有支持 ivy时间计划吗

**Comment by cipchk** [comment]
目前我的工作太忙，可能会比较缓慢推进，希望9.x之前能支持。

**Comment by cipchk** [comment]
fixed by 9.x
