### ISSUE TITLE
reuse-tab附带参数问题

### ISSUE THREAD

**Issue by checkmateTowindn** [ng-alain/ng-alain#1324]
reuse-tab组件如今是不支持 QueryString 查询参数的，但实际需求中，新开选项卡，会给原有页面带去参数，然后根据不同数据，于页面中进行的业务处理。能否给reuse-tab增加可以带有参数功能，或者说，有什么奇淫技巧可以告知，帮助我解决此类业务需求。
在下是ng初学者，也是ng-alain爱好者，希望可以帮帮我。

**Comment by cipchk** [comment]
Angular 路由支持 `params` 参数化 和 `queryString` 参数，你可以使用 `params` 参数，请参阅：https://angular.io/guide/router#route-definition-with-a-parameter
