### ISSUE TITLE
sf 能否加上视觉分组功能

### ISSUE THREAD

**Issue by chf007** [ng-alain/ng-alain#1327]
有些场景下，一个表单，需要按组进行视觉上的区分，类似多个card，可以有标题，附加操作，折叠等功能。

目前虽然可以自已想办法实现，但都不是特别优优雅，例如可以搞多个sf，然后最后的一个提交，获取其它 sf 的值，组合在一起提交表单；又或者把标题做成一个纯展示的自定义小部件，但是提交时又要把无意义的值排除掉。

建议未来的版本可以考虑一些基础的视觉分组功能。类似如下：
![image](https://user-images.githubusercontent.com/358650/64487396-a7801200-d26c-11e9-8531-03f583cffa08.png)

**Comment by hennychen** [comment]
我现在是加的 自定义widget = 分组标题  原理同你说的类似，

**Comment by xingkoo** [comment]
sf 分类布局 #953
以前提过一个类似的功能增强问题,现在还是挂着讨论的tag.等大神回复你这个帖子,原帖关闭.

**Comment by danxiaogui** [comment]
表单分组功能需要自定义sf小组件去实现，Divider是不错的选择，对于json schema来说，目前比较便捷的方法是通过冗余字段去处理

**Comment by chf007** [comment]
https://github.com/alibaba/uform 这个 React Form 库，也是用 json schema 的，可以借鉴一下

**Comment by hennychen** [comment]
下面是 做成组件

import { Component, OnInit } from '@angular/core';
import { ControlWidget } from '@delon/form';

@Component({
  selector: 'app-sf-divider',
  template: `
  <sf-item-wrap [id]="id" [schema]="schema" [ui]="ui" [showError]="showError" [error]="error">
    
    <nz-divider [nzText]="Text" [nzOrientation]="Orientation"></nz-divider>
    
  </sf-item-wrap>`
})

export class DividerWidget extends ControlWidget implements OnInit {
  /* 用于注册小部件 KEY 值 */
  static readonly KEY = 'Divider';

  // 组件所需要的参数，建议使用 `ngOnInit` 获取
  Orientation: string;
  Text: string;
  ngOnInit(): void {
    this.Orientation = this.ui.Orientation || 'left';
    this.Text = this.ui.Text || '';
  }
 
}
使用方法 同其他组件
 Divider: {
        type: 'string',
        ui: {
          spanLabelFixed: 0,
          grid: { span: 24 },
          widget: 'Divider',
          Orientation: 'left',
          Text: '标题'
        },
 
      },

**Comment by 13776668267** [comment]
Divider的方式能折叠表单吗？

**Comment by cipchk** [comment]
Object 已经支持 card 模式。
