### ISSUE TITLE
cascader 组件运用nzLoadData属性异步请求需要点击两次

### ISSUE THREAD

**Issue by zhengyanghuaer** [ng-alain/ng-alain#1328]
🚨 Issues 是用于BUG、Feature、进度追踪 🚨
🚨 The issue tracker is not for questions 🚨

如果有任何问题，可在以下方式获得答案：

- https://ng-alain.com/
- QQ Group：316911865
- https://segmentfault.com/t/ng-alain

**Comment by cipchk** [comment]
长时间未提供重现，因此关掉此 issues.
