### ISSUE TITLE
建议提供一个基本的startKit

### ISSUE THREAD

**Issue by laohoo** [ng-alain/ng-alain#133]
正好要用angular整个后台管理系统，google了挺多，决定基于此项目进行开发。刚开始弄，提个建议，ng-alian说起来是脚手架，但实际上有很多页面是用不上的，特别是routes里面的，pro 也参杂在一起，要先弄个干净的脚手架代码，发现比较麻烦。

很多项目都单独提供了startKit脚手架，需要什么就从完整版本中copy，会更方便。

**Comment by cipchk** [comment]
很好的建议。

ng-alain  并非是我本质工作，绝大多数是利用业余时间，所以一直受于时间的限制；其实也计划了一个 alain-cli 的工具，一直被搁置。

在这之前，我也一直考虑提供一个 StartKit 干净脚手架的分支；待 `0.4.0` 正式后同步发布一个 StartKit 分支。

**Comment by vellengs** [comment]
确实，ionic 这方面做的挺好的。

**Comment by xingkoo** [comment]
正在测试各个功能，然后用来做基础模板。楼主有没有交流群什么的。大家有问题一块交流。

**Comment by Kiuyam** [comment]
316911865 管理员 asdf 是作者。

**Comment by xingkoo** [comment]
哈哈哈，前两天刚看到一个相关博客，asdfblog，难道就是作者？

**Comment by cipchk** [comment]
😄 正是鄙人的个人博客，只是太久没有更新了，Angular文章一般都发布在sf，最近又转至知乎；乱乱的。

**Comment by laohoo** [comment]
0.4版本什么时候能够发布，能同时提供startkit的话，就基于这个版本来开发了。

谢谢

**Comment by cipchk** [comment]
目前 rc 是最后一个版本，可能会过几天吧，这段时间不会再新增任何东西，只会修正部分BUG。

**Comment by Kiuyam** [comment]
前排 感谢作者。

**Comment by RogerHuangZB** [comment]
感谢作者！
