### ISSUE TITLE
st导出到excel，数据值为null，则导出的数据显示为null字符串

### ISSUE THREAD

**Issue by jinghun1999** [ng-alain/ng-alain#1334]
如题，在使用st导出数据到excel文件时，如果json数据中值为null，则在导出文件中看到为null字符串，理想显示应该为空，而非显示为null字符。是否可以在参数中控制显示？或者callback中处理？

**Comment by cipchk** [comment]
`null` 或 `undefined` 应为空这个理解是对的，我们优化这一部分。
