### ISSUE TITLE
st表格数据加载后事件

### ISSUE THREAD

**Issue by s641135196** [ng-alain/ng-alain#1335]
我想在使用st表格数据加载完后需要处理一些事件（如：选中表格第一行）， 
有什么好的方法吗？   因为我在st没找到加载完数据后相关的事件。

**Comment by xingkoo** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        
            
        
    
    
        查看细STRes部分,有个process
            
        
    
    
    
    

    

    

    在2019年09月18日 14:59，s641135196<notifications@github.com> 写道： 


我想在使用st表格数据加载完后需要处理一些事件（如：选中表格第一行），

有什么好的方法吗？   因为我在st没找到加载完数据后相关的事件。

**Comment by s641135196** [comment]
这个是数据提交前的处理了，我想要的是加载数据成功再处理相关逻辑

**Comment by s641135196** [comment]
@xingkoo 这个是数据提交前的处理了，我想要的是加载数据成功再处理相关逻辑

**Comment by xingkoo** [comment]
仔细看一下,一个是  **STReq**   一个是 **STRes**
后者是针对返回的数据进行处理的.
问题解决请关闭Issue.

**Comment by s641135196** [comment]
谢谢， 的确是可以的。在里面用settimeout延迟20就好了。
