### ISSUE TITLE
menuService bug！

### ISSUE THREAD

**Issue by zdxxxxxx** [ng-alain/ng-alain#134]
![4f5fed1e-7237-44cf-9375-937a74fac208](https://user-images.githubusercontent.com/16288673/34282244-e131337c-e6fe-11e7-9810-33953c415bfd.png)
![2722655e-dade-4379-82b8-c03f8daa6589](https://user-images.githubusercontent.com/16288673/34282253-e98a39ce-e6fe-11e7-878e-9674e00dd2ce.png)

**Comment by cipchk** [comment]
![tim 20171222101828](https://user-images.githubusercontent.com/2987467/34282580-7ae150a4-e701-11e7-83de-fd68e8f0f817.png)
