### ISSUE TITLE
sf同时绑定formData和formChange，会导致丢失焦点

### ISSUE THREAD

**Issue by codingzhou** [ng-alain/ng-alain#1340]
ng-alain version: 8.4.0
Angular version: 8.3.0

重现链接：https://stackblitz.com/edit/angular-4rcmdm-uxundm?embed=1&file=src/app/app.component.ts

重现步骤：当在页面上输入框中输入字符串时，每次输入都会导致焦点丢失

**Comment by codingzhou** [comment]
补充formData和formChange()
```
formData: any = {};

formChange(value) {
    this.formData = value;
 }
```

**Comment by cipchk** [comment]
并非丢失焦点，而是当表单内容发生变更时，又重置了 `data`，这倒置表单重新渲染。

**Comment by codingzhou** [comment]
@cipchk HI 卡色，测试了一下，当在formChange函数中，将value复制给formData时，会导致表单重新渲染，但是实际场景中，是需要监听表单内容变更，并且将value复制给formData的，有什么好的解决方案么？如果删掉formChange函数，只保留[formData]="formData"，会发现表单内容变更时，formData并没有实时更新

**Comment by aspsaopao** [comment]
刚刚试验过，闪电formchange 函数  表单内容变更 数据源是i发生了改变的

**Comment by aspsaopao** [comment]
可以在formSubmit函数的时候给data重新赋值,

**Comment by met-pub** [comment]
@codingzhou 我用了另外一个 formDataChanging 来存储变更的数据...
