### ISSUE TITLE
希望STColumnButton能增加Text、Icon的Color属性；在Children中无论是否包含Icon，保持Text对齐

### ISSUE THREAD

**Issue by ystemni** [ng-alain/ng-alain#1343]
现在采用添加icon，然后在less中强行指定color，不是很方便。希望能改进。

**Comment by mo-gong** [comment]
[STIcon](https://ng-alain.com/components/table/zh#STIcon) 已经包含完整的 ICON 参数属性。

**Comment by mo-gong** [comment]
[STIcon](https://ng-alain.com/components/table/zh#STIcon) 已经包含完整的 ICON 参数属性。

**Comment by cipchk** [comment]
@mo-gong 已经给出正解，因此关闭 issues.
