### ISSUE TITLE
使用reuse-tab，某个tab页中打开modal对话框，会产生全局的遮罩，这个遮罩有可能只在tab页内吗，不要影响别的tab页

### ISSUE THREAD

**Issue by zheiyi** [ng-alain/ng-alain#1345]
![modal](https://user-images.githubusercontent.com/9414207/65741526-e5ab7b80-e11e-11e9-9c05-b20d8abb7fbf.PNG)

期望：在一个tab页面打开模态框后，不影响切换到别的tab页（不必关掉modal后再切换tab页）

**Comment by cipchk** [comment]
> 需要用户处理事务，又不希望跳转页面以致打断工作流程时，可以使用 `Modal` 在当前页面正中打开一个浮层，承载相应的操作。

所以，不会考虑这个功能。
