### ISSUE TITLE
在AppModule中导入DelonAuthModule和添加JWTInterceptor，请求头没有传token

### ISSUE THREAD

**Issue by kernelmix** [ng-alain/ng-alain#1351]
- ng-alain version: 8.4.0
- Angular version: 8.3.8

## 【必填项】重现链接，Reproduction link
import { DelonAuthModule, JWTInterceptor } from '@delon/auth';

@NgModule({
  imports: [
    DelonAuthModule
  ],
  providers: [
    // 指定认证风格对应的HTTP拦截器
    { provide: HTTP_INTERCEPTORS, useClass: JWTInterceptor, multi: true}
  ]
})
export class AppModule { }

**Comment by cipchk** [comment]
是否加入 token 取决于 `ITokenService` 中的 `get()` 能否正确得到 `token` 参数，对于 jwt 会有一些格式校验。有关更多细节请参考：https://ng-alain.com/auth/service
