### ISSUE TITLE
切换页面后再回到当前页使用reuseTabService.replace会自动关闭

### ISSUE THREAD

**Issue by s641135196** [ng-alain/ng-alain#1352]
- ng-alain version: 8.2.3
- Angular version: 8.2.3

## 【必填项】重现链接，Reproduction link
![自动关闭动画](https://user-images.githubusercontent.com/8079013/66469812-2a3dfc00-eabb-11e9-96d9-6ac8af5d06eb.gif)

https://stackblitz.com/edit/ng-alain-setup-9xiyni

## 重现步骤，Steps to reproduce
切换页面后回到当前页使用reuseTabService.replace会关闭当前页（实际应该是替换才是想要的效果）

**Comment by cipchk** [comment]
duplcated of #1283
