### ISSUE TITLE
期待st组件可展开的增强

### ISSUE THREAD

**Issue by huangjianzhuang** [ng-alain/ng-alain#1354]
目前st组件的展开是这样的。
![11](https://user-images.githubusercontent.com/37693552/66549363-b7de2200-eb75-11e9-84fa-4925919122ed.png)
对于有父子层级的数据，期待能实现标题是子表的标题，表格内容是主表内容可通过“ng-template”自定义渲染，表格展开后的内容是子表内容和标题对应。如图所示，“parent”可控制展开或不展开children2~children5。
![22](https://user-images.githubusercontent.com/37693552/66549408-ca585b80-eb75-11e9-9b02-1e96eb250515.png)

**Comment by huangjianzhuang** [comment]
尝试过把st组件的component.html和component.ts拿下来做自己的组件互换38~88,89~94两段的位置，报错
![33](https://user-images.githubusercontent.com/37693552/66551026-34becb00-eb79-11e9-8a14-1612e2975542.png)

**Comment by cipchk** [comment]
`expand` 只是一个空行的占位符，如果一定要保持同父表格的宽度，你可以在 expand 的表格做好 `width` 做到同父表格相应的列宽度，`st` 除非 `nz-table` 有相应的支持，否则不会对这类现象做更新。
