### ISSUE TITLE
水波图在card里边初始化时渲染不出来，页面resize之后水波图才显示

### ISSUE THREAD

**Issue by GreatDreamtrue** [ng-alain/ng-alain#1355]
初始化时水波图不显示
![image](https://user-images.githubusercontent.com/24841486/66638003-c0525d80-ec46-11e9-990b-db6a7cd33f9f.png)
页面resize之后水波图才显示
![image](https://user-images.githubusercontent.com/24841486/66638108-ef68cf00-ec46-11e9-9938-8371b7aed2ca.png)

在初始化时给水波图加了一个样式transform: 'none'，初始化时水波图可以直接显示，但是不会自适应页面
![image](https://user-images.githubusercontent.com/24841486/66638396-7158f800-ec47-11e9-9a84-c837211746e1.png)

![image](https://user-images.githubusercontent.com/24841486/66638365-61d9af00-ec47-11e9-81a5-6713736ea5c2.png)

**Comment by cipchk** [comment]
`nz-card` 的实现会导致DOM渲染慢于外部的代码，因此建议给 `delay` 加上值来延迟水波图的渲染。

> 文档缺少 `delay` 的描述。
