### ISSUE TITLE
第三方组件ueditor在动态表单中如何使用

### ISSUE THREAD

**Issue by HuiHenry** [ng-alain/ng-alain#1356]
参照文档，设置了ui的widget为ueditor，但是展示出来是文本框
cContent: {
                type: 'string',
                title: '内容',
                ui:{
                    widget:'ueditor'
                }
 },

**Comment by cipchk** [comment]
`ueditor` 并非内置，需要你手动创建，细节请参阅文档：https://ng-alain.com/form/ueditor/zh
