### ISSUE TITLE
reuse-tab bug

### ISSUE THREAD

**Issue by xingkoo** [ng-alain/ng-alain#136]
频率快速点击左侧菜单后，开始进行自动跳来跳去模式。

另外。文档里面看不懂如何使用，我在layout里面的reuse-tab中添加[excludes]=‘Menu’类似的方式，并不没有看到有排除的效果。方便的话帖我段代码。

**Comment by xingkoo** [comment]
点击一个菜单，未完成切换时，点下一个菜单，就会出现这个情况。

**Comment by smile2014** [comment]
关闭所有tab，再打开某个菜单，会带出很多tab

**Comment by cipchk** [comment]
`reuse-tab` 组件的逻辑有点问题，我已经重写了，下一版本会发布。
