### ISSUE TITLE
如何在modal中打开qr

### ISSUE THREAD

**Issue by huangjianzhuang** [ng-alain/ng-alain#1360]
在share.module.ts中
entryComponents:[
    QRComponent,
  ]

在component.ts中
        const modal = this.modalService.create({
            nzContent: QRComponent,
            nzComponentParams:{
                value:"nzComponentParams"
            }
        });

结果不会报错，但modal中没有内容，审查元素发现qr下的img的src为unknown。如果想通过modal打开qr该如何做？

**Comment by cipchk** [comment]
有关 Modal 传递参数请参考：https://ng.ant.design/components/modal/zh#components-modal-demo-service
