### ISSUE TITLE
page-header 设置为 fixed 时。媒体查询匹配窗口小于 768px 时，定位不准确。

### ISSUE THREAD

**Issue by Sookii** [ng-alain/ng-alain#1361]
ng-alain version: "8.4.0",
angular version: "8.2.10"

该结果无论是打开时窗口天然小于 768px ，或者通过改变窗口大小使其小于 768px 都存在。

另外，slide 为展开状态时，通过改变窗口大小将窗口缩小到 768 px 以下时，slide 也不会被自动隐藏。

**Comment by cipchk** [comment]
尝试升级 ng-zorro-antd 至最新版，这个可能是 `nz-affix` 引起的
