### ISSUE TITLE
page-header在通过Router（params传递参数）导航路由时会消失

### ISSUE THREAD

**Issue by nitmali** [ng-alain/ng-alain#1362]
- ng-alain version: 8.4.0
- Angular version: 8.2.1

**Comment by cipchk** [comment]
请参考文档：https://ng-alain.com/components/reuse-tab/zh#%E4%B8%8D%E6%94%AF%E6%8C%81-QueryString-%E6%9F%A5%E8%AF%A2%E5%8F%82%E6%95%B0

**Comment by nitmali** [comment]
> 请参考文档：https://ng-alain.com/components/reuse-tab/zh#%E4%B8%8D%E6%94%AF%E6%8C%81-QueryString-%E6%9F%A5%E8%AF%A2%E5%8F%82%E6%95%B0

我并没有使用QueryString（QueryParams），这里产生的问题是page-header面包屑没有显示
![GIF](https://user-images.githubusercontent.com/32920712/67194210-387c0880-f429-11e9-9112-9e7ecda3e714.gif)

**Comment by cipchk** [comment]
@nitmali 麻烦提供一个重现示例。

**Comment by maxj00** [comment]
请问你地问题解决没有

**Comment by cipchk** [comment]
长时间未提供重现，暂时关闭。
