### ISSUE TITLE
reuse-tab在通过Router（params传递参数）导航路由时无法获取菜单标签文本

### ISSUE THREAD

**Issue by nitmali** [ng-alain/ng-alain#1363]
- ng-alain version: 8.4.0
- Angular version: 8.2.1

![image](https://user-images.githubusercontent.com/32920712/67184826-2b561e00-f417-11e9-84e0-2d9aba63da48.png)

**Comment by cipchk** [comment]
请参考文档：https://ng-alain.com/components/reuse-tab/zh#%E6%A0%87%E7%AD%BE%E6%96%87%E6%9C%AC
