### ISSUE TITLE
ng-alain侧边栏菜单最多只能创建三级菜单吗？四级就会不显示

### ISSUE THREAD

**Issue by dyx18539489507** [ng-alain/ng-alain#1364]
大侠,您好。请问alain的侧边栏菜单只能创建三级菜单吗？如果我要创建四级菜单呢？

**Comment by cipchk** [comment]
如果把组名也包含进来，ng-alain 算是有四级菜单；没有实现无限级这种操作，主要是因为超过三级的菜单将会有极差的可读性。

**Comment by dyx18539489507** [comment]
不好意思，大侠。这里我稍微杠一下,在不考虑可读性的情况下,ng-alain支持创建四级菜单吗?或者说是如何实现四级菜单呢？

**Comment by cipchk** [comment]
不支持，你可以 `extends` 类 `SidebarNavComponent`，并重写 `sidebar-nav.component.html`。

**Comment by dyx18539489507** [comment]
> 不支持，你可以 `extends` 类 `SidebarNavComponent`，并重写 `sidebar-nav.component.html`。

好的,非常感谢大侠在百忙时间中解答疑惑,麻烦您了
