### ISSUE TITLE
karma start failure

### ISSUE THREAD

**Issue by luohong123** [ng-alain/ng-alain#1366]
版本：
```json
"name": "ng-alain",
 "version": "8.1.0",
```
当执行 karma start 命令时，出现以下错误
![image](https://user-images.githubusercontent.com/20392340/67380838-832e8980-f5bd-11e9-8197-59be55e833fa.png)
```bash
23 10 2019 17:47:32.436:ERROR [karma-server]: Server start failed on port 9876: Error: The '@angular-devkit/build-angular/plugins/karma' karma plugin is meant to be used from within Angular CLI and will not work correctly outside of it.
```

**Comment by cipchk** [comment]
翻译中文大意是：这个很长的插件仅限于 Angular Cli 内使用。

其实如果你想测试，我想 `ng t` 会更简单一点。

**Comment by cipchk** [comment]
翻译中文大意是：这个很长的插件仅限于 Angular Cli 内使用。

其实如果你想测试，我想 `ng t` 会更简单一点。
