### ISSUE TITLE
reuse-tab 浏览器刷新后默认页面消失

### ISSUE THREAD

**Issue by chpxl2** [ng-alain/ng-alain#1367]
🚨 Issues 是用于BUG、Feature、进度追踪 🚨
🚨 The issue tracker is not for questions 🚨

登录之后页面有一个默认的页面例如/home,  没有对应的菜单。
当点击菜单路由调转到/shipment。这时刷新浏览器之后，默认的那个tab就没有了

目前的想法是：
在页面unload时获取存储的路由信息，存储到localStorage中，然后项目init时，只需要调用ReuseService的存储方法(store)即可。

目前还是没有解决这个问题。
有谁遇到过相似的问题或者有好的想法的，请告知~万分感谢！

如果有任何问题，可在以下方式获得答案：

- https://ng-alain.com/
- QQ Group：316911865
- https://segmentfault.com/t/ng-alain

**Comment by cipchk** [comment]
`reuse-tab` 存储的是一个完整的Component实例，它并不是简单的可被持久存储数据对象。

**Comment by chpxl2** [comment]
好的，谢谢回答。那我只能从业务层面上去改动了
