### ISSUE TITLE
st组件表头分组无法实现，是否可以支持下

### ISSUE THREAD

**Issue by BennyCxb** [ng-alain/ng-alain#1368]
st表头分组无法实现，看了源码应该是不支持多行表头，希望能增加多行表头以及表头分组的功能和示例代码，谢谢

**Comment by BennyCxb** [comment]
> st表头分组无法实现，看了源码应该是不支持多行表头，希望能增加多行表头以及表头分组的功能和示例代码，谢谢

**Comment by hennychen** [comment]
#1327 参考使用 nz-divider

**Comment by cipchk** [comment]
duplcated of #1143
