### ISSUE TITLE
The fact that the ueditor USES local resources for initialization failure is not a display editor

### ISSUE THREAD

**Issue by DreamPWJ** [ng-alain/ng-alain#137]
The fact that the ueditor USES local resources for initialization failure is not a display editor  The same is true for lazy loading pattern display instances

**Comment by cipchk** [comment]
please provider more information in the result, anything error that help solve the issues, thx.

**Comment by DreamPWJ** [comment]
I found a mistake
AddComponent.html:6 ERROR TypeError: Cannot read property 'offsetWidth' of null
    at renderUI (ueditor.all.js:29403)
    at ueditor.all.js:29349
    at doReady (ueditor.all.js:1151)
    at Object.domReady (ueditor.all.js:1160)
    at UE.Editor.editor.render (ueditor.all.js:29348)
    at Object.UE.getEditor (ueditor.all.js:29458)
    at eval (ueditor.component.js:57)
    at ZoneDelegate.invoke (zone.js:392)
    at Zone.run (zone.js:142)
    at NgZone.runOutsideAngular (core.js:4701)
View_AddComponent_0 @ AddComponent.html:6
proxyClass @ compiler.js:14647
DebugContext_.logError @ core.js:15030
ErrorHandler.handleError @ core.js:1488
(anonymous) @ core.js:5915
ZoneDelegate.invoke @ zone.js:392
Zone.run @ zone.js:142
NgZone.runOutsideAngular @ core.js:4701
ApplicationRef.tick @ core.js:5915
(anonymous) @ core.js:5741
ZoneDelegate.invoke @ zone.js:392
onInvoke @ core.js:4753
ZoneDelegate.invoke @ zone.js:391
Zone.run @ zone.js:142
NgZone.run @ core.js:4570
next @ core.js:5741
schedulerFn @ core.js:4339
SafeSubscriber.__tryOrUnsub @ Subscriber.js:240
SafeSubscriber.next @ Subscriber.js:187
Subscriber._next @ Subscriber.js:128
Subscriber.next @ Subscriber.js:92
Subject.next @ Subject.js:56
EventEmitter.emit @ core.js:4319
checkStable @ core.js:4718
onHasTask @ core.js:4766
ZoneDelegate.hasTask @ zone.js:445
ZoneDelegate._updateTaskCount @ zone.js:465
Zone._updateTaskCount @ zone.js:289
Zone.runTask @ zone.js:209
drainMicroTaskQueue @ zone.js:602
ZoneTask.invokeTask @ zone.js:503
invokeTask @ zone.js:1540
globalZoneAwareCallback @ zone.js:1566
AddComponent.html:6 ERROR CONTEXT DebugContext_ {view: {…}, nodeIndex: 13, nodeDef: {…}, elDef: {…}, elView: {…}}
View_AddComponent_0 @ AddComponent.html:6
proxyClass @ compiler.js:14647
DebugContext_.logError @ core.js:15030
ErrorHandler.handleError @ core.js:1493
(anonymous) @ core.js:5915
ZoneDelegate.invoke @ zone.js:392
Zone.run @ zone.js:142
NgZone.runOutsideAngular @ core.js:4701
ApplicationRef.tick @ core.js:5915
(anonymous) @ core.js:5741
ZoneDelegate.invoke @ zone.js:392
onInvoke @ core.js:4753
ZoneDelegate.invoke @ zone.js:391
Zone.run @ zone.js:142
NgZone.run @ core.js:4570
next @ core.js:5741
schedulerFn @ core.js:4339
SafeSubscriber.__tryOrUnsub @ Subscriber.js:240
SafeSubscriber.next @ Subscriber.js:187
Subscriber._next @ Subscriber.js:128
Subscriber.next @ Subscriber.js:92
Subject.next @ Subject.js:56
EventEmitter.emit @ core.js:4319
checkStable @ core.js:4718
onHasTask @ core.js:4766
ZoneDelegate.hasTask @ zone.js:445
ZoneDelegate._updateTaskCount @ zone.js:465
Zone._updateTaskCount @ zone.js:289
Zone.runTask @ zone.js:209
drainMicroTaskQueue @ zone.js:602
ZoneTask.invokeTask @ zone.js:503
invokeTask @ zone.js:1540
globalZoneAwareCallback @ zone.js:1566
zone.js:2933 GET http://localhost:4200/net/controller.ashx?action=config&&noCache=1513996733068 404 (Not Found)
scheduleTask @ zone.js:2933
ZoneDelegate.scheduleTask @ zone.js:411
Zone.scheduleTask @ zone.js:236
Zone.scheduleMacroTask @ zone.js:259
(anonymous) @ zone.js:2966
proto.(anonymous function) @ zone.js:1366
doAjax @ ueditor.all.js:8247
request @ ueditor.all.js:8391
(anonymous) @ ueditor.all.js:8088
ZoneDelegate.invokeTask @ zone.js:425
Zone.runTask @ zone.js:192
ZoneTask.invokeTask @ zone.js:499
ZoneTask.invoke @ zone.js:488
timer @ zone.js:2040
setTimeout (async)
scheduleTask @ zone.js:2056
ZoneDelegate.scheduleTask @ zone.js:411
Zone.scheduleTask @ zone.js:236
Zone.scheduleMacroTask @ zone.js:259
(anonymous) @ zone.js:2072
proto.(anonymous function) @ zone.js:1366
UE.Editor.loadServerConfig @ ueditor.all.js:8078
UE.Editor @ ueditor.all.js:6751
UE.ui.Editor @ ueditor.all.js:29333
UE.getEditor @ ueditor.all.js:29457
(anonymous) @ ueditor.component.js:57
ZoneDelegate.invoke @ zone.js:392
Zone.run @ zone.js:142
NgZone.runOutsideAngular @ core.js:4701
UEditorComponent.init @ ueditor.component.js:53
UEditorComponent.ngOnInit @ ueditor.component.js:31
checkAndUpdateDirectiveInline @ core.js:12400
checkAndUpdateNodeInline @ core.js:13927
checkAndUpdateNode @ core.js:13870
debugCheckAndUpdateNode @ core.js:14763
debugCheckDirectivesFn @ core.js:14704
(anonymous) @ AddComponent.html:6
debugUpdateDirectives @ core.js:14689
checkAndUpdateView @ core.js:13836
callViewAction @ core.js:14187
execComponentViewsAction @ core.js:14119
checkAndUpdateView @ core.js:13842
callViewAction @ core.js:14187
execEmbeddedViewsAction @ core.js:14145
checkAndUpdateView @ core.js:13837
callViewAction @ core.js:14187
execComponentViewsAction @ core.js:14119
checkAndUpdateView @ core.js:13842
callViewAction @ core.js:14187
execEmbeddedViewsAction @ core.js:14145
checkAndUpdateView @ core.js:13837
callViewAction @ core.js:14187
execComponentViewsAction @ core.js:14119
checkAndUpdateView @ core.js:13842
callWithDebugContext @ core.js:15090
debugCheckAndUpdateView @ core.js:14627
ViewRef_.detectChanges @ core.js:11601
(anonymous) @ core.js:5908
ApplicationRef.tick @ core.js:5908
(anonymous) @ core.js:5741
ZoneDelegate.invoke @ zone.js:392
onInvoke @ core.js:4753
ZoneDelegate.invoke @ zone.js:391
Zone.run @ zone.js:142
NgZone.run @ core.js:4570
next @ core.js:5741
schedulerFn @ core.js:4339
SafeSubscriber.__tryOrUnsub @ Subscriber.js:240
SafeSubscriber.next @ Subscriber.js:187
Subscriber._next @ Subscriber.js:128
Subscriber.next @ Subscriber.js:92
Subject.next @ Subject.js:56
EventEmitter.emit @ core.js:4319
checkStable @ core.js:4718
onHasTask @ core.js:4766
ZoneDelegate.hasTask @ zone.js:445
ZoneDelegate._updateTaskCount @ zone.js:465
Zone._updateTaskCount @ zone.js:289
Zone.runTask @ zone.js:209
drainMicroTaskQueue @ zone.js:602
ZoneTask.invokeTask @ zone.js:503
invokeTask @ zone.js:1540
globalZoneAwareCallback @ zone.js:1566
ueditor.all.js:8111 请求后台配置项http错误，上传功能将不能正常使用！
showErrorMsg @ ueditor.all.js:8111
onerror @ ueditor.all.js:8102
xhr.onreadystatechange @ ueditor.all.js:8239
wrapFn @ zone.js:1166
ZoneDelegate.invokeTask @ zone.js:425
Zone.runTask @ zone.js:192
ZoneTask.invokeTask @ zone.js:499
invokeTask @ zone.js:1540
globalZoneAwareCallback @ zone.js:1566
XMLHttpRequest.send (async)
scheduleTask @ zone.js:2933
ZoneDelegate.scheduleTask @ zone.js:411
Zone.scheduleTask @ zone.js:236
Zone.scheduleMacroTask @ zone.js:259
(anonymous) @ zone.js:2966
proto.(anonymous function) @ zone.js:1366
doAjax @ ueditor.all.js:8247
request @ ueditor.all.js:8391
(anonymous) @ ueditor.all.js:8088
ZoneDelegate.invokeTask @ zone.js:425
Zone.runTask @ zone.js:192
ZoneTask.invokeTask @ zone.js:499
ZoneTask.invoke @ zone.js:488
timer @ zone.js:2040
setTimeout (async)
scheduleTask @ zone.js:2056
ZoneDelegate.scheduleTask @ zone.js:411
Zone.scheduleTask @ zone.js:236
Zone.scheduleMacroTask @ zone.js:259
(anonymous) @ zone.js:2072
proto.(anonymous function) @ zone.js:1366
UE.Editor.loadServerConfig @ ueditor.all.js:8078
UE.Editor @ ueditor.all.js:6751
UE.ui.Editor @ ueditor.all.js:29333
UE.getEditor @ ueditor.all.js:29457
(anonymous) @ ueditor.component.js:57
ZoneDelegate.invoke @ zone.js:392
Zone.run @ zone.js:142
NgZone.runOutsideAngular @ core.js:4701
UEditorComponent.init @ ueditor.component.js:53
UEditorComponent.ngOnInit @ ueditor.component.js:31
checkAndUpdateDirectiveInline @ core.js:12400
checkAndUpdateNodeInline @ core.js:13927
checkAndUpdateNode @ core.js:13870
debugCheckAndUpdateNode @ core.js:14763
debugCheckDirectivesFn @ core.js:14704
(anonymous) @ AddComponent.html:6
debugUpdateDirectives @ core.js:14689
checkAndUpdateView @ core.js:13836
callViewAction @ core.js:14187
execComponentViewsAction @ core.js:14119
checkAndUpdateView @ core.js:13842
callViewAction @ core.js:14187
execEmbeddedViewsAction @ core.js:14145
checkAndUpdateView @ core.js:13837
callViewAction @ core.js:14187
execComponentViewsAction @ core.js:14119
checkAndUpdateView @ core.js:13842
callViewAction @ core.js:14187
execEmbeddedViewsAction @ core.js:14145
checkAndUpdateView @ core.js:13837
callViewAction @ core.js:14187
execComponentViewsAction @ core.js:14119
checkAndUpdateView @ core.js:13842
callWithDebugContext @ core.js:15090
debugCheckAndUpdateView @ core.js:14627
ViewRef_.detectChanges @ core.js:11601
(anonymous) @ core.js:5908
ApplicationRef.tick @ core.js:5908
(anonymous) @ core.js:5741
ZoneDelegate.invoke @ zone.js:392
onInvoke @ core.js:4753
ZoneDelegate.invoke @ zone.js:391
Zone.run @ zone.js:142
NgZone.run @ core.js:4570
next @ core.js:5741
schedulerFn @ core.js:4339
SafeSubscriber.__tryOrUnsub @ Subscriber.js:240
SafeSubscriber.next @ Subscriber.js:187
Subscriber._next @ Subscriber.js:128
Subscriber.next @ Subscriber.js:92
Subject.next @ Subject.js:56
EventEmitter.emit @ core.js:4319
checkStable @ core.js:4718
onHasTask @ core.js:4766
ZoneDelegate.hasTask @ zone.js:445
ZoneDelegate._updateTaskCount @ zone.js:465
Zone._updateTaskCount @ zone.js:289
Zone.runTask @ zone.js:209
drainMicroTaskQueue @ zone.js:602
ZoneTask.invokeTask @ zone.js:503
invokeTask @ zone.js:1540
globalZoneAwareCallback @ zone.js:1566

**Comment by cipchk** [comment]
how import `UEditorModule` and *ueditor* script directory structure?

**Comment by DreamPWJ** [comment]
The same as the instance demo you wrote, your demo instance also has this situation ueditor.component. HTML you can see your scaffolding    I have modified the cost       UEditorModule.forRoot({
            // **注：** 建议使用本地路径；以下为了减少 ng-alain 脚手架的包体大小引用了CDN，可能会有部分功能受影响
            // 指定ueditor.js路径目录
            path: 'assets/ueditor/',
            // 默认全局配置项
            options: {
                themePath: '/assets/ueditor/themes/'
            }
        }),

**Comment by cipchk** [comment]
i not sure what the reason in accordance with `Cannot read property 'offsetWidth' of null`, this look like execute *UEditor* command before component initialization.

Also, the `ngx-ueditor` [demo](https://github.com/cipchk/ngx-ueditor/blob/master/demo/src/app/app.module.ts#L28) just using local script resources. i hope that will help you.

**Comment by cipchk** [comment]
i think `reuse-tab` that cause the problem. beause of route reuse that direct causes DOM lost.
