### ISSUE TITLE
stColumn 按钮列不换行

### ISSUE THREAD

**Issue by smmoums** [ng-alain/ng-alain#1370]
stColumn 按钮列设置了宽度，按钮多的时候以前会换行的，现在不换行并把这一行撑宽了，影响了其他列的宽度

**Comment by cipchk** [comment]
@smmoums 请提供一个重现示例，不同版本 `nz-table` 都会在迭代，可能渲染不同，我无法判断。

**Comment by smmoums** [comment]
> @smmoums 请提供一个重现示例，不同版本 `nz-table` 都会在迭代，可能渲染不同，我无法判断。

https://stackblitz.com/edit/angular-wrmc2n

**Comment by smmoums** [comment]
@cipchk  btn的列宽度问题，stackblitz终于能用了， 例子是文档的跳转改了下stcolumn

**Comment by cipchk** [comment]
使用 `widthMode` 严格模式来限定。
