### ISSUE TITLE
换肤问题

### ISSUE THREAD

**Issue by flxy1028** [ng-alain/ng-alain#1371]
这是换肤生成 alain-default.less过程中用到的一个方法，这个换色应该全面一点， 比如我项目中要换一个svg 的填充色，有属性 fill 和 stroke ,但这个方法是没有包含的，导致换不了
const reducePlugin = postcss.plugin("reducePlugin", () => {
  const cleanRule = rule => {
    if (rule.selector.startsWith(".main-color .palatte-")) {
      rule.remove();
      return;
    }
    let removeRule = true;
    rule.walkDecls(decl => {
      if (
        !decl.prop.includes("color") &&
        !decl.prop.includes("background") &&
        !decl.prop.includes("border") &&
        !decl.prop.includes("box-shadow")
      ) {
        decl.remove();
      } else {
        removeRule = false;
      }
    });
    if (removeRule) {
      rule.remove();
    }
  };
  return css => {
    css.walkAtRules(atRule => {
      atRule.remove();
    });

    css.walkRules(cleanRule);

    css.walkComments(c => c.remove());
  };
});

**Comment by cipchk** [comment]
的确如此，目前 `antd-theme-generator` 并没可自定义的操作，`ng-alain` 暂时也没有考虑 fork 它进行定制。
