### ISSUE TITLE
如何根据ng-cli的版本选择ng-alain的版本呢

### ISSUE THREAD

**Issue by zhaoyan11** [ng-alain/ng-alain#1372]
看官网上说 “请先通过 ng version 命令确认全局 Angular Cli 版本为最新版本号”。
如果我的 Angular Cli为6.0.0或其他某个版本，我该如何进行ng-alain的版本选择啊

**Comment by cipchk** [comment]
https://www.npmjs.com/package/@angular/cli#installation
