### ISSUE TITLE
reuse-tab组件BUG

### ISSUE THREAD

**Issue by rzjen** [ng-alain/ng-alain#1375]
- ng-alain version: 8.4.0
- Angular version: 8.1.0
reuse-tab超过最大复用数时没有清除之前的复用，再次点击未清除的复用时导致无限循环(详情见GIF) 
![lz](https://user-images.githubusercontent.com/46470156/67731566-a0d37700-fa33-11e9-9feb-239f73b74129.gif)

## 操作步骤
1、正常启用路由复用；
2、设置最大路由复用数为2；
3、点击菜单加载路由；
4、当路由复用数量操作最大路由复用数时第一个并没有销毁，点击第一个时出现无限循环。
![微信图片_20191029100609](https://user-images.githubusercontent.com/46470156/67731623-c95b7100-fa33-11e9-8c11-7f1e0acfd9be.png)
点击图片中红框标记就会出现无限循环

**Comment by cipchk** [comment]
duplcated of #1270

**Comment by rzjen** [comment]
我看了你那个GIF动画,操作步骤不对,当路由复用数量操作最大路由复用数时第一个并没有销毁，点击第一个时出现无限循环。备注（是点击
![QQ截图20191030090649](https://user-images.githubusercontent.com/46470156/67820536-a1801200-faf4-11e9-932a-c9f0e9552cfd.png)这个切换路由出现的无限循环,而不是点击右边的菜单切换,重要的事说三遍,
）
