### ISSUE TITLE
icon 报错

### ISSUE THREAD

**Issue by succulen-plants** [ng-alain/ng-alain#1377]
- ng-alain version: 8.4.0
- Angular version: 8.2.3

## 重现步骤，Steps to reproduce
使用一些icon时报错
  <i nz-icon nzType="drag" nzTheme="outline"></i>
使用了官方推荐的方法https://ng-alain.com/theme/icon/zh
core.js:6014 ERROR TypeError: Cannot read property 'toLowerCase' of undefined

**Comment by cipchk** [comment]
@succulen-plants  麻烦提供明确的重现步骤。

**Comment by cipchk** [comment]
关闭长时间未提供重现示例。
