### ISSUE TITLE
sf的select组件使用下scrollToBottom的时候会触发多次

### ISSUE THREAD

**Issue by ChaoQunPeng** [ng-alain/ng-alain#1381]
- ng-alain version: 8.4.0
- Angular version: 8.2.5

官网的例子无法正确运行，所以我找了之前的一些stackblitz链接，复现里的delon是  7.1.0，不过我项目里的8.4.0的也会有同样的问题。
而且如果在底部上上下下的拖动滚动条也会触发scrollToBottom事件

## 【必填项】重现链接，Reproduction link
https://stackblitz.com/edit/ng-alain-setup-ptjbwu?file=src/app/app.component.ts

## 重现步骤，Steps to reproduce
1、打开控制台
2、将下拉框拉到底部，可以看到下拉事件执行了多次

希望能实现的是下拉加载数据同时刷新select的enums

**Comment by cipchk** [comment]
关闭长时间未提供重现示例。

**Comment by cipchk** [comment]
受限于 https://github.com/NG-ZORRO/ng-zorro-antd/issues/4585

**Comment by cipchk** [comment]
最新版本已修复 。
