### ISSUE TITLE
sidebar-nav主菜单openStrictly不起作用的问题

### ISSUE THREAD

**Issue by abbylyy** [ng-alain/ng-alain#1382]
/template/tab/auto_pay/export-table/jlasync_view_a?title=多渠道自助缴费表（机构）
这样配置一个路由之后下拉菜单选择某项后自动关闭，现在的需求是不让它自动关闭，文档上说openStrictly属性用于控制展开完全受控，不再自动关闭已展开的项，贴上一个我使用的例子：
<sidebar-nav [openStrictly]="'true'"></sidebar-nav>，完全没反应

**Comment by cipchk** [comment]
关闭长时间未提供重现示例。

**Comment by 154192** [comment]
怎么配置点击二级菜单，其他已经展开的菜单不自动关闭
