### ISSUE TITLE
date bug问题

### ISSUE THREAD

**Issue by lvjiefang123** [ng-alain/ng-alain#1383]
得到 1969-09-03 转化为 19690903后 赋到给formData然后displayFormat得到的和展示的数值不对这是bug吗？
![image](https://user-images.githubusercontent.com/52185699/67929861-60bdf100-fbf9-11e9-9ab2-f124450bc61b.png)

**Comment by cipchk** [comment]
Timestamp 最低是 `1970-1-1 0:0:0`，如果有特殊需求，建议使用自定义小部件 。
