### ISSUE TITLE
无法兼容到ie9

### ISSUE THREAD

**Issue by quguangle** [ng-alain/ng-alain#1384]
项目在ie9下无法显示，更改这里
# This file is currently used by autoprefixer to adjust CSS to support the below specified browsers
# For additional information regarding the format and rule options, please see:
# https://github.com/browserslist/browserslist#queries
# For IE 9-11 support, please uncomment the last line of the file and adjust as needed
> 0.5%
last 2 versions
Firefox ESR
not dead
IE 9-11
也是没用，如果作者有时间，把ie9兼容性也做一下吧

**Comment by cipchk** [comment]
ng-alain 的基础组件库是 ng-zorro-antd，其支持的环境是IE11，见 [ng-zorro-antd文档](https://ng.ant.design/docs/introduce/zh#%E6%94%AF%E6%8C%81%E7%8E%AF%E5%A2%83)
