### ISSUE TITLE
7.x版本 @delon 下的excel导出组件默认联网下载 xlsx,而不是引用本地组件

### ISSUE THREAD

**Issue by weifengliuhen** [ng-alain/ng-alain#1385]
🚨 Issues 是用于BUG、Feature、进度追踪 🚨
🚨 The issue tracker is not for questions 🚨
ng-alain version: "7.x",

![image](https://user-images.githubusercontent.com/57127585/67996126-ee94ed00-fc88-11e9-92df-d94d8302d36e.png)
此处是以修改的,本地有安装 (npm install xlsx),但是仍会去(cdn.bootcss.com)下载,导致离线的时候导出功能失效.
如果有任何问题，可在以下方式获得答案：

- https://ng-alain.com/
- QQ Group：316911865
- https://segmentfault.com/t/ng-alain

**Comment by cipchk** [comment]
duplcated of #1376
