### ISSUE TITLE
建议为SF增加formValues属性或getFormValues方法

### ISSUE THREAD

**Issue by Auklet2019** [ng-alain/ng-alain#1387]
实际开发中可能会遇到这种情况，把一个有很多属性的大对象设为 sf 的 formData，而实际 schema 只定义了少数几个属性，使用 sf.value 获取到的仍然是整个 formData 对象，这样处理起来很不方便，希望能增加一个类似 formValues 之类的属性或方法，可以方便地获取到 schema 定义的全部 property 的值，忽略 schema 未定义的那些 formData 字段

**Comment by xingkoo** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        
            
        
    
    支持这个增强功能.目前也遇到了这样的问题.暂时通过init()二次赋值数据到指定的变量中来做为formdata使用.
    
    
    

    

    

    在2019年11月2日 04:13，Auklet2019<notifications@github.com> 写道： 


实际开发中可能会遇到这种情况，把一个有很多属性的大对象设为 sf 的 formData，而实际 schema 只定义了少数几个属性，使用 sf.value 获取到的仍然是整个 formData 对象，这样处理起来很不方便，希望能增加一个类似 formValues 之类的属性或方法，可以方便地获取到 schema 定义的全部 property 的值，忽略 schema 未定义的那些 formData 字段
