### ISSUE TITLE
运用ueditor富文本框,errorHandler is not defined

### ISSUE THREAD

**Issue by zhengyanghuaer** [ng-alain/ng-alain#1388]
🚨 Issues 是用于BUG、Feature、进度追踪 🚨
🚨 The issue tracker is not for questions 🚨

如果有任何问题，可在以下方式获得答案：

- https://ng-alain.com/
- QQ Group：316911865
- https://segmentfault.com/t/ng-alain

**Comment by zhengyanghuaer** [comment]
上传单张图片报![image](https://user-images.githubusercontent.com/35128870/68172626-2ebedd00-ffb3-11e9-9d8e-f6cd8b1e0be0.png)
上传多张图片![image](https://user-images.githubusercontent.com/35128870/68172648-47c78e00-ffb3-11e9-8fa6-0c73e3875e34.png)

**Comment by cipchk** [comment]
https://www.baidu.com/s?ie=UTF-8&wd=errorHandler%20is%20not%20defined
