### ISSUE TITLE
404页面为何没隐藏顶部导航？

### ISSUE THREAD

**Issue by codingzhou** [ng-alain/ng-alain#1391]
- ng-alain version: 8.4.0
- Angular version: 8.1.2
![image](https://user-images.githubusercontent.com/14120629/68272399-88500600-009e-11ea-8d67-718f9283b6d8.png)
![image](https://user-images.githubusercontent.com/14120629/68272404-8dad5080-009e-11ea-8026-d7f53335d001.png)
如上截图，404页面应该隐藏顶部导航(header-component)，但是却没有隐藏，这是为什么呢？

**Comment by cipchk** [comment]
将 [exception](https://github.com/ng-alain/ng-alain/blob/master/src/app/routes/routes-routing.module.ts#L44) 移出 `LayoutDefaultComponent` 的包裹。
