### ISSUE TITLE
notosanssc.css 谷歌字体文件加载问题

### ISSUE THREAD

**Issue by wangpai192** [ng-alain/ng-alain#1394]
**问题描述**：系统启动时会加载这个(https://fonts.googleapis.com/earlyaccess/notosanssc.css)文件，但是由于网络问题加载失败造成页面白屏；

在编辑器全局查找也找不到这个请求..

**想要结果**：如何能去掉这个请求？
![image](https://user-images.githubusercontent.com/30720792/68569176-68528500-0498-11ea-90bb-c933904f8ba5.png)

**Comment by cipchk** [comment]
抱歉，请问是什么编辑器，以及你如何使用的，最好能提供一个重现示例，否则我无法帮到你。

**Comment by wangpai192** [comment]
编辑器：vsCode
ng-alain: 8.4.0
angular: 8.2.13
angular/cli:  8.3.18

重现示例不好提供，在网络状态不好的情况下才出现，
就是如图所示的文件，网络正常时可以加载，网络不好时就加载不了，
![image](https://user-images.githubusercontent.com/30720792/68752377-2bc08e00-063e-11ea-96da-1bf4dde9f79b.png)

我想知道这个是哪个包引入的文件，能否替换成本地的

**Comment by cipchk** [comment]
ng-alain 并没有引用 `notosanssc.css` 检查一下是否你使用第三方类库引起。
