### ISSUE TITLE
ng server 报错：ERROR TypeError: Cannot read property 'orgs' of null

### ISSUE THREAD

**Issue by succulen-plants** [ng-alain/ng-alain#1395]
- ng-alain version: 8.4.0
- Angular version: 8.2.3

## 【必填项】重现链接，Reproduction link

![屏幕快照 2019-11-12 上午10 40 50](https://user-images.githubusercontent.com/16435419/68637234-f5e5b180-0538-11ea-9a3c-7fc86f7ff868.png)

## 重现步骤，Steps to reproduce

开发环境没有问题， serve的时候报这个问题， 导致页面不出现

**Comment by cipchk** [comment]
关闭长时间未提供重现示例。
