### ISSUE TITLE
SFButton  按钮默认是居中， 想布局在右边

### ISSUE THREAD

**Issue by succulen-plants** [ng-alain/ng-alain#1396]
🚨 Issues 是用于BUG、Feature、进度追踪 🚨
🚨 The issue tracker is not for questions 🚨

如果有任何问题，可在以下方式获得答案：
  button: SFButton = {
    submit:'提交',
    submit_type:'primary',
    reset:'重置',
    reset_type:'default',
    render: {
      offsetControl:20
    }
  }

不知道怎么写 render， 也没有示例

- https://ng-alain.com/
- QQ Group：316911865
- https://segmentfault.com/t/ng-alain

**Comment by cipchk** [comment]
没有可配置达到居中的效果；但可以通过设置 `button: null`，然后自定义按钮，https://ng-alain.com/form/getting-started/zh#%E7%BB%84%E4%BB%B6%E6%96%B9%E6%B3%95
