### ISSUE TITLE
angular7升级8后 reuse-tab组件内路由传参丢失参数

### ISSUE THREAD

**Issue by maxj00** [ng-alain/ng-alain#1397]
升级后 在reuse-tab里的路由传参会丢失，使用activatedRoute.queryParams.subscribe的方法去获取路由参数时，会直接运行两遍，第一次是可以获取的参数的，第二次就自动清空了参数，angular7没有这个问题，升级angular8就出现这个问题，有解决的方法吗？

**Comment by maxj00** [comment]
![image](https://user-images.githubusercontent.com/34929485/68824322-73dcc080-06d1-11ea-9372-ab73972b827d.png)
![image](https://user-images.githubusercontent.com/34929485/68824385-a4bcf580-06d1-11ea-9fb6-c7c79b056100.png)

**Comment by cipchk** [comment]
`queryParams` 至始至终都不支持，只支持 `params` 参数。

**Comment by maxj00** [comment]
> `queryParams`至始至终都不支持，只支持`params`参数。
是改这个吗 试过了 也是不行 也是获取到了 然后又自己清空

![image](https://user-images.githubusercontent.com/34929485/68825062-cd45ef00-06d3-11ea-83d2-90550a2c5deb.png)

**Comment by cipchk** [comment]
@maxj00 能否提供一个重现示例。

**Comment by maxj00** [comment]
@cipchk   请问如何提供重现 谢谢

**Comment by maxj00** [comment]
> @cipchk 改成params参数可以传参了，但是reuse-tab的标签不能复用 ，传一次参数就增加一个标签，有解决方法吗

**Comment by huangjianzhuang** [comment]
我也遇到同样的问题。官方说reuse-tab不支持queryParams，不过在angular7下可以使用，更新angular8后就不行了会直接运行两遍，第一次是可以获取的参数的，第二次就自动清空了参数。

**Comment by cipchk** [comment]
@huangjianzhuang 都不支持 queryParams，因为根据我们经验非常容易引起过载而导致内存泄漏。
