### ISSUE TITLE
建议为SF布局增加强制换行参数

### ISSUE THREAD

**Issue by Auklet2019** [ng-alain/ng-alain#1398]
当SF布局比较复杂时换行不太好控制。

比如希望一个widget只占表单一半的宽度，但要独占一行，右侧留空。如果指定span:12，那么下一个widget如果span小于或等于12就会自动补到右侧。

希望能实现，不论span怎么设置，都可以强制一个widget显示到新的一行中。

**Comment by cipchk** [comment]
是的，因为一行被分为 `24` 大小。如果你想保留，只能是设置 `span: 24`。
