### ISSUE TITLE
对于控制台应用，更常见的是把左侧菜单设置为深色，比如阿里云的控制台。能否在主题中增加深色菜单选项？

### ISSUE THREAD

**Issue by dusdong** [ng-alain/ng-alain#14]
## Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Desired functionality.

对于控制台应用，更常见的是把左侧菜单设置为深色，比如阿里云的控制台。能否在主题中增加深色菜单选项？

**Comment by cipchk** [comment]
我会提供相应的参数，然后有需求可以自行在 [_alain-custom-variables.scss](https://github.com/cipchk/ng-alain/blob/master/src/styles/_alain-custom-variables.scss) 修改，但不会作为默认发布。

**Comment by dusdong** [comment]
好的，ths~
