### ISSUE TITLE
关于ReuseTabComponent的标题

### ISSUE THREAD

**Issue by downlder** [ng-alain/ng-alain#140]
## Bug Report or Feature Request (mark with an `x`)
<pre><code>
[ ] Bug report -> please search issues before submitting
[x] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

当前ReuseTab的title是从MenuService中读取，我个人觉得不太合适，reuse-tab的title和页面的标题一样应该和Menu解耦，因为:
1)有些页面是不放到Menu中的;
2)有些页面的url是动态的；
以上最常见的情况就是列表的详情页面，比如 /roles/1, roels/2等，这种详情页面不用对话框形式 并且详情不会放到Menu中，而且url不是固定的。

## Expected behavior

希望页面的tab标题从路由或则从活动页面读取，类似页面标题，谢谢。

**Comment by cipchk** [comment]
`reuse-tab` 已经重写了，下一版本会发布，除了解决一些逻辑问题，包括 title 获取方式也会有相应的变化。
