### ISSUE TITLE
Widget array cannot display optionalHelp on hover

### ISSUE THREAD

**Issue by NanFengCheong** [ng-alain/ng-alain#1400]
## 【必填项】重现链接，Reproduction link

https://stackblitz.com/edit/angular-nalbrx?file=src/app/app.component.ts

## 重现步骤，Steps to reproduce
Similar with #1390

**Comment by NanFengCheong** [comment]
@cipchk 
Maybe you can replace all?
https://github.com/ng-alain/delon/search?q=%5BnzTooltipTrigger%5D&unscoped_q=%5BnzTooltipTrigger%5D
![image](https://user-images.githubusercontent.com/7321833/68919616-b5429e00-07ad-11ea-984c-99e737490934.png)

**Comment by cipchk** [comment]
@NanFengCheong This is because of `nzTooltipPlacement` written as `nzTooltipTrigger`.

**Comment by NanFengCheong** [comment]
@cipchk Got it. My bad.
