### ISSUE TITLE
ST组件合计功能

### ISSUE THREAD

**Issue by myprogo** [ng-alain/ng-alain#1402]
- ng-alain version: 8.6.0
- Angular version: 8.5.0
使用了ST的合计功能，
`
<st #st [data]="data" [columns]="columns" [page]="{ show: false }" [body]="bodyTpl">
      <ng-template #bodyTpl let-s>
        <tr>
          <td colspan="5" class="text-right">合计：</td>
          <td class="text-right">{{s.sum.text}} 分</td>
          <td></td>
        </tr>
      </ng-template>
    </st>
`

![{AE980CBB-61D9-4BD3-AA68-D0D7EAA304DD}_20191116180056](https://user-images.githubusercontent.com/25293740/68991568-0f6d5d00-089b-11ea-8f42-bec8df966bfa.jpg)

**Comment by cipchk** [comment]
关闭长时间未提供重现示例。
