### ISSUE TITLE
动态表单 - 页面滚动锚点定位错误

### ISSUE THREAD

**Issue by clyy** [ng-alain/ng-alain#1403]
GitHub 演示实例：https://ng-alain.github.io/

问题：
   点击“搜索”或“重置”按钮后，页面滚动锚点定位错误

重现链接：[https://ng-alain.github.io/ng-alain/#/delon/form](https://ng-alain.github.io/ng-alain/#/delon/form) 
![图片](https://user-images.githubusercontent.com/9590407/69003006-a4bd2f80-0935-11ea-8bcd-1661192389bf.png)

重现步骤：
1、点击“搜索”或“重置”按钮

代码调整试验
CASE-1：
1、调整字段“调用次数”字段宽度；
2、点击“搜索”或“重置”按钮。
结论：锚点定位正确
CASE-2：
1、调整表头任意字段名宽度，让其多行显示；
2、点击“搜索”或“重置”按钮。
结论：锚点定位错误

**Comment by chf007** [comment]
这种效果能否去掉？

**Comment by cipchk** [comment]
这是 `st` 的功能，可以利用 [STPage.toTop](https://ng-alain.com/components/table/zh#STPage) 来关闭，或使用 `toTopOffset` 调整偏移值。
