### ISSUE TITLE
抽屉和Lock页面

### ISSUE THREAD

**Issue by angelxg** [ng-alain/ng-alain#1404]
我现在系统的编辑页面都使用了抽屉Drawer 方式展示
然后超时后 跳转至 （DEMO页面的）/passport/lock 页面 
但URL跳转后 因为抽屉一直在最顶层，无法看到Lock页面
我的思路是吧抽屉放到一个全局变量里， Lock时先关闭抽屉 
不知道是否还有其他思路。

另外，调用Lock时 我想把Token清空（tokenService.clear();）。 解锁时走登录流程
因为用户名是从SettingsService自动带出  清空Token后 也清空了
是不是我也需要单独弄个保存用户名 的地方
谢谢

**Comment by cipchk** [comment]
1、目前 DrawerService 并不支持关闭所有的方法，参考 [#2965](https://github.com/NG-ZORRO/ng-zorro-antd/issues/2965)，我会考虑在 `DrawerHelper` 中增加类似功能。

2、我会增加只清除 `token` 的方法，临时解决方式也可以先 `get` 去除 `token`，然后再 `set`。
