### ISSUE TITLE
nz-table th nzWidth

### ISSUE THREAD

**Issue by l-hwen** [ng-alain/ng-alain#1407]
当我的数据很长时，我在表格中设置了列宽度，但是设置的宽度不起作用，在表格中数据仍然会撑开列。
<nz-table #basicTable [nzData]="listOfData" style="width:100%">
      <thead>
        <tr>
          <th nzWidth="30%">Name</th>
          <th>Age</th>
          <th>Address</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let data of basicTable.data">
          <td>qweeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeewqeqqqqqqqqqqqqqqqqqqqqq</td>
          <td>{{ data.age }}</td>
          <td>{{ data.address }}</td>
          <td>
            <a>Action 一 {{ data.name }}</a>
            <nz-divider nzType="vertical"></nz-divider>
            <a>Delete</a>
          </td>
        </tr>
      </tbody>
    </nz-table>

**Comment by cipchk** [comment]
使用 [widthMode](https://ng-alain.com/components/table/zh#STWidthMode) 来改变截短或强制换行。
