### ISSUE TITLE
delon的组件有没有计划和react pro版本的样式同步？

### ISSUE THREAD

**Issue by CK110** [ng-alain/ng-alain#1408]
- 和`ng-zorro`一样，delon中的组件把样式与组件内联，做成可以单独使用具体组件。
- 现在的模式感觉很重，必须和ng-alian搭配使用

**Comment by cipchk** [comment]
对于 @delon 所有组件都可以只单独引用相应组件的CSS，而非整个的。

**Comment by CK110** [comment]
比如 我只是单独的想使用`@delon/chart`，但是还必须安装`@delon/theme`。为什么不做成`@delon/chart`包里面就有他需要的样式，`@delon/theme`的样式可以单独找出`chart`中某个组件的样式吗？

**Comment by cipchk** [comment]
以后不再对这方面的优化，@delon/* 只专注于 ng-alain 脚手架的支持。
