### ISSUE TITLE
Date format doesn't work as expected

### ISSUE THREAD

**Issue by NanFengCheong** [ng-alain/ng-alain#1409]
- ng-alain version: 8.6.0
- Angular version: 8.2.14
## 【必填项】重现链接，Reproduction link

https://stackblitz.com/edit/angular-yzydgr?file=src/app/app.component.ts
```
schema: SFSchema = {
    properties: {
      date1: {
        type: 'string',
        format: 'YYYY-MM-DD',
        ui: { widget: 'date' } as SFDateWidgetSchema,
      },
      date2: {
        type: 'string',
        format: 'date',
      },     
    },
  };
```
![image](https://user-images.githubusercontent.com/7321833/69595466-90b2b580-103a-11ea-955e-418b9707f7bb.png)

## 重现步骤，Steps to reproduce
1. Select date in both date picker and submit

**Comment by cipchk** [comment]
You using a invalid `format` value, you can try `date` or `time`, pls refer to https://ng-alain.com/form/date/en#Notice

**Comment by NanFengCheong** [comment]
Ya. I know. But I having some timezone issue causing the date to be incorrect with the date format.

**Comment by cipchk** [comment]
Abort return the specified format via `ui.format`.
