### ISSUE TITLE
建议se、sv、sg支持跨列功能，目前不规则布局不能支持占2/3宽度

### ISSUE THREAD

**Issue by MagicWang** [ng-alain/ng-alain#1410]
建议给se、sv、sg添加colspan属性，支持跨列，如下所示
<form nz-form #f="ngForm" se-container="2">
  <se label="App Key" col="3" colspan="2">
    <input type="text" nz-input [(ngModel)]="i.ak" name="ak" required>
  </se>
</form>

**Comment by MagicWang** [comment]
<form nz-form #f="ngForm" se-container="2">
  <se label="App Key" col="3" colspan="2">
    <input type="text" nz-input [(ngModel)]="i.ak" name="ak" required>
  </se>
</form>

**Comment by MagicWang** [comment]
`<form nz-form #f="ngForm" se-container="2">
  <se label="App Key" col="3" colspan="2">
    <input type="text" nz-input [(ngModel)]="i.ak" name="ak" required>
  </se>
</form>`

**Comment by MagicWang** [comment]
`  <se label="App Key" col="3" colspan="2">
    <input type="text" nz-input [(ngModel)]="i.ak" name="ak" required>
  </se>`

**Comment by cipchk** [comment]
抱歉，我不是很明白这类需求，麻烦提供一个示例，以及期望的效果是什么。

**Comment by MagicWang** [comment]
![image](https://user-images.githubusercontent.com/3860039/69803084-0e7ee880-1216-11ea-9271-ded8eaa8887d.png)
我想要用se实现这种布局，第三行的第一列占据2/3

**Comment by cipchk** [comment]
你可以指定一个空字符串 label 值来满足这类情况。

**Comment by MagicWang** [comment]
理解有误，分类这个字段是自己封装的级联选择框，需要占用2/3的空间，不是三个字段

**Comment by snowchenlei** [comment]
@MagicWang see https://github.com/ng-alain/ng-alain/issues/2245

**Comment by xingkoo** [comment]
我也存在同样的需求，目前只能使用更多的宽度来体现这个需求，但不是很雅观。
空白的label目前并未完全隐藏，而是会出现一个很小的区域。至少垂直布局时，空label会导致出现一个几像素高的空白区域。

已看到#2245已经增强了这个功能。只能等待v14了。
