### ISSUE TITLE
ST 数据展示时对 防范跨站脚本(XSS) 内容的过滤

### ISSUE THREAD

**Issue by crazywen** [ng-alain/ng-alain#1412]
ST 数据展示时对 防范跨站脚本(XSS) 内容的过滤

类似：https://9q5tmn.run.stackblitz.io
![image](https://user-images.githubusercontent.com/3174264/69805176-1b520b00-121b-11ea-8ea7-2cb656c32dbb.png)

建议可以做到基于Angular 的 无害化处理
https://angular.cn/guide/security

**Comment by cipchk** [comment]
ducplated of #1419

**Comment by crazywen** [comment]
good job!
