### ISSUE TITLE
how can i update the sidebar menu's badge nubmer?

### ISSUE THREAD

**Issue by wzfjesun** [ng-alain/ng-alain#1418]
after init the siderbar menu，i want to update the siderbar menu badge on some condition.
how can i update the sidebar menu's badge nubmer?

![111](https://user-images.githubusercontent.com/6768736/69915990-4a24e700-1490-11ea-96cb-25b0dd3a0da9.png)

**Comment by cipchk** [comment]
Sorry, can be reset at the moment via `MenuService.add`.
