### ISSUE TITLE
st表格固定列之间出现空隙

### ISSUE THREAD

**Issue by snys98** [ng-alain/ng-alain#1421]
- ng-alain version: 8.6.0
- Angular version: 8.2.14
如图:
![9K`LQT))SFS ~V4OI}%L5PP](https://user-images.githubusercontent.com/11873100/70025402-ee657580-15d7-11ea-998e-e277392ad8de.png)

固定列之间存在非常大的间隙

## 【必填项】重现链接，Reproduction link
https://ng-alain.com/components/table/zh#components-table-fixed
https://stackblitz.com/edit/angular-wwnqpt?file=src/app/app.component.ts

## 重现步骤，Steps to reproduce
稳定重现, 可以参考文档:

**Comment by cipchk** [comment]
之前的 https://github.com/ng-alain/ng-alain/issues/1359 引起的，我已经回退，这两天会发布新版本。

**Comment by snys98** [comment]
hi, 建议在新版本发布之前保留open的状态, 发布之后再行close...
顺便在[这里](https://github.com/ng-alain/ng-alain/issues/1359#issuecomment-543210726)提到的workaround

> 可以设置 width: '100%' 来解决，未设置 width 会被认为空，这导致会被忽略渲染。

是指在css中指定宽度么?我这里测试还是不OK
![temp](https://user-images.githubusercontent.com/11873100/70399815-26e6d280-1a62-11ea-88ca-f76f14ef00aa.gif)

**Comment by cipchk** [comment]
@snys98 能否提供相应的重现示例，我不确定你是否是因为 #1359 的关系所引起的，我想这是两个不同的 issues，如果可能建议重开一个 issuess，以便我更好的追踪和维护。

**Comment by snys98** [comment]
@cipchk 抱歉, 前段时间特别忙, 没有关注这个问题...重现的示例我已经在issue中补充到了的

>【必填项】重现链接，Reproduction link
https://ng-alain.com/components/table/zh#components-table-fixed
https://stackblitz.com/edit/angular-wwnqpt?file=src/app/app.component.ts

第一个链接是你们的官方文档, 不过这次再点开的时候这个bug已经无法复现了, 固定列的示例代码被禁用了滚动:cry:

第二个链接我测试了一下还是可以复现之前的问题的, 你可以用这个示例的demo来复现bug

**Comment by snys98** [comment]
补充, 更新8.7.3之后这个问题解决了
