### ISSUE TITLE
ModalHelper可否返回引用对象?

### ISSUE THREAD

**Issue by xingkoo** [ng-alain/ng-alain#1422]
可能我没有看太明白.如果已有此功能希望能够帮忙说明一下如何使用.
> 组件A通过Modal弹出组件B.
> 组件B经用户录入后,将表单值返回组件A
> 组件A获取到组件B的数据,处理成功后将组件B关闭.

已知问题如下:
一, 是否有方法可以解决组件B向组件A传值而不关闭组件B.
> 组件B是一个封装的动态表单.对于表单值,在不同的场景下,处理方式不一样,所以才会需要将B传回A,以解决不同的数据处理逻辑.
> 目前通过订阅服务来将B数据传给A

二, ModalHelper 是否有返回NzModalRef?
> `ng-zorro`里面的`NzModalService`返回了`NzModalRef`,可以在发起Create的组件中通过引用关闭当前对话框
> ModalHelper 返回的似乎是一个订阅,目前的解决方案中,我并不知道如何能够在组件A中关闭组件B

**Comment by cipchk** [comment]
`NzModalService.openModals` 可以获取已经打开的所有模态，我会在 `ModalHelper` 增加一个快捷属性。

**Comment by xingkoo** [comment]
辛苦卡总.
还没有细看openModals的代码,不知道是不是可以通过某个标识来获取不同的modal. 
后续我会仔细阅读一下.希望增加快捷属性时可以考滤直接获取到指定的modal.

另外,有没有办法可以实现,子组件向父组件传递事件,类似 `(click)="click($event)"` 这样的方法.而非第三方的事件服务来传递?

我的理解是, ModalService 是通过服务来打开新的模态框的,  可以返回 `子组件引用`,或者通过  ````@ViewChild()```` 来获取子组件,关对期操作.

那么在子组件中,操作父组件, 应该就不可以通过 ````this.Injector.get(AbcComponent))````来获取父对象了

**Comment by cipchk** [comment]
`NzModalRef` 在未注入时，是无法获取到实例的，换言之在打开触发之前无法获得该实例，但是打开之后如果依然需要对父组件进行操作，可以将父组件的当前实例值使用传参的形式传递即可，此时可以利用这个实例来对父组件进行操作。

`ModelHelper` 无法对这一行为做干涉，因此关掉此 issues.
