### ISSUE TITLE
st 有没有可能支持nz table里面的树形表格？

### ISSUE THREAD

**Issue by coolyujiyu** [ng-alain/ng-alain#1423]
原生的nztable是可以用，但是实在是不太友好呐，有没有可能像vue版的一样，传入children，自动生成树形结构？
https://www.antdv.com/components/table-cn/#components-table-demo-tree-data

大佬能不能在9.0给实现一把，哈哈

**Comment by cipchk** [comment]
在努力中，但是对于 jsx 与 angular template 本质上的区别，实现这类非常麻烦，请统一跟踪：#1143
