### ISSUE TITLE
侧边栏选中元素，url跳转后侧边栏始终滚动到最上方

### ISSUE THREAD

**Issue by allenlongbaobao** [ng-alain/ng-alain#1425]
🚨 Issues 是用于BUG、Feature、进度追踪 🚨
🚨 The issue tracker is not for questions 🚨

如果有任何问题，可在以下方式获得答案：

- https://ng-alain.com/
- QQ Group：316911865
- https://segmentfault.com/t/ng-alain

**Comment by cipchk** [comment]
https://github.com/ng-alain/ng-alain/blob/master/src/app/routes/routes-routing.module.ts#L91
