### ISSUE TITLE
Support to href with routerLink on sidebar-nav

### ISSUE THREAD

**Issue by segux** [ng-alain/ng-alain#1427]
Actually, you're using (click) event for <a> child on sidebar-nav to navigate router links, this affects to original `a` native browser behaviour of the element. 

If you try to use mousewheel click, you can't open link into a new tab.

I offer two options:

1. Pass throught (click) MouseEvent with $event on template.
This option should be the easiest of the two, because you only need to compare event type and if click was do with mousewheel, should do open in a new tab.
This option is no longer using native functionality such as accessibility support and other features such as the keyboard
2. Try to use routerLink as much as possible.
As far as I know routerLink, I think it allows to pass full links as a value and it will treat them correctly in the href, keeping the anchor's native support

**Comment by cipchk** [comment]
I will optimize this, And don't support external links for `routerLink` [#24567](https://github.com/angular/angular/issues/24567).

**Comment by segux** [comment]
Oh, sorry then about second solution, probably i thought that was implemented because i read that more than a year ago. 

Ill try to understand where can be improved. If i find some solution ill make a PR

**Comment by cipchk** [comment]
Use [externalLink](https://github.com/ng-alain/delon/blob/master/packages/theme/src/services/menu/interface.ts#L31-L33) and target to achieve in `MenuService`.
