### ISSUE TITLE
怎么配置点击二级菜单，其他一级菜单下的二级菜单不自动关闭，我给<sidebar-nav></sidebar-nav>配置[openStrictly]="true"也不行

### ISSUE THREAD

**Issue by 154192** [ng-alain/ng-alain#1428]

**Comment by cipchk** [comment]
```html
<sidebar-nav class="d-block py-lg" openStrictly></sidebar-nav>
```

增加 `openStrictly` 会不受控，相应动画：

![demo](https://user-images.githubusercontent.com/2987467/70496326-2d507980-1b4a-11ea-9470-85b4c12fe6c5.gif)

**Comment by 154192** [comment]
点击二级菜单跳转，其他一级菜单会关闭，其他一级菜单下面的二级菜单就看不到了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "卡色"<notifications@github.com&gt;; 
发送时间: 2019年12月10日(星期二) 中午12:40
收件人: "ng-alain/ng-alain"<ng-alain@noreply.github.com&gt;; 
抄送: "秋枫落叶"<1541927227@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [ng-alain/ng-alain] 怎么配置点击二级菜单，其他一级菜单下的二级菜单不自动关闭，我给<sidebar-nav&gt;</sidebar-nav&gt;配置[openStrictly]=&quot;true&quot;也不行 (#1428)



<sidebar-nav class="d-block py-lg" openStrictly&gt;</sidebar-nav&gt;
 
增加 openStrictly 会不受控，相应动画：
