### ISSUE TITLE
按照官方文档操作启动报错SyntaxError: Inline JavaScript is not enabled. Is it set in your options?

### ISSUE THREAD

**Issue by zpsw** [ng-alain/ng-alain#1429]
本人前端新手

版本都是最新的 
按照官网命令
`ng new my-project --style less`
`cd my-project`
`ng add ng-alain`
`npm start`

出现错误
`cmd.exe /D /C call C:\Ver\Nodejs\kit\node_global\lessc.cmd alain-default.less alain-default.css --source-map`
`SyntaxError: Inline JavaScript is not enabled. Is it set in your options? in C:\Ver\Nodejs\app\sweet-admin\src\assets\alain-default.less on line 113, column 1:`
`112 // https://github.com/ant-design/ant-motion/issues/44`
`113 .bezierEasingMixin();`
`114 `

**Comment by cipchk** [comment]
这是 less 的错误，但是生成 `scripts/color-less.js` 依赖的是 [antd-theme-generator](https://github.com/mzohaibqc/antd-theme-generator/blob/master/index.js#L154) 已经开启了支持 JavaScript 选项，我想会不会是因为你全局安装了 less 然后导致的呢？试着给 `package.json` 增加： 

```
"less": "^3.9.0"
```

并重新 `yarn` 试试（最新先删除 `node_modules` 文件夹）。

**Comment by zpsw** [comment]
> 这是 less 的错误，但是生成 `scripts/color-less.js` 依赖的是 [antd-theme-generator](https://github.com/mzohaibqc/antd-theme-generator/blob/master/index.js#L154) 已经开启了支持 JavaScript 选项，我想会不会是因为你全局安装了 less 然后导致的呢？试着给 `package.json` 增加：
> 
> ```
> "less": "^3.9.0"
> ```
> 
> 并重新 `yarn` 试试（最新先删除 `node_modules` 文件夹）。

谢谢，我删掉了node_modules和全局的less，重新yarn就好了
