### ISSUE TITLE
ST组件在屏屏模式下,应取消横向滚动条功能.

### ISSUE THREAD

**Issue by xingkoo** [ng-alain/ng-alain#1432]
- ng-alain version: X.Y.Z
- Angular version: X.Y.Z

## 【必填项】重现链接，Reproduction link

对表格使用横向滚动,主要是考滤到列数过多,一屏显示不完整,但是在小屏模式下,表格会竖排显示,此时横向滚动没有大用,建议考滤在竖排显示时取消横向滚动条,或者设置一个开关.

**Comment by cipchk** [comment]
你可以关闭 `responsive` 响应式。
