### ISSUE TITLE
'st'组件 loading 相关问题

### ISSUE THREAD

**Issue by betgo** [ng-alain/ng-alain#1437]
st.loading = false 无法关闭 加载动画

![image](https://user-images.githubusercontent.com/23697638/70693071-a50fd700-1cf7-11ea-8831-2d7d14a5e876.png)

![image](https://user-images.githubusercontent.com/23697638/70692964-7265de80-1cf7-11ea-9ad2-cd5b056791ff.png)

st.loading = null 才会消失,不知道是不是bug

**Comment by cipchk** [comment]
`st` 是一个 `OnPush` 的更新策略，当利用组件实例对象来改变是不会立即渲染，可以在设置 `loading` 后再调用 `st.cd()` 来渲染。
