### ISSUE TITLE
路由复用插件，是否能够配置固定且不可关闭的路由呢？

### ISSUE THREAD

**Issue by coolyujiyu** [ng-alain/ng-alain#1439]
比如图片里面的首页，常驻第一，且不可关闭，很多管理系统都有这个需求

![TIM图片20191213170728](https://user-images.githubusercontent.com/18638322/70788085-12406c80-1dcb-11ea-9d8a-8786cc982ea4.jpg)

能不能reuse-tab提供API能够添加固定的tabs

**Comment by cipchk** [comment]
设置菜单为 `reuseClosable: false` （或路由 `data: { reuseClosable: false }`）表示不允许关闭。

**Comment by coolyujiyu** [comment]
是的，但是不是固定在第一个位置了，并且不能登录以后，自动出现
