### ISSUE TITLE
st中STColumn的type为img时，可否提供一个文件服务器根地址的可选字段？

### ISSUE THREAD

**Issue by selegiline** [ng-alain/ng-alain#1440]
例如，columns: STColumn[] = [
    {
      index: 'avatar',
      title: '头像',
      type: 'img',
      rootApi:'http://123.123.123.123/files/'
    }
]。很多的后端数据表，图片和文件存的都不是绝对地址。

**Comment by xingkoo** [comment]
自行封装个管道来做处理吧.

**Comment by cipchk** [comment]
@selegiline 利用 `format` 来自定义渲染url。
