### ISSUE TITLE
在路径为 https://ng-alain.com/docs/mock/zh ，页面拉到最顶部时，左侧导航栏的下半部分显示异常

### ISSUE THREAD

**Issue by yangguang0104** [ng-alain/ng-alain#1441]
在路径为 https://ng-alain.com/docs/mock/zh ，页面拉到最顶部时，左侧导航栏的下半部分显示异常

**Comment by cipchk** [comment]
@yangguang0104 请  https://ng-alain.com/docs/mock/zh 是从哪来的？

**Comment by yangguang0104** [comment]
在ng-alain 官网 点击文档&nbsp; 在左侧导航，选开发--&gt;h和服务端进行交互--&gt;Mock --&gt;有关更多 Mock 语法和使用方式参考"这里"。点击“这里”页面会跳转到&nbsp;https://ng-alain.com/docs/mock/zh&nbsp; ，这时在右侧将页面拉倒最顶部，左边导航栏的下半部分不显示，






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"卡色"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月14日(星期六) 下午3:26
收件人:&nbsp;"ng-alain/ng-alain"<ng-alain@noreply.github.com&gt;;
抄送:&nbsp;"似水流年"<283623163@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [ng-alain/ng-alain] 在路径为 https://ng-alain.com/docs/mock/zh ，页面拉到最顶部时，左侧导航栏的下半部分显示异常 (#1441)




@yangguang0104 请  https://ng-alain.com/docs/mock/zh 是从哪来的？
  
- 
您收到此邮件是因为有人提到您。
直接回复此电子邮件，在GitHub上查看，或取消订阅。
