### ISSUE TITLE
7升级到8后导致st报错

### ISSUE THREAD

**Issue by AdaVih** [ng-alain/ng-alain#1442]
前提：
- 根据官网文档上升级完成，并将版本改为8.7.1
- ng-zorro也升级到8.5.2

问题描述：
使用nz-tabel没有问题，但是使用st就会报错，报错内容如下。

报错：
1. 无法加载路由
2. core.js:6014 ERROR Error: Uncaught (in promise): NullInjectorError: StaticInjectorError(AppModule)[ModalHelper -> NzModalService]: 
  StaticInjectorError(Platform: core)[ModalHelper -> NzModalService]: 
    NullInjectorError: No provider for NzModalService!
NullInjectorError: StaticInjectorError(AppModule)[ModalHelper -> NzModalService]: 
  StaticInjectorError(Platform: core)[ModalHelper -> NzModalService]: 
    NullInjectorError: No provider for NzModalService!
![image](https://user-images.githubusercontent.com/35645884/70877391-359c2f00-1ff8-11ea-8afa-b5a81692322e.png)

**Comment by cipchk** [comment]
移除 `node_modules` 重新安装依赖包即可。

**Comment by AdaVih** [comment]
移除后重新下载依旧报错

**Comment by cipchk** [comment]
认真检查一下是否缺少模块的导入，目前收集到的这个异常所引起的无非就是这两种情况。

**Comment by AdaVih** [comment]
对应了一下现在版本的代码，并没有觉得少了什么模块的导入

**Comment by gmf520** [comment]
@AdaVih 解决了没有，我也遇到这个问题，8.3.0没问题，升到8.4就遇到

**Comment by gmf520** [comment]
解决了，删除node_modules和package-lock.json重新安装即可
