### ISSUE TITLE
主菜单提示xss信息

### ISSUE THREAD

**Issue by xingkoo** [ng-alain/ng-alain#1443]
- ng-alain version: X.Y.Z
- Angular version: X.Y.Z

## 【必填项】重现链接，Reproduction link

![WX20191216-151443](https://user-images.githubusercontent.com/2936579/70886607-d00b6b00-2016-11ea-8536-498ab411e3fb.png)

## 重现步骤，Steps to reproduce
如图所示

**Comment by cipchk** [comment]
更新至最新版本 `8.7.2`
