### ISSUE TITLE
sf的array部件布局问题

### ISSUE THREAD

**Issue by kapr1k0rn** [ng-alain/ng-alain#1445]
例如：
`const schema = {
  list: {
    type: 'array',
    items: {
      a: { type: 'string' },
      b: { type: 'number' }
    }
  }
};`
目前a和b是纵向布局，而每个item则是水平布局，有办法实现让a和b水平布局，而每个item纵向布局吗？

**Comment by cipchk** [comment]
抱歉，不支持，但是你可以重新定义 [Array](https://github.com/ng-alain/delon/blob/master/packages/form/src/widgets/array/array.widget.ts) 小部件。
