### ISSUE TITLE
导出excel 怎么实现添加样式

### ISSUE THREAD

**Issue by tang-butian** [ng-alain/ng-alain#1446]
我按照文档上，在 callback 里给 wb 按照  js-xlsx 的格式添加了样式，但是导出后还是没有样式；
SheetJS 样式支持又是收费的

![image](https://user-images.githubusercontent.com/27254047/71052498-74f88600-2186-11ea-8fb3-7ccca5b2643a.png)

**Comment by cipchk** [comment]
请自行阅读 js-xlsx 文档：https://github.com/protobi/js-xlsx#cell-object
