### ISSUE TITLE
g2-pie 饼状图数据动态绑定不渲染页面问题

### ISSUE THREAD

**Issue by iloveyins** [ng-alain/ng-alain#1451]
![image](https://user-images.githubusercontent.com/18527569/71242866-dd439500-2349-11ea-94e1-2cf3680ea838.png)

**Comment by iloveyins** [comment]
![image](https://user-images.githubusercontent.com/18527569/71242906-f9dfcd00-2349-11ea-82c5-b82e9d8567a2.png)

**Comment by cipchk** [comment]
`userData` !== `visitData`

**Comment by iloveyins** [comment]
![image](https://user-images.githubusercontent.com/18527569/71242968-2267c700-234a-11ea-8fc0-92a30e7f0587.png)

**Comment by iloveyins** [comment]
每一次 需要手动触发页面上任意一个按钮   数据才渲染出来

**Comment by cipchk** [comment]
A valid [demo](https://stackblitz.com/edit/angular-aqurgq?file=src/app/app.component.ts)

**Comment by iloveyins** [comment]
![image](https://user-images.githubusercontent.com/18527569/71245462-b2f4d600-234f-11ea-8ff5-74103919d695.png)

**Comment by iloveyins** [comment]
一旦放到这个异步方法中就不能自动渲染，  直接放到ngOnInit()是可以的

**Comment by iloveyins** [comment]
![image](https://user-images.githubusercontent.com/18527569/71247059-f0a72e00-2352-11ea-9438-c52459e18229.png)
![image](https://user-images.githubusercontent.com/18527569/71247079-fbfa5980-2352-11ea-8de4-b891eb5ea91c.png)
放到这个里面  也是不行的

**Comment by cipchk** [comment]
麻烦提供一个重现示例，我提供的示例中并不会有这类情况。 @iloveyins
