### ISSUE TITLE
多级 Module 下生成 list 业务页失败

### ISSUE THREAD

**Issue by clyy** [ng-alain/ng-alain#1455]
**多级 Module 结构下，应该如何生成业务页？**

**1. 通过命令：ng g ng-alain:module api 和 ng g ng-alain:module /api/project -m=api 得到目录结构**

![图片](https://user-images.githubusercontent.com/9590407/71364625-bac6ab80-25d7-11ea-9db4-d42336e316ae.png)

**2. 生成 list 页面：ng g ng-alain:list list -m=project， 生成失败**
> Specified module 'project' does not exist.
Looked in the following directories:

    /src/app/routes/project/project
    /src/app/routes/project/list
    /src/app/routes/project
    /src/app/routes
    /src/app
    /src

**3. 尝试：ng g ng-alain:list list -m=api/project，生成失败**
> Selector (app-api/project-list) is invalid.

**Comment by 1zilc** [comment]
你可以cd到你的 routes/api 目录下 执行 `ng g ng-alain:list list -m=project`

**Comment by 1zilc** [comment]
你可以cd到你的routes/api目录,执行 `ng g ng-alain:list list -m=project`

**Comment by clyy** [comment]
谢谢！cd 跳转目录后，问题得到解决。
