### ISSUE TITLE
ng-alain:tpl创建模板时不能传入一些未定义参数

### ISSUE THREAD

**Issue by shawnkuku** [ng-alain/ng-alain#1466]
- ng-alain version: 8.6.0
- Angular version: ~8.2.14

## 【必填项】重现链接，
![QQ截图20191230155319](https://user-images.githubusercontent.com/32611489/71572978-96f5ef00-2b1c-11ea-8a0f-c5a734bc3a8d.png)

## 重现步骤，Steps to reproduce
![QQ截图20191230155319](https://user-images.githubusercontent.com/32611489/71572978-96f5ef00-2b1c-11ea-8a0f-c5a734bc3a8d.png)

**Comment by cipchk** [comment]
这是 Angular cli 的一次变更导致的，暂时只能希望 `ng g` 允许未可知选项了 https://github.com/angular/angular-cli/issues/16510
