### ISSUE TITLE
sf 表单中自定义得小部件 怎么把下面得按钮button隐藏掉，如何设置呢  

### ISSUE THREAD

**Issue by lengmoukong** [ng-alain/ng-alain#1467]
🚨 Issues 是用于BUG、Feature、进度追踪 🚨
🚨 The issue tracker is not for questions 🚨

如果有任何问题，可在以下方式获得答案：
schema: SFSchema = {
    properties: {
      remark: {
        type: 'string',
        title: '',
        ui: {
          widget: 'ueditor',
          spanLabel:0,
          spanControl:24
        }
      }
    }
  };
- https://ng-alain.com/
- QQ Group：316911865
- https://segmentfault.com/t/ng-alain

**Comment by cipchk** [comment]
https://ng-alain.com/form/getting-started#Button

**Comment by lengmoukong** [comment]
> https://ng-alain.com/form/getting-started#Button

谢谢
