### ISSUE TITLE
reuse-tab 来回闪烁切换无法停止

### ISSUE THREAD

**Issue by rieonke** [ng-alain/ng-alain#147]
在原始的demo中，来回点击多个页面之后，在reuse tab里面形成了多个标签，这时导致多个标签之间来回闪烁切换，
如下是视频截图，注意看地址栏的变化
![alain-err-rec](https://user-images.githubusercontent.com/15796994/34328186-d4f0209e-e912-11e7-9746-cec7beec2f5d.gif)

**Comment by cipchk** [comment]
是哪个版本呢？

**Comment by rieonke** [comment]
0.4.0-rc.6 这个版本

**Comment by cipchk** [comment]
请使用 `0.4.0`
