### ISSUE TITLE
各浏览器适配最低版本号

### ISSUE THREAD

**Issue by allenlongbaobao** [ng-alain/ng-alain#1470]
🚨 Issues 是用于BUG、Feature、进度追踪 🚨
🚨 The issue tracker is not for questions 🚨

你好，请问有该库支持的各浏览器最低版本号吗？

如果有任何问题，可在以下方式获得答案：

- https://ng-alain.com/
- QQ Group：316911865
- https://segmentfault.com/t/ng-alain

**Comment by cipchk** [comment]
https://ng.ant.design/docs/introduce/en#environment-support
