### ISSUE TITLE
表格列表的“type：‘date’时，default默认值不起作用”

### ISSUE THREAD

**Issue by hightwo499** [ng-alain/ng-alain#1471]
- ng-alain version: 8.7.3
- Angular version: 8.2.11

## 【必填项】重现链接，Reproduction link

![image](https://user-images.githubusercontent.com/51105345/71654572-5fca4c80-2d6d-11ea-9694-2c3e0d2456c5.png)
![image](https://user-images.githubusercontent.com/51105345/71654611-a029ca80-2d6d-11ea-8466-620a0bd31c42.png)

## 重现步骤，Steps to reproduce

![image](https://user-images.githubusercontent.com/51105345/71654572-5fca4c80-2d6d-11ea-9694-2c3e0d2456c5.png)
![image](https://user-images.githubusercontent.com/51105345/71654611-a029ca80-2d6d-11ea-8466-620a0bd31c42.png)

**Comment by hightwo499** [comment]
![image](https://user-images.githubusercontent.com/51105345/71759375-23baf700-2ee7-11ea-9325-7b8a21f88890.png)
页面的数据显示还是为无效日期

**Comment by cipchk** [comment]
还未发布，会在8.8.1。
