### ISSUE TITLE
数组为必填时先新增2个再删除其中一个，就直接可以提交了

### ISSUE THREAD

**Issue by gaomengyong** [ng-alain/ng-alain#1472]
- ng-alain version: 8.5.0
- Angular version: 8.2.12

## 重现步骤，
数组为必填时先新增2个再删除其中一个，就直接可以提交了

**Comment by cipchk** [comment]
@gaomengyong 麻烦提供一个示例并对进一步描述问题的结果和期望。

**Comment by mostermsater** [comment]
设置minItems为1应该就可以了;
{
...
items:{
...
},
minItems:1
}

**Comment by gaomengyong** [comment]
@cipchk [是必填失效的问题。先添加2个![image](https://user-images.githubusercontent.com/23302214/72399120-25ef4200-3780-11ea-99f5-dd99ae55846e.png)，
再删除其中一个，必填项没有填写但是可以提交
![image](https://user-images.githubusercontent.com/23302214/72399146-3a333f00-3780-11ea-83da-5de279d1dffb.png)
