### ISSUE TITLE
SFComponent调用refreshSchema方法后，DateWidget点击清楚按钮没有清除日期值

### ISSUE THREAD

**Issue by cyh19890727** [ng-alain/ng-alain#1474]

**Comment by cyh19890727** [comment]
<sf #sf mode="search" [schema]="searchSchema" [button]="null" [formData]="params">

        this.searchSchema.properties.factoryId.enum = Select2Option(res.data);
        this.params = this.sf.value;   --- 会导致DateWidget点击清除按钮没有清除日期值
        this.sf.refreshSchema();

**Comment by cipchk** [comment]
@cyh19890727 麻烦提供一个重现示例。

**Comment by cyh19890727** [comment]
https://stackblitz.com/edit/ng-alain-setup-wcedew?file=package.json   这个是用例，先选中一个Type下拉，里面触发refreshSchema操作，之后清除日期控件，点击提交，日期值还在

**Comment by cyh19890727** [comment]
> @cyh19890727 麻烦提供一个重现示例。

https://stackblitz.com/edit/ng-alain-setup-wcedew?file=package.json 这个是用例，先选中一个Type下拉，里面触发refreshSchema操作，之后清除日期控件，点击提交，日期值还在

**Comment by cyh19890727** [comment]
@cipchk  https://stackblitz.com/edit/ng-alain-setup-wcedew?file=package.json 这个是示例，先选中一个Type下拉，里面触发refreshSchema操作，之后清除日期控件，点击提交，日期值还在

**Comment by cipchk** [comment]
肯定会包含日期数据，你并未清除 `createTime` 数据，你可以尝试：

```ts
const copyValue = { ...this.sf.value };
delete copyValue.createTime;
this.params = copyValue;
```
