### ISSUE TITLE
reuse-tab限制最大数量为2时无法正常使用

### ISSUE THREAD

**Issue by yihango** [ng-alain/ng-alain#1475]
- ng-alain version: 8.7.3
- Angular version: 8.3.0

## 【必填项】重现链接，Reproduction link
[发布后的网址](https://alain.cyanstream.com)

修改代码如下:
![image](https://user-images.githubusercontent.com/26987099/71707774-4a195d80-2e27-11ea-86c2-79a8afb2646a.png)

## 重现步骤，Steps to reproduce
* 修改复用标签数量为2,然后进行常规操作,会出现第三个标签,表现不正常

**Comment by cipchk** [comment]
路由复用只会在路由离开后触发，因此当前路由不管是否需要复用都会被显示在标签上。限制为 `2` 很容易引起一种错觉。
