### ISSUE TITLE
路由带参数， 路由并不能被复用

### ISSUE THREAD

**Issue by succulen-plants** [ng-alain/ng-alain#1476]
- ng-alain version: 8.7.3
- Angular version: 8.3.1

## 重现步骤，Steps to reproduce
路由配置：
```{ path: 'document/:type', component: DocumentComponent }```
菜单1: document/1 
菜单2: document/2

点击菜单1， DocumentComponent 中的ngOnInit 中的console.log()显示，
点击菜单2， DocumentComponent 中的ngOnInit 中的console没有执行， 好像 DocumentComponent没有被再次加载。

**Comment by cipchk** [comment]
https://ng-alain.com/components/reuse-tab/zh#生命周期
