### ISSUE TITLE
建议ST的row,能根据指定的条件追加样式名

### ISSUE THREAD

**Issue by wlclass** [ng-alain/ng-alain#1477]
在某些情况下,可能会对有不同状态的行,进行特殊的样式处理.
如:
- 具有警告状态的数据需要整行醒目提醒
- 已经完成的某条数据增加删除线等.
建议:
- 在```STData```类型里增加一个属性```className``` , 
- 在```STRes```的```process```的方法里可以设置此属性,渲染的时候,为table的tr附加设置的class

**Comment by cipchk** [comment]
请使用 `rowClassName` 属性。
