### ISSUE TITLE
关于菜单的问题

### ISSUE THREAD

**Issue by ada-hou** [ng-alain/ng-alain#148]
一般的后台管理系统菜单都比较多，可以按照头部的tab去切换
例如：
![default](https://user-images.githubusercontent.com/18135689/34330433-8fdf00fc-e957-11e7-91a8-7ff86fe95bdb.png)
ng-alain是否支持此类菜单

**Comment by cipchk** [comment]
根据路由改变菜单这一点并不难；只需要维护好 `MenuService` 的数据即可。
