### ISSUE TITLE
缺少 save icon 

### ISSUE THREAD

**Issue by Loongle** [ng-alain/ng-alain#1480]
- ng-alain version: 8.8.0
- Angular version: 8.2.14

![image](https://user-images.githubusercontent.com/7290992/72031960-fb594100-32c8-11ea-891f-bd977450a149.png)

## 重现步骤，Steps to reproduce
代码如下：

 ```
 <button nz-button nzType="primary" (click)="save(infoSF.value,claim.getValue())" [disabled]="!infoSF.valid">
    <i nz-icon nzType="save"></i>新增
 ```

![image](https://user-images.githubusercontent.com/7290992/72032061-4bd09e80-32c9-11ea-80ed-affbb5f936c9.png)

![image](https://user-images.githubusercontent.com/7290992/72032057-44a99080-32c9-11ea-8ace-ca32c1653407.png)

**Comment by cipchk** [comment]
需要手动引用，有关 ng-zorro-antd 的[图标说明](https://ng.ant.design/components/icon/zh#svg-%E5%9B%BE%E6%A0%87)，当然也可以使用 ng-alain 的自动[生成命令](https://ng-alain.com/cli/plugin/zh#icon)。
