### ISSUE TITLE
this.sf.refreshSchema();只想刷新表单里的一个下拉框的数据源

### ISSUE THREAD

**Issue by jmeichen** [ng-alain/ng-alain#1482]
![1](https://user-images.githubusercontent.com/20793262/72034360-be447d00-32cf-11ea-9746-304855e5a11e.png)

页面上有三个下拉框，第二个下拉框的options是根据第一个框的选择结果决定。每次更改第一个下拉框后要重置一下第二个下拉框的options。

重置后再调用refreshSchema（）会导致页面上已经填写过的表单值丢失。
请问能单独刷新  refreshSchema（第二个下拉框）吗

this.http.get('/apps').subscribe((res: any) => {
    this.schema.properties.app.enum = res;
    this.sf.refreshSchema();
  });

**Comment by cipchk** [comment]
当然会丢失，因为 `refreshSchema()` 会刷新整个表单。

建议使用 `this.sf.getProperty` 来对某个属性的操作，例如：

```ts
const property = this.sf.getProperty('/status2')!;
property.schema!.enum = newEnums;
property.resetValue(defaultValue, false);
```
