### ISSUE TITLE
在谷歌浏览器环境,st.exprot方法导出excel, 时间类型的数据会多几十秒,其他浏览器正常(官网示例即可重现)

### ISSUE THREAD

**Issue by LzyGit** [ng-alain/ng-alain#1484]
### 问题描述
使用STComponent表格组件的[st.export()](https://ng-alain.com/components/table/zh#components-table-export)导出excel表格,在谷歌浏览器导出的表格,时间类型的数据会多出几十秒,其他浏览器不会.
### BUG重现
在自己的项目中遇到的bug,然后发现官网的API文档的示例中也可以重现问题.访问
[https://ng-alain.com/components/table/zh#components-table-export](https://ng-alain.com/components/table/zh#components-table-export),点击示例左侧的Export按钮,导出excel表格,发现导出的数据中,"注册时间"字段比页面显示的原始数据要多几十秒.
![微信图片_20200111165211](https://user-images.githubusercontent.com/35184156/72201911-568b5f00-3494-11ea-8a2d-5db25a5f669d.png)

备注: 因为页面显示的"注册时间"格式只显示分钟不显示秒数,且时间是调用new Date()动态生成的,所以为了确保可以看到效果,应该在当前时间的秒数在30-50范围时刷新页面,即可保证看到导出的数据比页面看到的数据多1分钟的现象; 实际bug原因和new Date()无关, 本人项目是从后台请求的数据也会出现这个BUG.

### 环境
谷歌浏览器版本:  79.0.3945.117 
官网ng版本以官网为准,本人项目是 "ng-alain": "7.2.0", "@delon/abc": "7.2.0",
 windows, 东八区
实测以下浏览器**没出现**这个bug: IE, Edge, 火狐

### 贴一下官网示例中的代码
```
import { Component, ViewChild } from '@angular/core';
import { STColumn, STComponent } from '@delon/abc';

@Component({
  selector: 'components-table-export',
  template: `
    <button nz-button (click)="st.export()">Export</button>
    <button nz-button (click)="st.export(true)">Export Filtered Data</button>
    <button nz-button (click)="st.export(data, { filename: 'via-data.xlsx', sheetname: 'user' })">Export via data</button>
    <st #st [data]="data" [columns]="columns" class="mt-sm"></st>
  `,
})
export class ComponentsTableExportComponent {
  @ViewChild('st', { static: false }) st: STComponent;
  data: any[] = Array(10000)
    .fill({})
    .map((_item: any, index: number) => {
      return {
        id: index + 1,
        picture: {
          thumbnail: `https://randomuser.me/api/portraits/thumb/women/${Math.min(index + 1, 30)}.jpg`,
        },
        email: `e${index + 1}@qq.com`,
        phone: `phone - ${index + 1}`,
        price: Math.ceil(Math.random() * 10000000) + 10000000,
        registered: new Date(),
      };
    });
  columns: STColumn[] = [
    { title: '编号', index: 'id' },
    {
      title: '头像',
      type: 'img',
      width: 60,
      index: 'picture.thumbnail',
      exported: false,
    },
    { title: '邮箱', index: 'email' },
    { title: '电话', index: 'phone' },
    {
      title: '数字',
      index: 'price',
      type: 'number',
      sort: {
        compare: (a, b) => a.price - b.price,
      },
    },
    { title: '货币', index: 'price', type: 'currency' },
    { title: '注册时间', type: 'date', index: 'registered' },
  ];
}
```

**Comment by cipchk** [comment]
应该是 https://github.com/SheetJS/sheetjs/issues/1470 引起的。

**Comment by LzyGit** [comment]
确实是sheetjs的bug,已临时解决,按下面的方法修改了sheetjs源码,
[https://github.com/SheetJS/sheetjs/issues/1212#issuecomment-428192053](https://github.com/SheetJS/sheetjs/issues/1212#issuecomment-428192053)

按下面的方法将修改后的sheetjs库导入到自己的ng项目
[https://github.com/ng-alain/ng-alain/issues/984#issuecomment-491505490](https://github.com/ng-alain/ng-alain/issues/984#issuecomment-491505490)
