### ISSUE TITLE
ReuseTabService.title / closable 设置不生效

### ISSUE THREAD

**Issue by benchem** [ng-alain/ng-alain#1491]
- ng-alain version: 8.8.0
- Angular version: 8.2.14

## 【必填项】重现链接，Reproduction link

![image](https://user-images.githubusercontent.com/15070595/72805566-2dd24900-3c8e-11ea-8ea1-a553c0e216bf.png)

## 重现步骤，Steps to reproduce
A-TAB /  B-TAB

打开 A-TAB，再打开 B-TAB，切换回去 A-TAB 修改 ReuseTabService.title 不能马上生效，需要再次切换到 B-TAB，这时 A-TAB 才刷新（包括 closable 属性）；

如果只打开 A-TAB 或者 TAB 打开后，没切换过其他 TAB 情况， title / closable 修改是马上能生效的

**Comment by cipchk** [comment]
长时间未提供重现，暂时关闭。
