### ISSUE TITLE
Is there a support for Angular Ivy ?

### ISSUE THREAD

**Issue by aymeekouakou** [ng-alain/ng-alain#1492]
- ng-alain version: 8.8.0
- Angular version: 8.2.14

##  Persistent error

> ERROR in There is no appropriate source code format in '~/node_modules/date-fns/distance_in_words_to_now' entry-point.

## Steps to reproduce

1.  `ng new my-project --enableIvy --style less`

2.  `ng add ng-alain`

3.  `npm start`

**Comment by cipchk** [comment]
Will be supported in `9.0`.
