### ISSUE TITLE
为什么angular版本有一个回退？

### ISSUE THREAD

**Issue by tzraeq** [ng-alain/ng-alain#15]
## Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Mention any other details that might be useful.

为什么angular版本有一个回退？注释中没看到具体的说明。另外，有很多beta版本没有出现在release中。请问您对发布版是怎样计划的？

**Comment by cipchk** [comment]
抱歉，因为有一个angular 4.4.1 有一个[Reactive form BUG](https://github.com/angular/angular/issues/19219)，倒置生产环境有问题；我打算今晚发布一个版本，但不小心把我本地最近变更的提交了。
