### ISSUE TITLE
simple-table checkbox problem

### ISSUE THREAD

**Issue by wgqjiayou** [ng-alain/ng-alain#150]
Using the simple-table (checkboxChange) function, if you just click the checkbox in the table without clicking the checkbox header, the output array is empty, how to get the correct array?

**Comment by changxinjie** [comment]
Below is my solution by using viewChild annotation and implement the AfterViewChecked interface, and it works well. 

![image](https://user-images.githubusercontent.com/9565184/34347579-7c366692-ea3f-11e7-9163-93990ba5bf6f.png)

**Comment by wgqjiayou** [comment]
The problem has been solved, thank you very much
