### ISSUE TITLE
undefined error of @delon/auth BaseInterceptor.injector

### ISSUE THREAD

**Issue by NeilQ** [ng-alain/ng-alain#1500]
Hello, 我在使用ng add ng-alain创建脚手架后，使用默认的SimpleInterceptor，提示BaseInterceptor没有注入Injector实例，代码定位在：
```
 intercept(req: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
    const options = { ...new DelonAuthConfig(), ...this.injector.get<DelonAuthConfig>(DelonAuthConfig, undefined) };
....
```
错误内容为：
```
core.js:5828 ERROR TypeError: Cannot read property 'get' of undefined
    at SimpleInterceptor.intercept (auth.js:728)
    at HttpInterceptorHandler.handle (http.js:1941)
    at MockInterceptor.intercept (mock.js:460)
```

然后我追溯SimpleInterceptor的源码，发现没有在constructor中注入Injector，[SimpleInterceptor](https://github.com/ng-alain/delon/blob/master/packages/auth/src/token/simple/simple.interceptor.ts)

于是我创建一个自定义的Interceptor为baseInterceptor注入Injector，就没有错误了，自定义Interceptor如下：
```
@Injectable()
export class MyInterceptor extends SimpleInterceptor {
  constructor(protected injector:Injector) {
    super(injector);
  }
}
```

请问是不是我漏了某了地方的配置？ 我发现其他人好像没有这个问题。

**Comment by NeilQ** [comment]
可能是angular-cli的bug [angular/angular#31337](https://github.com/angular/angular/issues/31337)

**Comment by olivewind** [comment]
少了 @injectable  装饰器 @NeilQ

**Comment by NeilQ** [comment]
> 少了 @Injectable 装饰器 @NeilQ

感谢提醒，做了个简单实验，确实是基类少装饰器的原因。

**Comment by cipchk** [comment]
fixed by https://github.com/ng-alain/delon/pull/780
