### ISSUE TITLE
na-alain 项目里可以做ssr服务器渲染吗

### ISSUE THREAD

**Issue by lengmoukong** [ng-alain/ng-alain#1502]
在项目
ng add @nguniversal/express-engine --clientProject my-project
npm run build:ssr
报了一下错误：
ERROR in C:\Users\12436\Documents\LiuZhaoPing\angular\ng-alain\my-project\_cli-tpl\test\__path__\__name@dasherize@if-flat__\__name@dasherize__.component.spec.ts
[tsl] ERROR in C:\Users\12436\Documents\LiuZhaoPing\angular\ng-alain\my-project\_cli-tpl\test\__path__\__name@dasherize@if-flat__\__name@dasherize__.component.spec.ts(2,12)
      TS1003: Identifier expected.

ERROR in C:\Users\12436\Documents\LiuZhaoPing\angular\ng-alain\my-project\_cli-tpl\test\__path__\__name@dasherize@if-flat__\__name@dasherize__.component.spec.ts
[tsl] ERROR in C:\Users\12436\Documents\LiuZhaoPing\angular\ng-alain\my-project\_cli-tpl\test\__path__\__name@dasherize@if-flat__\__name@dasherize__.component.spec.ts(2,13)
      TS1110: Type expected.

ERROR in C:\Users\12436\Documents\LiuZhaoPing\angular\ng-alain\my-project\_cli-tpl\test\__path__\__name@dasherize@if-flat__\__name@dasherize__.component.spec.ts
[tsl] ERROR in C:\Users\12436\Documents\LiuZhaoPing\angular\ng-alain\my-project\_cli-tpl\test\__path__\__name@dasherize@if-flat__\__name@dasherize__.component.spec.ts(2,31)
      TS1109: Expression expected.

ERROR in C:\Users\12436\Documents\LiuZhaoPing\angular\ng-alain\my-project\_cli-tpl\test\__path__\__name@dasherize@if-flat__\__name@dasherize__.component.spec.ts
[tsl] ERROR in C:\Users\12436\Documents\LiuZhaoPing\angular\ng-alain\my-project\_cli-tpl\test\__path__\__name@dasherize@if-flat__\__name@dasherize__.component.spec.ts(2,33)

**Comment by cipchk** [comment]
duplcated of #1339
