### ISSUE TITLE
sf, upload部件，对formData内容不能展示

### ISSUE THREAD

**Issue by limingyao-xx** [ng-alain/ng-alain#1503]
ng-alain version: 8.8.0

重现链接:
https://stackblitz.com/edit/ng-alain-setup-qygcpj

问题：
sf, upload部件，对formData内容不能展示。
如例子↑，formData中name有图片连接，但是不会被展示出来。

也就是说该sf创建的数据，再用sf展示，是看不到图片的。

**Comment by cipchk** [comment]
如果你想展示已经上传的文件列表，必须指定 `fileList` 属性。
