### ISSUE TITLE
页面在IE浏览器中打不开

### ISSUE THREAD

**Issue by hightwo499** [ng-alain/ng-alain#1506]
- ng-alain version: X.Y.Z
- Angular version: X.Y.Z

## 【必填项】重现链接，https://ng-alain.github.io/ng-alain/#/passport/login

![image](https://user-images.githubusercontent.com/51105345/74701203-fc26b080-5240-11ea-8cf0-08c9cd087b46.png)

## 重现步骤，Steps to reproduce

![image](https://user-images.githubusercontent.com/51105345/74701206-fd57dd80-5240-11ea-8992-f77fc1c97805.png)

**Comment by cipchk** [comment]
是的，demo 示例中并没有开启相应的 [polyfills.ts](https://github.com/ng-alain/ng-alain/blob/master/src/polyfills.ts) 来支持IE，你可以自行打开。

**Comment by hightwo499** [comment]
> 是的，demo 示例中并没有开启相应的 [polyfills.ts](https://github.com/ng-alain/ng-alain/blob/master/src/polyfills.ts) 来支持IE，你可以自行打开。

polyfill中引入的包都引入了，在ie中打开，还是一直在loading，没有报错信息

**Comment by hightwo499** [comment]
> 是的，demo 示例中并没有开启相应的 [polyfills.ts](https://github.com/ng-alain/ng-alain/blob/master/src/polyfills.ts) 来支持IE，你可以自行打开。

![image](https://user-images.githubusercontent.com/51105345/75127597-e27ee080-56fa-11ea-892b-a90ec993b938.png)

**Comment by cipchk** [comment]
duplcated of  https://github.com/ng-alain/ng-alain/issues/1517
