### ISSUE TITLE
升级 angular 9 过程中，升级 ng-alain (ng update ng-alain)时出错

### ISSUE THREAD

**Issue by xinjie-just** [ng-alain/ng-alain#1512]
在从 angular 8.2.14 升级 angular 9 过程中，执行 ng update ng-alain，欲将 ng-alain 8.8.0 升级到最新版 8.9.0 报错。
Migration failed: domhandler_1.DomHandler is not a constructor

**Comment by cipchk** [comment]
目前还不支持ng9，预计在 ng-zorro 正式发布 9 以后的一周左右才能发布，估计在3月中旬。

**Comment by John0King** [comment]
@cipchk ng-zorro 的 9.0 beta2 出来了
