### ISSUE TITLE
Migration failed: domhandler_1.DomHandler is not a constructor

### ISSUE THREAD

**Issue by kerwin-ly** [ng-alain/ng-alain#1515]
- ng-alain version: 8.9.0
- Angular version: 9.0.2

## 【必填项】重现链接，Reproduction link

<img width="1439" alt="ng-update" src="https://user-images.githubusercontent.com/23304298/75133330-50380600-5715-11ea-8b07-9e7c80754f03.png">
<img width="1439" alt="update-ngalain-error" src="https://user-images.githubusercontent.com/23304298/75133247-fe8f7b80-5714-11ea-89d7-f97e927dcfc4.png">

## 重现步骤，Steps to reproduce
使用cli工具从angular`v7.0.2`升级到`v9.0.2`。`ng update`之后根据依赖进行升级。执行`ng update ng-alain`后报错。`Migration failed: domhandler_1.DomHandler is not a constructor`

**Comment by cipchk** [comment]
目前还不支持ng9，预计在 ng-zorro 正式发布 9 以后的一周左右才能发布，估计在3月中旬。
