### ISSUE TITLE
项目中在polyfills.ts文件中引入相应的包之后，在ie浏览器中打不开，之后现在loading，没有报错信息

### ISSUE THREAD

**Issue by hightwo499** [ng-alain/ng-alain#1517]
- ng-alain version: X.Y.Z
- Angular version: X.Y.Z

## 【必填项】重现链接，Reproduction link
项目中在polyfills.ts文件中引入相应的包之后，在ie浏览器中打不开，之后现在loading，没有报错信息
![image](https://user-images.githubusercontent.com/51105345/75134709-10275200-571a-11ea-8dcd-e57caf712cb0.png)
![image](https://user-images.githubusercontent.com/51105345/75134761-36e58880-571a-11ea-8dbf-8740f029d9ff.png)

## 重现步骤，Steps to reproduce
![image](https://user-images.githubusercontent.com/51105345/75134766-3b11a600-571a-11ea-94e5-d2362ba6493e.png)

**Comment by hightwo499** [comment]
@cipchk 这个问题什么时候可以解决

**Comment by succulen-plants** [comment]
问题已经解决， 是angular8  本地开发环境 ng server  默认taget es2015 ， 应该改成 es5

**Comment by snowchenlei** [comment]
解决了吗？我新下载的项目在ie下还是一直loading
