### ISSUE TITLE
st表格自定义按钮组，触碰按钮出现的弹窗一般是在屏幕左上角，有时也出现在其他位置

### ISSUE THREAD

**Issue by chendeli123** [ng-alain/ng-alain#1519]
**需求**：当触碰st表格自定义的按钮组中的操作，会有一个弹窗出现在操作的上方或下方，**当前遇到的问题是**：应用了st表格的界面就会出现弹窗出现在屏幕左上方，也有出现在其他位置的，f12看css代码时发现有的弹窗触发时没有top；left等属性，有的触碰操作发生变化时会有，但出现的位置还是不对,当项目第一次启动不会出现这个问题，但是修改保存代码，项目刷新后就会出现

**Comment by chendeli123** [comment]
![GIF](https://user-images.githubusercontent.com/44792870/75408469-cd9b8a80-5950-11ea-964d-c2a58c4f01ba.gif)

**Comment by cipchk** [comment]
@chendeli123 请问生产环境会有这类情况吗？还是说你是在hmr的模式才会有这种情况发生？

**Comment by cipchk** [comment]
缺少重现步骤，关闭此 issues，如果有其他细节请重新打开或发布新的 issues。
