### ISSUE TITLE
_onReuseInit在当前路由的子组件中无法使用

### ISSUE THREAD

**Issue by happyfeet1996** [ng-alain/ng-alain#1520]
🚨 Issues 是用于BUG、Feature、进度追踪 🚨
🚨 The issue tracker is not for questions 🚨

如果有任何问题，可在以下方式获得答案：

- https://ng-alain.com/
- QQ Group：316911865
- https://segmentfault.com/t/ng-alain
我使用路由跳转一个item的component，在item中可以使用_onReuseInit()，item有个子组件叫summary，在summary中无法使用_onReuseInit()

**Comment by cipchk** [comment]
写了半还是放弃，很难做到如果没有这些组件对实例的绑定的话，单从外部进行递归所有子组件，除非去引用一些 CLI 生成的东西 `__ngContext__`，但这是极不安全的做法。
