### ISSUE TITLE
文本组件mobile类型的bug

### ISSUE THREAD

**Issue by chensixiang1** [ng-alain/ng-alain#1521]
- ng-alain version:8.5.0
- Angular version: 8.2.12

## 【必填项】重现链接，Reproduction link
https://ng-alain.com/form/string/zh
https://ng-alain.com/form-pages/validator/zh
## 重现步骤，Steps to reproduce
在没有必填项的情况下，文本mobile组件下formdata下的mobile类型字段为空，无法提交，校验失败。
例如：
schema=
{
  "properties": {
      "mobile": {"type": "string","format": "mobile", "title": "手机号"},
      "test":{"type": "string", "title": "文本"}
  }
}
--------------------------------
formdata={"mobile":""}
--------------------------------
无法提交。
希望修改一下！！！

**Comment by cipchk** [comment]
麻烦提供重现，我无法重现这种现象。

**Comment by cipchk** [comment]
长时间未提供重现，暂时关闭。
