### ISSUE TITLE
ST的resetColumns方法不刷新列表

### ISSUE THREAD

**Issue by gelinagg** [ng-alain/ng-alain#1522]
-ng-alain升级8后，ST的.resetColumns()这个方法不能用了，什么原因

  @ViewChild('st', { static: true }) st: STComponent;

  this.st.resetColumns();
之前版本7.2

**Comment by gelinagg** [comment]
columns: STColumn[] = [
    { title: '编号', index: 'no' },
    { title: '调用次数', type: 'number', index: 'callNo', iff: () => this.iii === 0 },
    { title: '头像', type: 'img', width: '50px', index: 'avatar' },
    { title: '时间', type: 'date', index: 'updatedAt' },
  ];

  constructor(private http: _HttpClient) { }
  test() {
    // tslint:disable-next-line: no-unused-expression
    this.iii++;
    console.log(this.iii)
    this.st.resetColumns();
  }

**Comment by succulen-plants** [comment]
@cipchk 
确实不能生效，我需要根据不同的数据， table 结构发生变化，  this.st.resetColumns(); 没有生效

**Comment by hightwo499** [comment]
这个刷新列表的问题，现在有解决方法吗？
