### ISSUE TITLE
reuseTab在打开标签后，在切换语言时，tab标题不会自动改变，需要手动切换tab后才会刷新标题

### ISSUE THREAD

**Issue by 13775072234** [ng-alain/ng-alain#1523]
🚨 Issues 是用于BUG、Feature、进度追踪 🚨
🚨 The issue tracker is not for questions 🚨

如果有任何问题，可在以下方式获得答案：

- https://ng-alain.com/
- QQ Group：316911865
- https://segmentfault.com/t/ng-alain

**Comment by cipchk** [comment]
@13775072234  尝试使用最新版本试试，很久之前就对语言切换会重新渲染的处理了。

**Comment by cipchk** [comment]
长时间未提供重现，暂时关闭。
