### ISSUE TITLE
st自定义按钮组，按钮图标找不到

### ISSUE THREAD

**Issue by Mailko** [ng-alain/ng-alain#1524]
在st的自定义按钮组中，按钮的icon属性的值不知道如何填写，或者不知道有哪些值可供选择，
buttons: [
        {
          text: 'Edit',
          icon: 'edit',
          type: 'modal',
          modal: {
            component: DemoModalComponent,
          },
        },
尝试使用过ng-zorro的图标（https://ant.design/components/icon-cn/），如：PoweroffOutlined，但是并没有效果，页面提示：[@ant-design/icons-angular]:the icon PoweroffOutlined-o does not exist or is not registered.

**Comment by cipchk** [comment]
`icon` 支持对象，包含完整的 `nz-icon` 定义，例如：

```ts
icon: { type: 'edit' }
```
