### ISSUE TITLE
ng align array小部件bug

### ISSUE THREAD

**Issue by wangbaiwang123** [ng-alain/ng-alain#1527]
- ng-alain version: 8.8.0
- Angular version: 8.2.11

## 【必填项】重现链接，Reproduction link

![Uploading QQ图片20200305171734.png…]()
## 重现步骤，Steps to reproduce
1.  地址： https://ng-alain.com/form/array/zh，然后 在 stackblitz中打开
2.  先添加一组数据
3.  后删除，点击提交，添加得那组数据还在

**Comment by cipchk** [comment]
@EyeofTwilight 尝试使用最新版本试试。
