### ISSUE TITLE
ng build 很慢

### ISSUE THREAD

**Issue by zdxxxxxx** [ng-alain/ng-alain#153]
![3827683d-d2c6-4eb0-baa9-3ab71fd4916b](https://user-images.githubusercontent.com/16288673/34368524-b2b7d54c-eaef-11e7-84ad-bc250a6c4725.png)

**Comment by cipchk** [comment]
这一点目前没有什么办法，取决于cli。不过不久后，ABC（简称：Angular、Bazel、Closure）开放后这个问题才会得到解决吧。
