### ISSUE TITLE
ITokenService 增加token过期事件

### ISSUE THREAD

**Issue by John0King** [ng-alain/ng-alain#1530]
像 JWT 的 access_token 默认是 一个小时过期 （3600）  identity_token (id_token)一般是 5分钟 （300），  目前一旦token过期，系统就会退出登陆， 跟进 OpenId 协议里面 的 offline_access ,  请求的时候可以返回一个 refresh_token , 可以在 access_token 过期后，使用 refresh_token 换一个 新的 access_token, 目前没法处理这个 refresh_token

**Comment by cipchk** [comment]
事实上，可以发起刷新请求，我会下一版本中增加这个功能。

**Comment by John0King** [comment]
@cipchk   另外 还请 实现 我在 https://github.com/ng-alain/ng-alain/issues/1525 里面提到的 
`_HttpClient.form<TResponse>(url : string, form : FormData | any, params? : any, headers? : any):Observable<TResponse>` 方法

**Comment by tang-butian** [comment]
@John0King 现阶段你可以参考我的做法
![image](https://user-images.githubusercontent.com/27254047/80852398-cb102680-8c5a-11ea-8200-2444fc6c1c7b.png)
![image](https://user-images.githubusercontent.com/27254047/80852411-de22f680-8c5a-11ea-8173-0adb351605cd.png)
但有时候还是会直接跳转到登录，我还没时间调试，但是我觉得思路是对的

**Comment by cipchk** [comment]
fixed by [#1763](https://github.com/ng-alain/ng-alain/pull/1763)

**Comment by John0King** [comment]
@cipchk  @2693252993 这样处理真的好么？ 我认为它可能产生 死循环

看看里面的 案例4

另外， asp.net core 中 ，  token 如果过期  是在  `Authentication`  认证阶段 认为 token 不是有效的，所以会返回 401，
当 token 认证通过， 接下来的就是 `Authorization` 授权阶段，   在这个阶段， 可能产生 该认证过的用户 无法通过 系统配置的 授权 策略，  返回 403 ，（ 也就是要最后返回给用户的 403， 通常这就是最后了， 再怎么处理，除了重新登录其他权限更大的用户外， 不可能再授权成功了， 所以一般直接告诉用户， 您没有权限. ）  案例4 在一个 遵守规则的情况下， 除非发生了 后台api 配置错误， 导致正常的token 无法通过认证产生了

实际上，有以下几个阶段容易产生问题
1.  认证中心 --> refresh_token ----> 正常 400 错误， 万一某个 认证中心实现错误 返回 401
2. 认证中心--> 用户名密码---> 返回400  ， 万一返回 其他 状态码 如 401
3. api  --> token 过期  -->   正常 401 ， 万一返回 403

----------

### case 1  --> good case
- user login  =>  token, id_token , refresh_token
- access api  -->  token  --> 200 ok
- id_token  expired
- token expired
- access  api --> 401 not authenticate
- fallback to  refreshToken -> 200 ok ->  token, id_token
- continue  access api --> 200 ok
- success

### case 2 ---> bad case 
- user login  =>  token, id_token , refresh_token
- access api  -->  token  --> 200 ok
- id_token  expired
- token expired
- access  api --> `401 not authenticate`
- fallback to  refreshToken -> 400 bad request 
- return `400 bad request` with  the domain of  the  open_id center
- 原来的api 返回 401，  应该监视这个，让用户去登录， 结果这里被这个拦截器拦截去 refresh token 
- deed loop
 
### case 3 ---> good case 
- user login  =>  token, id_token , refresh_token
- access api  -->  token  --> 200 ok
- id_token  expired
- token expired
- access  api --> 401 not authenticate
- fallback to  refreshToken -> 200 ok ->  token, id_token
- continue  access api -->  403  not **authorized** ,  新token 无法通过授权了
- error -> 403

### case 4---> bad case 
- user login  =>  token, id_token , refresh_token
- access api  -->  token  --> 200 ok
- id_token  expired
- token expired
- access  api --> 401 not authenticate
- fallback to  refreshToken -> 200 ok ->  token, id_token
- continue  access api -->  401  not authenticate ， 新token还是无法通过认证， 可能api和认证中心其中一个错误了
-  goto step 6
-  waiting dead loop


------------------

所以我在想， 让页面知道什么时候会发生 刷新， 这样 我们不需要 回退， 当刷新成功（一般需要提前5秒）我们下次请求就带有新的token 了，  当 api 返回 401 ， 我们直接让用户重新登录，  当返回 403， 我们直接告诉用户，你没权限做这件事。

**Comment by cipchk** [comment]
@John0King 老实说，这种方式开发成本的确比较高，但并不会出现所顾虑的死循环。同时，示例中的代码几乎完全无法不修改的情况下满足业务需求。

但如果 Auth 内置刷新接口，势必需要采用定时器，它同样也会遇到同时多窗体、频率问题，也就是我没有内置的主要原因。

**Comment by John0King** [comment]
@cipchk   定时器可能有多个 window 的情况， 但不会有 频率问题，  我们得到 jwt 的时候， jwt 里面存储了 过期时间， 而且 存 jwt 或者其他 token 的时候， 也应该有个 有效期， 就像 openid /oauth 2 里面的返回一样， 有个  `{ token:"xxxxx", expires:3600}` , 这样每个window 只需要一个 setTimeout 即可（记得提前个5s）， 另外 多window 就算同时刷新token , 原来的 token 也是有效的（对于jwt而言） ， 另外可以通过到期时再次 检测一边， 重新检测过期时间设置新的 setTimeout,  （LocalStorage 的api 是同步的，可能对于多窗口是线程安全的）

**Comment by John0King** [comment]
ps:  我只建议增加一个 事件  `onTokenExpired: Obserable<{ currentToken:string }>`
