### ISSUE TITLE
ST查询

### ISSUE THREAD

**Issue by gelinagg** [ng-alain/ng-alain#1532]
- ng-alain version: X.Y.Z
- Angular version: X.Y.Z

## 重现步骤，Steps to reproduce
st搜索功能，st如果切非第一页后，查询框中输入条件，点击【搜索】，访问url是条件+当前页码，但是只查询当前页面的内容。与第一页查询的内容不一致。在【搜索】的click上增加st.load(1)，会产生2个请求后台的记录。可以优化么。

**Comment by cipchk** [comment]
麻烦提供一下版本信息。

**Comment by gelinagg** [comment]
7.2版本8版本都有

**Comment by cipchk** [comment]
长时间未提供重现，暂时关闭。
