### ISSUE TITLE
sf是不支持array简单类型么？（即array内部不是object，而是string/number之类）

### ISSUE THREAD

**Issue by met-pub** [ng-alain/ng-alain#1533]
- ng-alain version: 8.5.1

## 【必填项】重现链接，Reproduction link
https://stackblitz.com/edit/ng-alain-setup-85mgzk

![image](https://user-images.githubusercontent.com/7079888/76299185-9a181300-62f5-11ea-9ed9-0b8edbc1d79e.png)

**Comment by cipchk** [comment]
不支持基础类型的数组，可以使用 `select` 来代替。
