### ISSUE TITLE
sf自定义的widget在ngOnInit中取不到this.value的值？如何能取到呢？

### ISSUE THREAD

**Issue by met-pub** [ng-alain/ng-alain#1534]
- ng-alain version: 8.5.1

## 【必填项】重现链接，Reproduction link
https://stackblitz.com/edit/ng-alain-setup-custom-widget

## 重现步骤，Steps to reproduce
![image](https://user-images.githubusercontent.com/7079888/76313381-cc366e80-630f-11ea-8527-9e7f143ee9b0.png)

**Comment by cipchk** [comment]
`onInit` 只是渲染，并未对数据进行装载，你可以在 `reset()` 内来获取值。

```ts
reset(): void {
  console.log(this.value);
}
```

**Comment by met-pub** [comment]
谢谢。我的widget是放在弹出来的modal中的，reset() 不会被调用。有可能是什么问题？
