### ISSUE TITLE
sf的date小部件mode为range时,第二个值的格式出错

### ISSUE THREAD

**Issue by wlclass** [ng-alain/ng-alain#1535]
- ng-alain version: 8.9.0
- Angular version: 8.2.7

## 【必填项】重现链接，Reproduction link

https://stackblitz.com/edit/ng-alain-setup-aj9wb4

 
![image](https://user-images.githubusercontent.com/3060616/76394974-52ef5800-63b1-11ea-8c70-a65e1d814785.png)

## 重现步骤，Steps to reproduce

随意选择一个时间范围,点击提交按钮.
请看alert框里的第二个值的格式,跟第一个值不同

清除选择的时间后,再点击提交按钮.值成了"Invalid Data"

**Comment by wlclass** [comment]
已发pr.请审查.

**Comment by cipchk** [comment]
closed by https://github.com/ng-alain/delon/pull/778

**Comment by klaokai** [comment]
我也碰到这个问题，并且配合st控件使用，会出现end值丢失的情况
![image](https://user-images.githubusercontent.com/14050993/77410387-c2276c00-6df5-11ea-91c9-ebb0b8941613.png)
