### ISSUE TITLE
在切换到顶部菜单布局下，footer-toolbar默认没有撑满下面的页面

### ISSUE THREAD

**Issue by 305088020** [ng-alain/ng-alain#1536]
- ng-alain version: 8.6.0
- @delon/theme version: 8.5.0
- Angular version: 8.3.1

<img width="1440" alt="WechatIMG201" src="https://user-images.githubusercontent.com/15034602/76481852-854e9300-644d-11ea-9dfe-41ee27f458c0.png">

**Comment by cipchk** [comment]
fixed by `9.0.0`
