### ISSUE TITLE
sf的校验规则取不到其他字段的值

### ISSUE THREAD

**Issue by met-pub** [ng-alain/ng-alain#1537]
- ng-alain version: 8.5.1

## 【必填项】重现链接，Reproduction link
https://stackblitz.com/edit/ng-alain-setup-custom-widget

## 重现步骤，Steps to reproduce
用文档里的校验方法：
```
ui: {
          validator: (value: any, formProperty, form) => {
          return form.value.name2 === 'cipchk' ? [] : [{ keyword: 'required', message: '必须是cipchk@qq.com'}];
        }
}
```
见上述链接的console
> ERROR
> Error: Cannot read property 'name2' of null

form.value 是null

**Comment by cipchk** [comment]
如果你需要在 `validator` 内调用其他字段值，则可以 `form.properties.name2.value` 。

**Comment by met-pub** [comment]
编译不过去，也不会生效。麻烦看下 https://stackblitz.com/edit/ng-alain-setup-custom-widget

**Comment by NanFengCheong** [comment]
You need to change value of Name3 to trigger validator of Name3

**Comment by WalkingNormal** [comment]
同。编译不过去

**Comment by cipchk** [comment]
@WalkingNormal 

```diff
- return form.properties.name2.value
+ return (form.properties as { [key: string]: FormProperty } ).name2.value
```
