### ISSUE TITLE
time 没有时间变化回调， 也没有 时间范围所对应的结束值 end

### ISSUE THREAD

**Issue by succulen-plants** [ng-alain/ng-alain#1538]
- ng-alain version: X.Y.Z
- Angular version: X.Y.Z

## 【必填项】重现链接，Reproduction link

    time: {
        type: 'string',
        ui: { widget: 'time' } as SFTimeWidgetSchema,
      },

**Comment by cipchk** [comment]
能否提供更多细节？我无法理解你遇到什么问题。

**Comment by succulen-plants** [comment]
我要实现的功能是， 选择一天中发送消息的时间段，比如 9:00 到  15:00， 但是时间选择没有提供 end或者时间选择后的回调函数， 导致结束时间可以早于开始时间

**Comment by cipchk** [comment]
我建议你自己自定义一个这类业务级的小部件这会更容易一点。
