### ISSUE TITLE
sf  string 文本框，没有回调， 数据输入后不能做绑定

### ISSUE THREAD

**Issue by succulen-plants** [ng-alain/ng-alain#1539]
- ng-alain version: X.Y.Z
- Angular version: X.Y.Z

## 重现步骤，Steps to reproduce

name: {
        type: 'string',
        title: 'Name',
        ui: {
          addOnAfter: 'RMB',
          placeholder: 'RMB结算',
        } as SFStringWidgetSchema,
      },

**Comment by cipchk** [comment]
能否提供更多细节？我无法理解你遇到什么问题。

**Comment by xingkoo** [comment]
是想说，当前输入框为焦点时，点击回车键触发事件？

**Comment by succulen-plants** [comment]
是的， 就是没有提供输入数据后的触发事件，我需要监听输入框的输入信息

**Comment by xingkoo** [comment]
<input nz-input [(ngModel)]="testKeyUp"  (keyup)="keyUpSearch($event)">

<input nz-input [(ngModel)]="testKeyUp"  (keyup.enter)="keyUpSearch()">

善用搜索。close issue。
