### ISSUE TITLE
Increasing token authorization will have cross-domain issues and not obtain authorization information for the first time

### ISSUE THREAD

**Issue by DreamPWJ** [ng-alain/ng-alain#154]
Why does adding token authorization have cross-domain problems that don't increase without the following code

userId:localStorage.getItem("_token")?JSON.parse(localStorage.getItem("_token")).id:"",
token:localStorage.getItem("_token")?JSON.parse(localStorage.getItem("_token")).token:""

login_url: `/passport/login`,
token_send_key: 'Authorization',
token_send_template:environment.userId+"_"+environment.token,
token_send_place: 'header'

authorization=====null
authorization=====1_68e50ffc92f943e7b274e2bf6ed0d862
authorization=====1_68e50ffc92f943e7b274e2bf6ed0d862

## Environment

<pre><code>
Angular version: X.Y.Z

delon version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX

For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by DreamPWJ** [comment]
Angular CLI: 1.6.2
Node: 6.9.1
OS: win32 x64
Angular: 5.1.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 5.0.1
@angular/cli: 1.6.2
@angular-devkit/build-optimizer: 0.0.36
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.42
@ngtools/json-schema: 1.1.0
@schematics/angular: 0.1.11
@schematics/schematics: 0.0.11
typescript: 2.5.3
webpack-bundle-analyzer: 2.9.1
webpack: 3.10.0

**Comment by cipchk** [comment]
I think compare every request via chrome network panel. most of corss-domain be caused by request arguments.

**Comment by DreamPWJ** [comment]
http://127.0.0.1:8081/news/list   Get requests without parameters   If you open a cross-domain with plug-ins you can access it but it will appear  simple-table Cannot read property 'indexOf' of undefined

**Comment by DreamPWJ** [comment]
The first login cannot obtain the authorization information. The information may be written in the app.module

**Comment by cipchk** [comment]
I think you hope the following config of `AlainAuthModule`:

```
AlainAuthModule.forRoot({
    token_send_template: `${userId}_${token}`
})
```

but, not yet!

---

Do you provider more information about `indexOf` error?

**Comment by DreamPWJ** [comment]
1.token_send_template: `${userId}_${token}`   The wrong editor was incorrectly reported 
2.  indexOf  错误 <simple-table [data]="newsList"  [columns]="columns"  showTotal></simple-table>   ListComponent.html:12 ERROR TypeError: Cannot read property 'indexOf' of undefined
    at new HttpRequest (http.js:871)
    at HttpClient.request (http.js:1453)
    at _HttpClient.request (http.client.js:226)
    at SimpleTableComponent._genAjax (simple-table.component.js:199)
    at SimpleTableComponent.updateStatus (simple-table.component.js:580)
    at SimpleTableComponent.ngOnChanges (simple-table.component.js:592)
    at checkAndUpdateDirectiveInline (core.js:12396)
    at checkAndUpdateNodeInline (core.js:13927)
    at checkAndUpdateNode (core.js:13870)
    at debugCheckAndUpdateNode (core.js:14763)

**Comment by DreamPWJ** [comment]
add     response.setHeader("Access-Control-Allow-Headers", "Authorization,token,x-requested-with");    A solution to the JWT cross domain is implemented
