### ISSUE TITLE
st.resetColumns  不能生效

### ISSUE THREAD

**Issue by succulen-plants** [ng-alain/ng-alain#1540]
- ng-alain version: X.Y.Z
- Angular version: X.Y.Z

## 重现步骤，Steps to reproduce
在html 中调用 st.resetColumns() 结合 iif可以改变表结构，我需要根据获取的数据来改变表结构， 我在ts中 调用 this.ts.resetColumns() 不能生效

**Comment by cipchk** [comment]
@succulen-plants 麻烦提供一个重现 示例

**Comment by cipchk** [comment]
长时间未提供重现，暂时关闭。
