### ISSUE TITLE
多语言采用 translate.getBrowserLang(); 会被截取前两位的（zh）,与LANGS数组不存在匹配

### ISSUE THREAD

**Issue by jol5** [ng-alain/ng-alain#1543]
- ng-alain version: 8.X
- Angular version: 8.X

## 【必填项】重现链接，Reproduction link
源码链接：
https://github.com/ng-alain/ng-alain/blob/c435d38eba01634f06ef4b99340810ec813f2709/src/app/core/i18n/i18n.service.ts#L82
我采用：translate.getBrowserLang() -> navigator.language 获取系统首选语言了
## 重现步骤，Steps to reproduce
    const defaultLan = settings.layout.lang || translate.getBrowserLang();

**Comment by cipchk** [comment]
@jol5 目前采用的是 [getBrowserLang](https://github.com/ngx-translate/core/blob/master/projects/ngx-translate/core/src/lib/translate.service.ts#L506)，内部实际也是 `navigator.language`，不管怎么说这个还取决于目标浏览器的配置。你的浏览器环境是什么样的呢？

**Comment by jol5** [comment]
> @jol5 目前采用的是 [getBrowserLang](https://github.com/ngx-translate/core/blob/master/projects/ngx-translate/core/src/lib/translate.service.ts#L506)，内部实际也是 `navigator.language`，不管怎么说这个还取决于目标浏览器的配置。你的浏览器环境是什么样的呢？
1.浏览器只是设置了 中文 ，其他没有改变；
2.源码里边是做了切割的，zh-CN 会返回zh，与系统的统一配置（zh-CN）不符合，所以，遇到繁体字（zh-TW）时，就会因为不匹配，而直接展示默认值了。
