### ISSUE TITLE
sf的date部件range模式配合st控件的reset函数，会出现无法传送end值

### ISSUE THREAD

**Issue by klaokai** [ng-alain/ng-alain#1544]
- ng-alain version: 8.9.0
- Angular version: 8.2.14

## 【必填项】重现链接，Reproduction link
[Stackblitz模板](https://stackblitz.com/edit/ng-alain-setup-aepe9m?file=src/app/app.component.ts)

![image](https://user-images.githubusercontent.com/14050993/77413933-2993ea80-6dfb-11ea-9d1e-6aa415eed7b1.png)

怀疑是特殊符号的问题

## 重现步骤，Steps to reproduce
随意选择一个时间范围,点击提交按钮.
请看alert框里的第二个值的格式,跟第一个值不同

配合st控件使用，会出现end值丢失的情况
![image](https://user-images.githubusercontent.com/14050993/77410387-c2276c00-6df5-11ea-91c9-ebb0b8941613.png)

发现是组装语句range组装了两次
![image](https://user-images.githubusercontent.com/14050993/77436028-f31b9700-6e1d-11ea-966d-19adeab9e47c.png)

**Comment by wlclass** [comment]
https://github.com/ng-alain/ng-alain/issues/1535
