### ISSUE TITLE
st表格不支持rowspan配置吗，现在只能在STColumn中配置colSpan

### ISSUE THREAD

**Issue by snowsniw** [ng-alain/ng-alain#1545]
🚨 Issues 是用于BUG、Feature、进度追踪 🚨
🚨 The issue tracker is not for questions 🚨

如果有任何问题，可在以下方式获得答案：

- https://ng-alain.com/
- QQ Group：316911865
- https://segmentfault.com/t/ng-alain

**Comment by cipchk** [comment]
duplcated of #1126
