### ISSUE TITLE
side-nav component enhancement suggestion

### ISSUE THREAD

**Issue by ChangYinShung** [ng-alain/ng-alain#1546]
您好:  
使用以下網址 https://ng-alain.github.io/ng-alain/#/dashboard/v1  
選單:`儀表板`->`默認頁` 會自動亮起顯示藍色文字  

其他情況
當網址為 https://ng-alain.github.io/ng-alain/#/dashboard/v1?pageNo=1&pageSize=15，
選單並不會自動sidebar-nav__selected ，能否夠忽略比對 `?` 後面的參數 ，使選單顯示藍色文字

**Comment by succulen-plants** [comment]
这个问题如何解决了
