### ISSUE TITLE
配置栏在build之后，不消失

### ISSUE THREAD

**Issue by bxy2000** [ng-alain/ng-alain#1547]
配置栏只在开发环境用于预览，生产环境不会展现，请拷贝后手动修改参数配置文件 src/styles/theme.less

yarn build 之后，部署在web服务器上，配置栏依然存在，之前都没有，是升级8的原因？

**Comment by cipchk** [comment]
可能是克隆 ng-alain 源代码引起的，这里有个发布的错误引起的，[default.component.ts](https://github.com/ng-alain/ng-alain/blob/master/src/app/layout/default/default.component.ts#L80) 更改一下即可：

```diff
- if (!environment.prod) {
+ if (true) {
```
