### ISSUE TITLE
关于路由复用问题

### ISSUE THREAD

**Issue by guccihuiyuan** [ng-alain/ng-alain#155]
我实现了RouteReuseStrategy这个协议，在同一个子路由下可以复用，但是切换到其他子路由的时候，就会重新刷新一次，这个该怎么解决呢？

**Comment by cipchk** [comment]
抱歉，请提供更有效的信息，例如 https://stackblitz.com/edit/ng-alain-setup 可复现的示例

**Comment by neishiliu** [comment]
从项目列表进入其子路由项目详情时，切换reuseTab时详情页面会重新执行生命周期重新渲染。
![untitled](https://user-images.githubusercontent.com/18006711/34593730-a41a2d4a-f207-11e7-9a08-ad678f64cbaf.gif)

**Comment by cipchk** [comment]
最新打开的永远是当前的，而路由复用是指当我们离开当前页时若符合复用条件则保存当前路由所有组件状态（包括子组件），待下一次进入相同条件路由时再从中缓存中获取到。

**Comment by neishiliu** [comment]
关于路由复用条件是按照设置的匹配模式确定么？ 
 如果是的话，在默认的模式mode="MenuForce"下：
1、我在项目信息这个menu下并没有配置reuse：true这个属性却还是能复用；
![image](https://user-images.githubusercontent.com/18006711/34594372-9590115a-f20b-11e7-8675-8704f4b0d6bb.png)
![image](https://user-images.githubusercontent.com/18006711/34594393-aae6ca62-f20b-11e7-9939-44d52f5cbc1f.png)

2、对于像详情页这样的没有出现在menu里面的页面都不会复用么？
还请提供更多的关于复用条件的信息，谢谢！

**Comment by cipchk** [comment]
> 除以上规则以外，路由配置中 `data` 属性若设置 `reuse` 值时优先级高于上述规则

**Comment by winpzs** [comment]
这应该是url不匹配，应该在路由配置中 data 中增加一个属性，是否只匹配url部分，不理参数

**Comment by winpzs** [comment]
我的列表页面不能复用，切换到别的tab后， 会自动destory
但一些简单的页面就没问题

**Comment by winpzs** [comment]
查到原因了， 只要routing里有children节点，都不能复用，如下：
```typescript
{
	path: 'list', component: ListComponent,
	loadChildren: './ui-demo-routing.module#UiDemoRoutingModule'
}
```
/list 这个页面永远不能复用

**Comment by cipchk** [comment]
我无法回答你这个问题，原因是路由复用的原理是依当前路由的URL的地址为准，因此理论上不存在这种问题。

**Comment by winpzs** [comment]
我这样做的
/list 出列表页面
/list/detail;id=i-81520D9D 出相应的详情页面

也就是说/list页面里我会放一个router-outlet再结合上面的routing配置

这样就会出现不能复用

**Comment by cipchk** [comment]
能否提供https://stackblitz.com/edit/ng-alain-setup 可复现的示例

**Comment by winpzs** [comment]
你看看: [https://stackblitz.com/edit/ng-alain-setup-qh7vmt?file=app%2Fapp.module.ts](https://stackblitz.com/edit/ng-alain-setup-qh7vmt?file=app%2Fapp.module.ts)
  
list是不能复用的

**Comment by cipchk** [comment]
我不太明白的一点是，当有一个外层布局时为什么不是这样的路由配置呢？

```ts
  {
    path: 'list',
    component: LayoutListComponent,
    children: [
      { path: '', component: ListComponent },
      { path: 'detail', component: DetailComponent }
    ]
  },
```

是否这种的路由配置更为合理呢？

一个可行的 [demo](https://stackblitz.com/edit/ng-alain-setup-d6qoer?file=app%2Flist-layout.component.ts)

**Comment by winpzs** [comment]
那算了， 我只是试一下能不能在同一个tab，你这个还是会新一个tab

也就是说子页面都在同一个tab里打开，类似于a标签的target可以本窗口或新窗口

**Comment by cipchk** [comment]
### 不同URL

- `/list`
- `/list/edit`
- `/list/edit/1`

### 同URL

- `/list/view?id=1`
- `/list/view?id=2`

**Comment by cipchk** [comment]
可能等同 [#13](https://github.com/cipchk/delon/issues/13)，关闭此问题，有进一步需要重新提交。

**Comment by thelaurelyy** [comment]
@winpzs  请教，我在使用路由复用的时候出现了同一个Tab内跳转的情形，请问是什么原因导致的呢？
