### ISSUE TITLE
se-container 表现未符合预期

### ISSUE THREAD

**Issue by lengsehuoyan** [ng-alain/ng-alain#1551]
[order-edit.component.txt](https://github.com/ng-alain/ng-alain/files/4448092/order-edit.component.txt)
se-container=1,2,3,4 都表现良好
se-container=5 显示6列
se-container=6 显示10列

**Comment by cipchk** [comment]
列会根据响应式配置来决定不同分辨率需要显示多少列，默认配置请参考：https://ng-alain.com/theme/responsive/zh

**Comment by lengsehuoyan** [comment]
感谢。
