### ISSUE TITLE
st 的自定义列无法双向绑定？

### ISSUE THREAD

**Issue by Rwing** [ng-alain/ng-alain#1556]
- ng-alain version: 最新
- Angular version: 最新

## 【必填项】重现链接，Reproduction link
https://stackblitz.com/edit/ng-alain-setup-jxutjc

![image](https://user-images.githubusercontent.com/497333/79175520-8437c980-7e30-11ea-90ff-00d391e23113.png)

**Comment by cipchk** [comment]
duplcated of #1557

**Comment by Rwing** [comment]
可能与#1557不是同一个问题。
![image](https://user-images.githubusercontent.com/497333/79520826-4fbf4a00-808a-11ea-8f33-143751063a12.png)
