### ISSUE TITLE
关于tab的主题色问题

### ISSUE THREAD

**Issue by guccihuiyuan** [ng-alain/ng-alain#156]
我切换主题色的时候，其他控件的颜色都变了，tab的hovor状态主题色也变了，但是actived的颜色没有边，请问下在哪里设置呢？我用的是0.14的版本

**Comment by cipchk** [comment]
https://cipchk.github.io/ng-alain/dashboard/analysis
其中销售额&访问量并无这种现象，若是低版本的原因可以自行参考 @delon/theme 的历史变更记录。

**Comment by cipchk** [comment]
长时间未处理；有任何问题重新提交issues。
