### ISSUE TITLE
sf中的date控件默认值无法使用format进行格式化

### ISSUE THREAD

**Issue by klaokai** [ng-alain/ng-alain#1560]
- ng-alain version: 8.9.2
- Angular version: 8.6.26

## 【必填项】重现链接，Reproduction link
https://stackblitz.com/edit/ng-alain-setup-fxyrs2

## 重现步骤，Steps to reproduce
1.控件中设置如下
```ts
start: {
        type: 'string',
        title: '时间范围',
        default: "2020-04-15 14:00:00",
        ui: {
          grid: {
            span: 12,
          },
          widget: 'date',
          format:'YYYY-MM-DD HH',
          displayFormat: 'YYYY-MM-DD HH',
          end: 'end',
          showTime: true,
          showToday: true,
        } as SFDateWidgetSchema,
      },
      end: {
        type: 'string',
         default: "2020-04-15 16:00:00",
      },
```

2.直接点击提交，页面上方的message提示
{"start":"2020-04-15 14:00:00","end":"2020-04-15 16:00:00"}

3.随意更改日期后点击提交，页面上方的message提示
{"start":"2020-04-11 14","end":"2020-05-14 16"}

4.可见，默认值情况下，format没有生效

**Comment by cipchk** [comment]
`YYYY-MM-DD HH` 格式结果为 `2020-04-11 14` 这里有什么问题吗？还是指其他 方面？

**Comment by klaokai** [comment]
> `YYYY-MM-DD HH` 格式结果为 `2020-04-11 14` 这里有什么问题吗？还是指其他 方面？

在一开始会有:00:00 这个后缀。点选控件直接后才输出2020-04-11 14

**Comment by klaokai** [comment]
> `YYYY-MM-DD HH` 格式结果为 `2020-04-11 14` 这里有什么问题吗？还是指其他 方面？

![image](https://user-images.githubusercontent.com/14050993/79864783-9efbd680-840c-11ea-9a18-06e97a49c264.png)
