### ISSUE TITLE
sf的array部件删除功能存在问题

### ISSUE THREAD

**Issue by ydostyle** [ng-alain/ng-alain#1561]
- ng-alain version: 8.9.2
- Angular version: 9.1.2

Stackblitz模板:https://stackblitz.com/edit/angular-eljnrd

## 重现步骤

1.使用sf组件的array部件
2.默认展示2条数据
3.点击删除，删除全部数据
4.在submit打印数据，理论上数组应该是空，但是会存在一条数据。
![1](https://user-images.githubusercontent.com/22721444/79417835-c0605b00-7fe5-11ea-8e51-01acc85e7dde.jpeg)

**Comment by ydostyle** [comment]
回退到8.80版本是正常的。

**Comment by cipchk** [comment]
@ydostyle 我们还没有做好适配 9.x

**Comment by ydostyle** [comment]
@cipchk 不是angular9.x的问题。。8.x也有这个问题。。我本地项目angular是8.x的。你看看回退@delon/form到8.80就不会出现这个问题了。是出现在8.9.0里的

**Comment by ydostyle** [comment]
https://stackblitz.com/edit/ng-alain-setup-fmhnup?file=package.json 这个是8.x版本的
