### ISSUE TITLE
STColumnButton 可否添加 className 属性 来定义每个button的样式

### ISSUE THREAD

**Issue by 1zilc** [ng-alain/ng-alain#1563]
或者 可否提供 color 参数定义button的颜色
![20200416-165616](https://user-images.githubusercontent.com/44715458/79436319-4c34b000-8003-11ea-9f91-86a3277ea4bd.png)

**Comment by cipchk** [comment]
`nz-button` 组件并没有提供这类接口，建议自行通过定义 css 来强制刷新。
