### ISSUE TITLE
文档错误：STColumn 没有 i18n 属性

### ISSUE THREAD

**Issue by e-cloud** [ng-alain/ng-alain#1564]
- ng-alain version: 8.9.2
- Angular version: 8.x.0

## 【必填项】重现链接，Reproduction link
https://github.com/ng-alain/delon/blob/21eec5b1ace7dc88e5ba41e12a5d82fa0412be15/packages/abc/table/index.zh-CN.md#stcolumn

文档里面写着 `i18n` 属性
实际代码的 STColumn 接口里面并没有

**Comment by cipchk** [comment]
这是一个过期属性，使用 `title.i18n` 替代。
