### ISSUE TITLE
no such file or directory, open '/work/nodeprojects/ng-alain/node_modules/@antv/g2-plugin-slider/dist/g-2.0.0.min.js'

### ISSUE THREAD

**Issue by yhnnhyyhnn** [ng-alain/ng-alain#157]
请问这个异常是怎么回事？node_modules里g2-plugin-slider.min.js，但是没有g-2.0.0.min.js

**Comment by cipchk** [comment]
缺少包体文件，就目前 ng-alain 包含的 g2 包体而言，其结构大概是这样子：

![tim 20171229174558](https://user-images.githubusercontent.com/2987467/34434319-3d214d2c-ecc0-11e7-9960-89485289606a.png)

**Comment by yhnnhyyhnn** [comment]
我把.angular-cli.json文件中对g2-plugin-slider的依赖包改成真正install的包名,就ok了

**Comment by qiuliang1** [comment]
请问如果我要引入g2该如何引入，因为g2里面没有.d.ts文件，所以我new G2.Chart未定义，求教
![image](https://user-images.githubusercontent.com/35951262/38844208-008ffd12-4225-11e8-9925-878ceabb861e.png)

**Comment by qiuliang1** [comment]
我使用的是ng-alain

**Comment by cipchk** [comment]
https://github.com/cipchk/ng-alain/blob/master/src/typings.d.ts#L16
