### ISSUE TITLE
SFUISchema布局没有对齐

### ISSUE THREAD

**Issue by amoycode** [ng-alain/ng-alain#1575]
- ng-alain version: 9.0.0-rc.2
- Angular version: 9.1.2

### 升级前
![image](https://user-images.githubusercontent.com/18238708/79689487-cb3a1a80-8287-11ea-8221-bfdfd309c021.png)

### 升级后
![image](https://user-images.githubusercontent.com/18238708/79689477-b9587780-8287-11ea-911c-99f873664893.png)

## 重现步骤，Steps to reproduce
```
ui: SFUISchema = {
    '*': {
      spanLabelFixed: 100,
      grid: { span: 12 },
    },
    $remarks: {
      spanLabelFixed: 100,
      grid: { span: 24 },
    },
  };

```

**Comment by cipchk** [comment]
麻烦提供一个可重现的完整示例。 @amoycode

**Comment by blacksola** [comment]
看了一下，大概是nz-form-item下的nz-col中有ant-col-5这类class，这些class有类似max-width: 20%这些属性，当设的spanLabelFixed的固定值大于ant-col-x的max-width时就造成这种效果了

**Comment by cipchk** [comment]
@blacksola 能否提供一个重现示例，我无法重现这种现象 。

**Comment by blacksola** [comment]
官网的动态表单示例在stackblitz里打不开，提示
![image](https://user-images.githubusercontent.com/16145619/79741627-27f30f00-8334-11ea-80aa-165f63effb52.png)

只能临时搭一个空脚手架
http://129.204.88.98:8076/#/dashboard
服务器较慢，稍等会

可以看到我设的label的宽是180，但是label上的ant-col-5的class中有max-width: 20%的属性，所以实际宽度上限被限制了
textarea的label是正常的180，因为180不够一整行的20%
@cipchk

**Comment by cipchk** [comment]
@blacksola 感谢，已修复，今晚会发布新版本。
