### ISSUE TITLE
ng-alain 9 Invalid "extends" configuration value - could not require "tslint-config-prettier".

### ISSUE THREAD

**Issue by smallsong** [ng-alain/ng-alain#1577]
- ng-alain version: lastest
- Angular version: Angular CLI: 9.1.1

ng-cli 已经升级到最近版本
ng version 显示 

Angular CLI: 9.1.1
Node: 12.16.2
OS: win32 x64

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.1
@angular-devkit/build-angular     0.901.1
@angular-devkit/build-optimizer   0.901.1
@angular-devkit/build-webpack     0.901.1
@angular-devkit/core              9.1.1
@angular-devkit/schematics        9.1.1
@angular/cli                      9.1.1
@ngtools/webpack                  9.1.1
@schematics/angular               9.1.1
@schematics/update                0.901.1
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0

执行  `ng add ng-alain`   

oops

> Failed to load D:\project\starter\ng-alain-project\tslint.json: Invalid "extends" configuration value - could not require "tslint-config-prettier". Review the Node lookup algorithm (https://nodejs.org/api/modules.html#modules_all_together) for the approximate method TSLint uses to find the referenced configuration file.

**Comment by cipchk** [comment]
@smallsong 事实上已经成功安装了，只是最后一个会做一次 `ng line --fix` 动作.
