### ISSUE TITLE
动态表单date小部件绑值Invalid Date问题

### ISSUE THREAD

**Issue by wenpengpeng** [ng-alain/ng-alain#1578]
- ng-alain version: 8.8.0
- Angular version: 8.3.23

1、先选择一个时间段，点击搜索，这个时候是正常的；
![image](https://user-images.githubusercontent.com/34331662/79817725-b0b38e80-83b8-11ea-98b7-a13efb343f57.png)
2、点击叉叉，清空时间段；
![image](https://user-images.githubusercontent.com/34331662/79817844-e8bad180-83b8-11ea-9cb4-b324dd73b85c.png)
3、点击搜索，时间字段绑定的值就变成了Invalid Date了；
![image](https://user-images.githubusercontent.com/34331662/79817966-3cc5b600-83b9-11ea-8a12-48483053cb3c.png)
以下是我的代码：
![image](https://user-images.githubusercontent.com/34331662/79818148-a6de5b00-83b9-11ea-9bc8-7e97037b7932.png)
![image](https://user-images.githubusercontent.com/34331662/79818183-c2496600-83b9-11ea-9c3f-2765936f064a.png)

另：我在https://stackblitz.com/edit/ng-alain-setup上尝试使用date小部件是正常的，并且我赋值默认值为‘’空字符串，在我的项目中首次进入页面的时候时间段是有值的（1970-01-01~2020-04-21），而在https://stackblitz.com/edit/ng-alain-setup上又是没有值的，如下面的图所示：
![image](https://user-images.githubusercontent.com/34331662/79818446-692e0200-83ba-11ea-9779-1cadeb5d1e15.png)
![image](https://user-images.githubusercontent.com/34331662/79818528-a2ff0880-83ba-11ea-89ff-8be7621acfd7.png)
是我使用的这个版本有这个问题吗？

**Comment by cipchk** [comment]
@wenpengpeng 试着指定一下 `format` 呢？

**Comment by wenpengpeng** [comment]
> @wenpengpeng 试着指定一下 `format` 呢？

还是不行，绑的值还是“Invalid Date”

**Comment by cipchk** [comment]
@wenpengpeng 能否提供一下重现示例。

**Comment by wenpengpeng** [comment]
> @wenpengpeng 能否提供一下重现示例。

![image](https://user-images.githubusercontent.com/34331662/79842549-9050f780-83eb-11ea-91ea-caa2845efe06.png)
![image](https://user-images.githubusercontent.com/34331662/79842807-eb82ea00-83eb-11ea-952d-2e700eb6a5f8.png)

我用的就是当时官网下载下来的8.8.0版本的框架代码，这里上传不了zip文件，我在上面加了个时间段的小部件进行测试，就看到了上图说的结果，又出现了不一样的问题
另外还有个问题就是我们几个人的电脑都有这个问题，但有一个人的电脑访问又是没有问题的，我混乱了。。。。

**Comment by cipchk** [comment]
@wenpengpeng 你可以把完整的 Schema 给我，我运行一下能重现就行。
