### ISSUE TITLE
angular8版本不支持IE浏览器吗？

### ISSUE THREAD

**Issue by hightwo499** [ng-alain/ng-alain#1580]
- ng-alain version: 8.9.2
- Angular version: 8.2.11
polyfills文件中导入相应的包后，用IE浏览器依然打不开页面，没有报错信息
![image](https://user-images.githubusercontent.com/51105345/79843238-95627680-83ec-11ea-84c7-78876ba47393.png)

**Comment by cipchk** [comment]
我试一下，已经非常久没有尝试在ie下使用了。

**Comment by succulen-plants** [comment]
这个问题回复一下吧， 比较重要
