### ISSUE TITLE
升级9.0 后 se-title 不能独占一行了，还有 se-container 里面的 title 属性

### ISSUE THREAD

**Issue by tang-butian** [ng-alain/ng-alain#1584]
- ng-alain version: 9.0.0-rc.1
- Angular version: 9.1.2

## 重现步骤，Steps to reproduce

![image](https://user-images.githubusercontent.com/27254047/79935940-b8426880-8488-11ea-884b-2d9b5a8f60d8.png)
![image](https://user-images.githubusercontent.com/27254047/79935948-bd9fb300-8488-11ea-8ae1-0e0b54062368.png)
添加 style="width: 100%;" 后就恢复正常

**Comment by cipchk** [comment]
请升级至最新版本 `rc.3`

**Comment by tang-butian** [comment]
@cipchk   我升级rc.3了还是一样
