### ISSUE TITLE
[v8-v9] @delon/util

### ISSUE THREAD

**Issue by net027** [ng-alain/ng-alain#1586]
9.0 升级文档中提到
@delon/util 中移除了 *stringTemplateOutlet，

将现有项目中的 *stringTemplateOutlet  替换为 *nzStringTemplateOutlet 后，
应显示的内容没有显示出来。
chrome 控制台有一个警告：
> Can't bind to 'nzStringTemplateOutlet' since it isn't a known property of 'ng-container'.

还需要修改什么地方吗？

**Comment by net027** [comment]
升级到V9后 ，
*nzStringTemplateOutlet 是引用 ng-zorro-antd 中的 NzStringTemplateOutletDirective 吗？

**Comment by cipchk** [comment]
是的，需要引入

```ts
import { NzOutletModule } from 'ng-zorro-antd/core/outlet';
```
