### ISSUE TITLE
st 由于columns 使用了date类型导致数据都出不来

### ISSUE THREAD

**Issue by tang-butian** [ng-alain/ng-alain#1588]
- ng-alain version: 9.0.0.rc.3
- Angular version: X.Y.Z

## 【必填项】重现链接，Reproduction link

在8.xxx 都是正常的了

## 重现步骤，Steps to reproduce
![image](https://user-images.githubusercontent.com/27254047/79986696-0d10ce00-84df-11ea-8e65-e93359cf609f.png)

![image](https://user-images.githubusercontent.com/27254047/79986754-1f8b0780-84df-11ea-8047-5c3ca35cc371.png)
![image](https://user-images.githubusercontent.com/27254047/79986863-447f7a80-84df-11ea-80a3-a61394987a92.png)

注释掉这个type: 'date' 数据能正常出来
![image](https://user-images.githubusercontent.com/27254047/79987049-814b7180-84df-11ea-8670-59e3b246542b.png)

**Comment by tang-butian** [comment]
没有任何的报错

**Comment by klaokai** [comment]
> 没有任何的报错

临时添加这个看能不能解决，这个bug好像是因为原先YYYY被换成yyyy，DD被换成dd
dateFormat: 'yyyy-MM-dd HH:mm:ss'

**Comment by cipchk** [comment]
强制使用 `date-fns`，所以旧的 `YYYY-MM-DD` 属于 Angular 的格式，这种格式并非标准的。所以如果你指定了 `dateFormat` 就只能批量替换成标准的日期格式。

**前提是必须要指定[默认语言增加上 date-fns 的配置](https://ng-alain.com/docs/upgrade-v9/en#1%E3%80%81date-fns)**

**Comment by tang-butian** [comment]
@cipchk @klaokai    就算我 没有指定 dateFormat 也不行，只要 type: 'date'， 数据就渲染不出来
![image](https://user-images.githubusercontent.com/27254047/80189755-c7bae080-8645-11ea-9729-87115f5a616e.png)

**Comment by tang-butian** [comment]
![image](https://user-images.githubusercontent.com/27254047/80192771-47e34500-864a-11ea-87ed-0eea3e54a18c.png)
也添加了默认语言，但还是不出来

**Comment by tang-butian** [comment]
我找到原因了， 是因为我的后台返的字段 是 string ,  现在我把它map 成 date 就正常了
