### ISSUE TITLE
9.xxx 的 st组件STColumn里 时间类型能不能支持字符串

### ISSUE THREAD

**Issue by tang-butian** [ng-alain/ng-alain#1592]
在8.xxx 里  typd: date 时是支持 接收字符串的，但是到了9.xxx 就只支持 date 类型了，感觉不是很方便

**Comment by cipchk** [comment]
@2693252993 支持 `Date | string | number` 三种类型的呀

**Comment by tang-butian** [comment]
@cipchk  不行哦， 代码在 8.xxxx 的时候是正常的，升到9.xx 后数据都渲染不出来了， 只有把  typd: date 的列注释掉才正常，或者把data 里的 时间字符串 map 成 date 对象才正常

**Comment by caozping** [comment]
st: { title: '开始时间', index: 'Start',  type: 'date', dateFormat: 'yyyy-MM-dd'  },
data:"Start":"2020-04-24 00:00:00"
数据不能绑定到表格 ，
dateFormat: 'yyyy-MM-dd HH:mm:ss' 数据可以绑定到表格，但不是只显示日期部分。

**Comment by tang-butian** [comment]
@caozping   你的是9.xx 吗？  我的是所有数据都渲染不出来

**Comment by caozping** [comment]
升级为9后，数据和dateFormat格式一致的可以显示出来，
原来8.x.x都可以显示的

**Comment by cipchk** [comment]
duplcated of #1595
