### ISSUE TITLE
不同模块页面切换会报错

### ISSUE THREAD

**Issue by s641135196** [ng-alain/ng-alain#1594]
- ng-alain version: 8.2.0
- Angular version: 8.3.2

## 【必填项】重现链接 https://stackblitz.com/edit/ng-alain-setup-ht2qc5
 在stackblitz.com会在Console打印出错误信息
![error](https://user-images.githubusercontent.com/8079013/80294132-cc43de00-8798-11ea-9a04-4c39838d94da.png)

之前这问题重现 #1168 

不知道是不是因为2模块都引用了 `<router-outlet></router-outlet> `所在的Component

**Comment by bluesiboy** [comment]
这个错误是每一个写类似reuse-tab的人都会遇到的一个问题。
![image](https://user-images.githubusercontent.com/9855885/80464256-1b8e3800-896c-11ea-8180-dea9011868be.png)

**Comment by s641135196** [comment]
@bluesiboy 我这个问题有什么解决方法吗

**Comment by bluesiboy** [comment]
第一个办法就是解决你，就能解决这个问题。
第二个办法就是只复用直属于defaultLayoutComponent的路由，也就是那个空白path。你以为给子路由的子路由加个reuse为true的属性就能有选项卡是你成功投机取巧？错啦，不支持的！

**Comment by s641135196** [comment]
@bluesiboy  非常感谢你提供的解决方案
