### ISSUE TITLE
[建议]啥时候给整上登录功能

### ISSUE THREAD

**Issue by dkvirus** [ng-alain/ng-alain#16]
在 NG-ZORRO issue 上看到这个项目，我自己最近也在跟着 NG-ZORRO 框架在做一个后管系统，要是早知道有你这个还瞎整啥，重复造轮子多累。

**Comment by cipchk** [comment]
[login](https://cipchk.github.io/ng-alain/#/login)

**Comment by maplye** [comment]
I register another account, and login, but the sidebar's user information don't change?

**Comment by cipchk** [comment]
@maplye  `ng-alain` no any backend service.
