### ISSUE TITLE
最新版0.5.0-rc.5

### ISSUE THREAD

**Issue by jiankian** [ng-alain/ng-alain#160]
ng serve --open报错。好几个版本都是不能跑，不知道什么情况(⊙o⊙)哦
<img width="570" alt="qq20180102-141027 2x" src="https://user-images.githubusercontent.com/9036838/34475400-bdb2b0da-efc6-11e7-9ee1-8b7f914e614a.png">

**Comment by cipchk** [comment]
重新获取，或者自行安装 [xlsx](https://github.com/cipchk/ng-alain/blob/master/package.json#L109)
