### ISSUE TITLE
reuse-tab组件加入刷新能力

### ISSUE THREAD

**Issue by Anberm** [ng-alain/ng-alain#1601]
reuse-tab 是一个充满设计思想的组件之一，它解决了我司复杂中台多tab切换依赖于iframe痛点，所以在ng-antd-design与ng-alain开始之初，我司就一直跟进使用与相应改造，但是 reuse-tab一直缺少刷新能力，这在tab页签模式里面应该是个常用的功能，不知卡色怎么看待这个功能？

**Comment by cipchk** [comment]
主要还是涉及两方面，一是已经缓存的可以做到刷新，但是未缓存的要刷新就必须额外的组件处理这就是比较麻烦的地方。

**Comment by Anberm** [comment]
我这里用了个方式处理这个事情，[reload刷新](https://github.com/Anberm/delon/commit/2985b38c696ec5f387482520f4fb8dd1ec456efa)

**Comment by cipchk** [comment]
重置路由倒也是一个不错的思路，可以试一下。虽然他会重置整个路由目标组件。

你可以多测试一下，如果可行，我也一并加进来。

**Comment by Anberm** [comment]
嗯，0.6.0 到现在两年多使用下来，倒没什么问题
