### ISSUE TITLE
se 的 required 属性不能自动根据表单元素是否有 RequiredValidator 显示 * 号

### ISSUE THREAD

**Issue by tang-butian** [ng-alain/ng-alain#1602]
- ng-alain version: 9.0.0
- Angular version: 9.1.0

## 【必填项】重现链接，Reproduction link

https://stackblitz.com/edit/ng-alain-setup-os53yy

**Comment by cipchk** [comment]
`Validators.required` 是一个静态方法，Reactive form 无法获取到是不是 `required` 操作，可以手动增加 `required`，例如：

```diff
- <input nz-input formControlName="number" />
+ <input nz-input formControlName="number" required />
```
