### ISSUE TITLE
怎么才能让 se 显示 一行 五列

### ISSUE THREAD

**Issue by tang-butian** [ng-alain/ng-alain#1606]
现在做列表搜索的时候很尴尬，一行四列输入框显得太长，一行六列又显得太短；虽然提供了 nzLayout: inline 模式，但是如果搜索字段一多（超过一行）就会出现不对齐的情况，会显得页面很乱，不够美观；所以想问下有什么办法可以让 se 支持一行五列？？

**Comment by cipchk** [comment]
`se` 默认会根据 [ResponsiveService](https://ng-alain.com/theme/responsive/en) 来调整响应式，你可以根据需要重置这个行为。

**Comment by tang-butian** [comment]
@cipchk  但是没办法设置 五列，只能 4列 或者 6列
