### ISSUE TITLE
reuse-tab路由复用不生效，没有出现tabs选项卡

### ISSUE THREAD

**Issue by duoduoObama** [ng-alain/ng-alain#1609]
- ng-alain version: 9.0.0
- Angular version: 9.1.3

## 【必填项】重现链接，Reproduction link

![image](https://user-images.githubusercontent.com/30836806/80500298-9cffbd80-89a0-11ea-82df-5cc98d87fbc2.png)
![image](https://user-images.githubusercontent.com/30836806/80500359-b0ab2400-89a0-11ea-8682-90b12ad89e04.png)
![Uploading image.png…]()

**Comment by cipchk** [comment]
https://github.com/ng-alain/ng-alain/blob/master/src/app/global-config.module.ts#L34
