### ISSUE TITLE
按照文档升级到9.0后运行异常

### ISSUE THREAD

**Issue by Loongle** [ng-alain/ng-alain#1614]
![image](https://user-images.githubusercontent.com/7290992/80621876-87f75d00-8a7a-11ea-8285-7729348110d7.png)

按照文档进行对包的更新，删除了Package-lock.json 和 node_modules. 
npm install 完成后出错了

**Comment by cipchk** [comment]
G4 升级至 4.0，不再需要 `angular.json` 的 `scripts` 节点引用所有 G2 相关的依赖包，直接移除就行了。
