### ISSUE TITLE
ng-alain-ms license question

### ISSUE THREAD

**Issue by ChangYinShung** [ng-alain/ng-alain#1617]
抱歉,這問題應該用信箱發問 
我們這邊使用gmail ,我們公司信箱,無法聯絡到 qq信箱(cipchk@qq.com)

我這邊的問題是
1.這裡打算建置系統(後台框架:https://abp.io )，前台會使用 ng-alain-ms 樣板並打算以Open Source 方式公開於 GitHub 上(您的程式碼不會公開在網路上(打包成packages)，只會公開我們的程式)，請問我需要購買那個 License ?

2.我們聯繫的方式 
```json
further0507@gmail.com
yinchang0626@gmail.com
service@furthersoftware.com.tw
```

3.請問您那邊有其他聯絡方式嗎?

**Comment by cipchk** [comment]
目前授权只有两类：标准与扩展，前者与后者唯一区别是：不支持二次销售。这两种每个 licence 都只针对一个项目。

可联系：cipchk@gmail.com
