### ISSUE TITLE
nz-tree-select组件不可用

### ISSUE THREAD

**Issue by cheneyjuu** [ng-alain/ng-alain#1618]
- ng-alain version: 9.0.1
- Angular version: 9.1.4

以下是编辑器报错：
![image](https://user-images.githubusercontent.com/1205964/80808610-7a64e300-8bf2-11ea-9faa-30e65c0e5153.png)

以下是编译报错：
![image](https://user-images.githubusercontent.com/1205964/80808679-99fc0b80-8bf2-11ea-825f-bf00b32890d8.png)

**Comment by cheneyjuu** [comment]
同样的代码，在以下版本工作正常：

* ng-alain version: 8.9.0
* Angular version: 8.1.1

**Comment by cipchk** [comment]
应该是缺少 `nz-tree-select` 模块的导入，`9.x` 只支持按需导入 。

**Comment by cheneyjuu** [comment]
> 应该是缺少 `nz-tree-select` 模块的导入，`9.x` 只支持按需导入 。

谢谢！
