### ISSUE TITLE
ST 扩展后里面包含一个子ST,子ST里的 统计列的边框出不来

### ISSUE THREAD

**Issue by tang-butian** [ng-alain/ng-alain#1619]
- ng-alain version: 9.1.0
- Angular version: 9.Y.Z

## 【必填项】重现链接，Reproduction link
https://ng-alain-setup-qx37x6.stackblitz.io

## 重现步骤，Steps to reproduce
展开后子ST里的统计列下边框出不来
![image](https://user-images.githubusercontent.com/27254047/80852244-af585080-8c59-11ea-872d-eaac1a1e6995.png)

**Comment by cipchk** [comment]
这是因为 `nz-table` 没有考虑到只有一个行的情况下，正常情况下每一行是有两个 `<tr></tr><tr></tr>` 组成的，后者为 `nzExpand` 专用。

因此，对于在 `body` 自己新增的话，只能在再一行下去就成：

```diff

          <tr >
            <td>合计</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            
            
          </tr>
+         <tr></tr>
```

虽然不好，但是我还是强制修复这类情况吧。
