### ISSUE TITLE
新生成项目, 选择是否带i18n的问题

### ISSUE THREAD

**Issue by yuuuxt** [ng-alain/ng-alain#1620]
- ng-alain version: 9.1.0
- Angular version: X.Y.Z

1. 生成新项目, 如选择带i18n, layout.module缺少
`import { HeaderI18nComponent } from './default/header/components/i18n.component';`

2. 新生成项目, 如选择不带i18n(默认), translate管道导致报错

**Comment by cipchk** [comment]
@yuuuxt 如果不带 i18n 的确是无法使用 `translate`，这是合理的，`translate` 属于 i18n 的一部分。

**Comment by yuuuxt** [comment]
> 
> 
> @yuuuxt 如果不带 i18n 的确是无法使用 `translate`，这是合理的，`translate` 属于 i18n 的一部分。

了解, 我是想表达这两个选项都不能直接跑通项目的意思

**Comment by cipchk** [comment]
@yuuuxt 针对缺少引入的部分，你可以先手动引入 `HeaderI18nComponent`，应该就可以跑起来了。

**Comment by yuuuxt** [comment]
> 
> 
> @yuuuxt 针对缺少引入的部分，你可以先手动引入 `HeaderI18nComponent`，应该就可以跑起来了。

是的, 已经跑起来了. 谢谢!
