### ISSUE TITLE
ng update 升级到9，新增的global.module文件和st-widget内容是一样的

### ISSUE THREAD

**Issue by zmzimpl** [ng-alain/ng-alain#1623]
- ng-alain version: 9.1.0
- Angular version: 9.1.4

## 重现步骤，Steps to reproduce
通过ng update 命令升级，就可重现此错误

**Comment by cipchk** [comment]
我这里无法重现，能否提供更加明细的信息。

**Comment by zmzimpl** [comment]
> 我这里无法重现，能否提供更加明细的信息。

![image](https://user-images.githubusercontent.com/27490895/80908782-579f0f80-8d55-11ea-9719-b4fec32fdf72.png)

**Comment by cipchk** [comment]
这是已知bug，应该已经修复了，你再确认一下你的版本号。

**Comment by zmzimpl** [comment]
> 这是已知bug，应该已经修复了，你再确认一下你的版本号。

版本号没问题，9.1.0，从8.9.2升上来的

**Comment by cipchk** [comment]
你直接复制 [st-widget.module.ts](https://github.com/ng-alain/ng-alain/blob/master/src/app/shared/st-widget/st-widget.module.ts) 应该就可以解决了。

**Comment by zmzimpl** [comment]
> 你直接复制 [st-widget.module.ts](https://github.com/ng-alain/ng-alain/blob/master/src/app/shared/st-widget/st-widget.module.ts) 应该就可以解决了。

主要是global.config.module的东西，我从alain的模板里拷了一份稍微修改下，现在已经可以了，多谢~

**Comment by wlclass** [comment]
今天将一个项目也遇到这样的问题。 最后复制文件内容解决的。 
升级时，全程使用用的ng update ***
