### ISSUE TITLE
ms 主题 紧凑模式显示异常

### ISSUE THREAD

**Issue by liweitao92** [ng-alain/ng-alain#1625]
- Angular version: 9.x

## 重现步骤，Steps to reproduce
![image](https://user-images.githubusercontent.com/30191996/81035401-5bee3880-8ecd-11ea-9174-8f47f49f1d66.png)

使用zorro 的紧凑主题，菜单图标显示异常

**Comment by cipchk** [comment]
@liweitao92 我无法重现这种情况，这是我使用紧凑主题后的效果。

![image](https://user-images.githubusercontent.com/2987467/81037129-43cde780-8ed4-11ea-8534-de900dc2a63c.png)

**Comment by liweitao92** [comment]
![image](https://user-images.githubusercontent.com/30191996/81037507-8cd26b80-8ed5-11ea-8be6-5fd76a07d06c.png)
这是我重新下载的ms版本，同样显示的是不对的，是window电脑的问题？

**Comment by cipchk** [comment]
@liweitao92 是否方便加我的 Q 94458893
