### ISSUE TITLE
8-to-9 升级 ng-alain 9.0 版本报错

### ISSUE THREAD

**Issue by xinjie-just** [ng-alain/ng-alain#1628]
按照顺序升级完 angular 9.1.X, ng-zorro-anntd 9.1.0 和 ng-alain 9.1.0 后，重新安装依赖，然后启动项目（npm run start）提示如下：

WARNING in Entry point '@delon/util' contains deep imports into '/Users/lixinjie/Desktop/workspace/intelligent-robot-MP/node_modules/ng-zorro-antd/date-picker/standard-types'. This is probably not a problem, but may cause the compilation of entry points to be out of order.

ERROR in The target entry-point "@delon/theme" has missing dependencies:
 - date-fns/format
 - date-fns/formatDistanceToNow
 - @angular/cdk/overlay
 - @ant-design/icons-angular/icons

package.json 如下：

{
  "name": "intelligent-robot-management",
  "version": "2.0.0",
  "scripts": {
    "ng": "ng",
    "start": "npm run color-less && ng s -o",
    "build": "npm run color-less && node --max_old_space_size=5120 ./node_modules/@angular/cli/bin/ng build --prod",
    "test": "ng test",
    "lint": "npm run lint:ts && npm run lint:style",
    "e2e": "ng e2e",
    "analyze": "npm run color-less && node --max_old_space_size=5120 ./node_modules/@angular/cli/bin/ng build --prod --stats-json",
    "test-coverage": "ng test --code-coverage --watch=false",
    "color-less": "node scripts/color-less.js",
    "icon": "ng g ng-alain:plugin icon",
    "lint:ts": "ng lint --fix",
    "lint:style": "stylelint \"src/**/*.less\" --syntax less --fix",
    "lint-staged": "lint-staged",
    "tslint-check": "tslint-config-prettier-check ./tslint.json",
    "hmr": "ng serve -c=hmr"
  },
  "private": true,
  "dependencies": {
    "@angular-devkit/schematics": "^9.1.4",
    "@angular/animations": "~9.1.4",
    "@angular/common": "~9.1.4",
    "@angular/compiler": "~9.1.4",
    "@angular/core": "~9.1.4",
    "@angular/forms": "~9.1.4",
    "@angular/platform-browser": "~9.1.4",
    "@angular/platform-browser-dynamic": "~9.1.4",
    "@angular/router": "~9.1.4",
    "@delon/abc": "^9.1.0",
    "@delon/acl": "^9.1.0",
    "@delon/auth": "^9.1.0",
    "@delon/cache": "^9.1.0",
    "@delon/chart": "^9.1.0",
    "@delon/form": "^9.1.0",
    "@delon/mock": "^9.1.0",
    "@delon/theme": "^9.1.0",
    "@delon/util": "^9.1.0",
    "@ngx-translate/core": "^12.1.2",
    "@ngx-translate/http-loader": "^4.0.0",
    "ajv": "^6.12.0",
    "jquery": "^3.4.1",
    "lodash": "^4.17.15",
    "ng-alain": "^9.1.0",
    "ng-zorro-antd": "^9.1.0",
    "rxjs": "~6.5.5",
    "screenfull": "^5.0.2",
    "ts-md5": "^1.2.7",
    "tslib": "^1.10.0",
    "zone.js": "~0.10.3",
    "ngx-tinymce": "^9.0.0",
    "ngx-ueditor": "^9.0.0"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.901.4",
    "@angular/cli": "~9.1.4",
    "@angular/compiler-cli": "~9.1.4",
    "@angular/language-service": "~9.1.4",
    "@angularclass/hmr": "^2.1.3",
    "@delon/testing": "^8.8.0",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "@typescript-eslint/eslint-plugin": "^2.15.0",
    "@typescript-eslint/parser": "^2.15.0",
    "antd-theme-generator": "^1.1.9",
    "codelyzer": "^5.0.0",
    "eslint": "^6.8.0",
    "husky": "^4.2.3",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "less-bundle-promise": "^1.0.7",
    "lint-staged": "^10.1.2",
    "ng-alain-codelyzer": "^0.0.1",
    "prettier": "^2.0.4",
    "prettier-stylelint": "^0.4.2",
    "protractor": "~5.4.0",
    "stylelint": "^13.3.1",
    "stylelint-config-prettier": "^8.0.1",
    "stylelint-config-rational-order": "^0.1.2",
    "stylelint-config-standard": "^20.0.0",
    "stylelint-declaration-block-no-ignored-properties": "^2.3.0",
    "stylelint-order": "^4.0.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "tslint-config-prettier": "^1.18.0",
    "tslint-language-service": "^0.9.9",
    "typescript": "^3.8.3",
    "@types/jszip": "^3.1.7",
    "webpack-bundle-analyzer": "^3.6.1",
    "xlsx": "^0.15.6"
  },
  "husky": {
    "hooks": {
      "pre-commit": "npm run lint-staged"
    }
  }
}

**Comment by cipchk** [comment]
删除项目下 node_modules、package-lock.json 或 yarn.lock 文件
