### ISSUE TITLE
使用 ng-build 打包下来的 vendor.bundle.js 非常大

### ISSUE THREAD

**Issue by a532533603** [ng-alain/ng-alain#163]
下载的 基础版，没做任何功能，直接使用 ng build 打包。看了下 vendor.bundle.js 有 6M 多，加载很慢，不知道正常不正常
![image](https://user-images.githubusercontent.com/13478101/34508355-3d6233ac-f079-11e7-8f55-94bcd800a560.png)

**Comment by cipchk** [comment]
使用 `npm run build` 打包，或 `ng build --prod --build-optimizer`
配合web服务器的gzip。
