### ISSUE TITLE
sf 内 upload 组件有两个小问题

### ISSUE THREAD

**Issue by lengsehuoyan** [ng-alain/ng-alain#1631]
- ng-alain version: 8.9.0
- Angular version: 8.2.3

sf 内 upload 组件有两个小问题
1. limitFileCount 没有生效
2. 被required的情况下, firstVisual 设置为false, 也会立即提示'必填项'提示.

**Comment by lengsehuoyan** [comment]
https://stackblitz.com/edit/angular-znld6n @cipchk 我这里只能复现第二个问题。

**Comment by bluesiboy** [comment]
感谢反馈，不再维护旧版本，你可以自己维护此部件。

**Comment by cipchk** [comment]
我在最新版本下无法重现类似问题。关闭此 issues，如果有其他细节请重新打开或发布新的 issues。
