### ISSUE TITLE
ST组件 不支持nzTableLayout和nzEllipsis属性

### ISSUE THREAD

**Issue by liqi007** [ng-alain/ng-alain#1636]
ng-alain version: 9.2.1
Angular version: 9.1.4

ng-zorro-antd/table最新版9.1.0新增nzTableLayout和nzEllipsis属性，如不设置nzTableLayout，在特殊情况下会超出屏幕宽度；

**Comment by cipchk** [comment]
尝试使用 `widthMode`，效果与 `nzTableLayout` 一致。

**Comment by neesonqk** [comment]
@cipchk 
如果 配置了`[virtualScroll]=true [scroll]="{ x: '1650px', y: '350px' }"` 使用widthMode则不起作用

设置以上后下面的信息丢失造成不起作用
```
.ant-table-fixed {
    table-layout: fixed;
}
```

**Comment by cipchk** [comment]
@neesonqk 能否提供一个重现示例。

**Comment by liqi007** [comment]
@cipchk 在ng-alain8时，我们为了解决st在不设列宽时，也能保持超长字符串不换行是这样写的
https://stackblitz.com/edit/angular-cmvzms?file=src/app/app.component.ts

但是当升级到9时由于ant对table的修改，导致table-layout在不设置nzTableLayout 时是auto，造成table超出屏幕。
![image](https://user-images.githubusercontent.com/26212392/82007745-8f834c80-969d-11ea-8aa1-e59d266a81d5.png)

现在我们的折中办法是修改样式.ant-table-content：table-layout: fixed !important;来解决。
.ant-table {
  &-content {
    table {
      table-layout: fixed !important;
    }
  }
}
![image](https://user-images.githubusercontent.com/26212392/82007897-f6086a80-969d-11ea-9ed9-16bd1e1d80ed.png)
