### ISSUE TITLE
Project start error（Module not found: Error: Can't resolve 'jszip'）

### ISSUE THREAD

**Issue by colorful-app** [ng-alain/ng-alain#164]
![image](https://user-images.githubusercontent.com/14008067/34508410-f0037ee4-f079-11e7-8da2-1caeab09e697.png)

**Comment by colorful-app** [comment]
ERROR in ./node_modules/@delon/abc/zip/zip.service.js
Module not found: Error: Can't resolve 'jszip' in 'E:\workspace\Angular\cipchk\ng-alain\node_modules\@delon\abc\zip'
resolve 'jszip' in 'E:\workspace\Angular\cipchk\ng-alain\node_modules\@delon\abc\zip'
  Parsed request is a module
  using description file: E:\workspace\Angular\cipchk\ng-alain\node_modules\@delon\abc\package.json (relative path: ./zip)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: E:\workspace\Angular\cipchk\ng-alain\node_modules\@delon\abc\package.json (relative path: ./zip)
    resolve as module
      E:\workspace\Angular\cipchk\ng-alain\node_modules\@delon\abc\zip\node_modules doesn't exist or is not a directory
      E:\workspace\Angular\cipchk\ng-alain\node_modules\@delon\abc\node_modules doesn't exist or is not a directory
      E:\workspace\Angular\cipchk\ng-alain\node_modules\@delon\node_modules doesn't exist or is not a directory
      E:\workspace\Angular\cipchk\ng-alain\node_modules\node_modules doesn't exist or is not a directory
      E:\workspace\Angular\cipchk\node_modules doesn't exist or is not a directory
      E:\workspace\Angular\node_modules doesn't exist or is not a directory
      E:\workspace\node_modules doesn't exist or is not a directory
      E:\node_modules doesn't exist or is not a directory
      looking for modules in E:\workspace\Angular\cipchk\ng-alain\node_modules
        using description file: E:\workspace\Angular\cipchk\ng-alain\package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: E:\workspace\Angular\cipchk\ng-alain\package.json (relative path: ./node_modules)
          using description file: E:\workspace\Angular\cipchk\ng-alain\package.json (relative path: ./node_modules/jszip)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              E:\workspace\Angular\cipchk\ng-alain\node_modules\jszip doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              E:\workspace\Angular\cipchk\ng-alain\node_modules\jszip.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              E:\workspace\Angular\cipchk\ng-alain\node_modules\jszip.js doesn't exist
            as directory
              E:\workspace\Angular\cipchk\ng-alain\node_modules\jszip doesn't exist
      looking for modules in E:\workspace\Angular\cipchk\ng-alain\node_modules
        using description file: E:\workspace\Angular\cipchk\ng-alain\package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: E:\workspace\Angular\cipchk\ng-alain\package.json (relative path: ./node_modules)
          using description file: E:\workspace\Angular\cipchk\ng-alain\package.json (relative path: ./node_modules/jszip)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              E:\workspace\Angular\cipchk\ng-alain\node_modules\jszip doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              E:\workspace\Angular\cipchk\ng-alain\node_modules\jszip.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              E:\workspace\Angular\cipchk\ng-alain\node_modules\jszip.js doesn't exist
            as directory
              E:\workspace\Angular\cipchk\ng-alain\node_modules\jszip doesn't exist
      looking for modules in E:\workspace\Angular\cipchk\ng-alain\src
        using description file: E:\workspace\Angular\cipchk\ng-alain\package.json (relative path: ./src)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: E:\workspace\Angular\cipchk\ng-alain\package.json (relative path: ./src)
          using description file: E:\workspace\Angular\cipchk\ng-alain\package.json (relative path: ./src/jszip)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              E:\workspace\Angular\cipchk\ng-alain\src\jszip doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              E:\workspace\Angular\cipchk\ng-alain\src\jszip.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              E:\workspace\Angular\cipchk\ng-alain\src\jszip.js doesn't exist
            as directory
              E:\workspace\Angular\cipchk\ng-alain\src\jszip doesn't exist
      looking for modules in E:\workspace\Angular\cipchk\ng-alain\src
        using description file: E:\workspace\Angular\cipchk\ng-alain\package.json (relative path: ./src)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: E:\workspace\Angular\cipchk\ng-alain\package.json (relative path: ./src)
          using description file: E:\workspace\Angular\cipchk\ng-alain\package.json (relative path: ./src/jszip)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              E:\workspace\Angular\cipchk\ng-alain\src\jszip doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              E:\workspace\Angular\cipchk\ng-alain\src\jszip.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              E:\workspace\Angular\cipchk\ng-alain\src\jszip.js doesn't exist
            as directory
              E:\workspace\Angular\cipchk\ng-alain\src\jszip doesn't exist
[E:\workspace\Angular\cipchk\ng-alain\node_modules\@delon\abc\zip\node_modules]
[E:\workspace\Angular\cipchk\ng-alain\node_modules\@delon\abc\node_modules]
[E:\workspace\Angular\cipchk\ng-alain\node_modules\@delon\node_modules]
[E:\workspace\Angular\cipchk\ng-alain\node_modules\node_modules]
[E:\workspace\Angular\cipchk\node_modules]
[E:\workspace\Angular\node_modules]
[E:\workspace\node_modules]
[E:\node_modules]
[E:\workspace\Angular\cipchk\ng-alain\node_modules\jszip]
[E:\workspace\Angular\cipchk\ng-alain\node_modules\jszip.ts]
[E:\workspace\Angular\cipchk\ng-alain\node_modules\jszip.js]
[E:\workspace\Angular\cipchk\ng-alain\node_modules\jszip]
[E:\workspace\Angular\cipchk\ng-alain\node_modules\jszip]
[E:\workspace\Angular\cipchk\ng-alain\node_modules\jszip.ts]
[E:\workspace\Angular\cipchk\ng-alain\node_modules\jszip.js]
[E:\workspace\Angular\cipchk\ng-alain\node_modules\jszip]
[E:\workspace\Angular\cipchk\ng-alain\src\jszip]
[E:\workspace\Angular\cipchk\ng-alain\src\jszip.ts]
[E:\workspace\Angular\cipchk\ng-alain\src\jszip.js]
[E:\workspace\Angular\cipchk\ng-alain\src\jszip]
[E:\workspace\Angular\cipchk\ng-alain\src\jszip]
[E:\workspace\Angular\cipchk\ng-alain\src\jszip.ts]
[E:\workspace\Angular\cipchk\ng-alain\src\jszip.js]
[E:\workspace\Angular\cipchk\ng-alain\src\jszip]
 @ ./node_modules/@delon/abc/zip/zip.service.js 3:0-31
 @ ./node_modules/@delon/abc/zip/index.js
 @ ./node_modules/@delon/abc/index.js
 @ ./src/app/shared/shared.module.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts

**Comment by cipchk** [comment]
https://github.com/cipchk/ng-alain/blob/master/package.json#L85

**Comment by colorful-app** [comment]
![image](https://user-images.githubusercontent.com/14008067/34508472-be252732-f07a-11e7-8962-e8fb2760058f.png)

Have it already

**Comment by cipchk** [comment]
trying the follow steps:

- delete `node_modules` & `package-lock.json`
- `npm i`

**Comment by colorful-app** [comment]
![image](https://user-images.githubusercontent.com/14008067/34509003-5bf1687c-f080-11e7-9c5e-5904ec6c54d4.png)
Sorry, I did not see this file（package-lock.json）！

**Comment by colorful-app** [comment]
ok @cipchk
