### ISSUE TITLE
列表横向滚动样式问题

### ISSUE THREAD

**Issue by huajian123** [ng-alain/ng-alain#1645]
- ng-alain version: 9.2.1
- Angular version: 9.1.4

## 【必填项】重现链接，Reproduction link
https://ng-alain.com/components/st/zh

## 重现步骤，Steps to reproduce
![4C8842976CFD762000F84966FED3142B](https://user-images.githubusercontent.com/31737260/81792703-fcca9c80-953a-11ea-8cd5-9638dd97cb12.jpg)
![CFDCC0896456678021DE9130CCBB5E63](https://user-images.githubusercontent.com/31737260/81792710-ffc58d00-953a-11ea-8d0d-95eda98be787.jpg)
![E1DCA625ABE9B6FA5FE9998429B72BDA](https://user-images.githubusercontent.com/31737260/81792712-ffc58d00-953a-11ea-8855-2fa52bd1529a.jpg)

如图所示，将ng-alain 官网文档上可滚动列表源码，粘贴至ng-alain示例项目，也会出现横向滚动条最后一列的样式问题

**Comment by cipchk** [comment]
@huajian123 我无法复现，并且你所指的是什么问题呢？

![image](https://user-images.githubusercontent.com/2987467/81893101-67351880-95df-11ea-89c0-514eb0a0fec6.png)

**Comment by huajian123** [comment]
我的问题是，使用横向滚动列表，拖动滚动条至最右边，会出现列表和滚动条错开的情况。我用ng-alain文档上的示例滚动表格代码，拷贝到最新的ng-alain项目中，会有这样的情况出现，并且我自己的项目中也是如此

**Comment by cipchk** [comment]
缺少重现步骤，关闭此 issues，如果有其他细节请重新打开或发布新的 issues。
