### ISSUE TITLE
has no exported member 'PanelMode'

### ISSUE THREAD

**Issue by snowchenlei** [ng-alain/ng-alain#1646]
![image](https://user-images.githubusercontent.com/26211283/81884052-6a250e80-95c9-11ea-956b-eeb4b106f9e1.png)
cli新下载的项目运行报错。
ERROR in node_modules/@delon/util/src/config/abc/date-picker.type.d.ts:2:26 - error TS2305:
node_modules/ng-zorro-antd/date-picker/standard-types"' has no exported member 'PanelMode'.

**Comment by cipchk** [comment]
暂时可以将 `ng-zorro-antd` 回退至 `9.1.1`，今天会发布修复版本。
