### ISSUE TITLE
sf中spanLabelFixed固定时，select中的option文字太长会导致组件换行

### ISSUE THREAD

**Issue by blacksola** [ng-alain/ng-alain#1647]
- ng-alain version: 9.2.2
- Angular version: 9.1.7
- ng-zorro version: 9.1.2

![image](https://user-images.githubusercontent.com/16145619/81885906-f20d1780-95cd-11ea-9edd-af91db9c6cff.png)

## 【必填项】重现链接，Reproduction link

https://stackblitz.com/edit/angular-kxmvtt

**Comment by klaokai** [comment]
修复是修复了，可是select宽度再也展不开了
![image](https://user-images.githubusercontent.com/14050993/82006474-76c56780-969a-11ea-9200-de93a5d93d36.png)
spanLabelFixed参数也没有意义了，无法实现等宽布局

**Comment by cipchk** [comment]
看是否设置了 `layout`，我看重现示例升级至 `9.2.3` 后是正常的。

**Comment by klaokai** [comment]
好的，应该是我这里设置了mode="search"的问题

**Comment by wangzhen429** [comment]
想问一下sf，屏幕缩小时，文字也是换行了，css手动设置了不换行后，但是这样缩小屏幕文字就会重叠怎么解决呢？尝试过用了xs:24, sm:24,md:12,lg:8,发现没效果，

**Comment by cipchk** [comment]
@wangzhen429 可以另起一个Issues，最好提供重现示例。
