### ISSUE TITLE
se的col=1无效

### ISSUE THREAD

**Issue by tang-butian** [ng-alain/ng-alain#1649]
- ng-alain version: 9.2.3
- Angular version: 9.Y.Z

## 【必填项】重现链接，Reproduction link
https://stackblitz.com/edit/ng-alain-setup-dp8zx7

## 重现步骤，Steps to reproduce
![image](https://user-images.githubusercontent.com/27254047/81913389-7f6a5f00-9602-11ea-8de7-aa79a2a34cc3.png)
se 设置 col = 1 时没有单独一列

**Comment by cipchk** [comment]
改成：

```html
<se-container size="compact">
  <se *ngFor="let pro of processInfo; let i = index" col="1" labelWidth="180" [label]="pro?.name">
   <div>2123333333333123</div>
  </se>
  <se col="1" labelWidth="180" label="审批顺序" *ngIf="pro?.multiSelect">{{ pro['approveUsers'] }} </se>
</se-container>
```

新增 `div` 会破坏 DOM 结构，如果非要这样也可以使用 `ng-container` 替代。
