### ISSUE TITLE
_httpClient 求教

### ISSUE THREAD

**Issue by a532533603** [ng-alain/ng-alain#165]
![image](https://user-images.githubusercontent.com/13478101/34516286-5222c918-f0b1-11e7-8f33-cb472df94105.png)
使用_httpClient 请求登录方法，故意输错账号密码，得到了401 (但是还是报了个错误)，怎么获取返回的异常 json 文本.

![image](https://user-images.githubusercontent.com/13478101/34516325-752d6846-f0b1-11e7-889a-3a584ecb37ea.png)

**Comment by cipchk** [comment]
抱歉，请提供一个重现在线示例。

**Comment by a532533603** [comment]
找到原因了。DefaultInterceptor 的拦截器拦截了请求
![image](https://user-images.githubusercontent.com/13478101/34528073-ab821e10-f0e2-11e7-8b83-5c0cfed8e287.png)
然后使用这个抛出的异常，这样就没有正常的通过 catch 获取到返回的 json 信息
