### ISSUE TITLE
st 在带有缓存（reuse-tab、nz-tabs）的情况下宽度会失效

### ISSUE THREAD

**Issue by siwting** [ng-alain/ng-alain#1651]
- ng-alain version: 9.2.3
- Angular version: 9.1.7

## 【必填项】重现链接，Reproduction link

切换之前：

![image](https://user-images.githubusercontent.com/3980989/82005182-4f20d000-9697-11ea-9b13-a607228c0995.png)

切换之后：

![image](https://user-images.githubusercontent.com/3980989/82005234-6b247180-9697-11ea-930d-ab36277f69a2.png)

**Comment by cipchk** [comment]
may be duplcated of #1636

**Comment by siwting** [comment]
点击Tab之前，是按照设定的width分配每一列宽度的

![image](https://user-images.githubusercontent.com/3980989/82015767-1fcb8c80-96b2-11ea-97b3-151082994ea7.png)



切换Tab，第二次进入这个Tab的时候，列被平均分了
![image](https://user-images.githubusercontent.com/3980989/82015697-f90d5600-96b1-11ea-96db-a434d4185431.png)

**Comment by siwting** [comment]
这是操作步骤

![CleanShot 2020-05-15 at 14 02 41](https://user-images.githubusercontent.com/3980989/82017066-e1839c80-96b4-11ea-8152-65f89ad07414.gif)

**Comment by 694551594** [comment]
很可能是ng-zorro的bug。https://github.com/NG-ZORRO/ng-zorro-antd/issues/5160

**Comment by siwting** [comment]
@694551594 这个情况，只有表格有横向滚动条的时候，才发生

**Comment by 694551594** [comment]
@siwting 是的，我也有这个问题。我的解决办法是，让他隐藏一下，然后再显示，这样表格的宽度就是初始的宽度了。但是这样做相当于表格恢复到了初始状态，无法保留当时的状态。
`  this.visiable = !this.visiable;
        setTimeout(() => { this.visiable = !this.visiable }, 100);`

此外，可能也是这个BUG引起的，加了横向滚动条的列无法拖动。具体可以看：https://github.com/NG-ZORRO/ng-zorro-antd/issues/5167

**Comment by 694551594** [comment]
https://github.com/NG-ZORRO/ng-zorro-antd/issues/5370

**Comment by 694551594** [comment]
经测试，NG-ZORRO - 9.2.0 已经修正了此BUG。
https://github.com/NG-ZORRO/ng-zorro-antd/releases/tag/9.2.0
