### ISSUE TITLE
custom-column组件无法选择新的列

### ISSUE THREAD

**Issue by amoycode** [ng-alain/ng-alain#1654]
delon version: 9.2.4

custom-column组件反选列是没问题的,一旦勾选新的列则**列表渲染错误,控制台报错**.

![image](https://user-images.githubusercontent.com/18238708/82050720-3a6e2780-96eb-11ea-8ff6-237c583bc28d.png)
![image](https://user-images.githubusercontent.com/18238708/82050763-4b1e9d80-96eb-11ea-9f38-267d4c44f9a4.png)

**Comment by cipchk** [comment]
长时间无重现，暂时关闭。
