### ISSUE TITLE
表格的strict宽度模式（widthMode）不起作用

### ISSUE THREAD

**Issue by siwting** [ng-alain/ng-alain#1656]
- ng-alain version: 9.2.4
- Angular version: 9.1.7

## 【必填项】重现链接，Reproduction link

![image](https://user-images.githubusercontent.com/3980989/82133296-127ee100-981d-11ea-8c4f-290f9eca5517.png)

效果：

![image](https://user-images.githubusercontent.com/3980989/82133297-1f033980-981d-11ea-87cf-e0d7a641f35c.png)

**Comment by cipchk** [comment]
[DEMO](https://ng-alain.com/components/st/en#components-st-basic) 中是正常的，麻烦提供一个重现示例。
