### ISSUE TITLE
ng build --prod fail

### ISSUE THREAD

**Issue by apphost** [ng-alain/ng-alain#166]
## Bug Report or Feature Request (mark with an `x`)
<pre><code>
[x] Bug report -> please search issues before submitting
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

run `npm run build`

## Minimal reproduction of the problem with instructions

`ERROR in ngx-ueditor\index.ts(11,2): Error during template compile of 'UEditorModule'
  Function expressions are not supported in decorators in 'NgModule'
    'NgModule' contains the error at @angular\core\core.ts(194,31)
      Consider changing the function expression into an exported function.
`

## Environment

<pre><code>
Angular version: 5.1.2

delon version: 0.5.0-rc.7

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX

For Tooling issues:
- Node version: XX  
- Platform:  

Others:

_                      _                 ____ _     ___
/ \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
/ △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
/ ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
|___/

Angular CLI: 1.6.3
Node: 9.2.0
OS: win32 x64
Angular: 5.1.2
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 5.0.3
@angular/cli: 1.6.3
@angular-devkit/build-optimizer: 0.0.36
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.42
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.3
@schematics/angular: 0.1.11
@schematics/schematics: 0.0.11
typescript: 2.5.3
webpack-bundle-analyzer: 2.9.1
webpack: 3.10.0

</code></pre>

**Comment by cipchk** [comment]
trying the follow steps:

- delete `node_modules` & `package-lock.json`
- `npm i`

**Comment by apphost** [comment]
It's worked!
I used `cnpm install` before，and it faild.
