### ISSUE TITLE
antd-theme-generator: Cannot read property 'slice' of undefined

### ISSUE THREAD

**Issue by lizhigangd** [ng-alain/ng-alain#1664]
🚨 Issues 是用于BUG、Feature、进度追踪 🚨
🚨 The issue tracker is not for questions 🚨

如果有任何问题，可在以下方式获得答案：

- https://ng-alain.com/
- QQ Group：316911865
- https://segmentfault.com/t/ng-alain

**Comment by lizhigangd** [comment]
angular/cli 8.3.21
nodejs  12.14.0

错误信息：
    > node scripts/color-less.js

error TypeError: Cannot read property 'slice' of undefined
    at generateTheme (D:\GitLab\SpringSowing\EClinic_Client\node_modules\antd-theme-generator\index.js:337:46)
    at Object.<anonymous> (D:\GitLab\SpringSowing\EClinic_Client\scripts\color-less.js:49:1)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11
Theme generated successfully

**Comment by cipchk** [comment]
受 [antd-theme-generator issues 42](https://github.com/mzohaibqc/antd-theme-generator/issues/42) 影响，先把 `antd-theme-generator` 固定为 `1.2.2` 版本。

```bash
# yarn
yarn add antd-theme-generator@1.2.2
# npm
npm install --save antd-theme-generator@1.2.2
```

**Comment by wenpengpeng** [comment]
> ```shell
> yarn add antd-theme-generator@1.2.2
> ```

按照该方法slice这个错误是不报了   但是nz-steps使用会有样式错乱问题（我在群里提到过），ng-alain版本是8.9.3

**Comment by lizhigangd** [comment]
没有使用过nz-steps，目前无影响，刚加群。

**Comment by zmzimpl** [comment]
> 先把 `antd-theme-generator` 固定为 `1.2.2` 版本。

把`antd-theme-generator`固定为1.2.2之后，之前没问题，前两天install的时候发现出现了循环依赖的错误，类似报错信息如[issues](https://github.com/npm/cli/issues/1918)，将版本改为1.2.6之后，可以正常安装成功，但是在启动的时候报了错误：`Cannot read property 'slice' of undefined`，如下图
![image](https://user-images.githubusercontent.com/27490895/96391878-d77a4280-11ec-11eb-822e-20973b691197.png)
![image](https://user-images.githubusercontent.com/27490895/96391945-0bedfe80-11ed-11eb-8fde-a6b840d46f08.png)
环境：
- alain: 9.4.0
- zorro: 9.3.0
- ng: 9.1.4

**Comment by zmzimpl** [comment]
请问是否有最小变动的解决方案？

**Comment by cipchk** [comment]
@zmzimpl 升级至 [ng-alain-plugin-theme](https://github.com/ng-alain/ng-alain/blob/master/package.json#L38) 的写法，正因为 `antd-theme-generator` 带来许多 BUG。

**Comment by zmzimpl** [comment]
> @zmzimpl 升级至 [ng-alain-plugin-theme](https://github.com/ng-alain/ng-alain/blob/master/package.json#L38) 的写法，正因为 `antd-theme-generator` 带来许多 BUG。

我将`alain`的版本固定在`9.4.0`，以及`antd-theme-generator`版本固定在1.2.2，可以正常install了，想来先前install出现的循环依赖是因为原先的`alain`版本我设置为了`^9.4.0`,实际安装了`9,5,5`的，才导致的问题。
请问改成 `antd-theme-generator` 写法，需不需要升级到 10？因为在收尾阶段，不敢直接升到10

**Comment by cipchk** [comment]
@zmzimpl 不需要，它是一个 Node 命令行，不受 angular 版本的限制。你可以切一个新分支出来试一下 https://github.com/ng-alain/plugin-theme。

**Comment by zmzimpl** [comment]
> @zmzimpl 不需要，它是一个 Node 命令行，不受 angular 版本的限制。你可以切一个新分支出来试一下 https://github.com/ng-alain/plugin-theme

我尝试升级至 ng-alain-plugin-theme，发现需要在根目录加的 ng-alain.json 文件里面的 `"$schema": "./node_modules/ng-alain/schema.json"`会有找不到文件的提示，这个路径的文件是否是在`ng-alian@10.0.0`之后才引入的？这样的话似乎必须同步将项目升级至10才行了

**Comment by cipchk** [comment]
@zmzimpl 也没关系，不需要 这个也行，因为他只是为了校验而已。
