### ISSUE TITLE
Routing switches wait a long time

### ISSUE THREAD

**Issue by lyc152** [ng-alain/ng-alain#167]
Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX

  我在点击左侧菜单进行切换路由时，发现在等待新页面加载等待的时间很长，我在 ng-alain官网上做测试的时候发现也有类似的问题，请问大家有没有碰到这个问题，有什么好的解决方案吗

**Comment by cipchk** [comment]
能否提供更具体一点重现步骤吗？

**Comment by lyc152** [comment]
sockjs.js:1679 WebSocket connection to 'ws://sockjs-node/733/ohqrhfte/websocket' failed: Error during WebSocket handshake: Unexpected response code: 400
综合考虑:
1. 我这边网络问题
2. 跟路由的 loadChildren 有关系

**Comment by lyc152** [comment]
经过测试发现在本地开发 npm run start 时间是比较长的， 主要是没压缩，js比较大
![image](https://user-images.githubusercontent.com/4793878/34760110-6666484c-f619-11e7-82a3-492f637440fa.png)

在 npm run build 就比较快了，
在本地不影响调试的情况下有什么好的方案呢
