### ISSUE TITLE
nameSeparator not working with singleSort in st when global configed

### ISSUE THREAD

**Issue by selegiline** [ng-alain/ng-alain#1670]
- ng-alain version: 9.1.2
- Angular version: 9.3.0

## 【必填项】重现链接，Reproduction link

- Stackblitz模板：https://stackblitz.com/edit/ng-alain-setup-6xpxbw?file=src%2Fapp%2Fglobal-config.module.ts
- 截图：可通过拖拉图像文件到 Github 文本框可直接上传

![`_$T1J)QU3OPJ8CB~R73_ F](https://user-images.githubusercontent.com/31548229/82762206-4b791000-9e32-11ea-9166-11ee95dd546d.png)
![3 Q)$_LJB_@B 1DL(EC_{XS](https://user-images.githubusercontent.com/31548229/82762226-69467500-9e32-11ea-8236-6e1ccef3b3e6.png)
![YH5C{70_8_IT$A@XR{%Q)IK](https://user-images.githubusercontent.com/31548229/82762243-7c594500-9e32-11ea-925f-c04b103d0109.png)
![~CKT5UJ)AFW 2U4I~(~09_5](https://user-images.githubusercontent.com/31548229/82762253-85e2ad00-9e32-11ea-904a-189ccc94185c.png)

**Comment by cipchk** [comment]
尝试升级至最新版本，以下是预期的：
https://stackblitz.com/edit/ng-alain-setup-kttzn1?file=_mock/user.ts
