### ISSUE TITLE
9.3 用了紧凑主题后， se 的表单验证没用了， 输入框都不变红了

### ISSUE THREAD

**Issue by tang-butian** [ng-alain/ng-alain#1677]
- ng-alain version: 9.3.0
- Angular version: X.Y.Z

## 【必填项】重现链接，Reproduction link

Stackblitz模板没办法配置紧凑主题环境

**Comment by tang-butian** [comment]
![image](https://user-images.githubusercontent.com/27254047/82873520-34880a00-9f67-11ea-9f5d-375a9c50eedf.png)
加了个这个主题引用报错 @cipchk

**Comment by cipchk** [comment]
参考 [stackblitz模板](https://stackblitz.com/edit/ng-alain-setup?file=src%2Fapp%2Fapp.component.ts) 头部说明描述：

```ts
/**
 * NOTICE: This example is based on `9.x`, 8.x version please go to: https://stackblitz.com/edit/ng-alain-setup-8
 * If you want to switch the official theme, please modify `styles` path in `angular.json` file, likt this:
 * ```json
 * "node_modules/@delon/theme/{default|dark|compact}.css",
 * ```
 */
```

**Comment by tang-butian** [comment]
@cipchk 
https://stackblitz.com/edit/ng-alain-setup-u9erwc    这是重现连接，  nam 字段required  ，按以前的版本 如果没有输入，输入框是会红的，现在不会了

**Comment by cipchk** [comment]
需要设置 `error`

```diff
- <se col="4" label="姓名" [required]="true">
+ <se col="4" label="姓名" [required]="true" error="error message">
```
