### ISSUE TITLE
st里面的自定义按钮，选择抽屉。然后配置drawerOptions。配置无效

### ISSUE THREAD

**Issue by renzhuoyan0** [ng-alain/ng-alain#1679]
{
                    icon: 'edit',
                    tooltip: '编辑',
                    type: 'drawer',
                    drawer: {
                        title: '编辑',
                        component: AssetsIpEdit,
                        drawerOptions: {
                            nzHeight: '1920px',
                            nzWidth: '680px',
                            nzOffsetY: 30
                        }
                    },
                    // click: (item) => {  },
                },
输入如上抽屉配置，无效。
另外：nzTitle是有效的。

**Comment by cipchk** [comment]
`nzHeight`、`nzOffsetY` 需要指定  `nzPlacement` 为 `top` 或 `bottom` 才会生效，反之 `nzWidth`、`nzOffsetX` 必须指定为 `left` 或 `right` 才会生效。
