### ISSUE TITLE
simple-table

### ISSUE THREAD

**Issue by wgqjiayou** [ng-alain/ng-alain#168]
There are two problems:
1.After the simpleTable access back-end data, the paging function fails
2.How to use the sort function after the simpleTable gets back-end data

html code show as below:
```
<simple-table
                [url]="url"
                [columns]="header"
                [resReName]="{list: 'day' }"
                [pageSizeSelectorValues]="pageValues" [ps]="8"
                showSizeChanger showQuickJumper showTotal isPageIndexReset
></simple-table>
```
ts code show as below:
```
    url = '../../../../assets/data/line-report.json';
    header: SimpleTableColumn[] = [
        {   title: '序号',
            index: 'id',
            sorter: (a, b) => {
               return  a.id - b.id;
            }
        },
        {
            title: '名称',
            index: 'line',
            sorter: (a, b) => {
            }
            sortKey: 'line', 
            sortReName: { ascend: 'asc', descend: 'desc' }
        }
    ];
```
result:
![image](https://user-images.githubusercontent.com/34337762/34553633-927504ec-f163-11e7-95d2-7e5de04c6713.png)

**Comment by cipchk** [comment]
Please provide a full [demo](https://stackblitz.com/edit/ng-alain-setup?file=app%2Fapp.component.ts).

**Comment by wgqjiayou** [comment]
@cipchk here's my demo
[https://stackblitz.com/edit/ng-alain-setup-f58jal?file=app/app.component.ts](url)

**Comment by cipchk** [comment]
every request is random user data via `randomuser.me`;

but add `[total]="total"` in html template that fixed first question.

and,  If you need sort buttons only, set to `true`, e.g: `sorter: (a, b) => true`
