### ISSUE TITLE
[SF] SF TreeSelect组件如何获取全部节点数据？

### ISSUE THREAD

**Issue by meimosor** [ng-alain/ng-alain#1686]
您好，我在使用treeSelect组件时遇到一个问题，选择父节点后，正常情况下应该获取到这个父节点以及该父节点所有子节点的数据，但是实际获取到的只有父节点的内容，这个该怎么实现？求解，谢谢！

**Comment by cipchk** [comment]
估计没有设置 [nzCheckStrictly](https://ng.ant.design/components/tree-select/zh#nz-tree-select)、`nzMultiple` 等参数，只要有打勾的自然就可以通过 `getCheckedNodeList` 来获取已打勾的数据清单。

**Comment by meimosor** [comment]
在ng-zoro中设置nzCheckStrictly、nzMultiple参数可以实现，但是在alain的SF中怎么做，我看文档里面没有checkStricely属性

**Comment by meimosor** [comment]
> 估计没有设置 [nzCheckStrictly](https://ng.ant.design/components/tree-select/zh#nz-tree-select)、`nzMultiple` 等参数，只要有打勾的自然就可以通过 `getCheckedNodeList` 来获取已打勾的数据清单。



> 估计没有设置 [nzCheckStrictly](https://ng.ant.design/components/tree-select/zh#nz-tree-select)、`nzMultiple` 等参数，只要有打勾的自然就可以通过 `getCheckedNodeList` 来获取已打勾的数据清单。
