### ISSUE TITLE
SF中下拉菜单或多选按钮是否可以考虑增加对后端数组格式的快速处理？

### ISSUE THREAD

**Issue by xingkoo** [ng-alain/ng-alain#1688]
1、后端有时候数据会存储成`1,2,3,4,5,6,7`这样的格式。
2、前端使用下拉菜单（或多选按钮等）需要使用数组来填充值，如[1,2,3,4,5]
3、目前我是在获取数据后，split转换成数组。在提前保存前，join(',')来合并。

类似操作会经常出现，所以是否可以考虑封装一下。给ui组件增加一个预处理的选项，当打开时，会对数据自动处理？

**Comment by cipchk** [comment]
JSON Schema 有自己的严格数据类型处理，如果强制格式化成某个数据，会导致校验失败，这类业务层面的需求，个人认为并不适合成为一部分。
