### ISSUE TITLE
nz-st 设置表格高度，列表内容过长时，数据与表头将无法对齐！！！

### ISSUE THREAD

**Issue by zst20160902** [ng-alain/ng-alain#1692]
- ng-alain version: 8.9.1
- Angular version: 8.2.11

## 重现步骤，Steps to reproduce
![image](https://user-images.githubusercontent.com/40650757/83486299-7e2ea280-a4db-11ea-9418-171007430119.png)

![image](https://user-images.githubusercontent.com/40650757/83486326-8e468200-a4db-11ea-9f89-be4133554dcd.png)

![image](https://user-images.githubusercontent.com/40650757/83486383-a74f3300-a4db-11ea-99b4-97908c594e3b.png)

**Comment by cipchk** [comment]
尝试指定 `widthMode`

**Comment by zst20160902** [comment]
问题解决了， 设置了widthMode可以达到效果， 谢谢

**Comment by zst20160902** [comment]
但是如果设置了虚拟滚动， 将破坏表头与数据对齐效果。
 如果设置为truncate模式，无法将数据截取，表头与数据也将不能对齐。
![image](https://user-images.githubusercontent.com/40650757/83587657-21d28e00-a582-11ea-8bc3-6135a9de9a1c.png)

![image](https://user-images.githubusercontent.com/40650757/83587672-2eef7d00-a582-11ea-8820-c35e58a1a909.png)

**Comment by cipchk** [comment]
@zst20160902 麻烦提供一个重现示例

**Comment by zst20160902** [comment]
版本8的在线编辑不能使用，没法提供重现示例，在版本9中测试没有遇到这种情况，
