### ISSUE TITLE
CacheService不支持函数对象

### ISSUE THREAD

**Issue by ocweai** [ng-alain/ng-alain#1693]
![image](https://user-images.githubusercontent.com/40969504/83591133-cc01e400-a589-11ea-98d7-66bae1ea2335.png)

如上图的text和click并不会存储上。

![image](https://user-images.githubusercontent.com/40969504/83591247-17b48d80-a58a-11ea-9b9e-7c229365e6b7.png)

**Comment by cipchk** [comment]
就像你无法将一个 Java 方法存到 MySql 一个道理 。
