### ISSUE TITLE
st使用固定列时，能不能也让统计行对应的列也跟随固定

### ISSUE THREAD

**Issue by tang-butian** [ng-alain/ng-alain#1695]
如题

**Comment by cipchk** [comment]
可以在 `body` 内使用 `nzLeft`，参考 https://ng.ant.design/components/table/zh#components-table-demo-fixed-columns-header 写法。

**Comment by ezeryoung** [comment]
> 可以在 `body` 内使用 `nzLeft`，参考 https://ng.ant.design/components/table/zh#components-table-demo-fixed-columns-header 写法。

不行，nzLeft是和nzScroll配合使用的。用st的scroll滑动，nzLeft是没用的。如果使用nzScroll，那st表格里的固定列就固定不住了。统计列和st的列没法同时固定
