### ISSUE TITLE
8-to-9 升级至ng-alain 9.0 启动报错: An export assignment cannot be used in a module with other exported elements.

### ISSUE THREAD

**Issue by zst20160902** [ng-alain/ng-alain#1696]
🚨 Issues 是用于BUG、Feature、进度追踪 🚨
🚨 The issue tracker is not for questions 🚨

![image](https://user-images.githubusercontent.com/40650757/83730554-d3091f00-a67b-11ea-9dd5-69c3f5265227.png)

如果有任何问题，可在以下方式获得答案：

- https://ng-alain.com/
- QQ Group：316911865
- https://segmentfault.com/t/ng-alain

**Comment by cipchk** [comment]
`date-fns` 依旧是旧版本，参考 https://github.com/ng-alain/ng-alain/issues/1569  的开始之前节点 。
