### ISSUE TITLE
ST中通过修改columns来控制显示/隐藏列会导致错误

### ISSUE THREAD

**Issue by niuba** [ng-alain/ng-alain#1697]
- ng-alain version: 9.3.2
- Angular version: 9.1.9

## 【必填项】重现链接，Reproduction link
https://stackblitz.com/edit/ng-alain-setup-qgsu5z

## 重现步骤，Steps to reproduce
多次点击修改列按钮 

1. 无法按照index去对应数据
2.会导致报错ERROR Error: Cannot read property 'text' of undefined

可能的原因
1. 在只修改columns， _data[i]._value不会重新赋值
2. 是在模板代码中 st.component.html 
_columns 和_data 异步修改值 导致渲染的时候i._values[cIdx]可能为undefined

**Comment by cipchk** [comment]
```ts
Math.random() > 0.5
```

有可能会产生一个空的 `columns`， `st` 当遇到空会抛出异常，导致后面的动作会出错 。

**Comment by niuba** [comment]
https://stackblitz.com/edit/ng-alain-setup-qgsu5z
我改了。至少columns有一个。问题依旧

**Comment by cipchk** [comment]
依然保留现有的逻辑，如果需要重置列，建议调用 `st.resetColumns()` 并由自己决定是否重置数据。

> 但是 `resetColumns` 依然会有一个细节，那就是在加载数据前没有先清空，临时解决办法可以先调用 `clear`。
