### ISSUE TITLE
部署到IIS的问题

### ISSUE THREAD

**Issue by unix3000** [ng-alain/ng-alain#1698]
我用如下命令在ubuntu下新建了一个项目
ng new demo --style less --routing
cd demo
ng add ng-alain
ng build

部署到IIS后报告如下错误
polyfills-es2015.690…c25ea8557bb4b0.js:1 GET http://xxx.xxx.com/assets/tmp/i18n/zh-CN.json 404 (Not Found)

也试过其他的编译方式，ng build --prod和ng build --prod --aot
均报告同样的错误。

在i18n目录下建立index.html文件，访问http://xxx.xxx.com/assets/tmp/i18n/是可以正常显示index.html文件内容的。

请问这个问题要怎么解决？

**Comment by cipchk** [comment]
确认是 `assets/tmp/i18n/zh-CN.json` 是否存在，如果没有，可以尝试从 [i18n](https://github.com/ng-alain/ng-alain/tree/master/src/assets/tmp/i18n) 目录中下载。

**Comment by unix3000** [comment]
zh-CN.json文件确实存在。

**Comment by cipchk** [comment]
https://quark.sm.cn/s?from=kkframenew&search_id=AANgvLthlkBFN7ceMYBSOmNO8OSIW9ZSF4UsmynWvXHO5Q%3D%3D_1591497704520&round_id=-1&pdtt=1591497706&uc_param_str=dnntnwvepffrgibijbprsvpidsdichei&q=iis%20json%20404&hid=c440db8a98cb06fa855717d87e95ccf5
