### ISSUE TITLE
can you support IE11

### ISSUE THREAD

**Issue by maplye** [ng-alain/ng-alain#17]

**Comment by cipchk** [comment]
Yes, but you can compensate by loading `src/polyfills.ts` scripts, that demo site is not enabled by default.

**Comment by maplye** [comment]
but I got below problem:

Promise rejection: Object doesn't support property or method 'includes'

**Comment by cipchk** [comment]
see https://github.com/angular/angular-cli/issues/4128

**Comment by maplye** [comment]
Thank you cipchk,
I add the import to polyfills.ts follow the link, and it work well.
`import 'core-js/es7/array';`

I suggest add the line code and comment it into source code.
