### ISSUE TITLE
AlainAuthModule.forRoot ignores

### ISSUE THREAD

**Issue by a532533603** [ng-alain/ng-alain#170]
![image](https://user-images.githubusercontent.com/13478101/34592605-536e529c-f200-11e7-9634-050668710543.png)
![image](https://user-images.githubusercontent.com/13478101/34592609-5938cf22-f200-11e7-8039-be315d7b052f.png)
按照第一张图的设置方式，服务启动会报错，咋解决

**Comment by cipchk** [comment]
恐怕目前没有办法，这的确受限于 [#14187](https://github.com/angular/angular/issues/14187)。

恩，我想只能改为 `string[]`
