### ISSUE TITLE
路由复用在页面1里跳转到页面2时，在路由守卫里拦截跳转到新的页面3，由页面3切换到页面1时，页面1里的st都乱掉

### ISSUE THREAD

**Issue by tang-butian** [ng-alain/ng-alain#1700]
- ng-alain version: 9.3.2
- Angular version: X.Y.Z

## 【必填项】重现链接，Reproduction link

Stackblitz模板 不会配置 路由复用

## 重现步骤，Steps to reproduce
1、在脚手架里配置路由复用；
2、页面1里有一个ST表格，st里有一列设置type:link; 在click 回调里使用 this.router.navigate(['/contract/info', item.id]); 跳转到页面2；
3、页面2有一个路由守卫，代码如下 ：
     ` canActivate(
    next: ActivatedRouteSnapshot,
    state: RouterStateSnapshot,
  ): Observable<boolean | UrlTree> | Promise<boolean | UrlTree> | boolean | UrlTree {
    const p = state.url?.split(';')[0].split('/');
    const id = p[p.length - 1];
    if (!id) {
       this.router.navigateByUrl('/exception/403');
     // this.message.error('没有权限访问');
      return false;
    }
    return this.contractSrc.getContractInfoAuth({ id: id }).pipe(
      map((x) => {
        let result = false;
        if (x.success) {
          result = x.data;
        }
        if (!result) {
           this.router.navigateByUrl('/exception/403');
        //  this.message.error('没有权限访问');
        }

        return result;
      }),
    );
  }`
当前 result 为 false 时 跳转到  403页面；
4、从 403 页面再回到 页面1，此时页面1里的 st 会乱掉
![image](https://user-images.githubusercontent.com/27254047/83985269-1a88f700-a96b-11ea-8b9e-582679ca6d84.png)

**Comment by cipchk** [comment]
麻烦提供一下 `st` 的 `columns` 定义 。

**Comment by cipchk** [comment]
duplcated of #1651
