### ISSUE TITLE
紧凑主题下se里的 form表单，使用updateValueAndValidity不会出现错误视觉

### ISSUE THREAD

**Issue by tang-butian** [ng-alain/ng-alain#1701]
- ng-alain version: 9.3.2
- Angular version: X.Y.Z

## 【必填项】重现链接，Reproduction link

重现
https://stackblitz.com/edit/ng-alain-setup-kstae4

## 重现步骤，Steps to reproduce
使用 form 的patchValue 方法给表单赋值，新值长度大于验证规则的最大长度，并使用updateValueAndValidity方法更新表单的验证，但是页面不会马上出现错误视觉

**Comment by cipchk** [comment]
`se` 在做校验时会对 `dirty` （元素是否发生过变化）和校验结果一起比较，二者都为 `true` 才会认为这是一个错误的行为，而单纯的 `patchValue` 是不会认为 `dirty` 已经发生变化了，你可以这样子来解决：

```ts
this.contractForm.get('name')?.markAsDirty();
this.contractForm.patchValue({ name: '1234567890' });
```

> 另外 `patchValue` 内容已经会触发 `updateValueAndValidity` 无须再调用。
