### ISSUE TITLE
路由复用方法replace 不会关闭当前路由

### ISSUE THREAD

**Issue by tang-butian** [ng-alain/ng-alain#1702]
- ng-alain version: 9。3。2
- Angular version: X.Y.Z

## 重现步骤，Steps to reproduce
在紧凑主题下
路由复用中 使用replace 方法 原来是会关闭当前路由的，但是现在不会了，只跳转新的路由
![image](https://user-images.githubusercontent.com/27254047/83987919-4e1c4f00-a974-11ea-87d0-3801d3d02849.png)

**Comment by cipchk** [comment]
我无法重现你说的情况：

![help](https://user-images.githubusercontent.com/2987467/84110242-14704480-aa57-11ea-8cea-f6bd47c521f5.gif)

**Comment by tang-butian** [comment]
@cipchk  复用匹配用 模式用 URL,  对所有路由有效
