### ISSUE TITLE
ST组件表头分组后，空数据显示有问题，而且排序失效

### ISSUE THREAD

**Issue by BennyCxb** [ng-alain/ng-alain#1706]
- ng-alain version: 9.4.1
- Angular version: 9.1.9

## 【必填项】重现链接，Reproduction link
https://stackblitz.com/edit/ng-alain-setup-pwcegj?file=src%2Fapp%2Fapp.component.html
重现链接如上

![QQ截图20200610095822](https://user-images.githubusercontent.com/36026131/84218499-21497280-ab01-11ea-9706-8fa8992eb74b.png)

![QQ截图20200610095921](https://user-images.githubusercontent.com/36026131/84218539-358d6f80-ab01-11ea-9bb6-65391acfd650.png)

## 重现步骤，Steps to reproduce
![image](https://user-images.githubusercontent.com/36026131/86440570-423a6780-bd3d-11ea-9024-6723e396ba79.png)
![image](https://user-images.githubusercontent.com/36026131/86441259-867a3780-bd3e-11ea-985e-f37bbf26b878.png)

空数据的时候，列宽只占一级表头的列数，导致排版有问题
![image](https://user-images.githubusercontent.com/36026131/86440901-e45a4f80-bd3d-11ea-845e-10e1998dcf88.png)

![image](https://user-images.githubusercontent.com/36026131/86441531-f092dc80-bd3e-11ea-8d4f-7cce676c0b8f.png)
数据多的时候，排版完全不能看， 超过的数据会被挤压，即使x轴设置滚动条
期望：能修复表头分组的BUG

**Comment by cipchk** [comment]
抱歉，我不知道你在说什么，麻烦描述重现步骤及示例，以及期望结果。

**Comment by BennyCxb** [comment]
![image](https://user-images.githubusercontent.com/36026131/86440570-423a6780-bd3d-11ea-9024-6723e396ba79.png)
空数据的时候，列宽只占一级表头的列数，导致排版有问题
![image](https://user-images.githubusercontent.com/36026131/86440901-e45a4f80-bd3d-11ea-845e-10e1998dcf88.png)
期望：能修复表头分组的BUG

**Comment by BennyCxb** [comment]
已经补充

**Comment by cipchk** [comment]
麻烦提供一个重现示例，或者先尝试使用最新版本试试。

**Comment by BennyCxb** [comment]
补充的就是示例啊，已经升级到最新了

**Comment by BennyCxb** [comment]
重现示例：https://stackblitz.com/edit/ng-alain-setup-pwcegj?file=src%2Fapp%2Fapp.component.html

**Comment by cipchk** [comment]
`nzNoResult` 错位部分先跟踪 [#5509](https://github.com/NG-ZORRO/ng-zorro-antd/issues/5509)

至于宽度问题可以暂时设置 `widthConfig` 来解决，对最终每一列设置一个宽度。
