### ISSUE TITLE
full-content模式下页面被隔断

### ISSUE THREAD

**Issue by happyandrewli** [ng-alain/ng-alain#1708]
使用full-content组件时，如果里面的内容过长，需要上下滚动，或者浏览器过小，无法显示所有的内容，部分页面就会隔断。

**Reproduce issue**
点击下面链接，访问ng-alain建议表格演示。 手动减小浏览器高度，可见分页和部分表格被隔断，无法显示。

https://ng-alain.gitee.io/#/delon/st

![image](https://user-images.githubusercontent.com/6813061/84278519-da5c7c80-ab02-11ea-9104-4382ce6d19a5.png)

**Comment by bluesiboy** [comment]
感谢你的反馈。

**Comment by cipchk** [comment]
应该是 `nz-table` 组件在计算宽度时引起的，相关 issues：

- #1651
- https://github.com/NG-ZORRO/ng-zorro-antd/issues/5160
- https://github.com/NG-ZORRO/ng-zorro-antd/issues/5167
- https://github.com/NG-ZORRO/ng-zorro-antd/issues/5370

**Comment by cipchk** [comment]
duplcated of #1651
