### ISSUE TITLE
Ask a question about bar.

### ISSUE THREAD

**Issue by ohmygodoh** [ng-alain/ng-alain#171]
Ask a question
I run the project in the browser, when open a page, and there is no covered the entire screen, found that only up and down direction have a progress bar, left and right no progress bar, is my browser? I hope to get the answer, thanks!!
![image](https://user-images.githubusercontent.com/34624178/34593072-7ec7824e-f203-11e7-9320-1ea2a55de4cb.png)

**Comment by cipchk** [comment]
ng-alain not yet adaptived to any with, but work well in most device (e.g:mi, huawei, iphone, ipad[include rotate]......)

**Comment by ohmygodoh** [comment]
but，this is what I run on my computer,not phone ,I run on broswer in my computer base on google chrome.

**Comment by ohmygodoh** [comment]
It's just that the screen is not full screen

**Comment by cipchk** [comment]
the adaptive is often difficult to any width

**Comment by ohmygodoh** [comment]
thanks
