### ISSUE TITLE
ST组件Columns动态赋值问题

### ISSUE THREAD

**Issue by mostermsater** [ng-alain/ng-alain#1711]
- ng-alain version: 9.3.1
- Angular version: 9.0.0

## 重现步骤，
st使用url作为数据加载
初始化有abcde五列，现在设置为ab两列,（在我的项目里列头会更改，但是数据行还是原来的）,
再从ab两列设置为abcde五列 ，cde三列数据行会赋值错误( Cannot read property 'text' of undefined )，(在我的项目即使用resetColumns重新加载数据也一样)

**Comment by cipchk** [comment]
duplcated of #1697
