### ISSUE TITLE
Can't resolve '../../../theme/theme-default.less' in 'G:\webapp\node_modules\_@delon_abc@9.3.2@@delon\abc\st\style'

### ISSUE THREAD

**Issue by ghwillbe** [ng-alain/ng-alain#1713]
我在8.2升级到9.3后，编译一直未能成功.
我进入到发生错误的地方查看，发现```@import '../../../theme/theme-default.less'``` 这行代码的路径确实有问题，不知道是我在哪里的配置未写正确还是其他的问题？请求卡色老大帮帮忙，谢谢~
下面是编译发生的问题:
```
ERROR in ./src/styles.less (./node_modules/_css-loader@3.5.1@css-loader/dist/cjs.js??ref--14-1!./node_modules/_postcss-loader@3.0.0@postcss-loader/src??embedded!./node_modules/_less-loader@5.0.0@less-loader/dist/cjs.js??ref--14-3!./src/styles.less)
Module build failed (from ./node_modules/_less-loader@5.0.0@less-loader/dist/cjs.js):

@import '../../../theme/theme-default.less';
^
Can't resolve '../../../theme/theme-default.less' in 'G:\webapp\node_modules\_@delon_abc@9.3.2@@delon\abc\st\style'
      in G:\webapp\node_modules\_@delon_abc@9.3.2@@delon\abc\st\style\index.less (line 1, column 0)
```
我有Clone你给出的模板，发现同样也会出现这样的问题:
```
ERROR in ./src/styles.less (./node_modules/_css-loader@3.5.1@css-loader/dist/cjs.js??ref--14-1!./node_modules/_postcss-loader@3.0.0@postcss-loader/src??embedded!./node_modules/_less-loader@5.0.0@less-loader/dist/cjs.js??ref--14-3!./src/styles.less)
Module build failed (from ./node_modules/_less-loader@5.0.0@less-loader/dist/cjs.js):

@import '../../../theme/theme-default.less';
^
Can't resolve '../../../theme/theme-default.less' in 'F:\Angular Project\ng-alain-master (1)\ng-alain-master\node_modules\_@delon_abc@9.3.2@@delon\abc\st\style'
      in F:\Angular Project\ng-alain-master (1)\ng-alain-master\node_modules\_@delon_abc@9.3.2@@delon\abc\st\style\index.less (line 1, column 0)
ERROR in Module build failed (from ./node_modules/_less-loader@5.0.0@less-loader/dist/cjs.js):


@import './layout/fullscreen/theme-default.less';
@import '../abc/theme-default.less';
^
Can't resolve '../abc/theme-default.less' in 'F:\Angular Project\ng-alain-master (1)\ng-alain-master\node_modules\_@delon_theme@9.3.2@@delon\theme'
      in F:\Angular Project\ng-alain-master (1)\ng-alain-master\node_modules\_@delon_theme@9.3.2@@delon\theme\theme-default.less (line 5, column 0) ```
项目依赖包供您参考:
```
"dependencies": {
    "@angular/animations": "^9.1.11",
    "@angular/common": "^9.1.11",
    "@angular/compiler": "^9.1.11",
    "@angular/core": "^9.1.11",
    "@angular/forms": "^9.1.11",
    "@angular/platform-browser": "^9.1.11",
    "@angular/platform-browser-dynamic": "^9.1.11",
    "@angular/router": "^9.1.11",
    "@antv/data-set": "^0.10.1",
    "@antv/g2": "^3.4.5",
    "@antv/g2-plugin-slider": "^2.1.1",
    "@aspnet/signalr": "^1.1.2",
    "@delon/abc": "^9.3.2",
    "@delon/acl": "^9.3.2",
    "@delon/auth": "^9.3.2",
    "@delon/cache": "^9.3.2",
    "@delon/chart": "^9.3.2",
    "@delon/form": "^9.3.2",
    "@delon/mock": "^9.3.2",
    "@delon/theme": "^9.3.2",
    "@delon/util": "^9.3.2",
    "ajv": "^6.7.0",
    "core-js": "^2.6.3",
    "editorconfig-tools": "^0.1.1",
    "extend": "^3.0.2",
    "husky": "^1.3.1",
    "lint-staged": "^8.1.0",
    "ng-alain": "^9.3.2",
    "ng-zorro-antd": "^9.1.2",
    "ng2-pdf-viewer": "^6.3.0",
    "oidc-client": "^1.6.1",
    "pdfjs-dist": "^2.2.228",
    "prettier": "^1.16.1",
    "prettier-stylelint": "^0.4.2",
    "rxjs": "~6.5.5",
    "stylelint": "^9.10.1",
    "stylelint-config-standard": "^18.2.0",
    "tslib": "^1.10.0",
    "tslint-config-prettier": "^1.17.0",
    "zone.js": "~0.10.2",
    "@ngx-translate/core": "^12.1.2",
    "@ngx-translate/http-loader": "^4.0.0",
    "screenfull": "^5.0.2",
    "qrious": "^4.0.2"
  }
```

**Comment by cipchk** [comment]
不要使用 `cnpm` 来安装依赖，可以参考如何使用宝源：https://ng-alain.com/docs/faq/zh#%E5%A6%82%E4%BD%95%E6%AD%A3%E7%A1%AE%E4%BD%BF%E7%94%A8%E6%B7%98%E5%AE%9D%E6%BA%90%EF%BC%9F
