### ISSUE TITLE
禁用 lvy 编译后 报错 

### ISSUE THREAD

**Issue by flxy1028** [ng-alain/ng-alain#1714]
- ng-alain version: 9.3.2
- Angular version: 9.1.11

## 【必填项】重现链接，Reproduction link

本想传个图，但试了几次传不上去 

## 重现步骤，Steps to reproduce
ng new project 
cd project
ng add ng-alain
修改 tsconfig.app.json 后面添加一个属性
  "angularCompilerOptions": {
    "enableIvy": false
  }

再 npm run build 
执行完成 报错 如下
ERROR in node_modules/@delon/form/form.d.ts.ObjectWidget.html(39,3): Property 'cardBordered' does not exist on type 'ObjectWidget'.
node_modules/@delon/form/form.d.ts.ObjectWidget.html(38,3): Property 'cardBodyStyle' does not exist on type 'ObjectWidget'.

**Comment by cipchk** [comment]
fixed by `9.4.0`
