### ISSUE TITLE
ModalHelper.static() 调用后，回传值无效 undefined

### ISSUE THREAD

**Issue by dusdong** [ng-alain/ng-alain#1716]
- ng-alain version: 9.4.0
- Angular version: 9.1.11

## 重现步骤，Steps to reproduce
使用 ng-alain  #/extras/poi 页面示例代码：

`this.modal.close('true');`
`this.close();`

**Comment by bluesiboy** [comment]
close(result: any)  关闭(隐藏)对话框。
当用于以服务方式创建的对话框，此方法将直接 销毁 对话框（同destroy方法）

destroy(result: any)  销毁对话框。
仅用于服务方式创建的对话框（非服务方式创建的对话框，此方法只会隐藏对话框）


如果再不理解，我也无能为力了。

**Comment by dusdong** [comment]
明白了。
不过，#/extras/poi 的示例在 angular 8.x 下一直是好用的，大概是zorro修改了 modalRef.close() 的返回机制

**Comment by dusdong** [comment]
已提交 #1719

**Comment by evin2333** [comment]
close之后经常不触发subscribe是什么情况，这个subscribe触发条件是什么啊，有说明吗，给个链接
