### ISSUE TITLE
SF组件的upload小部件

### ISSUE THREAD

**Issue by bluesiboy** [ng-alain/ng-alain#1717]
- ng-alain version: 9.x
- Angular version: 9.x

## 重现步骤，Steps to reproduce
在SF组件的upload小部件肿，enum属性的权重貌似狠高。
当enum为[]时，即便用户上传了一张图片，也会提示 【不应少于 1 个项】。

**Comment by cipchk** [comment]
`enum` 最终会被转化成 `nzFileList` 属性值，并不会有权重高，麻烦提供一下具体的重现示例。

**Comment by cipchk** [comment]
缺少重现步骤，关闭此 issues，如果有其他细节请重新打开或发布新的 issues。
