### ISSUE TITLE
simple-table cannot render data by async when bounding data properties.

### ISSUE THREAD

**Issue by changxinjie** [ng-alain/ng-alain#172]
with the version 0.5.0-rc-5+
the simple-table data can't be show after 2 seconds.
![image](https://user-images.githubusercontent.com/9565184/34593884-9dcd23ba-f208-11e7-91cb-31a08e836112.png)

Is it a bug ?

**Comment by cipchk** [comment]
a fail [demo](https://stackblitz.com/edit/ng-alain-setup-7tbmhs?file=app%2Fapp.component.ts)
