### ISSUE TITLE
定制的小部件在最新版本报错

### ISSUE THREAD

**Issue by ydostyle** [ng-alain/ng-alain#1720]
- ng-alain version: 9.4.0
- Angular version: 9.1.11

## 【必填项】重现链接，Reproduction link
https://stackblitz.com/edit/angular-gcunnc?file=src%2Fapp%2Fcollapse-array.widget.ts

## 重现步骤，Steps to reproduce
1.定制的小部件去覆盖ArrayLayoutWidget部件的arraySpan属性值。
2.在ngInit里面打印this.sfComp为空导致后续一系列问题

**Comment by ydostyle** [comment]
https://stackblitz.com/edit/angular-gcunnc?file=src%2Fapp%2Fcollapse-array.widget.ts   重现链接

**Comment by cipchk** [comment]
`static` 在 `class` 内是一等公民，但是空行会引起解析失败？

```diff
+ export class CollapseArrayWidget extends ArrayLayoutWidget implements OnInit {
+   // TODO: add explicit constructor
- 
+   static readonly KEY = 'collapseArray';
```

总之去掉这个空行就通过了。

**Comment by ydostyle** [comment]
那为啥arraySpan不设置默认值就一切也正常- - @cipchk

**Comment by ydostyle** [comment]
在之前的版本是好的，升级才碰到

**Comment by cipchk** [comment]
@ydostyle 解决了？是如何解决的？去掉空格？
