### ISSUE TITLE
ST表格中如果根据某一个单元格设置这一行的样式，该如何？？

### ISSUE THREAD

**Issue by peacejj** [ng-alain/ng-alain#1722]
ST表格中如果根据某一个单元格设置这一行的样式，该如何？？

**Comment by cipchk** [comment]
- 如果是整行可以使用 `rowClassName` 方法，根据数据自行判断；（这个应该就是你需要的。）
- 如果是整列可以使用 `columns` 中定义 `className` 值；

**Comment by peacejj** [comment]
@cipchk thank you~
