### ISSUE TITLE
在img标签的src请求中如何在请求头添加了token？

### ISSUE THREAD

**Issue by peacejj** [ng-alain/ng-alain#1725]
在img标签的src请求中如何在请求头添加了token？
现在我并没有看到添加，这个是怎么处理呢？

**Comment by peacejj** [comment]
@cipchk 求助大佬

**Comment by cipchk** [comment]
的确不支持，你需要手动处理，比如在请求的URL加上 token，还有一种就是把图像请求放在 `HttpClient` 里当 `get` 来请求然后再以base64的形式应用到 `src` 上。
