### ISSUE TITLE
npm run icon 报错Cannot read property 'kind' of undefined

### ISSUE THREAD

**Issue by zmzimpl** [ng-alain/ng-alain#1726]
- ng-alain version: 9.4.0
- Angular version: 9.1.4

## 【必填项】重现链接，Reproduction link

![image](https://user-images.githubusercontent.com/27490895/85544485-a4b0ab00-b64d-11ea-8c68-b745a23d48d7.png)

## 重现步骤，Steps to reproduce
这个项目是从8升到9的，目前正常运行，只是icon的脚本运行不了，clone的ng-alain并没有报这个错，所以会不会是因为我升级时遗漏了什么东西？

**Comment by cipchk** [comment]
估计应该是无法解析出某个有效的 icon 值，从而导致错误，我试着优化一下看能否通过捕获异常来定位是哪个文件无法获取从而产生的问题的。
