### ISSUE TITLE
st 组件虚拟滚动 设置size为small 时，高度计算不正确，并且 virtualItemSize属性也不能更正高度

### ISSUE THREAD

**Issue by ttnkh21** [ng-alain/ng-alain#1729]
st 组件虚拟滚动 设置表格大小为size="small"  时，会有空白部分，不能完全填充 y的高度，virtualItemSize 也不能更正。
测试ng-zorro是没有问题的。
ng-zorro 连接：https://stackblitz.com/edit/angular-vrxjau?file=src/app/app.component.ts
![image](https://user-images.githubusercontent.com/23454757/94638600-ed42c900-030c-11eb-8498-cbaa00c8d4bb.png)

ng-alain 连接 ：https://stackblitz.com/edit/angular-qjadfb-ajeegc?file=src/app/app.component.ts
![image](https://user-images.githubusercontent.com/23454757/94638749-427eda80-030d-11eb-8439-66f1ea4d9900.png)

**Comment by cipchk** [comment]
我认为这同 #1836 相同问题，关掉此 issues。
