### ISSUE TITLE
Have a question

### ISSUE THREAD

**Issue by ohmygodoh** [ng-alain/ng-alain#173]
![image](https://user-images.githubusercontent.com/34624178/34594511-7fd6e09a-f20c-11e7-8da1-772b6c92809b.png)
Also in my computer browser, based on your component, I made a table by myself, not maximized, is the picture above normal? It's the question of my code or browser, or other?

**Comment by ohmygodoh** [comment]
I used the option of the nz-select component

**Comment by cipchk** [comment]
> ng-alain not yet adaptived to any with, but work well in most device (e.g:mi, huawei, iphone, ipad[include rotate]......)

dupliced of #171
