### ISSUE TITLE
st 组件指定scroll.x 时， 滚动条必出现， 未指定scroll.x属性则将容器撑开展示

### ISSUE THREAD

**Issue by zst20160902** [ng-alain/ng-alain#1732]
- ng-alain version: 9.4.1
- Angular version: 9.1.4

## 【必填项】重现链接，Reproduction link

https://codesandbox.io/s/dazzling-euclid-wi2i7?file=/src/app/app.component.ts

![image](https://user-images.githubusercontent.com/40650757/85936287-ca7ad000-b92b-11ea-8a49-7bc23c2e20ec.png)

**Comment by cipchk** [comment]
如果你不想超出可以设置宽度模式为严格模式：

```diff
- <st [data]="url" [req]="{ params: params }" [columns]="columns"> </st>
+ <st [data]="url" [req]="{ params: params }" [widthMode]="{type: 'strict'}" [columns]="columns"> </st>
```
