### ISSUE TITLE
 angular 10  is release ,please support angular 10 ,thanks.

### ISSUE THREAD

**Issue by gemron** [ng-alain/ng-alain#1733]

**Comment by cipchk** [comment]
Waiting NG-ZORRO!

**Comment by gemron** [comment]
ok! i upgrade to angular 10, tested it and found no problems.

**Comment by HikeNcity** [comment]
![ng-alain](https://user-images.githubusercontent.com/65915900/86221752-399b3300-bb7d-11ea-88eb-8326f918cd88.png)

**Comment by gemron** [comment]
https://github.com/ng-alain/ng-alain/issues/1740#issuecomment-652250628

**Comment by forecho** [comment]
https://ng-alain.com/docs/upgrade-v10/zh

**Comment by gemron** [comment]
NG-ZORRO 10 is released, see this https://github.com/NG-ZORRO/ng-zorro-antd/releases/tag/10.0.0 . 
Wait for the good news from ng-alain.
