### ISSUE TITLE
ST组件data传url，url携带login字样会默认去掉headers的Authorization

### ISSUE THREAD

**Issue by Dunqing** [ng-alain/ng-alain#1735]
- ng-alain version: 9.4.0
- Angular version: 9.1.1

![1593413819524_6EFB2317-3336-4b69-9611-2B480B0BA0AA](https://user-images.githubusercontent.com/29533304/85982703-ddb79980-ba18-11ea-9937-b7bbc6a006bb.png)
![1593413819538_EEBC4EA8-9AAE-4b23-9DBF-673D281BC246](https://user-images.githubusercontent.com/29533304/85982732-e6a86b00-ba18-11ea-923c-c29273e77443.png)

## 重现步骤，Steps to reproduce
使用ST组件时，传的url，url包含login字母，就出现了如上问题，使用的是jwtmodulet http拦截器

**Comment by cipchk** [comment]
授权 `@delon/auth` 时默认忽略属性 `ignores` 为 `[ /\/login/, /assets\// ]`，有两种方法解决：

+ 重新通过[全局配置](https://ng-alain.com/docs/global-config/en)来调整 `ignores` 的默认值。
+ 给请求的URL加上 `url?_allow_anonymous=true` 参数，来强制忽略当前的

**Comment by Dunqing** [comment]
> 授权`@delon/auth`时默认忽略属性`ignores`为`[ /\/login/, /assets\// ]`，有两种方法解决：
> 
> * 重新通过[全局配置](https://ng-alain.com/docs/global-config/en)来调整`ignores`的[预设](https://ng-alain.com/docs/global-config/en)值。
> * 给请求的URL加上`url?_allow_anonymous=true`参数，来强制忽略当前的

用第二种方式之后，不管有没有login字样都直接去掉了Authorization

**Comment by cipchk** [comment]
抱歉，我看错了，`url?_allow_anonymous=true` 是强制忽略受限校验，看样子只能通过全局配置来处理。其实可以试着反过来，比如通过全局配置 `ignores` 为 `[]`，然后在你需要强制忽略受限校验的请求在url加上 `url?_allow_anonymous=true`。
