### ISSUE TITLE
Menu项是否增加hidden属性

### ISSUE THREAD

**Issue by winpzs** [ng-alain/ng-alain#174]
## Bug Report or Feature Request (mark with an `x`)
<pre><code>
[ ] Bug report -> please search issues before submitting
[X ] Feature request
[ ] Documentation issue or request
</code></pre>

## Feature request
Menu项是否增加hidden属性，不显示但要使用相关数据

如: **列表详情** 不应该显示，但导航要用于此数据
```json
      {
            "text": "列表",
            "translate": "other",
            "link": "/other",
            "icon": "icon-magic-wand",
            "hidden":false,
            "children": [{
                "text": "列表详情",
                "link": "/other/split",
                "translate": "split",
                "hidden":true
            }]
        }
```

**Comment by cipchk** [comment]
导航是指什么呢？能否描述更明细场景？

**Comment by winpzs** [comment]
比如**breadcrumb**： 首页 / User列表/ User详情
我们要根据Menu数据来处理问题, 要它的层级，标题及描述等,
如上面的详情页面， 不可能直接显示**sidebar-nav**里，但我们要相关数据。
这只是场景之一， 还有好多场景是要这样的（只要数据，不要显示）。

**当然我可以加一层服务层来使用你的MenuService，但我感觉这个hidden你们应该有的**

**Comment by cipchk** [comment]
的确，我会增加类似功能。

**Comment by cipchk** [comment]
抱歉，我忘记了，应该有 `hide` 属性；你可以指定 `hide` 属性为 `true` 表示不显示显示。
