### ISSUE TITLE
Unexpected token / in JSON at position 0

### ISSUE THREAD

**Issue by zhouxinglong1991** [ng-alain/ng-alain#1740]
ng new 项目建成之后,ng add ng-alain报错Unexpected token / in JSON at position 0

<pre><font color="#EF2929"><b>$ </b></font><font color="#4E9A06">ng</font> add ng-alain                          
<font color="#4E9A06">Installing packages for tooling via yarn.</font>
<font color="#4E9A06">Installed packages for tooling via yarn.</font>
<font color="#4E9A06">?</font> <b>Which default language would you like to use?</b> <font color="#06989A">简体中文</font>
<font color="#4E9A06">?</font> <b>Would you like to add hmr plugin? (default: Y)</b> <font color="#06989A">Yes</font>
<font color="#4E9A06">?</font> <b>Would you like to add code style plugin? (default: Y)</b> <font color="#06989A">Yes</font>
<font color="#4E9A06">?</font> <b>Would you like to add dynamic form (sf component) plugin? (default: Y)</b> <font color="#06989A">Yes</font>
<font color="#4E9A06">?</font> <b>Would you like to add mock plugin? (default: Y)</b> <font color="#06989A">Yes</font>
<font color="#4E9A06">?</font> <b>Would you like to add i18n plugin? (default: N)</b> <font color="#06989A">No</font>
Can&apos;t parse json file (tsconfig.json), pls check for comments or trailing commas, or validate json via https://jsonlint.com/
<font color="#EF2929"><b>Unexpected token / in JSON at position 0</b></font>
</pre>

**Comment by gemron** [comment]
angular 10 生成的tsconfig.json文件头部有注释，把注释删除掉 即可
