### ISSUE TITLE
g2-timeline 组件时间显示异常

### ISSUE THREAD

**Issue by whwlsfb** [ng-alain/ng-alain#1744]
- delon/chart version: 9.5.0
- Angular version: 9.1.11

## 【必填项】重现链接，Reproduction link

![微信截图_20200702225747](https://user-images.githubusercontent.com/8212964/86374770-8420ca80-bcb7-11ea-8212-2906a5c7c621.png)

此处我设置的每24小时一个节点，日期格式化为：MM/dd，但是时间轴的日期部分却显示0~6不断重复。

## 重现步骤，Steps to reproduce

生成随机的相隔24小时的数据集，修改g2-timeline的mask属性为`MM/dd`即可重现。

**Comment by whwlsfb** [comment]
发错区了

**Comment by cipchk** [comment]
fixed by `9.5.1`
