### ISSUE TITLE
Resizable G2 Charts

### ISSUE THREAD

**Issue by vigneshbarani24** [ng-alain/ng-alain#1746]
Hello @cipchk, Can you please let me know if resizable charts is available as part of this awesome library ?
I am trying to do it. But i am not sure on how to achieve the same. Here, I have tried to do a minimum mockup using nzResizable.
[https://stackblitz.com/edit/angular-bmy5m8](url)

**Comment by cipchk** [comment]
The G2 uses `window.addEventListener('resize', this.onResize)` to detect a change in parent dom element's size.

So, you juse using `this.barComp['chart'].forceFit();` to force resize.

> `chart` is a private variable, I will make it public.

```diff
@Component({
  styles: [
    `
      .box {
+       display: block;
+       width: 100%;
      }
    `
  ]
})
export class NzDemoResizableBasicComponent {
+ @ViewChild('bar') private readonly barComp: G2BarComponent;
  onResize({ width, height }: NzResizeEvent): void {
+   this.barComp['chart'].forceFit();
	......
  }
}
```
