### ISSUE TITLE
给_HttpClient单独又封装了一层后，获取_HttpClient的loading，发现一直是false

### ISSUE THREAD

**Issue by peacejj** [ng-alain/ng-alain#1747]
具体操作是在新封装的service（暂称newHttp）中获取loading，如下：
 public loading = this.http.loading;
然后，在界面按钮上的获取newHttp.loading ，但是这个值一直是false，这是什么原因呢？

这个大家遇到过吗？怎么处理的呢？

**Comment by cipchk** [comment]
若是在Service下你获取的始终只是第一次的副本，建议在 Service 这样获取：

```ts
get loading() {
  return this.http.loading;
}
```

**Comment by peacejj** [comment]
@cipchk 哦哦哦
