### ISSUE TITLE
sf 当 属性的 type 为Object时，内部的部件是不是就不能自定义了？

### ISSUE THREAD

**Issue by zmzimpl** [ng-alain/ng-alain#1749]
我尝试将Object内部的部件自定义，发现label是可以加载的，但template的内容没有解析出来，是因为没有做这个支持吗？

**Comment by cipchk** [comment]
参考这个写法： https://github.com/ng-alain/delon/blob/master/packages/form/src/widgets/object/object.widget.html#L26-L28

**Comment by zmzimpl** [comment]
> 参考这个写法： https://github.com/ng-alain/delon/blob/master/packages/form/src/widgets/object/object.widget.html#L26-L28

不好意思，我没有表述清楚，我的意思其实是我在 一个object 里面写了一个 `widget: 'custom'` 的属性，这个属性的label可以被读取，但我在HTML里面写的template不能被解析

**Comment by cipchk** [comment]
还是没明白您的意思，能重现吗？

**Comment by zmzimpl** [comment]
> 还是没明白您的意思，能重现吗？

https://codesandbox.io/s/green-cloud-dmskn?from-embed=&file=/src/app/app.component.ts

在这个例子里 origin 是 fileInfo 的一个属性，widget为 custom

**Comment by cipchk** [comment]
抱歉，你可以到群里：428749721，问问。

**Comment by WalkingNormal** [comment]
请问这个最后怎么解决的？

-----
最后，从自定义一个小部件，解决了这个问题。
