### ISSUE TITLE
DefaultInterceptor ErrorObservable

### ISSUE THREAD

**Issue by a532533603** [ng-alain/ng-alain#175]
DefaultInterceptor ErrorObservable.create(event) 无法返回正确的错误信息
![image](https://user-images.githubusercontent.com/13478101/34609870-704ea822-f259-11e7-9807-7dda253b4d39.png)
![image](https://user-images.githubusercontent.com/13478101/34609881-78df92bc-f259-11e7-85ea-25ad2034ed54.png)
![image](https://user-images.githubusercontent.com/13478101/34609891-853669b4-f259-11e7-85e0-28abdbbddc2d.png)

**Comment by cipchk** [comment]
这个问题我也很苦恼，暂时我也没有什么好的 办法。

**Comment by a532533603** [comment]
如果是这样的话，现在是否就没法使用统一错误拦截器了
