### ISSUE TITLE
路由复用Tab行把内容挡住了部分

### ISSUE THREAD

**Issue by tang-butian** [ng-alain/ng-alain#1754]
- ng-alain version: 9.5.1
- Angular version: 9.1.9

## 【必填项】重现链接，Reproduction link

![image](https://user-images.githubusercontent.com/27254047/87111895-0eab9000-c29d-11ea-9aed-31c20100973f.png)

![image](https://user-images.githubusercontent.com/27254047/87111897-1408da80-c29d-11ea-9f9a-96150a8a54ed.png)

## 重现步骤，Steps to reproduce
我用的是紧凑主题，直接创建一个页面，路由复用打开，内容有8px被挡住了

**Comment by cipchk** [comment]
对于不使用 `page-header` 插件的特殊页，可以在模板的最外层加上间距 `class="pt-lg"`，参考 [analysis.component.html](https://github.com/ng-alain/ng-alain/blob/master/src/app/routes/dashboard/analysis/analysis.component.html#L1)
