### ISSUE TITLE
登录页设置token后，再次请求其他接口（还在登录页），请求头并没有token，但是在其他页发起请求是有token的

### ISSUE THREAD

**Issue by peacejj** [ng-alain/ng-alain#1757]
问题：登录页设置token后，再次请求其他接口（还在登录页），请求头并没有token，但是在其他页发起请求是有token的。

现在不清楚原因，由于这种情况没法做在线编辑，所以给不出链接，不知道有人遇到过类似的情况吗？

**Comment by cipchk** [comment]
设置Token后再做其他 Http 请求，参考 [login.component.ts](https://github.com/ng-alain/ng-alain/blob/master/src/app/routes/passport/login/login.component.ts#L122)

**Comment by peacejj** [comment]
@cipchk  我试了，并不可以。这个demo在设置token后只是跳转到首页，并没做其他请求。

**Comment by cipchk** [comment]
道理是相同的，如果依然有问题，麻烦提个重现法例。

**Comment by peacejj** [comment]
@cipchk 
`
 import { Component, Inject, OnInit } from '@angular/core';
 import { SettingsService, _HttpClient } from '@delon/theme';
 import { DA_SERVICE_TOKEN, ITokenService } from '@delon/auth';

@Component({
  selector: 'components-sv-type',
  template: `<div>{{token | json}}</div>`,
})
export class ComponentsSvTypeComponent implements OnInit {
   token
   constructor(
    private _http: _HttpClient,
    @Inject(DA_SERVICE_TOKEN) private tokenService: ITokenService,
  ) {}
   ngOnInit(): void {
    this.tokenService.set({
      'token':'123456'
    });
    this.token = this.tokenService.get()
    this.request();
  }
  request(){
    this._http.get('/users').subscribe(res=>{})
  }
}
`
在线示例看不了network，只能提供下代码，最简单的示例，大佬可以看下

>

**Comment by cipchk** [comment]
Token 是由 `@delon/auth` 模块自动加上的，比如  ng-alain 的 [app.module.ts](https://github.com/ng-alain/ng-alain/blob/master/src/app/app.module.ts#L72)，更多细节请看 [auth文档](https://ng-alain.com/auth/getting-started/en)

**Comment by peacejj** [comment]
已解：发现是默认配置【ignores】的问题，包含/login就会拦截token。
除了登录接口，我其他接口也有包含/login，所以才出现无token的情况。
