### ISSUE TITLE
feat(cache): new @delon/cache plans!

### ISSUE THREAD

**Issue by cipchk** [ng-alain/ng-alain#176]
解决中台通用性信息的缓存问题。

- [x] 读、写
    - [x] 过期
    - ~过期通知~
- [x] 移除
    - ~移除通知~
- [x] 持久化
- ~装饰化~

欢迎提供更友好的建议 🍼

**Comment by winpzs** [comment]
这个是什么作用？mock缓存吗？
如果是：
* 可配置优先读取服务端的还是mock的
* 缓存最近的记录数就行了，一般开发也就当前任务要而已
* 能读取持久化文件最好，已经发布的产品数据可以拿回来调试;
* 能有个切入口控制可以缓存的数据，如：没数据的http请求缓存也没意思，对吧

**Comment by cipchk** [comment]
[mock](http://ng-alain.com/docs/mock)
