### ISSUE TITLE
color-less.js缺少antDir参数，导致编译报错

### ISSUE THREAD

**Issue by BennyCxb** [ng-alain/ng-alain#1765]
- ng-alain version: 9.5.3
- Angular version: 9.1.11

## 重现步骤，Steps to reproduce
![20200714141713](https://user-images.githubusercontent.com/36026131/87391821-04abc900-c5de-11ea-969e-6f5cfe627023.png)
![image](https://user-images.githubusercontent.com/36026131/87392673-83edcc80-c5df-11ea-804c-7275d742823f.png)

![QQ截图20200714143419](https://user-images.githubusercontent.com/36026131/87392446-25c0e980-c5df-11ea-991b-464267fb2157.png)
![QQ截图20200714143523](https://user-images.githubusercontent.com/36026131/87392589-5c96ff80-c5df-11ea-841e-2026176599ea.png)

**Comment by cipchk** [comment]
固定 ["antd-theme-generator": "1.2.2"](https://github.com/ng-alain/ng-alain/blob/master/package.json#L113) 版本号。
