### ISSUE TITLE
ng g 出来的module报找不到元素 is not a known element

### ISSUE THREAD

**Issue by wgb123** [ng-alain/ng-alain#1766]
- ng-alain version: 9.5.3
- Angular version: 9.1.11

## 重现步骤，Steps to reproduce
ng g ng:alain:module trade
ng g ng:alain:list list -m=trade
RouteRoutingModule 添加路由
{ path: 'trade', loadChildren: () => import('./trade/trade-routing.module').then((m) => m.TradeRoutingModule) },
然后项目报错 
![图片](https://user-images.githubusercontent.com/26479828/87410982-9bd24a00-c5f9-11ea-8b10-9cd137cce571.png)
但是将tradeModule模块import到 routes.module.ts中 
![图片](https://user-images.githubusercontent.com/26479828/87411030-b3a9ce00-c5f9-11ea-9d77-71676dcee9dd.png)
并无引用的地方 项目就会恢复正常

**Comment by cipchk** [comment]
抱歉，我无法重现不管是 windows 还是 mac，建议安装依赖时是不否完整。
