### ISSUE TITLE
主题切换报错

### ISSUE THREAD

**Issue by mrYmang** [ng-alain/ng-alain#1770]
按照文档的代码走了一遍后
const less = require('less');
const LessPluginCleanCSS = require('less-plugin-clean-css');
const LessPluginNpmImport = require('less-plugin-npm-import');
const fs = require('fs');
const darkThemeVars = require('@delon/theme/theme-dark');

const appStyles = 'src/styles.less'; // 应用的样式入口文件
const themeContent = `@import '${appStyles}';`;

less.render(themeContent, {
  javascriptEnabled: true,
  plugins: [new LessPluginNpmImport({ prefix: '~' }), new LessPluginCleanCSS({ advanced: true })],
  modifyVars: {
    ...darkThemeVars
  }
}).then(data => {
  fs.writeFileSync(
    // 主题样式的输出文件
    'src/assets/style.dark.css',
    data.css
  )
}).catch(e => {
  // 记录渲染错误
  console.error(e);
});

发现一直在报这个错，

./node_modules/less-plugin-clean-css/node_modules/clean-css/lib/clean.js
Module not found: Error: Can't resolve 'fs' in 'G:\bigdata1.0.1\geometry-bi-ui\node_modules\less-plugin-clean-css\node_modules\clean-css\lib'

但该有的models文件都有了。

请问是哪里出问题了么。

![QQ图片20200716181328](https://user-images.githubusercontent.com/46770004/87659508-41b7bd00-c790-11ea-98a7-b718af4d1497.png)

**Comment by cipchk** [comment]
看起来像是缺少 `fs` 模块，试着重装安装一个所有依赖，我刚去查了相关的 依赖包，最近并没有更新纪录，所以只能 如此推断了。

**Comment by mrYmang** [comment]
> 看起来像是特定`fs`模块，试着重装安装一个所有依赖，我刚去查了相关的依赖包，最近并没有更新纪录，所以只能如此如此了。

是我弄错了，我是将这段代码写在项目的ts文件里的，万分抱歉。

**Comment by cipchk** [comment]
已解决，关闭了。
