### ISSUE TITLE
@delon 样式依赖导致无法生成 alain-default.less

### ISSUE THREAD

**Issue by yihango** [ng-alain/ng-alain#1774]
- ng-alain version: 9.5.3
- Angular version: 10.0.3
## 【必填项】重现链接，Reproduction link
无

## 重现步骤，Steps to reproduce
* 下载默认模板
* 移除 `@delon/chart` 依赖
* 执行 `npm run color-less`
![image](https://user-images.githubusercontent.com/26987099/87753978-6b2b2400-c836-11ea-83c1-149771271957.png)

## 问题原因
`@delon/abc` 组件样式依赖  `@delon/theme/theme-default.less` ， `@delon/theme/theme-default.less`  强依赖 `@delon/chart/theme-default.less`

以上依赖关系导致不安装 `@delon/chart` 就无法生成全局样式 `alain-default.less`

**Comment by cipchk** [comment]
是的，因为会有一些主题变量的依赖，虽然有这和中依赖 ，但是 它不会对您的包体有任何影响 ，只是单纯开发上需要这种依赖而已 。

**Comment by yihango** [comment]
> 是的，因为会有一些主题变量的依赖，虽然有这和中依赖 ，但是 它不会对您的包体有任何影响 ，只是单纯开发上需要这种依赖而已 。

也就是说把 `@delon/chart` 放到 `devDependencies` 中就行了对吧？

那么生成的样式文件体积会变大吗？还是说是几乎可以忽略的大小？

**Comment by cipchk** [comment]
是 `0` 字节。
