### ISSUE TITLE
Cannot build ng-alain

### ISSUE THREAD

**Issue by priyanperera** [ng-alain/ng-alain#1778]
I followed the documentation but when trying to build I get the following errors.

Property 'settings' is private and only accessible within class 'HeaderComponent'.
Can't bind to 'nzAutocomplete' since it isn't a known property of 'input'.
'nz-autocomplete' is not a known element:
'nz-auto-option' is not a known element:
Can't bind to 'nzValue' since it isn't a known property of 'nz-auto-option'.

I tried building first but the result was the same.

What am I doing wrong?

**Comment by cipchk** [comment]
Should be import [NzAutocompleteModule](https://github.com/ng-alain/ng-alain/blob/master/src/app/shared/shared-zorro.module.ts#L80) module in `shared-zorro.module.ts`.
