### ISSUE TITLE
PageHeader组件当前页面链接错误

### ISSUE THREAD

**Issue by xingkoo** [ng-alain/ng-alain#1780]
- ng-alain version: X.Y.Z
- Angular version: X.Y.Z

## 【必填项】重现链接，Reproduction link

访问Url地址如下：
http://192.168.2.5:4200/#/article/video;videoStatus=3

PageHeader组件生成的导航器，最后一项地址链接为以下格式：
http://192.168.2.5:4200/#/article/video%3BvideoStatus%3D3

是不可以正常访问的，如果上面我使用的传参链接没有用错的话，这应该是个bug吧？

**Comment by cipchk** [comment]
目前使用的 `routerLink` 指令，而且没有提供 `queryParams` 这种参数，所以才会生成这类格式，这是 `routerLink` 内部机制决定的。

建议使用这种路由配置 `http://192.168.2.5:4200/#/article/video/3`。
