### ISSUE TITLE
g2-water-wave 水波图有没有办法可以实现图表宽高根据容器自适应

### ISSUE THREAD

**Issue by Xiaofanaili** [ng-alain/ng-alain#1786]
想要实现水波图宽高自适应，有没有什么方法？
获取容器高度后，重新赋值给height，图表渲染异常

**Comment by cipchk** [comment]
如果你想父元素改变时重新自定义，恐怕你需要配合 [nz-resizable](https://ng-zorro.gitee.io/experimental/resizable/en) 并在 `nzResize` 触发时，重新调用组件的 `updateRadio()` 方法。

**Comment by Xiaofanaili** [comment]
利用 nz-resizable 调用updateRadio()方法，图表绘制异常，显示为正方形非圆形

**Comment by cipchk** [comment]
@Xiaofanaili 能否做个重现？

**Comment by Xiaofanaili** [comment]
重现链接：
https://stackblitz.com/edit/ng-alain-setup-7cfjag
（箭头向上拖动）

**Comment by cipchk** [comment]
尝试增加

```diff
- this.waterComp.updateRadio();
+ (this.waterComp as any).renderChart(false);
```

**Comment by Xiaofanaili** [comment]
链接：https://stackblitz.com/edit/ng-alain-setup-7cfjag
改变高度时仍然异常，改变宽度正常

**Comment by cipchk** [comment]
`onResize` 的触发频率太高了，建议增加一些延迟的处理。另外，这个组件目前在 G2 4.0 不好实现，会跟进 G2，介时再进行重写吧。

**Comment by Xiaofanaili** [comment]
图表颜色是只能渐变吗？还是可以设置为纯色？
有没有销毁图表的方法，重绘图表的方法？
