### ISSUE TITLE
ng-alain从8.x升级到最新版本9.5.5后，动态组件功能无法使用

### ISSUE THREAD

**Issue by anterwx** [ng-alain/ng-alain#1787]
ng-alain从8.x升级到最新版本9.5.5后，动态组件功能无法使用，Angular是最新版本10.0.3，猜测跟Angular本身有关。

`export class TabLazyComponent implements OnInit {
    @Input() tabItem: TabItem;
    @ViewChild(TabDirective, { static: true }) tabHost: TabDirective;

    constructor(private componentFactoryResolver: ComponentFactoryResolver) { }

    ngOnInit() {
        if (this.tabItem) {
            this.loadComponent();
        }
    }

    loadComponent() {
        const componentFactory = this.componentFactoryResolver.resolveComponentFactory(this.tabItem.component);
        const viewContainerRef = this.tabHost.viewContainerRef;
        viewContainerRef.clear();
        const componentRef = viewContainerRef.createComponent(componentFactory);
        (componentRef.instance as TabComponent).data= this.tabItem.data;
    }
}`

**Comment by cipchk** [comment]
目前还没有稳定适配 angular 10 版本，建议使用 angular9。
