### ISSUE TITLE
reuse-tab复用,当前页包含page-header时,刷新后reuse-tab丢失

### ISSUE THREAD

**Issue by liang0213** [ng-alain/ng-alain#1789]
- ng-alain version: 10.0.0-beta.1
- Angular version:  10.0.3

![image](https://user-images.githubusercontent.com/13412697/88288191-fd936200-cd25-11ea-8ce0-ef417e289a15.png)
![image](https://user-images.githubusercontent.com/13412697/88288225-084df700-cd26-11ea-8d1e-5eaa774c0a8a.png)

01.开启多个标签,且使用page-header时
02.当前页面包含page-header,刷新后当前reuse-tab 丢失

**Comment by cipchk** [comment]
还未对 angular10 进行适配，发布时间以 [release](https://github.com/ng-alain/ng-alain/releases) 为准。

**Comment by core2duoe6420** [comment]
实际上这个问题9.x也存在，可以这样重现：
```
git clone https://github.com/ng-alain/ng-alain
cd ng-alain
git checkout 9.5.5
vim src/app/global-config.module.ts # 取消45-51行关于RouteReuseStrategy的注释
vim src/app/shared/shared-delon.module.ts # 取消17,75行注释
vim src/app/layout/default/default.component.html # 在router-outlet上加入<reuse-tab #reuseTab></reuse-tab>
npm install
npm run start
```
然后按照楼主的步骤即可重现
