### ISSUE TITLE
STMultiSort separator to support for the array type request parameter

### ISSUE THREAD

**Issue by myatmin** [ng-alain/ng-alain#1791]
As of current, **`&`** character from `separator` attribute of  `STMultiSort` being encoded in the request URL.
`multiSort: { key: 'sort', separator: '&sort=', nameSeparator: ',' }` results to `/api/person?page=0&size=10&sort=name,asc%26sort=age,desc`

In order to be request param as array, parameter name should be added multiply as below.
`/api/person?page=0&size=10&sort=name,asc&sort=age,desc`

**Comment by cipchk** [comment]
Array is indeed not supported currently.

**Comment by cipchk** [comment]
@myatmin A temporary solution, you can do a process through `req.process`.

**Comment by myatmin** [comment]
Thank you, @cipchk !
