### ISSUE TITLE
STColumn+page分页 filter筛选 如果不在第一页 offset传值不为0

### ISSUE THREAD

**Issue by Liutaogit** [ng-alain/ng-alain#1792]
- ng-alain version:9.5.5
- Angular version: 9.1.11
STColumn+page分页 filter筛选 如果不在第一页 offset传值不为0 所有筛选不到数据

**Comment by cipchk** [comment]
@Liutaogit 麻烦提供一个重现示例。

**Comment by Liutaogit** [comment]
ST列表后台请求数据，跳转至第二页以后，在列头搜索🔍，offset请求传参数为页数*10,正确的应该offset修改为0.不然查询数据可能不显示。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "卡色"<notifications@github.com&gt;; 
发送时间: 2020年7月30日(星期四) 中午11:03
收件人: "ng-alain/ng-alain"<ng-alain@noreply.github.com&gt;; 
抄送: "&amp;#x1F61A;&amp;#x1F631;&amp;#x1F61C;星陨如雨"<624132316@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [ng-alain/ng-alain] STColumn+page分页 filter筛选 如果不在第一页 offset传值不为0 (#1792)





 
@Liutaogit 麻烦提供一个重现示例。
