### ISSUE TITLE
是否可以单独使用 delon/abc 组件库

### ISSUE THREAD

**Issue by screamsyk** [ng-alain/ng-alain#1793]
如题，如果能单独再项目中使用 delon/abc 组件库的话，用 st se 这些组件会很方便，也不需要其他 ng-alain 的东西

**Comment by cipchk** [comment]
导入组件模块与样式即可以，例如 `se`：

```less
# styles.less
@import '~@delon/abc/se/style/index';
```

至于模块引用，请参考 [shared-delon.module.ts](https://github.com/ng-alain/ng-alain/blob/master/src/app/shared/shared-delon.module.ts#L46).
