### ISSUE TITLE
采用路由复用后，打开一个select框后，路由自动跳转到其他页面，select框无法关闭

### ISSUE THREAD

**Issue by Tinet-zhangmd** [ng-alain/ng-alain#1795]
![image](https://user-images.githubusercontent.com/49385806/88889506-d29f9580-d272-11ea-8651-70366102e3c4.png)
![image](https://user-images.githubusercontent.com/49385806/88889540-e0edb180-d272-11ea-90a1-e3cf1f1439e4.png)
复现步骤
1：在ng-alain项目中，采用reuse-tab功能
2：在table-list.component.ts的ngOnInit钩子中添加
setTimeout(() => {
      this.router.navigate(['/pro/form/basic-form'])
    }, 5000)
3: 查询表格页面的 使用状态select框，路由跳转后，select框无法关闭，且页面其他区域也无法点击了

**Comment by cipchk** [comment]
目前 NG-ZORRO 没有提供统一的处理接口，有人在 [#3162](https://github.com/NG-ZORRO/ng-zorro-antd/issues/3162) 提到过，建议至 ng-zorro-antd 上提交这个需求。
