### ISSUE TITLE
page-header导致刷新整个页面时当前路由为菜单访问路径时复用标签异常

### ISSUE THREAD

**Issue by mostermsater** [ng-alain/ng-alain#1796]
- ng-alain version: 9.5.5
- Angular version: 9.1.6

## 重现步骤，Steps to reproduce
启用路由复用
比方说我现在在菜单路由下 用户管理 页面
这时候直接刷新整个页面 按理说 会有一个用户管理的复用标签。在用户管理页面加page-header时，复用标签没有，不加就有。
导致这个问题的原因是page-header.component.ts构造方法里有一个merge事件合并订阅中的路由事件订阅
merge(
      menuSrv.change.pipe(filter(() => this.inited)),
      router.events.pipe(filter((ev) => ev instanceof NavigationEnd)),
      i18nSrv.change,
    )
      .pipe(takeUntil(this.unsubscribe$))
      .subscribe((e) => {
        this.refresh();
      });
我不清楚这个路由订阅在这的作用
但是把路由订阅删除掉即能正常工作

**Comment by mostermsater** [comment]
这个和[https://github.com/ng-alain/ng-alain/issues/1789]是同一个问题

**Comment by cipchk** [comment]
请尝试最新版本是否问题依旧，`page-header` 有过好几个版本的迭代。关闭此 issues，如果有其他细节请重新打开或发布新的 issues。

**Comment by hsh007** [comment]
11版本也还有这个问题
