### ISSUE TITLE
关于主题切换的一些问题。

### ISSUE THREAD

**Issue by mrYmang** [ng-alain/ng-alain#1797]
看到主题切换中有两段，代码。
第一段
const less = require('less');
const LessPluginCleanCSS = require('less-plugin-clean-css');
const LessPluginNpmImport = require('less-plugin-npm-import');
const fs = require('fs');
const darkThemeVars = require('@delon/theme/theme-dark');

const appStyles = 'src/styles.less'; // 应用的样式入口文件
const themeContent = `@import '${appStyles}';`;

less.render(themeContent, {
  javascriptEnabled: true,
  plugins: [new LessPluginNpmImport({ prefix: '~' }), new LessPluginCleanCSS({ advanced: true })],
  modifyVars: {
    ...darkThemeVars
  }
}).then(data => {
  fs.writeFileSync(
    // 主题样式的输出文件
    'src/assets/style.dark.css',
    data.css
  )
}).catch(e => {
  // 记录渲染错误
  console.error(e);
});
第二段：
changeTheme(theme: 'default' | 'dark'): void {
  if (theme === 'dark') {
    const style = document.createElement('link');
    style.type = 'text/css';
    style.rel = 'stylesheet';
    style.id = 'dark-theme';
    style.href = 'assets/style.dark.css';
  } else {
    const dom = document.getElementById('dark-theme');
    if (dom) {
      dom.remove();
    }
  }
}

使用第二段代码的话能成功的切换主题，但是使用第一段代码的话就会报错，后来查找后发现这似乎是一段node代码，所以请问一下，这段代码是写在项目中哪里的，对node不太熟悉，也不知道怎么用，请大佬能够指点一下，万分感谢。

**Comment by cipchk** [comment]
相关的两处代码：

- https://github.com/ng-alain/ng-alain/blob/master/scripts/color-less.js
- https://github.com/ng-alain/ng-alain/blob/master/package.json#L37

**Comment by mrYmang** [comment]
好的，谢谢大佬。
