### ISSUE TITLE
ST组件渲染完成后，reset()等事件无法重新定义宽度

### ISSUE THREAD

**Issue by BennyCxb** [ng-alain/ng-alain#1805]
### Reproduction link
[https://stackblitz.com/edit/ng-alain-setup-vtdhx3?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/edit/ng-alain-setup-vtdhx3?file=src%2Fapp%2Fapp.component.ts)

### Steps to reproduce
输入宽度，点击提交，st1的columns没有变化
![image](https://user-images.githubusercontent.com/36026131/89275491-eaad5580-d674-11ea-928f-3a3f39e9ce0b.png)

### What is expected?
输入宽度，点击提交，st1的columns根据设定的宽度而变化

### What is actually happening?
输入宽度，点击提交，st1的columns没有变化

| Environment | Info |
|---|---|
| ng-alain | 9.5.5 |
| Browser | 84.0.4147.105 |

**Comment by cipchk** [comment]
临时解决办法是手动维护 `widthConfig` 值。
