### ISSUE TITLE
autocomplete in SFStringWidgetSchema not working

### ISSUE THREAD

**Issue by InbarTakdim** [ng-alain/ng-alain#1806]
### Reproduction link
[https://stackblitz.com/edit/ng-alain-setup](https://stackblitz.com/edit/ng-alain-setup)

### Steps to reproduce

```ts
ngOnInit() {
		this.schema = {
			properties: {
				departmentName: {
					type: 'string',
					title: this.i18n.fanyi('settings.vehicle.department-name'),
					ui: {
						autofocus: true,
						focus: (e) => {
							debugger;
						},
					} as SFStringWidgetSchema
				},
}
}
```

### What is expected?
when the schema is loaded the focuse should be on the input

### What is actually happening?
no focus

| Environment | Info |
|---|---|
| ng-alain | 9.5.5 |
| Browser | chrome |

**Comment by cipchk** [comment]
@InbarTakdim  If you open the chrome developer tools in debugging, the auto focus will not work.

**Comment by InbarTakdim** [comment]
the tools is close now, and still not working @cipchk

**Comment by InbarTakdim** [comment]
@cipchk  I did npm i and still getting the error, how should I use your solution?

**Comment by InbarTakdim** [comment]
and thanks for your quick response!

**Comment by cipchk** [comment]
Will be updated in version `10`, a temporary solution:

```ts
ngOnInit() {
		this.schema = {
			properties: {
				departmentName: {
					type: 'string',
					title: this.i18n.fanyi('settings.vehicle.department-name'),
					ui: {
						class: 'needAutoFocs',
						autofocus: true,
						focus: (e) => {
							debugger;
						},
					} as SFStringWidgetSchema
				},
  }
  setTimeout(() => {
	document.querySelector('.needAutoFocs .ant-input').focus();
  }, 100);
}
```
