### ISSUE TITLE
ST - set total not working

### ISSUE THREAD

**Issue by InbarTakdim** [ng-alain/ng-alain#1809]
### Reproduction link
[https://stackblitz.com/edit/ng-alain-setup](https://stackblitz.com/edit/ng-alain-setup)

### Steps to reproduce
I used ST with pagination. every time the server returns 4 item (pushed to the original array). I want to set the total number but it's not working. it takes the length of the array and set automatically the total to 4 and present only one page.
I read in the documentation about nzServerRender but it seems that the documentation isn't updated.
I need a response ASAP, it's for production version.

### What is expected?
total will change

### What is actually happening?
total set to data.length

| Environment | Info |
|---|---|
| ng-alain | 9.5.5 |
| Browser | chrome |

---
<st *ngIf="total" #st [data]="data" [columns]="columns" [expand]="expand" expandRowByClick expandAccordion [loading]="loading"
	(change)="handleClick($event)" [rowClassName]="rowClass" [noResult]="noResult" ps="4" [total]="total">

**Comment by cipchk** [comment]
Pls try set `page.front` is `true`, detail refer to https://ng-alain.com/components/st/en#Static

**Comment by InbarTakdim** [comment]
tried, still not working. @cipchk

**Comment by cipchk** [comment]
provide a reproduction link?

**Comment by InbarTakdim** [comment]
<st *ngIf="total" #st [data]="data" [columns]="columns" [expand]="expand" expandRowByClick expandAccordion [loading]="loading" [page]="page"
	(change)="handleClick($event)" [rowClassName]="rowClass" [noResult]="noResult" ps="4" [total]="total">
------------------------------------------------------------------------------------------------
	data: AlertViewDtoImp[] = [];
	total:number=10;
	page:STPage={
		front:true
	};

	ngOnInit(): void {
		this.subscriber = this.dataRefreshService.init().subscribe(() => {
			this.getData();
		});
	}

	getData() {
		this.loading = true;
		let params = this.filterParams as AlertQueryInfoImp;
		this.alertListService.getAlertList(params).then((res) => {
			if (res.success && res.data) {
				this.data = res.data.getValues().sort((a, b) => {
					if (a.notifyOn.getValue() > b.notifyOn.getValue()) return -1;
					else if (a.notifyOn.getValue() < b.notifyOn.getValue()) return 1;
					return 0;
				});
				this.loading = false;
			}
			if (this.detailedElement) {
				this.replaceElement(this.detailedElement);
			}
		});
	}

**Comment by cipchk** [comment]
try `[page]="{ front: false }"`, and maintains `(change)` when the page changes to reload data.

**Comment by InbarTakdim** [comment]
solved! Thanks for the quick response...have a good day
