### ISSUE TITLE
Have some confusion

### ISSUE THREAD

**Issue by ohmygodoh** [ng-alain/ng-alain#181]
First, your frame is truly a better framework
Recently, the second, I have some confusion here, recent read the document of ant-design base angular version , it's  demo is embedded in the document, but found no feeling in the beginning to open the index page here need some time to load components, want to ask, what the ng-alain framework needs some time to load?Or the document doing some technical processing?

**Comment by ohmygodoh** [comment]
第一、你的框架整体上确实是一个比较好用的框架
第二、最近在看ant-design的“angular”版本，它的demo是嵌入到它的文档里面的，但是发现打开这里的页面并没有感觉刚开始的时候需要一些时间去加载组件，我想知道，这个框架需要一些时间去加载什么东西？或者他们那边做了什么技术处理？

**Comment by cipchk** [comment]
需要时间一般都是懒加载网络的原因。ng.ant.design 默认情况下启动时就立刻加载 所有懒加载模块的脚本，所以看起来更快。

**Comment by ohmygodoh** [comment]
我理解就是说，所有模块如果都是懒加载，看起来就要快一些是吗？

**Comment by cipchk** [comment]
https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/src/showcase/app.module.ts#L28

**Comment by ohmygodoh** [comment]
thanks！

**Comment by ohmygodoh** [comment]
您好，作者，我现在如果想缩短一开始进去，出现的那个蓝屏加载的时间，要怎么做？谢谢

**Comment by cipchk** [comment]
其决于脚本下载、angular启动结束后开始渲染组件树这段时间里，是启动动画的时间。中间无任何额外的时间。

因此，你想快嘛，一是想办法加快脚本下载，二是去掉动画，从视觉感观上感觉是短了一点，因为目前的动画结束后100ms的渐变效果。

**Comment by ohmygodoh** [comment]
好的，谢谢
