### ISSUE TITLE
SF中object的卡片容器type=default的时候布局有问题

### ISSUE THREAD

**Issue by 694551594** [ng-alain/ng-alain#1813]
### Reproduction link
[https://stackblitz.com/edit/angular-gdt3qb?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-gdt3qb?file=src/app/app.component.ts)

### Steps to reproduce
1、Object为card类型，里面每个小部件span=24。2、修改为default类型，查看布局，本来card正常的布局变为了一行。

### What is expected?
default布局下的效果和card的布局效果一致

### What is actually happening?
default布局下的效果挤在了一行。

| Environment | Info |
|---|---|
| ng-alain | 9.5.5 |
| Browser | google |

**Comment by 694551594** [comment]
![image](https://user-images.githubusercontent.com/17873626/89786913-41bc9a00-db4f-11ea-8cb1-5cde3f21075b.png)
![image](https://user-images.githubusercontent.com/17873626/89786923-441ef400-db4f-11ea-95be-b5ee49b7e6d0.png)

    schema: SFSchema = {
        properties: {
            name: { type: 'string' },
            age: { type: 'number' },
            address1: {
                title: '地址1',
                type: 'object',
                properties: {
                    country: {
                        type: 'string',
                        ui: {
                            grid: { span: 24 },
                        }
                    },
                    city: {
                        type: 'string',
                        ui: {
                            grid: { span: 24 },
                        }
                    },
                    zone: {
                        type: 'string',
                        ui: {
                            grid: { span: 24 },
                        }
                    },
                },
                ui: {
                    type: 'card',
                    spanLabelFixed: 150,
                    grid: { span: 24 },
                } as SFObjectWidgetSchema,
            },
            address2: {
                title: '地址2',
                type: 'object',
                properties: {
                    country: {
                        type: 'string',
                        ui: {
                            grid: { span: 24 },
                        }
                    },
                    city: {
                        type: 'string',
                        ui: {
                            grid: { span: 24 },
                        }
                    },
                    zone: {
                        type: 'string',
                        ui: {
                            grid: { span: 24 },
                        }
                    },
                },
                ui: {
                    type: 'default',
                    spanLabelFixed: 150,
                    grid: { span: 24 },
                } as SFObjectWidgetSchema,
            },
        },
        required: ['name', 'age'],
        ui: {
            spanLabelFixed: 150,
            grid: { span: 24 }
        }
    };

**Comment by cipchk** [comment]
临时解决办法，在 `styles.less` 增加:

```less
.sf__fixed {
  flex-flow: row wrap;
}
```
