### ISSUE TITLE
用户认证是否可以对某个路由或页面忽略token检测。

### ISSUE THREAD

**Issue by mrYmang** [ng-alain/ng-alain#1818]
## What problem does this feature solve?
对于某个页面或某个路由进行免登查看。

## What does the proposed API look like?
想对某个页面进行免登查看，但都会进行令牌检测从而回到登录页面。
但查看文档似乎只发现了忽略以及allow_anonymous_key，似乎只能操作接口而非整个页面。
请问需要如何实现。
使用的是angular9以及ng-alain 9.5.1的版本
在routes-routing.module.ts中是这么配置路由的
{path：'view'，loadChildren：（）=> import（'./ view / view.module'）。然后（m => m.ViewModule）}，

**Comment by cipchk** [comment]
可以使用 `_allow_anonymous` 它足够自由，我觉得没有必要增加这类需求。

> `_allow_anonymous` 这个字符串也可以通过全局配置进行修改，可以跟后端有个进行一个匹配，对某个字符统一不进行校验。
