### ISSUE TITLE
功能需求

### ISSUE THREAD

**Issue by xingkoo** [ng-alain/ng-alain#182]
需要一个输入框的自动完成及提示功能，参考链接
http://angular-ui.github.io/bootstrap/#!#typeahead
ng-ant里面也没有相关文档，似乎没有这个功能。ng-alain不知道能不能封装一个？

**Comment by cipchk** [comment]
ng-alain 不会做基础组件的事。不久之后  ng-zorro-antd 将会有 autocomplete 之类的。
