### ISSUE TITLE
对SF的单项自定义Validator时, 无法通过全局的validator()调用检测

### ISSUE THREAD

**Issue by Kreedzt** [ng-alain/ng-alain#1820]
### Reproduction link
[https://stackblitz.com/edit/ng-alain-setup-zqk3zn?devtoolsheight=33&file=src/app/app.component.ts](https://stackblitz.com/edit/ng-alain-setup-zqk3zn?devtoolsheight=33&file=src/app/app.component.ts)

### Steps to reproduce
该demo为密码二次确认demo, 二次密码不一致时, 调用sf.validator()后, 单项字段valid为false, sf的valid为true(此时应该为false)

### What is expected?
sf的valid为true(此时应该为false)

### What is actually happening?
sf的valid为true

| Environment | Info |
|---|---|
| ng-alain | 9.5.5 |
| Browser | Firefox Dev Edition 81.0b2 |

---
在复杂自定义validator表单中, 该功能很常用

**Comment by ZhangYi520** [comment]
哇哇哇

**Comment by cipchk** [comment]
尝试升级至 `9.5.5`，其实无须调用 `validator`，例如：https://stackblitz.com/edit/ng-alain-setup-1swbey?file=src%2Fapp%2Fapp.component.ts

**Comment by taipeiwu** [comment]
@cipchk 

依照你的例子，当 customField1 及 customField2 栏位的内容都填妥且相符后，这时变动 customField1 栏位的资料是无法进行即时与 customField2 栏位资料重新检核校验的问题，sf.valid 还是为 true，正确来说，当变动 customField1 时，customField2 应显示 "输入不一致" 信息，请问有什么方法在 sf 内可达到此功能? 最常使用就是用于两次密码的验证，谢谢。
