### ISSUE TITLE
MenuService setItem not updated the menu

### ISSUE THREAD

**Issue by InbarTakdim** [ng-alain/ng-alain#1824]
### Reproduction link
[https://github.com/ng-alain/ng-alain/issues/new/choose](https://github.com/ng-alain/ng-alain/issues/new/choose)

### Steps to reproduce
this.menuService.add(res.menu);		
let item = this.menuService.getItem('settings');
item.hide= true;
this.menuService.setItem('settings', item);

### What is expected?
that 'setting' will be hidden

### What is actually happening?
'settings' shows in the menu

| Environment | Info |
|---|---|
| ng-alain | 9.5.5 |
| Browser | chrome |

**Comment by InbarTakdim** [comment]
@cipchk  I really need your help

**Comment by cipchk** [comment]
A temporary solution

```diff
- item.hide= true;
+ item._hidden= true;
```

**Comment by InbarTakdim** [comment]
@cipchk  thanks
