### ISSUE TITLE
sf 级联 select 当enum是 {label: 'xxx', value: 'xx'} 形式时 默认选中问题

### ISSUE THREAD

**Issue by yuuuxt** [ng-alain/ng-alain#1825]
### Reproduction link
[https://stackblitz.com/edit/angular-bxe8gt?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-bxe8gt?file=src/app/app.component.ts)

### Steps to reproduce
请见重现链接. 切换一级选项后, 二级选项并未被设置为默认值(对应代码: `cityProperty.widget.reset(items[0])`)

### What is expected?
与https://ng-alain.com/form/select/zh#form-select-coordinate 一致(重现链接为该案例修改cityData数据得到)

### What is actually happening?
不能显示默认值

| Environment | Info |
|---|---|
| ng-alain | 9.5.5 |
| Browser | firefox 80.0 |

**Comment by cipchk** [comment]
抱歉，我无法理解，这里的重现示例中并没有指定 `default`。

麻烦提供一个重现步骤。

**Comment by yuuuxt** [comment]
> 
> 
> 抱歉，我无法理解，这里的重现示例中并没有指定 `default`。
> 
> 麻烦提供一个重现步骤。

抱歉描述不清(下述说明已更新至正文). 

切换一级选项后, 二级选项并未被设置为默认值(对应代码: `cityProperty.widget.reset(items[0])`)

**Comment by cipchk** [comment]
`items[0]` 指的是一个 Object 并不是实际值，应该是 `items[0].value` 才对

**Comment by yuuuxt** [comment]
了解, 谢谢!
