### ISSUE TITLE
sf cascader 通过asyncData获取静态数据问题

### ISSUE THREAD

**Issue by yuuuxt** [ng-alain/ng-alain#1826]
### Reproduction link
[https://stackblitz.com/edit/angular-b45ieb?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-b45ieb?file=src/app/app.component.ts)

### Steps to reproduce
请见重现示例的报错

### What is expected?
允许重现示例中写法. 参照文档, 是可以从`asyncData`指一次性获取数据的.

### What is actually happening?
重现示例报错.

| Environment | Info |
|---|---|
| ng-alain | 9.5.5 |
| Browser | firefox 80.0 |

**Comment by cipchk** [comment]
`asyncData` 必须返回一个 `Promise`，示例中应该加上 `this.getData().toPromise()`

**Comment by yuuuxt** [comment]
> 
> 
> `asyncData` 必须返回一个 `Promise`，示例中应该加上 `this.getData().toPromise()`

在重现示例中将`asyncData: () => this.getData()`改为`asyncData: () => this.getData().toPromise()`后, 似乎仍不是预期结果? 还请帮忙看下, 谢谢

**Comment by cipchk** [comment]
请自行参考：https://ng-alain.com/form/cascader/en#form-cascader-simple

**Comment by yuuuxt** [comment]
> 请自行参考：https://ng-alain.com/form/cascader/en#form-cascader-simple

我之前就是参考这个链接的，但是我的需求如重现链接一样，数据源给出静态数据(已含有isleaf)的observable, 想通过asyncData直接接收(类似select组件)，而这里的async需要node 与index
