### ISSUE TITLE
SFCascaderWidgetSchema show the "previous" elements's children when its children is null

### ISSUE THREAD

**Issue by InbarTakdim** [ng-alain/ng-alain#1827]
### Reproduction link
[https://stackblitz.com/edit/ng-alain-setup](https://stackblitz.com/edit/ng-alain-setup)

### Steps to reproduce

```ts
{
			type: 'number',
			title: this.i18n.fanyi('app.filter.label.department'),
			ui: {
				changeOnSelect:true,
				widget: 'cascader',
				placeholder: this.i18n.fanyi('vehicle.filter.placeholder.department'),
				class: 'selected-department',
				allowClear: true,
				showArrow: true,
				menuClassName: 'departments-menu',
				columnClassName: 'department-column',
				change: (value: number[]) => {
					onChange(value);
				},
				asyncData: (node) => {
					if (node.level >= 0) {
						return this.departmentWidgetService.getRolesByDepartment(node);
					} else {
						return new Promise(resolve => {
							setTimeout(() => {
								this.departmentWidgetService.initDepartments().then((res) => {
									(node as any).children = res;
									resolve();
								});
							},);
						});
					}
				},
			} as SFCascaderWidgetSchema,
		};
```

in this case if i choose something that has children and then something without children it still show the children of the previous one.

### What is expected?
if there are no children - don't show the "children menu"

### What is actually happening?
showing the children of the previous one

| Environment | Info |
|---|---|
| ng-alain | 9.5.5 |
| Browser | chrome |

**Comment by InbarTakdim** [comment]
@cipchk can you help me?

**Comment by cipchk** [comment]
Sorry, can you provide detailed steps? I think this is a querstion of logical processing. You can provide whatever `children` needs.

**Comment by InbarTakdim** [comment]
@cipchk 

this is the schema:
{
			type: 'number',
			title: this.i18n.fanyi('app.filter.label.department'),
			ui: {
				changeOnSelect:true,
				widget: 'cascader',
				placeholder: this.i18n.fanyi('vehicle.filter.placeholder.department'),
				class: 'selected-department',
				allowClear: true,
				showArrow: true,
				menuClassName: 'departments-menu',
				columnClassName: 'department-column',
				change: (value: number[]) => {
					onChange(value);
				},
				asyncData: (node) => {
					if (node.level >= 0) {
						return this.departmentWidgetService.getRolesByDepartment(node);
					} else {
						return new Promise(resolve => {
							setTimeout(() => {
								this.departmentWidgetService.initDepartments().then((res) => {
									(node as any).children = res;
									resolve();
								});
							},);
						});
					}
				},
			} as SFCascaderWidgetSchema,
		};


--------------------------------------------------

initDepartments(): Promise<NzCascaderOption[]> {
		return new Promise((resolve) => {
			this.vehicleApiService.getDepartmentOptions().then((res: ControllerResponse<ext.TypedArray<DepartmentImp>>) => {
				if (res.success && res.data) {
					this._departmentNodes = [];
					let departmentOption;
					this.departments = res.data.getValues();
					for (const department of this.departments) {
						departmentOption = {
							title: department.name,
							label: department.name,
							value: department.id,
							key: department.id,
							parent: 0,
							level: 0,
							children: [],
						};
						this._departmentNodes.push(departmentOption);
					}
					resolve(this._departmentNodes);
				}
			});
		})
	}


	async getRolesByDepartment(node): Promise<void> {
			return await this.vehicleApiService.getRolesByDepartment(node.value).then((res: ControllerResponse<ext.TypedArray<DepartmentImp>>) => {
				if (res.success && res.data) {
					const roles = res.data.getValues();
					this.departments = this.departments.concat(roles);
					if (roles.length == 0) {
						 node.children = [];
						 node.isLeaf = true;
					} else {
						 node.isLeaf = false;
						 node.children = new Array();
						for (const role of roles) {
							node.children.push({
								level: 1,
								title: role.name,
								label: role.name,
								value: role.id,
								key: role.id,
								parent: node.id,
								//children: [],
								//isLeaf: true,
							});
						}
					}
				}else{
					node.isLeaf=true;
				}
			});
	}

**Comment by cipchk** [comment]
@InbarTakdim You can try set `isLeaf: true` when is not children.

**Comment by InbarTakdim** [comment]
here is the code: 
https://stackblitz.com/edit/angular-pnetaq?file=src/app/app.component.ts

please click on "1" (which has children) then click on "2" but we still see the children of 1.

**Comment by InbarTakdim** [comment]
<img width="237" alt="Screen Shot 2020-10-04 at 17 02 39" src="https://user-images.githubusercontent.com/15275755/95017684-7c304800-0663-11eb-87b4-94fe1abe70f3.png">
@cipchk 
I don't want to do isLeaf=true on "2" because I use async data and I don't know if it is a leaf or not, only after the user click on the item I do a server call to get its children.

**Comment by cipchk** [comment]
@InbarTakdim I think solve it can only include is leaf node data when the data return.

**Comment by InbarTakdim** [comment]
when the data return with no children I DO :
node.isLeaf = true
but problem still exists

**Comment by cipchk** [comment]
@InbarTakdim A working data:

```ts
const provinces = [
  {
    value: "1",
    label: "1"
  },
  {
    value: "2",
    label: "2",
    isLeaf: true
  }
];

const cities: {
  [key: string]: Array<{ value: string; label: string; isLeaf?: boolean }>;
} = {
  1: [
    {
      value: "1.1",
      label: "1.1",
      isLeaf: true
    },
    {
      value: "1.2",
      label: "1.2"
    }
  ]
};

const scenicspots: {
  [key: string]: Array<{ value: string; label: string; isLeaf?: boolean }>;
} = {
  1.2: [
    {
      value: "xihu",
      label: "West Lake",
      isLeaf: true
    }
  ]
};
```

**Comment by InbarTakdim** [comment]
I cant put on "2" isLeaf=true.
it's a asynchronous, this is the real code:

`	type: 'number',
			title: this.i18n.fanyi('app.filter.label.department'),
			ui: {
				widget: 'cascader',
				placeholder: this.i18n.fanyi('vehicle.filter.placeholder.department'),
				class: 'selected-department',
				allowClear: true,
				showArrow: true,
				changeOnSelect: false,
				menuClassName: 'departments-menu',
				columnClassName: 'department-column',
				change: (value: number[]) => {
					onChange(value);
				},
				asyncData: (node, index) => {
					if (index > -1) {
						return new Promise(resolve => {
							this.vehicleApiService.getRolesByDepartment(node.value).then((res: ControllerResponse<DepartmentImp[]>) => {
								node.loading = true;
								if (res.success && res.data) {
									const roles = res.data;
									node.children = new Array();
									let resp = null;
									node.isLeaf = true;
									for (const role of roles) {
										if (!resp) {
										resp = [];
											node.isLeaf = false;
										}
										resp.push({
											level: 1,
											title: role.name,
											label: role.name,
											value: role.id,
											key: role.id,
											parent: node.id,
										});
									}
									node.children = resp;
									node.loading = false;
								}
								resolve();
							});
						});
					} else {
						return new Promise(resolve => {
							setTimeout(() => {
								this.departmentWidgetService.initDepartments().then((res) => {
									(node as any).children = res;
									resolve();
								});
							},);
						});
					}
				},
			} as 

> SFCascaderWidgetSchema,`

**Comment by cipchk** [comment]
Sorry, We need the `isLeaf` value, I think the problem can only be solved from the back-end data.
