### ISSUE TITLE
设置主题预览报错，不生效

### ISSUE THREAD

**Issue by liqiantang** [ng-alain/ng-alain#1828]
### Reproduction link
[https://codesandbox.io/s/ng-alain-setup-dd0hq?file=/src/app/app.component.ts](https://codesandbox.io/s/ng-alain-setup-dd0hq?file=/src/app/app.component.ts)

### Steps to reproduce
请你到你们官方给的案例中点击左边的设置主题，然后进行预览，控制台会出现window.less.modifyVars is not a function
https://ng-alain.surge.sh/#/dashboard/v1

### What is expected?
可以预览主题

### What is actually happening?
无法预览

| Environment | Info |
|---|---|
| ng-alain | 9.5.5 |
| Browser | Chrome 85.0.4183.83 |

**Comment by cipchk** [comment]
我这里没有问题，估计是因为网络因素，导致无法访问 `https://gw.alipayobjects.com/os/lib/less.js/3.8.1/less.min.js`。
