### ISSUE TITLE
g2-single-bar 没有按照期望的显示长度

### ISSUE THREAD

**Issue by angelxg** [ng-alain/ng-alain#1830]
## What problem does this feature solve?
issue-helper 的错误报告无法下拉 版本 只能提到功能需求里了
我在表格中使用 g2-single-bar
没有按照期望的显示长度 比如value 都是7  2个长度不一样 

https://ng-alain.com/chart/single-bar/en
文档中的   min  max  参数描述好像也不对

## What does the proposed API look like?
N/A

**Comment by cipchk** [comment]
关于 `min`，`max` 的描述文档上有错误。

但是关于显示长度问题，麻烦提供一个重现示例。@angelxg
