### ISSUE TITLE
npm run hmr error after modified(修改代码后报错)

### ISSUE THREAD

**Issue by TAnsz** [ng-alain/ng-alain#1831]
### Reproduction link
[https://github.com/ng-alain/ng-alain](https://github.com/ng-alain/ng-alain)

### Steps to reproduce
git clone --depth=1 https://github.com/ng-alain/ng-alain.git

yarn

npm run hmr

modify code 修改任意界面代码

page blank, console error 页面空白，控制台报错：

Unhandled Promise rejection: Type DashboardV1Component is part of the declarations of 2 modules: RoutesModule and RoutesModule! 

 刷新后页面正常显示

### What is expected?
Auto refresh load new page 自动刷新加载新的页面

### What is actually happening?
console error:
Unhandled Promise rejection: Type DashboardV1Component is part of the declarations of 2 modules: RoutesModule and RoutesModule! Please consider moving DashboardV1Component to a higher module that imports RoutesModule and RoutesModule. You can also create a new NgModule that exports and includes DashboardV1Component then import that NgModule in RoutesModule and RoutesModule.
Type DashboardMonitorComponent is part of the declarations of 2 modules: RoutesModule and RoutesModule! Please consider moving DashboardMonitorComponent to a higher module that imports RoutesModule and RoutesModule. You can also create a new NgModule that exports and includes DashboardMonitorComponent then import that NgModule in RoutesModule and RoutesModule.
Type DashboardWorkplaceComponent is part of the declarations of 2 modules: RoutesModule and RoutesModule! Please consider moving DashboardWorkplaceComponent to a higher module that imports RoutesModule and RoutesModule. You can also create a new NgModule that exports and includes DashboardWorkplaceComponent then import that NgModule in RoutesModule and RoutesModule.
Type UserLoginComponent is part of the declarations of 2 modules: RoutesModule and RoutesModule! Please consider moving UserLoginComponent to a higher module that imports RoutesModule and RoutesModule. You can also create a new NgModule that exports and includes UserLoginComponent then import that NgModule in RoutesModule and RoutesModule.
Type UserRegisterComponent is part of the declarations of 2 modules: RoutesModule and RoutesModule! Please consider moving UserRegisterComponent to a higher module that imports RoutesModule and RoutesModule. You can also create a new NgModule that exports and includes UserRegisterComponent then import that NgModule in RoutesModule and RoutesModule.
Type UserRegisterResultComponent is part of the declarations of 2 modules: RoutesModule and RoutesModule! Please consider moving UserRegisterResultComponent to a higher module that imports RoutesModule and RoutesModule. You can also create a new NgModule that exports and includes UserRegisterResultComponent then import that NgModule in RoutesModule and RoutesModule.
Type UserLockComponent is part of the declarations of 2 modules: RoutesModule and RoutesModule! Please consider moving UserLockComponent to a higher module that imports RoutesModule and RoutesModule. You can also create a new NgModule that exports and includes UserLockComponent then import that NgModule in RoutesModule and RoutesModule.
Type CallbackComponent is part of the declarations of 2 modules: RoutesModule and RoutesModule! Please consider moving CallbackComponent to a higher module that imports RoutesModule and RoutesModule. You can also create a new NgModule that exports and includes CallbackComponent then import that NgModule in RoutesModule and RoutesModule. ; Zone: <root> ; Task: Promise.then ; Value: Error: Type DashboardV1Component is part of the declarations of 2 modules: RoutesModule and RoutesModule! Please consider moving DashboardV1Component to a higher module that imports RoutesModule and RoutesModule. You can also create a new NgModule that exports and includes DashboardV1Component then import that NgModule in RoutesModule and RoutesModule.

| Environment | Info |
|---|---|
| ng-alain | 9.5.5 |
| Browser | Microsoft Edge 85.0.564.51 |

---
Local projects from 8 to 9 also have this problem. 本地项目从8升到9后也有出现该问题.

**Comment by cipchk** [comment]
确保版本号的对应关系，比如 `9` 必须是所有 Angular & @delon 都为 `9.x`。

**Comment by TAnsz** [comment]
> 确保版本号的对应关系，比如 `9` 必须是所有 Angular & @delon 都为 `9.x`。

本地项目依赖如下，都是9.x版本，node_modules删除重新安装依赖，问题未解决。
官方示例项目直接clone下来未做任何更改，yarn安装依赖以后，运行也会有这样的错误。
```
"dependencies": {
    "@angular/animations": "~9.1.12",
    "@angular/cdk": "~9.2.4",
    "@angular/common": "~9.1.12",
    "@angular/compiler": "~9.1.12",
    "@angular/core": "~9.1.12",
    "@angular/forms": "~9.1.12",
    "@angular/platform-browser": "~9.1.12",
    "@angular/platform-browser-dynamic": "~9.1.12",
    "@angular/pwa": "~0.803.25",
    "@angular/router": "~9.1.12",
    "@angular/service-worker": "~9.1.12",
    "@antv/data-set": "^0.11.4",
    "@antv/g2": "^4.0.11",
    "@delon/abc": "^9.5.5",
    "@delon/acl": "^9.5.5",
    "@delon/auth": "^9.5.5",
    "@delon/cache": "^9.5.5",
    "@delon/chart": "^9.5.5",
    "@delon/form": "^9.5.5",
    "@delon/mock": "^9.5.5",
    "@delon/theme": "^9.5.5",
    "@delon/util": "^9.5.5",
    "@ngx-translate/core": "^12.1.2",
    "ajv": "^6.12.0",
    "editorconfig-tools": "^0.1.1",
    "husky": "^1.3.1",
    "lint-staged": "^8.1.0",
    "ng-zorro-antd": "^9.3.0",
    "ngx-tinymce": "^9.0.0",
    "ngx-ueditor": "^9.0.0",
    "prettier": "^1.16.1",
    "prettier-stylelint": "^0.4.2",
    "qrious": "^4.0.2",
    "rxjs": "~6.5.3",
    "screenfull": "^5.0.2",
    "tslib": "^1.10.0",
    "zone.js": "~0.10.3"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.901.12",
    "@angular/cli": "^9.1.12",
    "@angular/compiler-cli": "~9.1.12",
    "@angular/language-service": "~9.1.12",
    "@angularclass/hmr": "^2.1.3",
    "@delon/testing": "^9.5.2",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "@types/jszip": "^3.4.1",
    "@types/node": "^12.11.1",
    "antd-theme-generator": "^1.2.2",
    "codelyzer": "^5.1.2",
    "husky": "^4.2.3",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~5.0.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~2.1.0",
    "karma-jasmine": "~3.0.1",
    "karma-jasmine-html-reporter": "^1.5.0",
    "less-bundle-promise": "^1.0.7",
    "lint-staged": "^10.2.4",
    "ng-alain": "^9.5.5",
    "ng-alain-codelyzer": "^0.0.1",
    "prettier": "^2.0.5",
    "protractor": "~5.4.3",
    "stylelint": "^13.3.1",
    "stylelint-config-prettier": "^8.0.1",
    "stylelint-config-rational-order": "^0.1.2",
    "stylelint-config-standard": "^20.0.0",
    "stylelint-declaration-block-no-ignored-properties": "^2.3.0",
    "stylelint-order": "^4.0.0",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.2",
    "tslint-config-prettier": "^1.18.0",
    "typescript": "~3.8.3",
    "webpack-bundle-analyzer": "^3.6.1",
    "xlsx": "^0.16.1"
  },
```

**Comment by visionding** [comment]
同样遇到了这个问题，升级到10之后问题依旧

**Comment by cipchk** [comment]
我也没有遇到过，但感觉应该是 tsconfig.json 的配置引起多次加载模块？？？

**Comment by clong365** [comment]
https://github.com/angular/angular/issues/35265

和这个Issue相关，HMR和IVY一起用会出现这个错误。临时解决方案是用AOT编译：

A response from our friend: Simon Dragsbæk on StackOverFlow helped me...
Toggle on AOT in your angular.json config file, that should do it

**Here is the structure of where:**

> {
>   "projects": {
>     "x": {
>       "architect": {
>         "build": {
>           "options": {
>             "aot": true,
>           },
>           "configurations": {
>              "hmr": {
>               "aot": true
>             },
>             "local": {
>               "aot": true
>             }

**And run like this:**
`ng serve --aot=true`

In my case, since I have an additional configuration for **'hrm',** I execute this:
`ng serve --configuration hmr --aot=true`

_Originally posted by @1antares1 in https://github.com/angular/angular/issues/35265#issuecomment-593482782_

**Comment by TAnsz** [comment]
> [angular/angular#35265](https://github.com/angular/angular/issues/35265)
> 
> 和这个Issue相关，HMR和IVY一起用会出现这个错误。临时解决方案是用AOT编译：
> 
> A response from our friend: Simon Dragsbæk on StackOverFlow helped me...
> Toggle on AOT in your angular.json config file, that should do it
> 
> **Here is the structure of where:**
> 
> > {
> > "projects": {
> > "x": {
> > "architect": {
> > "build": {
> > "options": {
> > "aot": true,
> > },
> > "configurations": {
> > "hmr": {
> > "aot": true
> > },
> > "local": {
> > "aot": true
> > }
> 
> **And run like this:**
> `ng serve --aot=true`
> 
> In my case, since I have an additional configuration for **'hrm',** I execute this:
> `ng serve --configuration hmr --aot=true`
> 
> _Originally posted by @1antares1 in [angular/angular#35265 (comment)](https://github.com/angular/angular/issues/35265#issuecomment-593482782)_

`ng serve --configuration hmr --aot=true`
修改后能正常使用，非常感谢。
