### ISSUE TITLE
t 组件虚拟滚动 设置size为small 时，高度计算不正确，会有空白区域

### ISSUE THREAD

**Issue by ttnkh21** [ng-alain/ng-alain#1836]
### Reproduction link
[https://stackblitz.com/edit/angular-qjadfb-pmqgzk?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-qjadfb-pmqgzk?file=src/app/app.component.ts)

### Steps to reproduce
设置st的size属性为 small时， 如果y的高度大于600px，会出现空白区域，设置virtualItemSize属性后，依然会出现空白区域，但是滚动后会填满空白区域。
测试ng-zorro 没有问题

![image](https://user-images.githubusercontent.com/23454757/94639256-78708e80-030e-11eb-9491-dded2abf9914.png)

### What is expected?
正确计算内容高度

### What is actually happening?
内容高度计算不正确

| Environment | Info |
|---|---|
| ng-alain | 10.0.0 |
| Browser | 谷歌最新 |

**Comment by cipchk** [comment]
一个临时的解决办法是监听 `loaded` 事件，并重新调用 `checkViewportSize()`，类似：

```ts
if (ev.type === 'loaded') {
      setTimeout(() => this.st.cdkVirtualScrollViewport.checkViewportSize());
    }
```
