### ISSUE TITLE
How to solve this problem : No 'Access-Control-Allow-Origin' header is present on the requested resource

### ISSUE THREAD

**Issue by sliu1975** [ng-alain/ng-alain#184]
## Bug Report or Feature Request (mark with an `x`)
<pre><code>
[ ] Bug report -> please search issues before submitting
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Environment

<pre><code>
Angular version: X.Y.Z

delon version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX

For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by cipchk** [comment]
please google keywords: CORS

**Comment by sliu1975** [comment]
solved,thanks
