### ISSUE TITLE
input 属性 autocomplete=on 无法使用输入记录

### ISSUE THREAD

**Issue by morgeq** [ng-alain/ng-alain#1841]
## What problem does this feature solve?
input 属性 autocomplete=on 无法使用输入记录

## What does the proposed API look like?
input 属性 autocomplete=on

**Comment by morgeq** [comment]
input  要 id属性  id="userName"   autocomplete = on 才会生效

**Comment by cipchk** [comment]
`autocomplete` 是否生效都必须满足几个条件，细节请参考 [The HTML autocomplete attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete)。

> In order to provide autocompletion, user-agents might require `<input>/<select>/<textarea>` elements to:
> Have a name and/or id attribute
> Be descendants of a `<form>` element
> The form to have a submit button
