### ISSUE TITLE
拦截器忽略的接口,希望能够同时携带token

### ISSUE THREAD

**Issue by xingkoo** [ng-alain/ng-alain#1842]
## What problem does this feature solve?
默认的拦截器，如果设置忽略了验证，则不会携带token。
有个场景，startup.service.ts中的配置信息获取，两个请求合并请求完后再行处理。
在这个处理中，有设置个人信息的处理环节，该环节在登陆前设置用户信息为“访客”，登陆后设置为“用户姓名“。
当不设置忽略验证时，或者url添加allow anonmous时，该请求会被拦截。
当设置忽略验证时，当用户登陆后，再次刷新页面，将不能携带token，导致请求不能获取到当前用户信息。
是否可以考虑默认忽略验证时，如果存在token，也可以携带？

## What does the proposed API look like?
当存在token时，忽略验证请求的api请求也可以携带token发起请求。

**Comment by cipchk** [comment]
依然在 URL 上增加 `allow anonmous`，同时在需要的位置填写 Token，这一点并不冲突。

**Comment by xingkoo** [comment]
我增加了`allow anonmous`后，发起的请求中，并没有把token添加到header中，能否帮助给个排查的方式。
我使用的SimpleInterceptor，刷新页面后，并未把token通过header提交到请求中。

**Comment by xingkoo** [comment]
请求：
````
zip(
        this.httpClient.get(`/assets/tmp/i18n/${this.i18n.defaultLang}.json`),
        this.httpClient.get('/v1/guest/system/setting?_allow_anonymous=true'),
      )
````
验证设置
````
  auth: {
    login_url: '/auth/login',
    token_send_key: 'Authorization',
    token_send_template: 'Bearer ${token}',
    token_send_place: 'header',
    ignores: [/assets\//, /\/v1\/auth\/login/, /\/v1\/auth\/send-sms/],
  },
````

**Comment by cipchk** [comment]
```ts
a.get(`setting?_allow_anonymous`, null, { headers: { token: 'new-token'}})
```

**Comment by xingkoo** [comment]
原来需要手工添加。感谢卡大~
