### ISSUE TITLE
"acl" property in app-data.json doesn't get an array

### ISSUE THREAD

**Issue by InbarTakdim** [ng-alain/ng-alain#1843]
### Reproduction link
[https://stackblitz.com/edit/ng-alain-setup](https://stackblitz.com/edit/ng-alain-setup)

### Steps to reproduce
			{
					"text": "Chargers",
					"i18n": "menu.station",
					"icon": "anticon anticon-api",
					"link": "/station/list",
					"acl": "['user1' ,'user2']"
				},

the loggedin user has 'user2' role but the menu doesn't show the 'Chargers' option.
If I put it as a string **( "acl": "'user2'"  -it's work!)** but I need to set up a _list_ of roles and not only one.
@cipchk Do you have an idea how to solve it?

### What is expected?
the user will see the "Chargers" option in the menu

### What is actually happening?
"Chargers" option in the menu doesn't exist.

| Environment | Info |
|---|---|
| ng-alain | 10.0.2 |
| Browser | chrome |

**Comment by cipchk** [comment]
The `acl` support arrary, it's equivalent to `ACLService.can(roleOrAbility: ACLCanType)` parameter value.

**Comment by InbarTakdim** [comment]
but it's not working when I do it: {	"acl": "['user1' ,'user2']"}
