### ISSUE TITLE
"@delon/theme" has missing dependencies

### ISSUE THREAD

**Issue by yuuuxt** [ng-alain/ng-alain#1844]
### Reproduction link
NA

### Steps to reproduce
1. upgrade from 9 to 10
2. remove node_modules and run `npm install`
3. the following error appears

ERROR in The target entry-point "@delon/theme" has missing dependencies:
 - @angular/cdk/platform
 - @angular/cdk/overlay
 - @ant-design/icons-angular/icons

### What is expected?
no error occurs

### What is actually happening?
have the error above, and manually installing packages is required.

| Environment | Info |
|---|---|
| ng-alain | 10.0.2 |
| Browser | NA |

Please consider fixing this (though manually install `@angular/cdk` and `@ant-design/icons-angular` could fix, too).

**Comment by cipchk** [comment]
Pls try remove `package-lock.json` in step 2.

**Comment by yuuuxt** [comment]
> 
> 
> Pls try remove `package-lock.json` in step 2.

I didn't do that, but I checked those 2 were not in `package.json`. 

I'm afraid I won't try it now, and it would be fine if we just close the issue, anyway it's a small one. :)

**Comment by shalltears** [comment]
哈哈，我也遇到了，一模一样

**Comment by cipchk** [comment]
@shalltears 尝试移除 `package-lock.json` 或 `yarn.lock` 并移除 `node_modules` 目录，重新安装就可以了。

**Comment by shalltears** [comment]
嗯嗯，当时按上面说的直接就可以了
