### ISSUE TITLE
动态表单中，cascader 级联选择能否增加快捷变更其他值的功能。

### ISSUE THREAD

**Issue by xingkoo** [ng-alain/ng-alain#1845]
## What problem does this feature solve?
实际使用中向后台发起请求时，大多都是扁平数据，
如变更省、市、县三级时，向后台提交的数据应该是 ` {名称、省、市、县}` ，
目前表单生成的数据则会是是 `{名称、[省、市、县]}`

## What does the proposed API look like?
希望能够简化change事件，当选择指定数据时，直接变更当前表单其他属性的值，以便数据扁平提交。
````
{名称、省、市、县、地区:[省、市、县] } // 其中省市县可以隐藏不显示、地区使用级联选择器
````
当用户对`地区`做变更时，可以直接作用到`省、市、县`属性中。

如果能设置提交时能自动移除`地区`属性就可以更简单使用了。

**Comment by cipchk** [comment]
涉及业务行为可以自定义一个专门针对这类情况的。
