### ISSUE TITLE
@delon/abc/media 飘红

### ISSUE THREAD

**Issue by zyzhan1** [ng-alain/ng-alain#1848]
### Reproduction link
[https://github.com/ng-alain/delon](https://github.com/ng-alain/delon)

### Steps to reproduce
https://github.com/ng-alain/delon

### What is expected?
https://github.com/ng-alain/delon

### What is actually happening?
https://github.com/ng-alain/delon

| Environment | Info |
|---|---|
| ng-alain | 10.0.2 |
| Browser | chrom |

npm i  文件为什么不全哈

**Comment by cipchk** [comment]
能否提供一个重现步骤 ？
