### ISSUE TITLE
请问是否支持服务端渲染？

### ISSUE THREAD

**Issue by ElderJames** [ng-alain/ng-alain#185]
## Bug Report or Feature Request (mark with an `x`)
<pre><code>
[ ] Bug report -> please search issues before submitting
[x] Feature request
[ ] Documentation issue or request
</code></pre>

没有的话可否支持？

**Comment by cipchk** [comment]
服务端渲染任意angular项目都可以，只是需要增加一些东西，ng-alain 当下没有；不过很容易 做到这一点。

其次中台服务端渲染着实完全没有必要。

**Comment by ElderJames** [comment]
服务端渲染要求不能用到window、document之类的浏览器对象，而是使用虚拟dom，ng-alain是这样的吗？

**Comment by cipchk** [comment]
参考：https://universal.angular.io/

**Comment by ElderJames** [comment]
antd.umd.js 里面会报错：document is not defined

**Comment by cipchk** [comment]
阿门。

**Comment by 1166544** [comment]
@cipchk "中台服务端渲染着实完全没有必要"
如果BOSS要求你做的中台系统达到秒开，并且不出现转圈圈动画，提升首屏用户体验时，你觉得有没有必要？

**Comment by cipchk** [comment]
没有办法，主要还是基础组件 库并不支持服务端渲染。

**Comment by lc-01010** [comment]
现在最新ng-zorro支持服务端渲染。ng-alain的SettingsService里会报localStorage is not defined
