### ISSUE TITLE
使用npm或yarn安装新的包都会报错Error: ENOENT: no such file or directory, open 'F:\project\web-kalends-eimg\node_modules\@delon/theme/styles/default.less'，然后项目无法启动

### ISSUE THREAD

**Issue by lrqnew** [ng-alain/ng-alain#1850]
### Reproduction link
[https://github.com/ng-alain/ng-alain/issues/new/choose](https://github.com/ng-alain/ng-alain/issues/new/choose)

### Steps to reproduce
使用npm或yarn安装新的包都会报错Error: ENOENT: no such file or directory, open 'F:\project\web-kalends-eimg\node_modules\@delon/theme/styles/default.less'，之后项目就无法启动了

### What is expected?
不报错，可以正常安装

### What is actually happening?
报错，无法启动项目

| Environment | Info |
|---|---|
| ng-alain | 10.0.2 |
| Browser | 无 |

**Comment by cipchk** [comment]
能否确定 `F:\project\web-kalends-eimg\node_modules\@delon/theme/styles/default.less` 这个路径是存在的呢？如果存在是否因为权限问题呢？

**Comment by lrqnew** [comment]
> 能否确定 `F:\project\web-kalends-eimg\node_modules\@delon/theme/styles/default.less` 这个路径是存在的呢？如果存在是否因为权限问题呢？

就是npm i之后这个文件夹/styles/莫名消失了，导致报错了

**Comment by cipchk** [comment]
已找到问题根源，非 ng-alain 因素，关掉此 issues.
