### ISSUE TITLE
现在st有纵向虚拟滚动，是否有横向虚拟滚动，或横向纵向一起虚拟滚动

### ISSUE THREAD

**Issue by peacejj** [ng-alain/ng-alain#1853]
## What problem does this feature solve?
现在st有纵向虚拟滚动，是否有横向虚拟滚动，或横向纵向一起虚拟滚动

## What does the proposed API look like?
想要：st有横向纵向一起虚拟滚动

**Comment by cipchk** [comment]
使用 [scroll](https://ng-alain.com/components/st/zh#API) 参数可以实现。

**Comment by peacejj** [comment]
@cipchk 加了scroll是可以滚动了，但不是虚拟滚动。
例如列较多且行也较多的情况下，100列10000行，加载的时候没必要100列数据同时加载。
目前能到到的效果是：加载100列，可见区域的行数（10来行）
想要的效果：加载可见区域的列和行，比如10列10行。

大佬，有解撒？

**Comment by cipchk** [comment]
https://ng-alain.com/components/st/zh#components-st-virtual

**Comment by peacejj** [comment]
@cipchk  可能是我描述的不清楚吧
我想要的是渲染dom的虚拟滚动，不只是界面展示，您发的demo中全部列的elements都生成了

**Comment by cipchk** [comment]
@peacejj 抱歉，我依然没明白你的意思，如果有使用上的问题，麻烦提供相应的重现步骤以及期望结果与实际结果的对比 。
