### ISSUE TITLE
请问如何去掉登录认证页面，直接进入主页

### ISSUE THREAD

**Issue by seeallsea** [ng-alain/ng-alain#1857]
## What problem does this feature solve?
由于项目的需要，不需要登录认证，直接打开主页即可，请问如何去掉登录认证页面

## What does the proposed API look like?
No

**Comment by cipchk** [comment]
移除 `SimpleInterceptor` 配置，见[app.module.ts](https://github.com/ng-alain/ng-alain/blob/master/src/app/app.module.ts#L72)
