### ISSUE TITLE
simple-table total

### ISSUE THREAD

**Issue by a532533603** [ng-alain/ng-alain#186]
现在很多项目上的 total 都是放在 response 的  header 里面的，simple-table 可以支持嘛？
返回的 response body 的内容直接就是 数组
![image](https://user-images.githubusercontent.com/13478101/34663756-4ffecf2a-f493-11e7-9f00-c1867ff4236b.png)
![image](https://user-images.githubusercontent.com/13478101/34663763-5d4d278a-f493-11e7-9804-b43567aa79ea.png)

**Comment by cipchk** [comment]
not yet!

**Comment by a532533603** [comment]
有考虑添加嘛？

**Comment by cipchk** [comment]
决定不考虑支持；一段 http 协议对 [Response Header](https://www.w3.org/Protocols/rfc2616/rfc2616-sec6.html#sec6) 的说明：

> The response-header fields allow the server to pass additional information about the response which cannot be placed in the Status- Line. These header fields give information about the server and about further access to the resource identified by the Request-URI.

返回的header不应该包括：业务数据。
