### ISSUE TITLE
怎样去掉登录验证不跳转到登录界面呢？

### ISSUE THREAD

**Issue by wangyahua** [ng-alain/ng-alain#1861]
### Steps to reproduce
去掉app.module.ts中的{ provide: HTTP_INTERCEPTORS, useClass: SimpleInterceptor, multi: true}，依然还会验证调整登录界面。。。。。

### What is expected?
不要验证登录，不跳转登录界面。

### What is actually happening?
实际是取消不了验证登录逻辑。

| Environment | Info |
|---|---|
| ng-alain | 10.1.1 |
| Browser | Chrome |

**Comment by cipchk** [comment]
搜索整个项目，并移除以下几个项  `canActivate: [SimpleGuard],` 和 `canActivateChild: [SimpleGuard],`，这是因为默认会对所有业务配置授权的路由守卫，所以被拦截了。
