### ISSUE TITLE
Schema的条件类错误

### ISSUE THREAD

**Issue by zzz-1123** [ng-alain/ng-alain#1867]
### Reproduction link
[https://stackblitz.com/edit/ng-alain-setup](https://stackblitz.com/edit/ng-alain-setup)

### Steps to reproduce
问题出现在Schema的条件类错误。

表单提交时，我type选择的mobile，此时 'name', 'pwd' 应该是可以不填，而它提示必填

schema: SFSchema = {
  properties: {
    type: { type: 'string', enum: [ 'mobile', 'name' ], default: 'mobile' },
    name: { type: 'string' },
    pwd: { type: 'string' },
    mobile: { type: 'string' },
    code: { type: 'string' }
  },
  required: [ 'type' ],
  if: {
    properties: { type: { enum: [ 'mobile' ] } }
  },
  then: {
    required: [ 'mobile', 'code' ]
  },
  else: {
    required: [ 'name', 'pwd' ]
  }
};

### What is expected?
在Schema的条件类错误。

表单提交时，我type选择的mobile，此时 'name', 'pwd' 应该是可以不填，而它提示必填

### What is actually happening?
在Schema的条件类错误。

表单提交时，我type选择的mobile，此时 'name', 'pwd' 应该是可以不填，而它提示必填

| Environment | Info |
|---|---|
| ng-alain | 10.1.2 |
| Browser | 谷歌 |

---
重现链接、浏览器是我随便写的，我想说的问题出现在Schema的条件类错误。

**Comment by cipchk** [comment]
是的，目前 `if` 所处理的 `required` 除了必填项完，也作为展示逻辑的一部分，当然你也可以自己写相应的 `visibleIf` 逻辑，来实现非必填项，例如上述的 Schema 换成 `visibleIf` 的写法，差不多这样，只不过无须 `required` 的干涉：

```ts
{
  properties: {
    login_type: {
      type: "string",
      title: "登录方式",
      enum: [
        { label: "手机", value: "mobile" },
        { label: "账密", value: "account" }
      ],
      default: "mobile",
      ui: {
        widget: "radio",
        styleType: "button"
      }
    },
    mobile: {
      type: "string",
      ui: {
        visibleIf: {
          login_type: val => val === "mobile"
        }
      }
    },
    code: {
      type: "number",
      ui: {
        visibleIf: {
          login_type: val => val === "mobile"
        }
      }
    },
    name: {
      type: "string",
      ui: {
        visibleIf: {
          login_type: val => val === "account"
        }
      }
    },
    pwd: {
      type: "string",
      ui: {
        type: "password",
        visibleIf: {
          login_type: val => val === "account"
        }
      }
    }
  },
  required: ["login_type"]
};
```

**Comment by zzz-1123** [comment]
@cipchk 
嗯嗯，现在全部必填的情况下，在type选择A后，submit时，会提示B下的'name', 'pwd'未填写，这个问题可以如何归避呢
properties: {
    type: { type: 'string', enum: [ 'A', 'B' ], default: 'A' },
    name: { type: 'string' },
    pwd: { type: 'string' },
    mobile: { type: 'string' },
    code: { type: 'string' }
  },
  required: [ 'type' ],
  if: {
    properties: { type: { enum: [ 'A' ] } }
  },
  then: {
    required: [ 'mobile', 'code' ]
  },
  else: {
    required: [ 'name', 'pwd' ]
  }
