### ISSUE TITLE
XLSX组件对中文的支持。

### ISSUE THREAD

**Issue by xingkoo** [ng-alain/ng-alain#1868]
## What problem does this feature solve?
我看到文档最下方写了仅支持utf8 with bom，是否可以增加对文件编码的自适应功能？或者如何在此基础上自行增加这个功能？
目前我直接使用时，导入csv格式文件时全是乱码。

## What does the proposed API look like?
参考：
https://zhuanlan.zhihu.com/p/139246183

**Comment by cipchk** [comment]
临时解决办法可以覆盖 `XlsxService.read` 在这个环节里做处理。
