### ISSUE TITLE
simple format

### ISSUE THREAD

**Issue by a532533603** [ng-alain/ng-alain#187]
![image](https://user-images.githubusercontent.com/13478101/34669714-04f47564-f4ae-11e7-8a3c-e12a5e18a81c.png)
![image](https://user-images.githubusercontent.com/13478101/34669716-0afbb314-f4ae-11e7-9a71-5024ee3bcad0.png)

控制台会输出非常多，我觉得这是一个 bug

**Comment by cipchk** [comment]
每一次渲染都会被调用

**Comment by a532533603** [comment]
我一共只有3条数据，为什么会打印这么多次

**Comment by cipchk** [comment]
哪怕你使用一个简单的 `li` 它也会打印很多次的，所以不要在 `format` 调用复杂的计算。
