### ISSUE TITLE
sf date部件fornat为yyyyMMdd的时候默认值会被显示为19700101

### ISSUE THREAD

**Issue by 694551594** [ng-alain/ng-alain#1870]
### Reproduction link
[https://github.com/没梯子，没办法弄重现链接，抱歉。](https://github.com/没梯子，没办法弄重现链接，抱歉。)

### Steps to reproduce
1、date小部件的format设置为yyyyMMdd。
2、给默认值为20201206.
3、小部件显示值为19700101.

### What is expected?
小部件的值显示为20201206

### What is actually happening?
小部件的值显示为19700101.

| Environment | Info |
|---|---|
| ng-alain | 10.1.2 |
| Browser | google chrome |

---
初步调试为utils里面的toDate方法，把20201206作为了number处理，直接返回了new Date(20201206)。;

![QQ图片20201206224918](https://user-images.githubusercontent.com/17873626/101283439-523b0380-3815-11eb-84ed-2c834f0c626f.png)
![2](https://user-images.githubusercontent.com/17873626/101283456-772f7680-3815-11eb-8468-ae9895ca4397.png)

**Comment by cipchk** [comment]
fixed by `10.1.3`
