### ISSUE TITLE
动态表单的返回值是否可以清理？

### ISSUE THREAD

**Issue by xingkoo** [ng-alain/ng-alain#1875]
## What problem does this feature solve?
通常情况下，更新表单时，直接接收了一个从后台读取到的记录，然后直接给了sf的formdata，
在这种情况下，保存数据时，将会直接把整个记录完整传到后台。
而实际上，我可能只需要传送几个表单中用到的数据。我记不太清有没有类似的功能了，但是在文档中尚未发现有此设置。

## What does the proposed API look like?
增加一个开关，来决定表单返回的值是否清理未使用的属性。

**Comment by cipchk** [comment]
[cleanValue](https://ng-alain.com/form/getting-started/zh#API)

**Comment by xingkoo** [comment]
这个配置是否可以放置在全局配置中呢？
