### ISSUE TITLE
When ng-alain will support Angular 11?

### ISSUE THREAD

**Issue by maratkalibek** [ng-alain/ng-alain#1877]
### Reproduction link
-

### Steps to reproduce
-

### What is expected?
Angular 11 support

### What is actually happening?
There is no Angular 11 support

| Environment | Info |
|---|---|
| ng-alain | 10.1.3 |
| Browser | All |

**Comment by John0King** [comment]
same ask,  with Angular 11 ,  it saids it has 30% faster on build

**Comment by gemron** [comment]
should be waiting for ng-zorro-antd to upgrade. see [ng-zorro-antd v11  Milestone](https://github.com/NG-ZORRO/ng-zorro-antd/milestone/7)

**Comment by ousc** [comment]
https://zhuanlan.zhihu.com/p/338003257

**Comment by John0King** [comment]
now ng-zorro-antd v11 is published  https://github.com/NG-ZORRO/ng-zorro-antd/issues/6217

and I wonder is there a plan that ng-alain will migrate ?
- [ ] migrate `Tslint` to `ESlint`
- [ ] doc for migrate
- [ ] and so on
