### ISSUE TITLE
关于tab主题颜色的问题

### ISSUE THREAD

**Issue by guccihuiyuan** [ng-alain/ng-alain#188]
0.14版本的nz-tabset更换主题颜色没有问题，但是像这样设置<nz-tabset [nzType]="'card'">它的类型的时候就不会根据主题改变颜色了，请问下我该在哪里加上去？

**Comment by cipchk** [comment]
https://github.com/cipchk/delon/blob/master/src/core/theme/styles/themes/theme.less
