### ISSUE TITLE
sf 刷新string类型小部件hidden属性无效

### ISSUE THREAD

**Issue by fangpy** [ng-alain/ng-alain#1880]
### Reproduction link
[https://stackblitz.com/edit/angular-c4hvba?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-c4hvba?file=src/app/app.component.ts)

### Steps to reproduce
1、必填项name填值
2、点击提交按钮

### What is expected?
手机号小部件隐藏

### What is actually happening?
未隐藏

| Environment | Info |
|---|---|
| ng-alain | 10.1.3 |
| Browser | Google Chrome 87.0.4280.88 |

**Comment by cipchk** [comment]
`reset` 只会重新加载小部件，并不能重新渲染 Schema，而 `hidden` 是在渲染过程中才会执行操作，其实内部有个私有方法 `setVisible` 可以用于控制隐藏或显示，例如：

```diff
- nameProperty.ui.hidden = true;
+ (nameProperty as any).setVisible(false);
```
