### ISSUE TITLE
sf 身份证号校验最后一位带 x 的有问题

### ISSUE THREAD

**Issue by fangpy** [ng-alain/ng-alain#1882]
### Reproduction link
[https://stackblitz.com/edit/angular-hxe37y](https://stackblitz.com/edit/angular-hxe37y)

### Steps to reproduce
身份证号填写:  61232119840216192x

### What is expected?
正常提交

### What is actually happening?
格式不正确

| Environment | Info |
|---|---|
| ng-alain | 10.1.3 |
| Browser | Google Chrome 87.0.4280.88 |

---
正常的身份证号是有可能最后一位是 x 的

**Comment by cipchk** [comment]
这里的 `X` 应该是大写的。
