### ISSUE TITLE
feat(cli): new @delon/cli plans!

### ISSUE THREAD

**Issue by cipchk** [ng-alain/ng-alain#189]
一直以来都是依赖 Github 仓储下载脚手架，这给 ng-alain 约束了非常多限制，Angular Cli 应该可以帮助我们更多，从而减少不必要的开发成本。

Angular Cli 的 Schematics 是允许被二次开发的，从中我们可以透过 Angular Cli 强化与其 ng-alain 更多的融合。

例如，当我们创建一个新项目时：

```
ng new demo
```

生成的是一个 Cli 提供的模板，然而我们可以对它进一步二次开发，当我们使用：

```
ng new --collection=@delon/cli demo
```

应该直接构建一个 `blank` 分支的项目出来。

我们不应该把时间浪费在一些文件的操作上，因此，像 Cli 所提供的一些生成动作，应该提供一个更友好的支持。

例如，当我们生成一个模块时：

```
ng g module trade --routing
```

应该包括一些 `SharedModule` 的导入动作。

这是一项很费时间的工作，但我想是非常值得的，它应该包括：

| Action | Status |
| ------- | ------- |
| Create | - |
| Module | - |
| Page | - |
| Component | - |
| Directive | - |
| Pipe | - |
| Service | - |

**Comment by ColdMoonMao** [comment]
目前打包出来的体积挺大，有没有优化的方法

**Comment by cipchk** [comment]
一般而言打包的体积取决于你使用了哪些第三方类库的体积，这一点在任何框架中都是一样的。

其实我觉得应该从整体去分析你当下用了些什么、是否有必要？另外 [优化](http://ng-alain.com/docs/performance) 也包括了一些方案。

当然，对于 Web 服务器也一定要开启 gzip，一般能在几百KB是很正常的。

**Comment by maplye** [comment]
Great!
