### ISSUE TITLE
sf select小部件，添加enum属性后，打开select一直处于加载状态

### ISSUE THREAD

**Issue by 694551594** [ng-alain/ng-alain#1890]
### Reproduction link
https://ng-alain.gitee.io/delon/form/select/zh

### Steps to reproduce
1、sf select小部件，添加enum属性后，打开select一直处于加载状态。具体可以参看官网的例子。

### What is expected?
select可以正常显示

### What is actually happening?
select一直在加载

| Environment | Info |
|---|---|
| ng-alain | 11.0.1 |
| Browser | google chrome |

**Comment by cipchk** [comment]
这是正常现象，搜索过程中的一种状态。

**Comment by 694551594** [comment]
感觉不是呀。他一直是这个状态。

**Comment by cipchk** [comment]
> 感觉不是呀。他一直是这个状态。

控制台有什么异常，或者其他可以让我判断问题根源的信息吗？我这里一切正常。

**Comment by cipchk** [comment]
的确是逻辑 有问题。
