### ISSUE TITLE
默认模板**解决登录**后会出现立即刷新token的问题

### ISSUE THREAD

**Issue by John0King** [ng-alain/ng-alain#1893]
### Reproduction link
 无

### Steps to reproduce
- 安装 ng-algin
- 使用api解决登录问题
- 登录

### What is expected?
只有token过期才检查token

### What is actually happening?
登陆后里面出现 refresh_token ，因为失败所以   跳回登录

| Environment | Info |
|---|---|
| ng-alain | 11.0.2 |
| Browser | edge  |

---
虽然，这个问题倒是使用时，必须解决这部分的刷新问题， 但是刷新确实不应该在刚刚登录 就 又得刷新token

**Comment by cipchk** [comment]
麻烦提供更加具体的细节以及具体重现步骤，否则我们无法就此问题进一步细节的讨论。

**Comment by John0King** [comment]
![image](https://user-images.githubusercontent.com/13639146/103086029-5ee59700-461e-11eb-9425-b55b2df7afa8.png)
@cipchk   好像不知道什么原因， 这个 refresh 会自动发起，如果不验证token到底过期没，那就会重新来一遍

**Comment by cipchk** [comment]
的确 Jwt 的校验也应该加上，你的写法是对的，但只是一个临时解决办法，我会在内部的进行校验。
