### ISSUE TITLE
怎么样才能调整默认字号大小呢？

### ISSUE THREAD

**Issue by qld-cf** [ng-alain/ng-alain#19]
翻开node_module里面的zorro源码，默认字体貌似被限制了，都是12px，我感觉还是挺小的，那么ng-alain能否实现默认字体更改为14px？谢谢

**Comment by cipchk** [comment]
ng-zorrot-antd 目前没有办法做到这一点，除非你自己fock一份ng-zorro-antd源代码，然后自己编译。

而对于ng-alain 的字体，你可以通过修改相应参数改变他们，但这跟ng-zorro-antd无关，因此，只能期待 ng-zorro-antd 后期的改变。同时，我也会加强 ng-alain 参数化的，尝试去强化 ng-zorro-antd 的字号大小问题。

**Comment by qld-cf** [comment]
嗯  希望ng-alain越来越好，多更新nice的东西😁
