### ISSUE TITLE
st组件，嵌入到nz-popover组件中，点分页的时候报错

### ISSUE THREAD

**Issue by sunger** [ng-alain/ng-alain#1901]
### Reproduction link
[https://stackblitz.com/edit/ng-alain-setup-ymbyyj?file=src%2Fapp%2Fapp.component.html](https://stackblitz.com/edit/ng-alain-setup-ymbyyj?file=src%2Fapp%2Fapp.component.html)

### Steps to reproduce
直接运行

### What is expected?
无错

### What is actually happening?
有错

| Environment | Info |
|---|---|
| ng-alain | 11.0.2 |
| Browser | 谷歌 |

---
core.js:6241 ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'scrollTo' of null

**Comment by cipchk** [comment]
尝试升级一下，最新版本并不存在这类情况：https://stackblitz.com/edit/ng-alain-setup-qxzlqe?file=src%2Fapp%2Fapp.component.ts
