### ISSUE TITLE
使用reusetab后，标签页的内存疯狂增长，使用长时间后都增长到2g

### ISSUE THREAD

**Issue by siwting** [ng-alain/ng-alain#1906]
### Reproduction link
[版本11.1.0]()

### Steps to reproduce
反复点击不同的菜单

### What is expected?
同一个路由，反复点击后内存不会增长

### What is actually happening?
同一个路由，反复点击时，内存增加的比较多，详细的可以参见下面的动图

| Environment | Info |
|---|---|
| ng-alain | 11.1.0 |
| Browser | chrome 89 |

![CleanShot 2021-01-06 at 14 31 43](https://user-images.githubusercontent.com/3980989/103739273-59ca1400-5030-11eb-9a6f-cfb547cc5ced.gif)

**Comment by siwting** [comment]
https://github.com/siwting/test/tree/master     这个是完整的代码

**Comment by charisna** [comment]
其实可以直接看官方示例：https://ng-alain.surge.sh/#/pro/list/table-list
多点几次查询，关注下Performance内存情况

不过大概率是ng-zorro-antd的锅：https://github.com/NG-ZORRO/ng-zorro-antd/issues/5843

![image](https://user-images.githubusercontent.com/4499480/103861974-2d2dff00-50f9-11eb-9ea6-24fbd893ae77.png)

**Comment by siwting** [comment]
> 其实可以直接看官方示例：https://ng-alain.surge.sh/#/pro/list/table-list
> 多点几次查询，关注下Performance内存情况
> 
> 不过大概率是ng-zorro-antd的锅：[NG-ZORRO/ng-zorro-antd#5843](https://github.com/NG-ZORRO/ng-zorro-antd/issues/5843)
> 
> ![image](https://user-images.githubusercontent.com/4499480/103861974-2d2dff00-50f9-11eb-9ea6-24fbd893ae77.png)

我这里示例的是没有用到表格的，页面上基本没有东西，如果有表格确实会涨的更快

**Comment by jeffrey-liu-025** [comment]
The same trouble happened to me, please help!

**Comment by cipchk** [comment]
复用的本质是将当前组件的实例放入内存，的确是无法保证所有基础组件都做好离开与进入二者之前做一下后台数据临时取消操作等动作。

**Comment by emondora** [comment]
@cipchk hello. I'm wondering the reuse tab component is support Angular Universal? When i use it in server side rendering, the node.js process exit and throws error as below.
```javascript
Error: Injector has already been destroyed.
...
at ViewRef.detectChanges...
at reuseTab_ReuseTabComponent.genList...
...
```
 Thanks a lot.

**Comment by cipchk** [comment]
> @cipchk hello. I'm wondering the reuse tab component is support Angular Universal? When i use it in server side rendering, the node.js process exit and throws error as below.
> 
> ```js
> Error: Injector has already been destroyed.
> ...
> at ViewRef.detectChanges...
> at reuseTab_ReuseTabComponent.genList...
> ...
> ```
> 
> Thanks a lot.

Not yet.

**Comment by cipchk** [comment]
关闭此 issues，若有进一步描述重现步骤，可重新打开或创建新的 issues。
