### ISSUE TITLE
ReuseTabService 如何关闭指定的Tab

### ISSUE THREAD

**Issue by winpzs** [ng-alain/ng-alain#191]
## Bug Report or Feature Request (mark with an `x`)
<pre><code>
[ ] Bug report -> please search issues before submitting
[X] Feature request
[ ] Documentation issue or request
</code></pre>

## Feature request
好像提供了remove(url)方法，但没有缓存的页面关闭不了，应该如何关闭？

**Comment by cipchk** [comment]
"没有缓存的页面关闭不了"，不明白这话的意思。

**Comment by winpzs** [comment]
就是ReuseTabService是控制不了，临时页面(reuse=false时)
