### ISSUE TITLE
simple-table能否增加刷新方法

### ISSUE THREAD

**Issue by downlder** [ng-alain/ng-alain#192]
## Bug Report or Feature Request (mark with an `x`)
<pre><code>
[ ] Bug report -> please search issues before submitting
[x] Feature request
[ ] Documentation issue or request
</code></pre>

## Expected behavior

simple-table的刷新有时候是外部触发，比如extra-params改变的时候，能增加一个刷新的方法？

## Environment

<pre><code>
Angular version: X.Y.Z

delon version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX

For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by cipchk** [comment]
```html
<simple-table #st></simple-table>
<button (click)="st.load()" />
```
