### ISSUE TITLE
st在设置了[scroll]属性时，翻页会报错

### ISSUE THREAD

**Issue by zhangjian4** [ng-alain/ng-alain#1923]
### Reproduction link
[https://stackblitz.com/edit/angular-munjjs?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-munjjs?file=src/app/app.component.ts)

### Steps to reproduce
翻页

### What is expected?
根据错误信息来看应该是要滚动到顶部

### What is actually happening?
控制台报了`Cannot read property 'scrollTo' of null`的错误

| Environment | Info |
|---|---|
| ng-alain | 11.3.1 |
| Browser | chrome |

**Comment by programmingGu** [comment]
我也遇见了这样的错误  在 st上 加了 scroll 属性后 触发分页 控制台报错  
![QQ截图20210309145625](https://user-images.githubusercontent.com/22958243/110430805-de481a00-80e7-11eb-8749-accb22e5a15c.png)
![QQ截图20210309145803](https://user-images.githubusercontent.com/22958243/110430818-e1dba100-80e7-11eb-8c1c-fe557fe5e9d6.png)

**Comment by zhangjian4** [comment]
@programmingGu 这个已经修复了的，你更新到最新版试下

**Comment by programmingGu** [comment]
@zhangjian4 收到  多谢
