### ISSUE TITLE
sf中货币类型的货币单位指定

### ISSUE THREAD

**Issue by Diluka** [ng-alain/ng-alain#1924]
## What problem does this feature solve?
有时候货币是元有时候货币是分，目前总是当做元处理的

## What does the proposed API look like?
currencyUnit ？

**Comment by cipchk** [comment]
能否提供一个示例？

**Comment by Diluka** [comment]
目前只能这样自己写一个`format`，但是期望能内部实现除以100的操作来省略这个`format`从而使用内置的

```ts
const mFmt = (data: STData, col: STColumn) => {
  const v = _.get(data, col.index);
  return _.isNil(v) ? '--' : (v / 100).toFixed(2);
};
```
