### ISSUE TITLE
侧边栏toggleCollapsed功能无法使用

### ISSUE THREAD

**Issue by cswww** [ng-alain/ng-alain#1925]
## What problem does this feature solve?
知道侧边栏打开事件

## What does the proposed API look like?
侧边栏打开触发事件toggleCollapsed

**Comment by cipchk** [comment]
如果你需要监听变化，需要通过 `SettingsService.notify` 来订阅即可，注意所有布局相关的变化都会通过这个接口，所以需要做好 `filter` 操作。

**Comment by cswww** [comment]
好的 谢谢 希望在文档上能找打
