### ISSUE TITLE
st数据计算

### ISSUE THREAD

**Issue by Diluka** [ng-alain/ng-alain#1926]
## What problem does this feature solve?
使用内置格式化或者导出数据之前，对数据进行处理

#1924 提到的情况也可以用这种方式处理

## What does the proposed API look like?
compute ？

**Comment by cipchk** [comment]
可以使用 `format` 参数，自定义输出单元格数据，而 `st.export` 默认的情况下是使用当前页表格数据，如果你想进一步优化导出，`st.export` 支持提供数据，如果是当前页，可以通过 `st.list` 来获取数据，这是当前页表格数据。

当然也包括 #1924 所提的，也可以根据 `format` 来优化。

**Comment by Diluka** [comment]
其实就是`format`有一定的问题才想要这种功能。

1. 比如`货币`类型，会当做`元`处理，但是数据可能是`分`需要转换，但是并不想自己重新写一遍`format`，毕竟`货币`类型自带一套
2. 使用`format`之后其实`index`已经没什么用了，但是导出文件时没有`index`就不会导出这一列
3. 并不想修改原始数据，原始数据可能有其他用处
4. 在调用`st.export`时单独传入一套数据闲得很不优雅啊

其实最主要的还是第`1`点，明明有`货币`类型了，但是单位不是`元`就不能用了，很烦诶

**Comment by cipchk** [comment]
@Diluka 能否提供一个对于 `分` 的处理真实示例。

**Comment by Diluka** [comment]
> @Diluka 能否提供一个对于 `分` 的处理真实示例。

只能写一个`format`

```ts
const mFmt = (data: STData, col: STColumn) => {
  const v = _.get(data, col.index);
  return _.isNil(v) ? '--' : (v / 100).toFixed(2);
};
```


不过从`format`的接口设计来看，数据转换的api不好弄吧，`format`需要自己从行中提取数据，没有通过`index`自动提取的数据，那么数据转换就会反映到行数据上才能兼容`format`，但是这样又会导致原始数据被修改吧？
