### ISSUE TITLE
tree-antd init nodes can't associated parent node checkbox state

### ISSUE THREAD

**Issue by lyc152** [ng-alain/ng-alain#193]
## Bug Report or Feature Request (mark with an `x`)
init
```
this.nodes = [
      {
        name: '账户',
        hasChildren: true,
        checked: false,
        children: [
            {
              id: 1,
              name: 'name1',
              checked: false
            },
            {
              id: 2,
              name: 'name2',
              checked: true
            }
        ]
      }
    ]

```

expectation:
![image](https://user-images.githubusercontent.com/4793878/34759807-374df79a-f618-11e7-8582-438f85752969.png)

now:
![image](https://user-images.githubusercontent.com/4793878/34759853-6b35acb0-f618-11e7-95d0-b9a2a45b4e9d.png)

url:
https://ng-tree-antd-jmfi4m.stackblitz.io/

Is there any good solution?

**Comment by lyc152** [comment]
这个bug好修复吗？

**Comment by cipchk** [comment]
这个问题的确有点大，因为这涉及到受控的行为，`checkbox` 的受控的两种 `checked` 和 `halfChecked`。

就当下父子节点状态受控只有在用户单击时触发，而对于默认值 的的选中与否关联这又是受控的另一种，这个问题的确需要修复。

当下只能由你自己在外部提供的数据中指定 `checked` 和 `halfChecked` 来解决。

**Comment by cipchk** [comment]
我会新增一个属性 `nzCheckStrictly` 表示父节点的受控由 `nz-tree` 内部来做。

**Comment by lyc152** [comment]
确实设置为
```
    this.nodes = [
      {
        name: '账户',
        hasChildren: true,
        checked: false,
        halfChecked: true,
        children: [
            {
              id: 1,
              name: 'name1',
              checked: false,
              halfChecked: true
            },
            {
              id: 2,
              name: 'name2',
              checked: true,
              halfChecked: false
            }
        ]
      }
    ]
```
就可以达到期望效果，多谢

**Comment by cipchk** [comment]
已修复 [2.2.0](https://github.com/cipchk/ng-tree-antd/releases)
