### ISSUE TITLE
reuse组件的点击或切换能否阻止

### ISSUE THREAD

**Issue by KellenHe** [ng-alain/ng-alain#1934]
## What problem does this feature solve?
暴力切换的时候两个界面来回切换会导致一些问题，想做一个防抖，请问有onTabClick类似的事件，或别的方法吗

## What does the proposed API look like?
onTabClick事件，并可以阻止切换。

**Comment by cipchk** [comment]
可以利用 `change` 事件，并给 `reuse-tab` 组件增加一个 `pointer-events: none;` 样式可以禁止触发。

当然，会在下一版本中给`reuse-tab` 组件增加 `disabled` 属性
