### ISSUE TITLE
simple-table pi

### ISSUE THREAD

**Issue by liweitao92** [ng-alain/ng-alain#194]
后端使用的 spring boot, 他自己封装了一个 分页对象，但是他的起始页码是从  0  开始的，Simple-table 好像并没有办法能够修改 pi 的 第一页 下标

**Comment by cipchk** [comment]
```html
pi = 0
<simple-table [pi]="pi"></simple-table>
```

**Comment by liweitao92** [comment]
SimpleTableConfig 可以统一设置嘛

**Comment by liweitao92** [comment]
@cipchk  
![image](https://user-images.githubusercontent.com/30191996/34763653-decf6158-f626-11e7-9b65-5d2cdee794b8.png)
貌似并没有效果

**Comment by chenhongbinjs** [comment]
解决了吗？求解？

**Comment by cipchk** [comment]
没有办法，受限于 ng-zorro-antd 的分页组件只能从1开始。
