### ISSUE TITLE
sf not trigger change event when use widget.set()

### ISSUE THREAD

**Issue by Rwing** [ng-alain/ng-alain#1948]
### Reproduction link
[https://stackblitz.com/edit/ng-alain-setup-3qn5zl?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/edit/ng-alain-setup-3qn5zl?file=src%2Fapp%2Fapp.component.ts)

### Steps to reproduce
click "update status" button, not found log in console

### What is expected?
print log in console when click "update status" button

### What is actually happening?
not trigger change event

| Environment | Info |
|---|---|
| ng-alain | 11.7.0 |
| Browser | Chrome |

**Comment by Rwing** [comment]
sf.setValue() same as not trigger change event

**Comment by cipchk** [comment]
This expectations of `ngModel`, like this:

```ts
import { Component } from '@angular/core';

@Component({
  selector: 'my-app',
  template: `
    <input nz-input [(ngModel)]="value" (ngModelChange)="changeA()">
    <button (click)="value = 'b'" nz-button>Update value</button>
  `,
})
export class AppComponent {
  value = 'a';

  changeA(): void {
    console.log('update a value', this.value);
  }
}
```

Clicking the button cannot trigger `ngModelChange`.

**Comment by Rwing** [comment]
Maybe I didn't make it clear, I'm not click the button, instead  use the following function:
```
this.sf.getProperty('/status').widget.reset('2')
this.sf.setValue('2') 
```
both can't trigger widget's change event.

**Comment by Rwing** [comment]
@cipchk

**Comment by cipchk** [comment]
You can extract the `change` method in `schema` and then trigger it in `updateStatus` method.
