### ISSUE TITLE
_HttpClient是不是有bug

### ISSUE THREAD

**Issue by libgdxlover** [ng-alain/ng-alain#195]
## Bug Report or Feature Request (mark with an `x`)
<pre><code>
[ ] Bug report -> please search issues before submitting
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

```
this.http.post('../rest/user/auth', {
    username : this.userName.value, password : this.password.value
}, {
    headers: new HttpHeaders().set('Content-Type', 'application/x-www-form-urlencoded;charset=utf-8')               
}).subscribe()
```
用HttpClient执行没问题，用_HttpClient报错

## Environment

<pre><code>
Angular version: X.Y.Z

delon version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX

For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by cipchk** [comment]
能否提供具体的错误信息。

**Comment by libgdxlover** [comment]
main.4b6796975b17b03c39e2.bundle.js:1 ERROR TypeError: You provided an invalid object where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.
    at e.a (main.4b6796975b17b03c39e2.bundle.js:1)
    at e.error (main.4b6796975b17b03c39e2.bundle.js:1)
    at e._error (main.4b6796975b17b03c39e2.bundle.js:1)
    at e.E9/g.e.error (main.4b6796975b17b03c39e2.bundle.js:1)
    at e.E9/g.e._error (main.4b6796975b17b03c39e2.bundle.js:1)
    at e.E9/g.e.error (main.4b6796975b17b03c39e2.bundle.js:1)
    at e.E9/g.e._error (main.4b6796975b17b03c39e2.bundle.js:1)
    at e.E9/g.e.error (main.4b6796975b17b03c39e2.bundle.js:1)
    at e.notifyError (main.4b6796975b17b03c39e2.bundle.js:1)
    at e._error (main.4b6796975b17b03c39e2.bundle.js:1)
Sn @ main.4b6796975b17b03c39e2.bundle.js:1
LMZF.n.handleError @ main.4b6796975b17b03c39e2.bundle.js:1
Wr @ main.4b6796975b17b03c39e2.bundle.js:1
(anonymous) @ main.4b6796975b17b03c39e2.bundle.js:1
e.object.i @ main.4b6796975b17b03c39e2.bundle.js:1
E9/g.e.__tryOrUnsub @ main.4b6796975b17b03c39e2.bundle.js:1
E9/g.e.next @ main.4b6796975b17b03c39e2.bundle.js:1
E9/g.e._next @ main.4b6796975b17b03c39e2.bundle.js:1
E9/g.e.next @ main.4b6796975b17b03c39e2.bundle.js:1
TO51.e.next @ main.4b6796975b17b03c39e2.bundle.js:1
LMZF.e.emit @ main.4b6796975b17b03c39e2.bundle.js:1
e.onSubmit @ main.4b6796975b17b03c39e2.bundle.js:1
(anonymous) @ main.4b6796975b17b03c39e2.bundle.js:1
handleEvent @ main.4b6796975b17b03c39e2.bundle.js:1
handleEvent @ main.4b6796975b17b03c39e2.bundle.js:1
Wr @ main.4b6796975b17b03c39e2.bundle.js:1
(anonymous) @ main.4b6796975b17b03c39e2.bundle.js:1
(anonymous) @ main.4b6796975b17b03c39e2.bundle.js:1
t.invokeTask @ polyfills.bd68d593a0431d41961b.bundle.js:1
onInvokeTask @ main.4b6796975b17b03c39e2.bundle.js:1
t.invokeTask @ polyfills.bd68d593a0431d41961b.bundle.js:1
e.runTask @ polyfills.bd68d593a0431d41961b.bundle.js:1
e.invokeTask @ polyfills.bd68d593a0431d41961b.bundle.js:1
p @ polyfills.bd68d593a0431d41961b.bundle.js:1
h @ polyfills.bd68d593a0431d41961b.bundle.js:1

**Comment by cipchk** [comment]
我猜想应该是拦截器作祟吧。

**Comment by libgdxlover** [comment]
不用_HttpClient，发送的请求会带有token吗

**Comment by cipchk** [comment]
配置好相应的拦截器，当然可以。

**Comment by libgdxlover** [comment]
加了SimpleInterceptor就报错，是什么原因呢

**Comment by cipchk** [comment]
可能是无效 token 导致提前被拦截，更多细节搜索 [httpclient](https://github.com/cipchk/ng-alain/issues?utf8=%E2%9C%93&q=httpclient)或阅读ng-alain文档。
