### ISSUE TITLE
st固定列的表头样式问题

### ISSUE THREAD

**Issue by tyzh** [ng-alain/ng-alain#1951]
### Reproduction link
[https://stackblitz.com/edit/angular-ajt71b](https://stackblitz.com/edit/angular-ajt71b)

### Steps to reproduce
拖动滚动条

### What is expected?
固定列的阴影和隐藏正常显示；另外使用固定列时移动端st内容不能正常显示

### What is actually happening?
固定列阴影位置有问题，左侧固定列不能正常隐藏；另外移动端不能正常显示st内容
![image](https://user-images.githubusercontent.com/33508216/110412829-ca8cbb80-80c7-11eb-99b6-b74f2e65f56e.png)
![image](https://user-images.githubusercontent.com/33508216/110412909-f019c500-80c7-11eb-8481-37995cef83b9.png)

| Environment | Info |
|---|---|
| ng-alain | 11.7.1 |
| Browser | Chrome |

---
可能是每一个cellclass都有 : ant-table-cell-fix-right ant-table-cell-fix-left导致；移动端显示猜测是[scroll]="{ x: '1300px' }导致

**Comment by cipchk** [comment]
第一个部分问题在 https://github.com/ng-alain/delon/pull/1204 已经修复，需要等待下一版本。
