### ISSUE TITLE
全局储存key前缀

### ISSUE THREAD

**Issue by Diluka** [ng-alain/ng-alain#1955]
## What problem does this feature solve?
alain有很多配置需要储存，如：`user`, `layout`, `app`, `_token`，它们是与项目相关的，当一个域名下有多个alain项目时，它们有可能发生冲突，一个一个的手动加前缀不符合alain的风格，希望有一个统一前缀配置

## What does the proposed API look like?
globalKeyPrefix

**Comment by cipchk** [comment]
关于 `@delon/auth` 部分，可以对应的 `auth` 全局配置通过 `store_key` 来改变。
