### ISSUE TITLE
pdf组件放在modal中text渲染样式错乱问题

### ISSUE THREAD

**Issue by fssgh** [ng-alain/ng-alain#1960]
### Reproduction link
[https://github.com/fssgh/ng-alain-pdf.git](https://github.com/fssgh/ng-alain-pdf.git)

### Steps to reproduce
运行ng-alain-pdf  点击Dashboard面中的【查看PDF】按钮

### What is expected?
pdf组件 文本渲染正常。

### What is actually happening?
pdf组件 文本渲染不正常，样式错乱，全堆叠到了pdf首页上。

| Environment | Info |
|---|---|
| ng-alain | 11.8.0 |
| Browser | 谷歌内核86 |

**Comment by cipchk** [comment]
我看起来一起正常，png:
![image](https://user-images.githubusercontent.com/2987467/111421888-b892c480-8728-11eb-9f47-2e2045c16770.png)

可以试着使用 `renderText: false` 使用 canvas 渲染机制.

**Comment by fssgh** [comment]
看起来是正常，但我要 选文本复制文本就不正常了呀！官网上的示例是正常的。 @cipchk

**Comment by fssgh** [comment]
看起来是正常，但我要 选文本复制文本就不正常了呀！官网上的示例是正常的。 @cipchk

**Comment by cipchk** [comment]
我所截图也是非 `canvas` 模式，但的确是正常的，若有进一步重现，再重新打开此 issues。

**Comment by fssgh** [comment]
@cipchk 的确有问题，出问题的是textLayer的样式，请看截图
![Uploading 360截图20210317162945195.jpg…]()
![Uploading 360截图20210317163116466.jpg…]()

**Comment by fssgh** [comment]
![360截图20210317162945195](https://user-images.githubusercontent.com/14868289/111438403-26e28180-873f-11eb-8ca4-9f785966b483.jpg)
![360截图20210317163116466](https://user-images.githubusercontent.com/14868289/111438402-26e28180-873f-11eb-96d3-2e09d18672b3.jpg)

**Comment by fssgh** [comment]
pdf `内容html写到了nz-skeleton标签内了。。正确的应写到<div calss="pdfViewer">标签中的`

**Comment by cipchk** [comment]
喔，原来你说的是选中后。。。哎……难怪我一直无法重现，直到看到你的图。
