### ISSUE TITLE
price管道精度问题

### ISSUE THREAD

**Issue by Diluka** [ng-alain/ng-alain#1965]
### Reproduction link
[https://codesandbox.io/s/ng-alain-price-pipe-issue-vk96u](https://codesandbox.io/s/ng-alain-price-pipe-issue-vk96u)

### Steps to reproduce
当金额为整数时，精度会失效

### What is expected?
100分格式化为1.00元

### What is actually happening?
100分格式化为1元

| Environment | Info |
|---|---|
| ng-alain | 11.8.0 |
| Browser | edge |

**Comment by cipchk** [comment]
事实上是默认把 `.0` 或 `.00` 为结尾的跟忽略了。
