### ISSUE TITLE
多窗体操作

### ISSUE THREAD

**Issue by obamin** [ng-alain/ng-alain#1969]
## What problem does this feature solve?
![img1](https://user-images.githubusercontent.com/36915753/112244003-8681e500-8c89-11eb-8895-0b10d08cb2a8.png)

希望做一个像这里(https://truly-ui.com/modal)的功能(特征: 多窗体, 拖拽移动, 缩小放大, 不影响窗口层后面的主页面操作).
现在后台管理系统中, 经常需要在主要页面, 打开多个子窗口查看, 编辑,搜索, 比对其他信息, 
很多场景还是跑不了这么操作的方式
希望大大得空看下这个功能, 感谢!

## What does the proposed API look like?
组件形式, 参考这里(https://truly-ui.com/modal的Overlay Modal部分) 的例子做差不多就行了

**Comment by cipchk** [comment]
受限于 `nz-modal`，几乎没有办法实现。
