### ISSUE TITLE
npm run build ERROR in ng-tree-antd\index.ts(10,2): Error during template compile of 'NzTreeModule'

### ISSUE THREAD

**Issue by yangpengfei369** [ng-alain/ng-alain#197]
when run `npm run build` 
the console give me some err
`
> ng-alain@0.3.2 build D:\sources\newpcis\ng-alain
> ng build --prod --build-optimizer

Node#moveTo was deprecated. Use Container#append.

ERROR in ng-tree-antd\index.ts(10,2): Error during template compile of 'NzTreeModule'
  Function expressions are not supported in decorators in 'NgModule'
    'NgModule' contains the error at @angular\core\core.ts(194,31)
      Consider changing the function expression into an exported function.

Date: 2018-01-11T06:27:55.498Z
Hash: 9b8ee8470eaa248085df
Time: 71470ms
chunk {scripts} scripts.eed0b22222218ac04c8d.bundle.js (scripts) 915 kB [initial] [rendered]
chunk {0} styles.4b98a90cab59bcae938e.bundle.css (styles) 408 kB [initial] [rendered]
chunk {1} polyfills.3bc34265385d52184eab.bundle.js (polyfills) 86 bytes [initial] [rendered]
chunk {2} main.e402deade8b026b7d50e.bundle.js (main) 84 bytes [initial] [rendered]
chunk {3} inline.c252dc9d2f059fb83b07.bundle.js (inline) 1.45 kB [entry] [rendered]

npm ERR! Windows_NT 6.1.7601
`

and my version is 
`
D:\sources\newpcis\ng-alain>node -v
v6.10.3

D:\sources\newpcis\ng-alain>npm -v
3.10.10
`

ng-alain version is `0.3.2`

**Comment by cipchk** [comment]
Please upgrade nz-tree component to laster version.

**Comment by yangpengfei369** [comment]
@cipchk my some tree dependency version is 

  "name": "angular-tree-component",
  "version": "7.0.1"

  "name": "ng-tree-antd",
  "version": "2.2.2",

 nz-tree alreay upgrade latest version. run `npm run build` command failed 

` 12% building modules 21/23 modules 2 active ...s\fonts\Simple-Line-Icons.svg?v=
 12% building modules 22/23 modules 1 active ...font\weathericons-regular-webfon
 12% building modules 23/24 modules 1 active ...rces\newpcis\ng-alain\src\styles
Date: 2018-03-08T07:01:52.401Z
Hash: 62f2312a13a529135dd8
Time: 19185ms
chunk {scripts} scripts.b7bcc8d0d991085aaa87.bundle.js (scripts) 923 kB [initial
] [rendered]
chunk {0} styles.faf5ea4f8895e596d79c.bundle.css (styles) 543 kB [initial] [rend
ered]
chunk {1} polyfills.1c6a5562314418544ec4.bundle.js (polyfills) 268 bytes [initia
l] [rendered]
chunk {2} main.c6069b0780c882916252.bundle.js (main) 258 bytes [initial] [render
ed]
chunk {3} inline.2ba73c7dec2921066ca7.bundle.js (inline) 5.88 kB [entry] [render
ed]

ERROR in ..\ng-tree-antd\index.ts(10,2): Error during template compile of 'NzTre
eModule'
  Function calls are not supported in decorators but 'ɵmakeDecorator' was calle
d in 'NgModule'
    'NgModule' calls 'ɵmakeDecorator'.`

**Comment by cipchk** [comment]
I think this may be a problem with CLI. https://github.com/angular/angular-cli/issues/4647
