### ISSUE TITLE
sf正则表达式校验不生效

### ISSUE THREAD

**Issue by zhangjian4** [ng-alain/ng-alain#1973]
### Reproduction link
[https://stackblitz.com/edit/angular-cowolj?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-cowolj?file=src/app/app.component.ts)

### Steps to reproduce
在表单中输入非数字的文本

### What is expected?
校验不通过

### What is actually happening?
校验通过

| Environment | Info |
|---|---|
| ng-alain | 11.8.1 |
| Browser | chrome |

**Comment by cipchk** [comment]
ajv7 好像已经不再需要指定 `formatt`，试着移除它：

```diff
- format: "regex",
```
