### ISSUE TITLE
st表格应该显示文本内容,但是数据被xss注入

### ISSUE THREAD

**Issue by isHidden** [ng-alain/ng-alain#1979]
### Reproduction link
[https://codesandbox.io/s/ng-alain-xss-g7o04](https://codesandbox.io/s/ng-alain-xss-g7o04)

### Steps to reproduce
st表格加载数据

### What is expected?
不应该出现xss注入弹窗

### What is actually happening?
出现了alert弹窗

| Environment | Info |
|---|---|
| ng-alain | 11.9.0 |
| Browser | Edge，Chrome |

**Comment by cipchk** [comment]
当下的确为了方便，的确是信任HTML，允许我们直接传递一种带有特殊的行为，也没有相应开关，但是就目前这个示例中，可以将：

```diff
- { title: 'User', index: 'username' }
+ { title: 'User', index: 'username', format: i => i.username }
```

`format` 会做一步检测，如果带 `</` 则不做安全信任动作。
