### ISSUE TITLE
是否可以支持多标签页

### ISSUE THREAD

**Issue by wxq851685279** [ng-alain/ng-alain#1981]
## What problem does this feature solve?
希望添加点击菜单多标签页支持

## What does the proposed API look like?
希望添加点击菜单多标签页支持

**Comment by cipchk** [comment]
抱歉，我无法理解你的意思，能否提供具体的步骤？

**Comment by wxq851685279** [comment]
![image](https://user-images.githubusercontent.com/29041799/114875778-39c89e80-9e30-11eb-8ae2-7dd1433ab98c.png)
像这种

**Comment by cipchk** [comment]
https://ng-alain.com/components/reuse-tab

**Comment by wxq851685279** [comment]
![image](https://user-images.githubusercontent.com/29041799/138599025-7ad97992-2063-4d08-a498-27cbb7f2dc5d.png)
如何将面包屑导航放到标签页上面
@cipchk
