### ISSUE TITLE
codesandbox模板需要更新

### ISSUE THREAD

**Issue by Diluka** [ng-alain/ng-alain#1985]
### Reproduction link
[https://codesandbox.io/s/ng-alain-setup-dd0hq?file=/src/app/app.component.ts](https://codesandbox.io/s/ng-alain-setup-dd0hq?file=/src/app/app.component.ts)

### Steps to reproduce
点开codesandbox链接，这个模板旁边没有terminal

### What is expected?
旁边有terminal

### What is actually happening?
无法打开终端，无法执行脚本或者ng add等

| Environment | Info |
|---|---|
| ng-alain | 11.9.0 |
| Browser | edge |

---
这个就可以 https://github.com/codesandbox/codesandbox-client/issues/1437#issuecomment-565036479

**Comment by Amritanshu02** [comment]
Hello! I would like to work upon this issue. Could you suggest me where to start?

**Comment by cipchk** [comment]
@Amritanshu02 Codesandbox support's Angular and Angular Cli project, A Angular Cli project demo: https://codesandbox.io/s/confident-leakey-5rctv?file=/package.json 

I think can only compare the difference between the two to fix this.

**Comment by Amritanshu02** [comment]
Sir I tried to do that but was not able to do so.
My apologies Sir, I don't know anything about Angular right now.
Is there anything else I can do?
