### ISSUE TITLE
动态表单小部件中的Select在修改属性readonly时，下拉框内容不可选

### ISSUE THREAD

**Issue by wolfcome110** [ng-alain/ng-alain#1988]
### Reproduction link
[https://github.com/ng-alain/ng-alain/issues/new/choose](https://github.com/ng-alain/ng-alain/issues/new/choose)

### Steps to reproduce
无

### What is expected?
this.sf.getProperty('/LastVersion')!.ui.hidden = true;
执行这条语句不能隐藏掉，是写法不对？

### What is actually happening?
  schema: SFSchema = {
    properties: {
      LastVersion: { type: 'string', title: '理由' },
    },
  };

  ngAfterViewInit(): void {
   this.sf.getProperty('/LastVersion')!.ui.hidden = true;
  }
  不能将它隐藏，是写法不对吗？

| Environment | Info |
|---|---|
| ng-alain | 11.8.1 |
| Browser | Google Chrome 已是最新版本 版本 89.0.4389.114（正式版本） （64 位） |

**Comment by cipchk** [comment]
https://ng-alain.com/form/qa/zh?#%E5%A6%82%E4%BD%95%E5%88%B7%E6%96%B0%E7%89%B9%E5%AE%9ASchema%EF%BC%9F
