### ISSUE TITLE
simple table resReName invalid

### ISSUE THREAD

**Issue by liweitao92** [ng-alain/ng-alain#199]
![image](https://user-images.githubusercontent.com/30191996/34814107-78da72f4-f6e7-11e7-9378-3c6bff00683d.png)
![image](https://user-images.githubusercontent.com/30191996/34814124-8445cd5a-f6e7-11e7-85d9-dbcd6eead3c4.png)
![image](https://user-images.githubusercontent.com/30191996/34814145-8c03f648-f6e7-11e7-8e37-d82030af3a94.png)
resReName 设置的 total 没有效果

**Comment by cipchk** [comment]
请认真按 issues 模板的要求提供相应信息，谢谢。
