### ISSUE TITLE
CacheService支持POST

### ISSUE THREAD

**Issue by rxxy** [ng-alain/ng-alain#1999]
## What problem does this feature solve?
我发现CacheService使用了约定俗成的rest风格，在使用promise mode时，key不存在将自动使用GET方式获取有效数据。
但是还是有一些人没有使用rest，而是使用POST,或graphql，这时没办法使用promise mode这么好的功能。

如果可以支持自定义请求方式并全局配置的话，那这部分使用graphql或post请求的人也可以使用cacheService解决问题。简直awesome!

## What does the proposed API look like?
提供全局配置的未命中缓存的处理办法，如：
```
get: (key: string) => Observable<any>
```
promise模式下，在缓存未命中时，去调用get()，而不是直接发起一个http get请求

**Comment by Diluka** [comment]
@rxxy `POST`通常认为是非幂等请求，也就是每次请求不能保证返回值或者服务器处理的相同性，不支持缓存可以理解；然后，`GraphQL`有自己的缓存策略，你应该查看相应客户端的文档
