### ISSUE TITLE
bug:启动时，依赖包出错

### ISSUE THREAD

**Issue by mango-csl** [ng-alain/ng-alain#2]
`ERROR in Unexpected value '**PlatformModule** in F:/pool/git-program/ng-alain/node_modules/**@angular/cdk/cdk.d.ts**' imported by the module '**ScrollDispatchModule** in F:/pool/git-program/ng-alain/node_modules/ng-zorro-antd/src/release/core/overlay/scroll/index.d.ts'. 
Please add a @NgModule annotation.

node v6.9.5
npm  v3.10.10`

**Comment by cipchk** [comment]
看一下cdk的版本是多少，`ng-zorro-antd` 依赖的版本是 `cdk@2.0.0-beta.8`；若要重装就：

```bash
npm install @angular/cdk@2.0.0-beta.8
```

应该是依赖包没有安装全。

尝试删除 `node_modules` 和 `package-lock.json` 后，重新 `npm install`

另外，也可以尝试使用 `nrm`，然后使用 taobao 源，再安装  `npm install`。

**Comment by mango-csl** [comment]
cdk版本对的，然后我npm用的是蓝灯代理，cnpm用的淘宝镜像`http://registry.npm.taobao.org/`，两者下过来都是报同样的错误。

Module '"F:/testProgram/ng-alain/node_modules/ng-zorro-antd/node_modules/@angular/cdk/cdk"' **has no exported member**。。。。

之前有个老的项目，本来是正常的，今天我重新下载依赖包，也报这个错误
我猜测是不是跟我们公司的网络有关，准备回家再试试

**Comment by iedwin** [comment]
@cipchk 删除node-modules,yarn-lock，重新yarn，错误依旧，已yarn add @angular/cdk@2.0.0-beta.8 ：
<img width="1615" alt="screen shot 2017-08-30 at 11 31 44 pm" src="https://user-images.githubusercontent.com/17739715/29880865-89ae7d92-8d6e-11e7-9bc0-0e87ad0be70d.png">
<img width="310" alt="screen shot 2017-08-30 at 11 29 01 pm" src="https://user-images.githubusercontent.com/17739715/29880876-91644da0-8d6e-11e7-8151-579515f9a32f.png">

**Comment by alaahong** [comment]
Same issue,
`WARNING in ./node_modules/ng-zorro-antd/src/release/tabs/nz-tabs.module.js
21:40-52 "export 'PortalModule' was not found in '@angular/cdk'`


 fixed as https://github.com/NG-ZORRO/ng-zorro-antd/issues/191

  "dependencies": {
    "@angular/cdk": "^2.0.0-beta.8" 
}

**Comment by iedwin** [comment]
@cipchk 问题已解决，除了你提出的cdk版本方案以外，yarn有时好像会导致依赖无法正确按照package.json的变化而正常索引，删除node_modules，重新使用npm install后错误消失。

**Comment by pandsean** [comment]
楼上正解： 删除node_modules，重新使用npm install后错误消失。3Q
