### ISSUE TITLE
simple resReName total invalid

### ISSUE THREAD

**Issue by liweitao92** [ng-alain/ng-alain#200]
## Bug Report or Feature Request (mark with an `x`)
- [x ] bug report -> please search issues before submitting
- [ ] feature request

## Current behavior
resReName 的 total 重命名无效

## Expected behavior
这是个 bug？

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/ng-alain-setup-rcbvzv?file=app%2Fapp.component.ts

## Environment

Angular version: 5.0.0

delon version: 0.5.0

For Tooling issues:
- Node version: v8.2.1
- Platform:  Mac

**Comment by cipchk** [comment]
我不明白哪里有什么问题？

**Comment by liweitao92** [comment]
@cipchk 总条数显示的0
