### ISSUE TITLE
st采用行编辑并且指定列的类型tag(支持行编辑)，则tag显示无效

### ISSUE THREAD

**Issue by wolfcome110** [ng-alain/ng-alain#2000]
### Reproduction link
[https://stackblitz.com/edit/ng-alain-setup-biee37)

### Steps to reproduce
https://codesandbox.io/s/eviww

### What is expected?
支持行编辑，支持tag类型的显示

### What is actually happening?

st采用行编辑时定义的tag类型的列没有效果

| Environment | Info |
|---|---|
| ng-alain | 11.8.1 |
| Browser | 谷歌 |

---
TAG: STColumnTag = {
  1: { text: '成功', color: 'green' },
  2: { text: '错误', color: 'red' },
  3: { text: '进行中', color: 'blue' },
  4: { text: '默认', color: '' },
  5: { text: '警告', color: 'orange' },
};
  columns: STColumn[] = [
    { title: 'ReviseMark', index: 'ReviseMark' },
    { title: 'ItemNo', index: 'ItemNo' },
    { title: 'Confirmed', index: 'Confirmed', render: 'Comfirm_ConTpl', type: 'tag', tag: TAG },   
  ];

**Comment by cipchk** [comment]
@wolfcome110 麻烦提供个重现示例。
> 注意可以将 `"core-js": "3.9.1",` 固定为 `3.9.1` 方可以运行上述提到的示例。

**Comment by wolfcome110** [comment]
> @wolfcome110 麻烦提供个重现示例。
> 
> > 注意可以将 `"core-js": "3.9.1",` 固定为 `3.9.1` 方可以运行上述提到的示例。

https://stackblitz.com/edit/ng-alain-setup-biee37，这个在线模拟的一个示例，让表格支持行编译时，列设置为tag时显示无效

**Comment by cipchk** [comment]
在有 `render` 将的情况下，将由自己接管，所以这里只能你手动修正，例如：

```diff
- <ng-container *ngIf="!item.edit">{{ item.Quntity }}</ng-container>
+ <ng-container *ngIf="!item.edit">
+   <nz-tag [nzColor]="item._values[0].color">
+     <span [innerHTML]="item._values[0].text"></span>
+   </nz-tag>
+ </ng-container>
```
