### ISSUE TITLE
sf object 类型 required 首次初始化状态错误

### ISSUE THREAD

**Issue by C-racker** [ng-alain/ng-alain#2002]
### Reproduction link
[https://stackblitz.com/edit/angular-haeyat?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/edit/angular-haeyat?file=src%2Fapp%2Fapp.component.ts)

### Steps to reproduce
country 为必填，首次加载后提交按钮没有被置灰

### What is expected?
首次加载存在必填项提交按钮应被置灰

### What is actually happening?
首次加载提交按钮没有被置灰

| Environment | Info |
|---|---|
| ng-alain | 11.10.1 |
| Browser | Edge 90.0.818.62 |

**Comment by cipchk** [comment]
@C-racker JSON Schema 规则里 `address1` 为非必填项时，`country` 自然也会非必填，这也符合我们常规理解的逻辑，因此你想要让子对象触发，则：

```diff
this.schema = {
      properties: {
        address1: {
          title: '地址1',
          type: 'object',
          properties: {
            country: { type: 'string' },
            city: { type: 'string' },
            zone: { type: 'string' }
          },
          required: ['country']
        },
      },
+      required: ['address1']
    };
```
