### ISSUE TITLE
st新增类型string

### ISSUE THREAD

**Issue by Diluka** [ng-alain/ng-alain#2006]
## What problem does this feature solve?
将任意数据已字符串形式渲染，当前默认使用的是innerHTML，有xss注入风险

## What does the proposed API look like?
type='string'

**Comment by cipchk** [comment]
`st` 支持是否信任 html 的选项 `safeHtml`。

**Comment by Diluka** [comment]
> `st` 支持是否信任 html 的选项 `safeHtml`。

支持，但是这里不是一回事，是要将html数据当成字符串显示出来，目前必须自己写一个template来实现，但是这应该是一个基本功能

**Comment by cipchk** [comment]
如果 `safehtml` 无法满足场景，可以增加一个重现示例，离开场景的讨论将都是无意义的。

**Comment by Diluka** [comment]
> 如果 `safehtml` 无法满足场景，可以增加一个重现示例，离开场景的讨论将都是无意义的。

就是需要将数据显示在表格的格子里面，就算它是html，也不要渲染，要原封不动的显示出来。

实际情况是有一个昵称字段，有人使用html标签当做昵称，目前的st会渲染它而不是当字符串打印，除了xss问题之外，这个标签如果这样写`<img src>`并不会触发xss，但是却看不见了，就是一个空白，这个地方也没有渲染html的设计，是什么字符串就显示什么字符串才对。

当前的处理方案就是每个表格都放一个这个模板
`<ng-template st-row="string" let-o let-column="column">{{ o | _: 'get':column.index:'-' }}</ng-template>`

**Comment by Diluka** [comment]
## 总结
1. 新增类型`text`，将数据以类似`innerText`的形式直接显示为文本
2. 将现有的`''`空类型作为`html`类型，与新增的`text`类型对应
3. 新增st全局配置`defaultType`(随便取的名字)，默认值为`html`，就也是当前行为，将数据以类似`innerHTML`的形式渲染出来
4. 这样可以更加明确的告知开发者，他们的字符串数据将会以什么形式展现出来。特别地，要让他们知道，默认行为是**富！文！本！**

@cipchk

**Comment by cipchk** [comment]
恩，有道理，特别文本提到利用 `innerText` 倒是一个很不错的方案，我一直忽略了 `innerText` 的作用。
