### ISSUE TITLE
g2-mini-bar 指定color无变化

### ISSUE THREAD

**Issue by LFR1314** [ng-alain/ng-alain#2013]
### Reproduction link
[https://py6hw6--run.stackblitz.io](https://py6hw6--run.stackblitz.io)

### Steps to reproduce
数据内指定color元效

### What is expected?
每条柱的颜色可以自定义

### What is actually happening?
颜色默认无变化

| Environment | Info |
|---|---|
| ng-alain | 11.10.2 |
| Browser | google-91.0.4472.77（正式版本） (x86_64) |

---
用g2-bar指定color可以变色，mini不行

**Comment by cipchk** [comment]
@RayLoveJoe Demo无法打开，能否重新更新一下。
