### ISSUE TITLE
sf的手机号码格式校验不支持一些新的号码段

### ISSUE THREAD

**Issue by zhangjian4** [ng-alain/ng-alain#2014]
### Reproduction link
[https://stackblitz.com/edit/angular-72pskh?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-72pskh?file=src/app/app.component.ts)

### Steps to reproduce
输入166开头的手机号

### What is expected?
校验通过

### What is actually happening?
校验不通过

| Environment | Info |
|---|---|
| ng-alain | 11.10.2 |
| Browser | chrome |

**Comment by cipchk** [comment]
可以在全局配置中覆盖默认行为，例如：

```diff
const alainConfig: AlainConfig = {
  mock: { data: MOCKDATA },
+  sf: {
+    ajv: {
+      formats: {
+        mobile: new RegExp(`^[0-9]{10}`)
+      }
+    }
+  }
};
```
