### ISSUE TITLE
建议 theme-btn 组件生成的 link 标签的 href 跟随 --deployUrl 参数（如有）

### ISSUE THREAD

**Issue by xiaohuilam** [ng-alain/ng-alain#2016]
目前 theme-btn 没有自动在 href 拼入 --deployUrl

https://github.com/ng-alain/delon/blob/master/packages/theme/theme-btn/theme-btn.component.ts#L94

**Comment by cipchk** [comment]
@xiaohuilam `link` 标签元素在请求时应该会根据 `base` 里面的 `href` 为基准才对，至于 `deployUrl` 参数在最终编译后也会将该参数写入到 `index.html` 的 `base` 里面。

**Comment by xiaohuilam** [comment]
&gt; 至于&nbsp;deployUrl&nbsp;参数在最终编译后也会将该参数写入到&nbsp;index.html&nbsp;的&nbsp;base&nbsp;里面。



实测不会(demo: https://secure.quantumca.com.cn 查看源base非CDN域) 。
可能是因为 base 会污染 a 标签到CDN域名。

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："卡色 ***@***.***&gt;;
发送时间：2021年6月28日(星期一) 中午1:27
收件人："ng-alain/ng-alain" ***@***.***&gt;;
抄送："Bruce Lam ***@***.***&gt;;"Mention ***@***.***&gt;;
主题：Re: [ng-alain/ng-alain] 建议 theme-btn 组件生成的 link 标签的 href 跟随 --deployUrl 参数（如有） (#2016)
-----------------------------------

 

 
@xiaohuilam link 标签元素在请求时应该会根据 base 里面的 href 为基准才对，至于 deployUrl 参数在最终编译后也会将该参数写入到 index.html 的 base 里面。
