### ISSUE TITLE
startup.service.ts发送http请求时，设置headers

### ISSUE THREAD

**Issue by ada-hou** [ng-alain/ng-alain#202]
最初设想是在startup.service.ts中的load方法中向后台请求一些数据，angular自动编译报错
经过测试发现，在load方法中加入new HttpHeaders()，就会报错
![image](https://user-images.githubusercontent.com/18135689/34822020-7c7bbb48-f700-11e7-9950-b9ef4988fdd6.png)
报错内容为
ERROR in ./src/app/core/startup/startup.service.ts
Module not found: Error: Can't resolve '@angular/common/http/src/headers' in '/Users/ada/workfile/memo/ada-alain/src/app/core/startup'
resolve '@angular/common/http/src/headers' in '/Users/ada/workfile/memo/ada-alain/src/app/core/startup'
  Parsed request is a module
  using description file: /Users/ada/workfile/memo/ada-alain/package.json (relative path: ./src/app/core/startup)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /Users/ada/workfile/memo/ada-alain/package.json (relative path: ./src/app/core/startup)
    resolve as module
      /Users/ada/workfile/memo/ada-alain/src/app/core/startup/node_modules doesn't exist or is not a directory
      /Users/ada/workfile/memo/ada-alain/src/app/core/node_modules doesn't exist or is not a directory
      /Users/ada/workfile/memo/ada-alain/src/app/node_modules doesn't exist or is not a directory
      /Users/ada/workfile/memo/ada-alain/src/node_modules doesn't exist or is not a directory
      /Users/ada/workfile/memo/node_modules doesn't exist or is not a directory
      /Users/ada/workfile/node_modules doesn't exist or is not a directory
      /Users/ada/node_modules doesn't exist or is not a directory
      /Users/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
      looking for modules in /Users/ada/workfile/memo/ada-alain/node_modules
        using description file: /Users/ada/workfile/memo/ada-alain/package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: /Users/ada/workfile/memo/ada-alain/package.json (relative path: ./node_modules)
          using description file: /Users/ada/workfile/memo/ada-alain/node_modules/@angular/common/http/package.json (relative path: ./src/headers)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /Users/ada/workfile/memo/ada-alain/node_modules/@angular/common/http/src/headers doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /Users/ada/workfile/memo/ada-alain/node_modules/@angular/common/http/src/headers.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/ada/workfile/memo/ada-alain/node_modules/@angular/common/http/src/headers.js doesn't exist
            as directory
              /Users/ada/workfile/memo/ada-alain/node_modules/@angular/common/http/src/headers doesn't exist
      looking for modules in /Users/ada/workfile/memo/ada-alain/node_modules
        using description file: /Users/ada/workfile/memo/ada-alain/package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: /Users/ada/workfile/memo/ada-alain/package.json (relative path: ./node_modules)
          using description file: /Users/ada/workfile/memo/ada-alain/node_modules/@angular/common/http/package.json (relative path: ./src/headers)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /Users/ada/workfile/memo/ada-alain/node_modules/@angular/common/http/src/headers doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /Users/ada/workfile/memo/ada-alain/node_modules/@angular/common/http/src/headers.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/ada/workfile/memo/ada-alain/node_modules/@angular/common/http/src/headers.js doesn't exist
            as directory
              /Users/ada/workfile/memo/ada-alain/node_modules/@angular/common/http/src/headers doesn't exist
      looking for modules in /Users/ada/workfile/memo/ada-alain/src
        using description file: /Users/ada/workfile/memo/ada-alain/package.json (relative path: ./src)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: /Users/ada/workfile/memo/ada-alain/package.json (relative path: ./src)
          using description file: /Users/ada/workfile/memo/ada-alain/package.json (relative path: ./src/@angular/common/http/src/headers)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /Users/ada/workfile/memo/ada-alain/src/@angular/common/http/src/headers doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /Users/ada/workfile/memo/ada-alain/src/@angular/common/http/src/headers.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/ada/workfile/memo/ada-alain/src/@angular/common/http/src/headers.js doesn't exist
            as directory
              /Users/ada/workfile/memo/ada-alain/src/@angular/common/http/src/headers doesn't exist
      looking for modules in /Users/ada/workfile/memo/ada-alain/src
        using description file: /Users/ada/workfile/memo/ada-alain/package.json (relative path: ./src)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: /Users/ada/workfile/memo/ada-alain/package.json (relative path: ./src)
          using description file: /Users/ada/workfile/memo/ada-alain/package.json (relative path: ./src/@angular/common/http/src/headers)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /Users/ada/workfile/memo/ada-alain/src/@angular/common/http/src/headers doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /Users/ada/workfile/memo/ada-alain/src/@angular/common/http/src/headers.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/ada/workfile/memo/ada-alain/src/@angular/common/http/src/headers.js doesn't exist
            as directory
              /Users/ada/workfile/memo/ada-alain/src/@angular/common/http/src/headers doesn't exist
      looking for modules in /Users/ada/workfile/memo/ada-alain/src
        using description file: /Users/ada/workfile/memo/ada-alain/package.json (relative path: ./src)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: /Users/ada/workfile/memo/ada-alain/package.json (relative path: ./src)
          using description file: /Users/ada/workfile/memo/ada-alain/package.json (relative path: ./src/@angular/common/http/src/headers)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /Users/ada/workfile/memo/ada-alain/src/@angular/common/http/src/headers doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /Users/ada/workfile/memo/ada-alain/src/@angular/common/http/src/headers.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/ada/workfile/memo/ada-alain/src/@angular/common/http/src/headers.js doesn't exist
            as directory
              /Users/ada/workfile/memo/ada-alain/src/@angular/common/http/src/headers doesn't exist
      looking for modules in /Users/ada/workfile/memo/ada-alain/src
        using description file: /Users/ada/workfile/memo/ada-alain/package.json (relative path: ./src)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: /Users/ada/workfile/memo/ada-alain/package.json (relative path: ./src)
          using description file: /Users/ada/workfile/memo/ada-alain/package.json (relative path: ./src/@angular/common/http/src/headers)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /Users/ada/workfile/memo/ada-alain/src/@angular/common/http/src/headers doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /Users/ada/workfile/memo/ada-alain/src/@angular/common/http/src/headers.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/ada/workfile/memo/ada-alain/src/@angular/common/http/src/headers.js doesn't exist
            as directory
              /Users/ada/workfile/memo/ada-alain/src/@angular/common/http/src/headers doesn't exist
      looking for modules in /Users/ada/workfile/memo/ada-alain/src
        using description file: /Users/ada/workfile/memo/ada-alain/package.json (relative path: ./src)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: /Users/ada/workfile/memo/ada-alain/package.json (relative path: ./src)
          using description file: /Users/ada/workfile/memo/ada-alain/package.json (relative path: ./src/@angular/common/http/src/headers)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /Users/ada/workfile/memo/ada-alain/src/@angular/common/http/src/headers doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /Users/ada/workfile/memo/ada-alain/src/@angular/common/http/src/headers.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/ada/workfile/memo/ada-alain/src/@angular/common/http/src/headers.js doesn't exist
            as directory
              /Users/ada/workfile/memo/ada-alain/src/@angular/common/http/src/headers doesn't exist
      looking for modules in /Users/ada/workfile/memo/ada-alain/src
        using description file: /Users/ada/workfile/memo/ada-alain/package.json (relative path: ./src)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: /Users/ada/workfile/memo/ada-alain/package.json (relative path: ./src)
          using description file: /Users/ada/workfile/memo/ada-alain/package.json (relative path: ./src/@angular/common/http/src/headers)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /Users/ada/workfile/memo/ada-alain/src/@angular/common/http/src/headers doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /Users/ada/workfile/memo/ada-alain/src/@angular/common/http/src/headers.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/ada/workfile/memo/ada-alain/src/@angular/common/http/src/headers.js doesn't exist
            as directory
              /Users/ada/workfile/memo/ada-alain/src/@angular/common/http/src/headers doesn't exist
      looking for modules in /Users/ada/workfile/memo/ada-alain/src
        using description file: /Users/ada/workfile/memo/ada-alain/package.json (relative path: ./src)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: /Users/ada/workfile/memo/ada-alain/package.json (relative path: ./src)
          using description file: /Users/ada/workfile/memo/ada-alain/package.json (relative path: ./src/@angular/common/http/src/headers)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /Users/ada/workfile/memo/ada-alain/src/@angular/common/http/src/headers doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /Users/ada/workfile/memo/ada-alain/src/@angular/common/http/src/headers.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/ada/workfile/memo/ada-alain/src/@angular/common/http/src/headers.js doesn't exist
            as directory
              /Users/ada/workfile/memo/ada-alain/src/@angular/common/http/src/headers doesn't exist
      looking for modules in /Users/ada/workfile/memo/ada-alain/src
        using description file: /Users/ada/workfile/memo/ada-alain/package.json (relative path: ./src)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: /Users/ada/workfile/memo/ada-alain/package.json (relative path: ./src)
          using description file: /Users/ada/workfile/memo/ada-alain/package.json (relative path: ./src/@angular/common/http/src/headers)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /Users/ada/workfile/memo/ada-alain/src/@angular/common/http/src/headers doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /Users/ada/workfile/memo/ada-alain/src/@angular/common/http/src/headers.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/ada/workfile/memo/ada-alain/src/@angular/common/http/src/headers.js doesn't exist
            as directory
              /Users/ada/workfile/memo/ada-alain/src/@angular/common/http/src/headers doesn't exist
      looking for modules in /Users/ada/workfile/memo/ada-alain/src
        using description file: /Users/ada/workfile/memo/ada-alain/package.json (relative path: ./src)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: /Users/ada/workfile/memo/ada-alain/package.json (relative path: ./src)
          using description file: /Users/ada/workfile/memo/ada-alain/package.json (relative path: ./src/@angular/common/http/src/headers)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /Users/ada/workfile/memo/ada-alain/src/@angular/common/http/src/headers doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /Users/ada/workfile/memo/ada-alain/src/@angular/common/http/src/headers.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/ada/workfile/memo/ada-alain/src/@angular/common/http/src/headers.js doesn't exist
            as directory
              /Users/ada/workfile/memo/ada-alain/src/@angular/common/http/src/headers doesn't exist
      looking for modules in /Users/ada/workfile/memo/ada-alain/src
        using description file: /Users/ada/workfile/memo/ada-alain/package.json (relative path: ./src)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: /Users/ada/workfile/memo/ada-alain/package.json (relative path: ./src)
          using description file: /Users/ada/workfile/memo/ada-alain/package.json (relative path: ./src/@angular/common/http/src/headers)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /Users/ada/workfile/memo/ada-alain/src/@angular/common/http/src/headers doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /Users/ada/workfile/memo/ada-alain/src/@angular/common/http/src/headers.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/ada/workfile/memo/ada-alain/src/@angular/common/http/src/headers.js doesn't exist
            as directory
              /Users/ada/workfile/memo/ada-alain/src/@angular/common/http/src/headers doesn't exist
[/Users/ada/workfile/memo/ada-alain/src/app/core/startup/node_modules]
[/Users/ada/workfile/memo/ada-alain/src/app/core/node_modules]
[/Users/ada/workfile/memo/ada-alain/src/app/node_modules]
[/Users/ada/workfile/memo/ada-alain/src/node_modules]
[/Users/ada/workfile/memo/node_modules]
[/Users/ada/workfile/node_modules]
[/Users/ada/node_modules]
[/Users/node_modules]
[/node_modules]
[/Users/ada/workfile/memo/ada-alain/node_modules/@angular/common/http/src/headers]
[/Users/ada/workfile/memo/ada-alain/node_modules/@angular/common/http/src/headers.ts]
[/Users/ada/workfile/memo/ada-alain/node_modules/@angular/common/http/src/headers.js]
[/Users/ada/workfile/memo/ada-alain/node_modules/@angular/common/http/src/headers]
[/Users/ada/workfile/memo/ada-alain/node_modules/@angular/common/http/src/headers]
[/Users/ada/workfile/memo/ada-alain/node_modules/@angular/common/http/src/headers.ts]
[/Users/ada/workfile/memo/ada-alain/node_modules/@angular/common/http/src/headers.js]
[/Users/ada/workfile/memo/ada-alain/node_modules/@angular/common/http/src/headers]
[/Users/ada/workfile/memo/ada-alain/src/@angular/common/http/src/headers]
[/Users/ada/workfile/memo/ada-alain/src/@angular/common/http/src/headers.ts]
[/Users/ada/workfile/memo/ada-alain/src/@angular/common/http/src/headers.js]
[/Users/ada/workfile/memo/ada-alain/src/@angular/common/http/src/headers]
[/Users/ada/workfile/memo/ada-alain/src/@angular/common/http/src/headers]
[/Users/ada/workfile/memo/ada-alain/src/@angular/common/http/src/headers.ts]
[/Users/ada/workfile/memo/ada-alain/src/@angular/common/http/src/headers.js]
[/Users/ada/workfile/memo/ada-alain/src/@angular/common/http/src/headers]
[/Users/ada/workfile/memo/ada-alain/src/@angular/common/http/src/headers]
[/Users/ada/workfile/memo/ada-alain/src/@angular/common/http/src/headers.ts]
[/Users/ada/workfile/memo/ada-alain/src/@angular/common/http/src/headers.js]
[/Users/ada/workfile/memo/ada-alain/src/@angular/common/http/src/headers]
[/Users/ada/workfile/memo/ada-alain/src/@angular/common/http/src/headers]
[/Users/ada/workfile/memo/ada-alain/src/@angular/common/http/src/headers.ts]
[/Users/ada/workfile/memo/ada-alain/src/@angular/common/http/src/headers.js]
[/Users/ada/workfile/memo/ada-alain/src/@angular/common/http/src/headers]
[/Users/ada/workfile/memo/ada-alain/src/@angular/common/http/src/headers]
[/Users/ada/workfile/memo/ada-alain/src/@angular/common/http/src/headers.ts]
[/Users/ada/workfile/memo/ada-alain/src/@angular/common/http/src/headers.js]
[/Users/ada/workfile/memo/ada-alain/src/@angular/common/http/src/headers]
[/Users/ada/workfile/memo/ada-alain/src/@angular/common/http/src/headers]
[/Users/ada/workfile/memo/ada-alain/src/@angular/common/http/src/headers.ts]
[/Users/ada/workfile/memo/ada-alain/src/@angular/common/http/src/headers.js]
[/Users/ada/workfile/memo/ada-alain/src/@angular/common/http/src/headers]
[/Users/ada/workfile/memo/ada-alain/src/@angular/common/http/src/headers]
[/Users/ada/workfile/memo/ada-alain/src/@angular/common/http/src/headers.ts]
[/Users/ada/workfile/memo/ada-alain/src/@angular/common/http/src/headers.js]
[/Users/ada/workfile/memo/ada-alain/src/@angular/common/http/src/headers]
[/Users/ada/workfile/memo/ada-alain/src/@angular/common/http/src/headers]
[/Users/ada/workfile/memo/ada-alain/src/@angular/common/http/src/headers.ts]
[/Users/ada/workfile/memo/ada-alain/src/@angular/common/http/src/headers.js]
[/Users/ada/workfile/memo/ada-alain/src/@angular/common/http/src/headers]
[/Users/ada/workfile/memo/ada-alain/src/@angular/common/http/src/headers]
[/Users/ada/workfile/memo/ada-alain/src/@angular/common/http/src/headers.ts]
[/Users/ada/workfile/memo/ada-alain/src/@angular/common/http/src/headers.js]
[/Users/ada/workfile/memo/ada-alain/src/@angular/common/http/src/headers]
[/Users/ada/workfile/memo/ada-alain/src/@angular/common/http/src/headers]
[/Users/ada/workfile/memo/ada-alain/src/@angular/common/http/src/headers.ts]
[/Users/ada/workfile/memo/ada-alain/src/@angular/common/http/src/headers.js]
[/Users/ada/workfile/memo/ada-alain/src/@angular/common/http/src/headers]
 @ ./src/app/core/startup/startup.service.ts 19:16-59
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 webpack/hot/dev-server ./src/main.ts

**Comment by cipchk** [comment]
[HttpHeaders](https://angular.io/api/common/http/HttpHeaders) 是不可变值，请自行google或文档。

**Comment by ada-hou** [comment]
![image](https://user-images.githubusercontent.com/18135689/34825661-5b07f608-f70e-11e7-814a-95ae27ee358a.png)
![image](https://user-images.githubusercontent.com/18135689/34825686-73514d4a-f70e-11e7-896b-4d0aeeb9176d.png)
按照官方文档写也同样的错，在其他页面上使用这个方法不报错
![image](https://user-images.githubusercontent.com/18135689/34825721-977f3588-f70e-11e7-9a0a-83915358179c.png)
