### ISSUE TITLE
Parent object accessor with SFUISchema visibleIf

### ISSUE THREAD

**Issue by myatmin** [ng-alain/ng-alain#2029]
## What problem does this feature solve?
When the form has a nested `Array` type. (Example: multiple cities and multiple country).

If you use the root accessor, it has to be called `/country/0/city/0/name`.

But fixed index does not work for the following requirement.

For example, `City` property will be based on its containing parent `Country` object property(`countryCode`, `countryType`).

## What does the proposed API look like?
`../countryCode`

`../countryType`

**Comment by cipchk** [comment]
fixed by https://github.com/ng-alain/delon/pull/1281
