### ISSUE TITLE
tree async is not working

### ISSUE THREAD

**Issue by vellengs** [ng-alain/ng-alain#203]
## Bug Report or Feature Request (mark with an `x`)
<pre><code>
[ ] Bug report -> please search issues before submitting
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior
tree async is not working.

## Expected behavior
should work.
please check the demo 
```
https://cipchk.github.io/ng-alain/elements/tree-antd
```

**Comment by rieonke** [comment]
more details? configurations or tree data?

**Comment by lyc152** [comment]
可以参考 https://github.com/cipchk/ng-alain/blob/master/src/app/routes/elements/tree-antd/async.component.ts

**Comment by cipchk** [comment]
please upgrade `ng-tree-antd` to laster version.
