### ISSUE TITLE
simple-table SimpleTableConfig pi

### ISSUE THREAD

**Issue by liweitao92** [ng-alain/ng-alain#204]
## Bug Report or Feature Request (mark with an `x`)
<pre><code>
[ x] Bug report -> please search issues before submitting
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior
在SimpleTableConfig 设置 pi 为0，但是没有并没有产生效果

## Minimal reproduction of the problem with instructions

![image](https://user-images.githubusercontent.com/30191996/34828085-4f7475c4-f717-11e7-85d9-bbdaa32264e9.png)
![image](https://user-images.githubusercontent.com/30191996/34828094-5b10e462-f717-11e7-9d2e-e7de4027a5b6.png)

## Environment

<pre><code>
Angular version: 5.0.0
delon version: 0.6.0-rc.2

**Comment by cipchk** [comment]
这种做法只是针对 CoreModuel 建议在根目录，或见 [commit](https://github.com/cipchk/ng-alain/commit/571d3e416b3b476aacdd6904f75b412a5b0fa3b3).
