### ISSUE TITLE
sf upload小部件multiple: true时数据被擦除bug

### ISSUE THREAD

**Issue by jurendada** [ng-alain/ng-alain#2046]
### Reproduction link
[https://stackblitz.com/edit/ng-alain-setup-469ep3](https://stackblitz.com/edit/ng-alain-setup-469ep3)

### Steps to reproduce
问题描述： sf的upload 小部件在 multiple: true时，upload 的数据未进行任何修改操作，重新保存时，被 resReName 擦除了。
 
    <sf
      #sf
      mode="edit"
      [schema]="schema"
      [ui]="ui"
      [formData]="formData"
      (formSubmit)="save(sf.value)"
    >

  formData = {
    imgs: [
      {
        uid: '1',
        name: 'xxx.png',
        status: 'done',
        url:
          'https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png'
      }
    ]
  };

  schema: SFSchema = {
    properties: {
      imgs: { type: 'string', title: '图片列表' }
    }
  };

  ui: SFUISchema = {
    $imgs: {
      widget: 'upload',
      action: 'minio/upload',
      multiple: true,
      withCredentials: true
    } as SFUploadWidgetSchema
  };

  save(value: any) {
    console.log(value);
    // 未修改imgs的数据，只点击保存时，value 的值为 {imgs: [undefined]}
    // 问题描述： 表单的upload 小部件在 multiple: true时，数据被 resReName 擦除了
  }

### What is expected?
upload 小部件在multiple: true时，小部件的数据在编辑状态下，未重新上传，增加上传，删除文件时，都能让fileList保持UploadFile[]格式的数据，不被resReName 擦除

### What is actually happening?
upload 小部件的数据的被  resReName 擦除

| Environment | Info |
|---|---|
| ng-alain | 12.0.2 |
| Browser | 谷歌浏览器 |

**Comment by cipchk** [comment]
`fileList` 只是服务于 `nzFileList`，表单而言需要的是后端数据，而对于后端的数据应该在 `response` 下，例如：

```diff
  formData = {
    imgs: [
      {
        uid: '1',
        name: 'xxx.png',
        status: 'done',
        url:
          'https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png',
+        response: {
+          id: 10,
+        }
      },
      {
        uid: '2',
        name: 'yyy.png',
        status: 'done',
        url:
          'https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png'
      }
    ]
  };
```
