### ISSUE TITLE
sf 自定义 widget 内部 nz-form 布局会受外部  sf layout 设置影响

### ISSUE THREAD

**Issue by chf007** [ng-alain/ng-alain#2058]
### Reproduction link
[https://stackblitz.com/edit/angular-rfnt1v?file=src/app/widgets/cr-item-form/cr-item-form.widget.html](https://stackblitz.com/edit/angular-rfnt1v?file=src/app/widgets/cr-item-form/cr-item-form.widget.html)

### Steps to reproduce
sf 设置 [layout]="'vertical'"，自定义 widget nz-form 设置 nzLayout="horizontal"，但是并不生效，布局还是 vertical

### What is expected?
自定义 widget 的 nz-form 可以有自已的布局设定

### What is actually happening?
自定义 widget 的 nz-form 布局复用了 sf 的布局定义

| Environment | Info |
|---|---|
| ng-alain | 12.1.0 |
| Browser | Mac Chrome 92.0.4515.107 |

**Comment by cipchk** [comment]
如果要内部改变布局，最好是使用 `nz-row`、`nz-col` 配合，例如：

```html
<sf-item-wrap [id]="id" [schema]="schema" [ui]="ui" [showError]="showError" [error]="error" [showTitle]="schema.title">
  <div nz-row>
    <div nz-col nzSpan="6">
      请选择
    </div>
    <div nz-col nzSpan="18">
      <nz-select>
        <nz-option nzValue="1" nzLabel="选项1"></nz-option>
        <nz-option nzValue="2" nzLabel="选项2"></nz-option>
      </nz-select>
    </div>
  </div>
  <div nz-row>
    <div nz-col nzSpan="6">
      是否选中
    </div>
    <div nz-col nzSpan="18">
      <label nz-checkbox>
        <span>已选中</span>
      </label>
    </div>
  </div>

</sf-item-wrap>
```
