### ISSUE TITLE
存储token-存储类型为CookieStorageStore时系统报错

### ISSUE THREAD

**Issue by whx07** [ng-alain/ng-alain#2059]
### Reproduction link
[https://stackblitz.com/edit/ng-alain-setup-95mayr?file=src%2Fapp%2Fglobal-config.module.ts](https://stackblitz.com/edit/ng-alain-setup-95mayr?file=src%2Fapp%2Fglobal-config.module.ts)

### Steps to reproduce
1.global-config.module.ts里面设置存储token方式CookieStorageStore
{
    provide: DA_STORE_TOKEN,
    useClass: CookieStorageStore,
    deps: [CookieService]
  }

### What is expected?
系统不报错，正常使用

### What is actually happening?
系统报：SyntaxError:unExpected token u in JSON at position 0 auth.js:309 JSON.pars

| Environment | Info |
|---|---|
| ng-alain | 12.1.0 |
| Browser | chrome |

---
进一步分析，发现是cookie-storage.service.ts这个文件里面的get方法出现问题
get(key: string): ITokenModel {
    return JSON.parse(this.srv.get(key) || '{}') || {};
  }
当this.srv.get(key)为undefined时，并不会返回{},所以JSON.parse方法会报错，建议返回之前加个undefined判断

**Comment by cipchk** [comment]
先引用后使用，而不是先使用或引用：https://stackblitz.com/edit/ng-alain-setup-93rp9a?file=src%2Fapp%2Fglobal-config.module.ts
