### ISSUE TITLE
sf表单验证必填失败

### ISSUE THREAD

**Issue by JustForYouKing** [ng-alain/ng-alain#2067]
### Reproduction link
[https://stackblitz.com/edit/angular-jlefrc?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-jlefrc?file=src/app/app.component.ts)

### Steps to reproduce
sf中配置表单组件和必填项目，必填项目不填写或者选择任何值
调用this.sf?.valid
返回true

### What is expected?
返回实际表单验证结果

### What is actually happening?
不管验证是否通过，都返回true

| Environment | Info |
|---|---|
| ng-alain | 12.1.1 |
| Browser | Google Chrome 91.0.4472.124 |

**Comment by cipchk** [comment]
主要是因为 ajv 从 7.x 开始对 Schema 默认非常严谨，可以通过 GlobalConfig 统一配置 sf 的 `ajv` 选项为 `strict: false`。
