### ISSUE TITLE
ReuseTabService 能否提供完善接口

### ISSUE THREAD

**Issue by winpzs** [ng-alain/ng-alain#207]
## Bug Report or Feature Request (mark with an `x`)
<pre><code>
[ ] Bug report -> please search issues before submitting
[X] Feature request
[ ] Documentation issue or request
</code></pre>

## Feature request
* **ReuseTabService** 能否提供更多接口
   * 获取**Reuse-Tab**信息(如：title, url, 是否当前页面，是否可以reuse等)
   * 根据**Reuse-Tab**提供相关接口（如：删除，设置当前页等）

**Comment by cipchk** [comment]
关闭此问题，当下已满足日常所需要的接口，若有需求，请重新提交更完整的需求说明的ISSUES。
