### ISSUE TITLE
st的change回调类型允许string

### ISSUE THREAD

**Issue by Anberm** [ng-alain/ng-alain#2075]
## What problem does this feature solve?
在st的定制化功能时，比如导出，我们需要根据类型来处理st.change的内容，目前change的type被固定了那几项，应该允许开发者定义更多的类型来做定制化处理

## What does the proposed API look like?
export declare type STChangeType = 'loaded' | 'pi' | 'ps' | 'checkbox' | 'radio' | 'sort' | 'filter' | 'click' | 'dblClick' | 'expand' | 'resize' | string;

**Comment by cipchk** [comment]
你可以自行扩展，例如：

```ts
export type NewSTChangeType = STChangeType | 'asdf';
```

**Comment by Anberm** [comment]
好的，也行
