### ISSUE TITLE
require 校验对 format:"month" 无效

### ISSUE THREAD

**Issue by wyq-L** [ng-alain/ng-alain#2077]
### Reproduction link
[https://stackblitz.com/edit/ng-alain-setup-kd3v5f](https://stackblitz.com/edit/ng-alain-setup-kd3v5f)

### Steps to reproduce
 schema = {
    properties: {
      month: {
        type: 'string',
        format: 'month'
      }
    },
    required: ['month']
  };
对于format:'month' required无法校验  可以直接提交

format的注释部分截取
 /**
     * 数据格式，[文档](http://json-schema.org/latest/json-schema-validation.html#rfc.section.7.3)
     * - `date-time` 日期时间，渲染为 `date`，[RFC3339](https://tools.ietf.org/html/rfc3339#section-5.6)
     * - `date`、`full-date` 日期，渲染为 `date`
     * - `time`、`full-time` 时间，渲染为 `time`
     * - 非标准：`week`，渲染为 `nz-week-picker`
     * - 非标准：`month`，渲染为 `nz-month-picker`
     */

### What is expected?
format:"month"支持被require校验

### What is actually happening?
require 校验对 format:"month" 无效

| Environment | Info |
|---|---|
| ng-alain | 12.2.1 |
| Browser | google 92.0.4515.131 |

**Comment by cipchk** [comment]
@wyq-L 麻烦提供完整的重现步骤 ，我无法重现。

**Comment by wyq-L** [comment]
### Reproduction link

https://stackblitz.com/edit/ng-alain-setup-kd3v5f

### Steps to reproduce

``` schema = {
properties: {
    month: {
        type: 'string',
        format: 'month'
    }
},
required: ['month']
};

对于format:'month' required无法校验 可以直接提交

**Comment by cipchk** [comment]
从 Ajv 7.x 新增 [strict](https://ajv.js.org/options.html#strict-mode-options) 模式，并且默认为 `true`，当最基本的 `required` 都无法正确校验时，那大概率就是因为 Schema 包含了不符合 Json Schema 格式的信息，可以通过 `debug` 模式验证这一点：

```ts
schema: SFSchema = {
  properties: {
    month: {
      type: 'string',
      format: 'month'
    }
  },
  required: ['month'],
  ui: { debug: true }
};
```

由于这里的 `format: 'month'` 并不是 Json Schema 标准，因此，你可以在 Console 面板得到错误：

```
Error: unknown format "month" ignored in schema at path "#/properties/month"
```

解决这一问题，只能通过全局配置设置 `strict` 为 `false`：

```ts
// src/app/global-config.module.ts
const alainConfig: AlainConfig = {
  sf: {
    ajv: { strict: false }
  }
};
```
