### ISSUE TITLE
widget: 'string'，format：mobile手机号（198*开头）报格式不正确

### ISSUE THREAD

**Issue by 694551594** [ng-alain/ng-alain#2078]
### Reproduction link
[https://github.com/ng-alain](https://github.com/ng-alain)

### Steps to reproduce
1、string小部件设置format:mobile。输入198开头的手机号报告格式不正确，应该是正则表达式没有包含198开头的手机号

### What is expected?
198开头的手机号格式正确

### What is actually happening?
198开头的手机号格式 不正确

| Environment | Info |
|---|---|
| ng-alain | 11.10.2 |
| Browser | chrome |

**Comment by cipchk** [comment]
低版本建议使用  `GlobalConfig` 配置 `sf.ajv.formats.mobile` 作为临时解决方案。
