### ISSUE TITLE
 simple-table simpleTableConfig pi

### ISSUE THREAD

**Issue by liweitao92** [ng-alain/ng-alain#208]
## Bug Report or Feature Request (mark with an `x`)
<pre><code>
[x] Bug report -> please search issues before submitting
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior
全局 设置 pi 无效

## Minimal reproduction of the problem with instructions
![image](https://user-images.githubusercontent.com/30191996/34865479-de873174-f7b3-11e7-8188-0be0d4d56f8d.png)
![image](https://user-images.githubusercontent.com/30191996/34865485-e4fb5abc-f7b3-11e7-9021-2524f1b91484.png)
谢谢你之前纠正我的问题，按照你之前的方式，发现还是有这个问题
## Environment

<pre><code>
Angular version: 5.0.0
delon version: 0.6.0-rc.2
Browser:
- [x ] Chrome (desktop) version  63.0.3239.132
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX

For Tooling issues:
- Node version: v8.2.1
- Platform:  Mac

Others:

</code></pre>

**Comment by cipchk** [comment]
抱歉，我无法重现你的问题，你看是否缺少调用 `DelonModule.forRoot()`

**Comment by liweitao92** [comment]
@cipchk https://stackblitz.com/edit/ng-alain-setup-ymty6d?file=app/app.component.ts
这个是我的例子，可以观察到
![image](https://user-images.githubusercontent.com/30191996/34923954-458395c4-f9db-11e7-8b9b-9ad49794e4f6.png)
ps 的值可以根据我的设置更改，然而 pi 的值并不会发生变化

**Comment by cipchk** [comment]
这个问题恐怕没有办法处理，因为 `nz-table` 并不支持从 `0` 开始的页码。
因此，即使 `simaple-table` 支持也是无意义。
