### ISSUE TITLE
使用reuse-tab，可以打开max+1个页签，点击已打开的第max页签时，会自动关闭其他页签

### ISSUE THREAD

**Issue by gassyou** [ng-alain/ng-alain#2080]
### Reproduction link
[https://stackblitz.com/edit/github-rbsmuf?file=src%2Fmain.ts](https://stackblitz.com/edit/github-rbsmuf?file=src%2Fmain.ts)

### Steps to reproduce
1. reuse-tab 的max属性设置成5。
2. 打开6个页签。
3. 在reuse-tab上， 点击第5个页签时，其他页签被关闭

### What is expected?
按照理解，如果max=5，能打开的页签应该只有5个。
而且，点击已经显示的页签，不会关闭其他页签。

### What is actually happening?
点击页签时，会关闭其他页签

| Environment | Info |
|---|---|
| ng-alain | 12.2.1 |
| Browser | chrome |

---
 stackblitz 上如果不能直接启动，代码可以参考如下地址：其实就是在 ng-alain脚手架基础上开放了reuse-tab功能后，建了6个菜单。
https://github.com/gassyou/reuse-tab-test

**Comment by gassyou** [comment]
![image](https://user-images.githubusercontent.com/2518449/131794895-a49f3be0-0dd9-4a9f-a36c-8744e1715cd6.png)
点击上图第5个页签后，变成了如下状态。
![image](https://user-images.githubusercontent.com/2518449/131794980-40606472-5fe3-4cf4-8ca0-f3b9aac34205.png)

**Comment by cipchk** [comment]
这是因为路由复用的点在离开路由时，而为了确保体验始终会有一个当前页面的标签（不管是否需要复用），这也就会变成当你从最后一个标签转移到已复用标签时，才会移除超出的标签，从而感觉上有点奇怪，但这已经是目前我认为能最好的呈现方式了。

**Comment by gassyou** [comment]
了解了。谢谢解答。
