### ISSUE TITLE
Mac Safari i18n载入语言包失败。

### ISSUE THREAD

**Issue by xingkoo** [ng-alain/ng-alain#2082]
### Steps to reproduce
`i18n.service.ts`中修复之前大小写敏感导致的异常[https://github.com/ng-alain/ng-alain/issues/2068](https://github.com/ng-alain/ng-alain/issues/2068)后，语言配置文件默认改为会小写。如下
```typescript
const DEFAULT = 'zh-cn';
const LANGS: { [key: string]: LangConfigData } = {
  'zh-cn': {
    text: '简体中文',
    ng: ngZh,
    zorro: zorroZhCN,
    date: dfZhCn,
    delon: delonZhCn,
    abbr: '🇨🇳'
  },
  'zh-tw': {
    text: '繁体中文',
    ng: ngZhTw,
    zorro: zorroZhTW,
    date: dfZhTw,
    delon: delonZhTw,
    abbr: '🇭🇰'
  },
  'en-us': {
    text: 'English',
    ng: ngEn,
    zorro: zorroEnUS,
    date: dfEn,
    delon: delonEnUS,
    abbr: '🇬🇧'
  }
};
```
应用初始化时，执行如下代码载入语言包
```typescript
    const defaultLang = this.i18n.defaultLang;
    return zip(this.i18n.loadLangData(defaultLang),this.httpClient.get('')).pipe(
    );
```

当使用mac safari时，```defaultLang==='zh-cn'```，
而`src/assets/tmp/i18n/zh-CN.json`中，大小写再次出现异常。

### What is expected?
载入语言包

### What is actually happening?
载入语言包出错

| Environment | Info |
|---|---|
| ng-alain | 12.2.1 |
| Browser | macos safari |

**Comment by xingkoo** [comment]
我修改了`i18n.service.ts`来临时解决该问题。
```
  loadLangData(lang: string): Observable<NzSafeAny> {
    const l = LANGS[lang] ? LANGS[lang].delon.abbr : lang;
    return this.http.get(`assets/${environment.id}/i18n/${l}.json`);
  }
```

**Comment by cipchk** [comment]
文件名应该不受影响吧~

**Comment by xingkoo** [comment]
chrome获取到的语言为`zh-CN`，而safari获取到的则是`zh-cn`（也有可能没有safari没有获取到，直接取了默认值得到的zh-cn）。

所以载入文件的时候，后面一种情况就会去载入 `zh-cn.json` ，但是实际文件是 `zh-CN.json`。就会导致错误了。

**Comment by cipchk** [comment]
这应该是 WebKit 的 BUG 引起的见 [#163096](https://bugs.webkit.org/show_bug.cgi?id=163096)，并且应该会在最期会修复它，不过我觉得还是有必须做一些修正，并且保持 RFC 5646 的标准。
