### ISSUE TITLE
表格组件使用排序功能时，拖拽改变列宽的handle位置需要优化。

### ISSUE THREAD

**Issue by xingkoo** [ng-alain/ng-alain#2083]
### Reproduction link
https://ng-alain.com/components/st/zh?#components-st-resizable

### Steps to reproduce
官网Demo同样如此。
拖拽列宽的Handle和列表名称在一个span中，排序在另一个span中，导致Handle不能紧贴旁边的列，容易产生误操作。

下图中拖拽Handle和表名在同一个span中，右侧是显示Sort的span
![截屏2021-09-07 上午12 52 25](https://user-images.githubusercontent.com/2936579/132246647-037e67d8-49dd-4358-85f7-2c98fa4646e0.png)
下图中颜色部门为拖拽Handle的位置。
![截屏2021-09-07 上午12 53 08](https://user-images.githubusercontent.com/2936579/132246718-e1b56d2f-03f6-4ab3-8724-4a9955e210c5.png)

### What is expected?
移动Handle到边缘，以减少误操作。
如果可以，竖线的颜色是不是可以再深一点？目前不容易看出来这条竖线。

### What is actually happening?
应在在当前列表的最边缘，而非中间位置。

| Environment | Info |
|---|---|
| ng-alain | 12.2.1 |
| Browser | chrome |

**Comment by cipchk** [comment]
目前 `nz-table` 所提供的方式中，几乎没办法改变 DOM 结构，这也导致这类问题，这算是已知问题，恐怕要改过只能等待 `nz-table` 内置拖拽能力了。
