### ISSUE TITLE
建议为动态表单新增标签页布局功能

### ISSUE THREAD

**Issue by lyuan520** [ng-alain/ng-alain#2085]
## What problem does this feature solve?
经常遇到表单过大， 一版显示会眼花缭乱， 如果使用标签页划分， 则查看起来就会清晰很多

## What does the proposed API look like?
{
      tabs:[
                  {
                        title:'基本信息' , 
                        properties:{ 
                        },
                  },
                  {
                        title:'附加信息' , 
                        properties:{ 
                        },
                  }
            ]
}

**Comment by cipchk** [comment]
首先 `sf` 应该考虑的是数据结构，而非 UI 层面结构，认识这一点非常重要。

目前并没有分组的概念，不过有一种办法可以实现，那便是重新定义一个新的 `object` 小部件，但最终你依然需要在提前数据前做一些数据转化。

**Comment by xingkoo** [comment]
能否考虑使用什么方式让用户可以分享自己创建的一些小组件。

**Comment by cipchk** [comment]
我在讨论组上新增一个SF Widgets 技巧分享的专属模块：https://github.com/ng-alain/ng-alain/discussions/categories/sf-widgets
