### ISSUE TITLE
reuse-tab 打开新标签页的方式建议变更为在当前tab页后打开（类似chrome的tab页签跟随方式）

### ISSUE THREAD

**Issue by emondora** [ng-alain/ng-alain#2092]
## What problem does this feature solve?
当tab页签开得比较多的时候，新打开的tab页签都去到了最后，非常不方便切换。

## What does the proposed API look like?
建议tab页签直接跟随在当前激活的tab页后面打开，可参考chrome浏览器打开页签的方式。

**Comment by cipchk** [comment]
看起来一切表现正常，gif:

![demo](https://user-images.githubusercontent.com/2987467/132628514-89771aa7-96f9-4ea9-b275-7069e6e751fc.gif)
