### ISSUE TITLE
动态表单的数字输入框单位动态更新的Bug

### ISSUE THREAD

**Issue by xingkoo** [ng-alain/ng-alain#2096]
### Reproduction link
[https://stackblitz.com/edit/ng-alain-setup-8jpnqs?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/edit/ng-alain-setup-8jpnqs?file=src%2Fapp%2Fapp.component.ts)

### Steps to reproduce
年龄单位默认为“岁”，三个按键分别可以设置为a,b,c为年龄的单位。

第一个按键，直接使用 `widget.reset()` 方法，执行后，需要更新数字才可以变更单位。
第二个按键，同上，不同的是，先reset为空值，再reset恢复值。
第三个可以修改成功，通过移除再重新恢复值的方式。

### What is expected?
可以简单的更新单位。

### What is actually happening?
需要自行修改很多代码才可以实现动态修改数字输入框的单位。

| Environment | Info |
|---|---|
| ng-alain | 12.2.2 |
| Browser | chrome |

**Comment by cipchk** [comment]
这个问题事实上，只能追溯为 Anguar 变更检测机制的问题，由于相同值的情况下 `ngModel` 并不会发现变更，也就导致 `nzFormatter`、`nzParser` 无法触发的根本原因，这也就是为什么只有 `c` 的情况下才会发生变更，事实上这只针对 `unit` 的情况下会这样。
