### ISSUE TITLE
ng build --prod --aot 编译出来  vendor.js 太大

### ISSUE THREAD

**Issue by aboutyang** [ng-alain/ng-alain#21]
## Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
```

### Mention any other details that might be useful.

ng-alain 使用 ng build --prod --aot 编译出来的 js 还是有3M+。

是因为使用了 ng-zorro-antd ？ 

![ng-alain](https://user-images.githubusercontent.com/303348/30841230-ff2c3cfe-a2ad-11e7-9a9c-0a0cd08cdff9.png)

**Comment by cipchk** [comment]
有很多第三方类库，你可以去掉他们。
