### ISSUE TITLE
default.interceptor.ts拦截器跳转gologin问题

### ISSUE THREAD

**Issue by ada-hou** [ng-alain/ng-alain#211]
我的认证没有采用token，使用ajax的方式去后台去数据然后判断
![image](https://user-images.githubusercontent.com/18135689/34872829-8b08d4f2-f7cd-11e7-948f-ad1a89708423.png)
以前的版本可以raise一个错误被后面的catch捕获到，新版的如何raise一个错误
![image](https://user-images.githubusercontent.com/18135689/34872922-e3f7e710-f7cd-11e7-8f38-a67dccb50cf1.png)
我这样写后台报错

**Comment by cipchk** [comment]
目前好像无法通过 `_throw` 正确的捕获，因此，最新的是按以下规则：

- 业务级错误，依然以正确的形式，即 `of()` 抛出，内容使用一种 `{ status:0 } ` 的形式用于表示成功与否
- HTTP 级错误，则按不同状态码为准：
    - 未授权转路由
    - 无法请求，使用对话框提醒
