### ISSUE TITLE
ST 內 STColumn 的 SORT 無法排序字符串

### ISSUE THREAD

**Issue by YuTingKung** [ng-alain/ng-alain#2111]
## What problem does this feature solve?
排序

## What does the proposed API look like?
類似 sort: {  compare: (a, b) => a.age - b.age } 並能排序字符串，例如 a1、a2、a3、b1、b2、c1

**Comment by cipchk** [comment]
这属于es6范围，如果需要字符串排序，可以尝试：

```ts
sort((a, b) => a.name.localeCompare(b.name))
```
