### ISSUE TITLE
面包屑导航和标签页位置交换

### ISSUE THREAD

**Issue by wxq851685279** [ng-alain/ng-alain#2117]
## What problem does this feature solve?
可以把面包屑导航放到标签页上面么，没有找到这样的api
![image](https://user-images.githubusercontent.com/29041799/138704009-e0fc2663-00ba-46b9-b06b-b2f004a1197f.png)

## What does the proposed API look like?
 <reuse-tab #reuseTab> </reuse-tab> 可以在此标签上添加参数，实现该功能吗

**Comment by cipchk** [comment]
不建议这样子，每个页面有自己的标题、操作区等，如果允许对调就变得主、次不分。

**Comment by wxq851685279** [comment]
> 不建议这样子，每个页面有自己的标题、操作区等，如果允许对调就变得主、次不分。

但是我们想这样用，可以自定义实现吗，我们觉着这个导航应该是全局的，看过很多其他的ui组件都是全局的
![image](https://user-images.githubusercontent.com/29041799/138980799-b3f30b19-1637-48ff-b3b4-f06407aca7c2.png)
