### ISSUE TITLE
SF组件TextWidget增加HTML支持功能

### ISSUE THREAD

**Issue by xingkoo** [ng-alain/ng-alain#2118]
## What problem does this feature solve?
在一些复杂的场景，动态运算后，需要显示一些信息到页面上。
最佳体验是在相关属性下方，使用text输出。
当前Widget仅支持原样显示。如需显示HTML，需要再做处理。

虽然很简单，但实在不知道如何自己写好提交上去，只能麻烦作者了。抱歉抱歉

## What does the proposed API look like?
可以支持HTML显示。

**Comment by xingkoo** [comment]
想尝试自己处理一下，提现无权限。大佬有没有想关的代码贡献说明文档可以给参考一下的？

```
$ git push origin remotes/origin/issues-2118                                                                                                                                                                                                                                                                              [0]
Username for 'https://github.com': xxx@gmail.com
Password for 'https://xxx@gmail.com@github.com':
remote: Permission to ng-alain/delon.git denied to xxx.
fatal: unable to access 'https://github.com/ng-alain/delon.git/': The requested URL returned error: 403
```

**Comment by cipchk** [comment]
可以尝试每日构建版本：https://github.com/ng-alain/delon/blob/issues-2118/docs/faq.zh-CN.md#%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8delon%E6%AF%8F%E6%97%A5%E6%9E%84%E5%BB%BA%E7%89%88%E6%9C%AC
