### ISSUE TITLE
How to remove the sidebar entirely? (eom)

### ISSUE THREAD

**Issue by agiledigits** [ng-alain/ng-alain#213]
## Bug Report or Feature Request (mark with an `x`)
<pre><code>
[ ] Bug report -> please search issues before submitting
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Environment

<pre><code>
Angular version: X.Y.Z

delon version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX

For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by cipchk** [comment]
`clear()` `add()` methods.

**Comment by agiledigits** [comment]
Sorry but I'm not sure what you meant. I found only the clear() and add() methods for the menu service, but how about the sidebar itself? I don't even want the collapsed sidebar. It seems that clear() will still leave an empty sidebar.

<img width="220" alt="screenshot" src="https://user-images.githubusercontent.com/1360728/34904111-91b3cd86-f7f3-11e7-9a74-62495d305034.png">

**Comment by cipchk** [comment]
Please provider a online demo via https://stackblitz.com/edit/ng-alain-setup

**Comment by agiledigits** [comment]
It's too much code to demo, but the issue is simple: on the header I can click on a button to expand/collapse the sidebar; and I can set the initial sidebar state to "collapsed" by doing so in HeaderComponent's constructor like this:

`@Component({
    selector: 'app-header',
    templateUrl: './header.component.html'
})
export class HeaderComponent {
    searchToggleStatus: boolean;

    constructor(public settings: SettingsService) { }

    toggleCollapsedSideabar() {
        this.settings.setLayout('collapsed', !this.settings.layout.collapsed);
    }
}`

The question is, though: is there a way to specify that the layout should not have the sidebar (but still has the header, etc, like the screenshot shown above)?

**Comment by cipchk** [comment]
you can trying follow add styles in `src/styles/index.less`:

```less
.aside-collapsed {
    .aside { display: none; }
}

```

**Comment by agiledigits** [comment]
It doesn't quite work -- the sidebar is now empty but still occupies the original space.

**Comment by cipchk** [comment]
You can still using styles fix this, find the releated class name via elements panel in chorem.
