### ISSUE TITLE
新版本 release 不能跑

### ISSUE THREAD

**Issue by jiankian** [ng-alain/ng-alain#214]
<img width="570" alt="qq20180115-080852 2x" src="https://user-images.githubusercontent.com/9036838/34922485-764928c8-f9cb-11e7-87b8-ba2928677cee.png">

**Comment by jecyhw** [comment]
我的也是这个错误。angular-cli版本是：
Angular CLI: 1.6.4
Node: 8.9.1
OS: win32 x64
Angular: 5.2.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 5.0.4
@angular/cli: 1.6.4
@angular-devkit/build-optimizer: 0.0.38
@angular-devkit/core: 0.0.25
@angular-devkit/schematics: 0.0.48
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.4
@schematics/angular: 0.1.13
@schematics/schematics: 0.0.13
typescript: 2.6.2
webpack-bundle-analyzer: 2.9.2
webpack: 3.10.0

**Comment by jecyhw** [comment]
angular-cli安装1.6.3版本就行了，npm install @angular/cli@1.6.3

**Comment by WOOOFEI** [comment]
https://github.com/cipchk/ng-alain/pull/206/files

**Comment by WOOOFEI** [comment]
https://github.com/cipchk/ng-alain/issues/205

**Comment by jecyhw** [comment]
angular-cli安装1.6.3版本就行了，npm install angular-cli@1.6.3

**Comment by cipchk** [comment]
duplicated of #205

**Comment by jiankian** [comment]
升级最新版 1.6.4  cli也不能跑。

**Comment by cipchk** [comment]
`1.6.4` 依然还有问题，可以退回 `1.6.2`

**Comment by jiankian** [comment]
很奇怪，我安装1.6.4，1.6.3，1.6.2都失败。都是清空node_modules文件夹重新yarn的

**Comment by cipchk** [comment]
package-lock.json
