### ISSUE TITLE
窗口变小中有一段content缩进去了，但是侧边栏没被隐藏

### ISSUE THREAD

**Issue by jecyhw** [ng-alain/ng-alain#215]
![image](https://user-images.githubusercontent.com/10094084/34925202-cf50b7da-f9e2-11e7-8748-fd67861db7bb.png)

**Comment by alaahong** [comment]
![image](https://user-images.githubusercontent.com/3264250/34970783-460e0c78-fab1-11e7-9138-31ab3e0d0111.png)

FullScreen init, show correctly, then minimalize the sizing of screen, content display incorrectly too.
