### ISSUE TITLE
启动时报错 0.6 git master

### ISSUE THREAD

**Issue by mahuwei** [ng-alain/ng-alain#216]
<pre><code>
chunk {widgets.module} widgets.module.chunk.js () 125 kB  [rendered]

ERROR in ./node_modules/css-loader?{"sourceMap":false,"import":false}!./node_modules/postcss-loader/lib?{"ident":"postcss","sourceMap":false}!./node_modules/less-loader/dist/cjs.js?{"sourceMap":false}!./src/styles.less
Module not found: Error: Can't resolve '../font/weathericons-regular-webfont.eot' in 'D:\gitHub\ng-alain\src'
resolve '../font/weathericons-regular-webfont.eot' in 'D:\gitHub\ng-alain\src'
  using description file: D:\gitHub\ng-alain\package.json (relative path: ./src)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: D:\gitHub\ng-alain\package.json (relative path: ./src)
    using description file: D:\gitHub\ng-alain\package.json (relative path: ./font/weathericons-regular-webfont.eot)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        D:\gitHub\ng-alain\font\weathericons-regular-webfont.eot doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        D:\gitHub\ng-alain\font\weathericons-regular-webfont.eot.ts doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        D:\gitHub\ng-alain\font\weathericons-regular-webfont.eot.js doesn't exist
      as directory
        D:\gitHub\ng-alain\font\weathericons-regular-webfont.eot doesn't exist
[D:\gitHub\ng-alain\font\weathericons-regular-webfont.eot]
[D:\gitHub\ng-alain\font\weathericons-regular-webfont.eot.ts]
[D:\gitHub\ng-alain\font\weathericons-regular-webfont.eot.js]
[D:\gitHub\ng-alain\font\weathericons-regular-webfont.eot]
 @ ./node_modules/css-loader?{"sourceMap":false,"import":false}!./node_modules/postcss-loader/lib?{"ident":"postcss","sourceMap":false}!./node_modules/less-loader/dist/cjs.js?{"sourceMap":false}!./src/styles.less 7:57469-57520 7:57551-57602
 @ ./src/styles.less
 @ multi ./src/styles.less
ERROR in ./node_modules/css-loader?{"sourceMap":false,"import":false}!./node_modules/postcss-loader/lib?{"ident":"postcss","sourceMap":false}!./node_modules/less-loader/dist/cjs.js?{"sourceMap":false}!./src/styles.less
Module not found: Error: Can't resolve '../font/weathericons-regular-webfont.svg' in 'D:\gitHub\ng-alain\src'
resolve '../font/weathericons-regular-webfont.svg' in 'D:\gitHub\ng-alain\src'
  using description file: D:\gitHub\ng-alain\package.json (relative path: ./src)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: D:\gitHub\ng-alain\package.json (relative path: ./src)
    using description file: D:\gitHub\ng-alain\package.json (relative path: ./font/weathericons-regular-webfont.svg)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        D:\gitHub\ng-alain\font\weathericons-regular-webfont.svg doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        D:\gitHub\ng-alain\font\weathericons-regular-webfont.svg.ts doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        D:\gitHub\ng-alain\font\weathericons-regular-webfont.svg.js doesn't exist
      as directory
        D:\gitHub\ng-alain\font\weathericons-regular-webfont.svg doesn't exist
[D:\gitHub\ng-alain\font\weathericons-regular-webfont.svg]
[D:\gitHub\ng-alain\font\weathericons-regular-webfont.svg.ts]
[D:\gitHub\ng-alain\font\weathericons-regular-webfont.svg.js]
[D:\gitHub\ng-alain\font\weathericons-regular-webfont.svg]
 @ ./node_modules/css-loader?{"sourceMap":false,"import":false}!./node_modules/postcss-loader/lib?{"ident":"postcss","sourceMap":false}!./node_modules/less-loader/dist/cjs.js?{"sourceMap":false}!./src/styles.less 7:57843-57894
 @ ./src/styles.less
 @ multi ./src/styles.less
ERROR in ./node_modules/css-loader?{"sourceMap":false,"import":false}!./node_modules/postcss-loader/lib?{"ident":"postcss","sourceMap":false}!./node_modules/less-loader/dist/cjs.js?{"sourceMap":false}!./src/styles.less
Module not found: Error: Can't resolve '../font/weathericons-regular-webfont.ttf' in 'D:\gitHub\ng-alain\src'
resolve '../font/weathericons-regular-webfont.ttf' in 'D:\gitHub\ng-alain\src'
  using description file: D:\gitHub\ng-alain\package.json (relative path: ./src)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: D:\gitHub\ng-alain\package.json (relative path: ./src)
    using description file: D:\gitHub\ng-alain\package.json (relative path: ./font/weathericons-regular-webfont.ttf)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        D:\gitHub\ng-alain\font\weathericons-regular-webfont.ttf doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        D:\gitHub\ng-alain\font\weathericons-regular-webfont.ttf.ts doesn't exist
      .js...
</code></pre>
怎么处理？

**Comment by cipchk** [comment]
#205

**Comment by mahuwei** [comment]
谢谢。
