### ISSUE TITLE
The pipe 'translate' could not be found using @delon/cli

### ISSUE THREAD

**Issue by maplye** [ng-alain/ng-alain#217]
## Bug Report or Feature Request (mark with an `x`)
<pre><code>
[*] Bug report -> please search issues before submitting
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Environment

<pre><code>
Angular version: X.Y.Z

delon version: 0.6.0

Browser:
- [*] Chrome (desktop) version 63.0.3239.132
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX

For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

Uncaught Error: Template parse errors:
The pipe 'translate' could not be found ("  </div>
        <ul nz-menu>
            <li nz-menu-item (click)="msgSrv.success('profile')">{{ [ERROR ->]'profile' | translate }}</li>
            <li nz-menu-item (click)="msgSrv.success('settings')">{{ '"): ng:///LayoutModule/SidebarComponent.html@10:68
The pipe 'translate' could not be found ("'profile' | translate }}</li>
            <li nz-menu-item (click)="msgSrv.success('settings')">{{ [ERROR ->]'settings' | translate }}</li>
            <li nz-menu-item (click)="msgSrv.success('logout')">{{ 'l"): ng:///LayoutModule/SidebarComponent.html@11:69
The pipe 'translate' could not be found (" 'settings' | translate }}</li>
            <li nz-menu-item (click)="msgSrv.success('logout')">{{ [ERROR ->]'logout' | translate }}</li>
        </ul>
    </nz-dropdown>
"): ng:///LayoutModule/SidebarComponent.html@12:67
    at syntaxError (compiler.js:485)
    at TemplateParser.parse (compiler.js:24661)
    at JitCompiler._parseTemplate (compiler.js:34601)
    at JitCompiler._compileTemplate (compiler.js:34576)
    at eval (compiler.js:34477)
    at Set.forEach (<anonymous>)
    at JitCompiler._compileComponents (compiler.js:34477)
    at eval (compiler.js:34347)
    at Object.then (compiler.js:474)
    at JitCompiler._compileModuleAndComponents (compiler.js:34346)

**Comment by niubianli** [comment]
+1

**Comment by niubianli** [comment]
+1

**Comment by cipchk** [comment]
暂时解决办法：手动移除 ` | translate` 它们。我会在下一版本修复它。

**Comment by niubianli** [comment]
国际化可以先丢弃了，
