### ISSUE TITLE
About loadChildren

### ISSUE THREAD

**Issue by yunClouds** [ng-alain/ng-alain#22]
@cipchk 
First of  all , Ths  for share this.
我克隆你的代码到本地 执行ng serve 启动app，但是点击左侧菜单请切换目录时无法切换一直在加载中，特别是涉及loadChildren的菜单。
在你的在线例子中也偶有出现，请教不知道这个问题需要怎么处理？
附;我用的浏览器是 chrome 61.0.****版本

**Comment by yunClouds** [comment]
补充：在线例子首次切换loadchildrern路由时加载慢，应该是在加载文件（虽然慢但等待会还是可以加载出来），但我下载到本地ng serve命令运行起来的无法加载出来，直到把浏览器拖死（有查看cpu占用率，此问题导致chrome占用突曾）

**Comment by cipchk** [comment]
`loadChildren` 首次加载时，会下载js脚本，这个过程需要时间，所以顶部会出现一个彩虹进度条。

至于关于浏览器（同你的版本一样）假死的问题，我没遇到过，是否可以打开 network 查看一下js脚本加载的过程？

**Comment by yunClouds** [comment]
你好 @cipchk 
 查看network是有去下载一个新的script文件，对比了和你的在线例子也是下载一个新的script文件（文件名不一样而已，但应该是正常的，因为打包环境不同），下载状态都是是200，不同的是我本地环境下载完就停在那儿了，没有继续响应了...
另外，发现点击那些loadchildrern的菜单时去下载的文件名都 是 你在路由中定义的前缀 加 chunk.js(不知道这对发现解决问题是否有帮助...)， 如tables菜单 你在路由（routes）中定义的是 
{ path: 'tables', loadChildren: './tables/tables.module#TablesModule' }, 点击菜单下载的文件是  tables.module.chunk.js  
这是什么情况呢？

**Comment by cipchk** [comment]
文件名是对的，这是angular-cli 决定的。

没有继续响应，这个……无奈了

**Comment by cipchk** [comment]
我先关掉，若有更多细节请重新提issues。
