### ISSUE TITLE
ng-tree-antd expand and close the node speed super slow.

### ISSUE THREAD

**Issue by lyc152** [ng-alain/ng-alain#223]
Browser:
- [x] Chrome (desktop) version XX
- [x] Firefox version XX
- [x] Safari (desktop) version XX
- [x] IE version XX

当总数据量在500个左右时，展开2级节点会非常缓慢，是不是设置了什么缓动啊，可以放开吗，体验比较差

**Comment by cipchk** [comment]
性能取决于 angular-tree-component，不过 500 应该是小量级，目前我也没有相应的解决办法。或者你可以做一个 stackblitz 重现示例，看能否一起解决这个问题。

**Comment by lyc152** [comment]
我做了个示例： https://stackblitz.com/edit/ng-tree-antd-udi95g?file=app%2Fapp.component.ts
在 window 上面尤其差，在mac上面好点，感觉是不是展开和收起的时候加了timeout 啊

**Comment by lyc152** [comment]
有什么好的联系方式吗，比如qq 微信什么的，这个github 上沟通比较慢

**Comment by cipchk** [comment]
qq group: 316911865

**Comment by lyc152** [comment]
加上 [nzOptions]="{'animateExpand': false, animateSpeed: 0}" 速度提升很多，多谢，
建议开放
```
options = {
  useVirtualScroll: true,
  nodeHeight: 22
}

// Or using a function
options = {
  useVirtualScroll: true,
  nodeHeight: (node: TreeNode) => node.myHeight,
  dropSlotHeight: 3
}

```

**Comment by vellengs** [comment]
树形动画确实不理想。

**Comment by cipchk** [comment]
0.7.0 已经包含了 nz-tree
