### ISSUE TITLE
feat(http): new @delon/http lib. 关于HTTP使用方式的设想

### ISSUE THREAD

**Issue by cipchk** [ng-alain/ng-alain#227]
我们花费大部分时间在开发中台过程中重复着使用类似以下HTTP请求代码：

```ts
constructor(private http: _HttpClient) {}

ngOnInit() {
    this.http.get('/users').subscribe((res: any) => {
        // doing
    });
}
```

我一直在寻找一种更优雅、更高效的解决办法，前端应该与后端或前端中间层形成一种约定，例如：标准化RESTful、统一Response格式。

我们再把角度从开发者去思考这一问题时，会产生两个侧重点：

- 标准化
- 模型定义

## 标准化

倘若我们能够严格要求 RESTful 标准去构建资源的话，一个用户资源应该包括：

- `GET /users` 用户列表
- `GET /users/1` 获取用户详情
- `POST /users` 新增用户
- `PATCH /users/1` 修改用户
- `DELETE /users/1` 删除用户

与此同时，我们应该使用状态码来保证资源有效性，例如：

- `401` 没有权限
- `403` 没有授权
- `404` 无效请求
- `500` 服务器出错

最后，还要采用一种标准的输出格式，例如：

- 错误：`{ status: 1, message: '无效用户编号' }`
- 正确：`{ status: 0, data: [] }`

## 模型定义

我想对于大部分企业来说，都不会是后端主动妥协前端，或者说这两件事前都你自己来做的情况下，也很难保证总是想着前端数据应该是如何，因为我们总是有惰性。

倘若前后端真的分离，而后端特别是分布式应用的数据源很难去为了某个中台单独创建一些URI资源给你用；因此为了降低各种变化、渲染复杂度等问题，很多企业开始将前端的变成前端+中间层，使用中间层将后端数据进一步处理，使URI资源是干净的、有效的。

> GraphQL 也是为了解决这一问题存在的；只是理想很丰满现实很骨感。

假如说我们解决上述问题或部分问题，那对于 Angular 端是否有更进一步简化呢？

**获取**

前如所述，在获取一个模型以最简的方式大概需要这样：

```ts
this.http.get('/users').subscribe((res: any) => {});
```

然而，这种方式能否更进一步呢？TypeScript 提供一种叫装饰器的东西，它目标是为了修饰类、方法或成员，倘若我们进一步优化，那么相同一个功能，是不是只应该关心模型的获取呢？例如：

```ts
export interface User {
    id?: number;
}
```

```ts
@GET('/users')
getData(res: User) {
    this.list = res.map(item => item);
}
```

或者能不能更进一步呢？

```ts
@GET('/users', this.args)
list: User[] = [];
```

**创建**

在Angular中，若我们能统一使用响应式表单，我们把创建模型数据交由 Angular 来完成，模型创建不应该再关心表单对象的操作，例如一个响应式表单一般会这写：

```ts
form: FormGroup;
_submitForm() {
  for (const i in this.form.controls) {
    this.form.controls[ i ].markAsDirty();
  }
  if (this.form.invalid) return ;
  // POST DATA
  this.http.get('/users').subscribe((res: User) => this.msg.success('ok'));
}
```

为了保证模型数据的完整型，需要额外的 `for..in` 及 `invalid` 判断，我们是否能进一步优化，例如：

```ts
@SAVE('/users', this.form)
_submitForm(res: User) {
    this.msg.success('ok');
}
```

## 结论

ng-alain 一直秉承着 Angular 开发更简洁、更快速，`_HttpClient` 进一步优化会成为另一个独立的类库，例如：`@delon/http`。

欢迎进一步讨论！

**Comment by xingkoo** [comment]
我的数据返回就是jwt格式。所以在拦截器里面直接处理了。所有的问题都消息提醒，只有正常的时候才会把data数据给到下一步。意味着，只要我的代码中能接收到数据，他就是正确的。
因为大多数的情况下，错误只要提醒就可以。不要其他逻辑的。

**Comment by cipchk** [comment]
装饰器会在函数构建前进行初始化，关于 http 的可行性还在研究中。

**Comment by winpzs** [comment]
装饰器关系到类的定义，而它现在获取不了服务，如果NG本身支持就完美（可以去NG官方提建议）。

但可以很不友善的方式支持

**Comment by CoderPoet** [comment]
是不是类似这种的 https://github.com/troyanskiy/ngx-resource

**Comment by cipchk** [comment]
恩，但是希望可以更进一步，若是再造一个 ngx-resource 意义不大。

**Comment by laosandegudai** [comment]
一个http请求，返回的接口数据格式是固定的，如
{ 
  success: boolean;

    result?: any;

    targetUrl?: string;

    error?: IErrorInfo;

    unAuthorizedRequest: boolean; 
  }     ，在统一拦截的地方统一处理非业务性逻辑，我后台会把错误500处理成200返回，身份认证还是401等不变，拦截的地方处理异常情况，如提示错误或身份认证失败跳回登陆出，而业务调用的地方只用接收result部分即可，如何对返回的数据进行拦截处理后返回呢？

**Comment by cipchk** [comment]
尝试过，但是拦截器好像会抛异常，我没有进一步研究，但我想是应该的；有时间我会进一步研究。

**Comment by laosandegudai** [comment]
拦截器那我没尝试成功，我想作者应该可以实现的，目前我不得不在业务调用出多此一举的判断。
