### ISSUE TITLE
nz-tree删除节点会一直处于加载中的问题

### ISSUE THREAD

**Issue by xingcun** [ng-alain/ng-alain#230]
## Component
<pre><code>
export class AppComponent implements OnInit {
  nodes = [];
  ngOnInit() {
      this.nodes=[
			{
				"children":[
					{
						"disableCheckbox":false,
						"id":"22",
						"isGroup":true,
						"name":"aa",
						"pid":"21"
					}
				],
				"disableCheckbox":false,
				"id":"21",
				"isGroup":true,
				"name":"a"
			}];
  }
deleteTree() {
this.nodes=this.nodes=[
			{
				
				"disableCheckbox":false,
				"id":"21",
				"isGroup":true,
				"name":"a"
			}];
}
}

</code></pre>
## Html

    <nz-tree [nzNodes]="nodes">      
    </nz-tree>
    <button nz-button nzType='primary' (click)="deleteTree()">删除aa</button>
![image](https://user-images.githubusercontent.com/14237778/35023098-2ac660f0-fb74-11e7-9ea0-e369e0fadc9d.png)

![image](https://user-images.githubusercontent.com/14237778/35023032-deed2dc6-fb73-11e7-8459-dbb35b5f61bf.png)

当选中aa节点，点击删除按钮,即会出现一直加载中的问题

**Comment by cipchk** [comment]
这是 angular-tree-component 已知BUG，使用以下数据应该可以解决：

```ts
deleteTree() {
this.nodes=this.nodes=[
			{
				
				"disableCheckbox":false,
				"id":"21",
				"isGroup":true,
				"name":"a",
children: []
			}];
}
}
```
