### ISSUE TITLE
standard-form-row 组件右侧的“展开”可否隐藏？

### ISSUE THREAD

**Issue by dusdong** [ng-alain/ng-alain#231]
## Bug Report or Feature Request (mark with an `x`)

<pre><code>
[ ] Bug report -> please search issues before submitting
[x] Feature request
[ ] Documentation issue or request
</code></pre>

## Reproduction link

![tim 20180117144126](https://user-images.githubusercontent.com/3461709/35029142-82f851dc-fb94-11e7-92f7-200bbe966881.png)

**Comment by cipchk** [comment]
如果小数据量就没有办法使用 `tag-select`

**Comment by dusdong** [comment]
哦哦，原来是` tag-select` 的问题，加入  `[expandable]="false"` 就好了。

小数据量应该用哪个控件呢？
