### ISSUE TITLE
关于界面调整的建议

### ISSUE THREAD

**Issue by guccihuiyuan** [ng-alain/ng-alain#235]
当界面尺寸小于768的时候，可以自动收缩左边的菜单栏，不然感觉右边的界面会被挡住一部分

**Comment by cipchk** [comment]
请问是什么版本？

**Comment by xingkoo** [comment]
0.6.1有碰到这个问题。

**Comment by cipchk** [comment]
0.6.2 修复过一个中小屏没有同步的问题，但我不清楚是不是这一个。

**Comment by xingkoo** [comment]
后续我升级后再发现的话来反馈。

**Comment by mrshyi** [comment]
v0.6.3
1.左侧菜单展开（文字+图标情况）
2.拖动浏览器宽度<992
= 内容右侧显示不全，没有自适应。

**Comment by cipchk** [comment]
![tim 20180123113814](https://user-images.githubusercontent.com/2987467/35257021-ebb78ea8-0031-11e8-9799-a8dd7071cf48.png)

**Comment by mrshyi** [comment]
@cipchk 
**1.左侧菜单展开（文字+图标情况）**
![default](https://user-images.githubusercontent.com/5423305/35258568-5596f5e4-003b-11e8-98b1-ccc2f92fb509.PNG)

**Comment by cipchk** [comment]
在小屏幕中菜单展开后的显示并没有什么问题呀。我想这里可以更进一步，当切换路由时自动关闭侧边栏会更合理。

**Comment by cipchk** [comment]
fix 0.6.5
