### ISSUE TITLE
0.6.2从github上拉下来运行报错

### ISSUE THREAD

**Issue by guccihuiyuan** [ng-alain/ng-alain#237]
![image](https://user-images.githubusercontent.com/7911691/35128592-6cdceb06-fcf2-11e7-9d24-fd7266152758.png)

**Comment by ColdMoonMao** [comment]
[https://github.com/cipchk/ng-alain/issues/239](https://github.com/cipchk/ng-alain/issues/239)

> 此处有解决方法！
