### ISSUE TITLE
0.6.2 release下载的 运行不了

### ISSUE THREAD

**Issue by jiankian** [ng-alain/ng-alain#239]
<img width="570" alt="qq20180119-110545 2x" src="https://user-images.githubusercontent.com/9036838/35132975-d521fede-fd08-11e7-972c-40119e3d21cc.png">

**Comment by ColdMoonMao** [comment]
执行
`npm i @angular-devkit/core --save-dev`
该报错解决；

**Comment by Kiuyam** [comment]
楼上正解
