### ISSUE TITLE
reuse-tab problem

### ISSUE THREAD

**Issue by jecyhw** [ng-alain/ng-alain#240]
![image](https://user-images.githubusercontent.com/10094084/35139267-4a485dba-fd2d-11e7-9363-d4d034ef8d14.png)
![image](https://user-images.githubusercontent.com/10094084/35139277-55b188ca-fd2d-11e7-823b-5b5cef3b244f.png)
![image](https://user-images.githubusercontent.com/10094084/35139286-63169bae-fd2d-11e7-977c-c0ad5adbb9f5.png)
按照文档要求删除了reuse-tab相关的，但还是起作用了

**Comment by cipchk** [comment]
移除 `ReuseTabService` 的注册。

**Comment by jecyhw** [comment]
![image](https://user-images.githubusercontent.com/10094084/35143347-45779f9e-fd3c-11e7-93fa-5a14cd938c6d.png)
怎么移除，没找到ReuseTabService。

**Comment by cipchk** [comment]
把 delon.module 里面的 `AlainABCModule.forRoot()` 换成：

```ts
        AdErrorCollectModule.forRoot(), AdFooterToolbarModule.forRoot(), AdSidebarNavModule.forRoot(), AdDownFileModule.forRoot(), AdImageModule.forRoot(),
        AdAvatarListModule.forRoot(), AdDescListModule.forRoot(), AdEllipsisModule.forRoot(), AdExceptionModule.forRoot(), AdExceptionModule.forRoot(),
        AdNoticeIconModule.forRoot(), AdNumberInfoModule.forRoot(), AdProHeaderModule.forRoot(), AdResultModule.forRoot(), AdStandardFormRowModule.forRoot(),
        AdTagSelectModule.forRoot(), AdTrendModule.forRoot(), AdUtilsModule.forRoot(), AdChartsModule.forRoot(), AdCountDownModule.forRoot(), AdSimpleTableModule.forRoot(),
        AdReuseTabModule.forRoot(), AdFullContentModule.forRoot(), AdXlsxModule.forRoot(), AdZipModule.forRoot(),
```

然后剔除其中中的 `AdReuseTabModule.forRoot()`

**Comment by jecyhw** [comment]
嗯嗯，谢谢!
