### ISSUE TITLE
升级到0.6.2，用户登录后跳转 dashboard 页显示错乱

### ISSUE THREAD

**Issue by dusdong** [ng-alain/ng-alain#241]
## Bug Report or Feature Request (mark with an `x`)

<pre><code>
[x] Bug report -> please search issues before submitting
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

用户登录成功后，跳转到 dashboard 页面，代码为：
`this.router.navigate(['dashboard']);`
界面显示为：
![image](https://user-images.githubusercontent.com/3461709/35180958-a5ebf470-fdf4-11e7-9674-59237e611ae1.png)

按F5强制刷新后正常
![image](https://user-images.githubusercontent.com/3461709/35180989-c94cfde2-fdf4-11e7-9551-7ab9faf1eeb8.png)

代码相同，0.6.1不存在此问题

**Comment by cipchk** [comment]
duplcated of [#24](https://github.com/cipchk/delon/issues/24), i will next version fix this at night.
