### ISSUE TITLE
0.6.3 this.reuseTabService.title的方法出错

### ISSUE THREAD

**Issue by xiaoreign** [ng-alain/ng-alain#244]
ng-alain version: 0.6.3

this.reuseTabService.title = "" 修改tab标题名称的方法有些小问题

在当前的页面A下,打开新tab如有"this.reuseTabService.title"代码的情况下,新tab无法更新名称,再一次点击页面A的tab后,页面A的tab名称被修改

**Comment by xiaoreign** [comment]
新点击的页面使用此方法无法正确重命名
反而点击已存在的tab后  把重命名赋值给了已存在的页面tab上

**Comment by cipchk** [comment]
b. 若是bug，请填写复现步骤、在线演示（模板：https://stackblitz.com/edit/ng-alain-setup?file=app%2Fapp.component.ts）

**Comment by xiaoreign** [comment]
https://stackblitz.com/edit/ng-alain-setup-bozrsd

模板中 ReuseTabService 无法使用

**Comment by cipchk** [comment]
```
ERROR TypeError: Cannot read property 'active' of null
```

的确如此，我会在下一版本修复。
