### ISSUE TITLE
拦截器默认忽略的接口,不带token请求的问题

### ISSUE THREAD

**Issue by xiaoreign** [ng-alain/ng-alain#246]
请求的接口中只要带有'assets'就会忽略传递token吗?
今天请求的接口命名为'/xxxxxx/assets/yyyyyylist',其中带有'assets',没药传递token,我也没有在AlainAuthModule设置ignores这个参数

**Comment by cipchk** [comment]
应该是默认值引起的：https://github.com/cipchk/delon/blob/master/src/core/auth/auth.options.ts#L60

**Comment by xiaoreign** [comment]
我已经设置ignores 为空也不行,默认值无法修改吗?

**Comment by cipchk** [comment]
忽略TOKEN的URL地址列表，默认值为：`[ /\/login/, /assets\// ]`

**注：** 由于Angular的Bug（[#14187](https://github.com/angular/angular/issues/14187)），暂时只支持 `string[]` 格式正则表达式

**Comment by HJianfeng** [comment]
可以不要这个登录权限吗，因为我后端有自己的逻辑

**Comment by cipchk** [comment]
@HJianfeng 不明白你的意思，若非当前 话题，请重新提交新的，以免给其他人造成误解。

**Comment by winpzs** [comment]
可以添加一种途径处理这个ignores， 比如可以提供一个function来处理。(url:string) => boolean;
