### ISSUE TITLE
打包报错

### ISSUE THREAD

**Issue by qld-cf** [ng-alain/ng-alain#25]
vendor.8f0aeb983122b56bcd0a.bundle.js:1 Uncaught TypeError: Xe.Observable.throw is not a function
    at t.selector (main.95035915ababa27f2366.bundle.js:1)
    at t.error (vendor.8f0aeb983122b56bcd0a.bundle.js:1)
    at t.T14+.t._error (vendor.8f0aeb983122b56bcd0a.bundle.js:1)
    at t.T14+.t.error (vendor.8f0aeb983122b56bcd0a.bundle.js:1)
    at XMLHttpRequest.p (vendor.8f0aeb983122b56bcd0a.bundle.js:1)
    at t.invokeTask (polyfills.e4761bff8bd6a8151d1c.bundle.js:1)
    at Object.onInvokeTask (vendor.8f0aeb983122b56bcd0a.bundle.js:1)
    at t.invokeTask (polyfills.e4761bff8bd6a8151d1c.bundle.js:1)
    at r.runTask (polyfills.e4761bff8bd6a8151d1c.bundle.js:1)
    at e.invokeTask [as invoke] (polyfills.e4761bff8bd6a8151d1c.bundle.js:1)

**Comment by cipchk** [comment]
麻烦提供更多的信息，我无法帮你判断。

**Comment by qld-cf** [comment]
git clone  最新的ng-alain，npm后运行无误，打包运行 ng build --prod --aot，然后在服务器下运行index.html，就爆了这个错，群里也有人遇到这个情况，你可以试下

**Comment by dusdong** [comment]
啊，群是多少啊？我想加入

**Comment by dusdong** [comment]
啊，群是多少啊？我想加入

**Comment by qld-cf** [comment]
320404326  我也是刚加入不久，主要讨论ng-zorro-antd

**Comment by cipchk** [comment]
@qld-cf @dusdong  gh-pages 就是通过 `ng build --prod --build-optimizer --bh ./` 打包上传的，我想会不会是由于印刷体下载不全导致的呢？

能否发一下当前项目的运行 `ng -v` 的信息吗？

**Comment by qld-cf** [comment]
@cipchk  
no problem
1.你说的下载不全是什么意思呢，我重新打包还是有问题
2.
@angular/cli: 1.4.4
node: 6.11.2
os: win32 x64
@angular/animations: 4.4.3
@angular/common: 4.4.3
@angular/compiler: 4.4.3
@angular/core: 4.4.3
@angular/forms: 4.4.3
@angular/http: 4.4.3
@angular/platform-browser: 4.4.3
@angular/platform-browser-dynamic: 4.4.3
@angular/router: 4.4.3
@angular/cli: 1.4.4
@angular/compiler-cli: 4.4.3
@angular/language-service: 4.4.3
typescript: 2.3.4

**Comment by qld-cf** [comment]
@angular/cli: 1.4.4
node: 6.11.2
os: win32 x64
@angular/animations: 4.4.3
@angular/common: 4.4.3
@angular/compiler: 4.4.3
@angular/core: 4.4.3
@angular/forms: 4.4.3
@angular/http: 4.4.3
@angular/platform-browser: 4.4.3
@angular/platform-browser-dynamic: 4.4.3
@angular/router: 4.4.3
@angular/cli: 1.4.4
@angular/compiler-cli: 4.4.3
@angular/language-service: 4.4.3
typescript: 2.3.4

**Comment by qld-cf** [comment]
被和谐了？ 
。。`@angular/cli: 1.4.4
node: 6.11.2
os: win32 x64
@angular/animations: 4.4.3
@angular/common: 4.4.3
@angular/compiler: 4.4.3
@angular/core: 4.4.3
@angular/forms: 4.4.3
@angular/http: 4.4.3
@angular/platform-browser: 4.4.3
@angular/platform-browser-dynamic: 4.4.3
@angular/router: 4.4.3
@angular/cli: 1.4.4
@angular/compiler-cli: 4.4.3
@angular/language-service: 4.4.3
typescript: 2.3.4`

**Comment by cipchk** [comment]
@qld-cf 是使用 `cnpm` 安装包体的吗？

会不会是因为 rxjs 版本问题呢？试着：

```bash
npm install --save rxjs
```

**Comment by qld-cf** [comment]
@cipchk 
之前是放在服务器的目录下，服务器没正常开启导致，
不过现在还有问题，ng-alain clone下来，稍微改点配置和添加路由页面再打包，没有效果，和不打包的一样
这个何解？

**Comment by cipchk** [comment]
@qld-cf 抱歉，麻烦提供更多信息，否则我无法帮你解答任何问题。

> 另：若是另一个问题，请先关闭此 issue 并重开另一个 issue 以免让其他人同样问题时产生误解。
