### ISSUE TITLE
IE Browser Pro-header Desc-list Style Bug

### ISSUE THREAD

**Issue by colorful-app** [ng-alain/ng-alain#250]
## Bug Report or Feature Request (mark with an `x`)
<pre><code>
[ ] Bug report -> please search issues before submitting
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Reproduction link
https://cipchk.github.io/ng-alain/pro/profile/advanced

## What is expected?
IE Browser should be the same style as chrome.

## What is actually happening?
In IE 11 Browser， Pro-header label desc-list style disorder.

## Environment
<pre><code>
ng-alain version: 0.6.4
Angular version: 5.2.1
Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version 10，11
</code></pre>
- 
Chrome：
![image](https://user-images.githubusercontent.com/14008067/35261933-5923e598-004d-11e8-9d66-9d7925401b9c.png)
IE 10，11
![image](https://user-images.githubusercontent.com/14008067/35261980-87ebf942-004d-11e8-836a-f508445f5521.png)

**Comment by cipchk** [comment]
这取决于 [Ant Design PRO](https://preview.pro.ant.design/#/profile/advanced) 版本的兼容性，目前 ng-alain 不会进行处理。
