### ISSUE TITLE
集成 ngx-formly,布局错乱

### ISSUE THREAD

**Issue by smile2014** [ng-alain/ng-alain#251]
继承ngx-formly 动态表单布局错乱
https://angular-oprfhy.stackblitz.io

https://stackblitz.com/edit/angular-oprfhy

在公司名称位置输入值，再在部门名称地方输入值，清空部门名称对应得内容，界面就错乱了

**Comment by cipchk** [comment]
抱歉，我无法看到实际有问题的地方。

**Comment by smile2014** [comment]
是不好描叙，就静态表单样式也是有bug，一行排多个inpu 带验证得，先全部输入值，再一个个删除布局就乱了

**Comment by smile2014** [comment]
#<pro-header></pro-header>

      <form nz-form [formGroup]="form" (ngSubmit)="_submitForm()">
        <div nz-row [nzGutter]="16">
           <div nz-col [nzMd]="24">
            <nz-card>
                <div nz-form-item nz-row [nzGutter]="8">

                    <fieldset>
                        <legend>公司一般信息</legend>

                        <div nz-form-item nz-col [nzSpan]="8">
                            <div nz-form-label nz-col [nzSm]="6">
                                <label nz-form-item-required>公司编码</label>
                            </div>
                            <div nz-form-control nz-col nzHasFeedback [nzSm]="18" [nzValidateStatus]="companyId">
                                <nz-input formControlName="companyId" [nzPlaceHolder]="'请输入公司编码'" ></nz-input>
                                <div nz-form-explain *ngIf="(companyId.dirty || companyId.touched) && companyId.errors?.required">
                                    请输公司编码
                                </div>
                            </div>
                        </div>

                        <div nz-form-item nz-col [nzSpan]="8">
                            <div nz-form-label nz-col [nzSm]="6">
                                <label nz-form-item-required>公司名称</label>
                            </div>
                            <div nz-form-control nz-col nzHasFeedback [nzSm]="18" [nzValidateStatus]="companyName">
                                <nz-input formControlName="companyName" [nzPlaceHolder]="'请输入公司名称'"></nz-input>
                                <div nz-form-explain *ngIf="(companyName.dirty || companyName.touched) && companyName.errors?.required">
                                    请输公司名称
                                </div>
                            </div>
                        </div>

                        <div nz-form-item nz-col [nzSpan]="8">
                            <div nz-form-label nz-col [nzSm]="6">
                                <label nz-form-item-required>简称</label>
                            </div>
                            <div nz-form-control nz-col nzHasFeedback [nzSm]="18" [nzValidateStatus]="shortName">
                                <nz-input formControlName="shortName" [nzPlaceHolder]="'请输入公司简称'"></nz-input>
                                <div nz-form-explain *ngIf="(shortName.dirty || shortName.touched) && shortName.errors?.required">
                                    请输公司简称
                                </div>
                            </div>
                        </div>

                        <div nz-form-item nz-col [nzSpan]="8">
                            <div nz-form-label nz-col [nzSm]="6">
                                <label nz-form-item-required>国家名称</label>
                            </div>
                            <div nz-form-control nz-col nzHasFeedback [nzSm]="18" [nzValidateStatus]="countryName">
                                <nz-input formControlName="countryName" [nzPlaceHolder]="'请输入国家名称'"></nz-input>
                                <div nz-form-explain *ngIf="(countryName.dirty || countryName.touched) && countryName.errors?.required">
                                    请输国家名称
                                </div>
                            </div>
                        </div>

                        <div nz-form-item nz-col [nzSpan]="8">
                            <div nz-form-label nz-col [nzSm]="6">
                                <label nz-form-item-required>省份名称</label>
                            </div>
                            <div nz-form-control nz-col nzHasFeedback [nzSm]="18" [nzValidateStatus]="provinceName">
                                <nz-input formControlName="provinceName" [nzPlaceHolder]="'请输入省份名称'"></nz-input>
                                <div nz-form-explain *ngIf="(provinceName.dirty || provinceName.touched) && provinceName.errors?.required">
                                    请输省份名称
                                </div>
                            </div>
                        </div>

                        <div nz-form-item nz-col [nzSpan]="8">
                            <div nz-form-label nz-col [nzSm]="6">
                                <label nz-form-item-required>城市名称</label>
                            </div>
                            <div nz-form-control nz-col nzHasFeedback [nzSm]="18" [nzValidateStatus]="cityName">
                                <nz-input formControlName="cityName" [nzPlaceHolder]="'请输入城市名称'"></nz-input>
                                <div nz-form-explain *ngIf="(cityName.dirty || cityName.touched) && cityName.errors?.required">
                                    请输城市名称
                                </div>
                            </div>
                        </div>

                        <div nz-form-item nz-col [nzSpan]="8">
                            <div nz-form-label nz-col [nzSm]="6">
                                <label nz-form-item-required>注册地址</label>
                            </div>
                            <div nz-form-control nz-col nzHasFeedback [nzSm]="18" [nzValidateStatus]="registerAddress">
                                <nz-input formControlName="registerAddress" [nzPlaceHolder]="'请输入注册地址'"></nz-input>
                                <div nz-form-explain *ngIf="(registerAddress.dirty || registerAddress.touched) && registerAddress.errors?.required">
                                    请输入注册地址
                                </div>
                            </div>
                        </div>

                        <div nz-form-item nz-col [nzSpan]="8">
                            <div nz-form-label nz-col [nzSm]="6">
                                <label>公司英文名称</label>
                            </div>
                            <div nz-form-control nz-col [nzSm]="18">
                                <nz-input [nzPlaceHolder]="'请输入公司英文名称'"></nz-input>
                            </div>
                        </div>

                        <div nz-form-item nz-col [nzSpan]="8">
                            <div nz-form-label nz-col [nzSm]="6">
                                <label>邮政编码</label>
                            </div>
                            <div nz-form-control nz-col [nzSm]="18">
                                <nz-input [nzPlaceHolder]="'请输入邮政编码'"></nz-input>
                            </div>
                        </div>
                    </fieldset>

                    <fieldset>
                        <legend>公司其他信息</legend>

                        <div nz-form-item nz-col [nzSpan]="8">
                            <div nz-form-label nz-col [nzSm]="6">
                                <label nz-form-item-required>税号</label>
                            </div>
                            <div nz-form-control nz-col nzHasFeedback [nzSm]="18" [nzValidateStatus]="taxId">
                                <nz-input  formControlName="taxId" [nzPlaceHolder]="'纳税人识别号是税务登记证上的号码'"></nz-input>
                                <div nz-form-explain *ngIf="(taxId.dirty || taxId.touched) && taxId.errors?.required">
                                    请输入注册地址
                                </div>
                            </div>
                        </div>

                        <div nz-form-item nz-col [nzSpan]="8">
                            <div nz-form-label nz-col [nzSm]="6">
                                <label nz-form-item-required>开户银行</label>
                            </div>
                            <div nz-form-control nz-col nzHasFeedback [nzSm]="18" [nzValidateStatus]="bankName">
                                <nz-input formControlName="bankName" [nzPlaceHolder]="'请输入开户银行'"></nz-input>
                                <div nz-form-explain *ngIf="(bankName.dirty || bankName.touched) && bankName.errors?.required">
                                    请输入开户银行
                                </div>
                            </div>
                        </div>

                        <div nz-form-item nz-col [nzSpan]="8">
                            <div nz-form-label nz-col [nzSm]="6">
                                <label nz-form-item-required>帐号</label>
                            </div>
                            <div nz-form-control nz-col nzHasFeedback [nzSm]="18" [nzValidateStatus]="accountId">
                                <nz-input formControlName="accountId" [nzPlaceHolder]="'请输入帐号'"></nz-input>
                                <div nz-form-explain *ngIf="(accountId.dirty || accountId.touched) && accountId.errors?.required">
                                    请输入帐号
                                </div>
                            </div>
                        </div>

                        <div nz-form-item nz-col [nzSpan]="8">
                            <div nz-form-label nz-col [nzSm]="6">
                                <label nz-form-item-required>联系人</label>
                            </div>
                            <div nz-form-control nz-col [nzSm]="18">
                                <nz-input formControlName="contactName" [nzPlaceHolder]="'请输入联系人'"></nz-input>
                            </div>
                        </div>

                        <div nz-form-item nz-col [nzSpan]="8">
                            <div nz-form-label nz-col [nzSm]="6">
                                <label nz-form-item-required>联系电话</label>
                            </div>
                            <div nz-form-control nz-col [nzSm]="18">
                                <nz-input formControlName="contactPhone" [nzPlaceHolder]="'请输入联系电话'"></nz-input>
                            </div>
                        </div>

                        <div nz-form-item nz-col [nzSpan]="8">
                            <div nz-form-label nz-col [nzSm]="6">
                                <label nz-form-item-required>手机号码</label>
                            </div>
                            <div nz-form-control nz-col [nzSm]="18">
                                <nz-input formControlName="cellPhoneNumber" [nzPlaceHolder]="'请输入手机号码'"></nz-input>
                            </div>
                        </div>

                        <div nz-form-item nz-col [nzSpan]="8">
                            <div nz-form-label nz-col [nzSm]="6">
                                <label nz-form-item-required>有效标记</label>
                            </div>
                            <div nz-form-control nz-col [nzSm]="18">
                                <label nz-checkbox formControlName="isValid">
                                    <span>有效</span>
                                </label>
                            </div>
                        </div>

                        <div nz-form-item nz-col [nzSpan]="8">
                            <div nz-form-label nz-col [nzSm]="6">
                                <label>供应商编码</label>
                            </div>
                            <div nz-form-control nz-col [nzSm]="18">
                                <nz-input [nzPlaceHolder]="'请输入供应商编码'"></nz-input>
                            </div>
                        </div>

                        <div nz-form-item nz-col [nzSpan]="8">
                            <div nz-form-label nz-col [nzSm]="6">
                                <label>客户编码</label>
                            </div>
                            <div nz-form-control nz-col [nzSm]="18">
                                <nz-input [nzPlaceHolder]="'请输入客户编码'"></nz-input>
                            </div>
                        </div>

                        <div nz-form-item nz-col [nzSpan]="16">
                            <div nz-form-label nz-col [nzSm]="3">
                                <label>备注</label>
                            </div>
                            <div nz-form-control nz-col [nzSm]="21">
                                <nz-input [nzPlaceHolder]="'请输入字段'"></nz-input>
                            </div>
                        </div>
                    </fieldset>
                </div>
            </nz-card>
        </div>
    </div>

    <footer-toolbar errorCollect style="z-index: 0">
        <button nz-button [nzType]="'primary'" nzSize="large">提交</button>
    </footer-toolbar>
</form>

**Comment by smile2014** [comment]
import { Component, OnInit } from '@angular/core';
import {FormBuilder, FormGroup, Validators} from "@angular/forms";

@Component({
  selector: 'app-demo7',
  templateUrl: './demo7.component.html',
  styles: []
})
export class Demo7Component implements OnInit {

    feildList = [{
        "name": "companyId",
        "label": "公司编码",
        "placeHolder": "请输入公司编码",
        "type": "input",
        "crossColumn": {
            "div": 8,
            "label": 6,
            "input": 18
        },
        "event": {
        }
    },{
        "name": "companyName",
        "label": "公司名称",
        "placeHolder": "请输入公司名称",
        "type": "input",
        "crossColumn" : {
            "div": 8,
            "label": 6,
            "input": 18
        },
        "event": {
        }
    },{
        "name": "contractId",
        "label": "合同编码",
        "placeHolder": "请输入合同编码",
        "type": "input",
        "crossColumn" : {
            "div": 8,
            "label": 6,
            "input": 18
        },
        "event": {
        }
    },{
        "name": "contractName",
        "label": "合同名称",
        "placeHolder": "请输入合同名称",
        "type": "input",
        "crossColumn" : {
            "div": 8,
            "label": 6,
            "input": 18
        },
        "event": {
        }
    },{
        "name": "comment",
        "label": "备注",
        "placeHolder": "请输入备注",
        "type": "input",
        "crossColumn" : {
            "div": 16,
            "label": 3,
            "input": 21
        },
        "event": {
        }
    },{
        "name": "suggesting",
        "label": "建议",
        "placeHolder": "请输入建议",
        "type": "textarea",
        "crossColumn" : {
            "div": 24,
            "label": 2,
            "input": 22
        },
        "event": {
        }
    }];

    form: FormGroup;

    selectValue;

    options = [
        { value: 'jack', label: 'Jack' },
        { value: 'lucy', label: 'Lucy' },
        { value: 'disabled', label: 'Disabled', disabled: true }
    ];
    constructor(private fb: FormBuilder) {
        this.selectValue = this.options[0];

        this.form = this.fb.group({
            companyId: [],
            companyName: [],
            contractId: [],
            contractName: [],
            comment: [],
            suggesting: []
        });
    }

    ngOnInit() {
    }

    _submitForm(){
        console.log(this.form.value);
    }

}

**Comment by cipchk** [comment]
抱歉，关于业务应用和 ng-zorro-antd 请至官网提交相应 issues

**Comment by smile2014** [comment]
谢谢这个应该是ng-zorro-antd的bug
