### ISSUE TITLE
reuse-tab：切换tab页时使用了router-outlet的页面被关闭

### ISSUE THREAD

**Issue by jaydonshi** [ng-alain/ng-alain#252]
## Bug Report or Feature Request (mark with an `x`)

<pre><code>
[x] Bug report -> please search issues before submitting
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Reproduction link

![bug](https://user-images.githubusercontent.com/20196853/35279368-e1a91b4c-0087-11e8-8823-78373170d5d6.gif)

## Steps to reproduce

1. 打开一个使用了router-outlet的页面
2. 点击其他页面

## What is expected?

在打开的tab页面之间进行切换

## What is actually happening?

使用router-outlet的页面将会关闭

## Environment

<pre><code>
ng-alain version: 0.6.4
Angular version: 5.2.0
Browser:
- [x] Chrome (desktop) version 63
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
</code></pre>

**Comment by winpzs** [comment]
默认是根据menu数据来处理的，如果不在menu数据里的url，会被认为临时页面。然后就是你这情况了

**Comment by cipchk** [comment]
子模块再包含一个 `<router-outlet>` 这种情况的确没有测试过。DEMO 也的确响应这一情况；我需要进一步核实。

当前也可能如同 @winpzs 说的情况，因为当再一次遇到子路由时，在菜单数据中的确没有相对应。

**Comment by liangqiliang** [comment]
那如果遇到一个很特殊的情况，某个页面不想放它在menu里头，又想让其能够路由复用，能解决吗？ @winpzs @cipchk

**Comment by cipchk** [comment]
http://ng-alain.com/components/reuse-tab#%E5%8C%B9%E9%85%8D%E6%A8%A1%E5%BC%8F

**Comment by liangqiliang** [comment]
加入说是有个用户的编辑界面 它是根据用户生成不同的路由，比如/useredit/xxx，这样子怎么将其复用呢？ @cipchk

**Comment by cipchk** [comment]
@liangqiliang 抱歉，我无法理解你的问题。另请依文档来操作，我想文档中的三种匹配，可以解决你上述的问题。

> PS：有其他问题请独立 issues 描述，以免给其他人产生无法理解。
