### ISSUE TITLE
proxy.conf.json not effected ?

### ISSUE THREAD

**Issue by ghost** [ng-alain/ng-alain#255]
I use python django as api server, "http://dev.mautops.cn:8000" is api root url;

Here is snippets:
> proxy.conf.json
```
{
    "/api":{
        "target": "http://dev.mautops.cn:8000"
    }
}
```
> package.json
```
"start": "ng serve -H dev.mautops.cn --proxy-config proxy.conf.json",
```

> AngularJS Http Get
```
 this.http.get('/api/base-info/company/').subscribe((res: any) => {
    this.list = this.list.concat(res);
    this.loading = false;
 });
```

### But why proxy is not effected ??
> chrome dev-tool networking
```
Request URL:http://dev.mautops.cn:4200//api/base-info/company/
Request Method:GET
Status Code:404 Not Found
Remote Address:127.0.0.1:4200
Referrer Policy:no-referrer-when-downgrade
```

### ??  The expected URL is  "http://dev.mautops.cn:8000/base-info/company/"
But Why it still request aimed "http://dev.mautops.cn:4200//api/base-info/company/"

### AngluarJS New Commer, Please Help ;

**Comment by cipchk** [comment]
Please confirm has any error information in terminal, like: 

```
[HPM] Error occurred while trying to proxy request
```

**Comment by ghost** [comment]
Thanks U're Reply;

unfortunately，ng server run absolutely good, no error occurs

**Comment by cipchk** [comment]
i think your proxy.conf.json confirguration error, pls note the following details:

- url are `/api/base-info/company/`, so proxy should be `/api/*`.
- should be enabled `"logLevel": "debug"`

**Comment by ghost** [comment]
Hi Cipchk:

I will try in u're way later, right now , i modify the env vars to take effects

#### ^_^
```
export const environment = {
    chore: false,
    SERVER_URL: `http://dev.mautops.cn:8000`,
    production: false,
    hmr: false,
    useHash: true
};
```

#### 3Q, it's token problem right right now, we can close it !

**Comment by ghost** [comment]
```
SERVER_URL: `http://dev.mautops.cn:8000`,
```
config as shown, cross domain request appears;

> I Guess, maybe ?
```
may be proxy is effected because of DefaultInterceptor which u rewrite to deal http yourself
```

I Still Can not resolve the problem with cross domain request;

> ?? How can you resolve the cross domain issue without mock-server;
