### ISSUE TITLE
怎么自定义主题色？

### ISSUE THREAD

**Issue by weimingxuan** [ng-alain/ng-alain#256]
比如要改变表单点击态时的边框颜色，怎么做到的？

**Comment by cipchk** [comment]
除目前支持的若干种颜色以外，你只能透过 [theme.less](https://github.com/cipchk/delon/blob/master/src/core/theme/styles/themes/theme.less) 的写法，但成本比较高。

关于自定义色系，需要等到 ng-zorro-antd 0.7.0 才会支持，请持续关注。

**Comment by CoderPoet** [comment]
现在支持自定义主题色了吗？想搞一个暗色系的admin

**Comment by cipchk** [comment]
https://ng-alain.com/theme

**Comment by CoderPoet** [comment]
@cipchk 这个定制好像不能修改组件的样式把？组件的样式还是得自己去覆盖吗？
