### ISSUE TITLE
咨询菜单复用功能的使用方法

### ISSUE THREAD

**Issue by xingkoo** [ng-alain/ng-alain#260]
当前使用0.6.5版本
在列表页显入详情页时，使用的带参数的Url地址。
```ts
this.router.navigate(['proposal/detail', proposalId]);
```
在菜单中会显示当前路由 **proposal/detail**，如下图。请问如何使用可以不显示在菜单中，或显示指定名称？
![snip20180127_72](https://user-images.githubusercontent.com/2936579/35470726-b672da12-0389-11e8-81cc-d3504eb5cd7c.png)

**Comment by cipchk** [comment]
麻烦重现一个在线示例：https://stackblitz.com/edit/ng-alain-setup

**Comment by winpzs** [comment]
它的URL是完全匹配才行，这种带ID的子页面是应该考虑支持的
