### ISSUE TITLE
error when use [full-toggle] directive 全屏操作 full-toggle 报错

### ISSUE THREAD

**Issue by xbu** [ng-alain/ng-alain#263]
## Bug Report or Feature Request (mark with an `x`)

使用了表格全屏指令full-toggle，除了在demo页面，其他页面放进去都会报错

## Reproduction link

https://stackblitz.com/edit/ng-alain-setup-ecj3ha?file=app%2Fapp.component.html

## Environment

ng-alain 0.64
<pre><code>
ng-alain version: X.Y.Z
Angular version: X.Y.Z
Browser:
- [* ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
</code></pre>

**Comment by cipchk** [comment]
抱歉，我没看到DEMO有任何相关能重现问题的代码。

**Comment by xbu** [comment]
抱歉，我zai在app.component.html中更新了一些注释。
问题在我下载ng-alain源代码之后，除了在fs-table页面可以使用指令full-toggle之外，其他页面（含table模块下其他页面）使用都会在报错，
![image](https://user-images.githubusercontent.com/741724/35494628-cfb30bbe-04f6-11e8-82dd-fdc9b587a5a7.png)

上面链接里的有两个button，一个有指令full-toggle，可以通过注释来使得问题重现

**Comment by xbu** [comment]
问题解决，另外需要给全屏区域加上full-content标签
