### ISSUE TITLE
建议：menu增加一个配置，标识这个菜单在没权限的时候也展示

### ISSUE THREAD

**Issue by qq254963746** [ng-alain/ng-alain#264]
RT
建议：menu增加一个配置，标识这个菜单在没权限的时候也展示
有种场景是可以让用户看到菜单，但是真正点击菜单的时候，采取判断权限，并告知申请哪些权限

**Comment by cipchk** [comment]
建议直接不传 `acl` 属性，这样会更友好一点。

**Comment by jol5** [comment]
请问一下，如果有时候需要既需要它显示，却又不让他点击（灰色禁用状态呢），这样用户更加直观。
