### ISSUE TITLE
is Y-scroll required when using full content feature ? [需求讨论]全屏表格是否必须配合Y-scroll

### ISSUE THREAD

**Issue by xbu** [ng-alain/ng-alain#265]
初次看到全屏表格对于大量数据的展现眼前一亮，但如果不设置scroll属性则不能很好的显示，页面的下半部分包含分页显示不出来了。这项功能能否支持不用scroll属性，也能很好的全屏

![image](https://user-images.githubusercontent.com/741724/35559676-4337849e-05e6-11e8-99e5-415630230971.png)

**Comment by cipchk** [comment]
暂时没有办法，这是 `nz-table` 的缺失。你可以考虑对于大数据使用 ag-grid 好像有人这么用，#86
