### ISSUE TITLE
jwt过期无法跳转到登陆页面。

### ISSUE THREAD

**Issue by laosandegudai** [ng-alain/ng-alain#268]
目前使用了jwt拦截器，能够正常在头部添加token，但是当token失效时无法跳转到登陆页面而是直接抛出一个异常，该异常无有效信息。
使用方式，因为可以正常使用我猜我是正常使用的。为何失效时不能跳转到登陆页面我以下猜想：
1 登陆是按照cli生成的模板，是否填写的时间参数不对（因为token可正常使用）；
2 在appmodule里面按照文档配置了一些参数感觉没用；
3 读了jwt拦截器的源码后，返现payload属性，并且过期判断依赖此属性，payload的值是通过token值通过“.”切割所得，但是查看localstorage里面是用“,”分割，至此搞不清楚。
因为我能够正常使用Jwt拦截器但过期后无法解决，不知道我是否用错了方式。

**Comment by cipchk** [comment]
过期或无效（JWT）的情况下，若指定 `token_invalid_redirect:true` 才会根据 `login_url` 跳转。
其他的请自行了解JWT的标准。

**Comment by laosandegudai** [comment]
token_invalid_redirect:true
这个设置过了。
目前在存入token时指定了过期时间，在appmodule也设置了过期时间均无效。

**Comment by cipchk** [comment]
过期只限JWT，请核实JWT是否有效 https://jwt.io/

**Comment by laosandegudai** [comment]
有效的，因为我的接口访问是有限制的，如果不加token是不能正常访问的。

**Comment by cipchk** [comment]
能否提供你的 token

**Comment by laosandegudai** [comment]
可以，{"token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjEiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtaW4iLCJBc3BOZXQuSWRlbnRpdHkuU2VjdXJpdHlTdGFtcCI6IjhhZTIyNDU3LTMyNWUtZjE5ZS1mOWM0LTM5ZTQzZGVlYzk5NSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwic3ViIjoiMSIsImp0aSI6IjllMDI0OWMyLWU5ZTgtNDc0ZC05MDZiLTExMDI0ZWE0MDAwMiIsImlhdCI6MTUxNzQ3NjIyMiwibmJmIjoxNTE3NDc2MjIyLCJleHAiOjE1MTc1NjI2MjIsImlzcyI6Imd6bCIsImF1ZCI6Imd6bCJ9.IMDdDQwtPvwlocPTXJxVgocG-ZG2EgU3ARWoHRNUfD4","name":"admin","email":"cipchk@qq.com","id":1,"time":"2018-02-01T09:10:31.914Z"}，

token的保存是按照模板生成的代码保存符合文档要求。我看你写的jwt拦截器里面用 “.”点切割时间。不知我写的有误。
写入：
    const tokenExpireDate = this.remember ? (new Date(new Date().getTime() + 1000 * 10)) : undefined;
                this.tokenService.set({
                    token: result.accessToken,
                    name: this.userName.value,
                    email: `cipchk@qq.com`,
                    id: result.userId,
                    time: tokenExpireDate
                });
Token设置：
   AlainAuthModule.forRoot({
            ignores: ['api/TokenAuth/Authenticate'],
            login_url: '/passport/login',
            token_invalid_redirect: true,
            token_exp_offset: 10,
        }),

**Comment by cipchk** [comment]
auth 的 `exp` 必须是毫秒级，我看解析出来是：

```json
"exp": 1517562622
```

只到秒级。

**Comment by laosandegudai** [comment]
什么意思？时间必须精确到毫秒级？

**Comment by cipchk** [comment]
```js
new Date.getTime()
```

**Comment by laosandegudai** [comment]
我这是往后延迟10秒啊。

**Comment by cipchk** [comment]
```json
"exp": 1517562622
```

```js
(new Date).getTime()
// output
1517478737522
```

**Comment by laosandegudai** [comment]
exp小了不是应该更快过期吗？
懵了，不知道怎么设置了。

**Comment by laosandegudai** [comment]
作者意思是我的过期时间必须精确到毫秒级，我返回的确实是秒的。

**Comment by laosandegudai** [comment]
感谢作者耐心指导，稍后我会修改token过期的方式。

**Comment by 287541828** [comment]
请问你解决了吗?

**Comment by laosandegudai** [comment]
因为我不可能更改服务器，所以我重写了过期验证。
