### ISSUE TITLE
File Upload without any action when click Single upload button

### ISSUE THREAD

**Issue by maplye** [ng-alain/ng-alain#27]
## Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

0.1.2-beta.2

### Repro steps.

Without any action when click Single button of upload page under IE9 browser.
Need multiple click under chrome browser after F5 refresh the page.

**Comment by maplye** [comment]
I still can't open file dialog when I click Single button on IE 11, the version is 0.1.3

**Comment by cipchk** [comment]
the `nz-upload` comint soon (see [pull](https://github.com/NG-ZORRO/ng-zorro-antd/pull/370))

**Comment by cipchk** [comment]
原生已支持：https://ng.ant.design/#/components/upload
