### ISSUE TITLE
【建议】reuse-tab title问题

### ISSUE THREAD

**Issue by qq254963746** [ng-alain/ng-alain#272]
目前遇到几个问题.
1. title问题，queryString模式，设置title无用，貌似是bug，能否提供页面上某个隐藏元素中的文字的方式来解决
2. 复用问题，queryString 方式，不同的参数，复用了同一个tab，这种情况能否提供配置，来决定是否可以复用同一个 
3. 决定能否提供这种方式：否复用能否根据title来判断，title相同的就复用，不同的就不复用
  **感谢开源奉献**

**Comment by winpzs** [comment]
这个只是你自己的业务需要吧。。。

**Comment by sliu1975** [comment]
reuse-tab确实是个大问题，参数的传递是非常普遍的，这个建议好好设计下
