### ISSUE TITLE
独立使用ABC组件

### ISSUE THREAD

**Issue by jackzhum** [ng-alain/ng-alain#273]
环境：最新版的alain(0.6.6)。
因为有自己的权限管理，暂时用不到ACL，看到文档中说可以独立使用ABC，于是在delon.module.ts中把ACL引入的代码去掉了，但是运行的时候报错。看错误提示是因为没有导入ACL模块，看了错误代码发现在ABC的组件：simple-table中有使用到了ACL：

Failed to compile.

./node_modules/@delon/abc/simple-table/simple-table.component.js
Module not found: Error: Can't resolve '@delon/acl' in 'D:\Projects\angular-ant\node_modules\@delon\abc\simple-table'
 @ ./node_modules/@delon/abc/simple-table/simple-table.component.js 12:0-40
 @ ./node_modules/@delon/abc/simple-table/simple-table.module.js
 @ ./node_modules/@delon/abc/index.js
 @ ./src/delon.module.ts
 @ ./src/root.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts

**Comment by cipchk** [comment]
我可以明确这是一个可选依赖，请核实是否其他因素引起的。

**Comment by jackzhum** [comment]
@cipchk 感谢回复。今天又去看了下代码，以为是引入库引入错了，但是最后发现还是ABC组件里确实用到了ACL。我也去@delon项目里查看了源码，发现也确实有引入：
[https://github.com/cipchk/delon/blob/master/src/core/abc/simple-table/simple-table.component.ts](https://github.com/cipchk/delon/blob/master/src/core/abc/simple-table/simple-table.component.ts)

再次感谢！实在不行我就导入acl的包吧。

**Comment by cipchk** [comment]
需要安装 acl 包，但不需要引入。我可以明确这一点。

**Comment by jackzhum** [comment]
明白了，我一直以为如果不需要的话可以不安装acl包的。再次感谢。
