### ISSUE TITLE
number-info 数据文本组件，当 [total] 未赋值之前，会显示为 undefined

### ISSUE THREAD

**Issue by dusdong** [ng-alain/ng-alain#274]
## Bug Report or Feature Request (mark with an `x`)

<pre><code>
[x] Bug report -> please search issues before submitting
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Reproduction link

![image](https://user-images.githubusercontent.com/3461709/35761344-66c4c640-08c2-11e8-98e6-33b8338fb81f.png)

**Comment by cipchk** [comment]
不会修复，建议提供有效值。
