### ISSUE TITLE
NzModalService调用component作为内容，右上角默认有一个X，能去掉吗

### ISSUE THREAD

**Issue by fstanwh** [ng-alain/ng-alain#276]
## Bug Report or Feature Request (mark with an `x`)

<pre><code>
[ ] Bug report -> please search issues before submitting
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Environment

<pre><code>
ng-alain version: X.Y.Z
Angular version: X.Y.Z
Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
</code></pre>

**Comment by cipchk** [comment]
https://ng.ant.design/#/components/modal
