### ISSUE TITLE
table repeat request

### ISSUE THREAD

**Issue by lyc152** [ng-alain/ng-alain#281]
```
Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
```

在 使用table 组件时，发现如果  currentPage 不是第一页时，我现在在做筛选，排序或者带条件搜索时，发现会多发一次请求, simple table 有这个问题，ng-zorro 也有这个问题

**Comment by cipchk** [comment]
应该是 `nz-table` 的bug。

**Comment by lyc152** [comment]
已经给 ng-zorro 提bug了，我试图通过添加判断条件来禁止重复发请求，发现会报错，但是页面可以正常呈现
