### ISSUE TITLE
使用ng new -c=@delon/cli my-app 创建工程出现错误

### ISSUE THREAD

**Issue by rockjava** [ng-alain/ng-alain#282]
## Bug Report or Feature Request (mark with an `x`)

<pre><code>
[X] Bug report -> please search issues before submitting
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Steps to reproduce
按照命令行使用文档，搭建好环境后，执行创建工程命令是出现如下错误

```ts
Error: input.mergeMap is not a function
input.mergeMap is not a function
````

## Environment

<pre><code>
Angular CLI: 1.6.3
Node: 8.9.2
</code></pre>

**Comment by cipchk** [comment]
参考 [#8961](https://github.com/angular/angular-cli/issues/8961)
