### ISSUE TITLE
how to delete cosole https://kcart.alipay.com

### ISSUE THREAD

**Issue by lyc152** [ng-alain/ng-alain#286]
ng-alain version: X.Y.Z
Angular version: X.Y.Z
Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
</code></pre>

我发现后台 有这个警告
 The SSL certificate used to load resources from https://kcart.alipay.com will be distrusted in M70. Once distrusted, users will be prevented from loading these resources. See https://g.co/chrome/symantecpkicerts for more information.

不知道怎么删除

**Comment by cipchk** [comment]
见：https://antv.alipay.com/zh-cn/g2/3.x/tutorial/index.html#_%E4%BD%93%E9%AA%8C%E6%94%B9%E8%BF%9B%E8%AE%A1%E5%88%92%E8%AF%B4%E6%98%8E
