### ISSUE TITLE
_HttpClient 组件，可否提供一个参数，不自动处理时间格式

### ISSUE THREAD

**Issue by dusdong** [ng-alain/ng-alain#287]
## Bug Report or Feature Request (mark with an `x`)

<pre><code>
[ ] Bug report -> please search issues before submitting
[x] Feature request
[ ] Documentation issue or request
</code></pre>

_HttpClient 组件，可否提供一个参数，不自动处理时间格式

**Comment by cipchk** [comment]
可以直接使用原生的。

**Comment by dusdong** [comment]
习惯了用 _HttpClient，alain一体化解决方案， :-)

**Comment by cipchk** [comment]
暂时不会增加，你可以利用拦截器对其进一步修改。
