### ISSUE TITLE
Project not friendly with VSCode 'Angular Language Service' plugin.

### ISSUE THREAD

**Issue by vellengs** [ng-alain/ng-alain#29]
![image](https://user-images.githubusercontent.com/5743338/31533024-004222e2-afb6-11e7-91ea-218fc58be5e0.png)

A lot of error message like those:
file: 'file:///xxxxxxxx/src/app/routes/dashboard/v1/v1.component.html'
severity: 'Error'
message: 'Can't bind to 'sparkline' since it isn't a known property of 'div'.'
at: '29,42'
source: 'Angular';

**Comment by cipchk** [comment]
maybe caused by this issue [#99](https://github.com/angular/vscode-ng-language-service/issues/99)

**Comment by vellengs** [comment]
Yes, I added  NgZorroAntdModule.forRoot() into routes.module.ts 
imports, some errors disappear.
that had been imported at SharedModule.

**Comment by vellengs** [comment]
import { NgModule } from '@angular/core';
import { RouterModule } from '@angular/router';
import { SharedModule } from '@shared/shared.module';
import { PagesModule } from './pages/pages.module';

import { routes } from './routes';
import { DashboardV1Component } from './dashboard/v1/v1.component';
import { NgZorroAntdModule } from 'ng-zorro-antd';

@NgModule({
    imports: [
        NgZorroAntdModule.forRoot(),  // should not import again, may caused by Angular Language Service
        SharedModule,
        RouterModule.forRoot(routes, { useHash: true }),
        PagesModule
    ],
    declarations: [
        DashboardV1Component
    ],
    exports: [
        RouterModule
    ]
})

export class RoutesModule { }

**Comment by cipchk** [comment]
the Angular Language Service extenstion is optional in development, i can't provider fix this information. sorry.
