### ISSUE TITLE
import { ACLGuard } from '@delon/acl';

### ISSUE THREAD

**Issue by wgqjiayou** [ng-alain/ng-alain#290]
When used the "`import { ACLGuard } from '@delon/acl';`", the prompt error : **has no exported member 'ACLGuard'**

**Comment by cipchk** [comment]
i mark sure that have got export `ACLGuard` ([index.ts](https://github.com/cipchk/delon/blob/master/src/core/acl/index.ts#L26)), pls trying reinstall package again.

**Comment by wgqjiayou** [comment]
What is the instruction to download the package?

**Comment by cipchk** [comment]
```bash
npm i @delon/acl
```

**Comment by wgqjiayou** [comment]
I tried reinstall package again, but the file was not updated
![image](https://user-images.githubusercontent.com/34337762/36070562-74a3cda2-0f38-11e8-9ada-1aaca7845d2c.png)
![image](https://user-images.githubusercontent.com/34337762/36070565-8d1ea5a0-0f38-11e8-9b45-6f0553c75d90.png)

**Comment by cipchk** [comment]
```bash
# remove node_moudes & package-lock.json
npm i
```

**Comment by wgqjiayou** [comment]
Thank you very much, I found that its version is relatively low, upgraded to 0.6.6 later is correct
