### ISSUE TITLE
请教一下关于ACL 提供一个用于改变按钮级别粒度的控制能力的Directive 指令使用方法

### ISSUE THREAD

**Issue by Beelzebub4** [ng-alain/ng-alain#291]
## Directive 指令
ACL 提供一个用于改变按钮级别粒度的控制能力，例如：无权限者不允许显示列表页中的增加按钮。

使用角色名
<button [acl]="'user'"></button>
<button [acl]="['user', 'manage']"></button>
使用权限点
<button [acl]="10"></button>
<button acl [acl-ability]="10"></button>

## 上面是官方文档说明 下面是我的例子
<button [acl]="'user1'"></button>
报错信息如下:
ng: Can't bind to 'acl' since it isn't a known property of 'button'.
请问我应该import哪些组件才能使用这个指令

**Comment by cipchk** [comment]
确保导入 `@delon/acl` 模块

**Comment by ghost** [comment]
###  First Import Modules
```
import { AlainACLModule } from '@delon/acl';
@NgModule({
  imports: [
    SharedModule,
    BaseinfoRoutingModule,
    **AlainACLModule**
  ]
```

###  Second is the important
This will be unavailable
```
<button acl [acl-ability]="10"></button>
```
You Must use it like this:
```
<button acl acl-ability="10"></button>
```
### I Hope it Helps !

**Comment by cipchk** [comment]
建议在 `shared.module` 导入与导出 acl 模块，我会修正这一点。
