### ISSUE TITLE
在其他Component中能用SettingsService覆盖StartupService初始化的那些东西么

### ISSUE THREAD

**Issue by ReExia** [ng-alain/ng-alain#292]
我在UserLoginComponent中能用SettingsService，MenuService覆盖页面初始化StartupService中的东西么，比如User,menu

**Comment by cipchk** [comment]
当然 [setLayout](https://github.com/cipchk/delon/blob/master/src/core/theme/services/settings/settings.service.ts#L67)、setApp、setUser

**Comment by ReExia** [comment]
感谢您的回答,这套组件很棒，个人而言非常喜欢，希望文档中，日后能有一些对于登录授权与后台交互的一些说明.....

**Comment by iwantacook** [comment]
但是有个问题，F5刷新之后，好像数据就初始化了。
能不能先获取有效用户信息，存起来，然后获取，如果没有信息，就再到对应的页面去获取数据？
startup能不能在获取用户授权后再执行呢？
有什么好的方法吗？

**Comment by cipchk** [comment]
@iwantacook 默认情况下 token 是存在于 localStorage，因此，刷新并不会丢失。

> 有关业务逻辑问题，请至群：316911865，可能会得到更好的解答。

**Comment by iwantacook** [comment]
谢谢
