### ISSUE TITLE
ITokenService，它会帮你存储在 localStorage 当中（默认情况下）,如何改为cookie

### ISSUE THREAD

**Issue by ReExia** [ng-alain/ng-alain#294]
文档中有一句话是这样的
`ITokenService，它会帮你存储在 localStorage 当中（默认情况下）`
想问的是 如何设置存入cookie，不存在loaclStorage中

**Comment by cipchk** [comment]
`ITokenService` 是一个接口，默认情况下实现了 localStorage 版本。我可以根据你的需要实现一个 Cookie 版本亦可。

> PS: 群：316911865，有人实现相应的版本。

**Comment by ReExia** [comment]
感谢回答，目前我在项目中只引用了，
```
 "@delon/abc": "^0.6.5",
 "@delon/theme": "^0.6.5",
 "@delon/acl": "^0.6.5",
```
其余部分打算自己实现了，主题这些用alain

**Comment by wzfjesun** [comment]
> `ITokenService` 是一个接口，默认情况下实现了 localStorage 版本。我可以根据你的需要实现一个 Cookie 版本亦可。
> 
> > PS: 群：316911865，有人实现相应的版本。
 @cipchk 能否告知下是怎么实现的，我是新手
