### ISSUE TITLE
simple-table无法显示loading效果

### ISSUE THREAD

**Issue by chenhongbinjs** [ng-alain/ng-alain#295]
simple-table在使用url参数时，能够显示loading效果，但是该参数过时了，在使用data参数获取数据的时候如何获得loading效果？没看到有这个参数。

**Comment by cipchk** [comment]
请求过程中会自动管理 `loading` 值 [code](https://github.com/cipchk/delon/blob/master/src/core/abc/simple-table/simple-table.component.ts#L254)
