### ISSUE TITLE
建议丰富一下右侧的清理全部Tab页按钮的功能

### ISSUE THREAD

**Issue by baiyunchen** [ng-alain/ng-alain#296]
我司的管理后台也是基于angular的类似的多tab页的框架，对于ng-align中的关闭全部tab页的按钮，我司框架中还有一些其他的功能，感觉还挺实用，希望未来的ng align中可以增加。
其中GoTo是用来快捷的转到已打开的某个tab中。
![image](https://user-images.githubusercontent.com/10071911/36585623-93687834-18b9-11e8-96ae-2795886cc99b.png)

**Comment by cipchk** [comment]
welcome pr!
