### ISSUE TITLE
发布失败，UEditorModule有错误。

### ISSUE THREAD

**Issue by zhh007** [ng-alain/ng-alain#297]
## Bug Report or Feature Request (mark with an `x`)

<pre><code>
[x] Bug report -> please search issues before submitting
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Steps to reproduce

直接克隆项目后，进行发布操作，发生以下错误。
PS C:\__publish\my-project> ng build --prod --aot
Date: 2018-02-24T15:16:52.818Z
Hash: 086dd8d5bb253b3708f7
Time: 63571ms
chunk {scripts} scripts.e50c400a0fae7f0fbf51.bundle.js (scripts) 872 kB [initial] [rendered]
chunk {0} styles.10fb829aa5827d987cc4.bundle.css (styles) 422 kB [initial] [rendered]
chunk {1} polyfills.997d8cc03812de50ae67.bundle.js (polyfills) 84 bytes [initial] [rendered]
chunk {2} main.ee32620ecd1edff94184.bundle.js (main) 84 bytes [initial] [rendered]
chunk {3} inline.318b50c57b4eba3d437b.bundle.js (inline) 796 bytes [entry] [rendered]

ERROR in ..\ngx-ueditor\index.ts(11,2): Error during template compile of 'UEditorModule'
  Function calls are not supported in decorators but 'ɵmakeDecorator' was called in 'NgModule'
    'NgModule' calls 'ɵmakeDecorator'.

## Environment

<pre><code>
ng-alain version: 0.6.6
Angular version: 5.2.6
</code></pre>

**Comment by cipchk** [comment]
我确认并无问题，版本信息如下：

```
Angular CLI: 1.7.1
Node: 8.5.0
OS: win32 x64
Angular: 5.2.6
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 5.2.3
@angular/cli: 1.7.1
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.1
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.6.2
webpack-bundle-analyzer: 2.11.0
webpack: 3.11.0
```

**Comment by evin2333** [comment]
![image](https://user-images.githubusercontent.com/70325455/95728292-ed987800-0cad-11eb-8489-b0f9d921e45b.png)
这个有遇到过吗
