### ISSUE TITLE
应该采用package-lock.json

### ISSUE THREAD

**Issue by winpzs** [ng-alain/ng-alain#298]
## Bug Report or Feature Request (mark with an `x`)

<pre><code>
[ ] Bug report -> please search issues before submitting
[X] Feature request
[ ] Documentation issue or request
</code></pre>

## Feature request

 不然安装的版本与你的版本不一致

**Comment by cipchk** [comment]
很难取舍包到底应该保持最新，还是固化版本号。固化的确可以减少由于包的升级引起不必要的麻烦，但同时也会引起一些更新的繁琐。

容我再思考一下。

**Comment by winpzs** [comment]
起码你可以锁定运行的版本，如果我们想升级里面的组件，把lock文件干掉再安装就行了。

不然我更新后，你的版本跑不起来。

**Comment by cipchk** [comment]
[package-lock.json](https://gist.github.com/cipchk/7af963709c04ebed025f65a867916849)
