### ISSUE TITLE
编译后，放在tomcat运行，无法浏览网页

### ISSUE THREAD

**Issue by sliu1975** [ng-alain/ng-alain#299]
![image](https://user-images.githubusercontent.com/17998373/36650471-a7617896-1ade-11e8-8d3a-94d199b8ddf7.png)

## What is expected?

可以正常浏览

## What is actually happening?

无法打开网页

## Environment

<pre><code>
ng-alain version: 0.6.5
Browser:
- [ ] Chrome (desktop) 
</code></pre>

**Comment by cipchk** [comment]
应该是index.html中 `<base href="">` 语句倒置无法加载资源。
