### ISSUE TITLE
第一次打开页面http_client请求数据太慢，怎么破？？？

### ISSUE THREAD

**Issue by zhengyanghuaer** [ng-alain/ng-alain#301]
![qq 20180228160658](https://user-images.githubusercontent.com/35128870/36776640-74485d0c-1ca1-11e8-89ff-8093a4df1235.png)

**Comment by cipchk** [comment]
能否优先确认是否后端的原因呢？

**Comment by zhengyanghuaer** [comment]
后台的数据请求很快的啊，测试了的

**Comment by yixiangling** [comment]
这是后端服务的问题，如果只是第一个/次请求慢说明你服务在初始化，如果每次都慢就检查你代码执行效率低下的地方

**Comment by cipchk** [comment]
长时间未处理，有更多问题请重新提供 issues.
