### ISSUE TITLE
IE 11 problem in Theme switch

### ISSUE THREAD

**Issue by hidon84** [ng-alain/ng-alain#302]
HI GUYS. ^^

When I visit github.site using IE11 :   url :  https://cipchk.github.io/ng-alain/dashboard/v1  
then Theme switch is not working propery . Even I use all of pollyfills.

how can i fix this ? any one help me plz~!

**Comment by cipchk** [comment]
duplicated of [#33](https://github.com/cipchk/delon/pull/33/files).

i will next version fix this.
