### ISSUE TITLE
feat: sync ng-zorro-antd 0.7.0

### ISSUE THREAD

**Issue by cipchk** [ng-alain/ng-alain#304]
ng-alain 是以 ng-zorro-antd 为基础组件库，其 0.7.0 版本将至，ng-alain 也会尽可能快的同步。由于 0.7.0 有一个 BREAKING CHANGES 以及动态主题的实现，ng-alain 可能也会有一部分 BREAKING CHANGES 变更。

另外，ng-alain 将以 `1.0.0` 版本号为开端。

### [WIP] 脚手架变更

- 移除10种主题色，同时发布主题在线编辑器
- 移除实验性字体 `14px` 样式
- 移除 `ng-zorro-antd-extra` 类库（同时不再维护）
- 移除 `ng-tree-antd` 类库（同时不再维护）
- 支持多应用

### [WIP] CSS变更

| 现样式名 | 使用 zorro 组件替代 | 描述
| ---------- | ---------------------- | -----
| `.file-upload` | `nz-upload` | -
| `.list-group` | `nz-list` | -

### [WIP] 其它

- 改善 [ng-zorro snippets](https://marketplace.visualstudio.com/items?itemName=cipchk.ng-zorro-vscode)

### [WIP] 迁移说明

- ng-zorro-antd-extra

### 渴望

同时，欢迎各位提供一些有助于快速开发 Angular 项目的经验，并入 ng-alain。 💯

**Comment by CoderPoet** [comment]
支持自定义主题色了吗？？
