### ISSUE TITLE
路由复用的问题。

### ISSUE THREAD

**Issue by MourinhoLove** [ng-alain/ng-alain#306]
您好
我把Demo里面的路由复用逻辑拷贝到自己的项目里面。在使用的时候出现“ Cannot reattach ActivatedRouteSnapshot created from a different route”这样的错误。可是在Demo里面却是好的。请问一下作者是否知道出现该错误的原因是什么。
谢谢

**Comment by cipchk** [comment]
路由复用过程中存储和还原必须 是同一个路由地址。
