### ISSUE TITLE
ng-alain的修改建议

### ISSUE THREAD

**Issue by yixiangling** [ng-alain/ng-alain#308]
以下仅是个人对ng-alain的建议

1.建议在src/app同级增加src/account模块此模块跟app模块一样，有独立layout，模块主要用于帐号登录、注册、多租户切换选择等未登录状态的功能，以便和app进行区分。
这样能将很多登录的需求隔离出来，以便登录模块清楚的封装更多登录形式，比如微信登录、域帐号登录等等。
这样拆分后将需要在src下增加一个root模块，把src/app/app模块的引导功能移动到此，让app模块只做该模块本身的工作，当有更多application参与进来，比如src/wxapp，src/help都只需要参照src/app即可快速增加更多应用

2.建议从根模块就添加“**-routing.module.ts”，这样可以使得各个模块的路由关系跟目录结构保持一致性，便于后续的修改或直接复用一个独立app，修改也更清楚，直接可以通过目录层次结构就了解这些路由关系。

对1、2的补充说明
我项目的实际场景：平台管理app、商户管理中心app、商户应用中心app、帮助/知识库（免登录），这几个每个都算一个独立应用，相互之间无粘连关系。
现在的ng-alain结构设计也能完成我所说的这些需求，只不过把这些都放在了app模块下，但我遇到的实际需要就是有多个完全独立的app，每个app有独立的菜单结构，因此我认为这几个不算“一个app”而是多个，每个app下都有自己的模块，多个app有共享的部分，比如animation、pipe等我是存放在src/shared模块下。同时这多个app又有共享的一些功能模块。

3.关于acl，建议将acl部分放到启动模板代码中，而不是一个独立库，因为不同项目对于权限检查的方式不一样，后端提供的权限数据也不一样，需要做的判断和跳转也不一样。比如有的地方需要提示没有权限，而有的地方提示没有权限的同时可以提供授权码进行操作，甚至有的地方没有权限会提示切换访问身份。
对于acl当然可以说让后端按照这个框架要求的数据结构返回数据，达到目的，但这似乎就降低了框架的适应性，同时也增加了一些不必要的繁琐性，因此我觉得acl部分可以放在src/shared下，反正acl就是与后台对接的变化点，很难有简单直接的方式提供更高的适应性，更高适应性的acl同时也带来更多更复杂的配置，倒不如直接提供一个基础的实现，就放在启动模板代码里，有什么不同让使用者按需求自己改去，更多的需求直接复制一份改改就行了。

4.关于导航菜单，建议导航菜单通过后端返回的权限数据来做呈现。因为大多数后台系统保存的是权限、角色这类信息，为了做好前后分离，对于前端菜单的组织结构实际上后端系统是不应该关注的，因此后端返回导航菜单结构的方式不够好，后端返回权限数据permission、前端来根据permission呈现对应功能入口会更合适一些。
现在ng-alain已经实现路由守卫的部分data对象中实际已经包含的permission信息，那么菜单项的结构同样也可以直接与之匹配来使用，比如提供这样一个类来记录这个菜单所需的permissionName，在显示菜单的template里调用方法后使用服务来检查是否进行菜单显示即可。
```
export class MenuItem {
    name: string = '';
    permissionName: string = '';
    icon: string = '';
    route: string = '';
    items: MenuItem[];
}
```
最终菜单定义的地方实际上是完整的菜单定义，根据权限来决定显示什么菜单。一套权限，在各个app里呈现各个app不同的菜单，前端在做app拆分跟后端完全无关。
后端关于角色和权限是不同的，现在acl中通过角色来控制实际上需求还是有偏差。

其他.
angular开发门槛不来就不低，很多使用angular都是已经有相当经验的老司机了，而且后端开发者数量也相当多，在使用这类模板的时候或许更在乎的是，启动模板帮我完成了什么，我有不同需求的时候放在哪里实现更合适，启动模板是否能给我一个较清晰灵活的结构或者规则。
对于项目应用的不同需求这些代码反正是要写的，所以我觉得启动模板项目提供一个清晰灵活的结构即可，对于常见的需求有基础的实现即可，做得越多配置越多使用也越复杂，粘连关系也越多越不好替换或更改。

另外附上我暂时看到过做得比较不错的另一个angular启动模板，[https://aspnetboilerplate.com/Templates][1]

希望ng-alain越来越好，感谢 @cipchk 辛勤劳动！^Q^

  [1]: https://aspnetboilerplate.com/Templates

**Comment by cipchk** [comment]
谢谢关注。我理解的是涉及到**多应用**、**标准化**两个话题。就这两个话题我回答你上述的问题。

## 多应用

ng-alain 本身是一个完整的项目脚手架，关于多应用方面有两种选择，一是以应用模块交互，二是以Angular Cli 本身支持多应用开发。

前者灵活性比较高一点，但对于中心化要求非常高；对于非常大项目会这么做例如：阿里去控制台。

后者是基于 Angular Cli 项目，通过配置 `.angular-cli.json` 配置多应用支持，但依然还是涉及到一些中心化的小问题。

## 标准化

ACL 是一个比较标准的访问控制的具体实现，它是一个可选模块，ng-alain 无法保证每个后端都能完整的整合，因此，对于 @delon 模块而言尽可能以一种接口模式，以在确保开发者能使用尽可能少的代码开发符合需求。

## 结论

结合上述两点，我回答你的问题。

首先，关于目录结构的调整其目的是为了多应用，然而多应用的开发，我想会有一个更好的方式，ng-alain 也会在尝试这一方面的支持。

其次，ACL 我相信若是后端也保持一定的标准，应该使用起来会很愉快。当然，@delon/acl 模块若不符合你的要求，你大可不需要使用它；而由你自行开发。
