### ISSUE TITLE
利用@delon/cl构建的项目编译报错

### ISSUE THREAD

**Issue by zf1998** [ng-alain/ng-alain#310]
```
ERROR in Error during template compile of 'DelonModule'
  Function calls are not supported in decorators but 'AdChartsModule' was called.
```
用`ng new -c= #@delon/cli my-app `构建的项目，`ng build --prod --aot`编译报告以上错误

**Comment by cipchk** [comment]
请更新至最新版本 `0.7.0`

**Comment by zf1998** [comment]
谢谢作者，解决了，把这些全部更新到了`0.7.0`，构建默认是`0.6.9`的
<img width="286" alt="2018-03-05 20 15 18" src="https://user-images.githubusercontent.com/28880564/36974676-6f13177c-20b2-11e8-9c74-dd5a36533932.png">
