### ISSUE TITLE
@delon\cli\application\files\package.json 文件中使用版本0.6.0

### ISSUE THREAD

**Issue by xsjkj-com** [ng-alain/ng-alain#312]
https://github.com/cipchk/ng-alain/blob/0b18923ca7e4d6cf5c251ba07a5662971ce46667/package.json#L43
使用ng new -c=@delon/cli my-app生成的项目中package.json文件：@delon/XXX 的版本一直为^0.6.0

**Comment by cipchk** [comment]
https://stackoverflow.com/questions/22343224/whats-the-difference-between-tilde-and-caret-in-package-json
