### ISSUE TITLE
TinymceWidget cannot be used as an entry component

### ISSUE THREAD

**Issue by wuzguo** [ng-alain/ng-alain#318]
最新代码，clone到本地然后执行：

cnpm install

ng serve

然后报错：

![snipaste_20180307_111319](https://user-images.githubusercontent.com/8574644/37071666-92746aee-21f8-11e8-8976-0919fa05d7f0.jpg)

**Comment by cipchk** [comment]
建议使用 `npm i`，cnpm 经常出现这种情况。
