### ISSUE TITLE
思路请教：TokenInterceptor 如何弹窗错误提示窗口？

### ISSUE THREAD

**Issue by dusdong** [ng-alain/ng-alain#32]
## Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ x ] feature request
```
我想在 TokenInterceptor 捕捉到错误时，弹出错误提示窗口。import NzModalService 后，报错：
`Cannot instantiate cyclic dependency! ApplicationRef ("[ERROR ->]"): in NgModule AppModule in ./AppModule@-1:-1`

请问，您在实际项目中是否在 TokenInterceptor 中统一处理错误呢？该如何实现？

### Versions.

 0.1.2-beta.1

**Comment by cipchk** [comment]
循环依赖可以使用 `@Injector` 来解决（如：[token.interceptor.ts](https://github.com/cipchk/ng-alain/blob/master/src/app/core/net/token/token.interceptor.ts#L22)）。另对于http相关的错误处理 ng-alain 的确是在拦截器中统一处理。

**Comment by dusdong** [comment]
对对，用 `@Injector`，thx~
