### ISSUE TITLE
语言切换ReuseTab标题有时没反应，其他地方正常

### ISSUE THREAD

**Issue by jecyhw** [ng-alain/ng-alain#320]
![image](https://user-images.githubusercontent.com/10094084/37200913-243c411c-23c1-11e8-9c2f-2099ee8b47cf.png)

**Comment by jecyhw** [comment]
第一次和第二次切换语言，ReuseTab标题还是不变，第三次以后就好了。https://cipchk.github.io/ng-alain/dashboard/v1

**Comment by cipchk** [comment]
#329
