### ISSUE TITLE
搜索列表（项目）卡片显示错位

### ISSUE THREAD

**Issue by yixiangling** [ng-alain/ng-alain#321]
## Bug 重现链接
[搜索列表（项目）](https://cipchk.github.io/ng-alain/pro/list/cover-card-list)

第一行第二个卡片高度不一致，导致第二行卡片错位

## 重现步骤
窗口可视区域宽度大于1758px时会出现此问题
窗口可视区域宽度在1253px~1200px时会出现此问题

## 环境 
<pre><code>
Windows 10
Chrome 64.0.3282.186
</code></pre>

**Comment by cipchk** [comment]
了解这个情况，但我们无法避免，除非你估计描述只有一行，但你有动态行时总会遇到这种问题。
