### ISSUE TITLE
执行build操作时报错

### ISSUE THREAD

**Issue by HJianfeng** [ng-alain/ng-alain#322]
ERROR in ..\ngx-ueditor\index.ts(11,2): Error during template compile of 'UEditorModule'
  Function calls are not supported in decorators but 'ɵmakeDecorator' was called in 'NgModule'
    'NgModule' calls 'ɵmakeDecorator'.

**Comment by cipchk** [comment]
麻烦提供尽可能多的环境说明。

并按下面两个方法进一步尝试：
- 使用 `ng serve --aot` 看是否有更多错误信息
- 移除 `node_modules` ，并采用 [package-lock.json](https://github.com/cipchk/ng-alain/blob/master/package-lock.json) 这个版本试试。

**Comment by HJianfeng** [comment]
@cipchk 还是报同样的错误，我clone了项目后，cnpm安装完依赖，直接执行build 马上就报这个错误

**Comment by cipchk** [comment]
不建议使用 cnpm ，因为 angular 可能会受其文件链接的关系产生一个奇怪的错误。

**Comment by winpzs** [comment]
建议使用： npm config set registry=https://registry.npm.taobao.org 设置后正常使用npm
不建议使用cnpm
