### ISSUE TITLE
你好，我把@delon/auth升级到最高版本之后，设置SessionStorageStore缓存，但是httpClient没办法发出请求

### ISSUE THREAD

**Issue by zhangyuyuan123** [ng-alain/ng-alain#325]
## Bug Report or Feature Request (mark with an `x`)

<pre><code>
[ ] Bug report -> please search issues before submitting
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Environment

<pre><code>
ng-alain version: X.Y.Z
Angular version: X.Y.Z
Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
</code></pre>

**Comment by cipchk** [comment]
pls reproduce in [stackblitz](https://stackblitz.com/edit/ng-alain-setup)

**Comment by onecorner** [comment]
I also met this problem

**Comment by onecorner** [comment]
Have u got it?

**Comment by pholance** [comment]
@zhangyuyuan123 
初始模板的小bug，当使用delon cli创建模板时，新建的模板中`delon.module.ts`第56行的store初始化代码：
```
{ provide: DA_STORE_TOKEN, useFactory: SessionStorageStore }
```
应为：
```
{ provide: DA_STORE_TOKEN, useClass: SessionStorageStore }
```

**Comment by cipchk** [comment]
`1.0.0` 不存在这种情况，所以关闭它。
