### ISSUE TITLE
reuse-tab temporary page refresh problem.

### ISSUE THREAD

**Issue by Zhouuuuuuuuu** [ng-alain/ng-alain#328]
步骤:
1.打开一个临时页面
2.f5刷新页面
3.点击链接跳转到其他路由

问题：reuse-tab不会改变也不会新增标签。Console报一个err
![qq 20180313103653](https://user-images.githubusercontent.com/29364579/37319550-8792d2da-26aa-11e8-99c4-467dfede8fe3.png)

GIF
![gif](https://user-images.githubusercontent.com/29364579/37319528-664bd536-26aa-11e8-9f8f-5a30494b50eb.gif)

**Comment by cipchk** [comment]
reuse 有许多问题，近期将重构它。
