### ISSUE TITLE
饼图百分比显示错误

### ISSUE THREAD

**Issue by xiaoreign** [ng-alain/ng-alain#331]
![image](https://user-images.githubusercontent.com/20812513/37332213-feeeae54-26e0-11e8-915d-2d235a48d66e.png)
如图所示

**Comment by mysanyue** [comment]
![image](https://user-images.githubusercontent.com/25924148/37633475-85d05a70-2c2d-11e8-881f-f96d5820c19b.png)
这部分有办法去掉吗？

**Comment by cipchk** [comment]
没办法，你可以自己参考实现。 @mysanyue

**Comment by mysanyue** [comment]
@cipchk 好的，谢谢！
