### ISSUE TITLE
SimpleTable的Column能否增加支持跳转，包括url和router

### ISSUE THREAD

**Issue by downlder** [ng-alain/ng-alain#335]
## Bug Report or Feature Request (mark with an `x`)

<pre><code>
[ ] Bug report -> please search issues before submitting
[x] Feature request
[ ] Documentation issue or request
</code></pre>

## What is expected?

表格列表中点击某一行中某一列的内容进行跳转是很常见需求，能否增加该功能？

## Environment

<pre><code>
ng-alain version: X.Y.Z
Angular version: X.Y.Z
Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
</code></pre>

**Comment by cipchk** [comment]
建议使用 button 实现查看功能。
