### ISSUE TITLE
SimpleTable extraParams 参数动态指定

### ISSUE THREAD

**Issue by liweitao92** [ng-alain/ng-alain#336]
## Bug Report or Feature Request (mark with an `x`)

<pre><code>
[X] Bug report -> please search issues before submitting
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Reproduction link
[https://stackblitz.com/edit/ng-alain-setup-cqb7mf?file=app%2Fapp.component.ts](https://stackblitz.com/edit/ng-alain-setup-cqb7mf?file=app%2Fapp.component.ts)
## Steps to reproduce
点击按钮，观察 network 的参数变化
![image](https://user-images.githubusercontent.com/30191996/37391410-108dbae0-27a6-11e8-8071-0f802de84f91.png)
代码:
![image](https://user-images.githubusercontent.com/30191996/37391443-2b9cc380-27a6-11e8-89ec-59873e27958d.png)
此处是通过点击按钮，控制 params 的参数变化
问题:
第一次点击按钮的时候，参数值不会发送变化，在重复点击按钮的时候，参数值才会更新

**Comment by cipchk** [comment]
当然会是如此：

```ts
this.params = {a:2, b:3};
this.sf.load();
```

第一行是向组件传递一个参数为异步行为。
第二行是调用组件内的方法，属性同步行为。

可以将 `load()` 延迟一下调用，例如：

```
setTimeout(() => this.sf.load());
```
