### ISSUE TITLE
这是我报错的问题   望得到解决  万分感谢

### ISSUE THREAD

**Issue by qiuliang1** [ng-alain/ng-alain#339]
ERROR Error: StaticInjectorError(AppModule)[ListComponent -> RandomUserService]: 
  StaticInjectorError(Platform: core)[ListComponent -> RandomUserService]: 
    NullInjectorError: No provider for RandomUserService!

**Comment by cipchk** [comment]
请务必注册服务：

```
providers: [RandomUserService]
```
