### ISSUE TITLE
引入viser-ng库，ng build --prod 错误

### ISSUE THREAD

**Issue by hmukan** [ng-alain/ng-alain#340]
通过git clone 的方式创建项目。ng build 和 ng build --prod都可以。

然后引入viser-ng库，**ng build --prod**的方式构建失败：
引入viser-ng步骤说明：
(npm  install viser-ng --save方式安装)，
在shared.module.ts中加入ViserModule模块：
import { ViserModule } from 'viser-ng';
const THIRDMODULES = [
    CountdownModule,
  //....
    ViserModule
];
在某一个页面加入简单图表。

通过 ng serve -o 和 ng build的方式都可以成功运行和构建项目，页面的图表也是正常工作。

但是ng build --prod方式构建就失败：

（viser项目也有相关issues问题：https://github.com/viserjs/viser/issues/134 
viser的demo项目：https://github.com/linhuiw/viser-ng-demo，
 通过修改viser-ng/src/plugins/Plugin.ts文件后
  public context: PluginContext;
  constructor(context: PluginContext, vcRef: ViewContainerRef) {
      this.context = context;
  }
//。。。
可以ng build --prod成功
）

//错误信息：
ERROR in ./node_modules/viser-ng/src/Chart.ts
Module build failed: Error: D:\wp\gowp\src\blht.com\client\mtor\node_modules\viser-ng\src\Chart.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (D:\wp\gowp\src\blht.com\client\mtor\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:674:23)
    at plugin.done.then (D:\wp\gowp\src\blht.com\client\mtor\node_modules\@ngtools\webpack\src\loader.js:467:39)
    at process._tickCallback (internal/process/next_tick.js:103:7)
ERROR in ./node_modules/viser-ng/src/chartService.ts
Module build failed: Error: D:\wp\gowp\src\blht.com\client\mtor\node_modules\viser-ng\src\chartService.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (D:\wp\gowp\src\blht.com\client\mtor\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:674:23)
    at plugin.done.then (D:\wp\gowp\src\blht.com\client\mtor\node_modules\@ngtools\webpack\src\loader.js:467:39)
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by hmukan** [comment]
viser-ng的https://github.com/viserjs/viser/pull/148 方式修正，在https://github.com/linhuiw/viser-ng-demo项目中验证了ng build --prod的编译成功。
但是在ng-alain的脚手架环境中无法编译成功。还是报错误：
ERROR in ./node_modules/viser-ng/src/Chart.ts
Module build failed: Error: D:\wp\gowp\src\blht.com\client\mtor\node_modules\viser-ng\src\Chart.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.

是否ng-alain的构建脚本差异问题呢？

**Comment by cipchk** [comment]
提示信息非常明确，未找到文件。你再核实一下 viser-ng 的版本信息

**Comment by hmukan** [comment]
viser-ng已经是最新版2.2.2了

**Comment by winpzs** [comment]
是viser-ng 无法通过AOT， 与alain无关

**Comment by hmukan** [comment]
viser-ng的2.2.4版本已经修复改问题。

**Comment by xdonex** [comment]
你好，我也遇到这个问题了，我的viser-ng版本是2.2.4。请问你这个问题最后是如何解决的？

**Comment by NeilQ** [comment]
fyi: [viser-ng打包报错](https://github.com/viserjs/viser/issues/181)
