### ISSUE TITLE
路由复用 clear()方法无效

### ISSUE THREAD

**Issue by Eve-Sama** [ng-alain/ng-alain#341]
```ts
export class AppComponent {

  toIndex() {
        this.log.log('调用了toIndex()');
        this.router.navigate(['/welcome']);
        this.reuseTabService.clear();
    }
}
````
-->

## What is expected?

调用this.reuseTabService.clear()之后,销毁该组件的复用状态

## What is actually happening?

进入[专业测试]页面,输入几个数字
![3](https://user-images.githubusercontent.com/30228406/37500135-bcef674a-2902-11e8-80c0-c3db9819dbd1.png)

点击按钮触发this.reuseTabService.clear()与跳转至首页
![2](https://user-images.githubusercontent.com/30228406/37500047-31f02418-2902-11e8-83f4-3f33979435b9.png)
再次进入[专业测试]页面,发现数字还在,并没有销毁组件.是我理解错了clear的作用还是存在bug?
## Environment

版本是0.7.1
<pre><code>
ng-alain version: X.Y.Z
Angular version: X.Y.Z
Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
</code></pre>

**Comment by cipchk** [comment]
当然，因为复用存储是在路由离开发生的，建议配合 reuse 组件一起使用，可以更好的观察，或者打开 `debug` 模式，可以了解更多细节。

**Comment by winpzs** [comment]
非复用页面不能clear,
不同layout切换这个clear会报错
