### ISSUE TITLE
can not find component of <reuse-tab></reuse-tab>

### ISSUE THREAD

**Issue by wjs0509** [ng-alain/ng-alain#343]
在default.component.html中找不到<reuse-tab></reuse-tab>对应的组件，在哪里可以找到？
<div class="wrapper">
    <div class="router-progress-bar" *ngIf="isFetching"></div>
    <app-header class="header"></app-header>
    <app-sidebar  @class="aside"></app-sidebar>
    <section class="content">
         @<reuse-tab></reuse-tab>
        <router-outlet></router-outlet>
    </section>
</div>

**Comment by cipchk** [comment]
http://ng-alain.com/components/reuse-tab
