### ISSUE TITLE
路由路径有一样路径时，菜单会被默认选中

### ISSUE THREAD

**Issue by liweitao92** [ng-alain/ng-alain#344]
## Bug Report or Feature Request (mark with an `x`)

<pre><code>
[x] Bug report -> please search issues before submitting
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Reproduction link

![ezgif-5-5f8d887dae](https://user-images.githubusercontent.com/30191996/37513959-7688b74a-2941-11e8-9f8b-c78083b97ecd.gif)

估计是我路由这里路径的问题
```ts
const routes: Routes = [
    { path: 'menu', component: MenuComponent },
     //应该是下面两行的问题，都是 group 下面的路由
    { path: 'group/type', component: GroupTypeComponent},
    { path: 'group', component: GroupComponent}
];
```

## What is expected?

希望不会选中上面的菜单

## Environment

<pre><code>
ng-alain version: X.Y.Z
Angular version: X.Y.Z
Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
</code></pre>

**Comment by cipchk** [comment]
选中是由 `routerLinkActive` 机制来决定的，因此请先检查这种情况是否都命中。

**Comment by yunClouds** [comment]
@cipchk 
THANKS FIRST,
关于routerLinkActive建议，如果在Menu中增加配置项，关联 routerLinkActiveOption 中的 exact 配置，以达到根据业务场景自定义是否需要 @liweitao92  这种情况下的效果，那就更好了

**Comment by cipchk** [comment]
@yunClouds 正解，这应该以一种默认的形式存在。
