### ISSUE TITLE
_HttpClient似乎有bug, 绝对路径没有效果

### ISSUE THREAD

**Issue by x-falcon** [ng-alain/ng-alain#345]
ng root 目录是 /static
发送请求，_http.get('/api/get') 浏览器实际发出的是 /static//api/get，带上了/static这个前缀，
不知道这是ng的bug 还是？

**Comment by cipchk** [comment]
请核实自己的配置 [default.interceptor.ts](https://github.com/cipchk/ng-alain/blob/master/src/app/core/net/default.interceptor.ts#L64)

**Comment by x-falcon** [comment]
搞定，谢谢
