### ISSUE TITLE
请问关于 ng-zorro-antd 的问题

### ISSUE THREAD

**Issue by HJianfeng** [ng-alain/ng-alain#347]
如何把 ng-zorro-antd 的字体文件放到本地，因为每次从阿里cdn上下载，速度很慢，而且经常会加载失败

**Comment by cipchk** [comment]
这个问题 0.7.0 已经得到解决，以前的版本只能通过 `NgZorroAntdModule.forRoot()` 重新修改参数，但是依然会先加载 CDN 上的字体。
