### ISSUE TITLE
simple table resReName for more level of response ?

### ISSUE THREAD

**Issue by iwantacook** [ng-alain/ng-alain#348]
Sorry for my poor English ...
Thanks a lot for cipchk and ng-alain !
eg: my response is
 `{
item :{
 list:[
{a:123,b:123},
{a:123,b:123}
],
total:2
}
}
`
How can I add the list and total to resReName ?
`[resReName]="{list: 'item.list',total:'item.total' }"`??

**Comment by cipchk** [comment]
you are right.

**Comment by iwantacook** [comment]
OK，I will try again, thanks!

**Comment by iwantacook** [comment]
My demo is:
`<simple-table [data]="urlLink" [ps]="params.limit" [total]="total" [columns]="columnsnew" [extraParams]="params" [reqReName]="{pi: 'page',ps:'limit' }" [resReName]="{list: 'item.list',total:'item.total' }"></simple-table>`
And the final urlLink is:
 `https://api.3-gd.com/api/v1/optometry/user/list?page=1&limit=10&gu_name=&gu_tel=&gu_adds=&start_time=&end_time=&gu_num=`
But it do not word !
Is there anything wrong?

**Comment by cipchk** [comment]
https://stackblitz.com/edit/ng-alain-setup?file=app%2Fapp.component.ts

**Comment by iwantacook** [comment]
I got it ! 
I create 2 tables , and 1 columns , the first work, and the other one did not .
