### ISSUE TITLE
用get方式发起数据请求时，莫名报错。

### ISSUE THREAD

**Issue by zhengyanghuaer** [ng-alain/ng-alain#351]
用get方式发起数据请求时，报
![image](https://user-images.githubusercontent.com/35128870/37647148-85e25ed0-2c66-11e8-849a-82ac0faa8439.png)，事实上并没有向服务器发起请求。

**Comment by cipchk** [comment]
可能是拦截器提前中断了请求，但给予的数据不符合要求，所以导致这种错误。

**Comment by zhengyanghuaer** [comment]
![image](https://user-images.githubusercontent.com/35128870/37691343-284937cc-2cec-11e8-81f9-8eb1919a9081.png)
我是这样写的，没有传参。还是不明白到底是什么问题呢，大神
