### ISSUE TITLE
使用最新版的@delon创建项目后，发送httpClient请求会报错

### ISSUE THREAD

**Issue by mianxiaoqian** [ng-alain/ng-alain#353]
## Bug Report or Feature Request (mark with an `x`)

<pre><code>
[ ] Bug report -> please search issues before submitting
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Steps to reproduce
 在业务子模块使用HttpClient发送一个请求

## What is expected?
接口请求成功或失败

## What is actually happening?
报错，显示无法加载登录页路由,或者会跳转到登录页，在登录页输入默认的帐号密码后，报错
core.js:1448 ERROR TypeError: Cannot read property 'clear' of null
    at eval (login.component.ts:92)
讲这行代码注释之后，能够正常发送请求

## Environment

<pre><code>
ng-alain version: X.Y.Z
Angular version: X.Y.Z
Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
</code></pre>

**Comment by devcui** [comment]
我也是这样

# Service # 

![tim 20180321144744](https://user-images.githubusercontent.com/26159886/37697334-3e199fb2-2d17-11e8-9ed0-485c534567be.png)

# UserLoginComponent #

![tim 20180321144757](https://user-images.githubusercontent.com/26159886/37697348-53ab3c32-2d17-11e8-94bd-0b27ef2c2c6b.png)

# ERROR #

![tim 20180321144823](https://user-images.githubusercontent.com/26159886/37697354-5d66e8de-2d17-11e8-9f42-2de1e117379f.png)

**Comment by devcui** [comment]
@mianxiaoqian clear the simpleInterceptor at app.modules.ts

**Comment by mianxiaoqian** [comment]
已经将拦截去掉，不会再跳转登录页，谢谢
