### ISSUE TITLE
Not Page Name

### ISSUE THREAD

**Issue by Zhouuuuuuuuu** [ng-alain/ng-alain#354]
自己新增一个登陆页，但是title显示为Not Page Name，只要是不属于menu的路由都是这个情况。这个该怎么处理？
![image](https://user-images.githubusercontent.com/29364579/37697102-d055b1ba-2d15-11e8-8f4d-ff6d24f619e0.png)

**Comment by cipchk** [comment]
http://ng-alain.com/docs/common#TitleService
