### ISSUE TITLE
nz-tree加载dom时mobx报错并阻塞页面渲染

### ISSUE THREAD

**Issue by Zhouuuuuuuuu** [ng-alain/ng-alain#355]
加载页面时控制台会抛出一堆异常，并且页面停止渲染，需要有点击或者其他操作才会继续渲染。
![gif](https://user-images.githubusercontent.com/29364579/37701468-1dc79ff8-2d2a-11e8-841e-b7aad2019c70.gif)

**Comment by Ants24** [comment]
mobx-angular 组件升级到3.0.1版本就没有问题,我刚解决了

**Comment by Zhouuuuuuuuu** [comment]
@Ants24 thanks
