### ISSUE TITLE
form表单使用Validators.compose()验证的问题

### ISSUE THREAD

**Issue by xiaoreign** [ng-alain/ng-alain#356]
[ ] Bug report -> please search issues before submitting
[ ] Feature request
[√ ] Documentation issue or request

如表单需要设置最大值和最小值
如  -1~--5   && 1~5  有2个范围
那么Validators.min()和Validators.max()需要如何设置才能在2个范围内来验证

**Comment by cipchk** [comment]
没有办法，这种情况你只能自定义一个校验规则来符合你特殊需求。
