### ISSUE TITLE
如何才能直接使用mock打印所有的http请求信息呢？

### ISSUE THREAD

**Issue by iwantacook** [ng-alain/ng-alain#357]
在使用0.7.1版本的时候，不论是使用框架原来内置的mock请求，或者是向远程的服务器请求数据，都会有很详细的`HttpRequest`信息打印出来，这样，我能很方便的查找前端和后台的数据交互过程中的问题，但是，在升级到0.8.0之后，mock只能打印本地的请求信息（原框架的请求）。
所以，请问一下，如何才能设置，在配置或改动尽可能小的情况下，把`HttpRequest`信息打印出来呢？

**Comment by cipchk** [comment]
`mock` 只会在匹配的情况下才会打印，否则ｎｅｔｗｒｏｋ可以查看到明细了。
