### ISSUE TITLE
tab标签内部实现导航

### ISSUE THREAD

**Issue by williamwang2015** [ng-alain/ng-alain#359]
通常的crud页面，维护数据的时候通常采用dialog的方式来实现，也有相关的例子:https://cipchk.github.io/ng-alain/#/extras/poi
但是如果表单的内容比较复杂，像这样的https://cipchk.github.io/ng-alain/#/pro/form/advanced-form，
采用dialog的方式，用户体验就不是很好。能否在一个功能打开的页面内部，实现路由的跳转，而不是重新打开新的tab页，内部实现跳转的时候tab页的标题不变！个人尝试了一下子路由，没有达到效果，求解！

**Comment by cipchk** [comment]
不使用路由复用。

有一种方式，你可以试一下，调用 ReuseService 的 `removeUrlBuffer` 并设置当前路由地址。

> 注 `removeUrlBuffer` 是一个私有变量，可以使用 `<any>reuseService['removeUrlBuffer']` 看看。

**Comment by williamwang2015** [comment]
@cipchk 按照你说的方法测试了一下，如下为路由配置代码：
` const routes: Routes = [`
  `{`
  `  path: '', component: IndexComponent,data:{title:'管理首页'},`
   ` children: [`
   `   { path: 'list', component: ListComponent,data:{title:'管理首页',reuse:false} },`
   `   { path: 'form', component: FormComponent,data:{title:'管理首页',reuse:false} }`
  `  ]`
 ` }`

`]`

index组件里面，增加了两个a标签，进行路由的跳转测试：
`<a (click)="gotoForm()">详细</a>`
`<br/>`
`<a (click)="gotoList()">表格</a>`

事件代码如下：
`gotoForm(){`
    `this.reuseSerive['removeUrlBuffer']='trade/form';`
  `  this.router.navigateByUrl("trade/form") `
 ` }`

`  gotoList(){`
  ` this.reuseSerive['removeUrlBuffer']='trade/list';`
  `  this.router.navigateByUrl("trade/list") `
`  }`

经过测试，子路由的title，要和父路由的title一致，才能达到效果。
但是有一个问题，就是我再通过菜单打开新的链接的时候，会关闭这个tab页！如何在这种情况下不关闭呢？要是不关闭就是路由复用了，但是又不在新tab页打开矛盾了！求解！

**Comment by cipchk** [comment]
建议提供一下在线示例。

**Comment by williamwang2015** [comment]
不好意思，在线示例没法提供。仔细想了一下，我的那个需求通过路由来实现有所矛盾，看来只能动态控制界面来实现了！

**Comment by jackywang615** [comment]
这个问题我也遇到了，我之前用的tabs来切换界面，但生成tabs的同时也会把所有tab中的内容都生成。通过子路由来实现的时候会导致reusetab捕获到子路由从而生成新的reusetab项，而不是在原来的上面更新。这个和reusetab设计的初衷是相吻合的。稍后我写个在线示例出来。

**Comment by jackywang615** [comment]
https://stackblitz.com/edit/ng-alain-setup-27u6k9?file=app/app.module.ts

补上在线示例

**Comment by cipchk** [comment]
这个问题是存在的，这是由于路由的判断唯一标准是以URL，因此才会出现以上情况。

其实路由是否被复用是在路由离开时，诚如我前面说过使用 `removeUrlBuffer` 强制不复用当前页，以此于当路由切换成功后依然处在当前页，当然这是一种假像，因为上一页也就无如得以复用。

这问题有点复杂，毕竟若把这种情况也考虑进来的话，需要维护一个非常复杂的路由复用组件树。甚至很难去管理，这一点一开始 `reuse-tab` 就存在。

**Comment by jackywang615** [comment]
@cipchk reusetab在只剩一个标签的情况下任然能被关闭，这个问题还是没解决

**Comment by cipchk** [comment]
没人报告此问题，且没有一个具体可重现的步骤。

**Comment by jackywang615** [comment]
@cipchk 就上面那个示例链接就可以，点出2个tab来，然后关掉剩下一个的情况下最后那个也可以关

**Comment by jackywang615** [comment]
![2018-03-29_9-51-03](https://user-images.githubusercontent.com/9586655/38065545-82784562-3336-11e8-9481-709cda9cfd56.gif)

**Comment by Ants24** [comment]
这个问题我也纠结了好久,今天刚通过动态加载component的方式解决了  通一个页面的增删改查
可以看例子:https://plnkr.co/edit/1aHzVYsRytIuQnkesX6i?p=preview

**Comment by jackywang615** [comment]
@Ants24 我现在也考虑用动态加载来实现了，计划用@angular/cdk 的 portal功能 https://material.angular.io/cdk/portal/overview

**Comment by williamwang2015** [comment]
@cipchk 路由还是应该要复用的，只是顶部的tab标签不切换，参照
https://www.cnblogs.com/lovesangel/p/7853364.html
和http://www.cnblogs.com/lslgg/p/7700888.html 做了一下实现，初步达到了效果，还请多多指点！
https://stackblitz.com/edit/angular-pdr4jv
原理是对于路由对应的标签做了一个归类处理，如果id相同则认为tab标签不切换！

**Comment by cipchk** [comment]
@williamwang2015 建议在每个 page 加上一个动态值或文本框之类的，看是否真的实现了复用。

**Comment by williamwang2015** [comment]
@cipchk 在form那个加了个文本框，初步来看还是实现了复用的！你的实现是不管怎么切换路由，页面dom中其实都是最新的dom内容，离开tab后内容就没有了，所以需要保存前一内容的快照的，要想不跳转思路应该在处理顶部tab栏内容的显示上。另外还有一种方式这是github上别人实现的https://github.com/zjinger/tab-dynamic-componet，
当然这种方式没有了路由，我们以前用easyui的时候就是这种方式

**Comment by cipchk** [comment]
对的，其实可以考虑在路由配置上增加一项，例如： `{ data: { reuseUrl: '/news/list' } } `，当有多个相同时表示不希望增加标签。

**Comment by winpzs** [comment]
这样还有复用的效果吗？ 比如：list页面和add页面在同一个tab打开， 这样的两个页面还复用吗？

另外这个能不能在reuseServcie支持上，比如提供一个方法open({ reuseUrl: '/news/list', url:'/news/add' }, params)

**Comment by jackywang615** [comment]
@cipchk angular routerlink有个参数是skipLocationChange，当值为true时浏览器地址不会发生变化，能否考虑通这个参数来控制是否增加标签。

或者通过一个reusetab的指令的来确定是否新开标签

**Comment by xingkoo** [comment]
为什么一定要把form在tab内打开呢?
在ng1的时候,我就是使用的side方式.前两天写了isuuse推荐引用ng-side组件.
如果需要对内容进行修改或其他操作,使用一个边栏的方式,会是一个更新的操作体验.

**Comment by jackywang615** [comment]
@xingkoo sidebar是个好东西，antd目前没有该组件
@cipchk 有可能在@delon/abc中加入一个sidebar组件么，期待

**Comment by smile2014** [comment]
@williamwang2015  你问题解决没？我也有同样需求

**Comment by ghost** [comment]
发现当reuse-tab里打开两个页面，其中一个路由复用页面和一个非路由复用页面，此时点击叉号关闭允许路由复用的页面，然后再点击菜单打开刚刚关闭的允许路由复用的页面，页面报错。非常抱歉没能提供在线案例，但是这个问题很好重现。@delon/abc版本1.1.1也存在这个问题
![qq 20180621161513](https://user-images.githubusercontent.com/26426756/41709953-1226e7c2-7577-11e8-8345-43132d60c94a.png)
![qq 20180621162534](https://user-images.githubusercontent.com/26426756/41709964-17232db2-7577-11e8-8a75-52c82e0e85f7.png)

![qq 20180621171928](https://user-images.githubusercontent.com/26426756/41710294-e6386342-7577-11e8-8007-865196a476be.png)

**Comment by yangkghjh** [comment]
![2018-09-04 16_09_21](https://user-images.githubusercontent.com/3609399/45018544-f1805780-b05c-11e8-83cb-2acd564a374d.gif)

切换出使用子路由的页面时，reuse-tab 会自动把该标签关闭

```js
  {
    path: 'system',
    component: LayoutDefaultComponent,
    children: [
      {
        path: 'account', component: SystemAccountComponent,
        data: { title: '账户设置', titleI18n: '账户设置', reuse: true },
        children: [
          { path: '', redirectTo: 'setting', pathMatch: 'full' },
          {
            path: 'setting', component: SystemAccountSettingComponent,
            data: { title: '账户设置', titleI18n: '账户设置', reuse: '/system/account' }
          }
        ]
      },
    ]
  },
```

**Comment by cipchk** [comment]
关掉issues，有关更多问题请优先阅读文档，若有相应BUG，请重新提交新 issues。
