### ISSUE TITLE
simple-table 是否可以自定义显示和隐藏当前的列？

### ISSUE THREAD

**Issue by chris030123** [ng-alain/ng-alain#361]
比如table显示了编号、邮箱、电话等等，然后我想通过设置去隐藏电话这一列
![y7 q w c 8d viubov17i h](https://user-images.githubusercontent.com/37833965/37962950-61472676-31ef-11e8-8e6c-b61d7d90fddb.png)

**Comment by cipchk** [comment]
重置赋值给 `columns` 属性一个新的亦可。

**Comment by chris030123** [comment]
您好：
    是否能给个示例，谢谢！



zhangq5152@163.com
 
发件人： 卡色
发送时间： 2018-03-27 19:34
收件人： cipchk/ng-alain
抄送： chris; Author
主题： Re: [cipchk/ng-alain] simple-table 是否可以自定义显示和隐藏当前的列？ (#361)
重置赋值给 columns 属性一个新的亦可。

**Comment by cipchk** [comment]
```ts
column = [
   { title: 'id', index: 'id' }
];

click() {
    this.column = [
        { title: 'name', index: 'name' }
    ];
}
```
