### ISSUE TITLE
https 证书失效

### ISSUE THREAD

**Issue by bobmayuze** [ng-alain/ng-alain#362]
https 证书失效啦＝－＝

**Comment by cipchk** [comment]
谢谢提醒，但不影响使用。

> 这是由于 github pages 并不支持自定义域名证书的设置，所以只能如此了。

**Comment by maplye** [comment]
![secure_error](https://user-images.githubusercontent.com/105527/38120842-f90b2bc8-33fd-11e8-942d-de6dcaf2f33f.png)

I can't brower the change log page on the Chrome.

**Comment by cipchk** [comment]
- click on the “Advanced” link
- click on “Proceed to <website link> (unsafe)” link.
