### ISSUE TITLE
feat: @delon/form 设计指南

### ISSUE THREAD

**Issue by cipchk** [ng-alain/ng-alain#366]
早先 nz-schema-form 的作用比我预期的大非常多，但出于一开始是基于 angular2-schema-form 的原因，出现了一些数据流混乱、性能问题，并且非常难于去修复它们。

于是我决定重新设计并成为 `@delon/form` 的独立类库，它有几个特点：

- [Json Schema Form draft-07](http://json-schema.org/specification.html) 标准实现
- 更快、更符合标准校验库 [ajv](http://epoberezkin.github.io/ajv/)
- 更易用

现 nz-schema-form 的 Schema 包含了 UI 的解释，虽然对于只想利用 json schema form 快速构建表单来说反而更简单，但标准亦是单纯的，我们不应该去破坏它。因此，应该提供一种更智能的解析、以及更合理的强制UI的额外属性。

## JSON Schema Form

标准的 Schema 应该是单纯的，同时应该尽可能以标准来实现构建。

**String**

字符串类型默认应对应 `nz-input`  组件，当指定 `format` 时：

- `email` 应对应 `nz-input` 且类型为 `type="email"`
- `uri` 应对应 `nz-input` 且类型为 `type="url"`
- `data-url` 应对应 `nz-upload` 组件
- `date-time` 应对应 `nz-datepicker` 组件
- `date` 应对应 `nz-datepicker` 组件
- `time` 应对应 `nz-timepicker` 组件

**Boolean**

布尔类型默认应对应 `nz-checkbox` 组件，当 `enum` 时应对应 `select`。

**number** 或 **integer**

数字类型默认应对应 `nz-input-number` 组件，当 `enum` 存在时应该对应 `nz-radio`。同时应该物尽其用标准当中其他参数：

- `minimum` 对应 `min`
- `maximum` 对应 `max`
- `multipleOf` 对应 `step`

## UI

**Schema 与 UI 的关系**

把 Schema 的部分参数应该在 UI 渲染时被体现，它们包括：

- 提醒文本 `title`、`description`
- 状态 `default`、`readOnly`
- 断言 `required`
- 条件式 `if`、`them`、`else`
- 逻辑式 `allOf`、`anyOf`、`oneOf`、`not`

**Schema 与 UI 的界定**

nz-schema-form 的做法是将 `widget` 作为 Schema 的一部分，这两个弊端。一是当 Schema 由后端的另一套系统产生的情况下，很难更好的控制 UI 渲染；二是当若只是单纯用于快速构建前端表单时，额外的参数会显得多余。

因此 `@delon/form` 将以 Schema 为优先，额外增加 `uiSchema` 参数来定制 UI 渲染。

**Comment by CoderPoet** [comment]
sf支持input-group吗？

**Comment by cipchk** [comment]
不支持，一个 `key` 只对应一个数据，对于输入组有多个数据，这个只能自定义了。

**Comment by schsiung** [comment]
ERROR in node_modules/@delon/form/src/src/model/form.property.d.ts(4,38): error TS2305: Module '"D:/chinacscs/Gitlab/platform/FormRender/node_modules/@delon/form/src/src/schema/ui"' has no exported member 'SFUISchemaItemRun'.
node_modules/@delon/form/src/src/schema/ui.d.ts(153,37): error TS2304: Cannot find name 'SFUISchemaItemRun'.
node_modules/@delon/form/src/src/sf-item-wrap.component.d.ts(1,42): error TS6143: Module '..' was resolved to 'D:/chinacscs/Gitlab/platform/FormRender/node_modules/@delon/form/src/index.js', but '--allowJs' is not set.

**Comment by schsiung** [comment]
这个错误又遇到过吗？怎么解决？

**Comment by cswww** [comment]
可以动态更改key吗

**Comment by cswww** [comment]
添加key
