### ISSUE TITLE
如何在ng.ant.design选项卡组件的基础上，封装我自己项目的选项卡

### ISSUE THREAD

**Issue by luohong123** [ng-alain/ng-alain#367]
## Bug Report or Feature Request (mark with an `x`)

<pre><code>
[ ] Bug report -> please search issues before submitting
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Reproduction link

我现在的选项卡个数是有限制的，我不想通过 ng-content `select="[fccontent10]">` 去实现，因为这样的自定义content是有限的，我希望是无限的，请问有什么好的解决方案吗？我的代码如下：
```
<nz-tabset 
        nzAnimated="false"
        [nzType]="fcType" 
        [nzShowPagination]="fcShowPagination"
        [nzSize]="fcSize"
        [nzTabPosition]="fcPosition"
        [(nzSelectedIndex)]="fcSelectedIndex">
        <nz-tab [nzDisabled]="fcTabs[0]?.disabled" [hidden]="fcTabs.length<1">
            <ng-template #nzTabHeading>
               {{fcTabs[0]?.name}}
            </ng-template>
            <div><ng-content select="[fccontent1]"></ng-content></div>
        </nz-tab>
        <nz-tab [nzDisabled]="fcTabs[1]?.disabled" [hidden]="fcTabs.length<2">
            <ng-template #nzTabHeading>
            {{fcTabs[1]?.name}}
            </ng-template>
            <div><ng-content select="[fccontent2]"></ng-content></div>
        </nz-tab>
    </nz-tabset>
```

## Environment

<pre><code>
ng-alain version: X.Y.Z
Angular version: X.Y.Z
Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
</code></pre>

**Comment by cipchk** [comment]
为什么需要 `<ng-content select="[fccontent1]">` 的写法？你可以参考 https://ng.ant.design/#/components/tabs 的最后一个DEMO示例。

**Comment by luohong123** [comment]
因为我想用ant.design的选项卡组件，再次封装成我的选项卡组件，选项卡头部可以循环，内容区里面是自定义的div，内容区里面可能放列表、表单、图表或者其他，又需要用他的选项卡封装成我项目的选项卡标签，不知道如何去循环ng-content
![n u zg_hn n 9 khkm_ 5](https://user-images.githubusercontent.com/20392340/38126781-4685ada2-3425-11e8-8371-ff218492fcb5.png)

**Comment by luohong123** [comment]
我解释一下我的问题，如何把别人的写好的选项卡再次封装成自己的选项卡组件，内容区 不只是放文字，内容区还会嵌入到其他不确定的组件，ng-content无法循环
![m f 7kya7 2w z4fc0 uj](https://user-images.githubusercontent.com/20392340/38127295-1edb5ea2-3428-11e8-887d-5567db12018c.png)

**Comment by cipchk** [comment]
可以利用 TemplateRef 来存储组件对象，最后使用 `<ng-template [ngTemplateOutlet]="">` 动态渲染出来。
