### ISSUE TITLE
为什么快捷菜单重复出现

### ISSUE THREAD

**Issue by onecorner** [ng-alain/ng-alain#369]
这是我的后台返回的菜单结果：
[
      {
        "menuId": 2,
        "text": "主导航",
        "link": null,
        "menuCode": "main_navigation",
        "createTime": 1522252800000,
        "parentMenuId": 1,
        "i18n": "main_navigation",
        "group": true,
        "icon": null,
        "shortcutRoot": false,
        "shortcut": false,
        "reuse": false,
        "hideInBreadcrumb": true,
        "children": [
          {
            "menuId": 3,
            "text": "仪表盘",
            "link": null,
            "menuCode": "dashboard",
            "createTime": 1522252800000,
            "parentMenuId": 2,
            "i18n": "dashboard",
            "group": false,
            "icon": "icon-speedometer",
            "shortcutRoot": false,
            "shortcut": false,
            "reuse": false,
            "hideInBreadcrumb": false,
            "children": [
              {
                "menuId": 4,
                "text": "仪表盘V1",
                "link": "/dashboard/v1",
                "menuCode": "dashboard_v1",
                "createTime": 1522252800000,
                "parentMenuId": 3,
                "i18n": "dashboard_v1",
                "group": false,
                "icon": null,
                "shortcutRoot": false,
                "shortcut": false,
                "reuse": false,
                "hideInBreadcrumb": false,
                "children": []
              },
              {
                "menuId": 5,
                "text": "分析页",
                "link": "/dashboard/analysis",
                "menuCode": "dashboard_analysis",
                "createTime": 1522252800000,
                "parentMenuId": 3,
                "i18n": "dashboard_analysis",
                "group": false,
                "icon": null,
                "shortcutRoot": false,
                "shortcut": false,
                "reuse": false,
                "hideInBreadcrumb": false,
                "children": []
              },
              {
                "menuId": 6,
                "text": "Monitor",
                "link": "/dashboard/monitor",
                "menuCode": "dashboard_monitor",
                "createTime": 1522252800000,
                "parentMenuId": 3,
                "i18n": "dashboard_monitor",
                "group": false,
                "icon": null,
                "shortcutRoot": false,
                "shortcut": false,
                "reuse": false,
                "hideInBreadcrumb": false,
                "children": []
              },
              {
                "menuId": 7,
                "text": "Workplace",
                "link": "/dashboard/workplace",
                "menuCode": "dashboard_workplace",
                "createTime": 1522252800000,
                "parentMenuId": 3,
                "i18n": "dashboard_workplace",
                "group": false,
                "icon": null,
                "shortcutRoot": false,
                "shortcut": false,
                "reuse": false,
                "hideInBreadcrumb": false,
                "children": []
              }
            ]
          },
          {
            "menuId": 8,
            "text": "快捷菜单",
            "link": null,
            "menuCode": "shortcut",
            "createTime": 1522339200000,
            "parentMenuId": 2,
            "i18n": "shortcut",
            "group": false,
            "icon": "icon-rocket",
            "shortcutRoot": true,
            "shortcut": null,
            "reuse": false,
            "hideInBreadcrumb": false,
            "children": []
          },
          {
            "menuId": 9,
            "text": "小部件",
            "link": "/widgets",
            "menuCode": null,
            "createTime": 1522339200000,
            "parentMenuId": 2,
            "i18n": "widgets",
            "group": false,
            "icon": "icon-grid",
            "shortcutRoot": null,
            "shortcut": null,
            "reuse": false,
            "hideInBreadcrumb": false,
            "children": []
          }
        ]
      },
      {
        "menuId": 10,
        "text": "Alain",
        "link": null,
        "menuCode": null,
        "createTime": 1522339200000,
        "parentMenuId": 1,
        "i18n": null,
        "group": true,
        "icon": null,
        "shortcutRoot": null,
        "shortcut": null,
        "reuse": false,
        "hideInBreadcrumb": true,
        "children": [
          {
            "menuId": 11,
            "text": "样式",
            "link": null,
            "menuCode": "style",
            "createTime": 1522339200000,
            "parentMenuId": 10,
            "i18n": "style",
            "group": null,
            "icon": "icon-chemistry",
            "shortcutRoot": null,
            "shortcut": null,
            "reuse": false,
            "hideInBreadcrumb": false,
            "children": [
              {
                "menuId": 12,
                "text": "Typography",
                "link": "/style/typography",
                "menuCode": null,
                "createTime": 1522339200000,
                "parentMenuId": 11,
                "i18n": "typography",
                "group": null,
                "icon": null,
                "shortcutRoot": null,
                "shortcut": true,
                "reuse": false,
                "hideInBreadcrumb": false,
                "children": []
              },
              {
                "menuId": 13,
                "text": "Grid Masonry",
                "link": "/style/gridmasonry",
                "menuCode": null,
                "createTime": 1522339200000,
                "parentMenuId": 11,
                "i18n": "gridmasonry",
                "group": null,
                "icon": null,
                "shortcutRoot": null,
                "shortcut": null,
                "reuse": false,
                "hideInBreadcrumb": false,
                "children": []
              }
            ]
          }
        ]
      },
      {
        "menuId": 14,
        "text": "Pro",
        "link": null,
        "menuCode": "Pro",
        "createTime": 1522339200000,
        "parentMenuId": 1,
        "i18n": "Pro",
        "group": true,
        "icon": null,
        "shortcutRoot": null,
        "shortcut": null,
        "reuse": false,
        "hideInBreadcrumb": true,
        "children": [
          {
            "menuId": 15,
            "text": "Form Page",
            "link": "/pro/form",
            "menuCode": "Form Page",
            "createTime": 1522339200000,
            "parentMenuId": 14,
            "i18n": "form",
            "group": null,
            "icon": null,
            "shortcutRoot": null,
            "shortcut": null,
            "reuse": false,
            "hideInBreadcrumb": true,
            "children": [
              {
                "menuId": 16,
                "text": "Basic Form",
                "link": "/pro/form/basic-form",
                "menuCode": "Basic Form",
                "createTime": 1522339200000,
                "parentMenuId": 15,
                "i18n": "basic-form",
                "group": null,
                "icon": null,
                "shortcutRoot": null,
                "shortcut": true,
                "reuse": false,
                "hideInBreadcrumb": false,
                "children": []
              },
              {
                "menuId": 17,
                "text": "Step Form",
                "link": "/pro/form/step-form",
                "menuCode": "Step Form",
                "createTime": 1522339200000,
                "parentMenuId": 15,
                "i18n": "step-form",
                "group": null,
                "icon": null,
                "shortcutRoot": null,
                "shortcut": null,
                "reuse": false,
                "hideInBreadcrumb": false,
                "children": []
              }
            ]
          },
          {
            "menuId": 18,
            "text": "List",
            "link": null,
            "menuCode": "pro-list",
            "createTime": 1522339200000,
            "parentMenuId": 14,
            "i18n": "pro-list",
            "group": null,
            "icon": "icon-grid",
            "shortcutRoot": null,
            "shortcut": null,
            "reuse": false,
            "hideInBreadcrumb": true,
            "children": [
              {
                "menuId": 19,
                "text": "Table List",
                "link": "/pro/list/table-list",
                "menuCode": "Table List",
                "createTime": 1522339200000,
                "parentMenuId": 18,
                "i18n": "pro-table-list",
                "group": null,
                "icon": null,
                "shortcutRoot": null,
                "shortcut": true,
                "reuse": false,
                "hideInBreadcrumb": false,
                "children": []
              },
              {
                "menuId": 20,
                "text": "Basic List",
                "link": "/pro/list/basic-list",
                "menuCode": "Basic List",
                "createTime": 1522339200000,
                "parentMenuId": 18,
                "i18n": "pro-basic-list",
                "group": null,
                "icon": null,
                "shortcutRoot": null,
                "shortcut": null,
                "reuse": false,
                "hideInBreadcrumb": false,
                "children": []
              },
              {
                "menuId": 21,
                "text": "Card List",
                "link": "/pro/list/card-list",
                "menuCode": "Card List",
                "createTime": 1522339200000,
                "parentMenuId": 18,
                "i18n": "pro-card-list",
                "group": null,
                "icon": null,
                "shortcutRoot": null,
                "shortcut": null,
                "reuse": false,
                "hideInBreadcrumb": false,
                "children": []
              }
            ]
          }
        ]
      }
    ]
，但是渲染快捷菜单的时候出现了两次，这是为什么？
![image](https://user-images.githubusercontent.com/11347680/38132725-dfc68d56-343e-11e8-9fa2-b2fa77cd4bf2.png)

**Comment by cipchk** [comment]
是 `shortcut_root` 而不是 `shortcutRoot`

**Comment by onecorner** [comment]
额，这命名也是挺醉的！应该统一使用驼峰命名法会比较好

**Comment by onecorner** [comment]
还是谢谢！

**Comment by cipchk** [comment]
历史 原因。
