### ISSUE TITLE
$table-header-bg:red;

### ISSUE THREAD

**Issue by fstanwh** [ng-alain/ng-alain#37]
variables-antd.scss文件中的
$table-header-bg:red;

改了这个值，表头的颜色没有改变。

**Comment by cipchk** [comment]
`ng-alain` 不支持 `_antd-style/themes/default.less` 参数覆盖。

**Comment by fstanwh** [comment]
请教，要改表头或其他一些变量的颜色可以怎么修改。
说明上是写修改_alain-custom-variables.scss里更改变量，但没有文档不清楚哪些变量可以修改。

**Comment by cipchk** [comment]
[_alain-custom-variables.less](https://github.com/cipchk/ng-alain/blob/master/src/styles/_alain-custom-variables.less) 仅限于对 [variables.less](https://github.com/cipchk/ng-alain/blob/master/src/styles/alain/app/variables.less) 的覆盖。

PS：当前对 `ng-zorro-antd` 组件样式的覆盖是一个实验性功能，且没有对 `nz-table` 有什么样式的覆盖（包括：表头颜色），当然你很容易做到这一点，要以参考 [theme.less](https://github.com/cipchk/ng-alain/blob/master/src/styles/alain/themes/theme.less#L72) 的按钮或其他做法。
