### ISSUE TITLE
关于simpetable设置当前分页的问题

### ISSUE THREAD

**Issue by onecorner** [ng-alain/ng-alain#370]
<simple-table #st [columns]="columns"
                  [data]="data"
                  [loading]="loading"
                  [pi]="currentPage"
                  [total]="page.total"
                  [showTotal]="true"
                  (checkboxChange)="checkboxChange($event)"
                  (change)="change($event)"
                  (filterChange)="getData()">
        <ng-template st-row="status" let-i>
            <nz-badge [nzStatus]="i.statusType" [nzText]="i.statusText"></nz-badge>
        </ng-template>
    </simple-table>
这是我HTML的代码，可以看到已经设置了pi，返回之后设置了 this.http.post('/api/auth/user/list', {pageNum: this.page.pageNum, pageSize: this.page.pageSize}).pipe(
            catchError((error) => {
                console.log(error);
                return [error];
            }),
            tap(() => this.loading = false)
        ).subscribe(res => {
            if (res && res.result) {
                const page = res.result;
                console.log(page);
                this.data = res.result.list;
                this.page.pageNum = page.pageNum;
                this.page.total = page.total;
                this.page.currentPage = page.pageNum;
                console.log(this.page.currentPage);
                this.currentPage = page.pageNum; //当前页
            }

        });
但是当前页却仍然不起作用，这是为什么？当前选中的总是第一页，可以确定的是返回来的后台数据绝对不是1.

**Comment by cipchk** [comment]
请通过 https://stackblitz.com/edit/ng-alain-setup 重现。

**Comment by onecorner** [comment]
额，貌似必须一次性先把数据加载出来，才能点击下一页，否则，通过change事件，来实现按页点击获取数据的时候的时候，当前选中也总是第一页，而不是我点击页码。
![image](https://user-images.githubusercontent.com/11347680/38286628-f2442566-37f8-11e8-9355-2d1c859f2ff0.png)
你看我这里面是点击第2页然后去通过change事件发送请求去后台获取到数据，但是选中页码还是第一页。

**Comment by cipchk** [comment]
请通过 https://stackblitz.com/edit/ng-alain-setup 重现。
请通过 https://stackblitz.com/edit/ng-alain-setup 重现。
请通过 https://stackblitz.com/edit/ng-alain-setup 重现。

**Comment by onecorner** [comment]
恩，重现了，你可以看看https://stackblitz.com/edit/ng-alain-setup-a3pdgv

**Comment by cipchk** [comment]
请描述，当前重现的步骤？目前状态的什么样？你期望达到什么样的效果？

**Comment by onecorner** [comment]
期望达到的效果，点击页码的时候能处于选中状态，比如点击第2页，加载第2页的数据，同时当前选中页码也应该是第2页。
目前的问题：可以加载对应页码的数据，但是页码无法处于选中状态，选中的总是第一页。

**Comment by cipchk** [comment]
有点不太懂你的意思，但是你每一次都切换分页都重新获取新的 `data`，自然结果是从第一页开始计数了。

**Comment by onecorner** [comment]
来，demo里面的做法是一次性把一百条数据取出来，然后通过simpledata实现分页，每页10条这样，如果照他这样来做，是没有bug的，但是不合理，所以我的做法是通过点击页码的时候去后台加载数据，然后将获取到的数据重新赋值给data，但是这样就有问题了，理论上来说应该是点击第2页的时候，选中的也是第2页才对，但是无论我怎么弄，他选中的都是第一页，这就是我一直在追问的问题。

**Comment by cipchk** [comment]
此设计不会有什么改变，`data` 本身支持 url 参数，上述的需求完全可以直接使用 `url` 写法。

**Comment by hesmile** [comment]
解决方案：
1、声明组建
```
@ViewChild('st') 
 st: SimpleTableComponent;
```
2、http请求数据
```
this.http.post(_url, this.query).subscribe((pv: any) => {
            this.pv = pv;
            //在数据请求之后对st的pi属性做一个延迟赋值即可
            setTimeout(() => {
                this.st.pi = this.pv.pageNo;
            }, 1);
 })；
```

**Comment by qiuziz** [comment]
按@hesmile 的方法无效。

我的解决方案，是直接禁用掉前端分页
`
  page: STPage = {
    front: false
  }
`

然后在请求接口返回数据，设置
`
[total]="total"
`
（这个需要后端支持返回总条数字段）

在change里
`
 if (e.type === 'pi') {
      this.pageNum =  e.pi;
      this.getUserList(this.pageNum);
    }
`
这样页码会根据后端返回的总条数显示，如果11条数据，会显示1和2两个页码

**Comment by Criske7** [comment]
@qiuziz 麻烦问一下，在哪里配置禁用掉前端分页，我是在simple-table里直接用的属性frontPagination=false，但是还是没有解决这个问题。

**Comment by qiuziz** [comment]
@Criske7 https://ng-alain.com/components/table/zh#STPage
