### ISSUE TITLE
开发中取消热加载

### ISSUE THREAD

**Issue by Mrfujianfei** [ng-alain/ng-alain#371]
你好，我要怎么在开发过程中取消热加载呢？在开发的时候代码变动它会自动去重新编译，而我希望的是在我按了ctrl+s之后它再去编译。谢谢

**Comment by cipchk** [comment]
不是一直都只在保存动作发生时才会编译吗？我不明白你所指的热加载 是什么？

**Comment by Veyhunk** [comment]
你可能开启了文件自动保存功能，不然是不会重新加载的

**Comment by cipchk** [comment]
- vscode 有自动保存
- `tsconfig.json` 可能也有相关配置

**Comment by Mrfujianfei** [comment]
非常感谢，就是开了自动保存，感谢。
