### ISSUE TITLE
搜索列表快速切换后outlet无法显示相应的页面

### ISSUE THREAD

**Issue by devcui** [ng-alain/ng-alain#373]
![tim 20180404093318](https://user-images.githubusercontent.com/26159886/38283904-3b230cb0-37eb-11e8-9f52-9c5ca9883cfe.png)

这个地方非常快的切换文章->应用->项目,会有问题

**Comment by cipchk** [comment]
无效ISSUES，请提交一个人类看得懂的。再次感谢关注!
