### ISSUE TITLE
reusetab 多次点击开启/关闭tab操作导致reusetab列表消失

### ISSUE THREAD

**Issue by lxm23** [ng-alain/ng-alain#376]
重新步骤:
1  reusetab打开任意两个tab: tab1, tab2. 对它们分别点击一次;
2 关闭tab1并再次打开它.
3 关闭tab2
![qq20180407-173635](https://user-images.githubusercontent.com/8690938/38453691-5c608f58-3a8c-11e8-9dc9-08c429e7cd1d.gif)

**Comment by cipchk** [comment]
demo 由于发布原因倒置版本略低，已重新发布。
