### ISSUE TITLE
the "pageSizeOptions" inAPI should be changed to "pageSizeSelectorValues"

### ISSUE THREAD

**Issue by Miss-violet** [ng-alain/ng-alain#377]
## Bug Report or Feature Request

The parmas "pageSizeOptions" seems is not exist , when I try to use it to change the pageSize Options , the browser gave me a error , but "pageSizeSelectorValues" works !!!

## What is expected?

use "pageSizeOptions" to change the pageSize Options

## What is actually happening?

the browser hints mistake

<pre><code>
ng-alain version: 0.7.1
Angular version: 5.0.0
Browser:
- Chrome (desktop) version 58.0.3029.110
</code></pre>

**Comment by cipchk** [comment]
ng-alain.com currently at version `1.0.0-beta`, i will publish `0.8.x` version document.
