### ISSUE TITLE
simpe table 表格删除数据之后，如何reload表格数据？

### ISSUE THREAD

**Issue by onecorner** [ng-alain/ng-alain#379]
我是通过url的方式来获取数据的，但是发现在删除一条记录之后，无法去reload，另外说明，st.load()在这里不适用。

**Comment by cipchk** [comment]
http://ng-alain.com/components/simple-table#API

**Comment by xzedx** [comment]
现在貌似不支持删除+reload，回调和 'reload' 只能二选一

**Comment by cipchk** [comment]
的确，会有一个小**破坏变更**。

**Comment by xzedx** [comment]
看了下源码，可以通过第三个参数this调用load方法来实现
``` typescript
    click: (item: any, modal, _t) => {
        this.http.post('/mock/delete', {id: item.id}).subscribe(res => {
            this.message.info(`删除 [${item.id}] 成功`)
            _t.load()   // <--
        })
    }
```

**Comment by cipchk** [comment]
是的，不过目前 `simple-table` 的方法有些不明确。我会更变为：

- `reload` 表示刷新当前页
- `load` 表示刷新指定页
- `reset` 表示重置

同时，`Button` 配置，会有一个破坏变更：

- click 支持 `reload`、`load`、`function` 三种，前两种等价上述
