### ISSUE TITLE
请问如何让SimpleTableColumn默认选中？

### ISSUE THREAD

**Issue by onecorner** [ng-alain/ng-alain#382]

**Comment by cipchk** [comment]
请参考 http://ng-alain.com/components/simple-table 的 SimpleTableData 节点。

**Comment by onecorner** [comment]
但是问题是通过preDataChange时间去捕获数据的时候，完全不起作用，甚至该事件完全没有触发。

**Comment by cipchk** [comment]
麻烦提供一个在线重现示例。

**Comment by onecorner** [comment]
https://stackblitz.com/edit/ng-alain-setup-a3pdgv?file=app%2Fapp.component.html

**Comment by cipchk** [comment]
麻烦提供一个有效的重现示例，并说明重现步骤，以及期望。

**Comment by onecorner** [comment]
你那边无法打开吗？还是什么意思？
我的目的是要回显数据的时候，让一些行处于选中状态，根据你之前的提示，通过SimpleTableData可以做到，所以我现在要捕获SimpleTableData，根据API的说明，通过preDataChange()事件可以拿到这些数据，所以我在simpleTable里面添加了该事件，但是问题是该事件完全没有触发（我在该事件里面添加了打印日志，没有打印，理论上来说，应该是要打印的）

**Comment by onecorner** [comment]
谢谢，我知道了

**Comment by xingkoo** [comment]
这个是什么问题呢？写出来参考一下。
