### ISSUE TITLE
请问有nz-tree的demo吗？

### ISSUE THREAD

**Issue by onecorner** [ng-alain/ng-alain#383]
网上搜了很多demo，但是不知道是不是版本的问题，还是什么原因，我这边用的还是有很多问题，现在在用的ng-alain是最新的，直接就可以使用tree的，但是一些配置参数看不到说明

**Comment by cipchk** [comment]
https://ng.ant.design/version/0.7.x/components/tree/zh

**Comment by onecorner** [comment]
好的，谢谢
