### ISSUE TITLE
simple-table 服务器分页问题

### ISSUE THREAD

**Issue by wheather** [ng-alain/ng-alain#385]
<simple-table #st [columns]="columns" [loading]="loading"
                  (checkboxChange)="checkboxChange($event)" [data]="data.list"
                  [total]="data.totalCount"
                  [pi]="data.page"
                  [showQuickJumper] = "true"
                  [pageSizeOptions] = "[10,20,30,40,50]"
                  [showSizeChanger] = "true"
                  [isPageIndexReset] = "true"
                  [toTopInChange] = "true"
                  [showPagination] = "true"
                  (change)="changePage($event)">
        <ng-template st-row="status" let-i>
            <nz-badge [nzStatus]="i.statusType" [nzText]="i.statusText"></nz-badge>
        </ng-template>
    </simple-table>

问下为什么每次请求服务器后 pi指定的当前分页 分页栏都是第一条呢

**Comment by cipchk** [comment]
#370

没有任何理由需要这样子用！

**Comment by selegiline** [comment]
可能例子让大家产生误会了，有的其他框架的逻辑就是监听排序和分页器的事件然后替换data，angular material就是这样，然后看见 （change）（sortChange）就误以为是用来拿新数据的。

**Comment by 007katoo** [comment]
我之前遇到和看到过这个问题，把 [data]="data.list"改成[data]="url",然后把(change)="changePage($event)"里的方法changePage()修改成更新url即可；
注意，simpletable中的count属性最终以返回数据里的count为准；

**Comment by hesmile** [comment]
已解决：[点击查看](https://github.com/cipchk/ng-alain/issues/370)

**Comment by hesmile** [comment]
已解决：https://github.com/cipchk/ng-alain/issues/370

**Comment by lc-01010** [comment]
默认自动附加 pi、ps 至URL
-- | --
怎么将这个放到reqBody里面不要放url后面？
