### ISSUE TITLE
ant.design 升级工具缺陷

### ISSUE THREAD

**Issue by baiyunchen** [ng-alain/ng-alain#390]
https://cipchk.github.io/delon/6to7
生成的Input标签如下：
`<input style="width: 100%;" [(ngModel)]="itemInfo.QualityInspectionPercent" nz-input placeholder></input>`
这样的Input标签Angular不认~
应该生成：
`<input style="width: 100%;" [(ngModel)]="itemInfo.QualityInspectionPercent" nz-input placeholder/>`

另外，遇到HTML中的注释，程序就挂掉了

**Comment by baiyunchen** [comment]
升级了一半发现，ant.design 0.7日期控件还没好~~蜜汁尴尬

**Comment by cipchk** [comment]
haha^

**Comment by baiyunchen** [comment]
另外，工具能不能帮忙支持下table的升级，table的变化有点大~
还有image标签，br标签，也存在和input标签类似的问题

**Comment by cipchk** [comment]
可以明确以下的转换是正常的：

```html
    <nz-input [(ngModel)]="inputValue" [nzPlaceHolder]="'Basic usage'" (ngModelChange)="_console($event)"></nz-input>
    <p>{{inputValue}}</p>
```

transfered:

```html
<input [(ngModel)]="inputValue" (ngModelChange)="_console($event)" nz-input [placeholder]="'Basic usage'">
<p>{{inputValue}}</p>
```

若有其他问题请提供更明确的信息。
