### ISSUE TITLE
升级到1.0之后，控件变得非常大

### ISSUE THREAD

**Issue by baiyunchen** [ng-alain/ng-alain#391]
原来的效果：
![image](https://user-images.githubusercontent.com/10071911/38692864-b4f22d32-3eb7-11e8-8a50-7b465c30ee63.png)

新的效果：
![image](https://user-images.githubusercontent.com/10071911/38692819-91d63280-3eb7-11e8-88aa-91ad38cd2eeb.png)

**Comment by cipchk** [comment]
ng-zorro-antd 将所有字号同步新一层级，因此若以前带有 `nzSize="large"` 移除即可。
