### ISSUE TITLE
npm run build: Function calls are not supported in decorators but 'AdChartsModule' was called

### ISSUE THREAD

**Issue by OffieCao** [ng-alain/ng-alain#392]
## Steps to reproduce
**1. download code v0.6.7 from github
![oo4m c0dlpcds06izmyvq](https://user-images.githubusercontent.com/15085021/38800893-ff482e96-419a-11e8-9e04-20315441e831.png)
2. npm install
3. npm run build**

## Bug Report or Feature Request (mark with an `x`)

<pre><code>
D:\Project\ng-alain-0.6.7\ng-alain-0.6.7>npm run build

> ng-alain@0.6.7 build D:\Project\ng-alain-0.6.7\ng-alain-0.6.7
> ng build --prod --build-optimizer

Date: 2018-04-16T09:08:50.989Z
Hash: 0610547472ebb060a63d
Time: 13985ms
chunk {scripts} scripts.23b11124f0323868da65.bundle.js (scripts) 964 kB [initial] [rendered]
chunk {0} styles.c2d0fc7faf54e32fa78e.bundle.css (styles) 422 kB [initial] [rendered]
chunk {1} polyfills.997d8cc03812de50ae67.bundle.js (polyfills) 84 bytes [initial] [rendered]
chunk {2} main.ee32620ecd1edff94184.bundle.js (main) 84 bytes [initial] [rendered]
chunk {3} inline.318b50c57b4eba3d437b.bundle.js (inline) 796 bytes [entry] [rendered]

ERROR in Error during template compile of 'DelonModule'
  Function calls are not supported in decorators but 'AdChartsModule' was called.

npm ERR! Windows_NT 10.0.16299
npm ERR! argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! ng-alain@0.6.7 build: `ng build --prod --build-optimizer`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ng-alain@0.6.7 build script 'ng build --prod --build-optimizer'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ng-alain package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ng build --prod --build-optimizer
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ng-alain
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ng-alain
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Project\ng-alain-0.6.7\ng-alain-0.6.7\npm-debug.log
</code></pre>

![image](https://user-images.githubusercontent.com/15085021/38800691-7df486be-419a-11e8-977a-f466a52da7ae.png)

## Environment

<pre><code>
ng-alain version: 0.6.7
Angular version: 5.0.0
node: 6.10.2
npm: 3.10.10
</code></pre>

**package.json**
<pre><code>
{
  "name": "ng-alain",
  "version": "0.6.7",
  "description": "ng-zorro-antd admin panel front-end framework",
  "author": "cipchk",
  "homepage": "https://cipchk.github.io/ng-alain/",
  "bugs": {
    "url": "https://github.com/cipchk/ng-alain/issues"
  },
  "engines": {
    "node": ">= 4.2.1",
    "npm": ">= 3"
  },
  "license": "MIT",
  "scripts": {
    "precommit": "npm run lint-staged",
    "ng": "ng",
    "start": "ng serve -o",
    "serve:hmr": "ng serve -o --hmr -e=hmr",
    "build": "ng build --prod --build-optimizer",
    "analyze": "ng build --prod --build-optimizer --stats-json",
    "lint": "run-s lint:ts lint:style",
    "lint:ts": "ng lint",
    "lint:style": "stylelint \"{src}/**/*.less\" --syntax less",
    "lint-staged": "lint-staged",
    "e2e": "ng e2e",
    "test": "ng test -sr -sm=false",
    "test-coverage": "ng test -sr -cc -sm=false"
  },
  "dependencies": {
    "@angular/animations": "^5.0.0",
    "@angular/common": "^5.0.0",
    "@angular/compiler": "^5.0.0",
    "@angular/core": "^5.0.0",
    "@angular/forms": "^5.0.0",
    "@angular/http": "^5.0.0",
    "@angular/platform-browser": "^5.0.0",
    "@angular/platform-browser-dynamic": "^5.0.0",
    "@angular/router": "^5.0.0",
    "@antv/data-set": "^0.8.3",
    "@antv/g2": "^3.0.1",
    "@antv/g2-plugin-slider": "^2.0.0",
    "@delon/abc": "^0.6.5",
    "@delon/acl": "^0.6.5",
    "@delon/auth": "^0.6.5",
    "@delon/cache": "^0.6.5",
    "@delon/mock": "^0.6.5",
    "@delon/theme": "^0.6.5",
    "@ngx-translate/core": "^9.0.0",
    "@ngx-translate/http-loader": "^2.0.0",
    "angular-baidu-maps": "^1.0.1",
    "angular-qq-maps": "^1.0.1",
    "angular-split": "^1.0.0-rc.0",
    "angular-tree-component": "^7.0.1",
    "core-js": "^2.5.1",
    "file-saver": "^1.3.3",
    "font-awesome": "^4.7.0",
    "moment": "^2.19.3",
    "ng-clipboard-antd": "^2.0.1",
    "ng-tree-antd": "^2.2.2",
    "ng-zorro-antd": "^0.6.5",
    "ng-zorro-antd-extra": "^1.1.6",
    "ng2-dnd": "^5.0.0",
    "ng2-img-cropper": "^0.9.0",
    "ngx-color-picker": "^5.0.0",
    "ngx-countdown": "^2.0.0",
    "ngx-tinymce": "^1.0.1",
    "ngx-ueditor": "^1.1.0",
    "nz-schema-form": "^0.0.1",
    "rxjs": "^5.5.5",
    "screenfull": "^3.3.1",
    "simple-line-icons": "^2.4.1",
    "sweetalert2": "^7.0.0",
    "weather-icons": "^1.3.2",
    "zone.js": "^0.8.18"
  },
  "devDependencies": {
    "@angular/cli": "^1.6.2",
    "@angular/compiler-cli": "^5.0.0",
    "@angular/language-service": "^5.0.0",
    "@angularclass/hmr": "^2.1.3",
    "@angularclass/hmr-loader": "^3.0.4",
    "@delon/cli": "^0.6.4",
    "@types/jasmine": "~2.6.0",
    "@types/jasminewd2": "~2.0.3",
    "@types/jszip": "^3.1.2",
    "@types/mockjs": "^1.0.0",
    "@types/node": "~6.0.60",
    "@types/z-schema": "^3.16.32",
    "codecov": "^3.0.0",
    "codelyzer": "~4.0.1",
    "jasmine-core": "~2.8.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~1.7.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.3.0",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "karma-remap-istanbul": "^0.6.0",
    "karma-sauce-launcher": "^1.2.0",
    "lint-staged": "^5.0.0",
    "mockjs": "^1.0.1-beta3",
    "npm-run-all": "^4.1.1",
    "protractor": "~5.1.2",
    "stylelint": "^8.2.0",
    "stylelint-config-standard": "^17.0.0",
    "ts-node": "~3.2.0",
    "tslint": "~5.7.0",
    "typescript": "~2.6.0",
    "webpack-bundle-analyzer": "^2.9.0",
    "xlsx": "^0.11.16"
  },
  "lint-staged": {
    "src/**/*.ts": "lint:ts",
    "src/**/*.less": "lint:style"
  }
}
</code></pre>

**Comment by cipchk** [comment]
- remove `node_modules` & `package.json` & `package-lock.json`
- running `npm i` or `yarn`

**Comment by OffieCao** [comment]
It's solved! We need to update package.json!

    "@delon/abc": "^0.7.0",
    "@delon/acl": "^0.7.0",
    "@delon/auth": "^0.7.0",
    "@delon/cache": "^0.7.0",
    "@delon/mock": "^0.7.0",
    "@delon/theme": "^0.7.0",

use npm install, do not use cnpm install!
