### ISSUE TITLE
关于图表的问题

### ISSUE THREAD

**Issue by qiuliang1** [ng-alain/ng-alain#393]
1.首先这是我的报错；
![image](https://user-images.githubusercontent.com/35951262/38844592-bef2c310-4226-11e8-8a9a-2e76e471b9c8.png)
2.我想要自己写一个图表，引入了这个模块，但是里面没有.d.ts
![image](https://user-images.githubusercontent.com/35951262/38844618-dda2efc4-4226-11e8-9b6d-646241acd315.png)
所以我想请问，我该如何引入这个模块，求解答，谢谢

**Comment by cipchk** [comment]
https://github.com/cipchk/ng-alain/blob/master/src/typings.d.ts#L16
