### ISSUE TITLE
如何使用本地iconfont资源

### ISSUE THREAD

**Issue by assertyang** [ng-alain/ng-alain#394]
应用位于内网，由于ng-zorro组件使用了外网alicdn的源，导致应用连接外网失败界面部分图表丢失
已经参照ng zorro的这个方式在shared module中新增了ngzorroantdmodule 并且引入了外部字体文件，可是编译报错，无法替换，请问是否有可行方式，谢谢

本地部署
图标默认托管在 iconfont.cn，默认公网可访问。如需本地部署，可以下载iconfont文件,解压后放在 assets/fonts或其他公网可访问的文件夹下

NgZorroAntdModule.forRoot() 方法能够接受一个可选的配置对象，用于引入外部的字体文件，类型为 { extraFontName: string, extraFontUrl: string }。

**Comment by cipchk** [comment]
也可以使用强制覆盖 `font-family:anticon;` 字体，这部分属于CSS问题，具体做法可以自行百度。

**Comment by jiangxiaolin1995** [comment]
能不能说一下你是怎么实现的

**Comment by succulen-plants** [comment]
能不能提供一个例子， 试了几个方法没有成功

**Comment by cipchk** [comment]
至 8.x 以后 ng-zorro 已经使用的是 svg，有关这方面信息，请参考 https://ng.ant.design/components/icon/zh#svg-%E5%9B%BE%E6%A0%87
