### ISSUE TITLE
Please add a @NgModule annotation.

### ISSUE THREAD

**Issue by wuyunfeng8** [ng-alain/ng-alain#395]
## Bug Report or Feature Request (mark with an `x`)

<pre><code>
[x] Bug report -> please search issues before submitting
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is actually happening?

npm run build

报错

Unexpected value 'AdSimpleTableModule in /Users/wuyunfeng/work/resume-manage-system/node_modules/@delon/abc/abc.d.ts' imported by the module 'ResumeModule in /Users/wuyunfeng/work/resume-manage-system/modules/alain/resume/src/resume.module.ts'. Please add a @NgModule annotation.

## Environment

<pre><code>
ng-alain version: X.Y.Z
Angular version: X.Y.Z
Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
</code></pre>

**Comment by cipchk** [comment]
麻烦提供更多有利于判断的信息。
