### ISSUE TITLE
升级到最新版本报错

### ISSUE THREAD

**Issue by zhengyanghuaer** [ng-alain/ng-alain#397]
ERROR in ./node_modules/_raw-loader@0.5.1@raw-loader!./node_modules/_postcss-loader@2.1.1@postcss-loader/lib??embedded!./node_modules/_less-loader@4.1.0@less-loader/dist/cjs.js??ref--9-3!./src/styles.less
Module build failed:

// antd
@import "../../../ng-zorro-antd/src/style/index.less";

**Comment by zhengyanghuaer** [comment]
最新版本：
     "@delon/abc": "^1.0.0-beta.6",
      "@delon/acl": "^1.0.0-beta.6",
      "@delon/auth": "^1.0.0-beta.6",
      "@delon/cache": "^1.0.0-beta.6",
      "@delon/mock": "^1.0.0-beta.6",
      "@delon/theme": "^1.0.0-beta.6"

**Comment by zhengyanghuaer** [comment]
最新版本
  "@delon/abc": "^1.0.0-beta.6",
      "@delon/acl": "^1.0.0-beta.6",
      "@delon/auth": "^1.0.0-beta.6",
      "@delon/cache": "^1.0.0-beta.6",
      "@delon/mock": "^1.0.0-beta.6",
      "@delon/theme": "^1.0.0-beta.6",

**Comment by zhengyanghuaer** [comment]
![bnlb3tgf8 9d1h gej5vh4](https://user-images.githubusercontent.com/35128870/39119752-40018430-471f-11e8-81b8-ebb8389f255d.png)

**Comment by cipchk** [comment]
不要使用 cnpm，使用 npm 或 yarn

**Comment by zhengyanghuaer** [comment]
![image](https://user-images.githubusercontent.com/35128870/39160970-f187571c-47a0-11e8-8ae8-10bc704dd6bb.png) 我是在原来的版本基础上升级的，还是这样

**Comment by cipchk** [comment]
https://ng-alain.com/docs/changelog-81

**Comment by kenttanl** [comment]
@zhengyanghuaer 请问你有解决掉这个问题吗？

**Comment by cipchk** [comment]
@kenttanl https://ng-alain.com/docs/upgrade-v2

**Comment by kenttanl** [comment]
@cipchk 谢谢了，已经从1.x版本更新为最新的版本，只是更新后，`<section class="alain-default__content"></scction>`内容区域没有被显示出来，对比demo样式发现没什么区别，后来手动添加了 `html, body, app-root width: 100%` 样式后就可以了。再次感谢
