### ISSUE TITLE
After hide the simple-table component, when you show it again. the simple-table component will have only one visible column left !!!

### ISSUE THREAD

**Issue by 007katoo** [ng-alain/ng-alain#398]
stackblitz: https://stackblitz.com/edit/ng-alain-setup-bwp75w

the question is after switch the visibility of the simple-table component, the st will miss the data columns.
plz help solve this problem, thanks.

**Before hide:**
![image](https://user-images.githubusercontent.com/15177304/39174000-f9057a86-47d8-11e8-9338-1bf5094b306c.png)

**After hide, show again:**
![image](https://user-images.githubusercontent.com/15177304/39174026-0da32812-47d9-11e8-9791-61845f70764d.png)

**Comment by cipchk** [comment]
可能是 `columns` 被污染了，暂时先使用 `[hidden]` 解决。

**Comment by cipchk** [comment]
The `columns` data polluted in simple table, you can using `[hidden]` fixed this, like this:

```html
<simple-table [hidden]="!show"></simple-table>
```

In fact, this is bug, but won't fix issues. Because `columns` includes an object (like: `function`).

Muse be deep copy `columns` in simple-table, I'll leave use with that question.

**Comment by 007katoo** [comment]
thank you, but i have another question, how do you find the simple-table have the attribute 'hidden'?
i don't know that before you told me...

**Comment by cipchk** [comment]
The `hidden` is HTML5 attribute, You can as an alternative, use this:

```html
<simple-table [style.display]="show ? 'block' : 'node'"></simple-table>
```
