### ISSUE TITLE
创建项目失败

### ISSUE THREAD

**Issue by wanbolantian** [ng-alain/ng-alain#399]
1.按https://ng-alain.com/docs/cli 步骤安装@delon/cli，安装过程报警，如图warn所示,但所需要的模块是已经安装的了
2.通过ng new -c=@delon/cli my-app 创建项目，报图中红色字体部分错误
3.如果通过 ng -new 建立项目是可以成功的
![wx20180424-185254](https://user-images.githubusercontent.com/20452742/39182880-d33db27e-47f0-11e8-8c5a-1e8652af9776.png)
Ps:Node 版本为8.11.1
     npm 版本为5.6.0
     操作系统 macos sierra 
    Angular CLI 版本 1.7.4

请问要怎样解决？谢谢

**Comment by cipchk** [comment]
https://ng-alain.com/docs/cli
