### ISSUE TITLE
How to remove lazyload

### ISSUE THREAD

**Issue by yzy1197988245** [ng-alain/ng-alain#400]
## Bug Report or Feature Request (mark with an `x`)

<pre><code>
[ ] Bug report -> please search issues before submitting
[ ] Feature request
[x] Documentation issue or request
</code></pre>

## What is expected?

怎样移除懒加载。

## Environment

<pre><code>
ng-alain version: X.Y.Z
Angular version: X.Y.Z
Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
</code></pre>

**Comment by cipchk** [comment]
取消使用 `loadChildren`

**Comment by yzy1197988245** [comment]
我的意思是，取消图片的懒加载

**Comment by cipchk** [comment]
移除 `index.html` 相关样式。
