### ISSUE TITLE
Code Indentation at 4 spaces over 2 spaces?

### ISSUE THREAD

**Issue by billyma128** [ng-alain/ng-alain#404]
## Bug Report or Feature Request (mark with an `x`)

<pre><code>
[ ] Bug report -> please search issues before submitting
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Environment

<pre><code>
ng-alain version: X.Y.Z
Angular version: X.Y.Z
Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
</code></pre>

**Comment by cipchk** [comment]
English better than chinese effect when two spaces, vice versa, maybe??

**Comment by billyma128** [comment]
Practically, 2 spaces is perfect for HTML, and a lot of templates which is inlined into typescript file,  since HTML with 4 spaces is unreadable.

80 column limitation with [prettier](https://github.com/cipchk/ng-alain/pull/403/files#diff-f2e285fb35cc9694564cb6d2af099ad2R2), like [React did](https://github.com/facebook/react/blob/master/.prettierrc.js#L8), is almost a fair argument no matter what type of indentation is. And 2 space indentation is just so much more neater and better looking in terms of this limitation.

So many other popular repository have indentation at 2 namely

- [angular](https://github.com/angular/angular/blob/master/.editorconfig)
- [angular.js](https://github.com/angular/angular.js/blob/master/.editorconfig)
- [react](https://github.com/facebook/react/blob/master/.editorconfig)
- [express](https://github.com/expressjs/express/blob/master/.editorconfig)
