### ISSUE TITLE
simpleTable的type为link的问题

### ISSUE THREAD

**Issue by qiuliang1** [ng-alain/ng-alain#406]
1.这是我的代码
![image](https://user-images.githubusercontent.com/35951262/39610383-7777a438-4f82-11e8-9df2-5bdf1264d71e.png)
2.当我点击网址却没有跳转，原因是a标签没有href的属性，请问我该如何解决。
![image](https://user-images.githubusercontent.com/35951262/39610400-96a7a6a0-4f82-11e8-9c38-1c24d2ba52f0.png)
望解答！！！

**Comment by yzy1197988245** [comment]
可以用ngFor

**Comment by cipchk** [comment]
`link` 需要配合 `click` 一起使用，若需要打开新窗体，可以使用 `window.open`，路由则使用 `router`。
