### ISSUE TITLE
新手照着文档安装，各种错误~~

### ISSUE THREAD

**Issue by datafeng** [ng-alain/ng-alain#408]
反正是照着文档来的，各种奇怪的错误。
cli6、1.7两个版本----
windows\linux系统都对着文档测试过了。。都没能安装成功。。好伤心~~

**Comment by cipchk** [comment]
请提供有助于解决问题的信息。

> 别像小孩一样提问题，我跪下来求你了。

**Comment by datafeng** [comment]
linux:
![image](https://user-images.githubusercontent.com/6417549/39625271-48d619a0-4fcf-11e8-97a4-28793be778b6.png)

windows:
![image](https://user-images.githubusercontent.com/6417549/39625336-86500098-4fcf-11e8-82a5-1709326cc89d.png)

完全照着文档一步步来的。。。

**Comment by cipchk** [comment]
ng-alain 暂时不支持 v6

**Comment by thanatos915** [comment]
@cipchk 请问有没有支持V6的计划. webpack 4 和 rxjs 6 都有很好的改进 # #

**Comment by cipchk** [comment]
必须的，不过需要等待 ng-zorro-antd 支持 v6，应该很快，再者 v6 刚 release，看样子可以不要太着急，可以减少更多不确定性。
