### ISSUE TITLE
打包报错

### ISSUE THREAD

**Issue by yrx0823** [ng-alain/ng-alain#409]
## Bug Report or Feature Request (mark with an `x`)

<pre><code>
[ ] Bug report -> please search issues before submitting
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Reproduction link

![image](https://user-images.githubusercontent.com/23035615/39622744-eb6a5f14-4fc5-11e8-8f44-4c7bc27e6d19.png)

## Environment

<pre><code>
ng-alain version: X.Y.Z
Angular version: X.Y.Z
Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
</code></pre>

**Comment by cipchk** [comment]
执行：

```bash
npm i --save ngx-countdown
```
