### ISSUE TITLE
关于Layout变动

### ISSUE THREAD

**Issue by maplye** [ng-alain/ng-alain#41]
在upgrade.md中关于layout中的描叙：

页面整体布局结构，包括：头部、左边菜单，除非在更新日志中明确提醒否则该目录不太会变动。

但是实际上header.component中的Notifications中都是测试数据，肯定要调整的，这样是不是和不太会变动有矛盾

**Comment by cipchk** [comment]
若有Layout大的变动会详细说明，并且至少次级以上的版本号更新。

> 其实至 `0.1.x` 以来就没有什么大的改变。

**Comment by dusdong** [comment]
对于这个问题，在升级时，我都是使用Beyond Compare工具进行文件夹比较。

PS：是否可以把Notifications里面的测试数据抽离成一个服务呢？这样header.component都可以放心的更新了

**Comment by cipchk** [comment]
本身 header 只是一个 demo 的形式存在，其实就结构来讲，最好是将每一个按钮或搜索框做成独立一个组件。
