### ISSUE TITLE
ueditor/tinymce widget cannot pass tslint

### ISSUE THREAD

**Issue by NitronPlus** [ng-alain/ng-alain#410]
## Bug Report or Feature Request (mark with an `x`)

<pre><code>
[*] Bug report -> please search issues before submitting
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Reproduction link
![tsl](https://user-images.githubusercontent.com/1940394/39627980-20a18522-4fda-11e8-9dad-fb8ec5f30f24.png)

## Steps to reproduce
export class AppComponent {}
````
-->


## What is expected?



## What is actually happening?
<!-- 实际的结果是什么 -->


## Environment
<!-- 环境 -->

<pre><code>
ng-alain version: 1.0.0-beta.8
Angular version: 1.7.4
Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
</code></pre>

**Comment by cipchk** [comment]
的确有可能，widget-third 并没有计入 tslint 内，我也发现该问题，关于 tslint 我会统一再进行全部处理。

> 相关问题以 #404 为准
