### ISSUE TITLE
git clone下来报错

### ISSUE THREAD

**Issue by xgj1988** [ng-alain/ng-alain#413]
webpack: wait until bundle finished: /
Date: 
2018-05-06T04:48:13.810Z
ERROR in ./node_modules/_raw-loader@0.5.1@raw-loader!./node_modules/_postcss-loader@2.1.5@postcss-loader/lib??embedded!./node_modules/_less-loader@4.1.0@less-loader/dist/cjs.js??ref--9-3!./src/styles.lessHash: a661097b8c8fc43b4cd4

Time: Module build failed: 30229ms

chunk {
data-v.module} @import '../../../../theme/styles/default';data-v.module.chunk.js
 () 25.5 kB ^ [rendered]

chunk {delon.module} Can't resolve '../../../../theme/styles/default.less' in 'G:\gitlab\ng-alain\node_modules\_@delon_abc@1.0.0-beta.8@@delon\abc\src\avatar-list\style'delon.module.chunk.js () 140 kB 
 [rendered]      in G:\gitlab\ng-alain\node_modules\_@delon_abc@1.0.0-beta.8@@delon\abc\src\avatar-list\style\index.less (line 1, column 0)

**Comment by cipchk** [comment]
- 使用 `cnpm` 安装依赖包，会遇到无法找到样式文件。这是由于 `cnpm` 采用的是软链接路径形式，导致 `ng-zorro-antd` 文件夹名有所变动，因此建议改用 `npm` 或 `yarn` 安装依赖包。

> [摘自（开始使用）](https://ng-alain.com/docs/getting-started#%E4%BA%94%E3%80%81%E6%9C%AC%E5%9C%B0%E5%BC%80%E5%8F%91)
