### ISSUE TITLE
ng-alain 有 Electron 打包的基本脚本配置吗？？ 

### ISSUE THREAD

**Issue by zhoubonet** [ng-alain/ng-alain#415]
ng-alain 有 Electron 打包的基本脚本配置吗？？

**Comment by cipchk** [comment]
https://ng-alain.com/docs/cli

**Comment by zhoubonet** [comment]
npm install -g @angular-devkit/core @angular-devkit/schematics @schematics/schematics rxjs
npm install -g @angular/cli
npm install -g @delon/cli

创建的时候报错误
![image](https://user-images.githubusercontent.com/4209701/39690701-95753c6a-520d-11e8-88bc-e63fad7c652f.png)

**Comment by zhoubonet** [comment]
可以了，npm install -g @angular/cli@1.7.4 版本必须是这个

**Comment by zhoubonet** [comment]
谢谢
