### ISSUE TITLE
simple-table动态隐藏/显示数据列

### ISSUE THREAD

**Issue by chaoxiaochao** [ng-alain/ng-alain#417]
simple-table能否开放动态隐藏/显示数据列的功能？
类似下图这种：
![table](https://user-images.githubusercontent.com/20222848/39694633-925f1ec6-521a-11e8-861b-e8581841b6b4.jpg)

**Comment by cipchk** [comment]
你可以动态修改 `columns` 值。

**Comment by chaoxiaochao** [comment]
How to do it? I tried this method, but failed.
