### ISSUE TITLE
ReuseTab使用clear方法时出现异常。

### ISSUE THREAD

**Issue by xingkoo** [ng-alain/ng-alain#418]
复杂业务逻辑导致的，没有办法重现。简单描述一下吧。

routersModule下新增加三个模块，分别是aModule，bMoudule，cModule。
模块使用子路由守卫。里面使用 reuseTab.clear() 方法清除路由。然后进入目标模块。

实际操作时，发现当打开amodule的两个页面时，在某个页面中切换至另外的模块。即导致出现错误。
原来模块的路由未被清空，还保留了一个。又新增加了一个新模块的路由。
（所以，清空路由的操作，是否可以完全清空，不留一个？）

还有更严重的错误，选项卡的选中样式会固定在第一个。而且也只有点第一个选择卡才会有效果（切换页面）。

看下图，鼠标移动到第二个的时候，死命点，无效。第一个可以一直点一直切换。
![qq20180507-210305-hd](https://user-images.githubusercontent.com/2936579/39703263-225500e4-523a-11e8-999f-0ca65894c6c6.gif)

**Comment by smile2014** [comment]
getMenu 能设置成公有方法不，在表单界面需要拿当前菜单信息

**Comment by xingkoo** [comment]
已经过了好几个版本了。目前还没有碰到这个问题。下次如果再出现类似问题，我会重现一份样例出来提交。
