### ISSUE TITLE
Demo Bug

### ISSUE THREAD

**Issue by RoEcho** [ng-alain/ng-alain#42]
Open address：https://cipchk.github.io/ng-alain/

Environment：Chrome 62、liebao 6.5、Firefox 56
![image](https://user-images.githubusercontent.com/18479821/32207628-2357f71c-be38-11e7-9556-0951b8338e2e.png)

**Comment by cipchk** [comment]
sorry, error result from ng-zorro-antd laster version, i'll tracking [#504](https://github.com/NG-ZORRO/ng-zorro-antd/issues/504).

you can safe using `0.5.x` version.
