### ISSUE TITLE
默认路由配置

### ISSUE THREAD

**Issue by YDeity** [ng-alain/ng-alain#428]
如何设置默认的路由是登陆页呢？

**Comment by 107295472** [comment]
默认路由首页，你检查是否登录，不登录转到登录页

**Comment by YDeity** [comment]
是个不错的建议，可是代码怎么写呢？this.router.navigate(['/passport/login']); ? 是否存在用户怎么判断呢？

**Comment by 107295472** [comment]
判断cookie啊，用登陆就存cookie里

**Comment by YDeity** [comment]
js cookie 吗 ? 我看到代码里有
![image](https://user-images.githubusercontent.com/38305544/39987322-00ee958e-5797-11e8-9324-8666b9c33108.png)， 我写了 
![image](https://user-images.githubusercontent.com/38305544/39987423-596b13cc-5797-11e8-89a7-b1c4cff48dac.png) ， 可以吗 ？ 不起作用

**Comment by YDeity** [comment]
可以了，贡献一下代码 
![image](https://user-images.githubusercontent.com/38305544/39997055-1e2eaaea-57b4-11e8-9c11-8d25cf15f493.png)

感谢 Yin
