### ISSUE TITLE
清除本地缓存后路由错误

### ISSUE THREAD

**Issue by DesignHhuang** [ng-alain/ng-alain#429]
ng-alain与真实的后台连接（后台请求需要token）

清除本地缓存后，刷新请求后台数据的组件（auth机制会自动跳转到/passport/login中），输入正确的用户名，密码之后，点击登录。之后报错：无法加载xxxxx的路由。

@cipchk 具体错误如下：
使用的版本：ng-alain-1.0.0-beta.10
修改了login.component.ts，v1.component.ts和v1.component.html，改成真实获取后端数据。
![qq 20180516161147](https://user-images.githubusercontent.com/3368397/40104855-f86019e0-5923-11e8-9fc6-ad0bfe342e26.png)
![html0](https://user-images.githubusercontent.com/3368397/40104862-faef0630-5923-11e8-832d-73a00a5d49d4.png)
![ts](https://user-images.githubusercontent.com/3368397/40104866-fcd69b66-5923-11e8-8664-8de99a83130f.png)

修改之后：
输入账号，密码登录，登录成功，并自动跳转到 dashboard/v1 ，数据正确获取，如下图：
![qq 20180516160117](https://user-images.githubusercontent.com/3368397/40105018-60e771b6-5924-11e8-99a2-61a656567e4c.png)
之后清空本地缓存并点击浏览器中的刷新，如下图：
![111](https://user-images.githubusercontent.com/3368397/40105557-dd5536ce-5925-11e8-8092-3a3681b4b647.png)
![qq 20180516160148](https://user-images.githubusercontent.com/3368397/40105086-8ee6222e-5924-11e8-81a9-25b36d3f7c37.png)
以上操作之后，就会一直出现路由xxxxx无法加载的现象，如下图：
![qq 20180516160219](https://user-images.githubusercontent.com/3368397/40105125-a640170e-5924-11e8-83c5-ca18ad6b3c9d.png)

**Comment by cipchk** [comment]
请提供有助于判断的更多信息。

**Comment by lc-01010** [comment]
我是在未登录的状态访问非登录页面报错如下，不知是否同一问题？![image](https://user-images.githubusercontent.com/38215188/40030654-665d0086-581e-11e8-8db5-dd299156e20a.png)
好像是因为没有登录访问content路由的时候报如法加载XXX路由。登录后是无任何问题的，我的路由配置如下：
![image](https://user-images.githubusercontent.com/38215188/40030902-a81c48a0-581f-11e8-88d4-d8315c39afb1.png)

**Comment by cipchk** [comment]
@lc-01010 `ContentModule` 的路由配置呢？或者说有其他阻碍组件创建的一些 `providers` 之类，依然放弃非常判断。

**Comment by lc-01010** [comment]
@cipchk ?ContentModule的路由配置
![image](https://user-images.githubusercontent.com/38215188/40042815-33a3eb3c-5855-11e8-9674-3aa0e8c7e8fc.png)

**Comment by lc-01010** [comment]
@cipchk 是我代码写的有问题，有一个providers导致的。谢谢

**Comment by DesignHhuang** [comment]
@cipchk 问题已更新

**Comment by cipchk** [comment]
关闭此 issues，若有更多细节描述，重新提交 issue。
