### ISSUE TITLE
项目npm install后无法启动

### ISSUE THREAD

**Issue by iedwin** [ng-alain/ng-alain#43]
### Versions.
Angular CLI: 1.5.0
Node: 8.2.1
OS: darwin x64
Angular: 4.4.6
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, tsc-wrapped

@angular/cdk: 2.0.0-beta.8
@angular/cli: 1.5.0
@angular-devkit/build-optimizer: 0.0.32
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.35
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.0
@schematics/angular: 0.1.0
typescript: 2.3.4
webpack-bundle-analyzer: 2.9.0
webpack: 3.8.1

### Repro steps.
新下载项目后npm install， ng serve --open --port 0 报编译失败。

### The log given by the failure.
<img width="1368" alt="screen shot 2017-11-02 at 4 54 52 pm" src="https://user-images.githubusercontent.com/17739715/32317422-bdefed72-bfee-11e7-8db4-bf3cfe982a16.png">

**Comment by iedwin** [comment]
到node_modules/g2-angular/index.metadata.json中修改，不生效。不知要如何处理？

**Comment by cipchk** [comment]
becaue of `ng-zorro-antd` not compatible with v5 yet [#514](https://github.com/NG-ZORRO/ng-zorro-antd/issues/514), so` ng-alain` won't release V5-compatible versions.

we have no choice without waiting.

**Comment by jiankian** [comment]
我的也是 这两天的项目clone到本地 npm install 然后  ng serve --open启动网页打开是个Error标题 然后Cannot GET /

**Comment by cipchk** [comment]
@jiankian  非Angular5的情况下，需要提供更明细的错误。

**Comment by mizne** [comment]
这个好像是Angular cli版本太高的问题
我把package.json的版本都锁死 
删除node_modules和package-lock.json
再npm cache clean --force
再重装下依赖 应该就好了

**Comment by qld-cf** [comment]
@mizne 我按照你做的 爆了can not find node-sass错误

**Comment by cipchk** [comment]
抱歉，由于 `package.json` 采用的是兼容性比较宽的包体依赖。

我今晚会发布一个稳定angular4版本。

**Comment by chenjia123** [comment]
@cipchk 今晚几点发布啊
