### ISSUE TITLE
simple-table 多条件排序问题。

### ISSUE THREAD

**Issue by xingkoo** [ng-alain/ng-alain#431]
后端需要接收处理 类似样式的排序条件。
```
?sort=name.asc-id.desc
```
目前simple-table所能产生的条件是 ?name=asc&id=desc这样的结构。
能没有可能实现这样的需求？如果按index做为key, asc或desc做为value，在后端接收处理的时候，会非常麻烦，要每个参数做一次处理。

**重点在于，查询参数中，一般会有带id字段。如果还是使用id=asc或id=desc，就和查询参数冲突了。**

**Comment by xingkoo** [comment]
另外当使用多条件排序时，点击两个排序后，取消其中一个排序，会导出两个排序条件都消失掉的问题。

**Comment by cipchk** [comment]
1、不支持
2、[multiSort](https://ng-alain.com/components/simple-table#simple-table)

**Comment by xingkoo** [comment]
仔细看了一下手册，或许我可以通过preDataChange全局设置来解决这个问题。我试一下。

**Comment by xingkoo** [comment]
看划了，preDataChange是处理数据的，不是请求前执行的。我仔细看看代码给不能做到吧。
