### ISSUE TITLE
angular 6x has an error

### ISSUE THREAD

**Issue by thanatos915** [ng-alain/ng-alain#432]
## Environment

<pre><code>
ng-alain version: 1.0.1.beta2
Angular version: 6.0.0
</code></pre>

### I run yarn install then ng serve.  an error
```
ERROR in ./src/styles.less (./node_modules/raw-loader!./node_modules/postcss-loader/lib??embedded!./node_modules/@angular-devkit/build-angular/node_modules/less-loader/dist/cjs.js??ref--15-3!./src/styles.less)
Module build failed: 

// https://github.com/ant-design/ant-motion/issues/44
.bezierEasingMixin();
^
Inline JavaScript is not enabled. Is it set in your options?
      in node_modules/ng-zorro-antd/src/style/color/bezierEasing.less (line 110, column 0)
ERROR in ./src/app/routes/passport/register/register.component.less
Module build failed: 

```

**Comment by thanatos915** [comment]
@cipchk

**Comment by cipchk** [comment]
downgrade less from 3.x to 2.7.x, [#10430](https://github.com/angular/angular-cli/issues/10430)

**Comment by daihy8759** [comment]
好像问题没解决啊，clone下来启动还是会报错 @cipchk

**Comment by cipchk** [comment]
@dai875939260 移除 `node_modules` 和 `package.json`，重新 `npm i` 或 `yarn`

**Comment by daihy8759** [comment]
我移除过了。，里面的less确实是2.7版本

**Comment by zd5043039119** [comment]
@dai875939260
I have the same issue when less-loader's version to 4.1.0, and less is 2.7.0.
but if you downgrade less-loader from 4.1.0 to 4.0.6, then it passed.

**Comment by lumeng689** [comment]
locate to      'node_modules\@angular-devkit\build-angular\src\angular-cli-files\models\webpack-configs\styles.js'   line 136 and 142 （may be different in different version），modify lessPathOptions  object，add property :  lessPathOptions.javascriptEnabled = true

`
let lessPathOptions = { paths: [], javascriptEnabled: true};
    if (......);
        lessPathOptions = {
            paths: includePaths,
            javascriptEnabled: true
        };
    }
`

resolution from  [https://segmentfault.com/a/1190000015577159](https://segmentfault.com/a/1190000015577159)

**Comment by lumeng689** [comment]
change in package.json,  I found  when use 0.7.0, there is no error.
`
"@angular-devkit/build-angular": "0.7.0"
`
