### ISSUE TITLE
[Bug] @delon/cli does not support ng argument --prefix

### ISSUE THREAD

**Issue by shNerotic** [ng-alain/ng-alain#433]
## Bug report

<pre><code>
When I used delon/cli command to new a project with --prefix argument, it will does not work.
1. create a correct html tag <<i>prefix</i>-root></<i>prefix</i>-root>
2. but <b>DOES NOT</b> modify the component selector correctly, so it is inconsistent and fail to open this website.
</code></pre>

## Steps to reproduce
```ts
a. ng new -c=@delon/cli XXX -di -g2 --prefix marketing
b. yarn
c. npm run serve:hmr
````

## What is expected?
run the website correctly.

## What is actually happening?
can not open the website

## Environment

<pre><code>
ng-alain version: latest
Angular version: 5.2
Browser:
- Chrome (desktop) 
</code></pre>

**Comment by cipchk** [comment]
https://ng-alain.com/docs/cli

**Comment by shNerotic** [comment]
@cipchk  I must have to upgrade my Angular to v6 in order to support command ng add. But now I may need to modify the "prefix" in the existed codes manually because my Angular is v5.
