### ISSUE TITLE
simple-table 排序bug

### ISSUE THREAD

**Issue by xingkoo** [ng-alain/ng-alain#434]
````
<simple-table [data]="'api'" [columns]="columns" [multiSort]="true"></simple-table>
````
当使用多属性排序时，同时选择 **（A列、B列）** 排序的情况下，当取消（取消，不是变更）  **B列** ，发起的请求中， 
**A列** 的排序值将不会被发出。
再次点击 **B表** 排序，发起的请求中 
**A列** 还会出现。

另：
1、希望能使用多列排序时，支持 ````?sort=columnA.asc-columnB.desc```` 类似的数据处理。
目前支持的 ````?columnA=asc&columnB=desc````格式，后端处理时，需要接收多个值，每个值来做一个判断。不如上面所列方式更易用。
2、标题中，切换选择，能否点击标题后，从正序、倒序、默认三种状态循环切换？现在的上下选择正序或倒序以及默认三种的切换，容易误操作，普通用户在使用过程中，不能够第一时间知道分别点击上下两个前头是正倒序切换以及取消。

**Comment by xingkoo** [comment]
````
// 表格列配置
  columns: SimpleTableColumn[] = [
    {
      title: '编号',
      index: 'id',
      render: 'id',
      sorter: (a, b) => true,
      sortKey: 'sort',
      sortReName: { ascend: 'id', descend: 'id.desc' }
    },
    { title: '标题', render: 'title' },
    {
      title: '状态',
      index: 'status',
      width: '100px',
      format: function (cell: any) {
        return cell.status === '1' ? '正常' : '作废';
      },
      sorter: (a, b) => true,
      sortKey: 'sort',
      sortReName: { ascend: 'status', descend: 'status.desc' }
    }
  ];
````
以上代码，在单列排序时，可以获得 ```` ?sort=status ```` 或者 ```` ?sort=status.desc ````的效果。
在多列排序时，**sortKey**需要设置不同的值，才能使用。而得到的结果会是 ?````sort1=id.desc&sort2=status```` 类似效果。

我目前后端使用的yii1.1版本，sort功能是通过接收 ````?sort=status-id.desc```` **-** 横线或其他分隔开的多个排列标识。

**Comment by cipchk** [comment]
我总结两点：

1、相同排序 `key` 时，应该合并
2、操作行为目前没有办法，这一切受限于 zorro

**Comment by xingkoo** [comment]
（2）是操作体验问题，可以不急着解决。
（1）在开发过程中影响较大，这个需要尽快解决。

**Comment by yihango** [comment]
目前9.5.3版本我使用同样的写法，当change事件type为sort时，查询后台数据，重新给st的data赋值，会导致前端st排序信息丢失
