### ISSUE TITLE
ngx-aside 组件添加建议

### ISSUE THREAD

**Issue by xingkoo** [ng-alain/ng-alain#435]
aside component，属于比较常用的组件，show item detail at list page.
是否能够在@delon中移植此功能？

GitHub
[https://github.com/passenger6/ngx-aside](https://github.com/passenger6/ngx-aside)

Demo
[https://stackblitz.com/edit/github-q7dd3w?embed=1&file=src/demo-app/main.ts](https://stackblitz.com/edit/github-q7dd3w?embed=1&file=src/demo-app/main.ts)

![image](https://user-images.githubusercontent.com/2936579/40139039-26121476-5981-11e8-96f8-84bf5430f5a4.png)

**Comment by dusdong** [comment]
除了左右方向外，希望还可以从底部弹出。在阿里云ECS页面，点击监控状态时，会从底部弹出状态窗口，很方便。
![tim 20180521064811](https://user-images.githubusercontent.com/3461709/40284522-f5b0a9ec-5cc2-11e8-970d-6974864d5682.png)

**Comment by cipchk** [comment]
放弃，ng-zorro-antd 将直接支持，请关注：https://github.com/NG-ZORRO/ng-zorro-antd/issues/1565
