### ISSUE TITLE
请问，1.0.0 会发布正式版吗？想在 ng5 下使用 zorro 0.7

### ISSUE THREAD

**Issue by dusdong** [ng-alain/ng-alain#436]
## Bug Report or Feature Request (mark with an `x`)

<pre><code>
[ ] Bug report -> please search issues before submitting
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Environment

<pre><code>
ng-alain version: X.Y.Z
Angular version: X.Y.Z
Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
</code></pre>

**Comment by cipchk** [comment]
已经 `1.0`
