### ISSUE TITLE
select组件问题

### ISSUE THREAD

**Issue by DesignHhuang** [ng-alain/ng-alain#437]
测试地址：   https://cipchk.github.io/ng-alain/#/dashboard/v1

在网站中随便找一个带有select的页面，点击select，出现下拉选项，如下图：
![2221](https://user-images.githubusercontent.com/3368397/40153399-3e1726ac-59bc-11e8-9623-5c432f7c68f0.png)

不选择任何选项，直接点击浏览器的后退按钮

select的选项卡会一直存在在页面中，如下图：
![3333822](https://user-images.githubusercontent.com/3368397/40153433-68bdf458-59bc-11e8-813d-24e4be816e8a.png)

此时这个选项卡会一直存在，随便点其中的一个选项，选项卡会跳到页面的左上方并一直存在（除非点击浏览器刷新页面），如下图：
![4441](https://user-images.githubusercontent.com/3368397/40153495-acc5d18e-59bc-11e8-983c-0f268cb99d0c.png)

**Comment by cipchk** [comment]
这个问题是 ng-zorro-antd 组件引起的。

**Comment by cipchk** [comment]
相关 https://github.com/NG-ZORRO/ng-zorro-antd/issues/1455

**Comment by iwe7** [comment]
```ts
setTimeout(()=>{},0)
```
即可

**Comment by DesignHhuang** [comment]
@cipchk 我提的这个问题其实应该与ng-zorro-antd 组件没有关系，因为我直接用ng-zorro-antd中的nz-select的时候(直接新建一个项目，测试ng-zorro-antd组件)不会出现这样的选项一直存在的问题，但是当我将nz-select用在ng-alain项目里的时候，就会出现像我问题中图文描述的问题。

**Comment by DesignHhuang** [comment]
@cipchk 这个问题很有可能是路由复用的问题，当有select组件的页面使用路由复用之后，虽然点击的浏览器中的后退按钮，使页面从分析页跳转到了仪表盘，但其实缓存中分析页仍存在，所以在没有关闭选择项的时候，该框还会继续存在，如下图：

![1](https://user-images.githubusercontent.com/3368397/41329396-0fc76b6e-6f00-11e8-9a90-32352642ca8f.png)
-------------------------------------------------
但是如果在app-data.json中配置的时候给分析页加上reuse:false的话，这种情况就不会出现，所以我认为应该在使用到选择框的页面都需要配置reuse:false；或者确实需要使用路由复用的话是不是还有其他的解决办法（尝试在_onReuseDestroy()中解决此类问题？）。
