### ISSUE TITLE
1.0.0-beta10 页面中的_onReuseInit钩子不会触发

### ISSUE THREAD

**Issue by pengb0** [ng-alain/ng-alain#438]
看了下源码应该是用hasOwnProperty会一直false，method是在instance的__proto__中，
![image](https://user-images.githubusercontent.com/27408827/40154682-26d40f40-59c2-11e8-9a89-8fb53e6491ad.png)

![image](https://user-images.githubusercontent.com/27408827/40155113-79088fc8-59c4-11e8-8e6f-f1300f93ce31.png)

<pre><code>
ng-alain version: 1.0.0-beta10
Angular version: 5.0
Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
</code></pre>

**Comment by cipchk** [comment]
的确可能继承类会引起这个问题。

**Comment by pengb0** [comment]
暂时可使用下面代码解决
` _onReuseInit=()=> {
  doSomething();
}`
但是 路由复用的时候_onReuseInit中的内容会执行三次，这是个bug吗？经测试在@delon0.7.1版本中是只会执行一次的。 @cipchk
