### ISSUE TITLE
v1.0.1 cannot passed tslint

### ISSUE THREAD

**Issue by NitronPlus** [ng-alain/ng-alain#439]
## Bug Report or Feature Request (mark with an `x`)

<pre><code>
[x] Bug report -> please search issues before submitting
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Reproduction link

![image](https://user-images.githubusercontent.com/1940394/40162336-489b485e-59e6-11e8-9352-3cb90db8764d.png)

## Steps to reproduce

```bash
npm lint:ts  or ng lint
````
-->

## Environment

<pre><code>
ng-alain version: 1.0.1
Angular CLI: 6.0.3
Node: 8.11.0
OS: linux x64
Angular: 6.0.2
Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
</code></pre>

**Comment by cipchk** [comment]
https://github.com/cipchk/ng-alain/blob/master/package.json#L22

**Comment by NitronPlus** [comment]
一样的,不管是我手动运行
```shell
npm run -s lint:ts
````
![image](https://user-images.githubusercontent.com/1940394/40163240-df78568e-59e8-11e8-8b38-d3c8db5c0e0e.png)

或者是
```shell
tslint -p src/tsconfig.app.json -c tslint.json 'src/**/*.ts'
````
![image](https://user-images.githubusercontent.com/1940394/40163265-f1ef5ede-59e8-11e8-9f5c-97b836ad8899.png)

都是一样的结果
@cipchk

**Comment by cipchk** [comment]
抱歉，没注意看错误内容，这个问题是 [tslint.json](https://github.com/cipchk/ng-alain/blob/master/tslint.json#L126) 配置项的关系。

tslint 会规定代码风格指南，你可以根据你的需求自行修改。

**Comment by NitronPlus** [comment]
ok,这个我是看到了的,因为我想着里面有pro组件和两个编辑器,以为你忘记处理了
