### ISSUE TITLE
当 _HttpClient.post() 返回的状态码为200时，如何能使 HttpInterceptor  不报错？

### ISSUE THREAD

**Issue by dusdong** [ng-alain/ng-alain#44]
## Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
```

### Repro steps.

当调用 _HttpClient.post() 返回的状态码为200时，HttpInterceptor 会在 .catch((res: HttpResponse<any>) => {} 段落处捕捉到错误。
如何修改才能将200视为正常值，不返回错误？

**Comment by cipchk** [comment]
不明白你的意思，若HTTP返回的状态码为200是不会走 `catch` 的。

**Comment by dusdong** [comment]
哦哦，我又调试了下，我的后台webapi返回的值为空，状态码为200，应该是HttpClient在自动json()时报错：SyntaxError: Unexpected end of JSON input。
我再找找解决方案。。。

**Comment by dusdong** [comment]
搞定了！
参照 ExtrasPoiComponent 完成了一个基本的资料维护窗口，感谢楼主的开源项目~！

**Comment by lymanlee** [comment]
@dusdong 能分享你是如何解决的吗？

**Comment by dusdong** [comment]
我的后台是.net，原本是 return Ok(); 现改为 return Ok(HttpStatusCode.NoContent);
