### ISSUE TITLE
关于自定义主题色不生效的问题

### ISSUE THREAD

**Issue by guccihuiyuan** [ng-alain/ng-alain#441]
1.0.0-beta.10中，我升级了zorro0.7以后，设置主题色@primary-color: #00a854;后，样式不起作用，全部都是默认颜色，因为zorro0.7的文档上说要在.angular-cli.json中引入"../node_modules/ng-zorro-antd/src/ng-zorro-antd.less"，否则dataPicker组件样式会有问题，当我把这个样式去掉以后，设置主题色就可以生效，这个怎么解决呢？

**Comment by cipchk** [comment]
出于很多因素，@delon/theme 内置了 zorro 的组件样式，导致了你后来引入 了被覆盖，你可以只导入 `date-picker` 的样式亦可。
