### ISSUE TITLE
 后台配置项返回格式出错，上传功能将不能正常使用

### ISSUE THREAD

**Issue by iwe7** [ng-alain/ng-alain#447]
## Bug Report or Feature Request (mark with an `x`)

<pre><code>
[* ] Bug report -> please search issues before submitting
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is actually happening?

 [url](https://ng-alain.com/form/ueditor)
ueditor.all.min.js:124 后台配置项返回格式出错，上传功能将不能正常使用！

## Environment

<pre><code>
ng-alain version: X.Y.Z
Angular version: X.Y.Z
Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
</code></pre>

**Comment by cipchk** [comment]
是的，因为没给他配置后台，这只是一个简单的示例，细节需要用户自行处理。
