### ISSUE TITLE
Bug Report - xlsx Excel 操作，通过传递file参数方式导入报错，通过url参数方式导入成功！

### ISSUE THREAD

**Issue by LiensHuang** [ng-alain/ng-alain#449]
## Bug Report - xlsx Excel 操作，通过传递file参数方式导入报错，通过url参数方式导入成功！

<pre><code>
Bug report 
Documentation issue or request
</code></pre>

## Steps to reproduce

```ts
import { Component } from '@angular/core';
import { SimpleTableColumn, XlsxService } from '@delon/abc';

@Component({
    selector: 'components-xlsx-import',
    template: `
    <button nz-button (click)="url()">Via Url</button>
    <input type="file" (change)="change($event)" multiple="false" class="ml-sm" />
    <p class="mt-sm">result: {{data | json}}</p>
    `
})
export class ComponentsXlsxImportComponent {
    constructor(private xlsx: XlsxService) {}
    data: any;
    url() {
        this.xlsx.import(`./assets/demo.xlsx`).then(res => this.data = res);
    }

    change(e: Event) {
        const file = (e.target as HTMLInputElement).files[0];
        this.xlsx.import(file).then(res => this.data = res);
    }
}
````

## What is expected?

![image](https://user-images.githubusercontent.com/9148805/40213742-a78e2946-5a89-11e8-9caa-85d6d5e8b9eb.png)

## What is actually happening?

![_ _20180518105430](https://user-images.githubusercontent.com/9148805/40213831-1f749dfa-5a8a-11e8-802f-35d81ccbf723.png)

## Environment

<pre><code>
ng-alain version: 1.0.1
Angular version: 6.0.0
Browser:
- Chrome (desktop) version  63.0.3239.132
</code></pre>

**Comment by cipchk** [comment]
https://github.com/SheetJS/js-xlsx/wiki/Reading-XLSX-from-FileReader.readAsArrayBuffer()

**Comment by NitronPlus** [comment]
fixed, see delon's pr [#82](https://github.com/cipchk/delon/pull/82) 
```javascript
FileReader.readAsArrayBuffer(); 
Xlsx.read(data, {type: 'array'}) 
````
or
```javascript
FileReader.readAsBinaryString(); 
Xlsx.read(data, {type: 'binary'}) 
`````

**Comment by cipchk** [comment]
请提供一个干净的 pr.

**Comment by NitronPlus** [comment]
抱歉.已更新该PR.

**Comment by cipchk** [comment]
请问你核实过这个情况吗？我的意思是说这样子修改的确可以解决这一问题。

**Comment by NitronPlus** [comment]
是的,我先在ng-alain上自定义一个service覆盖掉delon/abc的引入

使用代码:
```javascirpt
FileReader.readAsBinaryString(fileOrUrl); 
Xlsx.read(data, {type: 'binary'}) 
````
执行结果
![image](https://user-images.githubusercontent.com/1940394/40217669-8b200704-5aa0-11e8-8dec-e25a3366d15c.png)

使用代码:
```javascript
FileReader.readAsArrayBuffer(fileOrUrl); 
Xlsx.read(data, {type: 'array'}) 
`````
执行结果
![image](https://user-images.githubusercontent.com/1940394/40217981-cc5e7542-5aa1-11e8-809a-d6914b5a3a9e.png)

WPS,LibreOffice, M$ Office的xlsx都做过测试
csv的则需要是UTF8 with BOM格式才能解析

**Comment by cipchk** [comment]
谢谢，因为没有相关测试用例。能否在代码注释一行相关的 【https://github.com/SheetJS/js-xlsx/wiki/Reading-XLSX-from-FileReader.readAsArrayBuffer()】
