### ISSUE TITLE
我想请问下 npm run build vendor.****.bundle.js 太大

### ISSUE THREAD

**Issue by mizne** [ng-alain/ng-alain#45]
@cipchk 
我自己通过npm run build发现vendor.****.bundle.js有2M+太大，但我看了DEMO链接过去的网页 
通过network发现main.****.bundle.js只有几百k，想请教下是如何做到的？
多谢了

**Comment by cipchk** [comment]
gzip.

**Comment by mizne** [comment]
多谢多谢 解决了
