### ISSUE TITLE
使用sechma form时，当使用modalService动态时，ueditor首次打开正常，关闭后打开报错

### ISSUE THREAD

**Issue by iwe7** [ng-alain/ng-alain#451]
## Bug Report or Feature Request (mark with an `x`)

<pre><code>
[ ] Bug report -> please search issues before submitting
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## What is actually happening?

暂时不知道什么原因，issue一下!

## Environment

<pre><code>
ng-alain version: X.Y.Z
Angular version: X.Y.Z
Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
</code></pre>

**Comment by iwe7** [comment]
```

UeditorWidget.html:3 ERROR TypeError: Cannot read property 'offsetWidth' of null

```

**Comment by iwe7** [comment]
找到了，ngOnChanges的时候，dom还没有准备好！下面是ngx-ueditor的源码
```
ngOnChanges(changes: SimpleChanges): void {
    if (this.inited && changes.config) {
      this.destroy();
      this.init();
    }
  }
```

**Comment by iwe7** [comment]
崩溃！还是不行

**Comment by cipchk** [comment]
可能需要一个延迟 `setTimeout`，我会增强 ngx-ueditor 部分。

**Comment by iwe7** [comment]
我试过了， setTimeout不行，问题出在document.getElementById('')

**Comment by iwe7** [comment]
关闭Modal后，在打开，document.getElementById获取的是null,我setTimeout了一个很大的数字 还是如此，在console里打开直接运行是可以获取到的！

**Comment by iwe7** [comment]
找到原因了，ueditor是iframe所以document.getElementById获取不到，我去

**Comment by cipchk** [comment]
相关 https://github.com/cipchk/ngx-ueditor/issues/34
