### ISSUE TITLE
请问拦截器如何返回错误信息？

### ISSUE THREAD

**Issue by xingkoo** [ng-alain/ng-alain#452]
在拦截器里面有如下代码，用于拦截当出现错误时显示错误提示。
如果如下代码，将会导致订阅时，错误信息无法自行处理。
请问有什么改进办法？
````
// 继续抛出错误中断后续所有 Pipe、subscribe 操作，因此：
// this.http.get('/').subscribe() 并不会触发
return ErrorObservable.throw(event);
````

**Comment by liweitao92** [comment]
这个好像一直没啥好办法，现在 alain 的处理方式是让服务端返回 {statu:0/1,message} 通过 statu 的返回确定是否成功

**Comment by xingkoo** [comment]
我返回的结果是：
````
{
  status: [success|error],
  code: '',
  data: any，
  message:'msg'
}
````

我尝试使用
````
return Observable.create(observer => observer.next(event));
or
return Observable.create(observer => observer.next({test:123}));
````
会导出HttpHandler执行两次。

希望能够有解决办法。

**Comment by cipchk** [comment]
以下回答是在默认 default.inteceptor 的基础上。

执行两次是由于 `handleData` 在处理 200 状态码时，默认给出的示例代码是抛出 `throwError(event)`（可能部分看到的是 `ErrorObservable.throw(event)`），因为抛出错误导致 `intercept` 的 `catchError` 也捕获到并再一次执行了 `handleData`，可以将 `throwError({})` 一个空的错误使后面在捕获错误后能正常调取，但不会执行任何动作。

另外，`default.inteceptor` 的示例只是一个基于比较常规性的代码，具体细节不能直接套用。

**Comment by xingkoo** [comment]
感谢。我最终还是和以前一样，把success和throw分开处理了。
