### ISSUE TITLE
疑似ng-ant中Steps组件的bug

### ISSUE THREAD

**Issue by xingkoo** [ng-alain/ng-alain#454]
master分支下的最新代码。

![image](https://user-images.githubusercontent.com/2936579/40247941-cec42836-5b00-11e8-94f6-8af90e2d068f.png)
![image](https://user-images.githubusercontent.com/2936579/40247959-de0949fc-5b00-11e8-99af-c4ec7f8e9da0.png)

**Comment by cipchk** [comment]
请提供更有意义的 issues

**Comment by xingkoo** [comment]
图1   加载 **nz-steps** 组件传入 **nzCurrent** . 未做任何其他多余操作.

通过vs code加载chrome debug插件.启动调试模式后,报上面图2中的错误.  
直接在chrome中运行时并没有这个错误产生.

**Comment by cipchk** [comment]
================================
为了减少浪费时间；描述不清楚、不符合以下声明规范；会直接关闭。
================================
请务必认真先阅读以下说明：
1. 官方 issue 用于报告 bug 和需求建议，关于Angular、@delon/*、ng-zorro-antd 的使用和开发问题在这里可能不会得到解答，感谢您的理解。
2. 为了避免浪费时间在互相追问上，请：
    a. 是否已经在 ng-alain.com 文档站点或检索 Issues 中找到答案
    b. 若是bug，请填写复现步骤、在线演示（模板：https://stackblitz.com/edit/ng-alain-setup?file=app%2Fapp.component.ts）
    c. 若是需求，请尽可能描述清晰，有时图示胜过千言万语
    d. 提供源代码请务必使用 Markdown 格式
3. 建议使用英文进行提问，这样你的问题可以被更多的人阅读和回答。如果表达上确实较复杂，英文标题加中文描述也是可选的方案。

**Comment by xingkoo** [comment]
我试着在stackblitz上重现,但是在线并没有报错,可能是版本问题.我提交到ant官网吧.

![image](https://user-images.githubusercontent.com/2936579/40264789-77827d08-5b5e-11e8-8517-fad2305e6040.png)
