### ISSUE TITLE
1.0.3 使用Yarn 安装报错

### ISSUE THREAD

**Issue by thanatos915** [ng-alain/ng-alain#457]
1.0.3  npm 安装 没有问题，使用yarn 后，还是报 javascript 函数功能错误 @cipchk

**Comment by cipchk** [comment]
https://yarnpkg.com/lang/en/docs/cli/upgrade/

**Comment by thanatos915** [comment]
@cipchk 可以给我提供一个命令吗？ 我试了这些命令但是还是报错

**Comment by cipchk** [comment]
```bash
yarn add less@2.7.3 --exact
```

**Comment by thanatos915** [comment]
这命令我也试过了，还是不行 我在 node_modules/@angular-devkit/build-angular/node_modules/less/package.json 看见了，这里面使用less版本并没有改变 @cipchk

**Comment by cipchk** [comment]
@thanatos915 那我不是很清楚了，我晚点试一下 yarn.

**Comment by cipchk** [comment]
尝试以下：

```bash
yarn add less@~2.7.0 less-loader@~4.0.0
```
