### ISSUE TITLE
如何绑定JSON Schema的事件(formSubmit)到nz-modal(nzOnOk)事件

### ISSUE THREAD

**Issue by rurico** [ng-alain/ng-alain#458]
![image](https://user-images.githubusercontent.com/24207813/40340519-d931fe48-5db1-11e8-912f-71714e259100.png)
我想利用modal的确认触发sf组件的formSubmit事件,请问怎么实现.

**Comment by cipchk** [comment]
https://ng-alain.com/form/modal
