### ISSUE TITLE
cache在对具有get/set属性的对象进行缓存后再取出导致丢失get/set属性

### ISSUE THREAD

**Issue by jackywang615** [ng-alain/ng-alain#459]
## Bug Report or Feature Request (mark with an `x`)

<pre><code>
[x] Bug report -> please search issues before submitting
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Steps to reproduce

```javascript
class User {
id: string;

get name() {
   return 'abc';
 }
}
```

在对上面这个User对象进行缓存后再取出name属性就变成undefined了

## Environment

<pre><code>
ng-alain version: X.Y.Z
Angular version: X.Y.Z
Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
</code></pre>

**Comment by jackywang615** [comment]
对象中无法序列化成json的成员在重新取出时就会丢失

**Comment by cipchk** [comment]
这是必然的，因为 `get name` 实际是一种函数，函数是无法被当作 JSON 的一部分。
