### ISSUE TITLE
自己写abc引用，build编译错误“ Function calls are not supported in decorators”

### ISSUE THREAD

**Issue by lusess123** [ng-alain/ng-alain#462]
当我自己写abc引用模块的时候，dev阶段是正常的，build的时候会报编译错误。
## Bug 

<pre><code>
Date: 2018-05-24T00:21:58.433Z
Hash: 72603bf2c691bbdf3c02
Time: 8565ms
chunk {scripts} scripts.7411945f3ab2271ac8e4.js (scripts) 1.21 MB  [rendered]
chunk {0} runtime.a66f828dca56eeb90e02.js (runtime) 1.05 kB [entry] [rendered]
chunk {1} styles.be650b1ef172414ab3cf.css (styles) 488 kB [initial] [rendered]
chunk {2} polyfills.207dcc605630215505f5.js (polyfills) 130 bytes [initial] [rendered]
chunk {3} main.f58b96bf9bf614ca37d4.js (main) 128 bytes [initial] [rendered]

ERROR in Error during template compile of 'DelonABCRootModule'
  Function calls are not supported in decorators but 'AdErrorCollectModule' was called.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ng-alain@1.0.3 build: `ng build --prod --build-optimizer`
npm ERR! Exit status 1
</code></pre>

## delon.module.ts
<pre><code>
import {DelonABCModule} from './abc.module'
</code></pre>

## abc.module.ts
<pre><code>
import { NgModule, ModuleWithProviders } from '@angular/core';
import {
    AdErrorCollectModule,
    AdFooterToolbarModule,
    AdSidebarNavModule,
    AdDownFileModule,
    AdImageModule,
    AdAvatarListModule,
    AdDescListModule,
    AdEllipsisModule,
    AdGlobalFooterModule,
    AdExceptionModule,
    AdNoticeIconModule,
    AdNumberInfoModule,
    AdPageHeaderModule,
    AdResultModule,
    AdStandardFormRowModule,
    AdTagSelectModule,
    AdTrendModule,
    AdCountDownModule,
    AdSimpleTableModule,
   // AdReuseTabModule,
    AdFullContentModule,
    AdXlsxModule,
    AdZipModule,
    AdNumberToChineseModule,
   // AdLodopModule,
    AdQuickMenuModule,
  //  AdQRModule,
    // charts
    AdG2BarModule,
    AdG2CardModule,
    AdG2ChartModule,
    AdG2GaugeModule,
    AdG2MiniAreaModule,
    AdG2MiniBarModule,
    AdG2MiniProgressModule,
    AdG2PieModule,
    AdG2RadarModule,
    AdG2TagCloudModule,
    AdG2TimelineModule,
    AdG2WaterWaveModule
} from '@delon/abc'

const MODULES = [
    AdErrorCollectModule,
    AdFooterToolbarModule,
    AdSidebarNavModule,
    AdDownFileModule,
    AdImageModule,
    AdAvatarListModule,
    AdDescListModule,
    AdEllipsisModule,
    AdGlobalFooterModule,
    AdExceptionModule,
    AdNoticeIconModule,
    AdNumberInfoModule,
    AdPageHeaderModule,
    AdResultModule,
    AdStandardFormRowModule,
    AdTagSelectModule,
    AdTrendModule,
    AdCountDownModule,
    AdSimpleTableModule,
    //AdReuseTabModule,
    AdFullContentModule,
    AdXlsxModule,
    AdZipModule,
    AdNumberToChineseModule,
   // AdLodopModule,
    AdQuickMenuModule,
   // AdQRModule,
    // charts
    AdG2BarModule,
    AdG2CardModule,
    AdG2ChartModule,
    AdG2GaugeModule,
    AdG2MiniAreaModule,
    AdG2MiniBarModule,
    AdG2MiniProgressModule,
    AdG2PieModule,
    AdG2RadarModule,
    AdG2TagCloudModule,
    AdG2TimelineModule,
    AdG2WaterWaveModule,
  ];
  
  // endregion
  @NgModule({
    imports: [
      AdErrorCollectModule.forRoot(),
      AdFooterToolbarModule.forRoot(),
      AdSidebarNavModule.forRoot(),
      AdDownFileModule.forRoot(),
      AdImageModule.forRoot(),
      AdAvatarListModule.forRoot(),
      AdDescListModule.forRoot(),
      AdEllipsisModule.forRoot(),
      AdExceptionModule.forRoot(),
      AdExceptionModule.forRoot(),
      AdNoticeIconModule.forRoot(),
      AdNumberInfoModule.forRoot(),
      AdPageHeaderModule.forRoot(),
      AdResultModule.forRoot(),
      AdStandardFormRowModule.forRoot(),
      AdTagSelectModule.forRoot(),
      AdTrendModule.forRoot(),
      AdCountDownModule.forRoot(),
      AdSimpleTableModule.forRoot(),
      //AdReuseTabModule.forRoot(),
      AdFullContentModule.forRoot(),
     // AdXlsxModule.forRoot(),
     // AdZipModule.forRoot(),
      AdNumberToChineseModule.forRoot(),
     // AdLodopModule.forRoot(),
      AdQuickMenuModule.forRoot(),
     // AdQRModule.forRoot(),
      // charts
      AdG2BarModule.forRoot(),
      AdG2CardModule.forRoot(),
      AdG2ChartModule.forRoot(),
      AdG2GaugeModule.forRoot(),
      AdG2MiniAreaModule.forRoot(),
      AdG2MiniBarModule.forRoot(),
      AdG2MiniProgressModule.forRoot(),
      AdG2PieModule.forRoot(),
      AdG2RadarModule.forRoot(),
      AdG2TagCloudModule.forRoot(),
      AdG2TimelineModule.forRoot(),
      AdG2WaterWaveModule.forRoot(),
    ],
    exports: MODULES,
  })
  export class DelonABCRootModule {}
  
  @NgModule({ exports: MODULES })
  export class DelonABCModule {
    static forRoot(): ModuleWithProviders {
      return { ngModule: DelonABCRootModule };
    }
  }
</code></pre>

**Comment by cipchk** [comment]
没有必要单独引用模块，Tree Shaking 已经足够智帮你处理未使用的模块。

**Comment by lusess123** [comment]
@cipchk  问题不在这边，主要是我想排除AdReuseTabModule 来阻止标签复用， dev的时候没有问题，build就报错了

**Comment by Kiuyam** [comment]
如果你单纯的 不想路由复用 文档有说明 { text:'Dashboard', reuse: false } 
查看 https://ng-alain.com/components/reuse-tab
AdReuseTabModule 中有一些 service 是被其他地方调用的，单纯移除Module是错误的

**Comment by cipchk** [comment]
@Kiuyam 是对的

**Comment by lusess123** [comment]
@Kiuyam  tks
