### ISSUE TITLE
build 不显示中文

### ISSUE THREAD

**Issue by bxy2000** [ng-alain/ng-alain#463]
我没有选择多语言支持，yarn start时，表格，对话框按钮显示的都是中文，但是yarn build之后就显示英文了

使用如下命令创建项目也是一样
ng new demo --style less
ng add ng-alain
yarn build
...

**Comment by Kiuyam** [comment]
老哥，你能自己找找问题吗，这真不是bug。

1.没太看懂什么叫没有选择多语言支持。难道你取消 translate注入了？取消translate注入确定能build？

建议 
1.没有选择语言麻烦更换一下语言选项,在右上角。
2.再者查看i18n文件是否正常加载了。没正常加载请查看angular 发布后，加载静态文件的问题。右转百度 或 谷歌
3.怎么查看是否正常加载 请开Chrome 按 F12，或者右键检查，后查看console.log。

如果还不知道  愿主保佑你。---三体。

**Comment by Kiuyam** [comment]
老哥，你能自己找找问题吗，这真不是bug。

1.没太看懂什么叫没有选择多语言支持。难道你取消 translate注入了？取消translate注入确定能build？

建议 
1.没有选择语言麻烦更换一下语言选项,在右上角。
2.再者查看i18n文件是否正常加载了。没正常加载请查看angular 发布后，加载静态文件的问题。右转百度 或 谷歌
3.怎么查看是否正常加载 请开Chrome 按 F12，或者右键检查，后查看console.log。

如果还不知道  愿主保佑你。---三体。

**Comment by bxy2000** [comment]
ng-alain 在zorro0.6.5版本的时候，如果使用ng new -c=@delon demo 创建项目的时候，默认是没有多语言支持的，但是如果yarn start，运行正常，但是如果yarn build，对话框按钮和table没有数据时都显示英文，

在zorro0.7.0（目前版本），按照ng-alain创建项目步骤，ng new 之后 ng add ng-alain，然后添加一个table，或者对话框，yarn build的时候，运行，依然，显示英文

我想可能是那个地方需要设置，但是，，，不得而知。

**Comment by bxy2000** [comment]
感谢@Kiuyam的回答，但是，你可以按我说的步骤，buid一下，看看什么情况

具体步骤如下：
ng new demo --style less
cd demo
ng add ng-alain
ng serve

然后，在dashboard上加一个table，注意，数据data=[]，然后yarn build，放到web服务器里，表格显示的是英文（没有数据）。

**Comment by bxy2000** [comment]
也就是说yarn start，一切正常（显示中文），yarn build之后，放到web里，没有数据时，看到的是英文。

**Comment by bxy2000** [comment]
包括目前版本 git clone --depth=1 https://github.com/cipchk/ng-alain.git my-project ，npm install之后，yarn build，同样如此

**Comment by bxy2000** [comment]
我不认为这是bug，但是不知道如何设置，才能让控件显示中文，我不想支持多语言。

**Comment by Kiuyam** [comment]
你的项目，在build完后打开确定一点都不报错？console.log里面一点错误都没有？

原有demo是通过 translate 管道进行i18n转换的，
需要加载I18N json数据文件，
build完以后发现不是中文的很大原因，我估计就是I18N 静态资源没有加载成功。

解决办法，你直接把对应代码的 translate去掉，换成中文。

难道你直接写一个按钮或者table直接用中文做按钮文字 和 table表头 会变成英文？

**Comment by xingkoo** [comment]
全局配置当表格数据为空时的显示内容。

**Comment by 694551594** [comment]
我也遇到过这个问题。。这个是zorro的问题。和ng-alain没关系。我的解决办法就是按照zorro的说明文档配置了一下多语言为中文。可能他默认的是英文的。你不配置的话就是英文的、。

**Comment by bxy2000** [comment]
谢谢，同意你的说法，只是用了alain之后，配置都是alain的，不知道在哪配置zorro的东东。我现在只能把对话框，table的文本，按照zorro的相关属性，写成中文的。

是zorro的问题，但是alain框架应该设置一下：）

**Comment by xingkoo** [comment]
`
是zorro的问题，但是alain框架应该设置一下：）
`
还没有碰到这个问题.如上描述的情况下,是应该设置zorro的语言环境和ng-alain一致的.
