### ISSUE TITLE
need: custom data and simply update

### ISSUE THREAD

**Issue by xingkoo** [ng-alain/ng-alain#465]
## Bug Report or Feature Request (mark with an `x`)

<pre><code>
[ ] Bug report -> please search issues before submitting
[X] Feature request
[ ] Documentation issue or request
</code></pre>

## Reproduction link

https://stackblitz.com/edit/ng-alain-setup-e9ckfa

## What is expected?

有两种数据，原始数据、自定义数据（包含原始数据中的部分数据）
1、在页面上显示某个属性的值时，如果自定义数据中存在该属性，则优先显示自定义数据中的值，且可以有标识用于区分该数据来源于自定义数据的视觉效果。
2、在显示的某个属性上，通过交互（点击或其他操作）可以显示出一个简单的编辑器（文本框、下拉选择、单选等），用于更新当前属性值。

希望能够对该功能封装组件，类似自定义表单组件。
有父组件，用于传入原始数据及自定义数据，以及更新数据时所需要使用的api接口地址
有子组件，用于显示数据（根据上述描述1），以及编辑数据。可传入接口api用来覆盖父组件的接口地址，而独立使用一个api更新属性。

类似效果见上方链接。

## Environment

<pre><code>
ng-alain version: X.Y.Z
Angular version: X.Y.Z
Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
</code></pre>

**Comment by cipchk** [comment]
请用一个女朋友来交换该组件。

**Comment by xingkoo** [comment]
果然被关闭拉
能给个思路吗？

**Comment by cipchk** [comment]
@xingkoo  整体思路是可行的。

> 请尽量不要提交一些与 ng-alain 无关的东西，目前有 130 号人在 watch，意味者每个评论、每一个 issues 都会通知给这130人。
