### ISSUE TITLE
simple-table ，添加buttons时的bug

### ISSUE THREAD

**Issue by a9524** [ng-alain/ng-alain#467]
如图，若使用二级菜单，删除按钮中有   ##type='del'，不会弹出确认框，编辑按钮我跳转了一个新的路由地址，菜单不会关闭。
![image](https://user-images.githubusercontent.com/39616923/40534120-85a38fb6-6037-11e8-99d5-8984902e90d6.png)
![image](https://user-images.githubusercontent.com/39616923/40534208-e05d92a8-6037-11e8-8288-e346e6642537.png)
![image](https://user-images.githubusercontent.com/39616923/40534231-f3cda1a2-6037-11e8-8a1d-f28589d7861c.png)

**Comment by cipchk** [comment]
## Bug Report or Feature Request (mark with an `x`)

<pre><code>
[ ] Bug report -> please search issues before submitting
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Reproduction link



## Steps to reproduce



## What is expected?



## What is actually happening?



## Environment


<pre><code>
ng-alain version: X.Y.Z
Angular version: X.Y.Z
Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
</code></pre>

**Comment by iwe7** [comment]
不关闭的setTimeout(()=>{},0)

**Comment by cipchk** [comment]
1、`type:'del'` 麻烦给一个在线重现示例。
2、相关 issues https://github.com/NG-ZORRO/ng-zorro-antd/issues/1455 https://github.com/NG-ZORRO/ng-zorro-antd/issues/1530

**Comment by iwantacook** [comment]
这个情况之前有遇到过，具体版本忘了，与`type: 'del'`没有关系，就是这个下拉菜单，在点击选项，打开新页面的时候，不会自动关闭，与simple-table无关。（可能是错误的理解，抱歉）
