### ISSUE TITLE
CacheService Bug Report

### ISSUE THREAD

**Issue by xingkoo** [ng-alain/ng-alain#469]
## Bug Report or Feature Request (mark with an `x`)

<pre><code>
[x] Bug report -> please search issues before submitting
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Steps to reproduce

1、 使用如下代码，尝试从服务器获取数据字典时，并未发起http请求。查看@delon/cache源码中也未找到发起订阅请求的事件。
````
const value = this.cache.get('guest/dict/building-attributes');
````
感谢 @Alvin 提醒，文档中写有：缓存并返回Observable。这个是我疏忽了。
````
1、promise 表示若不存 key 则把 key 当URL发起请求并缓存且返回 Observable
````
个人认为，返回Observable的处理，与@delon/cache的设计理念是不一至的。
使用get方法，需要得到的是一个结果，而非Observable。
在目前这种情况下，如果未在本地缓存中找到数据，将会需要我自行判断返回的是值还是Observable对象，来进行后续的处理，并未能有效减少工作量。

2、 ````@delon/cache```` 中 ````DelonCacheConfig```` 未导出。
````
import { DelonCacheConfig } from '@delon/cache';
export function delonCacheConfig() {
  return {
    reName: 'cache'
  };
}
````
````
  static forRoot(): ModuleWithProviders {
    return {
      ngModule: DelonModule,
      providers: [
        { provide: DelonCacheModule, useFactory: delonCacheConfig }
      ],
    };
  }
````

## Environment

<pre><code>
ng-alain version: 1.0.2
Angular version: X.Y.Z
Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
</code></pre>

**Comment by cipchk** [comment]
异步无法当同步使。

**Comment by xingkoo** [comment]
就像描述中写的一样，预期返回的是一个结果，而有可能返回了一个Observable。
那么我就需要来区分他返回的是不是我想要的数据，返回预期，我直接使用就可以。
如果不是我想要的数据，我还需要再次处理。那么就不能做到全局通用了，需要每个使用到的地方都需要做一定的判断处理。
有没有可能通一一下，哪怕全都返回Observable，至少多处使用的时候，我能够再次做一个封装来解决数据处理机制。

**Comment by cipchk** [comment]
异步无法当同步使。
异步无法当同步使。
异步无法当同步使。
