### ISSUE TITLE
CacheService 不能获取值

### ISSUE THREAD

**Issue by FlowPeakFish** [ng-alain/ng-alain#471]
在不同Component中，cache不能获取值，更新前("version": "1.0.0-beta.5")是可以成功获取的
set，clear可以正常运行，get getNone不可以，现在在localStorage['user']获取

当前版本：1.0.4 ng-alain

**Comment by cipchk** [comment]
b. 若是bug，请填写复现步骤、在线演示（模板：https://stackblitz.com/edit/ng-alain-setup?file=app%2Fapp.component.ts）

**Comment by FlowPeakFish** [comment]
stackblitz用不起来，一直报这个错，也不知道怎么调节版本
![image](https://user-images.githubusercontent.com/29328241/40603971-19f15a7c-6290-11e8-97bf-e03ec3ec33ea.png)

之前1.0beta还正常，主要思路：
passport/login成功登录后，会
        this.cache.set('user', user);
设置一个值，存储用户的id

然后在默认拦截器里面每次请求会加上用户信息
var user = this.cache.getNone('user') as any;
console.log(user)
            if (user != null) {
                newBody += "&userid=" + user.id;
            }
newReq = req.clone({
                url: url,
                body: newBody
            });

每次请求的都是
![image](https://user-images.githubusercontent.com/29328241/40604046-595e5322-6290-11e8-9dfe-89e6b0f67b84.png)

最后尝试在用同一个Component就可以正常提取出来，分开就不可以了_(:з」∠)_

现在这样先凑活用着
var user = JSON.parse(localStorage['user']) as any;
            if (user != null) {
                newBody += "&userid=" + user.id;
            }
