### ISSUE TITLE
1.0.5 npm install 报错

### ISSUE THREAD

**Issue by billpeace** [ng-alain/ng-alain#472]
22381 warn ng-alain@1.0.5 No repository field.
22382 verbose type version
22383 verbose stack codepage: No matching version found for codepage@1.13.1
22383 verbose stack     at pickManifest 
22384 verbose cwd E:\project\angular study\ng-alain
22385 verbose Windows_NT 10.0.17134

22387 verbose node v10.2.1
22388 verbose npm  v6.1.0
22389 error code ETARGET
22390 error notarget No matching version found for codepage@1.13.1
22391 error notarget In most cases you or one of your dependencies are requesting
22391 error notarget a package version that doesn't exist.
22391 error notarget
22391 error notarget It was specified as a dependency of 'ng-alain'
22392 verbose exit [ 1, true ]

**Comment by cipchk** [comment]
ng-alain 都有相应的ci通过后才会发布，其中有一项是对 https://cipchk.github.io/ng-alain/ 校验。

我想也许是网络的问题，哎……可能你没有女朋友吧，连网络都欺负你。

**Comment by billpeace** [comment]
不会一直欺负我，早上在公司的网络 也报错
