### ISSUE TITLE
reuse-tab丢失参数

### ISSUE THREAD

**Issue by fatesq** [ng-alain/ng-alain#473]
reuse-tab 打开一个带queryParams参数的标签页，点击标签页切换时，参数会丢失

**Comment by cipchk** [comment]
https://ng-alain.com/components/reuse-tab#%E5%8C%B9%E9%85%8D%E6%A8%A1%E5%BC%8F
除此之外 都不支持。

**Comment by fatesq** [comment]
如果需要带参数的标签页，有什么好的方法吗

**Comment by zdxxxxxx** [comment]
遇到同样的问题了

**Comment by cipchk** [comment]
若是路由可以在路由，可以指定路由参数 `data: { reuse: true | false }` 它的优先级高于一切。
