### ISSUE TITLE
新版本打包后丢 nginx 报错

### ISSUE THREAD

**Issue by smile2014** [ng-alain/ng-alain#474]
main.e6f502bfb69c28cbcb6f.js:1 ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'resolveComponentFactory' of undefined
TypeError: Cannot read property 'resolveComponentFactory' of undefined
    at t.e.createContainer (main.e6f502bfb69c28cbcb6f.js:1)
    at t.e (main.e6f502bfb69c28cbcb6f.js:1)

**Comment by cipchk** [comment]
学会宽容，要有一颗宽容的爱心！

**Comment by luokyme** [comment]
啥情况？

**Comment by smile2014** [comment]
开发模式跑的很正常丢nginx就报这个错，不好找问题

**Comment by smile2014** [comment]
@busyluo 有什么好办法调试没

**Comment by cipchk** [comment]
https://github.com/angular/angular-cli/wiki/serve
可以增加 `-aot` 和 `-prod` 试着定位一下范围。

**Comment by smile2014** [comment]
就是用的这个，编译没任何报错，只是在nginx允许就报错了

**Comment by smile2014** [comment]
在试着排查了，谢谢了@cipchk

**Comment by smile2014** [comment]
at NzMessageService.push../node_modules/ng-zorro-antd/esm5/antd.js.NzMessageBaseService.createContainer (vendor.js:156456)
    at NzMessageService.NzMessageBaseService (vendor.js:156391)
    at new NzMessageService (vendor.js:156470)

**Comment by skyoLion** [comment]
刚好碰到了同样的问题，这个是bug吗？暂时运行没问题，但是看到console有报错了

**Comment by smile2014** [comment]
好像是目前没办法支持angular6 ,如果开发模式是没问题，丢nginx或者tomcat里就有问题

**Comment by smile2014** [comment]
莫名其妙的又可以了，什么都没做，无语了

**Comment by skyoLion** [comment]
暂不影响功能，那就先不管了。
