### ISSUE TITLE
sf动态表单，异步数据源，设置默认值无效

### ISSUE THREAD

**Issue by lei1996** [ng-alain/ng-alain#476]
## Bug Report or Feature Request (mark with an `x`)

<pre><code>

//异步数据源，设置默认值无效。
ExchangeId: {
              type: 'string',
              title: '选择交易所',
              ui: {
                  widget: 'select',
                  asyncData: () => this.user.exchangesList({})
              },
              // default: this.record.id
              default: 1,
},

</code></pre>

**Comment by lei1996** [comment]
用的select 选择器， 不是联级选择器。

**Comment by cipchk** [comment]
阿弥陀佛！

**Comment by pengb0** [comment]
默认值应该在formData里设置吧
