### ISSUE TITLE
1.0.5版本控制台输出格式会乱

### ISSUE THREAD

**Issue by EvilVarmilo** [ng-alain/ng-alain#478]
![tim 20180530210317](https://user-images.githubusercontent.com/30097401/40721808-23d4060c-644d-11e8-81fd-88fbcbd580ec.png)

## Bug Report or Feature Request (mark with an `x`)

<pre><code>
[ ] Bug report -> please search issues before submitting
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Environment

<pre><code>
ng-alain version: X.Y.Z
Angular version: X.Y.Z
Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
</code></pre>

**Comment by cipchk** [comment]
你是多么的强迫症呀。

这是 webpacker4 产生的，我们无法左右。任何 angular6 项目都会产生这样的格式。
