### ISSUE TITLE
simple-table 下当总量小于每页数量时 自动隐藏分页器  问题

### ISSUE THREAD

**Issue by ghost** [ng-alain/ng-alain#479]
以下情形考虑一下，比如： 一开始查询按10条进行分页显示（总数量是20条），然后在分页器 选择30条显示，分页器自动隐藏了， 然后就切换不回按10条显示了

**Comment by duxie** [comment]
补充: 在总条数为0时,分页器无法自动隐藏
https://stackblitz.com/edit/ng-alain-setup-wflfbp?file=src%2Fapp%2Fapp.component.ts

**Comment by cipchk** [comment]
属性 ng-zorro-antd 请至 https://github.com/NG-ZORRO/ng-zorro-antd/issues 中提交。

**Comment by cipchk** [comment]
https://github.com/NG-ZORRO/ng-zorro-antd/pull/1583

**Comment by cipchk** [comment]
持续跟踪 https://github.com/NG-ZORRO/ng-zorro-antd/pull/1585 并进一步改进自动隐藏功能。

**Comment by cipchk** [comment]
我重新梳理一下两个问题：

1. 自动隐藏若从高至低页码进行切换时会无法再次切换回来，这个问题无解，不再处理。
2. 总条数为0分页器无法隐藏，已经发布请核实 `1.0.0@next` 版本
