### ISSUE TITLE
cdn problem

### ISSUE THREAD

**Issue by asself** [ng-alain/ng-alain#480]
Can I use my local font instead of cdn fonts(https://at.alicdn.com/t/font_zck90zmlh7hf47vi.woff)?

**Comment by cipchk** [comment]
```less
// in `styles/theme.less`
@icon-url: "<path>";
```

**Comment by asself** [comment]
The ng-alain version I use is 0.7.0. When I try to add @ icon-url in 'styles / custom-variables.less', I find that iconfont will be loaded twice, one from the local and the other from cdn. Is this a bug that has been fixed? How can I solve this problem if I still use this version for the time being?

**Comment by cipchk** [comment]
sorry, i can't, this is ng-zorro-antd `0.6.x` bug.
