### ISSUE TITLE
ng build --prod 打包发布之后，部分组件文字变英文

### ISSUE THREAD

**Issue by HeRunKang** [ng-alain/ng-alain#483]
问题：
ng serve 本地运行正常
![image](https://user-images.githubusercontent.com/25625730/40822179-980eb714-659d-11e8-86d8-dbe9c9a52ade.png)
![image](https://user-images.githubusercontent.com/25625730/40822250-f5db35f2-659d-11e8-96a1-f66f98c2b956.png)
![image](https://user-images.githubusercontent.com/25625730/40822237-ed528c6e-659d-11e8-9e54-3e82cac7c5a1.png)

ng build --prod 打包发布之后，部分组件文字变英文
![image](https://user-images.githubusercontent.com/25625730/40822208-bd4a20cc-659d-11e8-9606-9cce0f5cbbf4.png)
![image](https://user-images.githubusercontent.com/25625730/40822218-c8af4a5a-659d-11e8-9af1-6de0ac599639.png)
![image](https://user-images.githubusercontent.com/25625730/40822226-dacc5ec6-659d-11e8-8199-e8bb3626c514.png)

ng-alain版本：1.0.4
项目是使用 angular-cli 6.0.5 建的
ng new demo --style less
cd demo
ng add ng-alain

app.module.ts 里面配置没改变
`// angular i18n
import { registerLocaleData } from '@angular/common';
import localeZhHans from '@angular/common/locales/zh-Hans';
registerLocaleData(localeZhHans);`
`  providers: [
    { provide: LOCALE_ID, useValue: 'zh-Hans' },
...
]`

angular.json配置也没有改变
`{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
  "newProjectRoot": "projects",
  "projects": {
    "shop": {
      "root": "",
      "sourceRoot": "src",
      "projectType": "application",
      "prefix": "app",
      "schematics": {
        "@schematics/angular:component": {
          "styleext": "less"
        }
      },
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "outputPath": "dist/shop",
            "index": "src/index.html",
            "main": "src/main.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "src/tsconfig.app.json",
            "assets": [
              "src/favicon.ico",
              "src/assets"
            ],
            "styles": [
              "src/styles.less"
            ],
            "scripts": []
          },
          "configurations": {
            "production": {
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ],
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "aot": true,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true
            }
          }
        },
        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "options": {
            "browserTarget": "shop:build"
          },
          "configurations": {
            "production": {
              "browserTarget": "shop:build:production"
            }
          }
        },
        "extract-i18n": {
          "builder": "@angular-devkit/build-angular:extract-i18n",
          "options": {
            "browserTarget": "shop:build"
          }
        },
        "test": {
          "builder": "@angular-devkit/build-angular:karma",
          "options": {
            "main": "src/test.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "src/tsconfig.spec.json",
            "karmaConfig": "src/karma.conf.js",
            "styles": [
              "src/styles.less"
            ],
            "scripts": [],
            "assets": [
              "src/favicon.ico",
              "src/assets"
            ]
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": [
              "src/tsconfig.app.json",
              "src/tsconfig.spec.json"
            ],
            "exclude": [
              "**/node_modules/**"
            ]
          }
        }
      }
    },
    "shop-e2e": {
      "root": "e2e/",
      "projectType": "application",
      "architect": {
        "e2e": {
          "builder": "@angular-devkit/build-angular:protractor",
          "options": {
            "protractorConfig": "e2e/protractor.conf.js",
            "devServerTarget": "shop:serve"
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": "e2e/tsconfig.e2e.json",
            "exclude": [
              "**/node_modules/**"
            ]
          }
        }
      }
    }
  },
  "defaultProject": "shop",
  "schematics": {
    "ng-alain:module": {
      "routing": true,
      "spec": false
    },
    "@schematics/angular:module": {
      "routing": true,
      "spec": false
    },
    "@schematics/angular:component": {
      "spec": false,
      "flat": false,
      "inlineStyle": true,
      "inlineTemplate": false
    },
    "@schematics/angular:directive": {
      "spec": false
    },
    "@schematics/angular:service": {
      "spec": false
    }
  }
}`

小弟愚钝，请指教

**Comment by HeRunKang** [comment]
忘了一点，这里出现英文的组件都是  ng-zorro-antd(0.7.1)  的组件

**Comment by cipchk** [comment]
https://github.com/cipchk/ng-alain/blob/master/src/app/app.module.ts#L22

**Comment by HeRunKang** [comment]
已解决。
因为我不需要国际化，为了节省那一点点大小，我最终还是没有引入国际化模块。

ng build 的时候只有 --prod 才会出现这个问题，
通过提示文字精确搜索，发现对应的中英文转换是在ng-zorro-antd目录下的zh_CH，而项目中并没有引入这个js，所以去看了一下ng-zorro的官网文档
https://ng.ant.design/docs/i18n/zh

在app.module.ts中使用这个js就可以了

`import { NZ_I18N, zh_CN } from 'ng-zorro-antd';`
`providers:[
...
{ provide: NZ_I18N, useValue: zh_CN }
],`
