### ISSUE TITLE
无法加载/sys/log路由

### ISSUE THREAD

**Issue by ddpmz** [ng-alain/ng-alain#488]
按教程
ng new demo --style less
cd demo
ng add ng-alain
ng serve 正常显示
创建一个模块ng g ng-alain:module sys
加入{ path: 'sys', loadChildren: './sys/sys.module#SysModule' }
创建一个日志列表页ng g ng-alain:list log -m=sys
后，在地址栏上输入http://localhost:4200/#/sys/log，弹出无法加载/sys/log路由的错误
mac和windows上都试过了，是生成的模块html有问题吗？
![20180603104057](https://user-images.githubusercontent.com/3666795/40882638-c1250f30-671a-11e8-8212-a73c72568e0c.png)

**Comment by cipchk** [comment]
可以打开开发面板，自行了解错误细节。

**Comment by xingkoo** [comment]
检查一下生成的log.list.component具体的位置,以及在模块路由中是否配置.

**Comment by theheros** [comment]
我也是这个问题，大家用最新的，这样开始没有问题么？

**Comment by theheros** [comment]
@renfan 请问您是怎么解决的？

**Comment by ddpmz** [comment]
@theheros 我没有解决，我换git clone的方法，然后出现了另一个错误 #490

**Comment by theheros** [comment]
@renfan 我也是这样，初次接触这个。直接强加路由也不行。都是同一个错误。

>ERROR Error: Uncaught (in promise): ReferenceError: Ajv is not defined
ReferenceError: Ajv is not defined
    at new AjvSchemaValidatorFactory (form.js:1452)
    at _createClass (core.js:9262)
    at _createProviderInstance$1 (core.js:9234)

**Comment by cipchk** [comment]
@theheros 的确有这个问题，可以在 `angular.json` 加上：

```
"scripts": [
    "node_modules/ajv/dist/ajv.bundle.js"
]
```

**Comment by ddpmz** [comment]
可以了，谢谢 @cipchk

**Comment by linshaoqi** [comment]
我下载了最新版ng-alain，出现了同样的问题，发现是没有"node_modules/ajv/dist/ajv.bundle.js"这个文件。

**Comment by linshaoqi** [comment]
core.js:6150 ERROR Error: Uncaught (in promise): ReferenceError: Ajv is not defined
ReferenceError: Ajv is not defined
    at new AjvSchemaValidatorFactory (form.js:1649)
    at Object.factory (core.js:11474)
    at R3Injector.hydrate (core.js:11373)
    at R3Injector.get (core.js:11194)
    at NgModuleRef$1.get (core.js:25269)
    at R3Injector.get (core.js:11205)
    at NgModuleRef$1.get (core.js:25269)
    at Object.get (core.js:24983)
    at lookupTokenUsingModuleInjector (core.js:3327)
    at getOrCreateInjectable (core.js:3439)
    at resolvePromise (zone-evergreen.js:1209)
    at resolvePromise (zone-evergreen.js:1163)
    at zone-evergreen.js:1275
    at ZoneDelegate.invokeTask (zone-evergreen.js:402)
    at Object.onInvokeTask (core.js:28515)
    at ZoneDelegate.invokeTask (zone-evergreen.js:401)
    at Zone.runTask (zone-evergreen.js:174)
    at drainMicroTaskQueue (zone-evergreen.js:578)
defaultErrorLogger @ core.js:6150
handleError @ core.js:6198
next @ core.js:29135
schedulerFn @ core.js:25882
__tryOrUnsub @ Subscriber.js:183
next @ Subscriber.js:122
_next @ Subscriber.js:72
next @ Subscriber.js:49
next @ Subject.js:39
emit @ core.js:25872
(anonymous) @ core.js:28554
invoke @ zone-evergreen.js:368
run @ zone-evergreen.js:130
runOutsideAngular @ core.js:28457
onHandleError @ core.js:28554
handleError @ zone-evergreen.js:372
runGuarded @ zone-evergreen.js:143
api.microtaskDrainDone @ zone-evergreen.js:1070
drainMicroTaskQueue @ zone-evergreen.js:585
Promise.then (async)
scheduleMicroTask @ zone-evergreen.js:561
scheduleTask @ zone-evergreen.js:392
onScheduleTask @ zone-evergreen.js:279
scheduleTask @ zone-evergreen.js:382
scheduleTask @ zone-evergreen.js:217
scheduleMicroTask @ zone-evergreen.js:237
scheduleResolveOrReject @ zone-evergreen.js:1262
resolvePromise @ zone-evergreen.js:1200
(anonymous) @ zone-evergreen.js:1116
webpackJsonpCallback @ bootstrap:25
(anonymous) @ sys-sys-module.js:1

**Comment by cipchk** [comment]
@linshaoqi 应该是没有安装好 AJV，目前支持的 `6.x` 版本。

**Comment by linshaoqi** [comment]
@cipchk 安装6.12.5版可以，感谢感谢。
