### ISSUE TITLE
如何通过文件路径获取本地图片文件？

### ISSUE THREAD

**Issue by hancongduan** [ng-alain/ng-alain#489]
在项目assets文件夹中的img文件夹里面存了图片1.png，想要通过路径获取图片文件并将图片文件传给后台，在获取图片文件时，因为assets文件夹下的app-data.json文件可通过http请求的get方法获取json的内容，通过http请求的get方法获取图片文件，但是获取不到文件，请问如果获取？
<pre><code>
this.httpClient.get('assets/app-data.json').subscribe(res => {
       console.log(res);
});
</code>
</pre>
通过上述代码可以得到app-data.json的内容。
<pre><code>
this.httpClient.get('assets/img/1.png').subscribe(res => {
      let blob = new Blob([res], {
            type: 'image/png'
      })
      console.log(blob);
});
</code>
</pre>
但是获取图片文件时，什么都无法得到。
请问如何获取图片文件？

**Comment by cipchk** [comment]
Angular 基础知识。

`.get` 默认返回的是 `json` 数据，完整的 api 请至 [Angular 官网](https://angular.io/api/common/http/HttpClient#get)，了解其中：`observe` 和 `responseType`

**Comment by xingkoo** [comment]
````
  preview() {
    const image: any = new Image();
    const myReader: FileReader = new FileReader();
    const that = this;
    myReader.onloadend = (loadEvent: any) => {
      image.src = loadEvent.target.result;
      that.cropper.setImage(image);
    };

    myReader.readAsDataURL(this.file);
  }
````
供参考
