### ISSUE TITLE
git clone出来的项目，新增模块路径不对

### ISSUE THREAD

**Issue by ddpmz** [ng-alain/ng-alain#490]
使用git clone生成的项目用新增页面的命令，
生成的文件在app/routes/sys目录下，而不在src/app/routes/sys目录下，
请问这个可以在哪里配置吗？
<img width="420" alt="wx20180605-024640 2x" src="https://user-images.githubusercontent.com/3666795/40935457-d154f630-686a-11e8-9256-a989f647a05c.png">

**Comment by cipchk** [comment]
请使用 ng add ng-alain 来构建脚手架。
