### ISSUE TITLE
@delon/form custom Widget Bug

### ISSUE THREAD

**Issue by xingkoo** [ng-alain/ng-alain#492]
## Bug Report or Feature Request (mark with an `x`)

<pre><code>
[X] Bug report -> please search issues before submitting
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Reproduction link

https://stackblitz.com/edit/ng-alain-setup-2pzjvu

## What is expected?

不影响自定义节点

## What is actually happening?

异步加载表单数据后, 自定义节点消失不见了.
参见stackblitz中的Logo属性.当异步加载表单数据时,自定义模板被移除掉了.

## Environment

<pre><code>
ng-alain version: X.Y.Z
Angular version: X.Y.Z
Browser:
- [x] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
</code></pre>

**Comment by cipchk** [comment]
谢谢反馈。

**Comment by xingkoo** [comment]
使用过程中发现的.我们应该感谢你提供这么强大的plan才对.

**Comment by xingkoo** [comment]
已经在4天前标记了fixed,但是因为一直没有发布,所以这个功能一直在等待.
类似的fixed问题如何在看到有标记fixed后,未发布新版本前如何解决这个问题呢?
按时间来看,应该今天会发布新版本吧?
