### ISSUE TITLE
组件没有触发销毁钩子

### ISSUE THREAD

**Issue by wulifangy** [ng-alain/ng-alain#493]
当路由跳转时，未触发销毁钩子

**Comment by cipchk** [comment]
主动久了，也累了，不想再主动！

**Comment by yunClouds** [comment]
@cipchk what?

**Comment by yunClouds** [comment]
o..
delonModule->RouteReuseStrategy

**Comment by wulifangy** [comment]
@yunClouds @cipchk  thanks.我会好好学习的，不辜负作者的机遇之恩。
