### ISSUE TITLE
ACLService设置路由守卫失效

### ISSUE THREAD

**Issue by hancongduan** [ng-alain/ng-alain#494]
你好，目前想设置在登录页面，用户登录时，对不同角色的用户，页面左侧的菜单栏的某些菜单隐藏起来，使用ACLService的setRole方法设置了角色为user2，在app-data.json中相对应的菜单中设置了"acl": "user1"，登录后发现ACLService中角色发生变化为user1，但MenuService中的ACLService未发生变化，具体代码如下：
在登录页面：

```
this.aclServic.setFull(false);
this.aclServic.setRole(["user2"]);
this.menuService.resume();
console.log(this.aclServic);
console.log(this.menuService);
```

在app-data.json中：

```
{
       "text": "通讯管理",
       "link": "/backstage/adapter/listAdapter",
       "reuse": true,
       "acl": "user1"
}
```

用户依然可以看到通讯管理页面，打印出的结果中，ACLService中角色发生变化为user2，但MenuService中的ACLService未发生变化，请问这种情况是否还需要其他设置？

**Comment by cipchk** [comment]
ng-alain 不建议直接修改 `app-data.json` 来管理你的菜单数据，应该由后端 自行根据用户返回菜单数据。

**Comment by hancongduan** [comment]
在adapter-routing.module.ts文件中设置

` path:'listAdapter', component: ListAdapterComponent, canActivate: [ ACLGuard ], data: {title: '通讯协议管理', guard: 'user1'}`

也是无效
