### ISSUE TITLE
@delon/cli文档中没有了？

### ISSUE THREAD

**Issue by ZhangWren** [ng-alain/ng-alain#496]
![image](https://user-images.githubusercontent.com/25240164/41074158-3e52ccf6-6a39-11e8-964e-ea6e1b221884.png)
依稀记得曾经官方文档中是有记录@delon/cli的安装使用，但是现在我却怎么也找不到了，npm官网中也没有了，所以想问下，想使用@delon/cli必须升级到ng6么？升级到ng6就可以直接使用ng add等命令么？

**Comment by cipchk** [comment]
https://ng-alain.com/docs/changelog-v6
https://ng-alain.com/cli/getting-started
