### ISSUE TITLE
feat(abc:simple-form): 简化HTML模板表单的运用

### ISSUE THREAD

**Issue by cipchk** [ng-alain/ng-alain#498]
## 前述

在 ng-alain 中使用表单有三种方式：

- @delon/form 动态表单
- Angular 响应式表单
- Angular HTML模板表单

三者最大的区别在于可测试性和代码量由高到低。而现在的探讨的是后两者，一个表单需要呈现若干元素：

![form-input](https://user-images.githubusercontent.com/2987467/41083020-b7f9ad08-6a62-11e8-854e-0dd2cd60a478.png)
> 上图为 `@delon/form` 动态表单的实现细节

在动态表单中非常容易实现，而对于后两者的实现唯一共同之处：大量HTML支持。

```html
<nz-form-item>
    <nz-form-label [nzSpan]="8" nzRequired>方法</nz-form-label>
    <nz-form-control [nzSpan]="16">
        <input nz-input formControlName="method" name="method" maxlength="30" required>
        <nz-form-explain *ngIf="validateForm.get('note').dirty && validateForm.get('note').errors">Please input your username!</nz-form-explain>
    </nz-form-control>
</nz-form-item>
```

> 响应式表单也略同。

而如果我们希望一行两列表单元素，这太常见，则：

```html
<nz-row [nzGutter]="24">
    <nz-col [nzSpan]="12">
        <nz-form-item nzFlex>
            <nz-form-label [nzSpan]="8" nzRequired>方法</nz-form-label>
            <nz-form-control style="flex: 1 0 auto;">
                <input nz-input formControlName="method" name="method" maxlength="30" required>
                <nz-form-explain *ngIf="validateForm.get('note').dirty && validateForm.get('note').errors">Please input your username!</nz-form-explain>
            </nz-form-control>
        </nz-form-item>
    </nz-col>
    <nz-col [nzSpan]="12">
        <nz-form-item nzFlex>
            <nz-form-label [nzSpan]="8" nzRequired>名称</nz-form-label>
            <nz-form-control style="flex: 1 0 auto;">
                <input nz-input formControlName="name" name="name" maxlength="30" required>
                <nz-form-explain *ngIf="validateForm.get('note').dirty && validateForm.get('note').errors">Please input your username!</nz-form-explain>
            </nz-form-control>
        </nz-form-item>
    </nz-col>
</nz-row>
```

对于 ng-alain 而言，动态表单可以解决大部分场景，我们也希望尽可能的使用它们，然而事实还是需要在一些场合里使用Angular表单。

这对于选择而言依然需要大量的HTML，ng-zorro-antd 默认使用文本边框红色来表示错误。

同时若你希望更详细的错误反馈还需要维护 `nz-form-explain` 组件，而维护这个节点是非常麻烦的，一个用户名的错误反馈文本包括：

- 用户名必填
- 用户名最多5至15个字符
- 用户名只能由字母、数字组合
- 用户名已经存在

你可能需要维护四个节点，当然情况下你只需要维护一到二个。这对于我们中后台而已依然很蛋疼，是否应该思考一下，有些表单元素是否真的是必要的呢？

比如这里的错误文本视觉、布局，尝试把一行两列的表单变成：

```html
<nz-row [nzGutter]="24">
    <nz-col [nzSpan]="12">
        <simple-form-item term="方法">
          <input nz-input formControlName="method" name="method" maxlength="30" required>
        </simple-form-item>
    </nz-col>
    <nz-col [nzSpan]="12">
        <simple-form-item term="名称">
          <input nz-input formControlName="name" name="method" maxlength="30" required>
        </simple-form-item>
    </nz-col>
</nz-row>
```

我们依然还需要维护布局，然而就中台而言布局应该是**绝大部分**是等同固定的，于是：

```html
<simple-form-item term="方法">
  <input nz-input formControlName="method" name="method" maxlength="30" required>
</simple-form-item>
<simple-form-item term="名称">
  <input nz-input formControlName="name" name="name" maxlength="30" required>
</simple-form-item>
```

视乎还需要一些特殊的情况，我们可以利用 `col="1"` 来表示占1整列（antd的栅格系统是 `24` 列，`col` 的默认值为 `2` 时），比如：

```html
<simple-form-item term="方法">
  <input nz-input formControlName="method" name="method" maxlength="30" required>
</simple-form-item>
<simple-form-item term="名称">
  <input nz-input formControlName="name" name="name" maxlength="30" required>
</simple-form-item>
<simple-form-item term="描述" col="1">
  <textarea nz-input formControlName="remark" name="remark">
</simple-form-item>
```

假如你把响应式的代码也放弃了，则变成这样子：

```html
<simple-form-item term="方法">
  <input nz-input [(ngModel)]="method" name="method" maxlength="30" required>
</simple-form-item>
<simple-form-item term="名称">
  <input nz-input [(ngModel)]="name" name="name" maxlength="30" required>
</simple-form-item>
<simple-form-item term="描述" col="1">
  <textarea nz-input [(ngModel)]="remark" name="remark">
</simple-form-item>
```

## 总结

`simple-form-item` 将主动放弃一些东西，而转向一些开发效率上极致。假如这样的组件，你怎么看？

**Comment by winpzs** [comment]
这个有点过细的插手到开发了，这种场景应该是每个项目组自己封吧。
就比如上面验证提示，我们就不是要这样出的。

**Comment by blueisboy** [comment]
完全不需要这样做，当然，想不想有是您的自由。
另外，如果内部不是封装的 nz-form-item（label、control）的话我个人还是比较支持楼楼的。

**Comment by HengYuLuck** [comment]
对于初级程序员不会封装的来说 更喜欢 楼主封装好代码以后 直接去用，可以简化html代码，便于后期维护，可以提高开发效率。 然而对于一些高级编程人员，可能更习惯于根据自己的业务场景不同去封装自己的表单验证。

**Comment by zoeelf** [comment]
维护错误反馈文本
这是我一个不成熟的想法。能不能借鉴Entity Framework ，我们可以对表单实体属性进行注释，统一维护一个表单实体和组件分离，在用Typescript中属性装饰器来实现这种效果呢
public class CustomerMetaData
{
    // Require that the Title is not null.
    // Use custom validation error.
    [Required(ErrorMessage = "Title is required.")]
    public object Title;

    // Require that the MiddleName is not null.
    // Use standard validation error.
    [Required()]
    public object MiddleName;
}

**Comment by cipchk** [comment]
@linjianpin136 一个不错的想法，不过数据校验与表单元素二者很难非常好的配对，一个 `string` 可以理解为 `input`，然而实体是一个更复杂的时候，反而是一种累赘。

其实这种方式对于动态表单可能会更适合。

**Comment by mango-csl** [comment]
一直有个疑问，formControl作用体现在哪里，其对自定义验证规则的复用，也很捉急。后来封装了一个基于rxjs的动态form组件，对表单涉及到的元素进行组件编写，支持自定义规则的复用和扩展，感觉用的还好，暂不支持自定义组件。
[primeng-form-builder](https://github.com/mango-csl/primeng-form-builder)
