### ISSUE TITLE
Feature Color selected

### ISSUE THREAD

**Issue by xingkoo** [ng-alain/ng-alain#499]
我记得原来有颜色选择器的.现在整个站点上都没有找到.
希望能够恢复出来,另外在动态表单中添加进来更好拉.
只要是有需求让用户自定义一些信息的情况下,颜色选盘就非常有价值的.

如果您认为这个可以封装到动态表单中的话,也可以试着告诉我如何操作,我也试着贡献一份力量.

**Comment by cipchk** [comment]
不会考虑增加除 ng-zorro-antd 基础组件以外的部件。
