### ISSUE TITLE
请教下core module 和 shared module 是如何界定的

### ISSUE THREAD

**Issue by dyh333** [ng-alain/ng-alain#5]
如题，想请教下这两个module是如何界定放置的内容的。
感觉两个模块中放置的都是通用性的组件、样式或服务。
谢谢。

**Comment by cipchk** [comment]
简短的回答：见官网 [NgModule](https://angular.io/guide/ngmodule#shared-modules)。

以下是略为复杂点说明。

当复杂应用时，会有很多子模块代表着不同的子业务。

然而，总有一些共享的东西；这些共享的事物放在 `SharedModule`，而 `SharedModule` 这一模块会在每个模块中被导入。

但是又有一些看起来是共享，但又**不需要**在每个模块中需要导入的，比如一些 Service 服务，他们是一些单例没有必要在每个模块中被导入，因此放在 `CoreModule` 当中，只会在根模块中一次导入。

**Comment by dyh333** [comment]
明白。学习了。谢谢！

**Comment by dyh333** [comment]
@cipchk 再请教一下，你在shared模块中有两个service，colors和scroll。官网NgModule中建议是shared module不放service。因为多个模块引用shared module会生成多份service副本，而colors service应该有一份单例就够了，所以是不是把service移到core module中比较合适呢？

**Comment by cipchk** [comment]
谢谢提醒，有点历史性问题，所以导致这样的。
