### ISSUE TITLE
能否为reuse tab增加移动端浏览器的手势支持

### ISSUE THREAD

**Issue by selegiline** [ng-alain/ng-alain#505]
![e w67 zl8 1 u 9grvg](https://user-images.githubusercontent.com/31548229/41204364-54757986-6d16-11e8-8b90-765bd40f9633.png)
 在触摸屏上，左右两侧的翻页按钮不太容易点中，tab标签也要点击两次才能选中，可不可以加入类似tap，press，swipe这些手势的适配让ng-alain在手机浏览器里使用的更顺畅。

**Comment by selegiline** [comment]
供参考：https://vux.li/demos/v2/#/component/tab

**Comment by cipchk** [comment]
暂时没有办法，本质上是使用 `nz-tabset` 组件。
