### ISSUE TITLE
@delon/abc simpletable中的翻页请求发起和change事件emit的顺序能否颠倒过来，因为后端分页需要用到pi，ps参数并且使用的是post方法，若change事件触发比请求发起晚的话会导致post请求pi，ps参数不对

### ISSUE THREAD

**Issue by zl12180039** [ng-alain/ng-alain#507]
_change(type: 'pi' | 'ps') {
    if (!this._inited) return;
    this._genAjax();
    if (this.frontPagination) this._genData();
    this._toTop();
    this.change.emit({
      type: type,
      pi: this.pi,
      ps: this.ps,
      total: this.total,
    });
  }

**Comment by cipchk** [comment]
`change` 只是单纯的事件通知，这和发起起来是无关，我不清楚你这里说所以 `POST` 请求不对，麻烦提供一个完整可重现的示例。

**Comment by zl12180039** [comment]
`  <simple-table #st [columns]="aColumns" [reqMehtod]="req.method" [pi]="1" [ps]="5" [extraParams]="req.params" [data]="req.url"
    [resReName]="req.resName" [frontPagination]="false" [showSizeChanger]="true" [pageSizeOptions]="[3,5,10,20,50]">
    <ng-template #expand let-item let-index="index" let-column="column">
      <simple-table [data]="item.building" [columns]="bColumns"></simple-table>
    </ng-template>
  </simple-table>`
在如上reqBody中需要加入pi，ps，以及一些自定义的参数，目前塞入的pi和ps无法与实际值保持一致。或者是能否将extraParams的参数在reqMthod的为POST时将params放入请求的body中

**Comment by cipchk** [comment]
请认真阅读issues的要求。

**Comment by gmf520** [comment]
在`STReq`有`process`可以用，想处理啥请求参数都可以
