### ISSUE TITLE
Mock数据匹配规则优先级

### ISSUE THREAD

**Issue by pengb0** [ng-alain/ng-alain#508]
- ng-alain version:1.0.8
- Angular version: 6.0.4

## 【必填项】重现链接，https://ng-alain-setup-gouurw.stackblitz.io

类似于下面的这种API，当请求/user/list时总会跳转到/user/:id
![image](https://user-images.githubusercontent.com/27408827/41264454-61a84f48-6e1f-11e8-98ae-ce360ec075b4.png)
看了下源码，应该是最后这里的排序导致/user/list被放在了后面，优先匹配了/user/:id，可以考虑增加匹配规则的优先级设置吗？
![image](https://user-images.githubusercontent.com/27408827/41264576-0a766b1e-6e20-11e8-89a5-f210b18afb06.png)

**Comment by cipchk** [comment]
增加优先级在使用上反而麻烦，的确应该是依代码的顺序来执行。这个问题可能会引发另一种情况：

```
/user/:id
/user/:id/edit
```

会导致始终无法命中 `edit`

**Comment by hangxun** [comment]
正常来说 应该只有两个 /users 返回用户列表  /users/:id 返回指定用户
