### ISSUE TITLE
simple-table 分页时已经选中第二页且数据已经变更了，当前页码总是为1

### ISSUE THREAD

**Issue by oksonic** [ng-alain/ng-alain#509]
这个问题在#487中已经提到了，但1.0.8也没解决  
<simple-table #st [data]="data" frontPagination="false" (change)="change($event)" showSizeChanger="false"
                [total]="total" [columns]="columns" [isPageIndexReset]="false">
  </simple-table>

**Comment by cipchk** [comment]
请认真阅读issues的要求。
