### ISSUE TITLE
Reuse Tab _onReuseInit钩子触发两次

### ISSUE THREAD

**Issue by Zhouuuuuuuuu** [ng-alain/ng-alain#511]
![image](https://user-images.githubusercontent.com/29364579/41278864-8765bade-6e5d-11e8-8246-76efa483fdfb.png)
如上，我在组件中使用了_onReuseInit钩子来刷新数据。但是会触发两次导致Subject被订阅两次。
console log
![image](https://user-images.githubusercontent.com/29364579/41279037-fb6f5a3e-6e5d-11e8-8c35-ed88c70eebf4.png)

**Comment by cipchk** [comment]
操，他妈的，每个人都不看issues要求吗？

**Comment by Zhouuuuuuuuu** [comment]
@cipchk sorry,我会注意的，不好意思。
