### ISSUE TITLE
在分析页点击明细项，饼图会消失

### ISSUE THREAD

**Issue by Wayfreem** [ng-alain/ng-alain#512]
- ng-alain version: 1.0.x
- Angular version: 6.0.4

## 重现链接，https://cipchk.github.io/ng-alain/#/dashboard/analysis
![image](https://user-images.githubusercontent.com/20548003/41286399-dffd0e18-6e71-11e8-9917-d36a46853364.png)

### step 1：
进入分析页链接：https://cipchk.github.io/ng-alain/#/dashboard/analysis
### step 2：
点击 `销售额类别占比 ` 图右边的明细项。就会发现饼图消失。并且重新点击刚刚点击的明细项，也出不来。
### 点击之后的图示：
![image](https://user-images.githubusercontent.com/20548003/41286818-62190022-6e73-11e8-9cdd-a4fb649387d1.png)

## 最后我也找到了处理办法：
在 delon 这个项目下，源码链接：https://github.com/cipchk/delon/blob/master/packages/abc/charts/pie/pie.component.ts

**源码第 257 行** 
![image](https://user-images.githubusercontent.com/20548003/41287336-fcea01b8-6e74-11e8-9075-ec83f8076590.png)

**应该修改为**
 `this.chart.filter('x', (val: any, item: any) => item.checked);`

这个地方传入的有两个参数，我仔细看了下，第一个 val 只是 一个文本值 。例如: 个护健康. item 才是一个对象。

**Comment by cipchk** [comment]
@Wayfreem 非常好issues，若你对 [ant pro 主题](https://e.ng-alain.com/theme/antd-pro) 有兴趣，可留下一个EMAIL。

**Comment by kiyonlin** [comment]
我刚接触代码贡献，想尝试修复这个bug，请多指教 @cipchk

**Comment by cipchk** [comment]
@kiyonlin OK

**Comment by kiyonlin** [comment]
请问demo项目怎么在本地跑起来？ @cipchk

**Comment by cipchk** [comment]
```bash
ng serve
```

**Comment by Wayfreem** [comment]
ant pro 主题 ，这个我还没有仔细看过，如果有问题，我会继续发布的。 @cipchk
