### ISSUE TITLE
A simple logical error With advanced-form

### ISSUE THREAD

**Issue by NG-GGBond** [ng-alain/ng-alain#513]
## Version
- ng-alain version : any
- Angular version : 6.0
## Environment
Chrome 56
## Reproduction link
https://cipchk.github.io/ng-alain/#/pro/form/advanced-form
## Steps to reproduce
![bbbb](https://user-images.githubusercontent.com/39577696/41295229-a0af2f3c-6e8c-11e8-852a-1dd3ece58248.gif)
**Step1**. Add Line
**Step2**. Save Line
**Step3**. Edit Line
**Step4**. Cancal Line
**Result**: The line has been deleted.
## What is expected?
Edit cancel is not deleted.
## What is actually happening?
Line deleted.
## Other?
A simple logical error.

**Comment by NG-GGBond** [comment]
@cipchk  hi,cipchk.  I want  Antd Pro ,My Email:392787822@qq.com

**Comment by cipchk** [comment]
不修复该问题，本身只是一个数据模拟。
