### ISSUE TITLE
simple table 采用 reqMethod post 当更新页码以及页数等等时，

### ISSUE THREAD

**Issue by wulifangy** [ng-alain/ng-alain#514]
- ng-alain version: 1.0.8
- Angular version: 6

simple table 采用data为url， reqMethod为post ， reqBody等查询数据。
当更新页码以及页数时，发送接口的reqBody内容晚一步。
如： 
1. 当前pi为1,ps 为 5
2. 点击跳转页面，pi为2，ps为5
3. 可是http请求，body体内容，未更新至pi=2，ps=5，而是上一次结果。
结果：
simple table采用这种方式，先发送http请求，后至更新reqBody内容。

**Comment by NG-GGBond** [comment]
use   settimeout

**Comment by cipchk** [comment]
我愚钝，我认真阅读了三遍，还是没看明白。

**Comment by NG-GGBond** [comment]
只需要把st.load()延迟（settimeout）执行若干毫秒，就可以解决后加载reqbody的问题，而且simpletable的pi ps  也不是放到body里来处理的

**Comment by wulifangy** [comment]
@0o0o0o0o0o0o0  post方法时，就不把pi ps 放在url里面了。

**Comment by k-w-wang** [comment]
@wulifangy 如何解决掉用st.reset方法时只能触发get请求的问题，我想要触发post请求该如何更改

**Comment by NG-GGBond** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。
