### ISSUE TITLE
Reuse Tab _onReuseInit钩子重复触发

### ISSUE THREAD

**Issue by Zhouuuuuuuuu** [ng-alain/ng-alain#516]
- ng-alain version: 1.0.2
- Angular version: 6.0.0

## 【必填项】重现链接，Reproduction link

https://cipchk.github.io/ng-alain/#/dashboard/v1（Stackblitz实在是无法重现，但是demo中添加_onReuseInit钩子可以重现）

![gif](https://user-images.githubusercontent.com/29364579/41336035-90f98fe2-6f1d-11e8-9cb2-7dff904d4685.gif)

## 重现步骤，Steps to reproduce
**Step1**: 在Dashboard/v1组件中添加_onReuseInit方法
**Step2**: 切换Dashboard页面与其他页面
**Result**: Dashboard/v1组件中_onReuseInit触发两次

为上次不规范的issues抱歉。

**Comment by cipchk** [comment]
a working ant:

![success](https://user-images.githubusercontent.com/2987467/41337890-26a1aafc-6f23-11e8-9b65-8e3b85250993.gif)

**Comment by Zhouuuuuuuuu** [comment]
alright, this problem was resolved when I upgraded @delon to v1.0.8

**Comment by zhulj** [comment]
此问题在升新到12的版本又出现了，我之前11版本是没有问题的

**Comment by cipchk** [comment]
@zhulj 的确有这种现象，主要是 angular12 路由做了一些改变，目前临时的办法只能你自己做一些标记了。
