### ISSUE TITLE
Tinymce URL ERROR

### ISSUE THREAD

**Issue by NG-GGBond** [ng-alain/ng-alain#517]
## Version
- ng-alain version: 1.0.8
- Angular version: 6.0
## Environment
Any 
## Reproduction link
https://ng-alain.com/form/tinymce
## Steps to reproduce
Step1:
`NgxTinymceModule.forRoot({
      baseURL: '//cdn.bootcss.com/tinymce/4.7.4/',
 }),`
Result:[http://cdn.bootcss.com/tinymce/4.7.4//themes/modern/theme.min.js](url)
Double /
Step2:
`NgxTinymceModule.forRoot({
      baseURL: '//cdn.bootcss.com/tinymce/4.7.4',
 }),`
Result:[http://cdn.bootcss.com/tinymce/4.7.4tinymce.min.js](url)
No /
## What is expected?
URL loading success
## What is actually happening?
URL ERROR

**Comment by cipchk** [comment]
https://github.com/cipchk/ngx-tinymce/issues/10
