### ISSUE TITLE
通过 app-data.json 定义menu时，无法传入查询参数

### ISSUE THREAD

**Issue by dusdong** [ng-alain/ng-alain#518]
`
{
    "text": "文章库",
    "translate": "文章库",
    "link": "/content/article?isAdmin=true"
}
`

通过这方式定义的menu，url被转义了：http://localhost:4203/#/content/article%3FisAdmin%3Dtrue

请问下，应该如何定义？

**Comment by cipchk** [comment]
这是 `routeLinker` 路由导航引起的，也是合理的。

我建议采用两个不同路由，例如 `/content/article` 或 `/content/article_admin`，或者使用 ACL 来处理用户权限问题。

`@delon` 对于这种情况不会考虑处理。

**Comment by dusdong** [comment]
能否给加上 queryparams 这个参数呢？这样会更灵活些。

因为有时候，会分成不同的窗口显示不同的内容。比如：A窗口，显示原材料类；B窗口，显示半成品类。只需要传入参数就可以实现页面复用了。

谢谢~

**Comment by cipchk** [comment]
不同路由相同组件，本身就是在复用。灵活性更高。

**Comment by dusdong** [comment]
好的，明白了，十分感谢！
