### ISSUE TITLE
ERROR TypeError: You provided an invalid object where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.

### ISSUE THREAD

**Issue by guaicaiboshi** [ng-alain/ng-alain#52]
我在login页面的submit()方法中增加了
 this.http.get("http://localhost:8099/api/Values/get").subscribe((res: any) =>{
        console.log(res);
      });

我本地IIS的一个方法，支持跨域，但是报错误
ERROR TypeError: You provided an invalid object where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.

请求帮助

**Comment by bokire** [comment]
被token.interceptor拦截了

**Comment by guaicaiboshi** [comment]
if (!req.url.toLowerCase().includes('auth/') && !req.url.toLowerCase().includes('assets/'))
我把这里修改了下本地，不然url中的Auth也无法匹配，
我把我的
"http://localhost:8099/api/Values/get"
改为
  this.http.post('http://127.0.0.1:8777/api/Auth/Login', params).subscribe(res => console.log(res));
测试没问题！
token.interceptor拦截  auth与assets 是为了判断是否登录后的授权 ，还有资源请求的必须授权？

感谢您上午的回复

**Comment by jiaohuixing** [comment]
把我这个angular小白快要整的放弃的时候发现了这个答案。建议搞个学习群。

**Comment by guaicaiboshi** [comment]
好啊，你建吧，我QQ 173836966  到时候你拉我

**Comment by bokire** [comment]
@jiaohuixing 当初我也折腾了很久，最后问了作者

**Comment by DamonXiong** [comment]
学习群多少？这个token拦截怎么改的，改的那个位置？ @jiaohuixing
