### ISSUE TITLE
simple table 分页一直选中的是第一页

### ISSUE THREAD

**Issue by oksonic** [ng-alain/ng-alain#521]
- ng-alain version: 1.1.1
- Angular version: 6

## 

数据源使用数组时
 ` <simple-table #st [data]="data" (change)="change($event)" showSizeChanger="false" [extraParams]="q" [pi]="q.pi" [ps]="q.ps"
                [total]="total" [columns]="columns" [isPageIndexReset]="false">`
在change($event)方法中查看 this.st的pi和ps值，是很正常的，但q.pi和q.ps值不会变

data值重新得到数据后，`this.data = data.results;`分页的页码永远在第一页
`change(e){
    this.st.isPageIndexReset = false;
    console.log(this.st);
    console.log(this.q);
    ...
    this.data = data.results 有这一句后页码总跳到第一页
  }`

**Comment by Criske7** [comment]
我也遇到同样的问题，且我已经设置了frontPagination=false，获取分页的数据后总是跳回第一页。请问如何解决

**Comment by cipchk** [comment]
@Criske7 麻烦提供一下重现示例，https://stackblitz.com/edit/ng-alain-setup。

**Comment by Criske7** [comment]
@cipchk 这是我的相关代码，您先看一下
app.component.ts

import { Component } from '@angular/core';
import { NzMessageService } from 'ng-zorro-antd';
import { SimpleTableColumn, SimpleTableData, SimpleTableFilter } from '@delon/abc';
import { ActivatedRoute, Router } from "@angular/router";
import { _HttpClient } from "@delon/theme";
import { FormBuilder, FormGroup } from "@angular/forms";
import { HttpErrorResponse, HttpParams } from "@angular/common/http";
import { URLSearchParams } from "@angular/http";
import { SFSchema } from '@delon/form';


@Component({
  selector: 'my-app',
  templateUrl: './app.component.html',
  styleUrls: [ './app.component.css' ]
})
export class AppComponent  {
  name = 'Angular';
  public isSpinning = false;
  public total;
  public pageSizeOptions = [10, 15, 20];
  public searchForm: FormGroup;
  public params = {};
  public selectedValue = '';
  public environment;

  public list: any;
  public datas: any;

  q: any = {
    pi: 1,
    ps: 1,
    sorter: '',
    status: null,
    statusList: []
  };

  constructor(private router: Router,
    private http: _HttpClient,
    private msg: NzMessageService,
    private fb: FormBuilder,
    public ar: ActivatedRoute) {
    //  	this.getData();
    this.searchFormInit();
  }

  ngOnInit(): void {
    this.getData(1);
  }

  searchFormInit() {
    this.searchForm = this.fb.group({

    });
  }

  status = [
    { index: 1, text: '正常', value: false, type: 'default', checked: false },
    { index: 2, text: '锁定', value: false, type: 'success', checked: false },
  ];

  columns: SimpleTableColumn[] = [
    { title: '', index: 'id', type: 'checkbox' },
    //      {title: '编号', index: 'id'},
    { title: 'a', index: 'index1' },
    { title: 'b', index: 'index2' }
  ];

  getJsonLength(jsonData) {
    var jsonLength = 0;
    for (var item in jsonData) {
      jsonLength++;
    }
    return jsonLength;
  }

  public ids = [];

  //选择框获取id
  checkboxChange(ret: any) {
    //  	console.log(ret);
    console.log(ret.length);
    for (let i = 0; i < this.getJsonLength(ret); i++) {
      this.ids.push(ret[i].id);
    }
    console.log(this.ids);
    console.log(ret);
  }


  change(value: any) {
    console.log('change', value);
    this.q.pi = value.pi;
    //		this.getData(value.pi);
    const url = environment.domain + "/list";
    this.http.get(url, { page: value.pi - 1, pageSize: this.q.ps })
      .subscribe((res: any) => {
        this.list = res;
        this.datas = this.list.content;
        this.q.pi = value.pi;
      })
    console.log("getData complete");
  }

  getData(pi) {
    this.isSpinning = true;
    const url = environment.domain + "/list";
    this.http.get(url, { page: pi - 1, paseSize: this.q.ps })
      .subscribe((res: any) => {
        this.isSpinning = false;
        this.list = res;
        console.log(res);
        this.datas = this.list.content;
        this.total = this.list.totalElements;
      });
  }
}
//////////////////////////////////
app.component.html

<nz-card>
  <nz-spin [nzSpinning]="isSpinning" nzTip='Loading...'>
    <simple-table #st [data]="datas" [frontPagination]="false" [ps]="q.ps" [(pi)]="q.pi" 
      (change)="change($event)" [bordered]="true" [columns]="columns" 
      (checkboxChange)="checkboxChange($event)" [total]="total" pagePlacement="right"  
      showQuickJumper isPageIndexReset >
    </simple-table>
  </nz-spin>
</nz-card>

**Comment by Criske7** [comment]
@cipchk 这是我的相关代码，您看一下
list.component.html
<nz-card>
  <nz-spin [nzSpinning]="isSpinning" nzTip='Loading...'>
    <simple-table #st [data]="datas" [frontPagination]="false" [ps]="q.ps" [(pi)]="q.pi" 
      (change)="change($event)" [bordered]="true" [columns]="columns" 
      (checkboxChange)="checkboxChange($event)" [total]="total" pagePlacement="right"  
      showQuickJumper isPageIndexReset >
    </simple-table></nz-spin></nz-card>
////////////////////////////////////
list.component.ts
import { Component } from '@angular/core';
import { NzMessageService } from 'ng-zorro-antd';
import { SimpleTableColumn, SimpleTableData, SimpleTableFilter } from '@delon/abc';
import { ActivatedRoute, Router } from "@angular/router";
import { _HttpClient } from "@delon/theme";
import { FormBuilder, FormGroup } from "@angular/forms";
import { HttpErrorResponse, HttpParams } from "@angular/common/http";
import { URLSearchParams } from "@angular/http";
import { SFSchema } from '@delon/form';

@Component({
  selector: 'my-app',
  templateUrl: './app.component.html',
  styleUrls: [ './app.component.css' ]
})
export class AppComponent  {

  public isSpinning = false;
  public total;
  public pageSizeOptions = [10, 15, 20];
  public environment;
  public list: any;
  public datas: any;

  q: any = {
    pi: 1,
    ps: 1,
    sorter: '',
    status: null,
    statusList: []
  };

  constructor(private router: Router,private http: _HttpClient,private msg: NzMessageService,
    private fb: FormBuilder,public ar: ActivatedRoute) {
  }

  ngOnInit(): void {
    this.getData(1);
  }

  columns: SimpleTableColumn[] = [
    { title: '', index: 'id', type: 'checkbox' },
    //      {title: '编号', index: 'id'},
    { title: 'a', index: 'index1' },
    { title: 'b', index: 'index2' }
  ];

  change(value: any) {
    console.log('change', value);
    this.q.pi = value.pi;
    //		this.getData(value.pi);
    const url = environment.domain + "/list";
    this.http.get(url, { page: value.pi - 1, pageSize: this.q.ps })
      .subscribe((res: any) => {
        this.list = res;
        this.datas = this.list.content;
        this.q.pi = value.pi;
      })
    console.log("getData complete");
  }

  getData(pi) {
    this.isSpinning = true;
    const url = environment.domain + "/list";
    this.http.get(url, { page: pi - 1, paseSize: this.q.ps })
      .subscribe((res: any) => {
        this.isSpinning = false;
        this.list = res;
        console.log(res);
        this.datas = this.list.content;
        this.total = this.list.totalElements;
      });
  }
}
