### ISSUE TITLE
#487 反映的问题并没有解决: simple-table 使用静态数据采用后端分页,设置pi无效 

### ISSUE THREAD

**Issue by qingfeng365** [ng-alain/ng-alain#524]
- ng-alain version: 1.1.1
- Angular version: 6.0.0

## 【必填项】重现链接，Reproduction link
![snip20180617_1](https://user-images.githubusercontent.com/14341499/41506611-b7fa9508-7253-11e8-8471-be7718ac969d.png)
如图所示, 数据为 第二页, 当前页码会重置为第一页

## 重现步骤，Steps to reproduce

simple-table 声明如下:

```html
 <simple-table #st="" [columns]="columns" [data]="data" [loading]="loading" (checkboxChange)="checkboxChange($event)" (change)="change($event)" [frontPagination]="false" [total]="stRecordTotal" [pi]="stPageCurrNumber" >
</simple-table>
```
在 change 事件重新查询 当前页 data 后,  当前页码会重置为第一页

期望结果: 当 frontPagination = false 时, pi 值由外部输入参数决定, 不要重置为 1 

## 可能的原因

当在 change 事件重新查询 data 后,

触发 st 的 ngOnChanges

```ts
  ngOnChanges(
    changes: { [P in keyof this]?: SimpleChange } & SimpleChanges,
  ): void {
    if (changes.columns && this._inited) this.updateColumns();
    if (changes.data && this._inited) this.processData();

    this.setClass();
  }
```
在 processData 中, 会 调用 

```ts
    } else if (Array.isArray(this.data)) {
      this._genData(true);
    } else {
```

而在 _genData(true) 中, 总会重置 this.pi 为 1

```ts
    if (forceRefresh) {
      if (this.isPageIndexReset) {
        this.pi = 1;
      } else {
        const maxPageIndex = Math.ceil(data.length / this.ps);
        this.pi = !this.pi
          ? 1
          : this.pi > maxPageIndex
            ? maxPageIndex
            : this.pi;
      }
    }
```

因为 maxPageIndex 是 这种应用场景下, 总是为1 (因 data.length 仅为一页数据, 即 this.ps )

所以 this.pi > maxPageIndex 总是成立的

## 对组件文档的疑问

不知道我对帮助的说明是否理解有误

帮助是这样说明:

frontPagination 前端分页
   false 由用户通过 total 和 data 参数受控分页，并维护 (change) 当分页变更时重新加载数据

根据这个说明, 我的理解 是 total 和 pi 均为外部输入参数指定, 不应该在内部进行计算?

已有多人反映相同问题, 希望对该说明有详细示例,谢谢!

**Comment by cipchk** [comment]
你理解没错，的确会有这种情况发生。

**Comment by yyget** [comment]
## 这个问题解决了吗

**Comment by yyget** [comment]
#### ng serve翻页后页面是正常的，但是ng build --prod后还是原来的问题。@delon已经升级到1.1.2了
