### ISSUE TITLE
Bug report: @delon/form number widget multipleOf error

### ISSUE THREAD

**Issue by xingkoo** [ng-alain/ng-alain#526]
- ng-alain version: 1.1.1
- Angular version: X.Y.Z

## 【必填项】重现链接，Reproduction link

[演示地址](https://stackblitz.com/edit/ng-alain-setup-7grkjd)  

![image](https://user-images.githubusercontent.com/2936579/41582867-62b7dac8-73d5-11e8-99ef-f7fb1903afc4.png)

## 重现步骤，Steps to reproduce
ng-zorro-ant 里面可以通过控制`[nzStep]`来决定小数位数.
在ng-alain里面 ,`[multipleOf]`表示倍数,理论上来说两个应该是一至的吧?
实际情况中
* 提示信息中的位置值未正常显示,应该是`{{multipleOf}}`错写成`{multipleOf}`了.
* 当倍数为小数时,我试着使用0.01,  则值为0.07类似的时候,也会提示必需为倍数.这样我就无法限制小数位数了.

**Comment by xingkoo** [comment]
信息2中,包含0.07的倍数,都会显示错误信息

**Comment by iwantacook** [comment]
也发现了一样的问题，关于`multipleOf`，比如（仅是举例，不一定准确），设置值为0.001的时候，在0.007或某个时候，会提示类似的错误：`应当是{multipleOf}的整数倍`。

**Comment by cipchk** [comment]
这不算是一个BUG，受限于 javascript 精度的关系，建议需要高精确度可以使用 input 和 regex 配合。
关于 ajv 检验的根本问题，可以参考：https://github.com/epoberezkin/ajv/issues/697

若希望收到 ingoreKeywords 错误，可以通过 `DelonFormConfig` 增加 `[ 'multipleOf' ]` 来忽略掉。
