### ISSUE TITLE
@delon/form number widget and slider widget

### ISSUE THREAD

**Issue by xingkoo** [ng-alain/ng-alain#528]
* 数字类型的widget中,指定的addOnAfter无效. 如我需要记录用户年龄,数字类型输入,尾部需要增加`岁`字样,不能添加成功
````
floorDownNum: { 
  type: 'integer', 
  title: '地下楼层' 
  ui:{
    addOnAfter: '层'
  }
},
````
![image](https://user-images.githubusercontent.com/2936579/41589129-4862569c-73e6-11e8-86a3-c2442ec21169.png)

* 滑动块中,添加marks后,高度超出标准行高度,导出错误现象发生.
![image](https://user-images.githubusercontent.com/2936579/41589111-3f1d2dbe-73e6-11e8-9881-6aa8d2bcdec6.png)

* label预设后,导致复选框宽度出错
````
ui: SFUISchema = {
    '*': {
      spanLabelFixed: 100,
      grid: { span: 12, xs: 24, md: 12 },
    },
}
````
![image](https://user-images.githubusercontent.com/2936579/41591299-e2f749e2-73eb-11e8-9897-7190e816ced0.png)

**Comment by cipchk** [comment]
1. 按文档来使用API。
2,3 请提供相应的重现。

**Comment by xingkoo** [comment]
[2,3 问题重现](https://stackblitz.com/edit/ng-alain-setup-jlgmc2)

第一个在number widget基础上添加addOnAfter支持,会有背于ng-alain的立场吗?

个人觉得数字本身就是需要单位的.把单位写在前面的辅助区域,总感觉不是那么自然.
就是说如果我需要在后面生添加词语,就需要自行封装widget了吧.

**Comment by cipchk** [comment]
2. `grid.span` 污染了 `checkbox.span` 我会重新指定专门一个 `span` 来表示  checkbox 布局。
3. 只能重新针对  checkbox 指定 `spanLabelFixed: 0` 。

**Comment by cipchk** [comment]
关于 slider 小部件没有什么好的办法，你可以考虑让其占有一整行的小技巧来解决布局问题。
