### ISSUE TITLE
@delon/form too many properties,Need to be divided

### ISSUE THREAD

**Issue by xingkoo** [ng-alain/ng-alain#529]
* 当属性过多时,将会导出页面拉取非常长.
* 所有的属性都混在一块,不能按功能点间隔开,希望能够提供隔离方案
  * 按属性功能点分组,每组属性间可以使用线条分隔,以便视觉效果更清晰
  * 按属性功能点分组,使用tabsets分开放置

**Comment by cipchk** [comment]
自行自定义 object，也可以继承 `ObjectWidget` 或 `ArrayWidget` 类，并重新定义HTML模板来调整 Object 或 Array 对象的布局：

```json
{
    "order": {},
    "wares": [
   {  }, {}
  ]
}
```

那么可以使用上述办法增加类似选项卡风格。

**但**若本身就一个超级大 Object 就没有办法。

**Comment by xingkoo** [comment]
我先暂时放置在一块,后续我尝试一下.感谢提供思路.
