### ISSUE TITLE
关于webstorm编译错误提示问题

### ISSUE THREAD

**Issue by guccihuiyuan** [ng-alain/ng-alain#53]
我使用的是webtormIDE，编写HTML代码时候，凡是使用ng-zorro组件，编译器都没有代码智能提示，而且会会报一堆编译错误，但实际运行没问题，这要怎么解决呢？

**Comment by cipchk** [comment]
我不确定是怎么一回事，恩，如果你采用 `cnpm` 安装包体的话，那有可能是 `cnpm` 本身 link 的原因导致 ide 无法也说不定。我无法判断；亦或尝试重启IDE呢？抱歉，恐怕我无法帮到你什么。

> PS：个人建议 Angular 最好在 vscode 中开发，体验比任何IDE来得更好，恩，配合 [ng-zorro-vscode](https://marketplace.visualstudio.com/items?itemName=cipchk.ng-zorro-vscode) 更快速。
