### ISSUE TITLE
能否为simple-table组件，在url模式下加入option参数

### ISSUE THREAD

**Issue by billyshen26** [ng-alain/ng-alain#531]
![image](https://user-images.githubusercontent.com/5089845/41650872-a6ed2a72-74b1-11e8-8544-e760a2b442a6.png)
如上图所示，当simple-table读取数据用url模式的时候，无法指定withCredentials参数，能否加入字段来设置该字段。由于我的请求需要withCredentials为true。或者请问在url模式，是否能实现withCredentials=true的设置。
目前我的版本是  "version": "1.0.8",
    "@delon/abc": "^1.0.8",
    "@delon/acl": "^1.0.8",
    "@delon/auth": "^1.0.8",
    "@delon/cache": "^1.0.8",
    "@delon/form": "^1.0.8",
    "@delon/mock": "^1.0.8",
    "@delon/theme": "^1.0.8",
    "@delon/util": "^1.0.8",

thanks，
Billy

**Comment by cipchk** [comment]
可以使用拦截器临时解决这个问题。

**Comment by billyshen26** [comment]
多谢指点，已经可以了,在default.interceptor.ts中
    const newReq = req.clone({
      url: url,
      withCredentials: true  // 加入了这行
    });

thanks,
Billy
