### ISSUE TITLE
优化simple-table的SimpleTableButton参数

### ISSUE THREAD

**Issue by jackywang615** [ng-alain/ng-alain#532]
现在的参数如下
```javascript
    "buttons": [
        {
            "text": "编辑",
            "type": "modal",
            "component": EditModalComponent,
            "size": "sm",
            "params": (record:any) => object,
            "paramName": "record",
            "modalOptions": {},
            "click": (record:any, modal: any) => {//do something....}
        }
    ]
```
存在问题，参数扁平化，都放在同一个层级里面，用起来不方便，当type不同时，参数也不同，容易混在一起。
modalOptions是NzModalService的参数，既然已经有这个参数了外面的component是否就可以不要了？
还有那个参数的问题，paramName是不是可以不要了，通过params返回一个json格式的就可以了吧，和NzModalService中的一样，然后给modalOptions，这样就容易多了。

**Comment by cipchk** [comment]
注意到这个问题了，只是需要一些破坏性变更，一直隐忍着。

**Comment by jackywang615** [comment]
忍无可忍就无需再忍了，改了吧，写起来心累(￣▽￣)~*

能顺便给个仿antd pro的使用资格么ヾ(✿ﾟ▽ﾟ)ノ
