### ISSUE TITLE
1.0.0版model对话框

### ISSUE THREAD

**Issue by zzz** [ng-alain/ng-alain#533]
最新版框架，在接口报错走拦截器的时候，页面跳转到404页面或500页面。。。的时候，model对话框不会销毁，而是在404或500这些页面的上面。

**Comment by cipchk** [comment]
在所有异常页增加移除对话框动作，略同 login.component.ts 的写法。

**Comment by lzk1994** [comment]
你说的这种方式，其实每个异常页面默认都添加了，但解决不了以上问题
问题重显图片
![image](https://user-images.githubusercontent.com/39012698/41701194-1908a7ce-755e-11e8-84b8-a47446c30996.png)

添加的代码：
![image](https://user-images.githubusercontent.com/39012698/41701152-f449f3e8-755d-11e8-9d11-bfa7accd8328.png)

**Comment by cipchk** [comment]
请参考最新版本的写法。
