### ISSUE TITLE
@delon/form transfer widget value order

### ISSUE THREAD

**Issue by xingkoo** [ng-alain/ng-alain#538]
- ng-alain version: 1.1.1
- Angular version: X.Y.Z

## 【必填项】重现链接，Reproduction link

https://stackblitz.com/edit/ng-alain-setup-16vjx9

## 重现步骤，Steps to reproduce
* 异步加载数据,更新表单数据
* 设置穿梭框的值`顺序`和表单结构中定义的enum中的顺序不同.
  如 表单中是 [11,12,13,14,15], 设置值为[13,11]
* 右侧数据顺序会被enum的顺序影响而排序.  
  按上面写的操作,右侧值为被设置为[11,13]而非 [13,11] (实际使用中需要产生[13,11]这样的顺序)

特性:
希望增加右侧选中数据的顺序调整功能.
类似这个issue: https://github.com/ant-design/ant-design/issues/2538

**Comment by cipchk** [comment]
自行自定义小部件。

**Comment by xingkoo** [comment]
特性可以自行定义小部件解决,但是加载数据的时候,右侧选择项的顺序,是不是需要在这个组件中处理?

**Comment by xingkoo** [comment]
@cipchk 顺序问题可以解决吗?如果不能解决的话我就拿ant的自定义组件了.个人觉得不是按右侧值排序应该是个bug
