### ISSUE TITLE
Feature request: Migrate to NX for multiple applications structure

### ISSUE THREAD

**Issue by xgenvn** [ng-alain/ng-alain#54]
Hi,

Thank you for the excellent work.

I found out that [NX](https://nrwl.io/nx/guide-getting-started) has been open-sourced recently, and we can manage multiple apps within one place.
Do you think it's a good idea to migrate the current structure to a shared convenience way?
I've done some works and try to migrate some from your code base, but I really want to know your opinion.

For example, currently many shared codes are from app `core`, `utils` and `shared`.
We can try move this to a core app in nx, or even global `lib`, so we can reuse it later in many apps.

Thanks.

**Comment by cipchk** [comment]
thank you very much! NX is very good. 

I don't know how many changes will happen, if time permits, i will try to.

**Comment by xgenvn** [comment]
Yes, it'll be a breaking change for sure. If you intend to integrate NX, can you create another branch so that I can also contribute to? 
However, we can write an inject script to have current repository to work with NX.
Please let me know if you have any better idea ;).

**Comment by cipchk** [comment]
it is unlikely that if need releases a breaking change. I have a lot of work to do future, so i can't maintenance extra branches.

can supported NX on the bases, maybe your write an inject script is also a pretty good choice. other ways is so hard to implement, i don't have too much energy.

**Comment by cipchk** [comment]
@xgenvn hi, i pondered this problem over and over again that manage multiple apps within one place.

so, i plan to create a new repository service for business components (like [alain](https://github.com/cipchk/alain)), please tell me how to do compatible NX?

**Comment by xgenvn** [comment]
I'll start experiment with creating a lib called `alain`, and moving things from the `core` and `shared` into `alain`. Or two different lib (alain_shared, alain_core). Well, I don't think you'll have problem moving things around like that. However, the structures should be well-defined. Then the current dashboard implementation can be defined as a playground app for references.

Perhaps we can create another repository called nx.alain?

**Comment by cipchk** [comment]
Sure, it's the best if you can create a basic project service for NX.

and i have a few questions to ask.

+ What is the difference between NX and npm?
+ What should a NX directory structure?

**Comment by xgenvn** [comment]
I'm not sure how to answer the first question correctly.
I think it's very similar if we manage the app as npm packages.
There's one point that NX is superior though.
Scenario: We have Front app for user, Admin app for management, maybe Mobile app as well.
With NX, we have these apps under app folder. You can choose to build which app, and anything can be shared, put in lib folder, or separate npm package is also good.

With npm, I suppose we still have multiple app folders, right? And it makes maintenance a little bit harder.
So for me, NX solution is like a Visual Studio solution, where every app is a different project.

**Comment by dreamdevil00** [comment]
Why not using [lerna](https://github.com/lerna/lerna) to manage packages that you want to share among many other apps ?
And the code structure could be like [colmena](https://github.com/colmena/colmena) which is more scalable

**Comment by xgenvn** [comment]
Hi,

I haven't heard about lerna before. Thank you for mentioning it. Just have been checking it out, it serves similar to NX. However, lerna is very general compare to NX, which serves only Angular based development. And it requires a lot of configuration (correct me if I'm wrong). It's not like NX, one command and we have it working nicely.
And NX will extend Angular CLI, so it'll be better if we're using Angular CLI.

Colmena directory structure is similar to NX, and under active development. NX has reach the stable release at 1.5.x.

**Comment by dreamdevil00** [comment]
@xgenvn  In fact, there's little configuration you have to do with lerna,  just try it.
Yes,   Colmena  directory structure is similar to NX.

Using lerna to manage projects, you can control the package version and quickly publish it to npm, thus you can update your packages in semver. and use packages in other apps, not only current project. It's flexible whereas  you have to manage the directory structure by yourself like Colmena.  You can use `ng serve` as usual and do not have to build libs at first.

AFAIK,  using Nx do save our time to manage directory structure and the time to create some basic files,  but  you can not control the package version.

They are complementary。 I think it may be better if using both of them.
