### ISSUE TITLE
无法创建 edit 业务页

### ISSUE THREAD

**Issue by HelloValue** [ng-alain/ng-alain#540]
使用命令行: **ng g ng-alain:edit details -m=product**  创建对应module下的edit 业务页时，
出现报错：Could not find any [COMPONENTS_NOROUNT] variable.
PS：list 业务页能正常创建。 **ng g ng-alain:list list -m=group**
版本信息：
Angular CLI: 6.0.8
Node: 8.11.3
OS: win32 x64
Angular: 6.0.6

**Comment by cipchk** [comment]
业务页只对通过 `ng g ng-alain:module` 生成的模块有效。

**Comment by HelloValue** [comment]
==。我记得我是在ng g ng-alain:module 下创建的我的第一个模块，甚至我还在此模块下创建了一个list。
请问我该如何将现有模块转成ng-alain 的模块？

**Comment by cipchk** [comment]
你可以创建一个新模块，对比一下你自己创建模块的代码亦可了解差别。
