### ISSUE TITLE
主题系统中，能否为左侧导航中的分组项，提供更多的 theme 参数

### ISSUE THREAD

**Issue by dusdong** [ng-alain/ng-alain#541]
目前 对于左侧的导航菜单的分组项，只提供一个 @aside-nav-group-text-color 配置项，我在模仿阿里云的深色菜单时，感觉只靠字体颜色区分不是很明显。

我的配色代码：

```
// 顶部 阿里云风格
@header-hg: 50px;
@header-bg: #373d41;

// 左侧导航栏 阿里云风格
@aside-bg: #333744;
@aside-nav-text-color: rgba(255, 255, 255, .65);
@aside-nav-text-hover-color: #fff;
@aside-nav-group-text-color: rgba(255, 255, 255, .65);
@aside-nav-selected-text-color: #fff;
@aside-nav-selected-bg: #00c1de;
```

效果图：

![image](https://user-images.githubusercontent.com/3461709/41897890-28a14294-795b-11e8-97aa-1068ab6ca7cc.png)

能否增加下提供 字号、背景色、行高 的参数设置。

```
@aside-nav-group-bg
@aside-nav-group-width
@aside-nav-group-fontsize
```

**Comment by cipchk** [comment]
我不是很建议在 `sidebar-nav` 基础上修改成阿里云，必须是两种完全不同的实现方式。

**Comment by dusdong** [comment]
恩，我只是参考下阿里云的配色，这样可以突出工作区
