### ISSUE TITLE
Sidebar中菜单组能否考虑开关控制显示/隐藏？

### ISSUE THREAD

**Issue by goGetSomeFries** [ng-alain/ng-alain#542]
考虑到实际场景，菜单组是否能够做成显示隐藏可控制；

另外Menu中group属性在sidebar中未使用，是否后续通过group属性实现此功能？

**Comment by cipchk** [comment]
不会支持。

**Comment by goGetSomeFries** [comment]
@cipchk 请问Menu中group属性的作用是什么

**Comment by cipchk** [comment]
分组标记，做为第一层级的标记属性。

**Comment by fatesq** [comment]
第一层不能是菜单吗

**Comment by cipchk** [comment]
你可以设置为 `group: false` 来隐藏它们。https://ng-alain.com/components/sidebar-nav/en#Menu
