### ISSUE TITLE
旧版本升级 1.1.1 时，ng-alain 框架的样式不显示

### ISSUE THREAD

**Issue by yinhehuoxing** [ng-alain/ng-alain#543]
我们项目用的是早期的版本，【angular 5.0.0，ng-zorro-antd 0.6.5】 的，现在想要把项目的 ng-alain 版本升级为 1.1.1 版本的。现在框架升级以后，启动项目原有的框架样式有部分不显示。原有的依赖现在最新版本也没有了。这个要如何配置。有谁明白这里么？还清指定一下。拜谢！

比如下面这些以前用到了，现在没有要用什么替换？
@import '../node_modules/font-awesome/css/font-awesome.css';
@import '../node_modules/simple-line-icons/css/simple-line-icons.css';
@import '../node_modules/weather-icons/css/weather-icons.css';

**Comment by cipchk** [comment]
在 `angular.json` 中添加。
