### ISSUE TITLE
hmr.ts文件无法下载

### ISSUE THREAD

**Issue by zzz** [ng-alain/ng-alain#547]
使用命令下载时，会缺少一个文件，重复下载了三次，ng serve 就报错，@cipchk 能帮忙看下吗
![image](https://user-images.githubusercontent.com/39012698/42087404-a75d0d10-7bc8-11e8-96be-bb4640376bef.png)
![image](https://user-images.githubusercontent.com/39012698/42087534-0855f6a4-7bc9-11e8-9c6f-0c5034942d5b.png)

![image](https://user-images.githubusercontent.com/39012698/42087465-d7116c72-7bc8-11e8-80b3-628878c3ea1e.png)

**Comment by lzk1994** [comment]
@cipchk 能帮忙看下吗

**Comment by cipchk** [comment]
可以从 [hmr.ts](https://github.com/cipchk/ng-alain/blob/master/src/hmr.ts) 获取，我会检查 一下这个问题。

**Comment by zzz** [comment]
@cipchk 直接获取，会出现其它的问题，这些问题解决之后，运行ng serve 跑到95%就不跑了

**Comment by cipchk** [comment]
临时解决办法是，将 `main.ts` 替换为 [main.ts](https://github.com/cipchk/ng-alain/blob/7927d48395755ecde8d0c4255be63011aef74d8c/src/main.ts) 的版本，若你需要 hmr，可以初始化再运行一次：`ng g ng-alain:plugin hmr`。
