### ISSUE TITLE
run ng start

### ISSUE THREAD

**Issue by dsqdata** [ng-alain/ng-alain#550]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@6.1.0
3 info using node@v10.4.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle ng-alain@1.1.2~prestart: ng-alain@1.1.2
6 info lifecycle ng-alain@1.1.2~start: ng-alain@1.1.2
7 verbose lifecycle ng-alain@1.1.2~start: unsafe-perm in lifecycle true
8 verbose lifecycle ng-alain@1.1.2~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/root/my-project/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin:/root/apache-maven-3.3.9/bin:/usr/local/services/zookeeper/zookeeper-3.4.9//bin:/root/mongodb/mongodb-linux/bin
9 verbose lifecycle ng-alain@1.1.2~start: CWD: /root/my-project
10 silly lifecycle ng-alain@1.1.2~start: Args: [ '-c', 'ng serve -o' ]
11 silly lifecycle ng-alain@1.1.2~start: Returned: code: 2  signal: null
12 info lifecycle ng-alain@1.1.2~start: Failed to exec start script
13 verbose stack Error: ng-alain@1.1.2 start: `ng serve -o`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:304:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:961:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
14 verbose pkgid ng-alain@1.1.2
15 verbose cwd /root/my-project
16 verbose Linux 3.10.0-514.26.2.el7.x86_64
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
18 verbose node v10.4.1
19 verbose npm  v6.1.0
20 error code ELIFECYCLE
21 error errno 2
22 error ng-alain@1.1.2 start: `ng serve -o`
22 error Exit status 2
23 error Failed at the ng-alain@1.1.2 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]
~

**Comment by cipchk** [comment]
you can trying steps:

- remove `node_modules` `package-lock.json` or `yarn.lock`
- running `yarn`
