### ISSUE TITLE
@delon/form没有提供对简单数组对象的处理

### ISSUE THREAD

**Issue by jackywang615** [ng-alain/ng-alain#551]
我需要在sf中对一个字符串数组string[]进行操作时好像不允许如下的配置方式，目前文档中也没有提供对简单数组的配置方法。希望能加上此功能。

types: string[];

```javascript

      types: {
        type: "array",
        items: {
          type: "string"
        }
      }
```

**Comment by cipchk** [comment]
duplcated of https://github.com/cipchk/delon/issues/87

**Comment by selegiline** [comment]
> duplcated of https://github.com/cipchk/delon/issues/87

该链接已失效，遇到了同样的问题，请问该如何解决？
