### ISSUE TITLE
total does not work

### ISSUE THREAD

**Issue by phinney001** [ng-alain/ng-alain#552]
- ng-alain version: 1.1.1
- Angular version: 6.0.5
![4d7_k 9fqhfjo 6 m](https://user-images.githubusercontent.com/19651922/42203357-1a3a76b4-7ed1-11e8-8a9c-4abe5035d4be.png)
![qq 20180703145533](https://user-images.githubusercontent.com/19651922/42203392-30702000-7ed1-11e8-8f3f-39c26b888d75.png)
total does not work!

**Comment by cipchk** [comment]
请提示重现示例。

**Comment by cipchk** [comment]
若有更多细节请重新提交。
