### ISSUE TITLE
simple-table中的selectedRows计算方式

### ISSUE THREAD

**Issue by DesignHhuang** [ng-alain/ng-alain#553]
@cipchk  
`checkboxChange(list: SimpleTableData[]) {`
     `this.selectedRows = list;`
     `this.totalNodes = this.selectedRows.reduce((total, cv) => total + cv.nodeNum, 0, );`
`}`
这样写的话在第一页中选择的项，切到第二页的时候就没有了。如下图：
![33](https://user-images.githubusercontent.com/3368397/42206773-aea60300-7eda-11e8-958c-070285848b0a.png)
第一页中选择了一项，调用接口数量是790万项。这时候切到第二页中选择一项，
![34](https://user-images.githubusercontent.com/3368397/42206828-d91ed03a-7eda-11e8-90c4-ddec7720c94b.png)
调用接口变成了289万项，也就是说第一页并没有累加，实际选择的应该是两项，调用接口总量应该是1079万项。

**Comment by DesignHhuang** [comment]
修改了一下：
```javascript
checkboxChange() {
    this.data$.subscribe(res => {
        this.selectedRows = res.filter(value => value.checked);
        this.totalNodes = this.selectedRows.reduce((total, cv) => total + cv.nodeNum, 0, );
    });
}
```
我觉得还是用checked来判断选项会比较好，只是在定义实体的时候需要加上checked这个属性（checked?:boolean）。
不知道作者有没有其他好的解决办法？

**Comment by cipchk** [comment]
自行维护这种关系，因为示例中每一次都请求新的数据。
