### ISSUE TITLE
左侧导航展开收起状态跳转不同，展开跳链接，收起好像会匹配路由然后找不到跳默认dashboard(写的都是相对路径)

### ISSUE THREAD

**Issue by doudou2020** [ng-alain/ng-alain#554]
🚨 Issues 是用于BUG、Feature、进度追踪 🚨
🚨 The issue tracker is not for questions 🚨

如果有任何问题，可在以下方式获得答案：

- https://ng-alain.com/
- QQ Group：316911865
- https://segmentfault.com/t/ng-alain

**Comment by doudou2020** [comment]
设置的是externalLink，展开是可以跳转外链接，相对路径返回的是其他同域名下html资源，收起就会匹配路由不跳转

**Comment by cipchk** [comment]
请提供更详细信息。

**Comment by doudou2020** [comment]
您好，externalLink:"/system/list" 展开状态是好用的，是跳转 域名/system/list的资源(返回html)
收缩状态不可以，点击好像就会匹配路由，然后就匹配不到
