### ISSUE TITLE
关于simple-table添加[scroll]属性导致表头和表的内容没有对齐

### ISSUE THREAD

**Issue by zfywestbook** [ng-alain/ng-alain#558]
您好，近日使用了@delon/abc中的simple-table组件，在使用时发现添加滚动条后会出现如标题所示问题（见附图），暂未找到解决方法，如您能提供帮助将十分感谢。
![scroll](https://user-images.githubusercontent.com/26615440/42256041-6715ef44-7f81-11e8-95b4-0be9d6beb5c9.PNG)

**Comment by cipchk** [comment]
固定表头需要对所有列都指定宽度。细节，请参考 ng.ant.design。
