### ISSUE TITLE
在IE11下切换页面后，之前页面还存在

### ISSUE THREAD

**Issue by maplye** [ng-alain/ng-alain#56]
## Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

0.1.2

如：
点击进入/pro/form/advanced-form， 然后按一下F5刷新页面，然后再通过菜单点击进入如/elements/buttons页面，这个时候“高级表单”页面还继续在页面的下方。

**Comment by cipchk** [comment]
谢谢，ie11下的确存在 `matches` 不支持的问题，我会修正它，并且在未来更加注重IE上面兼容的问题。

**Comment by maplye** [comment]
Thanks for your effort, This open source is great, I have a plan to use it in the production, But we have lots of IE 11 client, so that will be very well if it have compatibility with IE.
