### ISSUE TITLE
DA_XLSX_CONFIG 项目发布无法正确获取配置信息

### ISSUE THREAD

**Issue by NG-GGBond** [ng-alain/ng-alain#560]
- ng-alain version: 1.0.5
- Angular version: 6.0.3

## 重现步骤，Steps to reproduce
以下配置完成以后，xlsx.full.min.js访问的是本地路径，
当运行 npm run build或者ng build --prod以后
发布到服务器，url依然访问cdn网络路径

**部分代码**
**delon.module.ts**
`import { DA_XLSX_CONFIG } from '@delon/abc';
export function XLSX() {
  return {
    url:'/assets/xlsx/xlsx.full.min.js',
    modules:[]
  }
}`
`{ provide: DA_XLSX_CONFIG, useFactory: XLSX }`

**完整代码**
`/**
 * 进一步对基础模块的导入提炼
 * 有关模块注册指导原则请参考：https://github.com/cipchk/ng-alain/issues/180
 */
import {
  NgModule,
  Optional,
  SkipSelf,
  ModuleWithProviders,
} from '@angular/core';
import { RouteReuseStrategy } from '@angular/router';
import { throwIfAlreadyLoaded } from '@core/module-import-guard';

import { NgZorroAntdModule } from 'ng-zorro-antd';
import { AlainThemeModule } from '@delon/theme';
import { DelonABCModule, ReuseTabService, ReuseTabStrategy } from '@delon/abc';
import { DelonAuthModule } from '@delon/auth';
import { DelonACLModule } from '@delon/acl';
import { DelonCacheModule } from '@delon/cache';
import { DelonUtilModule } from '@delon/util';
// mock
import { DelonMockModule } from '@delon/mock';
import * as MOCKDATA from '../../_mock';
import { environment } from '@env/environment';
const MOCKMODULE = !environment.production ? [DelonMockModule.forRoot({ data: MOCKDATA })] : [];

// region: global config functions

import { AdPageHeaderConfig } from '@delon/abc';
export function pageHeaderConfig(): AdPageHeaderConfig {
  return Object.assign(new AdPageHeaderConfig(), { home_i18n: 'home' });
}

import { DelonAuthConfig } from '@delon/auth';
export function delonAuthConfig(): DelonAuthConfig {
  return Object.assign(new DelonAuthConfig(), <DelonAuthConfig>{
    login_url: '/passport/login',
  });
}

import { DA_XLSX_CONFIG } from '@delon/abc';
export function XLSX() {
  return {
    url:'../assets/xlsx/xlsx.full.min.js',
    modules:[]
  }
}
// endregion

@NgModule({
  imports: [
    NgZorroAntdModule.forRoot(),
    AlainThemeModule.forRoot(),
    DelonABCModule.forRoot(),
    DelonAuthModule.forRoot(),
    DelonACLModule.forRoot(),
    DelonCacheModule.forRoot(),
    DelonUtilModule.forRoot(),
    //AdXlsxModule.forRoot({url:'/assets/xlsx/xlsx.full.min.js'}),
    // mock
    ...MOCKMODULE,
  ],
})
export class DelonModule {
  constructor(
    @Optional()
    @SkipSelf()
    parentModule: DelonModule,
  ) {
    throwIfAlreadyLoaded(parentModule, 'DelonModule');
  }

  static forRoot(): ModuleWithProviders {
    return {
      ngModule: DelonModule,
      providers: [
        // TIPS：若不需要路由复用需要移除以下代码及模板`<reuse-tab></reuse-tab>`
        {
          provide: RouteReuseStrategy,
          useClass: ReuseTabStrategy,
          deps: [ReuseTabService],
        },
        // TIPS：@delon/abc 有大量的全局配置信息，例如设置所有 `simple-table` 的页码默认为 `20` 行
        // { provide: SimpleTableConfig, useFactory: simpleTableConfig }
        { provide: AdPageHeaderConfig, useFactory: pageHeaderConfig },
        { provide: DelonAuthConfig, useFactory: delonAuthConfig },
        { provide: DA_XLSX_CONFIG, useFactory: XLSX },
      ],
    };
  }
}
`

**Comment by cipchk** [comment]
两个点：

- 建议使用 `useValue`
- 或使用 `AdXlsxModule.forRoot()` 注册方式

**Comment by NG-GGBond** [comment]
@cipchk 
AdXlsxModule.forRoot()方式使用过并不能正常打包，使用过ng-alain 1.0.5 以及完整git上的1.1.0，详情见
https://github.com/cipchk/ng-alain/issues/555

**Comment by 15738847829** [comment]
You can't comment at this time — your comment cannot be blank.

**Comment by 15738847829** [comment]
发送到是方法得到的得到的

**Comment by 15738847829** [comment]
奋斗奋斗的地方规范

**Comment by clong365** [comment]
delon.module.ts

`{ provide: DA_XLSX_CONFIG, useValue:{
            url: '/assets/xlsx/0.12.12/xlsx.full.min.js'
          }
        }`
