### ISSUE TITLE
左导航展开状态疑问

### ISSUE THREAD

**Issue by doudou2020** [ng-alain/ng-alain#561]
🚨 Issues 是用于BUG、Feature、进度追踪 🚨
🚨 The issue tracker is not for questions 🚨

如果有任何问题，可在以下方式获得答案：

- https://ng-alain.com/
- QQ Group：316911865
- https://segmentfault.com/t/ng-alain

**Comment by doudou2020** [comment]
左导航this.menuService.add(arr) mock数据是可以匹配展开状态，接口处理后的数据可以渲染但是不匹配路由展开对应的模块(已经设置是link不是externalLink)

**Comment by cipchk** [comment]
无效issues
