### ISSUE TITLE
nzCustomRequest的onSuccess问题

### ISSUE THREAD

**Issue by seahero520** [ng-alain/ng-alain#564]
"name": "ng-alain",
  "version": "1.0.6",
   angular: 6.0.0
   "ng-zorro-antd": "^0.7.1"

[我找到的参考demo](https://stackblitz.com/edit/ng-zorro-antd-setup-4bt3th?file=app%2Fapp.component.ts)
发现demo和我没啥区别，但是上传成功的文件无法正常置蓝。

**源码如下**
upload = (file: any) => {
      const req = new HttpRequest('POST', 'http://127.0.0.1:8082/verifyApi/verifyFileMD5', formData, {
        reportProgress: true
      });
   this.http.request(req).subscribe((event) => {
        if (event.type === HttpEventType.UploadProgress) {
          const percent = Math.floor((event.loaded / event.total) * 100);
          file.onProgress({percent: percent});
        }
        if (event.type === HttpEventType.Response) {
          file.onError();
          file.onSuccess(event.body, file.file, event);
        }
      });

上传完成后，如果使用onError 文件名正常置红，但使用onSuccess后文件名未正常置蓝
请问是什么原因？

**Comment by cipchk** [comment]
需要UI渲染，须自行维护 `fileList`
