### ISSUE TITLE
token

### ISSUE THREAD

**Issue by zzz** [ng-alain/ng-alain#565]
@cipchk 
接口报错怎么解决
Request header field token is not allowed by Access-Control-Allow-Headers in preflight response.
6.28号之前的版本不会报错，更新了之后就全部报这个错！

**Comment by cipchk** [comment]
拜过关公了吗？

**Comment by zzz** [comment]
社会人真jbnb，惹不起

**Comment by gin-lsl** [comment]
不是我说，这个报错提示已经很明显了吧？

**Comment by Kiuyam** [comment]
你TM是有多懒 百度把你的错误贴上去 第一个都解释得很清楚 嘴臭 脑子也不好使。

**Comment by gin-lsl** [comment]
@Kiuyam 行了行了。。骂战一旦开始，停下来就难了。这么长时间过去了。楼主恐怕也百度并解决了吧。
