### ISSUE TITLE
建议@delon/form中widget为text时增加数据格式化的功能

### ISSUE THREAD

**Issue by jackywang615** [ng-alain/ng-alain#566]
很多时候我们希望使用@delon/form进行数据的快速展示，现在的text不支持进行格式化操作，一些数据显示出来并不理想，只有采用custom自定义的方式才能实现，但过于繁琐。

希望能增加一个格式化函数之类的允许我们在进行静态数据展示时更方便

**Comment by cipchk** [comment]
渲染方式同业务联系非常紧密，请自行参考[完全自定义](https://ng-alain.com/form/customize#%E4%BA%8C%E3%80%81%E5%AE%8C%E5%85%A8%E8%87%AA%E5%AE%9A%E4%B9%89) 实现。
