### ISSUE TITLE
建议@delon/form增加grid布局方式

### ISSUE THREAD

**Issue by jackywang615** [ng-alain/ng-alain#567]
建议z增加如下图的布局方式，有时候水平/竖直显示出来每一项都太宽了，inline显示出来又太窄了

![tim 20180705115137](https://user-images.githubusercontent.com/9586655/42301832-0b3a1dca-804a-11e8-9be5-d3ae23235b76.png)

**Comment by cipchk** [comment]
目前不会考虑非 antd 支持的规范，请自行编写CSS。
