### ISSUE TITLE
ng add ng-alain

### ISSUE THREAD

**Issue by fstanwh** [ng-alain/ng-alain#568]
🚨 Issues 是用于BUG、Feature、进度追踪 🚨
🚨 The issue tracker is not for questions 🚨

如果有任何问题，可在以下方式获得答案：
ng add ng-alain
The specified command add is invalid. For available options, see `ng help`.
不能识别这个命令，还需要安装什么插件吗？
- https://ng-alain.com/
- QQ Group：316911865
- https://segmentfault.com/t/ng-alain

**Comment by cipchk** [comment]
`ng add` 只支持 angular6 以上版本。
