### ISSUE TITLE
NzModalService创建对话框，如果是独立定义的组件，build之后无法正确创建

### ISSUE THREAD

**Issue by sunger** [ng-alain/ng-alain#569]
- ng-alain version: 1.1.3
- Angular version: ^1.0.0

## 【必填项】重现链接，http://cs.sxxffww.com/#/product/product/kabao

凡是通过此方式创建的对话框（KaBaoFormComponent为独立定义的组件），build之后，都是报错误
 const modal = this.modalService.create({
            nzTitle: '编辑卡包',
            nzWidth:700,
            nzContent: KaBaoFormComponent,
...

具体错误信息：
TypeError: Cannot read property 'create' of undefined
at n.createModal (main.d776a37461a5e00f753a.js:1)

## 重现步骤，Steps to reproduce
进入测试：http://cs.sxxffww.com/index.html，用户密码： admin  888888
菜单：产品管理-》卡包-》新增

**Comment by cipchk** [comment]
请至 https://github.com/NG-ZORRO/ng-zorro-antd 找答案。
