### ISSUE TITLE
怎么捕获http异常？

### ISSUE THREAD

**Issue by shankesgk2** [ng-alain/ng-alain#571]
`
this.http.post('signin', value).pipe(catchError(err => {
        console.error('error', err);
        return of({});
      })).subscribe((res: any) => {
        console.log('成功', res);
      }, error => {
        console.log('err');
      })
`
返回422错误，捕获不到。

**Comment by cipchk** [comment]
可能被拦截器捕获，若希望在外部捕获，需要在拦截器内重新抛出异常。具体见 angular.io 官网。
