### ISSUE TITLE
请教theme的问题

### ISSUE THREAD

**Issue by zhaojieip** [ng-alain/ng-alain#572]
请问下，最新版支持动态修改主题吗

**Comment by cipchk** [comment]
目前能做到颜色动态修改，可以参考 ng-alain.com 站点的做法。

**Comment by zhaojieip** [comment]
@cipchk 
![image](https://user-images.githubusercontent.com/32030955/42609495-7d01f368-85bf-11e8-9000-9b3724e40b4d.png)
我想实现这种，项目下大佬又没的代码案例，找了下你给网址的文档，没找到具体实现的说明，还请大佬，详细赐教一下，多谢！
