### ISSUE TITLE
 NullInjectorError: No provider for NzModalRef!

### ISSUE THREAD

**Issue by fengxiaopeng** [ng-alain/ng-alain#573]
- ng-alain version: 1.1.1
- Angular version: 6.0.5

## 重现步骤，Steps to reproduce

1、根据https://ng-alain.com/form/getting-started使用动态表单
2、在模态框中使用动态表单的实例，ng g ng-alain:edit edit
3、无法运行示例程序，提示No provider for NzModalRef!

core.js:1542 ERROR Error: Uncaught (in promise): Error: StaticInjectorError(AppModule)[SysEditComponent -> NzModalRef]: 
  StaticInjectorError(Platform: core)[SysEditComponent -> NzModalRef]: 
    NullInjectorError: No provider for NzModalRef!

**Comment by cipchk** [comment]
确保合理的注入 ng-zorro-antd 模块。

**Comment by shareven** [comment]
> 确保合理的注入 ng-zorro-antd 模块。

能说明白一点吗?具体在哪怎么写?

**Comment by cipchk** [comment]
另一方面也有可能依赖包安装 不成功导致的，可以试着清除  node_moduels 和 package-lock.json 重新安装依赖包。
