### ISSUE TITLE
更换为通过服务端接口获取数据时出错，未能正常执行

### ISSUE THREAD

**Issue by songch080910** [ng-alain/ng-alain#574]
使用现在github上的最新版1.1.3
environment.ts 配置 
export const environment = {
  SERVER_URL: `./`,
  production: true,
  useHash: true,
  hmr: false,
};
environment.prod.ts 配置 
export const environment = {
  SERVER_URL: `http://localhost/szgh/serve/public/api`,
  production: true,
  useHash: false,
  hmr: false,
};

执行代码：通过远程接口获取数据（接口没有做任何验证，调试接口都正常）
    this.http.get('/menus').subscribe((res: any) => {
      console.log(res);
    });

DelonAuthConfig 配置，xx-token实际服务端现在并没有做验证工作
export function delonAuthConfig(): DelonAuthConfig {
  return Object.assign(new DelonAuthConfig(), <DelonAuthConfig>{
    store_key: 'xx-token',
    token_send_key: 'xx-token',
    // login_url: '/passport/login',
  });
}

报错信息：接口没有正常执行，本地mock可以正常执行，帮我排查一下错误原因
HttpErrorResponse
error:null
headers:HttpHeaders
message:"Http failure response for (unknown url): 401 From Simple Intercept --> http://ng-alain.com/docs/auth"
name:"HttpErrorResponse"
ok:false
status:401
statusText:"From Simple Intercept --> http://ng-alain.com/docs/auth"
url:null
__proto__:HttpResponseBase

**Comment by liuguolong1991** [comment]
请问找到问题了吗，我遇到了相同情况
