### ISSUE TITLE
点击弹出窗口的时, body标签被加上了padding-right: 17px; 严重影响体验

### ISSUE THREAD

**Issue by anarckk** [ng-alain/ng-alain#579]
代码：
![image](https://user-images.githubusercontent.com/27038948/42742101-ae3c503a-88ea-11e8-8379-92c27c7edcbd.png)
点击弹出前：
![image](https://user-images.githubusercontent.com/27038948/42742115-cf001d24-88ea-11e8-880c-745589bc50a0.png)
点击弹出后：
![image](https://user-images.githubusercontent.com/27038948/42742117-ddc2f4d0-88ea-11e8-9f82-91b92612a5b9.png)

**Comment by anarckk** [comment]
希望指导如何修改，让弹出窗口之后页面不会抖动

**Comment by cipchk** [comment]
我想原因可能是 ng-alain 默认对滚动条进行美化，而 `NzModel` 在打开时会强制加上 `padding-left: 17px`，这里的 `17px` 是包含着非美化时的滚动条宽度。

你可以尝试取消 ng-alain 的滚动条美化：`@scrollbar-enabled` 参数设置为：`false`

**Comment by anarckk** [comment]
有效的，几天没来给关了，ng-alain用了快一个月感觉非常好

**Comment by harrylyh** [comment]
> 有效的，几天没来给关了，ng-alain用了快一个月感觉非常好

大兄弟，这个是在哪里关的？

**Comment by anarckk** [comment]
> > 有效的，几天没来给关了，ng-alain用了快一个月感觉非常好
> 
> 大兄弟，这个是在哪里关的？

我后来在app.component的view check里面直接设置document.body.paddingRight=0
