### ISSUE TITLE
建议增加一个sidebar组件

### ISSUE THREAD

**Issue by jackywang615** [ng-alain/ng-alain#580]
建议增加一个sidebar组件

![2018-07-16_15-24-52](https://user-images.githubusercontent.com/9586655/42746863-7675d578-890c-11e8-911e-eb0b6157be83.gif)

**Comment by cipchk** [comment]
zorro 已经开发中，请关注 https://github.com/NG-ZORRO/ng-zorro-antd/issues/1565
