### ISSUE TITLE
关于颜色选择窗口导致chrome崩溃

### ISSUE THREAD

**Issue by askie** [ng-alain/ng-alain#582]
- ng-alain version: 最新
- Angular version: 最新
- macOs  chrome版本 67.0.3396.99

## 【必填项】重现链接，Reproduction link
https://cipchk.github.io/ng-alain/#/delon/qr

## 重现步骤，Steps to reproduce
![image](https://user-images.githubusercontent.com/1140973/42795801-d8b09848-89b8-11e8-86d6-e63d95653442.png)

关闭颜色对话框，导致chrome崩溃

**Comment by cipchk** [comment]
DEMO采用的是 `type=“color"` 属于HTML5原生颜色选择器。
