### ISSUE TITLE
Support preventing multi-submit in delon/form SFComponent

### ISSUE THREAD

**Issue by xiaotupansy** [ng-alain/ng-alain#583]
I think it's a common scenario to prevent multi-submit.
Here're some solutions coming to my mind:

1. simply disable submit button after submit
2. set a submit interval for form
3. disable submit button and provide a method/event emitter to change form's behavior

**Comment by cipchk** [comment]
https://ng-alain.com/form/getting-started#%E6%8C%89%E9%92%AE%E8%AF%B4%E6%98%8E

**Comment by xiaotupansy** [comment]
I've read this solution before.
But I think it's more convenient to add built-in support for common issue.

**Comment by xiaotupansy** [comment]
参照table组件的效果
https://ng.ant.design/components/table/zh#components-table-demo-ajax

外层套一个nz-spin即可
`<nz-spin [nzSpinning]="isSpinning">
    <sf #sf *ngIf="schema" [schema]="schema" (formSubmit)="submit($event)">
    </sf>
</nz-spin>`

**Comment by cipchk** [comment]
关闭 issues，若有相关问题请重新提交新的。
