### ISSUE TITLE
refactor(all): 关于 2.0 的畅想

### ISSUE THREAD

**Issue by cipchk** [ng-alain/ng-alain#588]
首先非常感谢所以长期一直以来对 ng-alain 支持的人。

ng-alain 一直以来都过度的追求快速迭代，以及至忽略了 ANTD 最重要的“自然”元素，我在多个项目中运用了 ng-alain，但从开发人员的角度而言，ANTD 很好的帮助我们解决了UI样式层面一些细节，我们可以轻松的开发一个蛮不错的中后台。

ng-alain 一直以"**让开发者更加专注于业务**"的目标在践行，可越是开发越是发现忽略了“自然”的重要元素，这些元素不光是UI样式层面，也包括以开发人员“自然”的体现，ng-alain 已经越来越有些背离。

## 目标

中后台大部分开发动作就是CURD，进一步简略就是列表、查看、编辑三种页。我们每天的大部分工作也是如此，而如何让这一切的开发动作执行起来应该很“顺”呢？

### 约定

约定的核心在于习以为常，无异议。

**命名规范**

命名风格应该是以开发人员角度出发，例如我们希望一个表格应该是 `table` 表述、一个查看片断应该是 `view`、一个编辑片断应该是 `edit`。

始终贯彻一种驼峰式命名风格。

**风格统一性**

每一个组件都属于自己的风格，例如大小、线框等，但往往这些风格是整个中后台是统一的，应该将这些风格在一开始就统一决定。

### API 定义

**属性多态性**

当构建一个数据表格时，表格的数据源可能来自远程数据或本地静态数据，但我们不应该过度的将数据源做成两个不同属性加以区分，他们只是不同的数据来源而已，但对于表格而言是统一：

```html
<table [data]="url"></table>
<table [data]="list"></table>
```

**属性内聚性**

同一个功能的属性应该更内聚，例如我们表述一个HTTP请求时，包含：请求方法、请求域、参数等，这些属性应该统一在一个对象值体现，`HttpClient` 请求就是一个非常好的例子。

```html
[reqMethod]="'GET'" [reqParams]="{ a: 1 }"
```

```html
[req]="{ method: 'get', params: { a: 1 } }"
```

## 组件重复性

目前有很多组件有着功能重复性，例如：表单布局类（`desc-list`、`simple-html-form`、`standard-form-row`），这些组件本质都是解决布局问题，但我们对编辑、查看、搜索做为三套组件。

我们应该使用一种更简单、更无感来解决表单布局，不管是编辑、查看、搜索。

## 社区

ng-alain 一直只有一个群，导致很多信息的探讨过后都被忽略。

**Comment by xiaotupansy** [comment]
几点看法：

1. 
对于所有显示与编辑的组件来说，数据的定义是第一位的，api之类获取数据的定义是第二位的。也就是说，当一个数据实体已经定义好了之后，它的显示，基础crud，列表的展现都可以使用通用的方法来实现。

2. 
数据实体可以使用jsonschema来定义，后端已经有dto的概念，那么使用工具自动生成，可以保证前后对数据的定义是一致的。

3. 
数据实体定义一致之后，那么调用数据的接口方法也能协调一致，也就是说，我不需要指定api传什么参数。我只需要描述，这是一个列表，即可自动获取对应的数据。

以下是本地已经实现的一些功能里面，调用的显示，希望能给你一些参考：

1.显示列表，指定的显示列为4列
`<app-domaintable size="middle" pageSize="5" domainType="CategoryDto" [columns]='["ChineseName","EnglishName","ThumbAddress","Rank"]'>
</app-domaintable>`

2.显示一个新建form
`<app-domainform domainType="IntIdDto"></app-domainform>`

3.显示一个修改form，通过Id获取指定数据
`<app-domainform domainType="IntIdDto" domainId="3"></app-domainform>`

4.显示一个部分修改的form
`<app-domainform domainType="IntIdDto" domainId="3" [columns]='["Name","IsOn","Price"]'></app-domainform>`


按照此种思路，核心就在于dto（后台）/schema（前台）的设计，如果从此处出发开始进行设计思考，感觉会比较深一些。

**Comment by newmann** [comment]
建议：
1、可自定义键盘快捷键，以便键盘操作。
2、更多一点的案例说明， 比如动态表单的应用案例。
3、移植到electron、chrome扩展、微信等平台的脚手架；

**Comment by xingkoo** [comment]
如果能增加ionic支持就更好了.省得写完web还得写app

**Comment by jiankian** [comment]
> 如果能增加ionic支持就更好了.省得写完web还得写app

后台干嘛要做APP。。

**Comment by xingkoo** [comment]
> > 如果能增加ionic支持就更好了.省得写完web还得写app
> 
> 后台干嘛要做APP。。

中后台和app有啥差别?

**Comment by bokire** [comment]
简化列表、查看、编辑三种页除了定义大量通用组件减少html内容，还要减少列表、查看、编辑三种页面对应Component的重复代码。
简单的CRUD功能其实很固定，可以定义一些抽象类供Component来继承。
抽象类中实现了大多数的CRUD代码，具体的Component只需提供接口服务和实现父类的抽象方法就能实现完整的CRUD操作。
页面有个性化需求的时候也可对抽象类中的方法进行重写，方便扩展。
