### ISSUE TITLE
simple-table 多属性排序问题

### ISSUE THREAD

**Issue by xingkoo** [ng-alain/ng-alain#589]
**PS: 涉及请求后端,实在不知道怎么做在线示例,直接帖代码了,请见谅.**

````
<simple-table [data]="'api'" [columns]="columns" [multiSort]="true"></simple-table>
````

````
// 表格列配置
  columns: SimpleTableColumn[] = [
    {
      title: '编号',
      index: 'id',
      render: 'id',
      sorter: (a, b) => true,
      sortKey: 'sort',
      sortReName: { ascend: 'id', descend: 'id.desc' }
    },
    { title: '标题', render: 'title' },
    {
      title: '状态',
      index: 'status',
      width: '100px',
      format: function (cell: any) {
        return cell.status === '1' ? '正常' : '作废';
      },
      sorter: (a, b) => true,
      sortKey: 'sort',
      sortReName: { ascend: 'status', descend: 'status.desc' }
    }
  ];
````

期望获取到的结果为  ```` ?sort=id,status-desc ````  逗号分隔多个属性,  横线区分升降序.
之前提过一个[issue ](https://github.com/cipchk/ng-alain/issues/434) ,
答复是   ```` 相同排序 key 时，应该合并 ````
理论上应该可以达到期望结果的.
不知道是不是我在设置上存在问题,使用如上代码,并没有获取到我期望的结果. 依然是单属性排序. 结果为 ````?sort=id```` 或 ````?sort=status-desc````
希望能够帮我解答一下.

**Comment by cipchk** [comment]
https://ng-alain.com/components/simple-table

**Comment by xingkoo** [comment]
我有看过官网显示代码.
他产生了如下的请求:
https://randomuser.me/api/?results=3&pi=1&ps=10&a=1&b=2&name.last=descend&gender=descend
即 ```` name.last=descend&gender=descend ````
而后端需要的结构是  ```` ?sort=name,-gender ````
按参数中的 ````multiSort````为直时,应该相同的key合并,那么至少应该得到 ````?sort=name,gender.desc```` 类似的请求结果.
在现有的演示中,以及我做的其他尝试,并没有找到可以实际类似结果的方法.
我不知道是我使用不正确,还是什么原因,麻烦你帮忙看一下.

**Comment by xingkoo** [comment]
**报告Bug.**
仅当如下设置时,多属性排序才会生效.
```` multiSort: { key: 'sort', separator: ',', name_separator: '_' } ````

演示代码是这么写的 ```` <simple-table multiSort></simple-table>````,
源码里面讲到这么一段:
````
/**
 * 多排序相同排序 key 时合并规则
 */
export interface SimpleTableMultiSort {
    /** 请求参数名，默认：`sort` */
    key?: string;
    /** 不同属性间分隔符，默认：`-` */
    separator?: string;
    /** 列名与状态间分隔符，默认：`.` */
    name_separator?: string;
}
````
读取这些信息,都指向设置````multiSort=true````即可开启多属性排序(SimpleTableMultiSort有设置值).
所以我的理解是,文档或演示代码需要修正.
