### ISSUE TITLE
建议移除antd-style文件夹下的代码

### ISSUE THREAD

**Issue by icycore** [ng-alain/ng-alain#59]
改为直接从antd包中引入似乎更妥当，除非作者需要直接hack掉原有的less样式。
`@import "~antd/lib/style/index.less";`
`@import "~antd/lib/style/themes/default.less";`

**Comment by cipchk** [comment]
我尝试过，但是 `~antd` 这类语法好像在 angular cli 中并不支持的样子。

**Comment by icycore** [comment]
我已经在你的项目基础上改写成功了，晚一点把项目推到Github给你瞧瞧。

**Comment by icycore** [comment]
https://github.com/icycore/ZorroAdmin

**Comment by cipchk** [comment]
好样的，不过需要依赖 `antd` 并不是很明智的选择，因为她是 React 版本，我会建议 ng-zorro-antd 团队在npm中保留 styles 目录，这样此问题可以更好的解决了。

同时我建议重新打开此 issue，以便我更好的跟进，谢谢。
