### ISSUE TITLE
SFComponent增加多列显示支持

### ISSUE THREAD

**Issue by xiaotupansy** [ng-alain/ng-alain#590]
不知道SFComponent是否内置了多列显示的支持能力。
当前看下来是一个属性就是一行。
如果在弹出框里面打开的话，那么两个属性一行或者三个属性一行是常见需求。
如果已经实现，能否给出实例。
如果没有，是否能考虑下给出实现。

**Comment by cipchk** [comment]
ng-alain.com

**Comment by xiaotupansy** [comment]
我这真找不到，官网我找很久了。
我意思是在调用SF的时候
<sf *ngIf="schema" [schema]="schema" (formSubmit)="submit($event)"></sf>
不需要我再写代码了，给个参数，直接就能2列显示。

**Comment by cipchk** [comment]
https://ng-alain.com/form/getting-started#%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8
`DelonFormConfig` 全局覆盖。

**注：** 这样会影响 `mode` 的优先级。

**Comment by xiaotupansy** [comment]
我意思是说，我需要sf两列就两列，想一列就一列，并不需要全局覆盖。
sf组件有个layout参数，但是当设置这个参数为inline的时候，会出现一个问题，就是两列布局的时候，第二列无法对齐。

**Comment by cipchk** [comment]
https://ng-alain.com/form/schema#%E5%93%8D%E5%BA%94%E5%BC%8F%E5%B1%9E%E6%80%A7-SFGridSchema

**Comment by MIAOMIAOUP** [comment]
怎没解决的 能粘出代码吗

**Comment by xingkoo** [comment]
配置ui参数可以实现的啊.
https://ng-alain.com/form-pages/validator
