### ISSUE TITLE
按照官方文档开始创建项目，界面是这样的，是什么错误呢？如有解答，小白不胜感激！

### ISSUE THREAD

**Issue by Sunshine-L** [ng-alain/ng-alain#592]
🚨 Issues 是用于BUG、Feature、进度追踪 🚨
🚨 The issue tracker is not for questions 🚨

如果有任何问题，可在以下方式获得答案：

- https://ng-alain.com/
- QQ Group：316911865
- https://segmentfault.com/t/ng-alain
![default](https://user-images.githubusercontent.com/41154870/42980110-61453032-8c08-11e8-95a5-248d4ba567ad.PNG)
![j](https://user-images.githubusercontent.com/41154870/42980161-b72d903e-8c08-11e8-97db-1781da03ff03.PNG)

**Comment by NitronPlus** [comment]
使用cli创建的项目是这样的
需要完整例子请直接clone repo

**Comment by Sunshine-L** [comment]
已解决，谢谢！
