### ISSUE TITLE
使用hmr是报错

### ISSUE THREAD

**Issue by zhengyanghuaer** [ng-alain/ng-alain#594]
🚨 Issues 是用于BUG、Feature、进度追踪 🚨
🚨 The issue tracker is not for questions 🚨

如果有任何问题，可在以下方式获得答案：

- https://ng-alain.com/
- QQ Group：316911865
- https://segmentfault.com/t/ng-alain
![image](https://user-images.githubusercontent.com/35128870/42987591-5a6e0c06-8c2c-11e8-8dba-0ef8424451a9.png)

**Comment by cipchk** [comment]
https://github.com/cipchk/ng-alain/blob/master/package.json#L27
