### ISSUE TITLE
能否去掉当拥有子菜单,但子菜单都被隐藏时的箭头图标

### ISSUE THREAD

**Issue by shilim-developer** [ng-alain/ng-alain#596]
能否去掉当拥有子菜单,但子菜单都被隐藏时父菜单的箭头图标

**Comment by cipchk** [comment]
尝试从业务角度解决这种问题，暂时不考虑为了这种细节增加很多多余的判断。

**Comment by shilim-developer** [comment]
就是因为想了没法办很好的解决才提的,因为有一个列表页,这个列表页里面可以跳转其他页面,但是这些页面都不需要在菜单显示,既然提供了隐藏,当所有都隐藏了,其实等同于没有子菜单,我觉得隐藏掉折叠按钮不是一个合理的存在吗.我现在只能把它提到上一级菜单隐藏.这样子也没法使面包屑按照"列表页/其他页"这样显示,但本也应该是这样的.
所以,我觉得这个判断应该是合理的吧

**Comment by cipchk** [comment]
抱歉，不考虑支持，尝试使用 `nz-table`

**Comment by askie** [comment]
+1
