### ISSUE TITLE
alain无法自动设置中文问题

### ISSUE THREAD

**Issue by water-zzh** [ng-alain/ng-alain#597]
系统初始的时候，调用  
 this.i18n.use("zh-CN");
this.settingsService.setLayout('lang', "zh-CN");
这两个方法，设置无效。
重新刷新页面后，就转成中文了。或者手动选择语言，切换到英文，然后再切回中文，系统就变成中文了。
不知这算不算BUG，还是我哪里配置错了？

**Comment by cipchk** [comment]
麻烦提供具体的可重现的步骤。

**Comment by water-zzh** [comment]
startup.service里的默认设置：
            this.i18n.use(this.i18n.defaultLang);
            this.settingService.setLayout('lang',this.i18n.defaultLang);
            // setting language data
            this.translate.setTranslation(this.i18n.defaultLang, langData);
            this.translate.setDefaultLang(this.i18n.defaultLang);
按照文档的说明，这应该就是设置成中文的。但是我通过登录页，登入系统后，菜单和页面内容，全部显示英文（并且是非正常英文设置格式）。所以我尝试在登录完成后，再次设置中文，但是结果还是一样，无法实现默认设置成中文模式。

**Comment by DesignHhuang** [comment]
可以设置的，不过你要自己改一下代码。

**Comment by water-zzh** [comment]
代码改了，没生效。

**Comment by DesignHhuang** [comment]
建议你仔细读一下i18n.service.ts   尤其是下图部分，看看逻辑是不是正确。
![image](https://user-images.githubusercontent.com/3368397/43114926-e9ab8d76-8f33-11e8-9f68-4bf3139b7ade.png)

**Comment by water-zzh** [comment]
zorro:zh-CN
i18n.service.ts:38 {locale: "zh-cn", Pagination: {…}, DatePicker: {…}, TimePicker: {…}, Calendar: {…}, …}
i18n.service.ts:43 datefns:zh-CN
i18n.service.ts:46 {distanceInWords: {…}, format: {…}}distanceInWords: localize: ƒ localize(token, count, options)__proto__: Objectformat: formatters: {MMM: ƒ, MMMM: ƒ, dd: ƒ, ddd: ƒ, dddd: ƒ, …}formattingTokensRegExp: /(\[[^\[]*\])|(\\)?(x|ss|s|mm|m|hh|h|do|dddd|ddd|dd|d|aa|a|ZZ|Z|YYYY|YY|X|Wo|WW|W|SSS|SS|S|Qo|Q|Mo|MMMM|MMM|MM|M|HH|H|GGGG|GG|E|Do|DDDo|DDDD|DDD|DD|D|A|.)/g__proto__: Object__proto__: Object

这是我打印的日志，显示设置都是中文，但是内容无法转成中文。（本来想截图，github传不上去）

**Comment by to0simple** [comment]
中文无法加载问题，是因为中文命名的错误 zh_CN与zh-CN仔细查看代码修改一下就好了

**Comment by cipchk** [comment]
关闭 issues，若有相关问题请重新提交新的。
