### ISSUE TITLE
使用路由复用时，通过nz-dropdown中子菜单跳转到新路由，下拉菜单没有收回

### ISSUE THREAD

**Issue by pengb0** [ng-alain/ng-alain#599]
- ng-alain version: 1.1.5
- Angular version: 6.0.9

Reproduction link:  https://stackblitz.com/edit/ng-alain-setup-7ntmj9

## 重现步骤，Steps to reproduce
1、点击下拉菜单中子菜单
2、跳转到新的路由后，原页面中的下拉菜单不会收回，如下图：

![image](https://user-images.githubusercontent.com/27408827/43200583-8a5b43a0-9048-11e8-85fd-d4eb2f0ba5c7.png)

**Comment by cipchk** [comment]
已知问题，这是因为菜单是动态构建的，组件复用是以当前组件树为准，而下拉菜单的构建方式相对于是脱离的，因此会产生以上情况。

准确来说这种情况只会发生在，使用浏览器前后退时。

**Comment by pengb0** [comment]
暂时通过click事件，用router导航到新页面解决了

`setTimeout(()=>{
 ...
   // 跳转到新页面
})`
