### ISSUE TITLE
登录页出现滚动条

### ISSUE THREAD

**Issue by tjweega** [ng-alain/ng-alain#6]
登录页出现滚动条

![image](https://github.com/tjweega/image/blob/master/TIM%E6%88%AA%E5%9B%BE20170902085353.png?raw=true)

**Comment by cipchk** [comment]
抱歉，我无法重现，能否提供更多细节，谢谢。

**Comment by MicroLord** [comment]
更改这个文件：ng-alain/src/app/shared/styles/app/utils/abs.scss
确实有这个问题，把这个地方的50%改为100%就可以了，但我不确定百分之多少是最合适的！
![css](https://user-images.githubusercontent.com/10664096/30010769-cb094e1c-9164-11e7-86df-3b400026492c.png)

**Comment by cipchk** [comment]
@MicroLord @tjweega 奇怪，你们怎么做到弄出滚动条的？不管是iphone、android、桌面浏览器，我都无法重现这一个情况。

**Comment by MicroLord** [comment]
谷歌浏览器
版本 60.0.3112.113（正式版本） （64 位）
有这个问题，mac系统

**Comment by cipchk** [comment]
@MicroLord  我同你一样。我的意思是说是怎么操作会有滚动条的呢？

**Comment by MicroLord** [comment]
选择登录界面就有了呀，mikasaleslie@163.com ，我的邮箱！ 想加你好友，兄弟，发一封邮件我！

**Comment by cipchk** [comment]
```javascript
'39885449'.split('').reverse().join('')
```
