### ISSUE TITLE
reuse-tab 国际化 不可用

### ISSUE THREAD

**Issue by wichochiu** [ng-alain/ng-alain#600]
- ng-alain version: 1.1.5
- Angular version: 6.0.0

## 【必填项】重现链接，Reproduction link

![tim 20180726102455](https://user-images.githubusercontent.com/11786029/43237862-43c29e68-90be-11e8-9be5-8dc522416481.png)

**Comment by cipchk** [comment]
`i18n` 字段其决于外部值，建议在 `<reuse-tab>` 所处位置监听 i18n 变化并重新赋值。
