### ISSUE TITLE
A merge conflicted on path "/src/main.ts".

### ISSUE THREAD

**Issue by YangManong** [ng-alain/ng-alain#601]
- ng-alain version: X.Y.Z
- Angular version: X.Y.Z

![capture](https://user-images.githubusercontent.com/17910519/43299665-2a224b6e-9129-11e8-9fe1-3a4f756bbc1f.PNG)

## 重现步骤，Steps to reproduce
ng new demo --style less
cd demo
ng add ng-alain
when i run this command code, it gave me A merge conflicted on path "/src/main.ts". error

**Comment by cipchk** [comment]
cli 有一系列测试用例保证每个版本的可用性，目前没有发现这种情况。

我想可能会是依赖包下载不全引起的，可以尝试给 angular cli 设定为 `yarn` 来安装依赖：

```bash
ng config -g cli.packageManager yarn
```

并使用淘宝源，自行Google or Baidu

**Comment by ConDey** [comment]
use Angular6.0.0  your version  6.1.0  unsupported

**Comment by LittleSixer** [comment]
使用最新的@angular/cli会导致该问题 ng new 生成的angular版本为6.1会导致不兼容 安装@angualr/cli@6.0.0版本，使用该版本可以解决该问题

**Comment by YangManong** [comment]
thanks guys
