### ISSUE TITLE
动态表单（不是custom自定义那种）添加自定义标签是否可行？

### ISSUE THREAD

**Issue by zhaojieip** [ng-alain/ng-alain#603]
在下图红色边框的位置我想添加一个自定义标签不知是否可以，因为要实现表单每项（红色边框包裹）都可以拖动，因为用的拖动组件自定义了两个标签，上面绑定了一些功能。所以必须加上，请问大佬，是否可行。

![image](https://user-images.githubusercontent.com/32030955/43312408-c7c73852-91bf-11e8-9269-4a60fdd77d10.png)

**Comment by cipchk** [comment]
不支持，建议使用原生表单写法。
