### ISSUE TITLE
simple-table increase double click event

### ISSUE THREAD

**Issue by bingyun123** [ng-alain/ng-alain#607]
simple-table可以为Row增加双击回调事件吗？
现在有个需求是双击行显示明细页，如果支持双击回调事件，这个需求就方便实现了。
请考虑下，谢谢！

Can simple-table add double-click callback events for Row?
There is now a need to double-click on the line to display the detail page. If double-click callback events are supported, this requirement is easily implemented.
Please consider, thank you!

**Comment by xingkoo** [comment]
估计够呛.单击都没有,双击估计更不会做了.

> 在 2018年7月31日，下午2:09，bingyun <notifications@github.com> 写道：
> 
> 请考虑下，谢谢！
> 
>
