### ISSUE TITLE
IE 9兼容性问题

### ISSUE THREAD

**Issue by leoyfm** [ng-alain/ng-alain#608]
ng 创建的 空项目，放开 polyfills里的注释。用 npm run build 后 放到 服务器里用ie9 浏览，报错。
![image](https://user-images.githubusercontent.com/1009894/43459884-8faa8fec-9501-11e8-8310-d438bc76a9bb.png)

问一下，想让项目兼容ie9，具体怎么做？

**Comment by HuangFuQuang** [comment]
我是尽量避免使用一些不兼容的东西

**Comment by HuangFuQuang** [comment]
尽量避免使用一些不兼容的特性

**Comment by wenyuantc** [comment]
骚年放弃ie9把

**Comment by cipchk** [comment]
参考： https://angular.cn/guide/browser-support#enabling-polyfills
