### ISSUE TITLE
simpe table 怎么重置所有filter的选项

### ISSUE THREAD

**Issue by YuiFn** [ng-alain/ng-alain#610]
配合搜索做重置操作的时候，希望同时清除已经选择被选择的filter项目。数据源选择的是url

**Comment by cipchk** [comment]
请提供可重现在线示例。

**Comment by YuiFn** [comment]
https://cipchk.github.io/ng-alain/#/pro/list/table-list

simpe table中的filter(状态)，重置查询表单的时候，同时重置filter中的选项
