### ISSUE TITLE
ReuseTabService 能否提供类似 open()、close()、active() 功能？

### ISSUE THREAD

**Issue by dusdong** [ng-alain/ng-alain#616]
对 ReuseTabService 功能增强：
open() - 打开tab页
close() - 关闭某Tab页
active() - 激活某Tab页

使用场景：list页面 可以更方便的控制 edit页面

**Comment by dusdong** [comment]
1、主Tab页对子Tab页可控（打开、关闭、激活）。

2、opne() 之前可判断该url是否已经打开：如果已经打开，则激活老窗口；否则，打开新窗口

3、open() 之后可以返回一个 TabId，可针对TabId进行关闭或激活操作。

**Comment by blueisboy** [comment]
有啊。
open = ()=> this.router.navigatByUrl('');
close = ()=> this.tabSev.close("");
active = ()=> this.router.navigatByUrl("");
