### ISSUE TITLE
完全取消菜单显示

### ISSUE THREAD

**Issue by xcorpio** [ng-alain/ng-alain#618]
我想在不同的路由里面可以有不同的菜单选项，首页可能没有菜单 类似于 gitlab
删除掉`<layout-sidebar class="aside"></layout-sidebar>` 后，会有一片空白在左侧。
<img width="277" alt="2018-08-07 7 26 51" src="https://user-images.githubusercontent.com/4575409/43773297-dd88f75a-9a77-11e8-9f1b-9f9a8567e3b5.png">

**Comment by xingkoo** [comment]
去看看路由设置,里面有个full layout,,你可以参考一下,自己写一个layout

**Comment by xcorpio** [comment]
ok. 自己想个 layout

**Comment by huweihong** [comment]
我也有类似的需求，搞定了么？ @xcorpio

**Comment by xcorpio** [comment]
@huweihong 自己写 layout ， 不同的路由 在各自的 layout 里面重置菜单, 设置该 layout 的菜单
