### ISSUE TITLE
simple-table 简易表格 在IE中 data的项目为“”的时候 IE11显示null

### ISSUE THREAD

**Issue by Dino-Wei** [ng-alain/ng-alain#619]
不知道是我是用的问题还是确实是个Bug啊

🚨 Issues 是用于BUG、Feature、进度追踪 🚨
🚨 The issue tracker is not for questions 🚨

如果有任何问题，可在以下方式获得答案：

- https://ng-alain.com/
- QQ Group：316911865
- https://segmentfault.com/t/ng-alain

**Comment by Dino-Wei** [comment]
补充：
Firefox和Chrome中均显示正常

**Comment by cipchk** [comment]
由于未提供重现示例，关闭issues。
