### ISSUE TITLE
simple-table 动态更新 columns 数据后自定义列都不显示了

### ISSUE THREAD

**Issue by shuizhongxiong** [ng-alain/ng-alain#622]
当 columns 数据里有 render 列时，编辑前一切正常，动态更改 columns 数据后，render 列就不显示了，其他列正常，请问有什么解决办法么？

组件的 load 、reload 、reset 方法都试过了，也不好使，我怀疑是 ng-template 的问题，但是想了好久也没有解决办法。

编辑前：
<img width="797" alt="wx20180808-171822 2x" src="https://user-images.githubusercontent.com/13978010/43828449-1f4540f6-9b2f-11e8-9bf6-4be27c4f2e2d.png">

编辑后：
![wx20180808-171642](https://user-images.githubusercontent.com/13978010/43828457-25241768-9b2f-11e8-8abb-9320bf4b4f4a.png)

**Comment by cipchk** [comment]
请提供一个可重现示例。

**Comment by shuizhongxiong** [comment]
示例代码是从[文档](https://ng-alain.com/components/simple-table#components-simple-table-render)上复制过来的，然后增加一个改变 columns 数据的按钮，点击按钮后，最后一列自定义列就直接不显示了，具体代码如下：

```js
import { Component } from '@angular/core';

import { SimpleTableColumn, SimpleTableChange, SimpleTableFilter } from '@delon/abc';

@Component({
  selector: 'app-home-page',
  template: `
    <button nz-button (click)="changeColumns()">改变 columns</button>

    <simple-table #st [data]="users" [ps]="3" [columns]="columns">
      <ng-template st-row="custom" let-item let-index="index">
        <span>tooltip: {{item.age}}-{{index}}</span>
      </ng-template>
    </simple-table>
    `
})
export class HomePageComponent {
  users: any[] = Array(10).fill({}).map((item: any, idx: number) => {
      return {
          id: idx + 1,
          name: `name ${idx + 1}`,
          age: Math.ceil(Math.random() * 10) + 20
      };
  });
  columns: SimpleTableColumn[] = [
      { title: '编号', index: 'id' },
      { title: '姓名', index: 'name' },
      { title: '年龄', index: 'age' },
      {
          title: '自定义',
          render: 'custom'
      }
  ];

  changeColumns() {
    this.columns = [
      { title: '编号', index: 'id' },
      { title: '姓名', index: 'name' },
      { title: '年龄', index: 'age' },
      {
          title: '自定义',
          render: 'custom'
      }
  ]
  }

}

```

**Comment by xingkoo** [comment]
你两个自定义列名称都一样?
st-row=‘custom’?????  自己的问题.

**Comment by shuizhongxiong** [comment]
@xingkoo  这个代码是从示例里面复制过来的，你有仔细看过么？第一个 st-row=‘custom’ 后面还有一个 type="title" 呢！

**Comment by xingkoo** [comment]
应该是官网代码bug.两个重复了.你没发现,age是没有被自定义的吗?

重点在于st-row, 和render指定的名称是一致的.

介绍中有写:
````
利用在 ng-template 定义 st-row="custom" 指定的名称，与列描述中的 render: 'custom' 关联；
````

````
其中若指定 type="title" 表示是对标题自定义列。附加可实现：表头分组。
````

@cipchk 如果理解错,应该是示例代码写错了.

**Comment by shuizhongxiong** [comment]
@xingkoo 
重点是我的问题不是这个，是**simple-table 动态更新 columns 数据后自定义列都不显示了**
算了，我把有歧义的地方删掉吧。

**Comment by xingkoo** [comment]
重设列配置后,尝试reset或reload一下,看看能不能起来效果.

PS:你的代码里面,重新设置列,和预置的列,信息是一样的,根本看不出来你要修改什么样的东西.
另外是否显示哪个列,可以尝试着使用 acl 来限制(文档中if只有在button中有,列里面并没有这一项,可以建议卡色添加一下.暂时你可以考滤acl来区分)

**Comment by shuizhongxiong** [comment]
@xingkoo 
首先，非常感谢您的建议，reset或reload已经尝试过了，没有用。

其次，我的代码只是一个示例，用来说明问题，具体的业务场景是：数据列很多，需要左右滑屏展示，在表格之外有一个“自定义指标”的按钮，来动态更改数据列的 **显示隐藏** 及 **其展示的顺序**，单靠 acl 无法实现动态更改其展示的顺序。

最后，关于这个问题，我的怀疑是[这里](https://github.com/cipchk/delon/blob/1a93cdb2433a0e1f300fac6107f6ecbf78318138/packages/abc/simple-table/simple-table-row.directive.ts#L26)的问题。

原因是，你在 ngOnInit 里面去初始化自定义模板，但是这个只会在组件初始化的时候执行一次，当我动态更改 columns 时，就不会再触发这里的逻辑了，也就造成了所有的自定义模板都是空的现象。

@cipchk  是否可以把这个逻辑放到一个函数里，ngOnInit 里执行一次，当动态更改 columns 时也会重新执行一次。

**Comment by xingkoo** [comment]
你的理解是对的.
对就的动态表单组件中,重新设置表单配置时,是有重置表单方法的.
相应的table组件应当也是这样. 如果在reset或reload中没有再次重置列结构,那我的理解,就是缺少这个方法的.

建议@卡色 考滤添加一下.单独的刷新结构方法可能会更加适应.

**Comment by cipchk** [comment]
这个问题很早之前的BUG，并且 已经 修复，我建议提供一个在线可重现示例，脱离这个的讨论都是没有意义的。

**Comment by shuizhongxiong** [comment]
@cipchk 您说得对，如果已经修复了，麻烦看一下我这里是哪里使用出错了么？
[https://stackblitz.com/edit/ng-alain-simple-table-render?embed=1&file=src/app/app.component.ts](https://stackblitz.com/edit/ng-alain-simple-table-render?embed=1&file=src/app/app.component.ts)

PS: 抱歉，stackblitz 这个搞了好久，到现在才回复您。

**Comment by xingkoo** [comment]
https://stackblitz.com/edit/ng-alain-simple-table-render-snseua?file=src/app/app.component.ts
我添加了reset和reload.事实上并没有效果.
简单过了一下代码, [simple-table.component.ts](https://github.com/cipchk/delon/blob/c28c965c602352c0a1289249c7da558f109c7f49/packages/abc/simple-table/simple-table.component.ts#L1030)
1030行里面有一段更新列的代码,
````
ngOnChanges(
    changes: { [P in keyof this]?: SimpleChange } & SimpleChanges,
  ): void {
  /***   就是这一句 ***/
   if (changes.columns && this._inited) this.updateColumns(); 
    if (changes.data && this._inited) this.processData();

    this.setClass();
  }
````
changes.columns  有没有可能是columns因为类型未变而不会触发事change事件???

**Comment by shuizhongxiong** [comment]
@xingkoo 
应该不是这个问题。其实这个是有执行的，除了自定义模板，你改变其他 columns 数据是可以成功的。

所以问题还是出在了自定义模板这里，你看[这里](https://github.com/cipchk/delon/blob/c28c965c602352c0a1289249c7da558f109c7f49/packages/abc/simple-table/simple-table-row.directive.ts#L25)的代码就是用来往 columns 添加自定义模板内容的，但是放在 ngOnInit 里面，就只有组件初始化的时候才会执行一次，当你动态更新数据时就不会再触发这里，所以就造成了自定义数据为空，其他的都能成功的现象。
