### ISSUE TITLE
https://ng-alain.com/auth/style 打开报错！ 请问有oauth2 认证的例子吗？ 

### ISSUE THREAD

**Issue by ccwxl** [ng-alain/ng-alain#623]
🚨 Issues 是用于BUG、Feature、进度追踪 🚨
🚨 The issue tracker is not for questions 🚨

如果有任何问题，可在以下方式获得答案：

- https://ng-alain.com/
- QQ Group：316911865
- https://segmentfault.com/t/ng-alain

**Comment by cipchk** [comment]
请从 https://ng-alain.com/auth/ 获取信息。
