### ISSUE TITLE
menuService.resume() 重设菜单后二级菜单不能自动展开

### ISSUE THREAD

**Issue by xingkoo** [ng-alain/ng-alain#624]
- ng-alain version: 1.3.1
- Angular version: X.Y.Z

## 【必填项】重现链接，Reproduction link

![qq20180809-035725](https://user-images.githubusercontent.com/2936579/43861480-8d55ba6c-9b89-11e8-95bf-77f441d7dea8.gif)

## 重现步骤，Steps to reproduce

menuService.resume() 写在子路由守卫中.

使用菜单服务,重置菜单后,不能自动展开子菜单,如上面动图(图片有点大,加载比较慢)

**Comment by cipchk** [comment]
请提供可重现示例。

**Comment by xingkoo** [comment]
抱歉,以为动画能体现出来了.
稍后补充重现示例.

**Comment by xingkoo** [comment]
抱歉,这两天stackblitz不稳定,刚做好示例

[https://stackblitz.com/edit/ng-alain-setup-8hhtbe?file=src%2Fapp%2Fapp.component.html](https://stackblitz.com/edit/ng-alain-setup-8hhtbe?file=src%2Fapp%2Fapp.component.html)

**Comment by cipchk** [comment]
建议调用 `openedByUrl` 解决这种情况，另一个有效[示例](https://stackblitz.com/edit/ng-alain-setup-s9ak7u?file=src%2Fapp%2Fapp.component.ts)。

**Comment by xingkoo** [comment]
明白了.重置菜单数据后,手工打开一下当前页面,即可实现重新展开菜单的效果.谢谢
