### ISSUE TITLE
使用angular cli创建组件时，组件的样式格式是css不是less，需要更改angular.json文件

### ISSUE THREAD

**Issue by wenyuantc** [ng-alain/ng-alain#625]
使用angular cli创建组件时，组件的样式格式是css不是less

请在angular.json下的 
projects
ng-alain
添加
 "schematics": {
        "@schematics/angular:component": {
          "styleext": "less"
        }
}

**Comment by cipchk** [comment]
干得漂亮，但大部分都知道。
