### ISSUE TITLE
Modal 关闭后会出现 ngOriginalError 异常

### ISSUE THREAD

**Issue by ddpmz** [ng-alain/ng-alain#626]
- ng-alain version: 1.3.1
- Angular version: 6.1.0

## 【必填项】重现链接，Reproduction link
https://cipchk.github.io/ng-alain/#/extras/poi
我发现这个例子也会报错
zone.js:192 Uncaught TypeError: Cannot read property 'ngOriginalError' of undefined

<img width="1325" alt="wx20180809-143643 2x" src="https://user-images.githubusercontent.com/3666795/43882268-ac189412-9be1-11e8-997a-27687ae52e6e.png">

 this.modal.destroy();

**Comment by cipchk** [comment]
已知情况，但是目前不清楚问题所在，暂时也无法利用 Modal 进行重现，有进一步进展，我会修复它。

唯一肯定的是不影响使用。

**Comment by ddpmz** [comment]
好的，谢谢！！
