### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by a952454** [ng-alain/ng-alain#628]
- ng-alain version: 1.3.0
- Angular version: 6.1.0
- ng-zorro-antd version: 1.3.0
![tim 20180810091907](https://user-images.githubusercontent.com/34675560/43933862-af0d3842-9c7e-11e8-9f54-f3e13dc482c6.png)
![tim 20180810091921](https://user-images.githubusercontent.com/34675560/43933863-b044a678-9c7e-11e8-8d6f-9a9164c2f584.png)

## 重现步骤，Steps to reproduce

正常的编译报错，代码没有问题

**Comment by xingkoo** [comment]
执行  ````./node_modules/.bin/ngc```` 自行检查一下

**Comment by a952454** [comment]
![image](https://user-images.githubusercontent.com/34675560/44009723-576265e0-9ee0-11e8-9fe6-0522a51c15aa.png)

**Comment by a952454** [comment]
![image](https://user-images.githubusercontent.com/34675560/44069276-8e08c960-9fb0-11e8-82b9-b07bcfe948fe.png)
@xingkoo 这个是什么原因呢？
ng-alain version: 1.3.0
Angular version: 6.1.0
ng-zorro-antd version: 1.3.0
"@angular/cli": "^6.1.3",

**Comment by a952454** [comment]
我看了更新日志，不就是这么写的吗？

**Comment by xingkoo** [comment]
在 tsmc目录下运行node_modules\.bin\ngc

**Comment by a952454** [comment]
这是更新日志：https://github.com/cipchk/ng-alain/commit/67c771
![image](https://user-images.githubusercontent.com/34675560/44084172-9b362780-9fe8-11e8-9eee-dc2602f2155f.png)
我自己的代码：
![image](https://user-images.githubusercontent.com/34675560/44084199-b0d3255c-9fe8-11e8-9acf-ca2cee74c633.png)
摸不着头脑，不知道哪里有问题
@xingkoo

**Comment by xingkoo** [comment]
和更新没有关系.
你先正常运行ngc检查一下语法问题再说别的.

**Comment by a952454** [comment]
我没有说更新有问题，我的确是按照更新日志，来写代码的，我完全是按照示例来引入less文件，但是执行ngc检查的时候，就只有这一条错误了
![image](https://user-images.githubusercontent.com/34675560/44128936-497c8eb2-a078-11e8-9bd4-7ec77e2f10e4.png)
@xingkoo

**Comment by xingkoo** [comment]
解决了吧?  中间的波浪号  ~  你那个在高处,好像不是一个符号.
一般碰到编译问题,ngc基本都可以解决.

> 在 2018年8月15日，上午10:45，a952454 <notifications@github.com> 写道：
> 
> 我没有说更新有问题，我的确是按照更新日志，来写代码的，我完全是按照示例来引入less文件，但是执行ngc检查的时候，就只有这一条错误了

**Comment by a952454** [comment]
最后问题找到了，因为这个项目时我中途接手
之前 SFComponent 是这样引入的， import { SFComponent } from '@delon/form/src/src/sf.component';
更新后，SFComponent变成了这样引入 import { SFComponent } from '@delon/form';
就因为这个问题，一直报错但是又不知道报错在哪，‘
这个问题 ngc 检查不出来

**Comment by a952454** [comment]
@xingkoo
