### ISSUE TITLE
编译时报WARNING

### ISSUE THREAD

**Issue by zdxxxxxx** [ng-alain/ng-alain#630]
- ng-alain version: 1.3.0
- Angular version: 6.0.4
- ng-zorro-antd version: 1.3.0

![image](https://user-images.githubusercontent.com/16288673/43953199-cebf6218-9cca-11e8-9e82-2b43a557ef2f.png)

**Comment by cipchk** [comment]
You can trying:

- delete `node_modules` `package-lock.json` `yarn.lock`
- run `npm i`
