### ISSUE TITLE
控制器click绑定。（查询表格）我如何才能把下图中的click事件绑定到自己的方法，绑定后出现三图所示错误。还有此click事件可以绑定到routerlink吗？先谢谢解答！

### ISSUE THREAD

**Issue by Sunshine-L** [ng-alain/ng-alain#633]
![default](https://user-images.githubusercontent.com/41154870/44003465-93ebdf10-9e85-11e8-93f2-ed988ad0e542.PNG)

![2](https://user-images.githubusercontent.com/41154870/44003472-a585b656-9e85-11e8-8a96-32c616afff99.PNG)
![image](https://user-images.githubusercontent.com/41154870/44003473-a7d9c1cc-9e85-11e8-9c3f-2da01530accf.png)

**Comment by xingkoo** [comment]
这问题在这里问会被骂.自行关闭吧.

click: (item: any)=>{ console.log(item); }
