### ISSUE TITLE
SimpleTable  Columns 动态加载

### ISSUE THREAD

**Issue by NG-GGBond** [ng-alain/ng-alain#635]
- ng-alain version: 1.3.1
- Angular version: 6.1.2

## 【必填项】重现链接，Reproduction link

https://stackblitz.com/edit/ng-alain-simple-table-render-3aak1g?embed=1&file=src/app/app.component.ts

## 重现步骤，Steps to reproduce
如果SimpleTable的Columns是动态获取的
SimpleTable的Data使用URL方式
如果Columns获取速度慢于Simpletable获取data数据时，无法显示数据。
在ng-alain version: 1.0.5（含）之前是没有这种问题的，再往上哪个版本会有这个问题不知，但最新版会这样，不知是BUG，还是设计就是如此，获取在动态获取st.reload、st.reset，可以解决，但等于多请求了一次。

**Comment by xingkoo** [comment]
通常操作都是同步操作配置列选项的.如果你需要动态加载列选项,请在列选项加载完后,再使用表格.可以外包 nz-spin 或考 使用ngIf来保证列配置项加载完成后才会渲染表格.
当前版本不支持的话,以前的版本肯定也不会支持.
当然st component也可以预置columns使用异步方式加载,在特定场景下还是有用的.
但是不见得卡色会做这么个配置.你可以试着提一个issue看能不能添加.

**Comment by cipchk** [comment]
@0o0o0o0o0o0o0 这种情况是存在的，数据的变化才会更新数据、列描述的变化才会更新列描述。我想这会更合理一点，否则可能会导致多次数据的请求，相比较而言成本会更低一些。

我的建议是获取列描述以后再赋值数据 `url`。
