### ISSUE TITLE
SimpleTable后端分页问题

### ISSUE THREAD

**Issue by Silence-wzy** [ng-alain/ng-alain#639]
本人在使用SimpleTable过程中发现：data使用url试图采用后端分页时，分页数竟然是根据外部提供的total决定的，这显然不合理。
难道不该是由请求时后台返回总页数或总数量决定的吗？

**Comment by cipchk** [comment]
我并不明白我的意思。

**Comment by DarkGin** [comment]
这个total就是你后台返回的total啊，如果你后台返回的数据格式不同,可以通过修改[resReName]=“{total： 'result.totalCount' }”，result.totalCount是你后台返回格式中的总数量

**Comment by KungFuChen96** [comment]
...

**Comment by cipchk** [comment]
关闭issues，有更一步细节请重新提交新issues.
