### ISSUE TITLE
打开Modal对话框后，点击浏览器前进或者后退按钮，Modal框未关闭

### ISSUE THREAD

**Issue by mysanyue** [ng-alain/ng-alain#646]
1、使用reuse-tab路由复用标签后
2、打开Modal对话框后，点击浏览器后退按钮，Modal框未关闭
期望：点击浏览器后退或者前进按钮，modal框关闭

**Comment by zl63** [comment]
抽屉也一样关闭不了，这个要怎么解决？

**Comment by cipchk** [comment]
@zl63 试一下 https://github.com/ng-alain/ng-alain/blob/master/src/app/app.component.ts#L27 这行代码，但是对于 Drawer 部分，受限于 [#2965](https://github.com/NG-ZORRO/ng-zorro-antd/issues/2965)，只能在哪个页打开，在哪个页监听了，目前 没有好的办法。
