### ISSUE TITLE
reuse-tab组件标签错乱

### ISSUE THREAD

**Issue by zhouyingqiu** [ng-alain/ng-alain#647]
- ng-alain version: ^0.8.0
- Angular version: ^5.2.10

## 重现链接
https://cipchk.github.io/ng-alain/#/dashboard/v1

## 重现步骤
1. 点开tab页数达到允许最多复用多少个页面设置值（默认值10）
![image](https://user-images.githubusercontent.com/18085481/44527588-e0108480-a719-11e8-8c4f-d94d473b897b.png)
2. 点击除最后一个标签外任意一个标签，tab的active样式仍然在最后一个标签上，但是页面内容是点击的组件
![image](https://user-images.githubusercontent.com/18085481/44527697-2e258800-a71a-11e8-8429-e29e9f81fb26.png)

## 补充
我用的版本跟官网版本不同，不过表现是一样的，官网上可以重现，另外还有一个问题是打开的复用页面可能会大于设置的最多可复用页面

**Comment by cipchk** [comment]
我无法重现，麻烦提供一下可重现示例。

**Comment by zhouyingqiu** [comment]
@cipchk 在官网demo上可以重现啊，点开十个页签，然后点第九个，路由地址和内容区是显示的第九个页签的地址和内容，但是页签导航上显示的是第十个是活动页

**Comment by blueisboy** [comment]
![txkf0 _vi59 q q en gno2](https://user-images.githubusercontent.com/30822684/44699252-f28e1380-aab5-11e8-9974-da64534b785e.png)

在离开URL后转到另一个URL，路由复用服务会依次调用2次存储方法。
第一次逻辑无误（存储第Max个路由对象），但是第2次是存储即将跳转的地址，此时第一句判断会生效（10 >10），应该将if判断移动到push后面。同时 idx应该顺序-1，不然会打开即将跳转的URL后面那个选项卡。

@cipchk

**Comment by zhouyingqiu** [comment]
![image](https://user-images.githubusercontent.com/18085481/44712023-66deac00-aae2-11e8-8238-be6f6d3c3efa.png)

不知道是不是版本原因，我的按照作者修复内容修改之后还是会有问题，然后改了这里好像可以，公司项目暂时没办法升级,作者会修复ng-alain : ^0.8.0版本的代码吗？

@cipchk

**Comment by cipchk** [comment]
不会再维护 `0.8.x` 版本。你可以复制 0.8 分支的代码，在本地项目中使用。

我会继续核实这个问题。
