### ISSUE TITLE
仪表盘 带Slider 数据滑动条的折线图问题

### ISSUE THREAD

**Issue by Sunshine-L** [ng-alain/ng-alain#649]
请问这是怎么回事呢？进的是官网例子看的
 1、【仪表盘】的折线图打开时正常
![image](https://user-images.githubusercontent.com/41154870/44573867-654b7600-a7ba-11e8-8103-3ce047a97ed4.png)
 当点击“检查”后，滑动条不见了，控制面板报错如下
 
![image](https://user-images.githubusercontent.com/41154870/44574082-e9056280-a7ba-11e8-9c9a-5f1273f955f9.png)

2、【分析页】也有这样一个图，可是为什么这里的则要手动将滑动条拉宽后图形才会出来呢？
![image](https://user-images.githubusercontent.com/41154870/44574135-27028680-a7bb-11e8-94f9-64af22e7251d.png)
![image](https://user-images.githubusercontent.com/41154870/44574384-df302f00-a7bb-11e8-99af-0f1c8a34915f.png)

望解答，谢谢！！

**Comment by cipchk** [comment]
抱歉，我无法重现。麻烦提供更详细的重现步骤。

**Comment by Sunshine-L** [comment]
https://cipchk.github.io/ng-alain/#/dashboard/analysis
就是在这页
