### ISSUE TITLE
bug report: simple-table iif repeat execute

### ISSUE THREAD

**Issue by xingkoo** [ng-alain/ng-alain#650]
- ng-alain version: 1.3.0
- Angular version: X.Y.Z

## 【必填项】重现链接，Reproduction link

https://stackblitz.com/edit/ng-alain-setup-9khtmk?file=src/app/app.component.ts

## 重现步骤，Steps to reproduce
表格使用iif后,不停循环执行.参见演示.
3条记录,应该执行3次iif的,结果一直在循环调用.

**Comment by cipchk** [comment]
建议了解Angular变化检测。
