### ISSUE TITLE
safari下输入法导致重复键入问题

### ISSUE THREAD

**Issue by xingkoo** [ng-alain/ng-alain#651]
我不能确认是不是BUG,在这个地方问题吧.

在官网的动态表单验证处(下面链接)录的屏, 使用的是 **搜狗五笔** 以及 **系统自带的拼音或其他输入法**
在**safari**下会出现这种问题, **chrome**下没有问题.
https://ng-alain.com/form-pages/validator

![qq20180826-085756](https://user-images.githubusercontent.com/2936579/44623881-2b8b8400-a90e-11e8-9a7c-7c1b58bad5c1.gif)

**Comment by cipchk** [comment]
完全没明白，请描述一个能让人类可重现的活。

**Comment by xingkoo** [comment]
输入汉字时,会把拼音写入input.
比如输入"我们"  women   会出现如下结果:   ````wwwowo我mmmememenmen门````
或者截图中所示,使用五笔时    有(e)问题(ukjg)  三个字是使用括号中的字母拼出来的,结果这些字母也被录入在input中了.而非仅显示汉字

**Comment by cipchk** [comment]
能否排除你电脑配置问题呢？ @xingkoo

**Comment by xingkoo** [comment]
之所以在这儿提这个问题,是因为在safari下,正常的表单没有问题

> 登陆页使用正常的ng表单,可以正常键入
> 其他使用ng的站点,也可以正常键入
> 但凡动态表单中的input,就会出现这个问题

所以我觉得应该是动态表单中的检测机制导致的问题,
但只有我自己一台电脑,暂时不能确认是这个问题
稍等几天,我更新到线上后,用其他电脑试过后再反馈一下结果

**Comment by xingkoo** [comment]
@cipchk 我已经在其他的mac上,使用safari测试,SF组件所产生的表单,确认存在这样的问题.

**Comment by cipchk** [comment]
我不确定哪里引起的，这个问题暂时无法处理。更进一步细节，可能需要大家来帮忙。

**Comment by xingkoo** [comment]
我使用ngx-color组件封装为SF的一个组件,该组件要求有一个**默认颜色值**.
当未设置颜色值时,ngx-color会报错.
而在封装为sf的组件并使用时,该错误重复出现.(见下图控制台右侧错误数字)

> 以前提过一个table组件的ISSUE[https://github.com/cipchk/ng-alain/issues/650](https://github.com/cipchk/ng-alain/issues/650) 也是类似的问题

所以我觉得这个问题是SF的刷新机制造成的`未输出完整中文字时,因组件刷新导致当前的拼音被写入input中`

![image](https://user-images.githubusercontent.com/2936579/44952274-78db9880-aeae-11e8-94b1-7217d16a5e72.png)

**Comment by niuba** [comment]
我也遇到了同样的问题。

**Comment by xingkoo** [comment]
你用的是哪个版本的?

**Comment by apphost** [comment]
1.x，android下也有该问题
