### ISSUE TITLE
可以做多级菜单吗

### ISSUE THREAD

**Issue by zhengyanghuaer** [ng-alain/ng-alain#653]
![image](https://user-images.githubusercontent.com/35128870/44646351-3842d180-aa0d-11e8-8edb-d6367fef0887.png)

**Comment by cipchk** [comment]
抱歉，不明白你的意思。

**Comment by QGDW** [comment]
菜单是无限级别的，大兄弟。

**Comment by cipchk** [comment]
not yet! 未来也不会支持所谓的无限级。
