### ISSUE TITLE
联级选择  选中非叶子节点

### ISSUE THREAD

**Issue by MIAOMIAOUP** [ng-alain/ng-alain#654]
现在Cascader级联选择 非叶子节点无法选中
我想实现这样的效果 参考
https://github.com/cipchk/ng-alain/issues/58
Cascader中是否有这样的开关，允许非叶子节点选中并且在输入框里产生数值

**Comment by cipchk** [comment]
ng-alain 不对 ng-zorro-antd 原始组件进一步改造，有关这类问题，请到 ng-zorro-antd 官网了解API文档以及对应的 issues 列表是否已经有相应问题已经解决的。
