### ISSUE TITLE
内置拦截器_allow_anonymous不起作用

### ISSUE THREAD

**Issue by wyshmily** [ng-alain/ng-alain#655]
```
 getFactoryList() {
    return this.httpClient.get<Factory[]>(`${API_BASE}/factory?_allow_anonymous=true`);
  }
```
在url里增加_allow_anonymous=true，拦截器还是报错（401）。不知道是否使用方法不对。

但是如果像下面这样配置ignores，则能正确调用，可见的确是拦截器报的错：
```
export function delonAuthConfig(): DelonAuthConfig {
  return Object.assign(new DelonAuthConfig(), <DelonAuthConfig>{
    login_url: '/passport/login',
    allow_anonymous_key: '_allow_anonymous',
    ignores: [/\/login/, /assets\//, /passport\//, /factory/],
  });
}
```

求问怎么正确使用_allow_anonymous

**Comment by cipchk** [comment]
建议优先升级一下 `@delon/*` 类库版本。

**Comment by askie** [comment]
```
"@delon/abc": "^2.0.1",
    "@delon/acl": "^2.0.1",
    "@delon/auth": "^2.0.1",
    "@delon/cache": "^2.0.1",
    "@delon/chart": "^2.0.1",
    "@delon/form": "^2.0.1",
    "@delon/mock": "^2.0.1",
    "@delon/theme": "^2.0.1",
    "@delon/util": "^2.0.1",
```
遇到了同样的问题，不生效。
设置：
```
allow_anonymous_key: '_allow_anonymous',
```
请求
http://framework.com/api2/rest/?_allow_anonymous=true
返回401

**Comment by Loongle** [comment]
@askie 兄弟，你的问题解决了吗

**Comment by cipchk** [comment]
旧版本的确存在远程URL不生效的问题，建议在 `params` 中指定：

```ts
        http
          .get('/user', { responseType: 'text', params: { _allow_anonymous: '' } })
          .subscribe(done);
```

**Comment by Loongle** [comment]
@cipchk 2.0.1版本，是目前RTM的最新版本了吧，请问在什么版本修复这个问题？

**Comment by askie** [comment]
@Loongle 不要在http请求中使用完整的url路径，否则就会出现不生效的情况。
只能使用相对路径。例如：  /api/a?_allow_anonymous=true

使用： https://www.abc.com/api/a?_allow_anonymous=true 就不会生效。

**Comment by Loongle** [comment]
@askie 这个没办法的，因为service 和 ui 不在同一个域下。所以目前只能用绝对路径

**Comment by askie** [comment]
@Loongle  可以的。多域名需要在 default.interceptor.ts 里面进行不同的追加域名即可：
![image](https://user-images.githubusercontent.com/1140973/52531859-13da7780-2d57-11e9-8173-58c57a787894.png)
