### ISSUE TITLE
官网总是显示错误的menu

### ISSUE THREAD

**Issue by tworry** [ng-alain/ng-alain#656]
- ng-alain version: X.Y.Z
- Angular version: X.Y.Z

## 重现步骤，Steps to reproduce

我打开官网的时候，上面的菜单总是显示
首页，文档，组件，表单（？），工具
然后要手动重新刷好几遍，才能显示正常的 Delon库。

然后过一天再打开，又是这样。

**Comment by cipchk** [comment]
应该是 Service workers 引起的，关掉它。

png:

![tim 20180829143228](https://user-images.githubusercontent.com/2987467/44769802-5f79da00-ab98-11e8-9c7a-c14677fd3a3c.png)
