### ISSUE TITLE
关于@delon/abc导入/出功能的XlsxService/加载cnd的问题

### ISSUE THREAD

**Issue by Diry2017** [ng-alain/ng-alain#657]
在使用delon导入导出功能的时候会发现这个功能会向外部加载cnd的一个js文件
可能有些同学和我一样不需要外部加载的cnd
研究后我发现了这个问题的一个非常粗鄙的解决方法
XlsxService加载js的链接是写在XlsxConfig里面的,但是我并不会修改这个默认注入的config
所以想出了这个粗鄙的方法在构造函数初次注入的时候手动设置config
```
 constructor(private xlsx: XlsxService) {
    (<any>xlsx).config = {
      url: "assets/js/xlxs.js",
      modules: [],
    }
  }
```
很显然我这种做法并不正确,但是可以解决当下燃眉之急
如果作者/或者各位大佬有时间的话可以帮小弟看看
告诉我正确的解决方案

**Comment by cipchk** [comment]
```ts
AdXlsxModule.forRoot({
  url: 'assets/js/xlxs.js'
})
```

**Comment by Diry2017** [comment]
谢谢大佬

**Comment by Caims01** [comment]
@cipchk 为什么没有AdXlsxModule，只有XlsxModule，但是XlsxModule.forRoot却是无参的
