### ISSUE TITLE
关于如何控制动态表单栅格布局的问题。

### ISSUE THREAD

**Issue by DrZhong** [ng-alain/ng-alain#660]
有一种场景：动态表单大多数情况下是一行显示两个表单元素。但是中间我想穿插着一些表单需要单独显示一行，这种业务场景我在ng-alain中不知道如何实现。
比如下图中的 【角色】这个表单项我想让它单独占一行，请问如何实现呢。
![p3](https://user-images.githubusercontent.com/8085571/44942164-6abe4700-adde-11e8-9414-965f46c98265.png)
![p4](https://user-images.githubusercontent.com/8085571/44942165-6abe4700-adde-11e8-82cd-b002219fcdbf.png)

感谢.

**Comment by cipchk** [comment]
```json
roleNames: {
  title: 'role',
  ui: {
    grid: {}
  }
}
```
