### ISSUE TITLE
如何增加类似@shared的路径别名？

### ISSUE THREAD

**Issue by gloriawish** [ng-alain/ng-alain#661]
🚨 Issues 是用于BUG、Feature、进度追踪 🚨
🚨 The issue tracker is not for questions 🚨

如果有任何问题，可在以下方式获得答案：

- https://ng-alain.com/
- QQ Group：316911865
- https://segmentfault.com/t/ng-alain

**Comment by cipchk** [comment]
You can search for `"@shared/*"` keywords in your project.

**Comment by gloriawish** [comment]
OK，已经解决，谢谢
