### ISSUE TITLE
Sidebar or Menu does not list submenu in Collapsed in Tablet or Mobile

### ISSUE THREAD

**Issue by lkhuoch** [ng-alain/ng-alain#664]
Hello,
I have problem with list submenu in collapsed in Table or Mobile, how to solve it?
Thanks,

**Comment by cipchk** [comment]
Pls provide any relevant screenshot to illustrate the issues.

**Comment by lkhuoch** [comment]
![ng-alain](https://user-images.githubusercontent.com/32889942/45015814-09e87600-b04d-11e8-8350-c5edd8c0d918.png)
Hello, you can check it on the image or you check Ipad mode view in google chrome on:
https://cipchk.github.io/ng-alain/#/dashboard/v1

thanks,

**Comment by cipchk** [comment]
Need to switch expanded aside via  ![tim 20180904154126](https://user-images.githubusercontent.com/2987467/45017014-02c76500-b059-11e8-81dd-435a2aff6cb6.png).

i will enhance of user experience in the part, thanks report.

**Comment by lkhuoch** [comment]
Ok, thank so much for helping.
