### ISSUE TITLE
动态表单数组布局bug

### ISSUE THREAD

**Issue by Piaoing** [ng-alain/ng-alain#669]
动态表单数组ui加入grid: { arraySpan: n  }导致前面输入框全都无法输入.如下
"$material":{
      grid: { arraySpan: 24 },
      spanLabel:2,
      spanControl:22,
      addType:"primary",
       "$items":{
       grid: { span: 8 },
       }
    }

**Comment by cipchk** [comment]
请提供可重现在线示例。
