### ISSUE TITLE
自己写的http请求怎么还会有这个auth拦截。

### ISSUE THREAD

**Issue by zyu** [ng-alain/ng-alain#670]
自己在注册页面写了一个注册http.post 就提示下面的错误

HttpErrorResponse {headers: HttpHeaders, status: 401, statusText: "From Simple Intercept --> http://ng-alain.com/docs/auth", url: null, ok: false, …}
error
:
null
headers
:
HttpHeaders {normalizedNames: Map(0), lazyUpdate: null, headers: Map(0)}
message
:
"Http failure response for (unknown url): 401 From Simple Intercept --> http://ng-alain.com/docs/auth"
name
:
"HttpErrorResponse"
ok
:
false
status
:
401
statusText
:
"From Simple Intercept --> http://ng-alain.com/docs/auth"
url
:
null
__proto__
:
HttpResponseBase

**Comment by cipchk** [comment]
建议优先阅读 ng-alain 入门系列视频：
youtube:https://www.youtube.com/watch?v=lPnNKPuULVw&list=PLhWkvn5F8uyJRimbVZ944unzRrHeujngw
腾讯视频：http://v.qq.com/vplus/2c1dd5c6db4feeeea25e9827b38c171e/foldervideos/870001501oy1ijf
b站：https://space.bilibili.com/12207877/#/channel/detail?cid=50229
