### ISSUE TITLE
ngx-ueditor 上传图片怎么提交额外的参数

### ISSUE THREAD

**Issue by guccihuiyuan** [ng-alain/ng-alain#671]
当使用ngx-ueditor上传图片的时候，希望能带一些额外的参数发送到服务器，请问怎么设置，又没有示例代码呢？

**Comment by cipchk** [comment]
https://www.baidu.com/s?wd=ueditor+%E4%B8%8A%E4%BC%A0%E5%8F%82%E6%95%B0
