### ISSUE TITLE
关于柱状图底部月份显示问题

### ISSUE THREAD

**Issue by zhaopeiym** [ng-alain/ng-alain#672]
## 重现链接
https://ng-alain.com/components/charts

## 重现步骤
1、刷新进入页面查看柱状图，底部没有月份显示
2、当你改变浏览器窗体大小是会出现月份显示（会自动重绘）
3、柱状图可否提供一个显示数值单位的地方？

![qq 20180909114237](https://user-images.githubusercontent.com/5820324/45260885-92885d00-b425-11e8-856c-f13b6163e8ef.png)

**Comment by cipchk** [comment]
x 轴会在小屏幕下自动隐藏。

[2.x](https://ng-alain.com/chart/bar/en) 对所有 g2 组件进行重构，若图表不符合需求，建议参考自定义部分。
