### ISSUE TITLE
Tab标签页   reuse-tab 路由复用标签

### ISSUE THREAD

**Issue by visugar** [ng-alain/ng-alain#678]
想问下1.x版本用的是Tab标签页 ，现再切到2.x版本之后还是希望使用tab标签页的形式，这个  reuse-tab 路由复用标签现在要怎么配置？

**Comment by cipchk** [comment]
https://ng-alain.com/components/reuse-tab/en#%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8%EF%BC%9F
