### ISSUE TITLE
nz-list display not work in Internet Explorer

### ISSUE THREAD

**Issue by icycore** [ng-alain/ng-alain#68]
## Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Repro steps.

Hi,
   Your zorro-extend package need more test under IE. THX~

![bug](https://user-images.githubusercontent.com/1421701/33228193-23cdf216-d1f0-11e7-961c-62fbe3adf424.jpg)

**Comment by cipchk** [comment]
a ant-design [demo](https://ant.design/components/list-cn/) since it's not an issue width ng-zorro-antd-extr.
