### ISSUE TITLE
Adding icon to menu item in app-data.json file

### ISSUE THREAD

**Issue by mortifactor** [ng-alain/ng-alain#687]
I had menu part like this:
```
{
  "app": {
    "name": "АРМ CITYBUS",
    "description": "АРМ CITYBUS"
  },
  "user": {
    "name": "Admin",
    "avatar": "./assets/tmp/img/avatar.jpg",
    "email": "cipchk@qq.com"
  },
  "menu": [
    {
      "group": true,
      "hideInBreadcrumb": true,
      "children": [
        {
          "text": " References",
          "icon": "fal fa-folders",
          "children": [
            {
              "icon": "fal fa-folders",
              "text": "Cities",
              "link": "/cities"
            }
          ]
        }
      ]
    }
  ]
}
```

and the icon in children node not working:

![image](https://user-images.githubusercontent.com/1426349/45809592-bf285880-bcf2-11e8-9b34-2a74a9b96813.png)

or in example template:

![image](https://user-images.githubusercontent.com/1426349/45808060-0f052080-bcef-11e8-8600-11372f2f10c7.png)

how can I set this?

**Comment by cipchk** [comment]
Icon just only supported first level (not group name).

**Comment by mortifactor** [comment]
Ok. So could you please add ability to set icon to child2 in delon\packages\abc\sidebar-nav\sidebar-nav.component.html?

**Comment by cipchk** [comment]
sorry, the current version will not be support.

**Comment by segux** [comment]
Will be added in future versions?
