### ISSUE TITLE
st 组件在模态框里面的 checkbox全选有异常

### ISSUE THREAD

**Issue by navisoftware** [ng-alain/ng-alain#689]
- ng-alain version:^2.0.0-beta.1
- Angular version: ^6.1.0

## 【必填项】重现链接，Reproduction link

无环境模拟,提供的Stackblitz 是1.4的
## 重现步骤，Steps to reproduce
在A组件中有         
`<st mode="edit" [data]="url" [size]="'small'" [columns]="columns"></st>`
`columns: STColumn[] = [
    { title: '编号', index: 'id',type:'checkbox' },
    { title: '头像', type: 'img', width: '100px', index: 'avatar' },
    { title: '邮箱', index: 'owner' },
    { title: '电话', index: 'callNo' },
    { title: '注册时间', type: 'date', index: 'updatedAt' },
  ];`
B组件用模态的方式打开A组件内容.
` this.modal.
        createStatic(FormEditComponent, { record: { id: item.id }, formid: this.report.form }, {
          size: 'xl',
        });`

此时的A组件里面的全选有问题:
1.要点击全选/取消,每次都需要两次点击才能生效.
2.点击全选后,在表格任意地方点击一次,则全选会被取消.

![c4d3854d-790d-4bcb-a754-a16c58eed52a](https://user-images.githubusercontent.com/15653415/45871075-10058300-bdbf-11e8-916b-92e74f1a6d8e.png)

**Comment by navisoftware** [comment]
补充一下:经测试 nz-table 无此问题

**Comment by cipchk** [comment]
关掉issues，若有进一步细节请提供相应的重现示例。
