### ISSUE TITLE
SFSchema自动生成form之后，在重置日期列时会提示格式不正确

### ISSUE THREAD

**Issue by xiaotupansy** [ng-alain/ng-alain#690]
- ng-alain version: 1.4.4
- Angular version: 6.0.8

## 【必填项】重现链接，Reproduction link
![image](https://user-images.githubusercontent.com/10205937/45927771-b477f880-bf6a-11e8-8db7-1df766e115e9.png)

## 重现步骤，Steps to reproduce

1.设置一列日期列
2.给这列设置一个默认值，比如当前时间
3.点击重置按钮

**Comment by xiaotupansy** [comment]
`    ngOnInit(): void {
        this.domainType = this.ui['domainType'];
        this.displayColumns = this.ui['displayColumns'];
        this.originalId = this['schema']['default'];
        this.originalObj = this.ui['reference'];
        this.setValue(this.originalId);
    }

    reset() {
        this.obj = deepClone(this.originalObj);
// 注意此处我没有调用this.setValue(this.originalId);方法
    }`

此错误可能与ControlWidget的reset方法有关系。

1.reset方法在nginit方法之后还会被调用一次，这个逻辑有点奇怪
2.如果在reset方法里面调用了setValue，那么对这个字段来说，requeired属性工作就不正确，出现一直报错但是form还是valid并可以提交的情形

**Comment by cipchk** [comment]
关掉issues，若有进一步细节请提供相应的重现示例。
