### ISSUE TITLE
@icon-url 路径问题

### ISSUE THREAD

**Issue by starpeng** [ng-alain/ng-alain#692]
- ng-alain version: 2.0.0-beta.2
- Angular version: 6.1.8

iconfont放置到./assets/iconfont/目录下
[按文档](https://ng-alain.com/docs/faq/zh#%E5%A6%82%E4%BD%95%E6%9C%AC%E5%9C%B0%E9%83%A8%E7%BD%B2-antd-%E5%9B%BE%E6%A0%87%EF%BC%9F)
设定@icon-url 本地路径@icon-url: "./assets/iconfont/iconfont"，实际引入到ng-zorro-antd后编译的路径是以./node_modules/ng-zorro-antd/style/core/iconfont.less:8:11 这个文件为base路径的，所以会找不到文件。

暂时解决方法：
@icon-url: "../../../../src/assets/iconfont/iconfont";

**Comment by cipchk** [comment]
尝试使用绝对路径： `/assets/iconfont`

**Comment by starpeng** [comment]
绝对路径可以
