### ISSUE TITLE
没有发送ajax请求？

### ISSUE THREAD

**Issue by martin-yin** [ng-alain/ng-alain#693]
![image](https://user-images.githubusercontent.com/19162008/46023513-5f2d1a00-c117-11e8-8420-544e9110d38b.png)

![image](https://user-images.githubusercontent.com/19162008/46023616-91d71280-c117-11e8-8a7e-ce553b6b0ef1.png)
点击登录按钮的时候network 没有发送ajax 也没有报错。这是什么情况。

**Comment by martin-yin** [comment]
![image](https://user-images.githubusercontent.com/19162008/46023704-c054ed80-c117-11e8-874f-00930c287a66.png)
default.interceptor 打印出来的东西在这里。

**Comment by cipchk** [comment]
Pls refer to https://ng-alain.com/mock/getting-started/en
