### ISSUE TITLE
路由守卫做成全局的吧？

### ISSUE THREAD

**Issue by MicroLord** [ng-alain/ng-alain#7]
看了这个demo，非常值得学习，作为后台，涉及权限这块的时候，因为你这边的菜单都是初始化循环读取menu.ts的，根据用户的权限动态展示菜单比较麻烦，可否把路由卫士做成全局实例？其他的token验证和权限验证我们只需要改为自己的业务代码即可！

我目前是在menu.ts里面加了一个role来限制拥有这个权限的才能够显示这个菜单，然后在html界面多加了一个条件，总觉得不妥，菜单过多时，加载首页很慢
menu.ts:
![menu](https://user-images.githubusercontent.com/10664096/30011216-48a050de-9168-11e7-9b6c-26e50080b7c3.png)
sidebar.comment.html:
![auth](https://user-images.githubusercontent.com/10664096/30011260-757c7722-9168-11e7-8bb3-4d966fd523c1.png)

**Comment by cipchk** [comment]
是有这个想法，但是每个人的权限体系都不一样，一直都没有找到一个比较折中的办法。

近期会更新这一部分的内容。

若有好想法，欢迎PR。

**Comment by MicroLord** [comment]
只要菜单不是写在数据库里面的，普通的权限验证就足够了，比如一个账户有"ROLE_ADMIN,ROLE_USER"两个角色，登录的时候存到token，然后给菜单一个或者多个角色访问权限，只要token的权限角色里面的一个存在于这个菜单角色里面，就可以激活，这种状态满足于绝大部分的权限验证系统！以下已实现功能代码，供参考：
user.service.ts:

```
    getRoles(): Authority[] {
        return this.getUserToken().authorities;
    }

    valRoles(authorities: Authority[]): boolean {
        for (let permission of this.getRoles()) {
            return authorities.some((auth: Authority) => auth.authority === permission.authority);
        }
    }
```

sidebar.component.html

```
<li *ngIf="child.children && authSrv.valRoles(child.role)" [nzOpen]="child.selected" nz-submenu>
                        <span title>
                            <i class="{{ child.icon }}"></i> {{ (child.translate | translate) || child.text }}
                        </span>
                        <ul *ngFor="let item of child.children">
                            <li *ngIf="authSrv.valRoles(item.role)" nz-menu-item [nzSelected]="item.selected"
                                [routerLink]="item.link" (click)="closeMenu()">
                                {{ (item.translate | translate) || item.text }}
                            </li>
                        </ul>
                    </li>
```

界面需要两个判断，主菜单和子菜单都需要验证，就可以达到，不同角色可以访问不同界面！
后台用的spring ouath2的token验证，希望能够给卡色一点灵感，但最终我还是会尊重你的思路，当然会用你的代码，尽快更新哦，我这个完全为了达到目的，很多性能没考虑的！

**Comment by cipchk** [comment]
see [0.0.1-alpha.6](https://github.com/cipchk/ng-alain/blob/master/CHANGELOG.md).
