### ISSUE TITLE
ng-alain@0.2

### ISSUE THREAD

**Issue by cipchk** [ng-alain/ng-alain#70]
`ng-alain@0.2` 的一个计划明细，分支：https://github.com/cipchk/ng-alain/tree/0.2.0

- [x] 将 `theme`、`core`、`shared` 分离独立库类似 `@delon/theme` 之类，解决更友好的升级问题。
    - [x] `theme` 抽离成 `@delon/theme`
    - [x] `shared` 抽离成 `@delon/abc`（abc：Alain Bussioness Components）
    - [x] `acl` 抽离成 `@delon/acl`
    - [x] `_HttpClient` 增加 `jsonp`、`patch`、`put`、`request` 请求
    - [x] `app-layout-nav` 更名为 `sidebar-nav`，并成为 `@delon/abc` 组件之一
    - [x] `rxjs` 引用方式更改为 `5.5` 版本
    - [x] 清理无效代码
    - [x] 规范表单校验编码风格
- [x] 增加文档站点
    - [x] 将 `ng-alain` 所有文档信息转移至站点中
- [x] 业务组件
    - [x] 倒计时（依赖 `ngx-coundown`）
    - [x] `fixed-btns` 更名为 `footer-toolbar` 正名为：底部工具栏
    - [x] 升级g2至3.x
    - [ ] ~侧边栏编辑区域~
- [x] 提升单元测试性能

**Comment by icycore** [comment]
```建议，仅供参考~```

share抠出来就差不多了，拆太多包反而不太好哦，太碎片了。
我个人感觉不应该把aside nav剥离，head nav + aside nav 组成sketch，它们属于一个整体。

拆包的目的是为了能够```解耦```。
比如有的项目是暂时停留在ng 4.x的，把Alain降回4.x的时候，header的一些component就得重做，它们是依赖于Zorro-Extra的组件，Zorro-Extra又只支持5.x.
author你考虑一下~

```i18n```能抠出来也挺好。

**Comment by cipchk** [comment]
`sidebar-nav` 本身是一个主菜单完整版，也是一个很重要的组件，抽离也能更好的复用。

> 其实 `@delon/abc` 将每个组件独立成为一个模块的形式存在，倘若真需要自定义，大可无须引用 `sidebar-nav` 模块，同时 fork 一个份到 ng-alain 根目录下。

extra 我会在今晚发布一个兼容 4 & 5 的版本。

**Comment by icycore** [comment]
angular web storage 的最新版也是只支持5.x.
改太多库和组件出来，可能你的精力不太够用。
一群人喊着让你改改改也烦啊，亲。
anyway，加油。

**Comment by maplye** [comment]
When do you ready to release 0.2?

**Comment by cipchk** [comment]
pre-release within two days.
