### ISSUE TITLE
clone2.0.0beta3版本，npm intall安装完成后，使用ng serve运行，编译报错

### ISSUE THREAD

**Issue by robbiesky** [ng-alain/ng-alain#701]
错误信息为：ERROR in src/app/app.module.ts(55,31): error TS2307: Cannot find module 'ngx-ueditor'. src/app/shared/shared.module.ts(17,31): error TS2307: Cannot find module 'ngx-ueditor'.

**Comment by cipchk** [comment]
重新安装一次，是 `ngx-ueditor` 发布了错误版本，已经在 `2.1.2` 中修复。
