### ISSUE TITLE
动态表单的（手动校验一次表单） validator 方法没有反应

### ISSUE THREAD

**Issue by GitYonglin** [ng-alain/ng-alain#707]
在这个例子中点击验证没有任何反应
文档描述

参数 | 说明 | 返回值
-- | -- | --
valid | 表单是否有效 | boolean
value | 表单值 | any
refreshSchema | 刷新 JSON Schema | void
reset | 重置表单 | void
validator | 手动校验一次表单 | void

https://stackblitz.com/edit/angular-edkzb3?file=src/app/app.component.ts

**Comment by cipchk** [comment]
请问你想表达什么？

**Comment by GitYonglin** [comment]
@cipchk 
可能我理解的有问题。
这个方法我的理解应该是触发验证结果吧，相对于点击 FormGroup 中的 updateValueAndValidity方法。
我想实现的是可以通过外部的方法触发 sf组件的 submit方法。
没看到 动态表单的源码，是通过 FormGroup 实现的吗？如果是能开放操作FormGroup对象就更灵活了

**Comment by cipchk** [comment]
`sf` 并非使用 FormGroup，有一套自己实现的检测监听规则。

我不清楚，你想干嘛。

我暂时关闭 issues，若有必要再重新打开。

**Comment by onecorner** [comment]
其实他的意思就是说提交的时候，能够将对应的验证错误结果给显示出来

**Comment by onecorner** [comment]
> @cipchk
> 可能我理解的有问题。
> 这个方法我的理解应该是触发验证结果吧，相对于点击 FormGroup 中的 updateValueAndValidity方法。
> 我想实现的是可以通过外部的方法触发 sf组件的 submit方法。
> 没看到 动态表单的源码，是通过 FormGroup 实现的吗？如果是能开放操作FormGroup对象就更灵活了

请问你的问题解决了吗？

**Comment by GitYonglin** [comment]
还是没有解决，validator 这个方法是可以得到 valid 的值但是错误提示还是没有显示？

**Comment by zdxxxxxx** [comment]
出现了同样的问题，这个手动校验不能让表单显示报错信息
