### ISSUE TITLE
less与scss互相切换

### ISSUE THREAD

**Issue by qmy777** [ng-alain/ng-alain#71]
## Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### 需求描述
能否提供一种便捷的方式对less和scss进行切换呢？

**Comment by cipchk** [comment]
由于antd本身只有less版本，并且其带了一些非常特殊的实现方式，基于此不会提供 scss 版本。

不过angular本身是不受限，换句话说，Less&scss是可以同时使用的。
