### ISSUE TITLE
acl setRole 增加字符串参数

### ISSUE THREAD

**Issue by Cuiqs76** [ng-alain/ng-alain#712]
- ng-alain version: 2.0.0 beta.0
- Angular version: 6.1.0

## 【必填项】重现链接，Reproduction link
https://ng-alain.github.io/ng-alain/#/delon/acl

## 重现步骤，Steps to reproduce
 增加 setRole( string | string[]) .
 如果从服务器获取的用户只有一个角色，那么是一个字符串 --- setRole后， acl不能正常工作。
如果是两个角色及以上，返回的是字符串数组， setRole后 acl可以正常工作。

**Comment by cipchk** [comment]
关闭原因： 长时间未回复提供更多信息。
