### ISSUE TITLE
2.0 版本 -- st 组件  分页显示器中 '共 0 条'-->’total 0 items‘ 未国际化的问题

### ISSUE THREAD

**Issue by lyj1008** [ng-alain/ng-alain#713]
- ng-alain version: 2.0
- Angular version: 6.1

## 【必填项】 重现链接，Reproduction link
- 模板：https://ng-alain.com/components/table/zh#STPage
- 截图：
![stpage](https://user-images.githubusercontent.com/43951176/46645460-968bd400-cbb7-11e8-9b9f-7214faa3f87f.jpg)

## 重现步骤，Steps to reproduce
![st](https://user-images.githubusercontent.com/43951176/46645709-c4bde380-cbb8-11e8-8f72-4098ec885114.jpg)

升级后，<st total="number" [page]="page"></st> 
total : number，不能自定义 <ng-templae #totalContent> {{'total'|translate}} {{total}} {{'item'|translate}} </nng-template>
STPage中total,只能在加载页面时 渲染一次。
  eg:   public  page: STPage = {
    total: this.translate.instant(`total`) + `${this.total}` + this.translate.instant(`items`),
    show: true, front: false, showSizeChanger: true, showSize: true, pageSizes: [10, 20, 30, 40, 50], 
   showQuickJumper: true };
原生的分页器中，对于总条数的显示，可以自定义

**Comment by cipchk** [comment]
下一版本会增加 `total`  i18n 的支持的。

**Comment by allenlongbaobao** [comment]
请问现在的最新版本中支持自定义 total 的国际化吗

**Comment by cipchk** [comment]
@allenlongbaobao 是的

**Comment by allenlongbaobao** [comment]
@cipchk 已经找到方法了，谢谢
