### ISSUE TITLE
增加全局配置：每次左侧菜单点击的时候内容页面对应刷新

### ISSUE THREAD

**Issue by wuxilin** [ng-alain/ng-alain#718]
# 增加全局配置：每次左侧菜单点击的时候内容页面对应刷新

1. 现有的菜单点击只有第一次的时候内容页面才会刷新，实际上更多的是每次点击菜单后刷新内容页面，当然，复用路由也是同时需要的，要的效果并不是禁用复用路由

2. 希望能在1.x的版本加上对应的功能，因为还没那么快升级2.x的版本

**Comment by cipchk** [comment]
https://ng-alain.github.io/1.x-doc/components/reuse-tab#%E5%8C%B9%E9%85%8D%E6%A8%A1%E5%BC%8F

> 除以上规则以外，路由配置中 `data` 属性若设置 `reuse` 值时优先级高于上述规则。
