### ISSUE TITLE
增加全局配置：复用路由切换时可以保留之前的滚动条位置

### ISSUE THREAD

**Issue by wuxilin** [ng-alain/ng-alain#719]
# 增加全局配置：复用路由切换时可以保留之前的滚动条位置

1. 现有的复用路由切换内容页面每次都是滚动到顶部，希望能配置保留之前的滚动位置

2. 希望能在1.x的版本加上对应的功能，因为还没那么快升级2.x的版本

**Comment by cipchk** [comment]
https://github.com/ng-alain/ng-alain/blob/1.x/src/app/layout/default/default.component.ts#L42
