### ISSUE TITLE
侧边导航收起后，建议高亮显示子级

### ISSUE THREAD

**Issue by Jonasgao1993** [ng-alain/ng-alain#72]

**Comment by cipchk** [comment]
jpg:
![1](https://user-images.githubusercontent.com/2987467/33269067-5d1e46da-d3ba-11e7-8a40-56df4faccfd1.png)

**Comment by zdxxxxxx** [comment]
刷新才会选中，不刷新不会自动选中

**Comment by cipchk** [comment]
DEMO也未发现这类问题；能否提供更明细的环境。

**Comment by cipchk** [comment]
关闭长期未处理问题。
