### ISSUE TITLE
st 对话框 modal 传输自定义参数

### ISSUE THREAD

**Issue by hennychen** [ng-alain/ng-alain#720]
/**
     * 对话框参数
     */
    params?: (record: any) => Object; 

每次都会传输 st 当前行的数据，而不是自定义数据，，按照文档修改params  依然不对，请看下是否有问题，谢谢

**Comment by hennychen** [comment]
console.log('-__-_-----___----__---_-', this.modalRef.getContentComponent()); 
 可以通过这个看到 params 的数据

**Comment by iwantacook** [comment]
设置参数：
```
modal: {
          component: MemberDetailComponent,
          size: 'md',
          params: (record: STData) => ({user_id: record.from_user_id}),
},
```

接收参数：
```
@Input()
user_id: string | number;
```
