### ISSUE TITLE
如何获取表格里面的滚动条？

### ISSUE THREAD

**Issue by BecksWang** [ng-alain/ng-alain#723]
表格通过overflow 出现滚动条后，无法获取到，希望能获取到然后控制滚动条的位置。

**Comment by cipchk** [comment]
ng-alain 出现的表格有两种：`st` 和 `nz-table`，前者本质上还是使用 `nz-table`，因此具体需求请至：https://github.com/NG-ZORRO/ng-zorro-antd/issues
