### ISSUE TITLE
请教一下关于自定义组件打包发布npm的问题

### ISSUE THREAD

**Issue by guccihuiyuan** [ng-alain/ng-alain#724]
我是用ng g library 命令创建了一个库，写好了自定义组件，组件是基于ng-zorro开发的，但是我在ng build的时候，先是报了schemas的错误，然后参照你的打包的组件，加了NO_ERRORS_SCHEMA后，又报了 Property binding ngForOf not used by any directive on an embedded template 这个错误，我在模板里面确实是用了  *ngFor="let column of columns"，但这个是angular默认有的，找不到解决办法。请教一下怎么解决这个问题

**Comment by cipchk** [comment]
https://zhuanlan.zhihu.com/p/45034574
