### ISSUE TITLE
tab菜单切换时，滚动条没有记住切换前的位置

### ISSUE THREAD

**Issue by wuxilin** [ng-alain/ng-alain#728]
- ng-alain version: 1.4.5
- Angular version: 6.1.0

## 注释掉这句代码后tab菜单切换时，滚动条还是在顶部，没有记住切换前的位置
![qq 20181018104909](https://user-images.githubusercontent.com/11895453/47128374-7f3d9c80-d2c3-11e8-839f-033351d90587.png)

**Comment by cipchk** [comment]
我不确定是否你设置过 [scrollPositionRestoration](https://angular.io/api/router/ExtraOptions#scrollPositionRestoration)，除此之外已经没有相应会自动跳转至顶部的代码。

**Comment by wuxilin** [comment]
请问scrollPositionRestoration在哪设置，我都是直接用ng-alain命令生成的工程，没加什么其他的

**Comment by cipchk** [comment]
建议好好阅读 Angular 基础知识，angular.io 是个非常好的选择。

**Comment by SuperRichZhao** [comment]
你好，请问你最后解决了吗？@wuxilin
