### ISSUE TITLE
点击当前激活的菜单时能刷新内容页

### ISSUE THREAD

**Issue by wuxilin** [ng-alain/ng-alain#729]
- ng-alain version: 1.4.5
- Angular version: 6.1.0

## 重现步骤

![qq 20181018105702](https://user-images.githubusercontent.com/11895453/47128618-992baf00-d2c4-11e8-928a-a390c1991b65.png)

如图：激活“数据字典”这个菜单后，再次点击“数据字典”这个菜单时，内容页没有刷新

**Comment by cipchk** [comment]
https://angular.io/api/router/ExtraOptions#onSameUrlNavigation

**Comment by wuxilin** [comment]
![qq 20181018112043](https://user-images.githubusercontent.com/11895453/47129443-e1000580-d2c7-11e8-8d35-41375f974e16.png)

按照你发的路径我这样改，但是，点击激活的菜单还是没有刷新，是我改的有问题吗
