### ISSUE TITLE
表单验证，是否应该增加对touched的检查？

### ISSUE THREAD

**Issue by codingzhou** [ng-alain/ng-alain#73]
```javascript
<div nz-form-explain *ngIf="getFormControl('captcha').dirty&&getFormControl('captcha').hasError('required')">Please input the captcha you got!
</div>
```
以上代码，是对captcha这个元素做校验，可以看到做了dirty校验，但是并没有做touched校验，官方文档上有如下建议：
> Why check dirty and touched?
> 我们肯定不希望应用在用户还没有编辑过表单的时候就给他们显示错误提示。 对dirty和touched的检查可以避免这种问题。改变控件的值会改变控件的dirty（脏）状态，而当控件失去焦点时，就会改变控件的touched（碰过）状态。

我个人觉得以上代码应该修改成：
```javascript
<div nz-form-explain *ngIf="(getFormControl('captcha').dirty || getFormControl('captcha').touched)&&getFormControl('captcha').hasError('required')">Please input the captcha you got!
</div>
```
但是预览代码发现，确实增加了touched校验，但是当光标从输入框移开，不做任何输入时，会触发required检查，但是style并不会变化

**Comment by cipchk** [comment]
的确，ng-alain 现存的 demo 当中的确有很多页面在处理表单校验时，没有统一的编码风格，有点历史原因，我会在 `0.2` 的时候统一处理这件事情。

**Comment by codingzhou** [comment]
@cipchk 感谢回答，刚才看了一下ng-zorro-antd的官方文档，也没有对touched做处理，期待大神的新版本！

**Comment by codingzhou** [comment]
@cipchk 刚才看了一下ng-zorro-antd的发行版本，
https://github.com/NG-ZORRO/ng-zorro-antd/releases/tag/0.5.0-rc.3，
在这个版本里面有提到修复了#117（touched的问题）这个问题，但是我的版本是大于0.5.0-rc.3的，好像这个问题并没有被真正修复

**Comment by cipchk** [comment]
@codingzhou 恩， 这个问题算是一种BUG。
