### ISSUE TITLE
关于多标签打开页面的功能支持

### ISSUE THREAD

**Issue by justein** [ng-alain/ng-alain#730]
大佬，以前1.x中间版本的时候，记得支持多标签的页面打开支持，类似如下
![image](https://user-images.githubusercontent.com/4216113/47130258-5e794500-d2cb-11e8-8f1a-6e99d05e416a.png)
多个标签这样的样式，请问这个功能还有支持吗？

**Comment by cipchk** [comment]
https://github.com/ng-alain/ng-alain/blob/master/src/app/delon.module.ts#L32
