### ISSUE TITLE
page-header组件内部属性失效.

### ISSUE THREAD

**Issue by Diry2017** [ng-alain/ng-alain#733]
- ng-alain version: 2.0.0
- Angular version: 6.1.0

## 【必填项】重现链接，Reproduction link

page-header组件,内部的例如tab消失.
解决方案 在page-header 引入属性即可
例如 :
```
<page-header [tab]='tab'>
  <ng-template #tab>
  </ng-template>
</page-header>
```
在之前的版本无需这样引入都会出现.

现在[alain演示](https://ng-alain.github.io/ng-alain/#/pro/list/articles)就出现了这种问题.

## 重现步骤，Steps to reproduce
[这里查看](https://ng-alain.github.io/ng-alain/#/pro/list/articles)

**Comment by Diry2017** [comment]
我不知道这个算不算bug,这个情况只会出现在生产环境中,然后按照以前的版本不会出现这个问题,最近几天重新下载依赖后才出现.

**Comment by cipchk** [comment]
这是DEMO示例的问题，可能升级时没有彻底，但你的方法是对的。

**Comment by Diry2017** [comment]
发现一个新问题在 IOS环境下 --prod 打包会出现以下错误
```
ERROR in : Can't bind to 'action' since it isn't a known property of 'page-header'.
1. If 'page-header' is an Angular component and it has 'action' input, then verify that it is part of this module.
2. If 'page-header' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("<page-header [ERROR ->][action]='action'> 
  <ng-template #action>
    <nz-radio-group nzSize="large" [(ngModel)]="time" (")
```
不知道是什么情况在IOS下载依赖后 page-header 不会出现action这个属性...

**Comment by cipchk** [comment]
这个错误应该是未找到 `page-header` 组件， 所以才找不到 `action` 属性。我想可能是缺少导入引起的，建议从自身找找原因。
