### ISSUE TITLE
全局cli升级到7.0 之后 克隆项目 进入页面报错。

### ISSUE THREAD

**Issue by liwan11123123** [ng-alain/ng-alain#735]
- ng-alain version: 2.0.0-beta.5
- Angular version: 6.1.10

## 重现步骤，Steps to reproduce

angular-cli ： 7.0.2
Git clone https://github.com/ng-alain/ng-alain.git
cd ng-alain
npm start
进入首页报错

**Comment by cipchk** [comment]
请提供具体的错误信息，若是 国际化相关为已知问题，自行移除对于的 ` | translate` 即可。

> 暂时未对 7.0 进行任何测试，关于 7.0 需要等待 zorro 完成 7.0 的工作，才会升级。
