### ISSUE TITLE
less or sass

### ISSUE THREAD

**Issue by lovedemo** [ng-alain/ng-alain#740]
I meet a problem when I want to use @delon/chart.I install the package,and I found the style file is .less,but my project is use .scss.So may I ask there are any ways to solve it.

**Comment by cipchk** [comment]
Absolutely, you can keeping `styles.less` and add `styles.scss` while importing it to angulars.json `styles` node, like this:

```
"styles": [
  "src/styles.less",
  "src/styles.scss"
],
```

**Note:** But can't use less variable in sass https://ng-alain.com/theme/global/en

**Comment by lovedemo** [comment]
I follow your code,but still have some problems.
I use the @delon/chart  independent because of that doc.
![image](https://user-images.githubusercontent.com/16830106/47425966-7adf1b00-d7be-11e8-97d9-ed242e6fddd0.png)
 I only install the @delon/chart and the @delon/until.It doesn't work.
Did I misunderstand the independent use?

**Comment by cipchk** [comment]
Sorry, will not recommend use delon/* alone, just deprecated a part document.
