### ISSUE TITLE
手机上访问后台，表格变成竖排了

### ISSUE THREAD

**Issue by water-zzh** [ng-alain/ng-alain#743]
手机上访问后台，表格变成竖排了。怎样设置才能让表格保持横排？

**Comment by cipchk** [comment]
`st` 目前是强制性，你可以暂时使用 `nz-table`，下一版本会增加一个新属性是否开启响应式。

**Comment by water-zzh** [comment]
好吧。那下个版本什么时候出？

**Comment by water-zzh** [comment]
哦不对，我现在就是用的nz-table，也是直接变成竖排了

**Comment by cipchk** [comment]
`nz-table` 也有自带响应式，只是风格不同，不过应该没有相应的可配置项，估计只能自己强制覆盖样式，或者向 zorro 提交相应的特性请求。

**Comment by water-zzh** [comment]
好的，多谢！

**Comment by s97712** [comment]
st 的样式连同 nz-table 也一起改了，建议先限制下选择器，不要影响到单独使用 nz-table
```css
/* 作用于所有 nz-table */
@media screen and (max-width: 767px)
.ant-table-tbody > tr > td {
   ...
}
```

**Comment by cipchk** [comment]
@s97712 能否麻烦就此问题重新发布一个新的 issues，谢谢。
