### ISSUE TITLE
[error] Can't bind to 'action' since it isn't a known property of 'g2-card'.

### ISSUE THREAD

**Issue by Caims01** [ng-alain/ng-alain#745]
Can't bind to 'action' since it isn't a known property of 'g2-card'.
1. If 'g2-card' is an Angular component and it has 'action' input, then verify that it is part of this module.
2. If 'g2-card' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.

@cipchk

**Comment by cipchk** [comment]
Pls import `@delon/g2` lib. to `DelonModule` (https://github.com/ng-alain/ng-alain/blob/master/src/app/delon.module.ts#L80)

**Comment by Caims01** [comment]
@cipchk 
能否贴一下代码给我看下，我怕理解有误，并且我看了此repository的delonModule并没有导入@delon/g2，为什么这个repository运行的g2图表能正常显示？

**Comment by cipchk** [comment]
笔误 [@delon/chart](https://github.com/ng-alain/ng-alain/blob/master/src/app/delon.module.ts#L15)

**Comment by Caims01** [comment]
我看了默认的ng-alain@next是有import这个@delon/chart

如
import { DelonChartModule } from '@delon/chart';
DelonChartModule.forRoot(),

但我还是出现错误，所以我比较纳闷

@cipchk

**Comment by cipchk** [comment]
https://github.com/ng-alain/ng-alain/search?q=DelonChartModule&unscoped_q=DelonChartModule

**Comment by Caims01** [comment]
@cipchk 谢谢大佬，我在shared.module.ts中按https://github.com/ng-alain/ng-alain/search?q=DelonChartModule&unscoped_q=DelonChartModule中缺少的DelonChartModule部分的代码补上就可以了
