### ISSUE TITLE
ng update ng-alain issues (问题汇总)

### ISSUE THREAD

**Issue by cipchk** [ng-alain/ng-alain#750]
## 最低依赖

```ts
"typescript": "2.9.x",
"parse5": "^5.0.0"
```

## QA

> 建议优先阅读：https://ng-alain.com/docs/upgrade-v2

**为什么图标不见了**

ng-zorro-antd 1.7 对图标有破坏性变更，具体修复参考：https://github.com/NG-ZORRO/ng-zorro-antd/issues/2304

**图标出现双皮奶**

使用旧的 color.less，重新执行 `npm run color-less`，建议根据 #760 添加相应指令使每一次构建都自动重新生成。

**.bezierEasingMixin();**

Angular build 版本过低，提升 `"@angular-devkit/build-angular": "~0.8.0",` 版本。

**Comment by liwan11123123** [comment]
富文本 可否 有braft-editor这样的支持？？？
我找了angular下的富文本，发现都不是很好用，react下的这个用起来很舒服。

**Comment by cipchk** [comment]
@liwan11123123 https://github.com/cipchk/ngx-tinymce 和 https://github.com/KillerCodeMonkey/ngx-quill 都是不错的选择。

**Comment by kolterr** [comment]
我用cli新建了一个curd业务页，page-header的add 按钮怎么才能显示出来呢

**Comment by hidoos** [comment]
@kolterr 你去看一下 page-header 组件的文档就知道了。https://ng-alain.com/components/page-header/zh

**Comment by danranVm** [comment]
https://github.com/danranVm/update-ng-alain

**Comment by danranVm** [comment]
### 从1.5.2 升级到2.0失败
- 完全根据文档中的升级命令来执行的，npm和yarn 都试过了
- 执行 ng update ng-alain --next  
  - ![image](https://user-images.githubusercontent.com/25052421/51442976-c5205b80-1d1d-11e9-8f19-ac36de3fb1a1.png)
  - ng-alain的版本号会变成 ^2.0.0-rc.3
  - ng-zorro-antd 的版本是 1.8.1
  - 相关 delone 的版本未发生变化 （1.5.2）
  - 不会自动更新 st se sv等组件内容
- 执行 ng update ng-alain@2.0.0 与上面效果一样
- 执行 ng update ng-alain 
  - ![image](https://user-images.githubusercontent.com/25052421/51443123-272d9080-1d1f-11e9-9d61-d71e9194a9a2.png)
  - ng-alain的版本号会变成 7.0.0-rc.4
  - ng-zorro-antd 的版本是 1.8.1
  - 相关 delone 的版本变成 7.0.0-rc.4
  - 会自动更新 st se sv等组件内容
- [可以用这个仓库来复现](https://github.com/danranVm/update-ng-alain)

**Comment by danranVm** [comment]
上面升级失败，我目前的解决方案是：
```bash
# 1、删除 node_modules、package-lock.json
npm install
# 2、强制指定 `parse5` 版本
npm add parse5@^5.0.0 -D
# 3、执行安装
ng update ng-alain
# 4、在上一步操作后 会直接升级到 7.0.0_rc3, 所以我们需要回退一下版本
# 删除 node_modules、package-lock.json 并将 ng-alain 和相关 delone 库的版本手动修改为 2.0.1
npm install
```

**Comment by hennychen** [comment]
update to 7.0.0-rc.6 (2019-01-22)
error
![3 6qna7gbgz4zrvqkh 1 _g](https://user-images.githubusercontent.com/2526830/52488461-d19c2380-2bfa-11e9-835b-2dd8b60ad12c.png)
WARNING in ./src/styles.less (./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/src??embedded!./node_modules/less-loader/dist/cjs.js??ref--15-3!./src/styles.less)
Module Warning (from ./node_modules/postcss-loader/src/index.js):
Warning

(159:3) Replace text-decoration-skip: ink to text-decoration-skip-ink: auto, because spec had been changed

ERROR in The Angular Compiler requires TypeScript >=3.1.1 and <3.3.0 but 3.3.3 was found instead.

**Comment by magic-L** [comment]
升级@delon到7.0.3版本后运行项目出错
ERROR in ./src/styles.less (./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/src??embedded!./node_modules/less-loader/dist/cjs.js??ref--15-3!./src/styles.less)
Module build failed (from ./node_modules/less-loader/dist/cjs.js):
@import 'node_modules/@delon/theme/styles/index';
@import 'node_modules/@delon/abc/index';
^
Can't resolve './node_modules/@delon/abc/index.less' in 'F:\MyProject_Web\src'
      in F:\MyProject_Web\src\styles.less (line 3, column 0)
ERROR in node_modules/rxjs/internal/types.d.ts(81,44): error TS1005: ';' expected.
node_modules/rxjs/internal/types.d.ts(81,74): error TS1005: ';' expected.
node_modules/rxjs/internal/types.d.ts(81,77): error TS1109: Expression expected.

**Comment by twt898xu** [comment]
@magic-L 
你好，
我的ng6的项目升级到ng7以后出现和你一样的错误，请问你是怎么解决的！！
感谢。。

**Comment by hennychen** [comment]
建议删除 package-lock.json 和node_modules 目录
重新npm install

**Comment by mingyaaaa** [comment]
我出现了同样的问题 执行 `ng g ng-zorro-antd:fix-icon` 图标还是不显示  重新安装 
`@ant-design/icons-angular`可以解决     看了一下问题应该是安装 ant-design 时 `@ant-design/icons-angular` 库不包含src目录结构
