### ISSUE TITLE
动态表单tree-select小部件，enum如果带children，默认值无法显示

### ISSUE THREAD

**Issue by jovian007** [ng-alain/ng-alain#751]
- ng-alain version: 1.4.4
- Angular version: 1.6.0
动态表单tree-select小部件，enmu如果带children，默认值无法显示。
## 【必填项】重现链接，Reproduction link
https://stackblitz.com/edit/ng-alain-setup-nthqeu

**Comment by jovian007** [comment]
动态表单加载，默认一个部门的值，结果部门不显示这个值

**Comment by cipchk** [comment]
@jovian007 我无法运行该示例。

**Comment by jovian007** [comment]
> @jovian007 我无法运行该示例。


示例刚打开没法运行，预览里刷新下就好了，我也不知道为啥，麻烦您看下，谢谢辛苦啦

**Comment by jovian007** [comment]
动态表单tree-select小部件 ，以下代码的departmentList中enum 如果数据是[{a},{b}]这样类型的可以默认值显示出来，如果数据是类似树形node,如[{a:children[{b},{c}]},{d}]情况的默认值无法显示出来，SFSchema代码如下：
  userSchema:SFSchema={
    properties: {
      userId: { type: 'number', title: 'ID' },
      departmentList: { type: 'string', title: '部门',enum: [{title:"考录处",value:616,children:[{title:"考录处1",value:6161},{title:"考处2",value:6162}]},{title:"考培处",value:610},{title:"事业单位管理处",value:615}],default:[6162], ui:{widget: 'tree-select',checkable:true}},
      description:{type: 'string', title: '描述'},
    },
  } ;
则部门 无法在页面加载时候默认值不显示。

**Comment by cipchk** [comment]
tree-select 的键名为 `key`，试着把 `enum` 数据的 `value` 变更为 `key`。

https://ng.ant.design/components/tree-select/zh

**Comment by jovian007** [comment]
我前面也是根据ng-zorro写的树，情况也是一样的，重现连接也修改过。@cipchk

**Comment by hennychen** [comment]
我也遇到这种情况了，默认值无法显示

**Comment by cipchk** [comment]
注意一下 zorro 的版本。
