### ISSUE TITLE
这个clone下来，依赖安装完执行ng server --hmr之后出现的编译问题，不知道什么原因我哪里都没有改过？

### ISSUE THREAD

**Issue by harrylyh** [ng-alain/ng-alain#752]
🚨 Issues 是用于BUG、Feature、进度追踪 🚨
🚨 The issue tracker is not for questions 🚨

如果有任何问题，可在以下方式获得答案：

- https://ng-alain.com/
- QQ Group：316911865
- https://segmentfault.com/t/ng-alain
![image](https://user-images.githubusercontent.com/26681969/47598076-602cc200-d9c9-11e8-9c4c-0ac9fc397868.png)

**Comment by cipchk** [comment]
请勿使用cnpm，具体见文档qa

**Comment by cipchk** [comment]
https://ng-alain.com/docs/faq/en
