### ISSUE TITLE
关于acl的建议

### ISSUE THREAD

**Issue by hackeryutu** [ng-alain/ng-alain#756]
acl的功能我觉得可以把角色的控制变成资源的控制， 后端只要返回资源标识， 然后前端根据资源来决定渲染还是不渲染。 

如果使用角色来控制访问， 每加一个角色， 前端相关角色的资源控件都要改一遍代码。 

<button class="add-user" [acl]="{role: ['ADMIN']}">
</button>

<button class="add-user" [acl]="USER_ADD">
</button>

**Comment by hennychen** [comment]
建议你可以用动态获取 不要写死，

**Comment by hackeryutu** [comment]
我看到有权限点这个东西
