### ISSUE TITLE
右侧配置项，点击换肤后，页面按钮出现重影（git本地版本，而在线预览的demo版没有这个问题）

### ISSUE THREAD

**Issue by chenfei66** [ng-alain/ng-alain#758]
右侧配置项，点击换肤后，页面按钮出现重影（git本地版本，而在线预览的demo版没有这个问题），请问是什么原因呢？
本地的nodejs，Angular Cli 都是最新版本

**Comment by cipchk** [comment]
可能你使用了旧版本的 `alain-default.less` 文件，可以重新执行一次：

```bash
npm run color-less
```

相应命令所在 [package.json](https://github.com/ng-alain/ng-alain/blob/master/package.json#L33)

**Comment by fiberstar** [comment]
执行完报错如下：
> ng-cms@0.0.0 color-less D:\development\project\jk-client\ng-cms
> node scripts/color-less.js

module.js:549
    throw err;
    ^

Error: Cannot find module 'D:\development\project\jk-client\ng-cms\scripts\color-less.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ng-cms@0.0.0 color-less: `node scripts/color-less.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ng-cms@0.0.0 color-less script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\win 10\AppData\Roaming\npm-cache\_logs\2018-11-05T13_11_07_010Z-debug.log
