### ISSUE TITLE
请问下，我更改系统的主题背景色后，页面中ng-zorro-antd的card和表格还是白色，请问下如何对应的修改，保持与主题的背景色一直呢？谢谢

### ISSUE THREAD

**Issue by shaohongzhu** [ng-alain/ng-alain#759]
🚨 Issues 是用于BUG、Feature、进度追踪 🚨
🚨 The issue tracker is not for questions 🚨

如果有任何问题，可在以下方式获得答案：

- https://ng-alain.com/
- QQ Group：316911865
- https://segmentfault.com/t/ng-alain

**Comment by cipchk** [comment]
每个 zorro 组件都有自己的样式风格，你想覆盖可以自行寻找对应的变量值，然后在 theme.less 中重新定义，例如： [card](https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/components/card/style/index.less#L29)。

相关文章：

- https://ng-alain.com/theme/getting-started/zh#%E5%A6%82%E4%BD%95%E8%A6%86%E7%9B%96%E5%8F%82%E6%95%B0
