### ISSUE TITLE
ng-alain 2.0.0左边菜单的tab切换功能取消了吗

### ISSUE THREAD

**Issue by zhengyanghuaer** [ng-alain/ng-alain#766]
![image](https://user-images.githubusercontent.com/35128870/48246656-3b096c00-e42b-11e8-9a4e-1eb557e3db43.png)

**Comment by cipchk** [comment]
https://ng-alain.com/components/reuse-tab/en#%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8

反之。
