### ISSUE TITLE
将哈希路由改为默认路由的问题

### ISSUE THREAD

**Issue by chenjia123** [ng-alain/ng-alain#77]
我在使用最新版的 ng-alain ，做的很不错，就拿来直接作为架子用了。但是也遇到一些问题。

ng-alain 使用的是哈希路由策略，当我改为默认路由策略后，路由跳转会刷新整个页面，我看 network 中确实时做了一个完整的启动请求，这样就破坏了 SPA 的优点了。

angular文档中有一句话：Stick with the default unless you have a compelling reason to resort to hash routes。当然使用默认路由需要将服务器所有 URL 重定向到 index.html 中，这一点要注意。

**Comment by cipchk** [comment]
`PathLocation` 需要后端web服务器的支持，这本身和 ng-alain 无关。

**Comment by chenjia123** [comment]
我并没有打包部署，只是用 ng serve 启动这个项目。之前也有一个angular 4项目是用默认路由的，没有出现这样的问题。
这里只是更改了路由策略，也就是删除“{ useHash: true }”，并没有做其他任何修改，然后点击侧边栏的就会重新加载整个页面，而不是局部刷新。

**Comment by chenjia123** [comment]
目前我解决的方式是：取消在侧边栏的 routerLink 指令，改为 click 绑定一个goto函数，将 link 作为参数传进去，然后goto函数里面用 router.navigate([link])，这样就不会刷新整个页面了

**Comment by cipchk** [comment]
这里是有一个已知BUG，这是由于 angular4 的历史原因存在的，在 `0.2` 已经修复它了。

我会重新打开此 issue，以便你更好的跟踪。
