### ISSUE TITLE
SF Select 如何 进行检索查询 

### ISSUE THREAD

**Issue by MrChuJiu** [ng-alain/ng-alain#770]
https://stackblitz.com/edit/ng-alain-setup-cmmhpq 

我的查询下拉菜单有 100个 我限制每次最多显示50个，现在我想检索这个下拉菜单
我使用onSerch方法 来进行检索  请问应该如何处理
(现在下拉菜单显示的是 lable1  至 lable 50     输入lable55  让他检索出来并且在option上显示 如何去做)

**Comment by cipchk** [comment]
closed this, because of fixed in qq group.

**Comment by AnthonyZhang12** [comment]
这个问题是怎么解决的呀？能分享一下吗？非常感谢
