### ISSUE TITLE
sf 使用 formData 属性赋值，后使用refreshSchema()更新数据，提交按钮无法激活

### ISSUE THREAD

**Issue by GitYonglin** [ng-alain/ng-alain#773]
- ng-alain version: 2.0.0-rc.3
- Angular version: 6.1.0
1. sf 使用 formData 属性赋值后使用refreshSchema()更新数据出现了以下问题？
2. 有个想法不知道可以不在 执行 refreshSchema()方法时不触发change() 方法？
## 重现链接: https://stackblitz.com/edit/ng-alain-sfrefreshschema?file=src/app/app.component.ts
![20181115_000114](https://user-images.githubusercontent.com/18706176/48495271-9348cf80-e86a-11e8-9ffa-d564214db0fd.gif)

这个不知道是bug吗？

**Comment by cipchk** [comment]
`refreshSchema` 只会对Schema进行刷新，并不会做检校。你可以手动触发 `validator()`。

> PS：`validator()` 会受 `firstVisual` 属性值的影响。

**Comment by GitYonglin** [comment]
我发现了 age 属性
"age": {
      "type": "number",
      "title": "年龄",
      "minLength": 5,
      "minimum": 18,
      "maximum": 50,
      "default": 25
    },
这里设置了minimum和maximum，我直接在代码中设置 age 的值不符合校验规则的问题。
手动校验可以的得到 valid 的值，但是界面没有更新错误提示，界面也更新一下就更直观了
