### ISSUE TITLE
Reuse tab标题样式自定义

### ISSUE THREAD

**Issue by xingjl6280** [ng-alain/ng-alain#783]
您好, 

reuse-tab是个非常有用的组件, 不知道目前的组件能不能自定义tab title的样式, 我查阅了reuse-tab的文档, 没有发现能够实现这个需求的方法.

场景:
对于一些复杂的表单, 我们选择用新的页面(tab)显示而不是modal对话框, 如果表单已被修改处于dirty状态, 我们希望能够将tab title设置成红色或加上icon, 更进一步, 我们希望实现未提交保护, 防止用户错误关闭浏览器或tab页丢失数据

因为项目比较急, 目前有没有什么workaround?

谢谢

**Comment by xingjl6280** [comment]
补充一下, 我使用的是最新2.0.0版本

**Comment by cipchk** [comment]
简单回答：这些都可以实现。

- `reuse-tab` 内部实际是 `nz-tabset`，你可以强制覆盖相应的CSS亦可。
- 表单与 `reuse-tab` 要有所关联，估计只能由你自己重新定义 `ReuseTabComponent`，若不复杂视觉，可以通过相应的 JavaScript 代码也能实现。
