### ISSUE TITLE
"padding-right: 15px" was added to body when drawer is open

### ISSUE THREAD

**Issue by WOOOFEI** [ng-alain/ng-alain#784]
- ng-alain version: stable
- Angular version: 6.2.7
- MacOS 10.13.6 

## 【必填项】重现链接，Reproduction link
https://ng-alain.github.io/ng-alain/#/dashboard/v1

## 重现步骤，Steps to reproduce
点击主页右侧这个图标后打开抽屉会导致右侧多加了15px的padding
![image](https://user-images.githubusercontent.com/21849553/48890797-c85daf00-ee74-11e8-9833-f206758d088a.png)

I found that all drawers will cause this problem， I've tried setting "@scrollbar-enabled" to "false", but it did not work.

**Comment by cipchk** [comment]
这是ng-zorro-antd已知BUG，若你在意可以关掉 ng-alain 对滚动条美化。

```less
// in theme.less
@scrollbar-enabled: false
```
