### ISSUE TITLE
存储Token服务（申明多个ITokenService服务）不能支持同时多种存储类型？

### ISSUE THREAD

**Issue by jomesx** [ng-alain/ng-alain#786]
ITokenService默认是采用 LocalStorageStore 持久化存储，也很方便通过配置实现其它类型的存储。
现在的问题是：存储类型仅仅支持一种（DA_STORE_TOKEN只能有一种值），有时还需要多种存储类型同时支持，如登陆的remember me功能在需要记录时存储在LocalStorageStore ，不需要存储时应该记录在SessionStorageStore或MemoryStore中，这样关闭浏览器时下次必须重新登陆。
请问ng-alain中是否已支持支持同时（申明多个ITokenService服务）多种存储类型？

**Comment by cipchk** [comment]
不支持，但是不应该把 Remember me 当作实际授权有效期的条件，Token 该什么时候过期就应该什么时候过期， Remember me 一般是用于支持自动无感刷新 Token。

**Comment by lfli** [comment]
ng-alain预览网站上取消自动登陆的勾选后，依旧自动登陆，这是为什么？

**Comment by cipchk** [comment]
@lfli  DEMO 没有对这部分进行功能编码。
