### ISSUE TITLE
Cannot read property 'tagName' of null

### ISSUE THREAD

**Issue by zengxiangfu** [ng-alain/ng-alain#788]
- ng-alain version: 2.0.0
- Angular version: 6.1.10

最新的ng-alain 模板总是报Cannot read property 'tagName' of null,   启动每点击一次页面都会出现一次

![image](https://user-images.githubusercontent.com/26755064/48963900-35d62080-efd8-11e8-9930-3f5db47d2908.png)

**Comment by cipchk** [comment]
麻烦提供更多的环境，以及我能重现的方法。

另外有一种感觉应该是因为一些浏览器兼容问题，细节可以参考：https://angular.io/guide/browser-support。
