### ISSUE TITLE
Cannot find module 'g2-angular'

### ISSUE THREAD

**Issue by maplye** [ng-alain/ng-alain#79]
Verson:  0.2.0-beta.0

I npm start the application, and got below error message when compile the code.

`
ERROR in src/app/routes/charts/charts.module.ts(3,31): error TS2307: Cannot find module 'g2-angular'
`

**Comment by cipchk** [comment]
please remove [import](https://github.com/cipchk/ng-alain/blob/0.2.0/src/app/routes/charts/charts.module.ts#L17) code fix this.

**Comment by maplye** [comment]
Done
