### ISSUE TITLE
菜单折叠后表格出现空白，表格是用的jqwidgets，不能很好的根据菜单的折叠状态响应布局。大神是否有好的解决办法？

### ISSUE THREAD

**Issue by zhengyanghuaer** [ng-alain/ng-alain#793]
![image](https://user-images.githubusercontent.com/35128870/49062907-a25b5480-f250-11e8-8931-a20c13cd24d9.png)
![image](https://user-images.githubusercontent.com/35128870/49062926-ae471680-f250-11e8-9720-117920d7db1a.png)

**Comment by cipchk** [comment]
假如 `jqwidgets` 有相应的刷新布局的方法时，可以通过以下方式：

```ts
this.settings.notify.subscribe(() => this.setClass());
```

当布局变更时，重新调用一次相应 `jqwidgets` 的刷新动作。

> 注：订阅同时也需要取消订单，保持一个良好的编码习惯。

**Comment by zhengyanghuaer** [comment]
问题已经解决了，大神你真是帮我大忙了。非常感谢！！！
