### ISSUE TITLE
ng build --prod打包后页面样式乱了，刷新后又好了

### ISSUE THREAD

**Issue by zhengyanghuaer** [ng-alain/ng-alain#795]
进来的页面呈现：
![image](https://user-images.githubusercontent.com/35128870/49070171-01779400-f266-11e8-8e23-3e8b9d9ebef0.png)
刷新后页面呈现：
![image](https://user-images.githubusercontent.com/35128870/49070200-16542780-f266-11e8-8c5c-a122424e02eb.png)

**Comment by cipchk** [comment]
使用 Chrome 打开面板就知道问题所在，无非就是样式路径无效，相关参考：

- [baseHref](https://angular.io/cli/build)
- [deployUrl](https://angular.io/cli/build)

> PS：请勿重开重复的 ISSUES，会给所有 WATCH 的人发送一些无意义的通知。 #794
