### ISSUE TITLE
ST表格组件打开模态框时，标题设置有问题

### ISSUE THREAD

**Issue by anarckk** [ng-alain/ng-alain#798]
- ng-alain version: 2.0.0
- Angular version: ^6.0.0

## 【必填项】重现链接，Reproduction link

https://stackblitz.com/edit/ng-alain-setup-jivpos

## 重现步骤，Steps to reproduce
打开模态框之后，标题没有展示，按着ts的类型描述写的，
![image](https://user-images.githubusercontent.com/27038948/49272007-e184e200-f4aa-11e8-8721-0a8fc9856995.png)
这是打开之后有问题的图片：
![image](https://user-images.githubusercontent.com/27038948/49272036-09744580-f4ab-11e8-8bc9-94339649a14c.png)

**Comment by anarckk** [comment]
我想把标题起在这里：
![image](https://user-images.githubusercontent.com/27038948/49272092-3b85a780-f4ab-11e8-8288-57aa678138ec.png)

**Comment by anarckk** [comment]
我又给你找麻烦了，作者大大

**Comment by cipchk** [comment]
请认真阅读文档：https://ng-alain.com/components/table/en#STColumnButtonModal
