### ISSUE TITLE
The menu will be selected duplicately.

### ISSUE THREAD

**Issue by bokire** [ng-alain/ng-alain#8]
## I'm submitting a menu selected bug

<pre><code>
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Support request => Please do not submit support request here
</code></pre>

## Current behavior

First， sorry for my bad English.
Sometimes the menu will be selected duplicately like image1.
![image1](https://user-images.githubusercontent.com/4404438/30192941-073ff4ec-947d-11e7-9f7c-e7469e5578f0.png)

In order to describe the error more clear，I append the `item.selected` after the `(item.translate | translate) || item.text` . Then, click the menu ,  the menu  `item.selected`  will be changed to true.
![image2](https://user-images.githubusercontent.com/4404438/30192990-42b62ed8-947d-11e7-862c-531ba9f14809.png)

At this time , click a menu which will leave the page like 'Login' under the 'Pages'
![image3](https://user-images.githubusercontent.com/4404438/30193019-77acd998-947d-11e7-839a-ae073d5f4f21.png)

The browser will href to Login page , then click the 'go back' button of the browser to back, now  all of the 'item.selected == true' menus will be selected like image1.

## Environment

<pre><code>
Browser:
- [x] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by cipchk** [comment]
maybe make a mistake logical in `setSelector()`,  i will confirm that. thx.

**Comment by bokire** [comment]
I think...
should be defined a globel variable to remember  the selected menu with `menu.id` .
