### ISSUE TITLE
simple-table STMultiSort custom

### ISSUE THREAD

**Issue by xingkoo** [ng-alain/ng-alain#801]
当后端接收排序参数的规则与STMultiSort默认规则不同
比如`?sort=a.descend,b.ascend`中,分割符是使用的`,`来分割的.就需要自行配置全局STMultiSort规则.

如果是部分表格单字段排序, 部分表格多字段排序, 且当后端规则与默认值不同时,将无法配置全局规则.
如配置全局规则,将导致所有的表格都装支持多排序.

所以是否可以装排序规则与是否开启所有表格多字段排序分开设置?

**Comment by cipchk** [comment]
抱歉，没明白您的意思。所有排序相关参数：

- https://ng-alain.com/components/table/en#STSingleSort
- https://ng-alain.com/components/table/en#STMultiSort

超出以下范围，目前没有再扩充的考虑。

**Comment by xingkoo** [comment]
我想说的是,如果全局配置了 `STMultiSort`, 会导致`**所有的表格**`都使用多字段排序.
但是配置 STMultiSort `**只是**`为了让`多字段排序的规则(比较间隔符)与后端匹配`.`**而非**`让所有的表格**默认使用多字段排序**

**Comment by cipchk** [comment]
一般来说会需要多字段排序是否表示整个系统都会需要多字段排序，这个问题有两个方向：

1. 保留目前现状，即全局配置 `mulitSort` 表明所有都需要多字段排序。
2. 全局配置 `mulitSort` 表示为规则配置，但对于整个系统需要多字段排序者都需要逐一为每一个 `st` 增加 `mulitSort` 选项，若某个表格无须多字段排序，则单独设置 `mulitSort="false"`。
