### ISSUE TITLE
modal & drawer custom click close and mask

### ISSUE THREAD

**Issue by xingkoo** [ng-alain/ng-alain#803]
Drawer 组件中有个 `(nzOnClose)`事件绑定.
Modal 组件中有个`(nzOnCancel)`事件绑定.
如果想要使用服务动态加载组件的方式使用时,如何设置对应的事件绑定呢?查看了下源码,没有看明白如何可以做到,不知道是不是没有暴露出来对应的绑定方法,或者写了我没有找出来?
麻烦看下能不能解决这个问题.   一些特殊场景下会需要使用这个方法.

比如在列表中点击后弹出drawer  然后里面点击编辑, 使用modal方式来编辑.
编辑完成时,drawer中可以订阅到close事件,直接更新页面数据.`(可以标识一个数据被修改,用于关闭drawer时回传)`
当关闭drawer时,不能回传这个标识

**Comment by cipchk** [comment]
自行阅读文档，所有可配置项：https://ng.ant.design/components/drawer/zh#nzdraweroptions

**Comment by xingkoo** [comment]
我是想要设置 `(nzOnClose)`这个回调.
目前官网的demo里面是使用`<nz-drawer (nzOnClose)="close()"></nz-drawer>`的方式来使用的.
使用服务的方式来打开drawer时,不知道怎样使用.
求教.

**Comment by xingkoo** [comment]
这个问题是不是应该是刷nzOnClose没有暴露出来?
