### ISSUE TITLE
使用CLI创建的ng-alain项目，通过浏览器直接访问/passport/下的任何组件被重定向到login组件。

### ISSUE THREAD

**Issue by lfli** [ng-alain/ng-alain#805]
创建了一个关于邮箱验证的组件，配置的路由和login在同一级，用户需要直接访问此页面，但是在浏览器上直接访问此路由时，url地址被重定向到login，直接访问注册页面也同样如此。目前发现是没有token导致的，在配置DelonAuthConfig中，给ignores加上此地址无效（貌似只对http请求有效）。请问如何配置才能直接访问在passport下的非login组件？

**Comment by cipchk** [comment]
几个方面自行检查：

- 路由配置是否包含守卫
- 目标页面是否一开始发起请求导致 Auth 自动跳转

更多细节请阅读 angular.cn

**Comment by lfli** [comment]
就是Auth自动跳转的，并没有路由守卫，直接访问注册页面也会自动跳转到登陆页面，从git上克隆下来的项
目不存在这个问题（此项目中DelonAuthConfig只配置了login_url），我只知道关闭token_invalid_redirect能
做到不跳转，我不清楚这是否是一个bug。

**Comment by cipchk** [comment]
@lfli 能否提供重现示例，我本地无法重现你的问题。

**Comment by lfli** [comment]
找到原因了，是在viaHttp中请求用户数据导致的，没有注意到一访问就调用了viaHttp，抱歉。
