### ISSUE TITLE
tree compent reset data bug

### ISSUE THREAD

**Issue by xingkoo** [ng-alain/ng-alain#808]
- ng-alain version: X.Y.Z
- Angular version: X.Y.Z

## 【必填项】重现链接，Reproduction link

https://stackblitz.com/edit/ng-alain-setup-sm7pq5

## 重现步骤，Steps to reproduce
点击demo中的刷新按钮.当tree的数据重设时,所有的checded数据都被丢失了.

**Comment by xingkoo** [comment]
我的临时解决方案时,使用if来判断nodes是否存在,不存在时不显示tree组件.
当需要刷新时,nodes设置为false,再设置数据.此问题解决.

**Comment by cipchk** [comment]
ng-alain 不接收任何 ng-zorro 组件使用的问题，请自行至 ng-zorro-antd。
