### ISSUE TITLE
reuse-tab: reuse-tab doesn't work when using another <route-outlet> or child routes in a component

### ISSUE THREAD

**Issue by WOOOFEI** [ng-alain/ng-alain#809]
- ng-alain version: 2.0.0
- Angular version: 6.1.3

## 【必填项】重现链接，Reproduction link
![qq20181207-140335](https://user-images.githubusercontent.com/21849553/49631821-7dc06300-fa2e-11e8-8830-bf23e184dd63.gif)

## 重现步骤，Steps to reproduce
DEMO中“个人页>个人设置”（settings.component)中使用了子路由来对几个界面进行路由，导致无法被reuse-tab识别成一个标签，我尝试过在路由文件中增加data: {reuse: true}，但是这会让每个路由都有一个自己的标签。如果想实现复用settings.component并保持子路由正常工作，有没有什么其他的解决方法（例如允许多个路由公用一个复用标签？）。

**Comment by cipchk** [comment]
不考虑这种情况，可以自己重写 settings.component 来实现。

**Comment by SuperRichZhao** [comment]
一样的功能需求，请问最后如何解决的。每个子路由增加data: {reuse: true}吗@WOOOFEI
