### ISSUE TITLE
How to get user.name through ajax

### ISSUE THREAD

**Issue by lyc152** [ng-alain/ng-alain#81]
看到 user.name 通过 assets/app-data.json 获取 , 怎么样通过ajax 请求 获取 name 呢? 我另外写了UserInfoService，但是 在 setting.service 中 的 setUser 中 调用 这个 service ， 会报以下错误

zone.js:690 Unhandled Promise rejection: StaticInjectorError[UserInfoService]: 
  StaticInjectorError[UserInfoService]: 
    NullInjectorError: No provider for UserInfoService! ; Zone: <root> ; Task: Promise.then ; Value: Error: StaticInjectorError[UserInfoService]:

但是 我新开页面中调用 新写的UserInfoService 中的获取 user.name 是 可以获取到的，麻烦看下是什么原因呢？

**Comment by cipchk** [comment]
1
[No provider for UserInfoService!] 是指你没有注册这个Service，SettingService 是在 `coer.module.ts` 中注册，因此，你想让其调用 UserInfoService，你的 UserInfoService 依然也需要在 `core.module.ts` 中注册。

2
我不太建立你去修改 setting.service.ts 的内容，这是因为它本质为服务于 ng-alain 主题系统的，所需要的数据，而且相应的接口也算满足日常需求；透过远程获取用户信息，可以在 [startup.service.ts](https://github.com/cipchk/ng-alain/blob/master/src/app/core/services/startup.service.ts#L35) 给予，这样做会更合理。
