### ISSUE TITLE
请问有没有相关websocket使用的封装，和相关的例子？

### ISSUE THREAD

**Issue by shaohongzhu** [ng-alain/ng-alain#811]
请问有没有相关websocket使用的封装，和相关的例子？

**Comment by cipchk** [comment]
rxjs/websocket 已经足够简单，参考：

https://zhuanlan.zhihu.com/p/45178635

**Comment by shaohongzhu** [comment]
> rxjs/websocket 已经足够简单，参考：
> 
> https://zhuanlan.zhihu.com/p/45178635

多谢，学习一下
