### ISSUE TITLE
在所有IE都报错

### ISSUE THREAD

**Issue by zhaojieip** [ng-alain/ng-alain#812]
项目在所有的IE浏览器都报错，好像是图标引起的
![qq 20181209222758](https://user-images.githubusercontent.com/32030955/49730242-b7a19b80-fcb2-11e8-9887-e3432c356c29.png)

**Comment by gongchao** [comment]
ng-aliain 和 ng-zorro-antd 的版本是多少？

**Comment by zhaojieip** [comment]
我的项目ng-alain 1.3.1 ， ng-zorro-antd 1.7.0， 我查看了ng-alain的demo，在IE也会出现这个问题，这应该与 ng-zorro-antd无关，我单独引入ng-zorro-antd不会出现这个问题。

**Comment by zhaojieip** [comment]
好像是ng-zorro-antd 的问题
