### ISSUE TITLE
修改过login.component.ts, 直接登录后左边的菜单栏不见了，发现没有执行startup.service.ts代码

### ISSUE THREAD

**Issue by YeFei572** [ng-alain/ng-alain#814]
```js
    zip(
        this.httpClient.get(`assets/tmp/i18n/${this.i18n.defaultLang}.json`),
        this.httpClient.get('assets/tmp/app-data.json'),
      )
        .pipe(
          // 接收其他拦截器后产生的异常消息
          catchError(([langData, appData]) => {
            resolve(null);
            return [langData, appData];
          }),
        )
        .subscribe(
          ([langData, appData]) => {}
```

上述代码在修改过login.componet.ts后就不执行了，请问是什么原因呢？

**Comment by YeFei572** [comment]
虽然问的问题很低级, 而且你关闭了我的问题, 但是我还是凭自己摸索出来了, 贴一下问题的原因希望能帮助跟我一样刚入门的朋友:
出现这个问题是因为读json文件的时候被自定义拦截器中的http拦截给截胡了
ng-alain/src/app/core/net/default.interceptor.ts文件中的第96行代码, 规定了只要http请求的地址不是以http://或者https://开头的都要在请求地址上拼接一个SERVER_URL, 而读静态文件下面的那个if正好避过了这个条件并且进入下面的代码. 所以只要在条件里面加一条 !url.startsWith('assets') , 就可以完美避开这个问题
建议在原项目中也加进去, 这不会影像用户正常开发!
正常代码:
```js
 // 统一加上服务端前缀
    let url = req.url;
    if (!url.startsWith('assets') &&!url.startsWith('https://') && !url.startsWith('http://')) {
      url = environment.SERVER_URL + url;
    }
```

**Comment by cipchk** [comment]
> 强烈推荐阅读 [《提问的智慧》](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way)、[《如何向开源社区提问题》](https://github.com/seajs/seajs/issues/545) 和 [《如何有效地报告 Bug》](http://www.chiark.greenend.org.uk/%7Esgtatham/bugs-cn.html)、[《如何向开源项目提交无法解答的问题》](https://zhuanlan.zhihu.com/p/25795393)，更好的问题更容易获得帮助。

并非高冷关掉问题，但请你遵守作者极有限的时间，维护一个项目比开发项目要更花时间，我会认真对待每一个 ISSUES，但前提也先尊重一下你所提的 ISSUES。
