### ISSUE TITLE
STConfig重新配置modal: { size: 'lg' }会导致STColumnButton创建的目标组件接收不到record参数

### ISSUE THREAD

**Issue by DarkGin** [ng-alain/ng-alain#815]
- ng-alain version: 2.0.1
- Angular version: 6.1.10

## 重现步骤，Steps to reproduce
用cli创建的ng-alain项目，delon.module.ts下面69行配置STConfig的地方默认有这段配置：
export function fnSTConfig(): STConfig {
  return Object.assign(new STConfig(), <STConfig>{
    modal: { size: 'lg' },
  });
}
然后我用st组件的STColumnButton放置一个编辑按钮，弹出的模态框的record参数接收不到传入的值，我在编辑模态框用this.modal.getContentComponent()打印出来这个值是放在undefined那里

**Comment by DarkGin** [comment]
![qq 20181212143231](https://user-images.githubusercontent.com/35771250/49851492-32d29100-fe1c-11e8-918a-ce55509a0270.png)

**Comment by cipchk** [comment]
@DarkGin 请提供重现连接。

**Comment by charlee2025** [comment]
@cipchk 我也遇到这样的情况了
重现链接 https://stackblitz.com/edit/angular-fxhvkp?file=src%2Fapp%2Fapp.module.ts
1.点击编辑
2.弹出框的header上，显示不出来id值。

**Comment by charlee2025** [comment]
![qq 20181213161704](https://user-images.githubusercontent.com/8101989/49925105-f3c33f00-fef2-11e8-9292-a49cfe79d515.png)
![qq 20181213162043](https://user-images.githubusercontent.com/8101989/49925158-105f7700-fef3-11e8-88bb-4dedaa61e157.png)

**Comment by charlee2025** [comment]
@cipchk ,已有项目如何修复啊？我看你没有升级版本号

**Comment by cipchk** [comment]
待发布状态，会在本周发布新版本
