### ISSUE TITLE
动态表单 数字输入框

### ISSUE THREAD

**Issue by zhuxm0217** [ng-alain/ng-alain#817]
![image](https://user-images.githubusercontent.com/25685199/49911456-716e5700-fec1-11e8-92f5-d77ff3e3ba0c.png)

**Comment by zhuxm0217** [comment]
![image](https://user-images.githubusercontent.com/25685199/49911530-b72b1f80-fec1-11e8-8f1f-e3e312e36d8c.png)

**Comment by cipchk** [comment]
这里指的是对 `min`、`max`、`step` 强制移除小数点。
