### ISSUE TITLE
How to set another theme to default

### ISSUE THREAD

**Issue by maplye** [ng-alain/ng-alain#82]
I want to set black theme to default theme, how can I do?

**Comment by cipchk** [comment]
[theme.component.ts](https://github.com/cipchk/ng-alain/blob/master/src/app/layout/header/components/theme.component.ts#L41)

**Comment by maplye** [comment]
you mean I can add below code to StartupService?

`this.themeServ.setTheme(theme);
this.settings.setLayout('theme', theme);
`

**Comment by cipchk** [comment]
Binggo

**Comment by maplye** [comment]
thank you very much!

**Comment by 1166544** [comment]
![图片](https://user-images.githubusercontent.com/2033010/62613313-d0df1280-b93b-11e9-8652-a64fbb5a6bda.png)
新版 v8.3.0 移除了 ThemesService? 意味着 
this.themeServ.setTheme(theme); 
this.settings.setLayout('theme', theme); 
用不了了。请问在系统启动时该如何更改默认蓝色主题？
