### ISSUE TITLE
Quick Start not init demo properly 

### ISSUE THREAD

**Issue by miff** [ng-alain/ng-alain#828]
- ng-alain version: 7.0.0-rc.0
- Angular version: 7.1

## 重现步骤，Steps to reproduce
```
ng new demo --style less
cd demo
ng add ng-alain
ng serve -o
```
There is no routes except Dashboard

**Comment by cipchk** [comment]
@miff Yes, Just only provide a clean version for production, can be get full demo pages via `git clone`.
