### ISSUE TITLE
ng g ng-alain: edit 生产页面后无法路由

### ISSUE THREAD

**Issue by askie** [ng-alain/ng-alain#829]
- ng-alain version: 2.0.1
- Angular version: 6.1.10

## 重现步骤
按照文档执行：
```
ng g ng-alain:edit edit -m=sys
或者
ng g ng-alain:crud edit -m=sys
```
浏览器访问：
http://localhost:4200/#/sys/edit
直接跳转至：http://localhost:4200/#/dashboard

如果使用list命令：
```
ng g ng-alain:list a1 -m=sys
或者
ng g ng-alain:empty a2 -m=sys
```
浏览器访问：
http://localhost:4200/#/sys/a1
http://localhost:4200/#/sys/a2
一切正常

**Comment by askie** [comment]
view,edit都是需要通过组件调用的。
不能路由。

**Comment by waitd** [comment]
只有list才能通过路由调用?
