### ISSUE TITLE
关于项目部署

### ISSUE THREAD

**Issue by guccihuiyuan** [ng-alain/ng-alain#83]
我的项目做好以后，该怎么发布到服务器上呢？还有在本地调试的时候，是用的webpack做的转发，发布的时候是要用nginx 来转发吗？

**Comment by cipchk** [comment]
Angular 实际只是若干静态文件，你可以放在任意的 web 服务器（如：nginx）某个站点根目录或任何意思中。

**Comment by cipchk** [comment]
有关更多构建和发布参考[文档](http://ng-alain.com/docs/deploy)。
