### ISSUE TITLE
上一版本导航条取消问题

### ISSUE THREAD

**Issue by lfzx** [ng-alain/ng-alain#830]
我使用的是上一个版本，所以导航条是有的，就像图片中一样。请问应该从哪里设置取消显示？谢谢回答！
![image](https://user-images.githubusercontent.com/34572392/50215590-7306b600-03be-11e9-896e-d5a0e46b1c5c.png)

**Comment by cipchk** [comment]
https://github.com/ng-alain/ng-alain/blob/master/src/app/delon.module.ts#L25

**Comment by lfzx** [comment]
可是我是想彻底清除这一块

**Comment by lfzx** [comment]
非常谢谢！之前因为只修改了delon.module而没有修改default.component.html，所以没有达到预期效果。现在已经解决了
