### ISSUE TITLE
使用rootProperty.setValue为时间组件赋值失败，显示为空

### ISSUE THREAD

**Issue by danxiaogui** [ng-alain/ng-alain#831]
## 版本信息
- ng-alain version: 2.0.0
- Angular version: 6.1.10

### 1 打开此处代码注释，schema加载成功，时间组件赋值成功
> 
![image](https://user-images.githubusercontent.com/22045563/50222499-650f6000-03d3-11e9-9207-cc11c65a95ff.png)
![image](https://user-images.githubusercontent.com/22045563/50222505-6d679b00-03d3-11e9-837e-9d37732417cb.png)

### 2 打开此处代码注释，schema加载成功，使用rootProperty.setValue为时间组件赋值失败
> 
![image](https://user-images.githubusercontent.com/22045563/50222511-76586c80-03d3-11e9-899b-f55de0cdcae1.png)
![image](https://user-images.githubusercontent.com/22045563/50222525-82dcc500-03d3-11e9-989d-5c0d7d749dcb.png)

## 代码
```
import { Component,ViewChild ,OnInit} from '@angular/core';
import { NzMessageService } from 'ng-zorro-antd';
import { STColumn } from '@delon/abc';
import { SFSchema ,SFComponent} from '@delon/form';

@Component({
  selector: 'my-app',
    template: `<sf #sf  [schema]="schema"  [formData]="formData"
    (formSubmit)="submit($event)"
    (formChange)="change($event)"></sf>`,
})
export class AppComponent  implements OnInit {
  
  @ViewChild('sf') sf: SFComponent;

  formData: any = {};
  schema: SFSchema = {
    properties:{},
    ui:{}
  };

  constructor(public msg: NzMessageService) { }

  ngOnInit(): void {

    let tempSchema : SFSchema = {
      properties: {
        datetime: {
          type: 'string',
          format: 'date-time',
        },
        date: {
          type: 'string',
          format: 'date',
        },
      },
      required:['date','datetime'],
      ui:{
        spanLabel:4
      }
    }

    let tempDate = {
      'datetime':'2018-12-19T18:27:20+08:00',
      'date':'2018-11-14',
    }
    
    /**
     * 刷新 Schema 和 formData 没有问题
     */
    //this.schema = tempSchema;
    //this.formData = tempDate;

    /**
     * refreshSchema 刷新Schema表单结构成功
     * rootProperty.setValue 为时间组件初始化值出错,时间组件显示为空
     */
    //this.sf.refreshSchema(tempSchema);
    //this.sf.rootProperty.setValue(tempDate,false);

  }

   submit(value: any) {
     this.msg.success(JSON.stringify(value));
  }

  change(value: any) {
    console.log('change', value);
  }
}
```

**Comment by cipchk** [comment]
https://ng-alain.com/form/getting-started/en#Methods

**Comment by danxiaogui** [comment]
### 根据路径设置值，输入框组件设置成功，时间组件设置失败

![image](https://user-images.githubusercontent.com/22045563/50224495-04832180-03d9-11e9-9146-49a31ee6e284.png)
![image](https://user-images.githubusercontent.com/22045563/50224513-0cdb5c80-03d9-11e9-8e49-e2561e7653d2.png)

**Comment by danxiaogui** [comment]
### 动态表单提供的操作接口中，可以设置值的是这个，但是对时间组件不起作用
![image](https://user-images.githubusercontent.com/22045563/50224711-81160000-03d9-11e9-89c6-0c0854832d50.png)

**Comment by cipchk** [comment]
@danxiaogui, Pls prvoide a clean reproduce demo.

**Comment by danxiaogui** [comment]
OK，I am so sorry
here is the clean reproduce demo [https://stackblitz.com/edit/ng-alain-setup-kuzan-datetime?file=src/app/app.component.ts](url)
thanks.

**Comment by danxiaogui** [comment]
### 版本信息
- ng-alain version: 7.0.0-rc.1
- Angular version: 7.1.4

### [重现地址](https://stackblitz.com/edit/ng-alain-setup-kuzan-datetime-7-0-0-rc1?file=src%2Fapp%2Fapp.component.ts)


##### 我的项目中更新 ng-alain 版本为 7.0.0-rc.1，但是对时间组件的赋值仍然有问题，
##### 以下的代码可以为时间组件赋值，实际上设值成功，但是页面显示为空
    this.sf.rootProperty['properties']['datetime'].setValue('2018-12-19T18:27:20+08:00', false);

##### 需要添加 resetValue 页面才可以将时间显示出来
    this.sf.rootProperty['properties']['datetime'].resetValue('2018-12-19T18:27:20+08:00', true);
    this.sf.rootProperty['properties']['datetime'].setValue('2018-12-19T18:27:20+08:00', false);

**Comment by cipchk** [comment]
@danxiaogui Pls provide a reproduce demo in 7.0.0-rc.1

**Comment by danxiaogui** [comment]
### 版本信息
- ng-alain version: 7.0.0-rc.1
- Angular version: 7.1.4

### [重现地址](https://user-images.githubusercontent.com/22045563/50423473-bc5c7700-0890-11e9-9a00-2c1187a816e3.png)

#### [package.json地址](https://stackblitz.com/edit/ng-alain-setup-kuzan-datetime-7-0-0-rc1?file=package.json)
![image](https://user-images.githubusercontent.com/22045563/50423512-8f5c9400-0891-11e9-81b7-65af12a996f6.png)

### 现在的demo版本是 7.0.0-rc.1，时间组件赋值的问题依旧存在
![image](https://user-images.githubusercontent.com/22045563/50423507-70f69880-0891-11e9-9142-c917f9858573.png)

**Comment by danxiaogui** [comment]
### 我找到一种替代方法，即使用 resetValue 赋值 [复现地址](https://stackblitz.com/edit/ng-alain-setup-kuzan-datetime-7-0-0-rc1-setvalue-date?file=src/app/app.component.ts)

#### 动态表单的时间组件可以使用 resetValue 进行赋值
```
let datas = {
  'datetime': '2018-12-19T18:27:20+08:00',
  'date': '2018-12-19'
}
this.sf.refreshSchema(tempSchema).rootProperty.resetValue(datas,false);
```

#### 也可以对动态表单中单个时间组件进行赋值 resetValue (但是会抛异常)
```
 this.sf.refreshSchema(tempSchema);
 this.sf.rootProperty['properties']['datetime'].resetValue('2018-12-19T18:27:20+08:00', false);
 this.sf.rootProperty['properties']['date'].resetValue('2018-12-19', false);
```
![image](https://user-images.githubusercontent.com/22045563/50425130-b758f100-08ab-11e9-8a0a-3d82a654929d.png)

#### 从我本次测试的结果来说，setValue 方法对时间组件的赋值还是存在问题，实际上已经成功将值设置到时间组件的FormProperty中，但页面上却没有显示出来，或许是我测试有误

**Comment by cipchk** [comment]
事实上这一问题的根治还是只能靠 ng-zorro-antd 全面性支持 ＯｎＰｕｓｈ模式，不再对此问题进一步优化。
