### ISSUE TITLE
ST性能问题

### ISSUE THREAD

**Issue by xioxin** [ng-alain/ng-alain#833]
- ng-alain version: 7.0.0-rc.0
- Angular version: 7.1.3

## 重现连接
https://stackblitz.com/edit/ng-alain-setup-2o7wmf

![image](https://user-images.githubusercontent.com/5716100/50264709-caf0fb80-0456-11e9-8e96-c5e5520cc3ab.png)

![image](https://user-images.githubusercontent.com/5716100/50264898-cbd65d00-0457-11e9-8875-934a85126e6c.png)

## 重现步骤，Steps to reproduce

复杂表格中 点击排序 或 调整窗口大小 会有明显卡顿

如果界面更复杂问题会更严重

**Comment by cipchk** [comment]
简洁回答：ST === Simple Table

> st 并不是在创造另一个表格组件，而是在 nz-table 基础上以可配置形式渲染表格，在中后台里这种方式可以满足绝大多数场景，但又可以更易地管理表格渲染动作。

`st` 本质还是使用 `nz-table` 且受限于目前还未支持 OnPush，虽然  `st` 本身是 OnPush 会尽可能少的重新渲染，因此某种情况下若 `nz-table` 支持 OnPush 也会进一步提升 `st` 性能，但就目前我们运用情况，比你示例中更复杂的示例依然有很好的表现。

此外，`stackblitz` 属于 dev 模式，Zone 的执行任何一个 dev 环境下都差不了太大，而至于内存占用，我建议从优化角度应该从不同环境、机器里得到结果，至少：

![123](https://user-images.githubusercontent.com/2987467/50267051-dba66f00-0460-11e9-8cfd-3b61a8c87bb9.png)
