### ISSUE TITLE
npm run hmr 启动 前端还是会刷新整个页面（闪一下，就把界面清空了）

### ISSUE THREAD

**Issue by jol5** [ng-alain/ng-alain#834]
🚨 Issues 是用于BUG、Feature、进度追踪 🚨
🚨 The issue tracker is not for questions 🚨

如果有任何问题，可在以下方式获得答案：
1.已确定开启hmr，前端终端也输出对应的增量信息；
场景：
     在完整ng-alain项目下：
     1.打开一个表单页面；
     2.在表单中填入一些文字
      3.修改layout的header内容，如github a标签文字 
     预期效果：
     1.增量编译，前端控制台输入增量模块信息
      2.页面只刷新头部，不影响表单部分（表单的文字还在）
    实际效果：
      1.页面整体刷新（闪一下），底下表单的内容也不复存在（在路由复用下，其他标签页会被关闭，只刷新整体）
      2.没有出现初始化的那几个小球加载（表明已经开启了hmr）

2.不是说hmr只刷新对应的模块的吗？怎么又影响整体了
- https://ng-alain.com/
- QQ Group：316911865
- https://segmentfault.com/t/ng-alain

**Comment by cipchk** [comment]
HMR 若想保留数据，需要自己处理，细节见 https://github.com/gdi2290/angular-hmr
