### ISSUE TITLE
reuse-tab  如何让一个菜单多次重复打开

### ISSUE THREAD

**Issue by jol5** [ng-alain/ng-alain#839]
🚨 Issues 是用于BUG、Feature、进度追踪 🚨
🚨 The issue tracker is not for questions 🚨
左侧菜单如果需要重复打开怎么办？不像url路由跳转，可以在url后面贴上唯一id。
如果有任何问题，可在以下方式获得答案：

- https://ng-alain.com/
- QQ Group：316911865
- https://segmentfault.com/t/ng-alain

**Comment by jol5** [comment]
![image](https://user-images.githubusercontent.com/28615922/50397819-e9842900-07ad-11e9-857f-b2de8f12df1c.png)
类似于这样，设置一下下

**Comment by cipchk** [comment]
Not Yet!
