### ISSUE TITLE
树形的图标不正常

### ISSUE THREAD

**Issue by vellengs** [ng-alain/ng-alain#84]
## Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
```

### Mention any other details that might be useful.

![10d789e8-11fb-4ef2-acd4-87fcac3bebec](https://user-images.githubusercontent.com/5743338/33667427-c516376a-dad7-11e7-912f-7af1db73950b.png)

**Comment by vellengs** [comment]
步骤：
$ git clone -b 0.2.0 --depth=1 https://github.com/cipchk/ng-alain.git my-project
$ cd my-project
```
npm install 
npm start
```

**Comment by cipchk** [comment]
请升级 `ng-tree-antd`

**Comment by vellengs** [comment]
@cipchk 
升级了； 2.02 还是一样。 "ng-tree-antd": "^2.0.2",

**Comment by vellengs** [comment]
![aa](https://user-images.githubusercontent.com/5743338/33719505-eeaf0916-db9b-11e7-89e9-11ad96161546.png)

**Comment by vellengs** [comment]
你的演示站的chrome tools 里是 content: "\E606";
我的看到的是 "e606"

**Comment by cipchk** [comment]
请升级 ng-tree-antd

**Comment by vellengs** [comment]
升级到最新了，结果还是一样呢，我哪里搞错了吗？

**Comment by cipchk** [comment]
删除 `node_modules` & `package-lock.json`，`npm install`
OR
`npm install --save ng-tree-antd`

**Comment by vellengs** [comment]
问题是node_modules 里面已经是2.02 版本了。
这个不是最新的  ng-tree-antd 版本吗？

**Comment by vellengs** [comment]
```
删除 node_modules & package-lock.json，npm install
OR
npm install --save ng-tree-antd
```
反复做过多次了结果一样；你能确认下下
content: "\E606" vs  "e606" 的差异吗？

**Comment by vellengs** [comment]
2.0.2 is the latest of 6 releases
我说了已经是 2.0.2 版本了，为什么还让我升级？

**Comment by cipchk** [comment]
https://cipchk.github.io/ng-alain/#/elements/tree-antd
https://cipchk.github.io/ng-tree-antd/
两处都是正常的，我不确定是不是你浏览器本地缓存之类引起的。

**Comment by cipchk** [comment]
@vellengs 抱歉，好像的确有问题，应该是 `\E` 开头才对，但生成的是 `e` 少了 `\`，我得看一下是哪里的原因。

**Comment by cipchk** [comment]
@vellengs 请使用 `npm install --save ng-tree-antd` 升级至 `2.0.4`

**Comment by vellengs** [comment]
可以了
