### ISSUE TITLE
reuse-tab 当超出max个数时，再打开一个新tab，会有问题

### ISSUE THREAD

**Issue by jol5** [ng-alain/ng-alain#840]
- ng-alain version: X.Y.Z
- Angular version: X.Y.Z

## 【必填项】重现链接，Reproduction link
reuse-tab 当超出max个数时，再打开一个新tab，会覆盖一些已经设置了不可关闭的tab，而且切换时，也会发生错乱，延迟。

**Comment by cipchk** [comment]
Pls provide reproduction link.

**Comment by jol5** [comment]
emmm,just like that:
![g 2 pzu 3vky spriwqvmny](https://user-images.githubusercontent.com/28615922/50439322-94225600-092c-11e9-8b4b-c0ed82f00374.png)
