### ISSUE TITLE
希望更多主题菜单

### ISSUE THREAD

**Issue by lc-01010** [ng-alain/ng-alain#843]
![image](https://user-images.githubusercontent.com/38215188/50415674-4ab40700-0857-11e9-95bf-847bcac77ebb.png)
像上面四种默认主题，四种左侧菜单。上面两种目前ng-alain是可以做到的，下面两种不知如何实现？

**Comment by cipchk** [comment]
ng-alain 只是一个脚手架，ng-zorro 提供上百中 less 变量参数，换句话说你可以定制任何出主题的风格（包含上述四种）。

> 后续也会陆续推出不同项目性质的主题。
> 小透露一下：即将发布微服务主题版本。

**Comment by lc-01010** [comment]
> ng-alain 只是一个脚手架，ng-zorro 提供上百中 less 变量参数，换句话说你可以定制任何出主题的风格（包含上述四种）。
> 
> > 后续也会陆续推出不同项目性质的主题。
> > 小透露一下：即将发布微服务主题版本。

感谢ng-alain团队做出的贡献，继续跟随大佬脚步勇往直前。
