### ISSUE TITLE
Cannot find module './utils/yuan'.

### ISSUE THREAD

**Issue by sean-liang** [ng-alain/ng-alain#845]
- ng-alain version: 7.0.0-rc.1
- Angular version: 7.1.4

## 重现步骤，Steps to reproduce

1. ng new webadmin（选择routing与less）
2. cd webadmin
3. ng add ng-alain（默认语言选择English，其他选项都选Y）
4. ng serve

命令行输出：
** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
                                                                                          
Date: 2018-12-26T11:22:12.704Z
Hash: 82102e00b1e81e831d2e
Time: 22144ms
chunk {main} main.js, main.js.map (main) 1.9 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 92.4 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.08 kB [entry] [rendered]
chunk {scripts} scripts.js, scripts.js.map (scripts) 1.26 MB  [rendered]
chunk {styles} styles.js, styles.js.map (styles) 2.34 MB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 322 kB [initial] [rendered]

ERROR in src/app/shared/index.ts(4,15): error TS2307: Cannot find module './utils/yuan'.

**Comment by FlowPeakFish** [comment]
ng add ng-alain
这样添加并没有添加这一块
1、删除这一行代码，自然不会报错
2、手动在./utils/下，创建yuan.ts
可以从这个路径复制内容
https://github.com/ng-alain/ng-alain/blob/master/src/app/shared/utils/yuan.ts
