### ISSUE TITLE
多tab情况下  G2图表问题

### ISSUE THREAD

**Issue by wulaiwei** [ng-alain/ng-alain#851]
- ng-alain version: 1.4
- Angular version: 6

#
问题发生再多tab下
![image](https://user-images.githubusercontent.com/16910820/50534416-3d5c8c80-0b77-11e9-91de-be54ddcaaf8d.png)

![image](https://user-images.githubusercontent.com/16910820/50534409-2b7ae980-0b77-11e9-9064-24e3b0849c17.png)

## 重现步骤，

假如存在两个Tab  Tab A  存在图表   然后新开TabB  接着浏览器窗口大小发生变化后  再切换至TabA  图表就出现图中问题

**Comment by cipchk** [comment]
参考 ng-alain 示例的解法：[analysis.component.html](https://github.com/ng-alain/ng-alain/blob/master/src/app/routes/dashboard/analysis/analysis.component.html#L208)

主要原因是 nz-tab 的渲染方式会使得所有 g2 容器无法正常的获取到高度值。

**Comment by xLong1029** [comment]
> 参考 ng-alain 示例的解法：[analysis.component.html](https://github.com/ng-alain/ng-alain/blob/master/src/app/routes/dashboard/analysis/analysis.component.html#L208)
> 
> 主要原因是 nz-tab 的渲染方式会使得所有 g2 容器无法正常的获取到高度值。

遇到类似的问题，但不是出现在Tab中，而是路由切换下。
A/B路由都存在图表，从A路由跳转至B路由，浏览器窗体大小发生变化后，再切换至A路由，就会出现图表不显示或者错乱的问题，仔细看了一下，Canvas标签中width属性为NaN，获取不到宽度大小

stackblitz出了部分问题，一直提示“Can't find package:date-fns”缺少依赖包，安装了也没用，非常抱歉，无法提供有效链接。
问题示例图如下：

![G2图表问题](https://user-images.githubusercontent.com/18066675/64680535-8d367600-d4b0-11e9-96c7-10324e99dae8.gif)
