### ISSUE TITLE
使用upload上传图片的服务器接口

### ISSUE THREAD

**Issue by dayhi** [ng-alain/ng-alain#858]
前台代码

edit.component.ts
```
cImg: {
        type: 'string',
        title: '图标',
        enum: [],
        maxItems: 1,
        minItems: 1,
        ui: {
          widget: 'upload',
          action: 'uploadimg',
          resReName: 'resource_id'
        },
      }
```

后台uploadimg接口返回
```
resource_id: 15464130
url: "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png"
```

是返回的格式有问题吗？此时图片无法预览，点击请求的地址是/undefined

**Comment by dayhi** [comment]
并且图片对象没有添加到enum。添加的动作监听change事件来完成？

**Comment by dayhi** [comment]
html
![image](https://user-images.githubusercontent.com/18325669/50585736-63549a80-0eb1-11e9-8a7f-e96510e45766.png)

ts
![image](https://user-images.githubusercontent.com/18325669/50585774-939c3900-0eb1-11e9-8644-87efa47b79ff.png)

接口返回格式
![image](https://user-images.githubusercontent.com/18325669/50585803-b0387100-0eb1-11e9-8269-2946bed078b3.png)

问题：
接口返回后点击按钮下方的图片名，弹出窗口
![image](https://user-images.githubusercontent.com/18325669/50585857-e118a600-0eb1-11e9-83a6-241e74962b56.png)
发现访问地址为http://localhost:4200/undefined

**Comment by cipchk** [comment]
预览需要保证 File 对象中的 `url` 或 `thumbUrl` 两个参数其中之一有数据，建议通过 `change` 事件，在上传成功后根据后端返回的数据重新指定 File 对象的 `url` 或 `thumbUrl` 参数之一。

**Comment by dayhi** [comment]
谢谢帮助，这个问题解决了

**Comment by ayaka209** [comment]
看似有点小问题
```
    change :(args: UploadChangeParam) => {
        if(args.type == "success"){
          args.fileList[0].url = args.file.response.location;
          args.fileList[0].thumbUrl  = args.file.response.location;
        }
        console.log(args);

    }
```
这样设置fileList里面的对象是可以的
但是直接设置args.file的url和thumbUrl是不行的
这中间存在着多个file对象是吗，我注意到多次change回调（start, progress, success)之间，他们的file对象都不是同一个实例

**Comment by cipchk** [comment]
@ayaka209 是的，因为列表是由 `fileList` 决定的。
