### ISSUE TITLE
sf visibleIf 函数调用多次

### ISSUE THREAD

**Issue by winds1987** [ng-alain/ng-alain#859]
- ng-alain version: 7.0.0-rc.3
- Angular version: 7.1.0

visibleIf 函数多次调用，且只有最后一次 value有值，其余调用时，value=null
ui schema:
$no: {
      widget: 'text',
      // hidden: true,
      visibleIf: {
        callNo: (value: any) => {
          console.log("visibleIf callNo value:", value)
          return value > 0
        }
      }
    },

对话框模式显示时，log:
visibleIf callNo value: null
visibleIf callNo value: 841

**Comment by winds1987** [comment]
##重现链接
Reproduction link
https://stackblitz.com/edit/ng-alain-setup-hz7odw?file=src%2Fapp%2Fapp.component.ts

##重现步骤
加载页面后出现
![ngalain_bug](https://user-images.githubusercontent.com/9546433/50587058-520e8c80-0eb7-11e9-9b30-ec47a59e356b.jpg)

**Comment by cipchk** [comment]
so?

**Comment by winds1987** [comment]
无效啊

**Comment by cipchk** [comment]
抱歉，实在无法理解你需要我帮助你什么。再次感谢关注 ng-alain。

**Comment by winds1987** [comment]
由于这个方法执行多次，而且首次执行时，传递进去的参数 value 为 null，会导致这个方法里面出现逻辑错误，从而导致这个 visibleIf属性无效。

**Comment by logan2013** [comment]
我也遇到这个问题
