### ISSUE TITLE
想让工作区的表格铺满全屏，怎样实现高度自适应？

### ISSUE THREAD

**Issue by dusdong** [ng-alain/ng-alain#86]
## Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```
比如示例的门店页面，想让工作区的门店表格的高度自适应铺满工作区，该如何实现？谢谢~

**Comment by cipchk** [comment]
能否上图表述一下你具体的需求？

**Comment by dusdong** [comment]
如图所示，我在系统的查询窗口使用了 kendo-ui 的grid控件。查询数据量一般都比较大，需要进行分页显示，故提供了每页行数的选择项。

现状：在每页显示10行的情况下，下面有很大的空余；在每页显示20行的情况下，需要拖动页面的滚动条，就会看不到顶部的表格标题及操作按钮等，不方便。

需求：如果能将表格自动铺满工作区，在显示20行数据的情况时，就可以拖动表格本身的滚动条了，不浪费显示空间又可以保留表格标题及操作按钮的显示。

![1](https://user-images.githubusercontent.com/3461709/33700796-4691551c-db56-11e7-9ebf-f34784225225.png)
![2](https://user-images.githubusercontent.com/3461709/33700819-5fc31cbe-db56-11e7-8f59-ad1c634a69c7.png)

**Comment by cipchk** [comment]
复杂表格页面对种需求的确很常见。要解决这个问题，我想到的至少要有几下几点需要处理：

+ 强制设置 `body` 为无滚动条
+ 内容区域需要有一个宽高 `100%` 的容器

然而，这里还有另一个问题需要解决，那就是 grid 控制是否会自适应，否则一但侧边栏缩进后，右边会出现新空白。

我建议，现在只能由你当上述需求，自行写一个这样的组件，去处理这几个细节。

有关更多细节上欢迎进一步讨论，若有可能会将组件并入 `@delon/abc` 当中。

**Comment by dusdong** [comment]
按照您的提示我测试了下，如果在内容区设置一个宽高100%的容器，容器内部放置height=100%的table，就可以实现该需求。可是，我参照google写的宽高100%的容器总是各种问题。

故，求一个宽高100%的容器的写法~谢谢！

**Comment by dusdong** [comment]
```
<pro-header></pro-header>
<div style="
    background: #D9C666;
    position: absolute;
    height: calc(100% - 270px);
">
   <table></table>
</div>
```

这是我写的，高度没问题，宽度无法自适应。

![3](https://user-images.githubusercontent.com/3461709/33707263-d8da76cc-db71-11e7-9fb4-422bc145b26d.png)
![4](https://user-images.githubusercontent.com/3461709/33707289-e6914778-db71-11e7-9b80-fcdc637e100e.png)

**Comment by dusdong** [comment]
实现了一个简易版的指令。因为 kendo-grid 是 flex 布局的，直接将其height设为 100% 会无视顶部的  form 控件。 故需要在调用时写入扣减的高度。
代码如下：
```
import { ElementRef, Directive, Input } from '@angular/core';

@Directive({
    selector: '[autoHeight]'
})

export class AutoHeightDirective {

    private height = 0;

    // 扣减grid顶部占用的空间大小
    @Input() autoHeight: number;

    constructor(public element: ElementRef) {
    }

    ngAfterContentChecked(): void {
        this.adjust();
    }

    adjust(): void {
         if (this.height <= 0) {
            const aside = document.getElementsByClassName('aside-inner');

            // 50 是 pro-header 的高度；32 是 @content-padding 的值x2
            this.height = aside.item(0).clientHeight - 50 - 32 - this.autoHeight;

            this.element.nativeElement.style.height = this.height + 'px';
        }
    }
}

```
页面使用：
```
<pro-header>
</pro-header>
<div autoHeight="40">
     <form>...</form>
     <kendo-grid [style.height.%]="100">...</kendo-grid>
</div>
```
使用效果：
![1](https://user-images.githubusercontent.com/3461709/33749193-65b8aa56-dc07-11e7-9348-86df52b57e84.png)
![2](https://user-images.githubusercontent.com/3461709/33749304-f6771604-dc07-11e7-800a-db35b9bb81e5.png)

**Comment by ithan945** [comment]
ng-Alain怎么实现h5网页自适应
