### ISSUE TITLE
打包报错,应该是内存的问题问题,内存有810M左右

### ISSUE THREAD

**Issue by zhouhuiquan** [ng-alain/ng-alain#860]
- ng-alain version: 7.0.0-rc.3
- Angular version: 7.1.4

## 【必填项】重现链接，Reproduction link

![image](https://user-images.githubusercontent.com/33424719/50595668-513c2180-0edc-11e9-8846-807a9c288ddc.png)

## 重现步骤，Steps to reproduce

npm run build

之后就出现了

**Comment by cipchk** [comment]
尝试把 `ng build` 替换成 `node --max_old_space_size=8000 ./node_modules/@angular/cli/bin/ng build`

**Comment by zhouhuiquan** [comment]
@cipchk 看样子你们也注意到这个问题了,这样也解决了,但是不是生产环境打包,vender文件太大了,有将近10M

**Comment by cipchk** [comment]
@zhouhuiquan  往根源上来说这个问题实际上是 node 的问题，Angular 在 AOT 时的确会根据项目大小很吃内存，目前除了利用 `max_old_space_size` 给 Node 环境更大的内存好像没有更好的办法。
