### ISSUE TITLE
sf的upload小部件上传成功提示'不应少于 1 个项'

### ISSUE THREAD

**Issue by dayhi** [ng-alain/ng-alain#862]
![image](https://user-images.githubusercontent.com/18325669/50626706-c2c2b100-0f6a-11e9-8471-7efd4c125594.png)

代码是:
![image](https://user-images.githubusercontent.com/18325669/50626720-d53cea80-0f6a-11e9-8722-0c6b241b56cb.png)

**Comment by dayhi** [comment]
无法重现吗？上传成功之后服务器返回
![image](https://user-images.githubusercontent.com/18325669/50627310-e509fe00-0f6d-11e9-9acf-e14c86e90fd6.png)


处理后100%出现提示不应少于1个项，同时提交按钮不能按

**Comment by dayhi** [comment]
依然无法重现吗

**Comment by cipchk** [comment]
尝试去掉 `enum: []`
