### ISSUE TITLE
自定义表单验证，一个input变化影响另外一个input的valid状态

### ISSUE THREAD

**Issue by Evelyn523** [ng-alain/ng-alain#864]
如题，需要做出两个输入框 其中一个必填的效果，如何在
 ui: {
      validator: (value: any, formProperty: FormProperty, form: PropertyGroup) => { }
}
这个里面去控制另外一个input的状态呢

**Comment by cipchk** [comment]
没有直接办法，内部检查是以 `errorChange` 为准，目前也没有相应公共可以直接完成（虽然透过一些不合理的方式可以实现）。
