### ISSUE TITLE
上传文件的组件，是否可以拿到用户上传文件的真实文件名称和扩展名

### ISSUE THREAD

**Issue by joseph830727** [ng-alain/ng-alain#866]
🚨 Issues 是用于BUG、Feature、进度追踪 🚨
🚨 The issue tracker is not for questions 🚨

如果有任何问题，可在以下方式获得答案：

- https://ng-alain.com/
- QQ Group：316911865
- https://segmentfault.com/t/ng-alain

**Comment by cipchk** [comment]
https://ng.ant.design/components/upload/zh
