### ISSUE TITLE
Perforamnce issue on g2-bar

### ISSUE THREAD

**Issue by lovelangy** [ng-alain/ng-alain#867]
- ng-alain version: X.Y.Z
- Angular version: X.Y.Z

## Reproduction link
https://ng-alain.github.io/ng-alain/#/dashboard/analysis

## Steps to reproduce

1, Open https://ng-alain.github.io/ng-alain/#/dashboard/analysis
2. You will see  "Stores Sales Trend" bar chart
3, Click "Visits"  to swith to "Visits Trend",  it takes more than 10 seconds to render bar chart.

Notes:  If you press F12 to enable chrome developer tool or close if you already open the  developer tool.   the "Visits Trend" bar chart will be rendered imediatelly.   it looks that it needs mannually "trigger" the UI change.

**Comment by cipchk** [comment]
You are right. or used [delay](https://ng-alain.com/chart/bar/en#g2-bar) property delay rendering g2-bar.
