### ISSUE TITLE
npm run build is slow

### ISSUE THREAD

**Issue by lyc152** [ng-alain/ng-alain#87]
## Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
```
在 执行 npm run build 的时候 ，发现速度比较慢，执行完大概耗时8-10分钟，请问碰到过这个问题吗？

**Comment by cipchk** [comment]
+ 固态硬盘吗？
+ `cnpm` 安装吗？

**Comment by lyc152** [comment]
我本地用的mac，固态硬盘, cnpm可以安装,上生产运维 不允许 cpm 可以有其他解决方法吗, 另外 我发现在 92% chunk asset optimization 95% emitting 这个阶段花的时间最多
Date: 2017-12-08T04:07:22.199Z
Hash: cae9287fd28b64d207ce
Time: 288716ms

**Comment by cipchk** [comment]
我也不清楚，抱歉。现在 ng-alain 的 cli 用的是最新版本，虽然老早之前有类似这种BUG，但是已经很久以前的问题了，早就修复了。

**Comment by lyc152** [comment]
多谢，我再研究下
