### ISSUE TITLE
很抱歉，沒有看到哪里修改sidebar

### ISSUE THREAD

**Issue by SWMLee** [ng-alain/ng-alain#873]
如題，沒有找到修改sidebar列表的，地方

**Comment by cipchk** [comment]
你想修改什么？

**Comment by SWMLee** [comment]
我看到sidebar.component.html文件中有使用<sidebar-nav class="d-block py-lg"></sidebar-nav>，但是里面的東西不知道在哪里

**Comment by SWMLee** [comment]
@cipchk 我看到sidebar.component.html文件中有使用<sidebar-nav class="d-block py-lg"></sidebar-nav>，但是里面的東西不知道在哪里

**Comment by cipchk** [comment]
https://ng-alain.com/components/sidebar-nav/
