### ISSUE TITLE
建议：增加ST控件的简单聚合功能

### ISSUE THREAD

**Issue by insov** [ng-alain/ng-alain#874]
ST控件现在没有每行汇总的功能，实际业务需求中经常会遇到。

查看ST的API，发现有一个这种的属性
![image](https://user-images.githubusercontent.com/3804453/51011458-91159f80-1593-11e9-802e-741d9b2918c7.png)

文档中没有描述这个  TemplateRef 的格式。

我建了一个stackblitz.
https://stackblitz.com/edit/angular-hmjzxn

示例中，汇总行需要显示的内容： 医院列显示合计多少条，在金额列中显示合计多少金额。
实际业务的需求列会更多，需要合计的列也会很多。

**Comment by cipchk** [comment]
主要利用 `process` 与 `body` 结合，一个示例：https://stackblitz.com/edit/angular-hmjzxn-wjq6gm?file=src%2Fapp%2Fapp.component.ts

> 可以考虑增加一个简单的聚合能力。

**Comment by insov** [comment]
谢谢，这个确实解决了问题。
推荐可以将这个配置加入到STColumn中，实现常用的 总条数、合计、最大最小值
