### ISSUE TITLE
page-header当在ipad中显示变形

### ISSUE THREAD

**Issue by liuyun521** [ng-alain/ng-alain#875]
- ng-alain version: 7.0.0-rc.1
- Angular version: 7.1.4
## 【必填项】重现链接，
https://ng-alain.github.io/ng-alain/#/pro/profile/advanced

![image](https://user-images.githubusercontent.com/9554224/51040264-f7310f80-15f1-11e9-9e7d-2155da8a8d56.png)

重现步骤
1.进入链接
2.按f12
3.设备选择ipad

**Comment by cipchk** [comment]
`<768` 屏幕会被当成二行，本来就是这样设计的，没毛病。:)
