### ISSUE TITLE
关于 F5 刷新后，导航菜单 ACL 访问控制会失效

### ISSUE THREAD

**Issue by dusdong** [ng-alain/ng-alain#88]
## Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

```
this.aclService.setFull(false);
this.aclService.setRole(roles);
this.menuSrv.resume();
```
在用户登录窗口，通过上述语句可以实现导航菜单的隐藏，但F5刷新后，导航菜单会全部显示出来，控制失效。

是否应该在layout组件中保存导航菜单的ACL控制状态？

**Comment by cipchk** [comment]
F5刷新后自然Angular项目重新加载，自然所在内存的数据都会丢失，但是我想你的用户登录token是存在 localStorage 里面，从感观上来说像是不需要重新登录，但实际值是从 localStoarge 再获取一次。同样的道理 acl 也是如此。

建议在 `startup` 当中对重新刷新一遍。

**Comment by dusdong** [comment]
收到，在 startup 中设置后 OK

**Comment by baiyunchen** [comment]
Role放到LocalStorage中未必合适。理由如下：
Token是一串加密的字符，放到LocalStroage中，用户乱改也很难改成另外一个用户的Token，除非是另外一个用户的Token泄漏。
但是角色的名称一般是比较固定的，用户是有可能能猜测到的，猜到之后，就可以自己给自己加个比较大的权限了
虽然API端也需要验证权限，但是这样的前端实现显然安全上是有点小问题的，个人感觉每次都从API端重新取权限比较好~

**Comment by Gyyyang** [comment]
@dusdong 我现在两年后也遇到这个问题了，请问这个怎么解决的呢，如何在刷新后重新执行startup呢？如果您看到消息，望赐教

**Comment by devilmay5** [comment]
同问 文档并没有明确写出该如何处理 代码中的案例也并不明确提示 请问该如何解决呢 @dusdong

**Comment by wangkailun** [comment]
同问，2022年也遇到同样的问题,在刷新之后role会被清空，ACL权限只可以在startup里面设置吗？因为项目要整合公司内部的登录验证接口，没办法在startup页面获取角色权限。

**Comment by cipchk** [comment]
> 同问，2022年也遇到同样的问题,在刷新之后role会被清空，ACL权限只可以在startup里面设置吗？因为项目要整合公司内部的登录验证接口，没办法在startup页面获取角色权限。

也可以在内部登录后将ACL权限存储在 locatStorage 当中，在 startup 内加载优先加载它就行。

**Comment by devcui** [comment]
一般是后台做缓存策略，框架的加载过程可以想象成一种  事件流  过程，例如

->  platformBrowserDynamic.bootstrapModule() -> ..... -> startupService -> loadMenu(存到运行时的变量中) -> loadUser(存到运行时的变量中) -> loadRole(存到运行时的变量中) -> load基础数据(存到运行时的变量中) -> startup.resolve() -> preloaderFinish()

其中(存到运行时的变量中)可以替换成(如果缓存有，拿缓存中的，如果没有，发请求，存到运行时的变量中)

整体是一个动态的加载，除了借助cacheService进行localStorage缓存，其余时间是无(暂存)状态的，F5 就回到了 流 的原点，重新执行这个过程

**Comment by wangkailun** [comment]
今天我也想到利用cacheService将roles保存到localStorage中，然后在startup中重新加载roles，目前问题已经解决。感谢卡色贡献了这么优秀的框架。 @cipchk
