### ISSUE TITLE
大页面滚动时 rendering时间过长

### ISSUE THREAD

**Issue by mikeyreilin** [ng-alain/ng-alain#880]
![qq 20190116101206](https://user-images.githubusercontent.com/26787043/51222187-9ef26880-1977-11e9-8bfb-54020e367711.png)
大概十几个表单的长页面，在谷歌浏览器下面，滚动时rendering时间过长，明显觉得卡顿。
同一个页面在火狐浏览器下，滚动流畅

**Comment by cipchk** [comment]
打开 Rendering 面板，可以跟踪到哪些元素在滚动时会被重新渲染。

**Comment by mikeyreilin** [comment]
> 打开 Rendering 面板，可以跟踪到哪些元素在滚动时会被重新渲染。

![qq 20190116105323](https://user-images.githubusercontent.com/26787043/51223505-fcd57f00-197c-11e9-939b-517eded38653.png)
貌似是这些，感觉很奇怪

**Comment by mikeyreilin** [comment]
> 打开 Rendering 面板，可以跟踪到哪些元素在滚动时会被重新渲染。

![qq 20190116105323](https://user-images.githubusercontent.com/26787043/51223587-5473ea80-197d-11e9-9ecb-1066f8a97d0c.png)
应该是这些。感觉比较奇怪
