### ISSUE TITLE
prod 模式下,使用   @ViewChild(STComponent)   simpleTable: STComponent 获取pi 报错

### ISSUE THREAD

**Issue by danranVm** [ng-alain/ng-alain#883]
- ng-alain version: 2.0.1
- Angular version: 6.1.10

## 【必填项】重现链接，Reproduction link
![image](https://user-images.githubusercontent.com/25052421/51454357-37755800-1d7f-11e9-9051-9bb655f8fe82.png)
- 由于dev 模式下不会复现，无法提供复现链接,所以提供下面部分代码：
```ts
export class MyComponent implements OnInit {
  @ViewChild(STComponent)
  simpleTable: STComponent
  columns: STColumn[] = [
    { title: '客户简称', index: 'corpShortName' }
  ]
  ngOnInit() {
      console.log(this.simpleTable.pi)
  }
```
- 1.5.2版本没有这个问题的，升级到2.0.1后出现。

**Comment by cipchk** [comment]
https://angular.io/guide/lifecycle-hooks

**Comment by danranVm** [comment]
@cipchk 那为什么 我换成  `@ViewChild('simpleTable')  ` 同时在模板里使用`  <st
    #simpleTable></st>`就能获取到呢？  求解答。我之前一直是这么用的。

**Comment by danranVm** [comment]
我刚刚又去看了下 delone 中 st 的源码，发现 pi 在constructor 中就是有一个默认值的。
那么按照我对生命周期的理解，执行顺序应该是这样的。
- parent 组件的 constructor 执行，绑定了 ViewChild
- st 组件的 constructor 执行，此时 pi就有值了。
- parent 的 onInit 执行。 在父组件里获取 st的 pi 按理应该有值才对。

但是现在的情况就是 `@ViewChild(STComponent)` 报错  `@ViewChild('simpleTable')` 正常获取
- emmmmmm  写到这里 ，我大概知道了。应该就是 `@ViewChild(STComponent)` 在 parent 组件的`OnInit`阶段 还没有拿到 st 组件的对象。。。😭

**Comment by danranVm** [comment]
可是为什么上个版本 ng-alain 1.5.2 可以。  这个错误是升级到 2.0.1 才出现的。😭
