### ISSUE TITLE
menu  externalLink  suggest

### ISSUE THREAD

**Issue by dangzhenghui1985** [ng-alain/ng-alain#886]
关于菜单配置里面外部链接改进的建议 目前是弹出新窗口。往往我们想要的是在这个框架里显示外部链接内容。
比如：
![image](https://user-images.githubusercontent.com/16914422/51467852-7ec40e80-1da8-11e9-986c-f07de597ffed.png)
![image](https://user-images.githubusercontent.com/16914422/51467895-99968300-1da8-11e9-820d-09058b2be2f5.png)
![image](https://user-images.githubusercontent.com/16914422/51467977-cea2d580-1da8-11e9-8171-2fa7e1df3210.png)

这些都是第三方页面要集成到这个里面使其页面更加灵活
目前我的实现方式是新增一个公共页面
![image](https://user-images.githubusercontent.com/16914422/51468089-0a3d9f80-1da9-11e9-97b4-fda1cfdadcd5.png)
通过Iframe
![image](https://user-images.githubusercontent.com/16914422/51468137-2ccfb880-1da9-11e9-93b0-cfba0a946b43.png)
![image](https://user-images.githubusercontent.com/16914422/51468166-3fe28880-1da9-11e9-8f4c-cd9d8af094c3.png)
渲染出来的页面。是否可以有更好的实现方式可以原生支持下？用 externalLink  这个或者inerexternalLink  这样原生支持下。

**Comment by cipchk** [comment]
ng-alain 不推荐项目中使用 iframe。
