### ISSUE TITLE
Error On initl project  No matching version found for ng-alain-codelyzer@DEP-7.0.0-rc.5

### ISSUE THREAD

**Issue by seebosmile** [ng-alain/ng-alain#888]
Error On initl project

ng new demo --style less
ng add ng-alain --defaultLanguage=en

....
npm ERR! code ETARGET
npm ERR! notarget No matching version found for ng-alain-codelyzer@DEP-7.0.0-rc.5
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'demo2'
npm ERR! notarget

**Comment by cipchk** [comment]
duplcate of https://github.com/ng-alain/delon/pull/401, it's my mistake.

> A simple solution, manually modify the version number of ng-alain-codelyzer to `^0.0.1` and run yarn again
