### ISSUE TITLE
tree-select  内容太多 是否可以自动添加滚动条

### ISSUE THREAD

**Issue by hennychen** [ng-alain/ng-alain#890]
- "ng-alain": "^2.0.1",
- Angular version: 
"@angular/animations": "^6.1.0",
    "@angular/common": "^6.1.0",
    "@angular/compiler": "^6.1.0",
    "@angular/core": "^6.1.0",
    "@angular/forms": "^6.1.0",
    "@angular/http": "^6.1.0",
    "@angular/platform-browser": "^6.1.0",
    "@angular/platform-browser-dynamic": "^6.1.0",
    "@angular/router": "^6.1.0",

## 【必填项】重现链接，Reproduction link
![3b2kw 1t p1oaf6a98 fp](https://user-images.githubusercontent.com/2526830/51515798-0ca70480-1e50-11e9-8e7a-6a7586b27260.png)

## 重现步骤，Steps to reproduce
tree-select  内容太多 在弹出框 是否可以自动添加滚动条

**Comment by cipchk** [comment]
closed by https://github.com/ng-alain/ng-alain/issues/893
