### ISSUE TITLE
希望 se 组件支持 [labelWidth]

### ISSUE THREAD

**Issue by danranVm** [ng-alain/ng-alain#892]
`se` 的前身 `shf-item` 是支持的，升级 2.0 后反而移除了，是出于什么原因呢?  
类似的组件 `sv` 也是支持的。

**Comment by cipchk** [comment]
`sv` 是文档的错误，为什么需要在 `se` 中使用 `labelWidth`，能否提供一种为什么需要的场景？

**Comment by danranVm** [comment]
```html
<form nz-form [formGroup]="form" se-container="5" labelWidth="100">
  <se label="省份">
    <input nz-input formControlName="provinceNameLike" />
  </se>
  <se label="地级市名">
    <input nz-input formControlName="prefectureNameLike" />
  </se>
  <se label="县级市名">
    <input nz-input formControlName="countyNameLike" />
  </se>
  <se labelWidth="0">
    <label nz-checkbox formControlName="onlyPrefecture">只查看地级城市</label>
  </se>
  <se labelWidth="0">
    <label nz-checkbox formControlName="onlyCounty">只查看县级城市</label>
  </se>
</form>
```

目前我的一个场景 就是查询条件中有两个是 `checkbox` 文本会比较超长 所以我想把 `labelWidth` 设置为0

**Comment by cipchk** [comment]
@danranVm 这样会破坏整体表单的对齐，我不觉得这是一个好主意。虽然 `labelWidth` 很简单可以增加，但是破坏对齐并不是一个好设计。

**Comment by danranVm** [comment]
@cipchk 我现在理解了你移除 `labelWidth ` 的原因。 
但是实际开发场景中还是有这样的需求的，如果不提供这个属性的支持，那么我只能通过修改样式的方式去实现，会稍微麻烦一些。
- 我还是希望 `se` 和 `sv` 支持 `labelWidth `，因为这对于使用者来说多了一个选择，虽然这是一个不太好的设计，但是它确实便利了使用者。
- 如果你决定 `se` 和 `sv` 不再支持 `labelWidth ` ,我表示理解和接受。不过由于 1.x 是支持的，所以这算是 `Breaking Changes `,应该在升级文档中体现一下。

**Comment by cipchk** [comment]
@danranVm 可以自行增加一个通用样式

```less
.hide-label {
  .sv__label,
  .se__label {
     display: none !important;
  }
}
```

对于 `se`、`sv` 则：

```html
  <se class="hide-label">
    <label nz-checkbox formControlName="onlyCounty">只查看县级城市</label>
  </se>
```

`se`、`sv` 依然克制不增加相应属性。

**Comment by visionding** [comment]
@cipchk 我也碰到有这个需求，在稍复杂的表单中，很多字段的排列并不规则，有些字段标签文本稍长或者没有标签的话需要单独设置labelWidth，横向排列的时候也并不影响美观。ElementUI的form有类似的设计，el-form上的label-width可以被el-form-item上的label-width覆盖
