### ISSUE TITLE
当formGroup调用markAsDirty和updateValueAndValidity，需要执行两次才能触发se的校验。

### ISSUE THREAD

**Issue by zdxxxxxx** [ng-alain/ng-alain#899]
- ng-alain version: latest
- Angular version: latest

## 【必填项】重现链接，
https://stackblitz.com/edit/ng-alain-setup-fysykj?file=src%2Fapp%2Fapp.module.ts

## 重现步骤，
需要点击两次提交，se才能提示错误

**Comment by cipchk** [comment]
maybe duplcated of #897

**Comment by zdxxxxxx** [comment]
It looks like a same problem. But it still occured in current version. How to fix it？
