### ISSUE TITLE
每个模块或者组件的service应该放在哪个文件夹？

### ISSUE THREAD

**Issue by ZeyZhang** [ng-alain/ng-alain#9]
这种文件结构，每个模块或者组件的service应该放在哪个文件夹，都放在core文件里吗？

**Comment by cipchk** [comment]
@ZeyZhang 取决于你的需要，一般 `core` 表示在整个模块树中有效。倘若你的 Service 可能只是在某个模块中运用的，只需要放在相应模块中的 `services` 文件夹中；这样的结构才更合理。

**Comment by ZeyZhang** [comment]
好的，感谢
