### ISSUE TITLE
preserveWhitespaces导致ng-zorro的transfer组件按钮错位

### ISSUE THREAD

**Issue by hongkz** [ng-alain/ng-alain#900]
- ng-alain version: 2.0.1
- Angular version: 6.1.10

## 【必填项】重现链接，Reproduction link

Stackblitz模板：https://stackblitz.com/edit/ng-alain-setup-np1xr1

正常情况：
![image](https://user-images.githubusercontent.com/11613879/52691691-9b64f800-2f9c-11e9-868f-a571a624f9cd.png)

异常情况：
![image](https://user-images.githubusercontent.com/11613879/52691854-1fb77b00-2f9d-11e9-8a56-a90eda6a6c02.png)

是否是因为开启了preserveWhitespaces后为两个连续的button加了margin-left:8px，没有考虑button是上下排列的情况呢，谢谢！

**Comment by hongkz** [comment]
补充重现链接：
https://stackblitz.com/edit/ng-alain-setup-np1xr1

**Comment by cipchk** [comment]
请尝试更新至最新版本

**Comment by hongkz** [comment]
> 请尝试更新至最新版本

2.0.1是稳定版中的最新版本了，您是指从2.0.1更新至7.0.0-rc.6？

**Comment by cipchk** [comment]
是的，2与7只是版本号的变更，目前没有什么破坏性变更，一直rc版本主意原因是保持ng-zorro-antd的rc版本，会在其正式候跟随。

**Comment by hongkz** [comment]
您好，更新了版本之后，还是有错位的现象。我是修改了package.json里面的ng-alain版本号为rc6之后重新构建的。
