### ISSUE TITLE
封装ng-zorro-mobile？

### ISSUE THREAD

**Issue by xingkoo** [ng-alain/ng-alain#904]
delon对ng-zorro进行的封装，使用起来非常方便，特别是动态表单的功能。
现在ng-zorro-mobile也发布很久了，有没有考滤进行封装？
希望在ionic中使用ng-zorro-mobile的时候，可以有动态表单之类的功能可以使用。

**Comment by cipchk** [comment]
ng-alain 定位在PC端的中后台，目前没有对移动端支持的打算。
