### ISSUE TITLE
Can't create new ng-alain page on windows

### ISSUE THREAD

**Issue by AyozeM** [ng-alain/ng-alain#907]
- ng-alain version: 7.0.0
- Angular version: 7.2.5
- Angular CLI: 7.3.1
- Node: 10.15.0
- OS: win32 x64 (Windows 10)

## 重现步骤，Steps to reproduce
* Create new module
* Try to create new  page.

I tried to execute it with Powershell and CMD, both with admin permissions

![image](https://user-images.githubusercontent.com/26739636/53020089-8550af00-3456-11e9-9a7c-7db357d74883.png)

**Comment by cipchk** [comment]
everything is working in latest version (`7.0.0-rc.8`)

![image](https://user-images.githubusercontent.com/2987467/53024162-717a6c80-3499-11e9-98f0-febab4288e03.png)

![image](https://user-images.githubusercontent.com/2987467/53029345-97a50a00-34a3-11e9-82a2-f83553567ebc.png)

there appeared to be nothing exception error, can you debug the `buildAlain` method of the `node_modules/ng-alain/utils/alain.js` file? although this is a very troublesome way, i can't have better advice.
