### ISSUE TITLE
使用st表单控件采用change方式排序问题

### ISSUE THREAD

**Issue by s641135196** [ng-alain/ng-alain#909]
多条件排序无法区分得按哪个字段先排序。 

代码精简如下： 
A.component.html
```javascript
   <st  (change)='tableChange($event)' ></st>
```
A.component.ts
```javascript
 tableChange(stChange: STChange) {
    switch(stChange.type){
         case "sort":
           console.log("sort: ", stChange.sort);
           break;
         default:
           console.log("其它stchange事件");
    }
  }
```
 我单击userName列，再单击createdTime 和 先单击createdTime 再单击userName，生成的stChange.sort.map值一样. 
console.log("sort: ", stChange.sort);  如下图
![image](https://user-images.githubusercontent.com/8079013/53061495-cbf6e580-34f8-11e9-8cc6-45074838d1e7.png)

我程序中排序是根据 stChange.sort.map中的值进行的排序的。
这样导致多条件排序不能区谁分先后先后。  

我认为正常情况应该是 stChange.sort.map的值会根据单击字段先后顺序排序的。不知道说的对不对

有什么办法解决这个问题吗？ 
当前ng-alian版本为2.0

**Comment by cipchk** [comment]
的确不会保持点击顺序，目前解决办法只能自己根据 `change` 事件维护该列表。

**Comment by cipchk** [comment]
打开此 issue，在多排序上保持用户点击顺序才能得到期望结果这是合理的，我会修复它。
