### ISSUE TITLE
功能建议：工具栏

### ISSUE THREAD

**Issue by dusdong** [ng-alain/ng-alain#91]
## Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```
在有复杂操作的CURD窗口的业务场景下，toolbar是最佳的方案之一，希望可以加入
示例：[http://www.jeasyui.net/demo/510.html](http://www.jeasyui.net/demo/510.html)

easy ui 应用截图：
![2017-12-09_214755](https://user-images.githubusercontent.com/3461709/33796188-ae01fa6e-dd2a-11e7-87bc-0940b7a51acf.png)

**Comment by cipchk** [comment]
Ant Design 并不适合处理这种传统的页面，我想你应该更改一种用户体验至上的为理念，这种页面与 Ant Design 完全违背。

当然 ng-alain 也不会提供这种东西。

**Comment by dusdong** [comment]
可能是我截图的业务窗口不符合 Ant Design的设计理念。抛开那个业务窗口，toolbar本身是否违背 Ant Design 的理念呢？
一个AngularJS示例：
[http://demos.telerik.com/kendo-ui/toolbar/angular](http://demos.telerik.com/kendo-ui/toolbar/angular)

**Comment by cipchk** [comment]
Ant Design 其中有一项很重要的是主次关系对比。

**Comment by lauralxj** [comment]
是不是用tab标签采用iframe也是与Ant Design是违背的

**Comment by cipchk** [comment]
也不一定是，有时候需求大于一切，只不过需求可以换另一种形式表述，就我个人对 Ant Design 的理解是最核心的：用户至上。

像在一个列表页中，从用户的角度他可能最关心或最常用的是搜索按钮、或添加按钮；利用主次关系可以极大的突现用户所关心的，反观就普通显示。

**Comment by cipchk** [comment]
[reuse-tab](http://ng-alain.com/components/reuse-tab) 路由复用标签可能会是你需要的。

关闭此问题，若有更多疑问请重新开启新 issue.
