### ISSUE TITLE
动态表单sf中的select修改enum应如何实现?

### ISSUE THREAD

**Issue by SargerasWang** [ng-alain/ng-alain#911]
我试过  `this.sf.schema.properties.XXX.enum = [];` 这样并不会刷新下拉列表的内容.

如果再之后执行 ` this.sf.refreshSchema();` 倒是可以刷新,但是这个操作就刷新了整个sf表单,影响太大.

**Comment by SargerasWang** [comment]
已使用subject解决.

**Comment by myprogo** [comment]
大哥。你是如何解决的？

**Comment by shiqkuangsan** [comment]
> 已使用subject解决.

请问是如何解决的？
