### ISSUE TITLE
st组件设置 @scrollbar-table-enabled为true后整体向上偏移。

### ISSUE THREAD

**Issue by zjxcv7** [ng-alain/ng-alain#912]
- ng-alain version: 7.0.0-rc.8
- Angular version: 7.2.6

## 【必填项】重现链接，Reproduction link
未设置之前
<img width="1246" alt="2019-02-21 11 14 59" src="https://user-images.githubusercontent.com/24834874/53141197-3592f480-35ca-11e9-9cc3-7428bc22f449.png">
设置@scrollbar-table-enabled为true后
<img width="1246" alt="2019-02-21 11 15 24" src="https://user-images.githubusercontent.com/24834874/53141209-3fb4f300-35ca-11e9-910f-f4e0cc46fc3b.png">

**Comment by cipchk** [comment]
应该是 https://github.com/NG-ZORRO/ng-zorro-antd/issues/2612 引起的，目前没有别的办法，只能等待 zorro 发布新版本再决定下一步。

**Comment by cipchk** [comment]
ng-zorro-antd `7.x` 已经修复该问题，关闭此 issue，若有新情况请重新提交新 issue。
