### ISSUE TITLE
CLI安装项目startup.service.ts中导航栏menu初始化未被执行

### ISSUE THREAD

**Issue by jedihoo** [ng-alain/ng-alain#914]
### 1.CLI安装空项目
![qq 20190221164606](https://user-images.githubusercontent.com/14693616/53155670-84578300-35f8-11e9-95a4-7305713b32ce.png)
**2.修改了menu的配置文件app-data.json，没有初始化出新的菜单，于是在startup.service.ts文件的相应为止执行console.log(res.menu);，发现并没有被执行**
![qq 20190221165453](https://user-images.githubusercontent.com/14693616/53156068-722a1480-35f9-11e9-96bd-9a95a457b6a5.png)
![qq 20190221164454](https://user-images.githubusercontent.com/14693616/53155886-05af1580-35f9-11e9-9006-b1f855a64a10.png)
![qq 20190221164354](https://user-images.githubusercontent.com/14693616/53155896-09429c80-35f9-11e9-929b-1c6cf1e1bc83.png)
望作者不辞辛苦，看下初始化这块的问题，谢谢，辛苦了。

**Comment by cipchk** [comment]
检查是否正确执行 `StartupService.load` 方法；其他情况请自行debugger，DEMO示例表现一切正常。

**Comment by Gyyyang** [comment]
请问是怎么解决的，我也是通过脚手架生成一个新项目，改了用户名字试一下，发现不能渲染 @jedihoo 

//修改自己提问，自己傻了，果然加班太晚，脑子不清醒。。在startup中初始化load()方法默认加载的是viaMock,这是局部变量，要手动换成viaHttp()
![image](https://user-images.githubusercontent.com/44013699/56175841-899ae200-602b-11e9-97b8-a7c9866ebb9d.png)
不好好看代码就来提问的下场，够丢人的了，希望之后又看到的小伙伴吸取教训

**Comment by YeFei572** [comment]
如果始终是想在本地加载而非网络加载, 那么不必走网络, 但是一定要修改拦截器里面的东西, 因为load()方法执行之前也要走拦截器, 所以拦截器里面应该修改成如下:
```
 intercept(req: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
    // 统一加上服务端前缀
    let url = req.url;
    // if (!url.startsWith('https://') && !url.startsWith('http://')) {
    //   url = environment.SERVER_URL + url;
    // }
    if (!url.startsWith('assets') && !url.startsWith('https://') && !url.startsWith('http://')) {
      url = environment.SERVER_URL + url;
    }

    const newReq = req.clone({ url });
    return next.handle(newReq).pipe(
      mergeMap((event: any) => {
        // 允许统一对请求错误处理
        if (event instanceof HttpResponseBase) return this.handleData(event);
        // 若一切都正常，则后续操作
        return of(event);
      }),
      catchError((err: HttpErrorResponse) => this.handleData(err)),
    );
  }
```
