### ISSUE TITLE
error: ngx-countdown error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'

### ISSUE THREAD

**Issue by xcorpio** [ng-alain/ng-alain#916]
- ng-alain version: ^7.0.0-rc.8
- Angular version:  ~7.2.0

## 【必填项】重现链接，Reproduction link

无

## 重现步骤，Steps to reproduce

从 `"ng-alain": "^1.4.4",` 升级到 `"ng-alain": "^7.0.0-rc.8",`
`ng server` 和 `ng build prod` 报
```
ERROR in node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.
node_modules/ngx-countdown/node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.
```

找到的ISSUE： https://github.com/cipchk/ngx-countdown/issues/26
需要删除 `./node_modules/ngx-countdown` 里面的 `node_modules` 目录才行。

升级`yarn add ngx-countdown@^3.2.0` 也不行，

请问有没有正式点儿的解决方案

**Comment by cipchk** [comment]
修改 `package.json` 的：

```
"ngx-countdown": "^3.1.0",
```
即可
删除 `node_modules` & `yarn.lock`，重新 `yarn` 即可
