### ISSUE TITLE
列名输出到内容里了

### ISSUE THREAD

**Issue by myprogo** [ng-alain/ng-alain#917]
- ng-alain version:7.0.0.rc8
- Angular version: 7.2.0

## 【必填项】重现链接，Reproduction link
![qq 20190222164243](https://user-images.githubusercontent.com/25293740/53230109-e7ace800-36c0-11e9-91f8-67134ff50ba0.png)

直接把列名也循环出来了

**Comment by cipchk** [comment]
`st` 的自适应功能引起的，检查是否 `ant-table-rep__title` 样式是否存在且值应该是 `display: none` 当大屏幕状态下，移动端下会自动切换为 `block` 状态。

检查方法是使用 Chrome 的 Elements 面板。

若其他因素，请提供相应的重现链接。

**Comment by myprogo** [comment]
确实是ant-table-rep__title未定义
