### ISSUE TITLE
编译失败 - failed to compile

### ISSUE THREAD

**Issue by johnsnow20087349** [ng-alain/ng-alain#92]
## Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions.

Angular CLI: 1.6.0
Node: 6.9.5
OS: win32 x64
Angular: 5.1.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 5.0.0
@angular/cli: 1.6.0
@angular-devkit/build-optimizer: 0.0.35
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.41
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.0
@schematics/angular: 0.1.10
@schematics/schematics: 0.0.10
typescript: 2.4.2
webpack-bundle-analyzer: 2.9.1
webpack: 3.10.0

### Repro steps.

从地址：git clone --depth 1 https://github.com/cipchk/ng-alain.git 克隆之后执行了npm install，之后npm start，没有执行别的操作

### The log given by the failure.

这是控制台输出和异常的代码截图：
![qq 20171210222049](https://user-images.githubusercontent.com/14345551/33805803-87213494-ddf9-11e7-9211-8e9e6cbd1651.png)

### Desired functionality.

按照提示说是参数赋值的类型不对，修改为字符串的true之后编译成功

**Comment by johnsnow20087349** [comment]
文件路径：ng-alain\src\app\routes\extras\poi\edit\edit.component.ts

**Comment by cipchk** [comment]
[NzModalSubject](https://github.com/NG-ZORRO/ng-zorro-antd/blob/master/src/components/modal/nz-modal-subject.service.ts#L16) 接收的是 `Subject<string | object>` 类型，`true` 是并非合理的值范围。

**Comment by johnsnow20087349** [comment]
是我下载的ng-zorro-antd 版本不对，所以检查的类型有误，更新到0.6.5 就OK了

**Comment by cipchk** [comment]
抱歉，的确有这个问题，这是因为 [#722](https://github.com/NG-ZORRO/ng-zorro-antd/pull/722) 引起的。
