### ISSUE TITLE
编译太慢，寻求建议。

### ISSUE THREAD

**Issue by Coder7777** [ng-alain/ng-alain#923]
随着项目的发展，现在基于Ng-alain开发的模块已达10个左右，涉及的页面30个左右。
现在，一点小改动，ctrl+s保存后，都会触发cli编译，然后浏览器刷新，这个整个过程随着页面的增多变得非常缓慢，时长要等上30~50秒，开发电脑的配置不算太差。
请问有什么好的办法解决这个问题？能否指定只对正在开发的页面的文件夹才执行ctrl+s触发编译？

**Comment by cipchk** [comment]
我们项目有 30 多个模块，几乎是秒级编译速度；这是前提，cli 的编译能力不算差。

但我建议你能给出一些有意义的代码和结构，才能综合分析。

**Comment by Coder7777** [comment]
cli确实不算慢，单个文件的修改保存，1秒多就能编译完成。

开发调试的时候慢的是浏览器那边，ctrl+s编译完成会触发浏览器刷新，浏览器（chrome）停留在蓝色背景那个loading界面大概耗时会有15秒左右，才能展示出页面来，所以整个过程大概再20秒左右。

npm run build完部署到服务器又很快，刷新浏览器大概1~2秒页面能完全展示出来。


开发机电脑配置i7-5500u+8g+固态。

**Comment by Coder7777** [comment]
> 我们项目有 30 多个模块，几乎是秒级编译速度；这是前提，cli 的编译能力不算差。
> 
> 但我建议你能给出一些有意义的代码和结构，才能综合分析。

cli确实不算慢，单个文件的修改保存，1秒多就能编译完成。

开发调试的时候慢的是浏览器那边，刚刚看了下确切的从编译到刷新页面展示出来的时间，ctrl+s编译完成会触发浏览器刷新，浏览器（chrome）停留在蓝色背景那个loading界面大概耗时会有15秒左右，才能展示出页面来，所以一般整个过程大概再20秒左右。

npm run build完，把dist部署到服务器又很快，刷新浏览器大概1~2秒页面能完全展示出来。

开发机电脑配置i7-5500u+8g+固态。

**Comment by Coder7777** [comment]
![image](https://user-images.githubusercontent.com/17242425/53461111-72536580-3a7a-11e9-9e8d-403dc9128d57.png)

业务模块都写在 routes目录下，自定义的业务模块component大概有三四十个。
是不是跟我导入component的地方不对有关？我的业务模块的component是在 providers/shared.module.ts 导入的。

**Comment by cipchk** [comment]
从以下几个方面出发：

- `ng s` 每一次编译会给出花费多少时间
- Chrome 的加载时间
- 换台机器

**Comment by dyx18539489507** [comment]
大侠,您好,又是我。这个问题我接着问,ng s编译时间50s,Chrome编译时间6s。笔记本配置为i7八代+512固态+8g运行内存。

**Comment by danxiaogui** [comment]
Angular HMR 热加载了解一下

**Comment by dyx18539489507** [comment]
> Angular HMR 热加载了解一下
平常在开发中呢？

**Comment by danxiaogui** [comment]
我自己电脑的配置还不错没遇到这个问题，不过我看ng-alain是支持hmr的，日常开发可以用hmr启动，至于细节性的只能你自己去查了

**Comment by dyx18539489507** [comment]
> 我自己电脑的配置还不错没遇到这个问题，不过我看ng-alain是支持hmr的，日常开发可以用hmr启动，至于细节性的只能你自己去查了

好的,非常感谢。

**Comment by danxiaogui** [comment]
![image](https://user-images.githubusercontent.com/22045563/68014313-22443700-fcca-11e9-99f0-b37e7a09159f.png)

**Comment by topperCao** [comment]
hmr ， 也一样的慢， cli里编译大概得30秒，浏览器hmr得10秒，改一行样式代码看效果，40秒过去了。。。。

**Comment by Y2zz** [comment]
这个问题确实很头疼，项目越来越大，编译就会越来越慢，hmr 也解决不了这个问题

**Comment by yang6701218** [comment]
我见过一次更改，然后每次都要重新登录，等待的时候2-3分钟，卧槽！！！为啥要用ag？react和vue 不香嘛
