### ISSUE TITLE
st表格行号怎么生成连续并紧接上一页的行号

### ISSUE THREAD

**Issue by s641135196** [ng-alain/ng-alain#924]
```javascript
  { title: '编号', type: 'no' ,fixed: 'left', width: '200px' }, 
```
这种方式在st中生成的行号每页都是从1开始的， 
我想要的是下一页的行页应该紧接到上一页的行号。
有什么办法实现了？

**Comment by cipchk** [comment]
`noIndex` 支持自定义方法，请参考文档：https://ng-alain.com/components/table/en#STColumn

**Comment by s641135196** [comment]
我对照文档这样写个测试。
```javascript
    { title: '编号', type: 'no' ,fixed: 'left', width: '80px', noIndex : (item: STData, col: STColumn, idx: number) => 111}, 
```
输出结果变成 
![image](https://user-images.githubusercontent.com/8079013/53396715-20f69800-39e0-11e9-8e7c-8f676ce4c112.png)
哪有用写错了吗？

**Comment by s641135196** [comment]
谢谢， 可以了， 升级到最新版本解决
