### ISSUE TITLE
SF input sizing

### ISSUE THREAD

**Issue by ronnyek** [ng-alain/ng-alain#926]
- ng-alain version: 7.0.0-rc.8
 Angular version: 7.1.4
## 重现步骤，Steps to reproduce
1. Create a sf dynamic form, with  plain text input type and specify size
``` js
UserName: {
        type: 'string',
        title: 'User Name',
        maxLength: 10,
        ui: {
          optionalHelp: 'Desired Username',
           size: 200
        }
      },
```
2. I'd assume this would set the width of the input text box, but appears to set the group's width with label etc.

I'd just like to know how I might be able to have a label and help icons etc, but have the text box width be settable. Setting width does appear to be getting applied and the input textbox does get smaller, however placement of the input textbox overlap the labels.

Is this the appropriate way to specify input textbox width?

**Comment by cipchk** [comment]
`sf` use responsive layout, so when you use a fixed width, it breaks the layout of other elements.

Of course, if you are sure you need to use a fixed width, you can using `width` in ui schema, and use `spanLabel` `spanLabel` to adjust the spacing.

> `size` is the size of the component, referring to `nzSize`.

you can try:

```
UserName: {
        type: 'string',
        title: 'User Name',
        maxLength: 10,
        ui: {
          optionalHelp: 'Desired Username',
           size: 'large',
			width: 500,
			spanLabel: 10,
			spanControl: 14
        }
      },
```

**Comment by ronnyek** [comment]
I'll give that a try. Appreciate the response!
