### ISSUE TITLE
ueditor在上传图片后，(ngModelChange) 不能监测到图片上传成功之后的变化

### ISSUE THREAD

**Issue by ehow2018** [ng-alain/ng-alain#927]
// ueditor在上传图片后，(ngModelChange) 不能监测到图片上传成功之后的变化
`
import { Component, OnInit, ViewChild } from '@angular/core';
import { ControlWidget } from '@delon/form';
import { UEditorComponent } from 'ngx-ueditor';

@Component({
    selector: 'sf-ueditor',
    template: `
        <sf-item-wrap [id]="id" [schema]="schema" [ui]="ui" [showError]="showError" [error]="error"
                      [showTitle]="schema.title">
            <ueditor #full
                     [ngModel]="value"
                     [config]="config"
                     [loadingTip]="loading"
                     (ngModelChange)="change($event)">
            </ueditor>
        </sf-item-wrap>
    `,
    preserveWhitespaces: false,
    styles: [`:host ueditor {
        line-height: normal;
    }`],
})
// tslint:disable-next-line:component-class-suffix
export class UeditorWidget extends ControlWidget implements OnInit {
    static readonly KEY = 'ueditor';

    config: any;
    loading: string;

    @ViewChild('full') full: UEditorComponent;

    ngOnInit(): void {
        this.loading = this.ui.loading || 'loading';
        this.config = this.ui.config || {};
    }

    change(value: string) {
        if (this.ui.change) this.ui.change(value);
        this.setValue(value);
    }

}
`

change 方法不执行

**Comment by cipchk** [comment]
https://github.com/fex-team/ueditor/wiki/FAQ


问题描述：简单文件上传完成后未触发contentchange 事件
解决方案：修改simpleUploder.js
