### ISSUE TITLE
avatar-list组件中不支持nzIcon设置

### ISSUE THREAD

**Issue by bokire** [ng-alain/ng-alain#93]
## Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Desired functionality.

ng-zorro的avatar组件支持icon方式进行头像设置，但是@delon/abc中avatar-list中只有scr方式，同样的问题还有ng-zorro-antd-extra种的nz-card-meta

**Comment by cipchk** [comment]
下一版本会加上，谢谢。

**Comment by cipchk** [comment]
`0.2.1` has fixed.
