### ISSUE TITLE
st组件的STColumnButton问题

### ISSUE THREAD

**Issue by liuyun521** [ng-alain/ng-alain#932]
st组件里的STColumnButton如何做到，根据列值显示不同的按钮

如果有任何问题，可在以下方式获得答案：

- https://ng-alain.com/
- QQ Group：316911865
- https://segmentfault.com/t/ng-alain

**Comment by cipchk** [comment]
[iif](https://ng-alain.com/components/table/en#STColumnButton)

**Comment by liuyun521** [comment]
![image](https://user-images.githubusercontent.com/9554224/53778668-81ce2500-3f38-11e9-95c2-fa20db60b018.png)
完全不起作用，断点也进不去

**Comment by liuyun521** [comment]
> [iif](https://ng-alain.com/components/table/en#STColumnButton)

完全不起作用
