### ISSUE TITLE
sf, upload部件，对formData内容不能展示

### ISSUE THREAD

**Issue by ayaka209** [ng-alain/ng-alain#934]
- ng-alain version: 7.0.0.rc10
- Angular version: 

## 【必填项】重现链接，Reproduction link 

https://stackblitz.com/edit/ng-alain-setup-fepz9h

## 重现步骤，Steps to reproduce

sf, upload部件，对formData内容不能展示
如例子↑，formData中name有图片连接，但是不会被展示出来。

也就是说该sf创建的数据，再用sf展示，是看不到图片的。

只能用asyncData再来做加载吗？

**Comment by ayaka209** [comment]
目前自己做了一个upload的widget
相比库里的upload
```
 reset(value: SFValue) {

    const { fileList } = this.ui;
    (fileList ? of(fileList) : getData(this.schema, this.ui, this.formProperty.formData)).subscribe(
      list => {
        list = this.formProperty.formData;      <----- 加了这一行 （数据为 [ {url:xxx} ]
        this.fileList = list as UploadFile[];
        this._setValue(this.fileList);
        this.detectChanges();
      },
    );
  }
```
我认为这个应该还是属于一个bug的，和用户的预期行为不符（主要是用于"编辑"页面时）
是否还有更好的处理方式？

**Comment by ayaka209** [comment]
另：
type:"array",
widget: "upload",
formdata传入该属性的数组时（数组内容为地址字符串），同样会报错
type:"string"时也会

各不同，先暂时不放在线演示了

**Comment by cipchk** [comment]
目前上传成功后应设置 `url` 或 `thumbUrl` 参数才能触发内置的预览效果（当然也可以通过 `preview` 来自定义预览效果），而且只能通过 `change` 事件来做这一件事，这样的行为的确有点反人类。

**Comment by ayaka209** [comment]
这个情景也不是在上传成功之后
而是 上传成功 - 保存 - 再重新加载数据
也就是给formData赋值这个过程，虽然给upload组件有赋值，但是不会自动转为fileList

**Comment by jerrytang67** [comment]
是蛮变扭的.用picture-card模式remove以后也不会改变list
