### ISSUE TITLE
bug report: ST component lost param name. when reName request param name 'ps'

### ISSUE THREAD

**Issue by xingkoo** [ng-alain/ng-alain#935]
- ng-alain version: 7.0.1
- Angular version: X.Y.Z

## 【必填项】重现链接，Reproduction link

https://stackblitz.com/edit/ng-alain-setup-ckd3wc?file=src/app/app.component.html

## 重现步骤，Steps to reproduce

示例中的表格正常请求应该是
`https://ng-alain-setup.stackblitz.io/users?total=100&ps=10&a=1&b=2`

全局配置ST组件的 `req.reName.ps` 时，实际请求的参数名称出错。实际链接地址丢失ps参数。
`https://ng-alain-setup.stackblitz.io/users?total=100&undefined=10&a=1&b=2`

### 7.0.0 rc2 版本是正常的

**Comment by xingkoo** [comment]
临时解决方案：
`req: {reName: { pi: 'page', ps: 'ps' } }` 
改为
`req: {type:'page', reName: { pi: 'page', ps: 'ps' } },`

应该是合并参数的时候出现的问题。

**Comment by cipchk** [comment]
抱歉，上个版本的性能优化导致的。
