### ISSUE TITLE
STColumnButton的modalOptions和drawerOptions会导致STConfig全局配置失效

### ISSUE THREAD

**Issue by devsharper** [ng-alain/ng-alain#936]
- ng-alain version: 7.0.1

https://github.com/ng-alain/delon/blob/1196fed697f1777d3f5cd1315c1d735527d15bd9/packages/abc/table/table-column-source.ts#L51

https://github.com/ng-alain/delon/blob/1196fed697f1777d3f5cd1315c1d735527d15bd9/packages/abc/table/table-column-source.ts#L60

建议改成 Object.assign 形式
size: lg 也建议去掉，以全局配置为准

**Comment by cipchk** [comment]
duplcated of #935

**Comment by devsharper** [comment]
@cipchk 老大，7.0.2中这个问题仍然存在，组件中的 modalOptions / drawerOptions 把全局配置STConfig中的这两个对象给整个覆盖了。

比如全局设置了 drawerOptions: { nzClosable: false }，组件中设置任意一个属性比如 drawerOptions: { nzPlacement: 'bottom' }，全局的 nzClosable 就失效了，建议不要替换整个对象，只覆盖里边的属性
