### ISSUE TITLE
STColumnButton的Drawer的nzPlacement设为top或bottom时，Drawer宽度不能全屏

### ISSUE THREAD

**Issue by devsharper** [ng-alain/ng-alain#937]
- ng-alain version: 7.0.1

STColumnButton  type: drawer,  drawerOptions: { nzPlacement: 'bottom'}  //或top

弹出的Drawer宽度不是100%，貌似是受size影响了
建议top或bottom时自动100%宽度
对于left或right，size影响宽度，对于top或bottom，size应该影响高度

**Comment by cipchk** [comment]
关于宽、高请参考 https://ng.ant.design/components/drawer/zh 文档。
