### ISSUE TITLE
动态表单全局配置忽略某些错误类型时导致其他问题。

### ISSUE THREAD

**Issue by xingkoo** [ng-alain/ng-alain#939]
- ng-alain version: X.Y.Z
- Angular version: X.Y.Z

## 【必填项】重现链接，Reproduction link

https://stackblitz.com/edit/ng-alain-setup-6qbzvs

## 重现步骤，Steps to reproduce
参考之前的问题 @delon/form number widget multipleOf error  https://github.com/ng-alain/ng-alain/issues/526
配置全局忽略 `倍数` 检查错误。
````
import { DelonFormConfig } from '@delon/form';
export function fnDelonFormConfig(): DelonFormConfig {
  return Object.assign(new DelonFormConfig(), <DelonFormConfig>{
    // values
   ingoreKeywords: ['multipleOf'],
  });
}
````
导致产生新的错误（见上面重现链接）。

类似如下代码时，激活 `应当是预设定的枚举值之一` 错误。
````
  schema: SFSchema = {
    properties: {
      status: {
        type: 'integer',
        title: '状态',
        enum: [{ label: '可用', value: 1 }, { label: '不可用', value: 0 }],
        default: 1,
        ui: {
          widget: 'radio',
          styleType: 'button',
        },
      },
    },
    required: ['name']
  };
````

在官方文档中，该 `ingoreKeywords`默认值为['type', 'enum']。
是否 type 以及 enum 两种类型的错误也是需要被忽略的？
在使用中，需要按下面代码来处理吗？
````
ingoreKeywords: ['multipleOf', 'type', 'enum'],
````
这里面的 type ，有这么一种类型？

**Comment by cipchk** [comment]
是的，当你覆盖默认配置时，需要加上当前默认值。你也可以针对某个 Schema 设置不同的 `ingoreKeywords`。
