### ISSUE TITLE
如果ng-alain更新了，怎么更新自己的项目。

### ISSUE THREAD

**Issue by zdxxxxxx** [ng-alain/ng-alain#94]
如题

**Comment by cipchk** [comment]
升级 `@delon/theme`、`@delon/abc` 等即可，一般只需要 `npm install` 时会自动安装最新版本，无须任何配置上的调整。当然你要是手机修改 package.json 里面的版本号也是可以的。

**Comment by zdxxxxxx** [comment]
[#77](https://github.com/cipchk/ng-alain/issues/77)
这个是怎么解决的啊

**Comment by cipchk** [comment]
0.2 已经修复该问题

> 同一个 issue 只涉及一个问题，以免给其他人在查阅 issue 时产生疑惑。

**Comment by zdxxxxxx** [comment]
ok，thanks！
