### ISSUE TITLE
侧边栏菜单收缩状态下，点击一级菜单图标，二级菜单消失

### ISSUE THREAD

**Issue by ma-lihui** [ng-alain/ng-alain#942]
- ng-alain version: 7.0.0-rc.3
- Angular version: 7.2.2

## 重现步骤，Steps to reproduce

1. 将侧边栏菜单设置为收缩状态
2. 鼠标悬浮在一级菜单图标，二级菜单悬浮出现，点击一级菜单图标，二级菜单消失

## 期望
点击一级菜单图标，二级菜单不会消失。 （react版本没这种情况）

**Comment by cipchk** [comment]
`sidebar-nav` 的设计本身就是在收缩状态下，点击子菜单会自动关闭。

**Comment by ma-lihui** [comment]
> `sidebar-nav` 的设计本身就是在收缩状态下，点击子菜单会自动关闭。

点击子菜单是应该关闭，但点击主菜单，子菜单会关闭

**Comment by cipchk** [comment]
麻烦提供一个重现示例，我并不了解你所指。

**Comment by ma-lihui** [comment]
![Mar-18-2019 13-38-41](https://user-images.githubusercontent.com/16605318/54509243-e4391380-4983-11e9-8c48-6771af865f8b.gif)

如图，收缩侧边栏时。鼠标悬浮在一级菜单图标上，二级菜单显示；点击一级菜单图标，二级菜单消失。
【期望】：点击点击一级菜单图标，二级菜单不会消失

**Comment by cipchk** [comment]
不消失这会导致一个行为的奇怪现象，目前移动展开，点击关闭是一种合理的操作行为。
