### ISSUE TITLE
导航栏在收起状态下点击菜单项导致内容延迟加载或者直接不加载问题。

### ISSUE THREAD

**Issue by zjxcv7** [ng-alain/ng-alain#943]
- ng-alain version: 7.0.1
- Angular version: 7.2.7

## 【必填项】重现链接，Reproduction link

https://ng-alain.github.io/ng-alain/#/pro/form/basic-form

## 重现步骤，Steps to reproduce

1、在主界面将导航栏设置为收缩状态
2、点击导航栏中某个菜单项

注意右边内容部分。在展开时是正常加载，在导航栏收缩后再点击的话会发现加载延迟或者直接不加载。

**Comment by cipchk** [comment]
duplcated of #938
