### ISSUE TITLE
upload firefox faild

### ISSUE THREAD

**Issue by lyc152** [ng-alain/ng-alain#95]
## Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
```

 我在做上传文件功能时看到官网  https://cipchk.github.io/ng-alain/#/forms/upload  的例子，经过测试发现 chrome 是没问题的，但是在 firefox 浏览器下面 是不可以的， 具体的问题是点击上传，不能选择文件最新的 firefox  57.0.1 版本也不可以，然后我发现 alain 用的 是 ng2-file-upload 这个插件，我在本地 放弃使用这个文件，用原生的去实现这个功能在 alain 这个组件库下还是不能实现上传的，但是我用 Angular-cli 直接生成的空白项目是可以实现上传的，不知道大家碰到过这个问题吗？

**Comment by cipchk** [comment]
这可能是因为 css 导致了文件无法选择的原因，或者很难命中。我不打算修复它，因为 `ng-zorro-antd` 的上传组件已经快好了。

与 #27 重复，因此我关闭该  issue，谢谢。

**Comment by lyc152** [comment]
确实是 样式问题， 是 button 和 input file 相结合 导致 上传组件不能被点击到，之前没考虑到这个问题，谢谢
