### ISSUE TITLE
Can you make dictionary matching ignore characters or numbers?

### ISSUE THREAD

**Issue by dangzhenghui1985** [ng-alain/ng-alain#950]
- ng-alain version: X.Y.Z
- Angular version: X.Y.Z

## 【必填项】重现链接，Reproduction link

https://stackblitz.com/edit/ng-alain-setup-2djg9u
往往服务端传回的字典有可能是字符串类型，数据有可能是nubmer类型 目前类型不一致没法匹配。是否可以忽略类型更加兼容一些呢？
![image](https://user-images.githubusercontent.com/16914422/54081999-a1ef5100-4349-11e9-915f-2badb523c029.png)
![image](https://user-images.githubusercontent.com/16914422/54082011-d7943a00-4349-11e9-9799-2760f81e811c.png)

**Comment by dangzhenghui1985** [comment]
![image](https://user-images.githubusercontent.com/16914422/54082023-05797e80-434a-11e9-8d36-3b63fd5b0d93.png)

**Comment by cipchk** [comment]
数据的一致性非常重要，关于这个问题，建议从自身的后端设计为统一化。
