### ISSUE TITLE
使用Cascader组件后，刷新表单结构报错。

### ISSUE THREAD

**Issue by xingkoo** [ng-alain/ng-alain#951]
- ng-alain version: 7.0.2
- Angular version: X.Y.Z

## 【必填项】重现链接，Reproduction link

https://stackblitz.com/edit/ng-alain-setup-s7f3bw?file=src%2Fapp%2Fapp.component.ts

## 重现步骤，Steps to reproduce
场景：

表单属性|描述
-|-
省、市、区| 使用级联组件选择
商圈| 使用下拉列表，当选择城市时，动态更新商圈的备选列表。

见重现示例（点击组件组件后，控制台可见错误信息）

**Comment by xingkoo** [comment]
使用延迟刷新，可以正常使用。我不确认这个是不是bug。反馈一下。
````
setTimeout(
  ()=>{ this.sf.refreshSchema(); },
  250
);
````

**Comment by xingkoo** [comment]
当我优先修改了其他属性。 然后当我再选择（省市区）后，触发`this.sf.refreshSchema();`刷新表单结构时，会导致之前修改的其他属性数据丢失。
我能否只修改某个属性的结构？

我现在尝试临时解决方案：

    初始化时，将数据赋值给表单（数据A）
    将当前表单的值，保存起来（数据B）。
    刷新完表单结构后，重新赋值给表单。（数据B赋值给表单）
    修改reset,使用之恢复初始化时加载的数据。（数据A赋值给表单）

**Comment by cipchk** [comment]
`refreshSchema` 会导致所有表单元素被重置，异步后的组件已经移除了，自然会收到 `Attempt to use a destroyed view: detectChanges` 异常。

对于这类表单，我建议自己写个小部件进行整合，当你无法使用现有基础小部件完成业务时都应该考虑是否采用自定义小部分，城市与商圈很明显可以集成在一个小部件上，参考 date 小部件可以自行实现一个小部件内同时对多个元素进行赋值。

**Comment by xingkoo** [comment]
我使用另外的方法来解决这个问题。
对表单数据做冗余，存 **[省，市，区] **  实际和后台对接的元素使用   **省、市、区** 三个属性。

商圈使用下拉框，数据源采用异步获取。
增加生效条件如````visibleIf: { townId: (value: any) => value && value > 0 },````

当用户通过组件来选择省市区时，在该事件中，移除 省、市、区的值。然后重新赋值。
以触发商圈元素 **visibleIf** 的生效。达到该表单元素的增加及移除。

以此来达到动态变更商圈数据源的目的。
