### ISSUE TITLE
将Delon的ACLService的parseACLType方法提为单独服务注入，以兼容更多功能点数据形式

### ISSUE THREAD

**Issue by gmf520** [ng-alain/ng-alain#952]
### 现在的ACLService存在的问题：
1. 在路由或者菜单中的acl配置，如果是简单数据类型（string/string[]/number/number[]）的写法，被限定为string是角色，number中功能点，兼容性不高
2. 如果要功能点支持字符串的形式，那acl配置只能是ACLType类对象的形式，形如{role: xxx, ability:xxx}，使用起来很不方便
3. 导致以上问题的原因，主要是ACLService中由ACLCanType到ACLType的转换规则被私有代码写死了，无法进行扩展
```
  can(roleOrAbility: ACLCanType): boolean {
    if (this.full === true || !roleOrAbility) {
      return true;
    }

    let t: ACLType = {};
    if (typeof roleOrAbility === 'number') {
      t = { ability: [roleOrAbility] };
    } else if (
      Array.isArray(roleOrAbility) &&
      roleOrAbility.length > 0 &&
      typeof roleOrAbility[0] === 'number'
    ) {
      t = { ability: roleOrAbility };
    } else {
      t = this.parseACLType(roleOrAbility);
    }
    ...

  private parseACLType(val: string | string[] | ACLType): ACLType {
    if (typeof val !== 'string' && !Array.isArray(val)) {
      return val as ACLType;
    }
    if (Array.isArray(val)) {
      return { role: val as string[] } as ACLType;
    }
    return {
      role: [val],
    } as ACLType;
  }
```

### 解决办法
1. 增加一个`IACLTypeParseService`接口的全局单例服务来负责`ACLCanType到ACLType`的转换工作，开发者可以替换自己的服务实现进行替换
2. 也可以在DelonACLConfig 中增加 功能点字符串 匹配的正则表达式，符合正则表达式规则的字符串即认为是功能点字符串，而非角色字符串。

这样应该能满足那些功能点字符串有规律的系统的扩展需求，希望能采纳

**Comment by gmf520** [comment]
已提交实现此Issus的PR，请阅览
https://github.com/ng-alain/delon/pull/471

**Comment by cipchk** [comment]
谢谢PR。

字符与数字的区分是一个折中的办法，的确并不能符合所有场景，其中您所提的 **正则表达式** 来区分角色与功能点，我认为是个非常好的建议，除此之外，我不认为一个转换而做一个额外的接口并不是非常好的解决办法。

ACL 本身并不复杂，若有特殊需求完全可以覆盖现有的 `ACLService`。

**Comment by gmf520** [comment]
@cipchk 你说的覆盖`ACLService`指的是这种方式吗？
```
{ provide: ACLService, useClass: MockACLService }
```
明白了，谢谢
或者还有一种方式，你可以把`ACLService`中负责转换的代码提取为一个`protected parseACLType(val: string | string[] | ACLType)`的方法，这样我们重写转换逻辑的时候会方便很多，现在的是私有方法，并且转换逻辑的代码很分散，不方便统一重写，只能重写整个`can`，不是很方便
