### ISSUE TITLE
sf 分类布局

### ISSUE THREAD

**Issue by xingkoo** [ng-alain/ng-alain#953]
有些表单项目比较多，划分出来多个表单会导致用户操作过多。
希望能够可以通过分割线来划分区域，让用户在使用的时候更加清晰。

**Comment by cipchk** [comment]
我建议使用 `class` 对某个属性进行样式优化，若把 divider 当成一个元素，会产生多余的表单数据，虽然技术上可以处理，但是为了UI而让表单多余并不是一种很好的解决办法。

**Comment by xingkoo** [comment]
使用class来操作也是一个解决方法。只是这样操作，会不会导致需要分块的位置，对应的表单数据需要占用整行来进行处理。这样会影响到后续其他表单属性的排版。

**Comment by xingkoo** [comment]
这个问题没有其他人有经常碰到吗？

**Comment by xingkoo** [comment]
#1327  sf 能否加上视觉分组功能
