### ISSUE TITLE
MenuService 设置导航栏SVG图标时在Chrome上正常显示，但是在Safari，Firefox上显示模糊。

### ISSUE THREAD

**Issue by zjxcv7** [ng-alain/ng-alain#954]
- ng-alain version: 7.0.2
- Angular version: 7.2.8

### 导航栏展开时
<img width="199" alt="屏幕快照 2019-03-11 下午3 04 13" src="https://user-images.githubusercontent.com/24834874/54105810-22c45080-440f-11e9-9e4b-291e4bd9be93.png">
### 导航栏收缩时
<img width="250" alt="屏幕快照 2019-03-11 下午3 04 31" src="https://user-images.githubusercontent.com/24834874/54105812-2526aa80-440f-11e9-97fd-dbbf361e17cf.png">
### 设置代码
<img width="420" alt="屏幕快照 2019-03-11 下午3 05 13" src="https://user-images.githubusercontent.com/24834874/54105815-28219b00-440f-11e9-9a96-f73143cec1f2.png">

**Comment by cipchk** [comment]
关闭此issues，若有关进一步细节描述再重新打开。
