### ISSUE TITLE
关于路由复用销毁的问题

### ISSUE THREAD

**Issue by mjn1154477982** [ng-alain/ng-alain#956]
关于路由复用，有个问题想问问大神，就是ng-alain是如何实现路由复用的时候，点击上方的关闭tab按钮的时候，是如何触发组件ngOnDestroy的这个钩子的？目前我是通过componentRef.destroy()的方式，在点击关闭的时候，手动销毁组件，用来触发ngOnDestroy这个钩子，不知道ng-alain是用什么方式实现的

**Comment by cipchk** [comment]
https://ng-alain.com/components/reuse-tab/zh#%E7%94%9F%E5%91%BD%E5%91%A8%E6%9C%9F
