### ISSUE TITLE
modal弹出框 sf   textarea 组件  autosize 失效问题

### ISSUE THREAD

**Issue by dangzhenghui1985** [ng-alain/ng-alain#957]
- ng-alain version: 7.0.1
- Angular version: 7.0.1

## 【必填项】重现链接，Reproduction link

https://stackblitz.com/edit/ng-alain-setup-hvbozf
![image](https://user-images.githubusercontent.com/16914422/54120541-f15d7c00-4432-11e9-8116-c804b97a0270.png)
只要包裹标签就会显示失败

**Comment by hennychen** [comment]
要设置 autosize: { minRows: 2, maxRows: 6 },

**Comment by dangzhenghui1985** [comment]
![image](https://user-images.githubusercontent.com/16914422/54400510-1a656180-46fe-11e9-94c2-0564945562a0.png)
这个是设置的上面两个地方用的同一套设置导致一个好使一个不好使 有重现连接可以看看

**Comment by cipchk** [comment]
受限于 https://github.com/NG-ZORRO/ng-zorro-antd/issues/2417 目前无解，我会继续跟进

**Comment by cipchk** [comment]
@dangzhenghui1985  能否就最新版本进一步重现呢？我尝试过，但一切都 正常。

**Comment by dangzhenghui1985** [comment]
新版的我试了好使的完全没有问题可以关闭这个问题了
