### ISSUE TITLE
side bar 在二级菜单很多的情况显示不下，没有出现滚动条

### ISSUE THREAD

**Issue by huangyunfei007** [ng-alain/ng-alain#959]
- ng-alain version: X.Y.Z
- Angular version: X.Y.Z

## 重现步骤，Steps to reproduce
添加二级菜单项，大于真个页面的高度，使用弹出显示，不能把所有菜单都显示完整

**Comment by cipchk** [comment]
关闭此issues，若有关进一步细节描述再重新打开。
