### ISSUE TITLE
SF transfer 穿梭框 点击文字前面的复选框 导入按钮不改变

### ISSUE THREAD

**Issue by hennychen** [ng-alain/ng-alain#960]
- ng-alain version: ^7.0.2
- Angular version: ^7.2.4

## 【必填项】重现链接，Reproduction link
https://ng-alain.com/form/transfer/zh

## 重现步骤，Steps to reproduce
![(9MYNE%6U11RQI~$V R4F0](https://user-images.githubusercontent.com/2526830/54181774-9aab7d00-44da-11e9-9ba6-3afe4f220b9c.png)

**Comment by cipchk** [comment]
fixed by ng-zorro-antd `7.0.2`, pls upgrade ng-zorro-antd to latest version.

**Comment by cipchk** [comment]
https://github.com/NG-ZORRO/ng-zorro-antd/issues/3026
