### ISSUE TITLE
st表格没有resetColumns方法

### ISSUE THREAD

**Issue by i6448038** [ng-alain/ng-alain#962]
- ng-alain version: 2.0.0-rc.2
- Angular version: 6.1.10

## 【必填项】重现链接，Reproduction link

![image](https://user-images.githubusercontent.com/6186049/54292132-9cfbfd00-45e8-11e9-86db-cbadb1104300.png)
![image](https://user-images.githubusercontent.com/6186049/54292191-b8670800-45e8-11e9-94e7-de7804e0c179.png)
![image](https://user-images.githubusercontent.com/6186049/54292254-cfa5f580-45e8-11e9-864a-bbfc92a7e1e3.png)
![image](https://user-images.githubusercontent.com/6186049/54292551-58249600-45e9-11e9-9f99-04b6b9630105.png)

**Comment by cipchk** [comment]
pls upgrade all @delon/* libs to latest version.
