### ISSUE TITLE
'header-i18n' is not a known element

### ISSUE THREAD

**Issue by HighLordA** [ng-alain/ng-alain#963]
入门-开始使用的时候-CLI安装的时候，默认命令安装完 会提示18n错误

![Capture](https://user-images.githubusercontent.com/10086392/54325941-9482e100-463f-11e9-9068-09e949c2fc1d.PNG)

**Comment by HighLordA** [comment]
https://ng-alain.com/docs/getting-started/zh 就是这个界面的

**Comment by KarmaHwang** [comment]
提示得很清楚了，【header-i18n】，组件不存在，默认neg-alain会使用【header-i18n】组件，但是你应该在构建的时候没有启用i18n模块，  全局搜索<header-i18n>  删掉就可以用了，如果需要使用i18n，https://ng-alain.com/docs/i18n/zh

**Comment by HighLordA** [comment]
> 提示得很清楚了【header-i18n】，组件不存在，默认ng-alain会使用【header-i18n】组件，但是你应该在构建的时候没有启用i18n模块， 全局搜索 删掉就可以用了，如果需要使用i18n，https://ng-alain.com/docs/i18n/zh
我是想说这个快速入门页面应该更正这个指令ng new my-project --style less 如果18n是必须的话
