### ISSUE TITLE
ST表格

### ISSUE THREAD

**Issue by myprogo** [ng-alain/ng-alain#965]
- ng-alain version: 7.0.0
- Angular version: 7.2.2

## 【必填项】重现链接，Reproduction link
用ST表格组件，从后台取出用户列表，现在往用户列表里动态加入对于的用户角色信息，发现数据源里已经有信息了。但是ST却无法读取加入的角色信息。
![QQ截图20190314164616](https://user-images.githubusercontent.com/25293740/54343003-be0c2e80-4678-11e9-9ad5-99083cfbee3b.png)
![QQ截图20190314164627](https://user-images.githubusercontent.com/25293740/54343004-bf3d5b80-4678-11e9-81ba-e93088ec8b4b.png)

**Comment by cipchk** [comment]
关闭此issues，若有关进一步细节描述再重新打开。
