### ISSUE TITLE
Upload widget的fileList属性双向绑定无效

### ISSUE THREAD

**Issue by devsharper** [ng-alain/ng-alain#969]
- ng-alain version: 7.0.2

在SF schema中配置fileList属性：
xxx: { type: 'string', ui: { widget: 'upload', fileList: this.fileList } }

使用picture-card模式，文件上传成功后页面上可以正常预览图片，但 this.fileList 仍然为空，在后台给 this.fileList 赋值也无法反映到页面上，双向绑定都不起作用

**Comment by cipchk** [comment]
关闭此issues，若有关进一步细节描述再重新打开。

**Comment by Null-Ouwenjie** [comment]
v7.0.3 <sf/>上传图片，遇到类似问题，有空的时候，请帮忙看一下，谢谢了

reproduce : https://stackblitz.com/edit/ng-alain-setup-u3lypw
重现过程中，上传图片一致报 SVGTagNotFoundError 不知道什么原因，导致无法运行，无法重现下面的问题。
只能麻烦看看代码了，代码就跟我项目中的差不多。（七牛token有效期是60分钟，过期了我可以再更新）

问题一，submit 的时候，sf.value.uploadPic 是有值的，但是上传了多张图片的时候，该值依旧只有一个
问题二，如楼主一样，fileList 绑定的对象 this.fileList 是空的

**Comment by devsharper** [comment]
@cipchk 重现链接
https://stackblitz.com/edit/ng-alain-setup-3pbbwy

**Comment by cipchk** [comment]
@devsharper 提交数据中已经包含 `name: "upload"` 的值，`sf` 作为表单其结果是合理的，若你需要了解状态变更可以使用 `change`

**Comment by cipchk** [comment]
@Null-Ouwenjie 关于多值请参考文档 [注意事项](https://ng-alain.com/form/upload/en#%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9)

**Comment by Null-Ouwenjie** [comment]
> @Null-Ouwenjie 关于多值请参考文档 [注意事项](https://ng-alain.com/form/upload/en#%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9)

建议操作的单选多选，和表单结果的单值多值，分开配置比较好
