### ISSUE TITLE
关于tabs动态加载其他组件的页面

### ISSUE THREAD

**Issue by guccihuiyuan** [ng-alain/ng-alain#97]
我想在点击一次侧边栏的按钮时候，将该组件的页面添加到tab的内容里面，但是这样做的话会有问题，当添加新的页面的时候，前面一个tab的内容就会变成新的组件内容，有没有什么好的解决办法吗？
<nz-tabset [nzType]="'card'" [nzSelectedIndex]="tabs.length-1">
            <nz-tab *ngFor="let tab of tabs">
                <ng-template #nzTabHeading>
                    <div>
                        {{tab.name}}
                        <i class="anticon anticon-cross" (click)="closeTab(tab)"></i>
                    </div>
                </ng-template>
                <router-outlet></router-outlet>
            </nz-tab>
        </nz-tabset>

**Comment by cipchk** [comment]
问题的核心是路由复用，有兴趣可以参考 @delon/abc 的 [reuse-tab](http://ng-alain.com/components/reuse-tab)；

我将关闭此 issue，若有更多细节讨论可重新 issue。
