### ISSUE TITLE
Cross origin requests are only supported for protocol schemes

### ISSUE THREAD

**Issue by mid120** [ng-alain/ng-alain#973]
zone.js:3243 Failed to load localhost:8100/api/v1/system/log?pi=1&ps=10&no=11111: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension

如何配置跨入问题
![image](https://user-images.githubusercontent.com/20294565/54595846-6ef63d00-4a6e-11e9-95a5-752b6e9e90e2.png)

**Comment by cipchk** [comment]
请自行百度或问后端人员。
