### ISSUE TITLE
建议增加MenuService::setData();

### ISSUE THREAD

**Issue by zdxxxxxx** [ng-alain/ng-alain#98]
不知道如何清除MenuService.data

**Comment by cipchk** [comment]
`MenuService.add([])`

**Comment by zdxxxxxx** [comment]
MenuService.prototype.add = function (items) {
        (_a = this.data).push.apply(_a, items);
        this.resume();
        var _a;
    };
只能push，不能清空，我想重新设置菜单

**Comment by cipchk** [comment]
我会在下一版本加上 `clear()` 操作。

**Comment by jackywang615** [comment]
正是我想要的

**Comment by cipchk** [comment]
`0.2.1` has fixed.
