### ISSUE TITLE
excel导出不能用了，xlsx cdn报错

### ISSUE THREAD

**Issue by yyget** [ng-alain/ng-alain#984]
目前用的是ng alain 1.3.0的版本，今天突然发现导出不能用了，console报错如下
![image](https://user-images.githubusercontent.com/13427513/54803581-0b0c8800-4cab-11e9-96e7-a8a0718c6cb1.png)

**Comment by HJianfeng** [comment]
官网的例子也不能用了，好像是//cdn.bootcss.com/xlsx/0.12.13/xlsx.full.min.js这个文件被删除了

**Comment by yyget** [comment]
> 官网的例子也不能用了，好像是//cdn.bootcss.com/xlsx/0.12.13/xlsx.full.min.js这个文件被删除了

是的，我专门下载了官网的例子，不能用，不过我已经解决了

**Comment by yyget** [comment]
修改app.module.ts 两个地方
import {AdXlsxModule } from '@delon/abc';
  AdXlsxModule.forRoot({
      url: 'assets/xlsx.full.min.js'
    }),

自己下载xlsx.full.min.js放在assets下就可以了
https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.12.12/xlsx.full.min.js
不用谢我叫雷锋

**Comment by liveangela** [comment]
新版本的delon可能没有AdXlsxModule了，针对这个问题（这里也是同样的问题 #657 ），
我用的是下面的做法，在`src/app/delon.module.ts`文件合理位置，添加如下代码
```js
... // 上面大量可仿造的代码写法

import { XlsxConfig } from '@delon/abc';
export function fnXlsxConfig(): XlsxConfig {
  return {
    ...new XlsxConfig(),
    ...({
      url: 'assets/js/xlsx.full.min.js',
    } as XlsxConfig),
  };
}

const GLOBAL_CONFIG_PROVIDES = [
  // TIPS：@delon/abc 有大量的全局配置信息，例如设置所有 `st` 的页码默认为 `20` 行
  ...
  { provide: XlsxConfig, useFactory: fnXlsxConfig },
];
```

并按@yyget 手动下载xlsx.full.min.js放入assets下指定的路径即可（务必要下载full版本的）

my delon version: ^7.2.0
