### ISSUE TITLE
ST能不能增加个表头固钉，类似zorro的Affix功能

### ISSUE THREAD

**Issue by gmf520** [ng-alain/ng-alain#986]
![QQ图片20190324225603](https://user-images.githubusercontent.com/3930317/54881159-0bae4580-4e88-11e9-8fa7-db1f2ca225d3.png)
ST不能固定表头在数据多的时候很不方便，比如上面这个表格，看不见表头就瞎了，不知哪列是啥，老要上下倒来确定

**Comment by cipchk** [comment]
`scroll` 属性了解一下。

**Comment by gmf520** [comment]
![QQ截图20190325175659](https://user-images.githubusercontent.com/3930317/54910525-795d7e80-4f27-11e9-815d-8409fe2331e3.jpg)
@cipchk `scroll`在小屏中并不好用，页头，搜索之类的信息已经占用了很大一部分屏幕了，留给数据行显示的空间就很小了，并且应对不同倍率的屏幕，scroll并不能很好的解决问题

**Comment by cipchk** [comment]
@gmf520 `st` 是基于 `nz-table` 的基础上，我建议使用 `nz-table` 若依然如此，可以至 ng-zorro-antd 提交相应的 ISSUES。
