### ISSUE TITLE
标签页右键关闭功能

### ISSUE THREAD

**Issue by runFP** [ng-alain/ng-alain#988]
## What problem does this feature solve?
目前标签页右键，关闭标签，是关闭当前标签，关闭其他标签是关闭除选中外的所有标签

## What does the proposed API look like?
能否提供参数，让关闭其它标签和关闭标签一样都是基于鼠标选中，来排除其他标签

**Comment by cipchk** [comment]
若是如此有点反人类设计，目前参考的是 Chrome 的 Tab 设计。

**Comment by runFP** [comment]
hi,cipchk,我想你有些误会了，因为ng-alain现在确实和谷歌的不一样，谷歌是鼠标移上去，关闭其他标签，是以鼠标当前所在的tab为基准，关闭其他标签，而ng-alain的关闭标签，是以当前被选中的tab为基准。
