### ISSUE TITLE
ArrayWidget的path在searchProperty无法找到正确的formProperty

### ISSUE THREAD

**Issue by zd5043039119** [ng-alain/ng-alain#991]
- ng-alain version: latest
- Angular version: 7.1.4

## 【必填项】重现链接，Reproduction link

https://stackblitz.com/edit/ng-alain-setup-ejp5ek

## 重现步骤，Steps to reproduce
1.增加一个节点,在名称内添加任意内容,console可见
/product/1/name
undefined
true
2.再增加一个节点,还是在第一个名称内添加内容
/product/1/name
Error: Object too large to inspect. Open your browser console to view.
true
3.删除所有节点再添加一个几点
/product/3/name
undefined
false

问题1: tick是从1开始计算,但是searchProperty是用的是array的index来判断,从0开始,会导致从searchProperty找不到正确的节点
问题2: tick只增加不减少,但是searchProperty时用的是array的index来判断,所以出现删除后可能会再也无法找到正确的节点

在validate下可以不从root开始查找,但是实际场景可能出现this.sf.rootProperty.searchProperty的应用场景,并且通过操作节点记下path,不正确的path导致无法找到正确的节点

建议:是否对于Array类型的property在可以有唯一的id,然后通过array的find唯一的id来进行searchProperty

**Comment by cipchk** [comment]
是的，如果你需要我建议根据 `parent` 属性来获取数组父属性，并通过 `properties` 来获取当前的清单，此时的下标是完整的。

`tick` 算是一个缺陷问题，但并不会影响特别性的使用，暂时不考虑修复它。
