### ISSUE TITLE
希望能出一个方法来刷新动态表单里面类似select等组件的enum值

### ISSUE THREAD

**Issue by huangxiuqi** [ng-alain/ng-alain#992]
没有找到直接的方法能修改enum的值，希望能加一个方法，或者告知一种便捷的方法来修改enum

**Comment by xingkoo** [comment]
仔细看手册。有刷新表单结果的方法。

**Comment by huangxiuqi** [comment]
> 仔细看手册。有刷新表单结果的方法。

除了refreshSchema还没有找到其他的方法，但是refreshSchema会重置表单的值，form的源码也看了下，没什么思路，还望指点一下

**Comment by huangxiuqi** [comment]
> 仔细看手册。有刷新表单结果的方法。

好像在asyncData里面用Subject也能实现，但是这种方法有点繁琐，所以希望能调一个方法直接修改enum

**Comment by xingkoo** [comment]
重置之前获取一下当前表单值。重置后重新赋值回去。

**Comment by its404** [comment]
这样能实现，但感觉并不是很理想。
```
this.currentFormData = this.sf.value;
this.sf.refreshSchema();
this.record = this.currentFormData;
```

**Comment by cipchk** [comment]
事实上我们也总希望一个简单的事可以把数据做变更，但事实上这很困难，绝大部分内置小部件数据源都有异步源，他并不是只靠 `enum` 来加载数据，不同的 `enum` 从 JSON Schema 来说可以视为不同的 JSON Schema，如果你的数据是不确定的，可以在确定数据已经加载以后再进行初始化。

**Comment by its404** [comment]
@cipchk ，当前的dynamic form和widgets已经相当灵活，好用了:thumbsup: 后续再慢慢不断完善就好。

我今天的需求是个典型的级联select，通过第一个select选择来刷新第二个select的option，我第一反应是用`asyncData`，但我试了试，更新了第二个select的`asyncData`之后，没有办法触发option的刷新，最后走了`refreshSchema`的办法。

**Comment by cipchk** [comment]
级联（例如：所在地、业务分类等等）最好的方式是将你要级联的部分做成小部件，可参考自定义小部件文档。

**Comment by its404** [comment]
感谢，我后边看一下。

**Comment by zd5043039119** [comment]
@its404 级联有Cascader组件,如果一定要用多个Select的话可以在第一个Select的validator或者change里面调用
```javascript
form.searchProperty('***').resetValue(null, false);
```
或者
```javascript
form.searchProperty('***').widget.reset(value);
```
这都会触发第二个Select的asyncData来更新options

可参考 https://stackblitz.com/edit/ng-alain-setup-1s3aq9

**Comment by tsun424** [comment]
@zd5043039119 , 框架提供的级联组件我看到了，但我们的设计想要多个Select，我现在第一个Select选完，需要改变第二个Select的asyncData，然后再触发option更新，你说这个方法我稍后试一下，感觉应该是可以的。谢谢！

**Comment by xingkoo** [comment]
最早之前同样碰到了这个问题。我使用了一个极简单的方式来解决这个问题。

例如：
    现有 **组件A** 和 **组件B**。通过选择**组件A**的值。不决定**组件B**的备选列表。

1、**组件B**动态加载备选数据。在此操作中，当**组件B**被完成加载后，即可动态获取备选列表。
2、针对**组件B**，使用 ````ui```` 属性中的 ````visibleIf````属性来监听一个**X**，决定是否显示该组件。
3、针对**组件A**，监听**change**事件。此时，通过设置**标识X**为false的方式，来达到在DOM中移除**组件B**的效果。然后再重新设置**标识X**。让**组件B**重新载入到DOM中。
4、**组件B**被再次加载后，重新加载备选列表。

可变相达到动态刷新组件B的值的效果。

**Comment by its404** [comment]
@zd5043039119 感谢你的建议，我最后把reset放到第一个Select的change里边了，我测试发现放validator有的时候会由于验证调用导致第二个option多余刷新。
下边是我的样例代码，给有类似场景需求的同学们参考。

```
$targetType: {
      widget: 'select',
      change: (item: number) => {
          this.currentTargetType = item;
          this.sf.getProperty('/target').resetValue(null, false);
    },
},
$target: {
    widget: 'select',
    notFoundContent: 'Not Found',
    asyncData: () => {
        return this.service.getTargetOptions(
        this.currentTargetType
        );
    },
},
```

**Comment by cipchk** [comment]
@its404 这不算多余的刷新，每次 reset 都会导致异步的触发；数据与缓存事实上并不冲突，若你请求的数据属于一些字典类的，建议增加一层缓存机制，这一点很容易通过HTTP拦截器实现。

**Comment by its404** [comment]
@cipchk ，我计划着加缓存呢，新项目，逐渐搭建完善中，感谢。

**Comment by huangxiuqi** [comment]
@zd5043039119 方法很好用，
https://stackblitz.com/edit/ng-alain-setup-nwsqqe?file=src/app/app.component.ts   
这是使用Subject更新option的例子，稍微麻烦一些，到也是一个方法，

**Comment by huangxiuqi** [comment]
@cipchk  是我对asyncData的理解不够，想的有些简单了，感谢大佬的解释

**Comment by xuewlw** [comment]
> @zd5043039119 感谢你的建议，我最后把reset放到第一个Select的change里边了，我测试发现放validator有的时候会由于验证调用导致第二个option多余刷新。
> 下边是我的样例代码，给有类似场景需求的同学们参考。
> 
> ```
> $targetType: {
>       widget: 'select',
>       change: (item: number) => {
>           this.currentTargetType = item;
>           this.sf.getProperty('/target').resetValue(null, false);
>     },
> },
> $target: {
>     widget: 'select',
>     notFoundContent: 'Not Found',
>     asyncData: () => {
>         return this.service.getTargetOptions(
>         this.currentTargetType
>         );
>     },
> },
> ```
请教一下 你的target首次载入时 如何根据targetType值 形成自己的option集合 也就是在首次载入target中 如何获取targetType的值 也形成自己的option集合
