### ISSUE TITLE
关于STData的状态更新

### ISSUE THREAD

**Issue by devsharper** [ng-alain/ng-alain#996]
- ng-alain version: 7.0.3

在代码中修改STData的.checked值，控制checkbox或radio选中某一行。在7.0.3版本中，修改.checked属性后必须调用 st.reload() 才能将选中状态反映到页面上，而调用 st.reload 会触发一次 type为pi的change事件。type为pi的change一般用于翻页，调用后端服务获取数据，重新绑定表格。结果就是本来只是想选中一行，却导致表格整个刷新了，之前设定的checked值，也就是选中状态，又被刷没了……这里的逻辑有点问题。

还没时间仔细看源代码，不知道有没有表达清楚。

在以前的版本中，设定.checked值后无需调用st.reload()即可立即生效，7.0.3版新出现的这个问题

**Comment by devsharper** [comment]
@cipchk 应该是所有STData属性的双向绑定都失效了，设置.checked页面没反应，页面点击checkbox或radio，.checked属性也不变。
其他属性也一样，通过ng-template把任意一个boolean类型的属性绑定到switch上，也是一样的问题，双向绑定都不起作用

**Comment by devsharper** [comment]
@cipchk 补充重现链接

https://stackblitz.com/edit/ng-alain-setup-5pfuwr

**Comment by cipchk** [comment]
原因请参考：[数据修改后页面为什么没有更新](https://ng-alain.com/docs/faq/en#%E6%95%B0%E6%8D%AE%E4%BF%AE%E6%94%B9%E5%90%8E%E9%A1%B5%E9%9D%A2%E4%B8%BA%E4%BB%80%E4%B9%88%E6%B2%A1%E6%9C%89%E6%9B%B4%E6%96%B0]

以上重现可以改为：

```ts
    this.data.find(item => item.id === 1).checked = true;
    this.data = [ ...this.data ];
```
