### ISSUE TITLE
reuse-tab如何实现菜单可重复打开

### ISSUE THREAD

**Issue by s641135196** [ng-alain/ng-alain#998]
尝试用过下面方法都不行。 后面的queryparams参数变化都只会在同个选项卡打开 
```javascript
this.route.navigateByUrl('/workorder/workorder-operate?id=6');
<button routerLink="/workorder/workorder-operate">Go to sidekicks</button>
 this.menuService.openedByUrl('/workorder/workorder-operate?a=6',false)
```

我看到有类似的issue,试了也不行。 [https://github.com/ng-alain/ng-alain/issues/839](url)  我在Menu api中没看到multi参数。我也在Menu增加过些参数也不行。 
请问怎么重复打开了，相当就算URL完全一样也可以打开多选项卡。

**Comment by cipchk** [comment]
`reuse-tab` 只认 URL 的 path 部分，会忽略 QueryString 参数；路由参数可以支持 `/workorder/workorder-operate/:id` 来解决上述问题。
